Repository island-is/island.is, pull requests merged in 2021-08, with the labels that each got.

#4592 feat(sn): adding ship location and other textbox
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/lib/messages/accidentLocation.ts
  libs/application/templates/accident-notification/src/lib/messages/fishingLocationAndPurpose.ts
  libs/application/templates/accident-notification/src/lib/messages/index.ts
  libs/application/templates/accident-notification/src/types/index.ts
  libs/application/templates/accident-notification/src/utils/fishermanUtils.spec.ts
  libs/application/templates/accident-notification/src/utils/fishermanUtils.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isFishermanAccident.spec.ts
  libs/application/templates/accident-notification/src/utils/isFishermanAccident.ts
Labels: automerge

#4612 feat(an): On behalf of juridical person flow
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/accidentType.ts
  libs/application/templates/accident-notification/src/lib/messages/index.ts
  libs/application/templates/accident-notification/src/lib/messages/injuredPerson.ts
  libs/application/templates/accident-notification/src/lib/messages/injuredPersonInformation.ts
  libs/application/templates/accident-notification/src/lib/messages/juridicalPerson.ts
  libs/application/templates/accident-notification/src/utils/getAccidentTypeOptions.spec.ts
  libs/application/templates/accident-notification/src/utils/getAccidentTypeOptions.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isHomeActivitiesAccident.spec.ts
  libs/application/templates/accident-notification/src/utils/isReportingOnBehalfOfEmployee.spec.ts
  libs/application/templates/accident-notification/src/utils/isReportingOnBehalfOfEmployee.ts
Labels: automerge

#4613 feat(an): Sports club employee hindrance
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/lib/messages/sportsClubInfo.ts
  libs/application/templates/accident-notification/src/types/index.ts
  libs/application/templates/accident-notification/src/utils/getWorkplaceData.spec.ts
Labels: automerge

#4618 fix: 08-05-2021 yarn audit
  package.json
  yarn.lock
Labels: automerge

#4582 fix(crc): change prefix for correct template's name
  libs/application/templates/family-matters/children-residence-change/src/dataProviders/NationalRegistryProvider.ts
Labels: automerge

#4531 feat(judicial-system): Add the ability to extend investigation cases
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#4614 chore(an): Data schema now up to date
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
Labels: automerge

#4624 feat(an): Attachments update
  libs/application/templates/accident-notification/src/fields/FormOverview/ValueLine.tsx
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/types/index.ts
Labels: automerge

#4626 feat(an): Added work machine data to overview
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/lib/messages/overview.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isMachineRelatedAccident.spec.ts
  libs/application/templates/accident-notification/src/utils/isMachineRelatedAccident.ts
Labels: automerge

#4632 fix(core): 08-11-2021 yarn audit
  package.json
  yarn.lock
Labels: automerge

#4615 refactor: split timeline components
  libs/application/templates/parental-leave/src/fields/EditPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/index.tsx
  libs/application/templates/parental-leave/src/fields/components/SummaryTimeline/SummaryTimeline.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/Chart.treat.ts
  libs/application/templates/parental-leave/src/fields/components/Timeline/Chart.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/Panel.treat.ts
  libs/application/templates/parental-leave/src/fields/components/Timeline/Panel.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/Timeline.treat.ts
  libs/application/templates/parental-leave/src/fields/components/Timeline/Timeline.tsx
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#4635 fix(hi): Change codeowners
  .github/CODEOWNERS
Labels: automerge

#4410 feat(hi): Rework prerequisite modal to a screen.
  libs/application/templates/health-insurance/src/constants.ts
  libs/application/templates/health-insurance/src/fields/ErrorModal/ErrorModal.treat.ts
  libs/application/templates/health-insurance/src/fields/ErrorModal/ErrorModal.tsx
  libs/application/templates/health-insurance/src/fields/InformationRetrieval/InformationRetrieval.treat.ts
  libs/application/templates/health-insurance/src/fields/InformationRetrieval/InformationRetrieval.tsx
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/SummaryItem.treat.ts
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/SummaryItem.tsx
  libs/application/templates/health-insurance/src/fields/Review/FormerInsurance.tsx
  libs/application/templates/health-insurance/src/fields/Review/ReviewAdditionalInfo.tsx
  libs/application/templates/health-insurance/src/fields/Review/StatusAndChildren.tsx
  libs/application/templates/health-insurance/src/fields/index.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/health-insurance/src/forms/PrerequisitesForm.ts
  libs/application/templates/health-insurance/src/forms/messages.ts
  libs/application/templates/health-insurance/src/healthInsuranceUtils.ts
  libs/application/templates/health-insurance/src/hooks/useModalContent.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.spec.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
  libs/application/templates/health-insurance/src/lib/answerValidators.spec.ts
  libs/application/templates/health-insurance/src/lib/answerValidators.ts
  libs/application/templates/health-insurance/src/lib/dataSchema.ts
  libs/application/templates/health-insurance/src/shared/constants.ts
  libs/application/templates/health-insurance/src/types.ts
Labels: automerge

#4627 feat(crc): unhides mocking system
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
  libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
Labels: automerge

#4593 fix(parental-leave): assignee role for the applicant when own employer
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#4591 fix(core): use european date format
  libs/shared/constants/src/lib/date.ts
  libs/shared/form-fields/src/lib/DatePickerController/DatePickerController.spec.tsx
Labels: automerge

#4599 fix(email-service): info log level for message id
  libs/email-service/src/lib/email.service.ts
Labels: automerge

#4334 fix(hi): Update messages in data gathering screen
  libs/application/templates/health-insurance/src/forms/messages.ts
Labels: automerge

#4640 feat(rb): Readme
  SUMMARY.md
  apps/financial-aid/README.md
Labels: automerge

#4668 fix(core): use yarn audit level high until a fix for next lands
  package.json
Labels: automerge

#4643 fix(judicial-system): Investigation Case Signature Fix
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Confirmation/ConfirmationForm.tsx
Labels: automerge

#4645 fix(parental-leave): missing read permission for employer
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#4495 fix(parental-leave): use percentage calculated by VMST api
  apps/application-system/api/src/app/modules/application/utils/validationUtils.ts
  libs/api/domains/application/src/lib/application.service.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.repository.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.service.ts
  libs/application/core/src/types/Fields.ts
  libs/application/core/src/types/Form.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/Duration/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodEndDate/PeriodEndDate.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/hooks/useGetOrRequestEndDates.ts
  libs/application/templates/parental-leave/src/hooks/useGetOrRequestLength.ts
  libs/application/templates/parental-leave/src/hooks/useLazyParentalLeavePeriodLength.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
  libs/application/ui-fields/src/getDefaultValue.ts
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/application/ui-shell/src/components/FormField.tsx
  libs/application/ui-shell/src/components/FormMultiField.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
Labels: automerge

#4671 fix: Set heap space limit when enforcing memory limit in k8s
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/.prettierrc
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/dsl.ts
Labels: automerge

#4636 chore(parental-leave): improve sentry logs
  apps/application-system/form/src/app/App.tsx
  apps/application-system/form/src/routes/Application.tsx
  apps/application-system/form/src/routes/Applications.tsx
  apps/application-system/form/src/routes/AssignApplication.tsx
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/dataProviders/Children/Children.ts
  libs/application/ui-shell/src/components/ErrorBoundary.tsx
  libs/application/ui-shell/src/components/ErrorShell.tsx
  libs/application/ui-shell/src/components/LoadingShell.tsx
  libs/application/ui-shell/src/index.ts
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/lib/FormShell.treat.ts
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/application/ui-shell/src/lib/NotFound.tsx
  package.json
  yarn.lock
Labels: automerge

#4639 fix(financial aid): Fixing comments from testing (dropdown, text labels, filter and formatting)
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-osk/src/components/Header/Header.treat.ts
  apps/financial-aid/web-osk/src/components/Header/Header.tsx
  apps/financial-aid/web-veita/dist/.nx-results
  apps/financial-aid/web-veita/src/components/AdminLayout/AdminLayout.treat.ts
  apps/financial-aid/web-veita/src/components/AdminLayout/AdminLayout.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.treat.ts
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/Files/Files.tsx
  apps/financial-aid/web-veita/src/components/InputModal/InputModal.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/components/TableHeaders/TableHeaders.tsx
  apps/financial-aid/web-veita/src/routes/Application/application.tsx
  apps/financial-aid/web-veita/src/routes/ApplicationsOverview/applicationsOverview.tsx
  apps/financial-aid/web-veita/src/utils/navigation.ts
  libs/financial-aid/shared/src/lib/formatters.ts
Labels: automerge

#4672 feat(judicial-system): Case Life Cycle events
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/modules/auth/auth.module.ts
  apps/judicial-system/api/src/app/modules/case/case.module.ts
  apps/judicial-system/api/src/app/modules/case/case.resolver.ts
  apps/judicial-system/api/src/app/modules/event/event.module.ts
  apps/judicial-system/api/src/app/modules/event/event.service.ts
  apps/judicial-system/api/src/app/modules/event/index.ts
  apps/judicial-system/api/src/app/modules/index.ts
  apps/judicial-system/api/src/environments/environment.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#4649 fix(financial aid): File upload header
  apps/financial-aid/README.md
  apps/financial-aid/backend/src/environments/environment.ts
  apps/financial-aid/web-osk/src/utils/useFileUpload.ts
Labels: automerge

#4652 fix(judicial-system): Audit failed actions
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/court/court.resolver.ts
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/api/src/app/modules/file/file.exception.ts
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.spec.ts
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
Labels: automerge

#4650 feat(financial aid): Checking whether user in web-osk has applied for current month
  apps/financial-aid/README.md
  apps/financial-aid/api/src/app/modules/auth/auth.controller.ts
  apps/financial-aid/api/src/app/modules/user/user.model.ts
  apps/financial-aid/api/src/app/modules/user/user.module.ts
  apps/financial-aid/api/src/app/modules/user/user.resolver.ts
  apps/financial-aid/api/src/app/modules/user/user.service.ts
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/pages/index.tsx
  apps/financial-aid/web-osk/src/components/CancelModal/CancelModal.tsx
  apps/financial-aid/web-osk/src/components/FormContentContainer/FormContentContainer.tsx
  apps/financial-aid/web-osk/src/components/FormFooter/FormFooter.tsx
  apps/financial-aid/web-osk/src/components/FormLayout/FormLayout.tsx
  apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx
  apps/financial-aid/web-osk/src/components/HasApplied/hasApplied.tsx
  apps/financial-aid/web-osk/src/components/Header/Header.tsx
  apps/financial-aid/web-osk/src/components/Login/login.tsx
  apps/financial-aid/web-osk/src/components/LogoHfj/index.tsx
  apps/financial-aid/web-osk/src/components/RadioButtonContainer/RadioButtonContainer.tsx
  apps/financial-aid/web-osk/src/components/UserProvider/UserProvider.tsx
  apps/financial-aid/web-osk/src/components/index.ts
  apps/financial-aid/web-veita/graphql/errorLink.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminLayout/AdminLayout.tsx
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/AidAmountModal/AidAmountModal.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/Files/Files.tsx
  apps/financial-aid/web-veita/src/components/InputModal/InputModal.tsx
  apps/financial-aid/web-veita/src/components/LogoHfj/index.tsx
  apps/financial-aid/web-veita/src/components/Nav/Nav.tsx
  apps/financial-aid/web-veita/src/components/NavigationStatisticsProvider/NavigationStatisticsProvider.tsx
  apps/financial-aid/web-veita/src/components/OptionsModal/OptionsModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/Profile.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/components/TableBody/TableBody.tsx
  apps/financial-aid/web-veita/src/components/TableHeaders/TableHeaders.tsx
  libs/financial-aid/auth/src/lib/auth.module.ts
  libs/financial-aid/auth/src/lib/guards/index.ts
  libs/financial-aid/auth/src/lib/guards/token.guard.ts
  libs/financial-aid/shared/src/lib/types.ts
Labels: automerge

#4675 fix(financial-aid): Fixed an issue with the veita login
  apps/financial-aid/api/src/app/modules/auth/auth.controller.ts
  apps/financial-aid/api/src/app/modules/auth/auth.module.ts
  apps/financial-aid/api/src/environments/environment.ts
Labels: automerge

#4536 feat(island-ui): Add autoComplete prop to Input component
  libs/island-ui/core/src/lib/Input/types.ts
Labels: automerge

#4681 fix(core): Update yarn.lock
  yarn.lock
Labels: automerge

#4617 feat(an): Application confirmation email
  .github/CODEOWNERS
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/config/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/emailGenerators/confirmationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/emailGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/emailGenerators/overviewTemplate.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/index.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/accident-notification/src/lib/messages/overview.ts
  libs/application/templates/accident-notification/src/shared/constants.ts
  libs/application/templates/accident-notification/src/shared/index.ts
Labels: automerge

#4688 feat(web): Add missing children links to services screen nav list
  apps/web/screens/Organization/Services.tsx
Labels: automerge

#4685 feat(auth-api): Add endpoint for info from national registry
  apps/services/auth-api/src/app/app.module.ts
  apps/services/auth-api/src/app/modules/user-profile/national-registry.config.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.module.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/entities/dto/individual-info.dto.ts
  libs/auth-api-lib/src/lib/services/user-profile.service.ts
Labels: automerge

#4693 fix(Regulations/web): API changes making ministry relation optional
  apps/web/components/Regulations/RegulationDisplay.tsx
  apps/web/components/Regulations/RegulationInfoBox.tsx
  apps/web/components/Regulations/RegulationTexts.types.ts
  apps/web/screens/Regulations/RegulationsHome.tsx
Labels: automerge

#4677 feat(financial-aid): Created application filter endpoint
  apps/financial-aid/api/src/app/modules/application/application.resolver.ts
  apps/financial-aid/api/src/app/modules/application/models/applicationFilter.model.ts
  apps/financial-aid/api/src/app/modules/application/models/index.ts
  apps/financial-aid/api/src/app/modules/user/user.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/pages/_app.tsx
  apps/financial-aid/web-veita/src/components/ApplicationFiltersProvider/ApplicationFiltersProvider.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/Nav/Nav.tsx
  apps/financial-aid/web-veita/src/components/NavigationStatisticsProvider/NavigationStatisticsProvider.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/components/TableBody/TableBody.tsx
  apps/financial-aid/web-veita/src/components/TableHeaders/TableHeaders.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  libs/financial-aid/shared/src/lib/types.ts
Labels: automerge

#4684 fix(judicial-system): Improved life cycle event
  apps/judicial-system/api/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/user/user.controller.ts
  apps/judicial-system/backend/test/e2e.spec.ts
Labels: automerge

#4686 feat(judicial-system): Turn autocomplete off
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/LokeCaseNumber/LokeCaseNumber.tsx
  apps/judicial-system/web/src/shared-components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/shared-components/DateTime/DateTime.tsx
Labels: automerge

#4690 feat(judicial-system): N/A option for prosecutor appeal decision
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx
Labels: automerge

#4694 fix(judicial-system): Debounce transition case from SUBMITTED to RECEIVED
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/Overview.tsx
Labels: automerge

#4606 feat(license-service): add generic pkpass verify + for drivers license
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.type.ts
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/service-portal/licenses/src/screens/components/LicenseCards/LicenseCards.tsx
Labels: automerge, deploy-feature

#4678 fix(application-system): for text field without defaultValue, using empty string
  libs/application/ui-fields/src/getDefaultValue.ts
Labels: automerge

#4648 feat(an): in review
  libs/application/templates/accident-notification/src/constants/index.ts
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/fields/InReviewSteps/ReviewSection/ReviewSection.treat.ts
  libs/application/templates/accident-notification/src/fields/InReviewSteps/ReviewSection/ReviewTag.tsx
  libs/application/templates/accident-notification/src/fields/InReviewSteps/ReviewSection/index.tsx
  libs/application/templates/accident-notification/src/fields/InReviewSteps/index.tsx
  libs/application/templates/accident-notification/src/fields/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/forms/InReview.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/accident-notification/src/lib/messages/application.ts
  libs/application/templates/accident-notification/src/lib/messages/inReview.ts
  libs/application/templates/accident-notification/src/lib/messages/index.ts
  libs/application/templates/accident-notification/src/types/index.ts
Labels: automerge

#4687 fix(parental-leave): disable button to add new period when limit of days is already used
  libs/application/templates/parental-leave/src/fields/PeriodEndDate/PeriodEndDate.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/hooks/useDaysAlreadyUsed.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4695 feat(judicial-system): Add position: sticky to form stepper
  apps/judicial-system/web/src/shared-components/PageLayout/PageLayout.treat.ts
  apps/judicial-system/web/src/shared-components/PageLayout/PageLayout.tsx
Labels: automerge

#4692 feat(ctao): implemented confirmation screen
  libs/application/templates/complaints-to-althingi-ombudsman/src/assets/InstitutionIllustration.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ConfirmationScreen/ConfirmationScreen.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/informationToComplainer.ts
Labels: automerge

#4698 feat(judicial-system): Received-by-court notifications
  apps/judicial-system/backend/migrations/20210823112901-update-notification.js
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4673 fix(parental-leave): make the expectedDateOfBirth optional
  libs/api/domains/directorate-of-labour/src/models/parentalLeave.model.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
  libs/clients/vmst/src/clientConfig.yaml
Labels: automerge

#4555 chore(core): add polyfill for intl-locale
  libs/localization/src/lib/polyfills.ts
  package.json
  yarn.lock
Labels: automerge

#4696 fix(parental-leave): allow one month before dob to create a period
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
Labels: automerge

#4689 feat(ctao): Preexisting complaint screen
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintInformation.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/courtAction.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/informationToComplainer.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/preexistingComplaint.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/shared.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/utils.ts
Labels: automerge

#4705 fix(core): Yarn lock file mismatch
  yarn.lock
Labels: automerge

#4701 fix(judicial-system): Contentful namespace cleanup
  apps/judicial-system/web/messages/Core/laws.ts
  apps/judicial-system/web/messages/Core/restrictions.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/confirmation.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepOne.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepTwo.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/demandsForm.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/reportForm.tsx
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/requestedHearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/confirmation.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/rulingStepOne.tsx
  apps/judicial-system/web/messages/RestrictionCases/Court/rulingStepTwo.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/reportForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/requestedHearingArrangementsForm.ts
Labels: automerge

#4708 fix(judicial-system): Adds a migration dependency to be able to modify enum types
  apps/judicial-system/backend/esbuild.json
Labels: automerge

#4625 feat(an): Illustrated radio button
  libs/application/core/src/types/Fields.ts
  libs/application/templates/accident-notification/src/assets/WorkTypeIllustration.tsx
  libs/application/templates/accident-notification/src/assets/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/island-ui/core/src/lib/RadioButton/RadioButton.treat.ts
  libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx
  libs/shared/form-fields/src/lib/RadioController/RadioController.tsx
Labels: automerge

#4682 fix(api-domains-cms): Fix error when encountering draft covid pages
  libs/cms/src/lib/models/adgerdirPage.model.ts
Labels: automerge

#4703 fix(judicial-system): Prefill court date in investigation cases
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
Labels: automerge

#4710 feat(services-endorsements-api): Access control update
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/src/app/app.module.ts
  apps/services/endorsements/api/src/app/guards/accessGuard/access.decorator.ts
  apps/services/endorsements/api/src/app/guards/accessGuard/access.enum.ts
  apps/services/endorsements/api/src/app/guards/accessGuard/access.guard.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/closeEndorsementList/seed.js
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/findOneEndorsementList/seed.js
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/openEndorsementList/openEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/openEndorsementList/seed.js
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/pipes/endorsementListById.pipe.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/pipes/isEndorsementListOwnerValidation.pipe.ts
  apps/services/endorsements/api/src/environments/environment.ts
  apps/services/endorsements/api/test/environment.jest.ts
  apps/services/endorsements/api/types/index.d.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/application/templates/party-application/src/lib/messages.ts
  libs/application/templates/party-letter/src/lib/messages.ts
Labels: automerge

#4713 feat(judicial-system): Prosecutor court date email improvements
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#4715 fix(ui): enable background blue calendar
  libs/island-ui/core/src/lib/DatePicker/DatePicker.treat.ts
Labels: automerge

#4712 feat(judicial-system): Autofill conclusion with prosecutorDemands if case is accepted
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
Labels: automerge

#4719 fix(license-service): strip dash from SmartSolution nationalId
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
Labels: automerge, high priority

#4716 feat(judicial-system): Adds reference to rettarvorslugatt in prosecutor sms
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#4711 fix(parental-leave): remove the percentage from the slider duration
  libs/application/templates/parental-leave/src/fields/Duration/Duration.treat.ts
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
Labels: automerge, high priority

#4707 feat(judicial-system): Open case on overview for prosecutors if case is SUBMITTED or RECEIVED
  apps/judicial-system/web/src/routes/Shared/Requests/Requests.tsx
Labels: automerge

#4691 feat(an): Reviewer token
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/emailGenerators/assignReviewerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/emailGenerators/index.ts
Labels: automerge

#4646 feat: send our payment id to fjs
  apps/application-system/api/src/app/modules/payment/payment.service.ts
  libs/clients/payment/src/lib/payment.type.ts
Labels: automerge

#4717 chore(driving-license-client): api client update
  libs/clients/driving-license/src/clientConfig.json
Labels: automerge

#4718 chore(application-system-payment): updating code owners for a payment related part of the application-system-api
  .github/CODEOWNERS
Labels: automerge

#4720 fix(judicial-system): Hearing arrangements popup copy change
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#4721 fix(judicial-system): Request PDF copy update
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
Labels: automerge

#4725 fix(crc): hides mocking implementation.
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
  libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
Labels: automerge

#4727 fix(judicial-system): Fixes receive case by court
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
Labels: automerge

#4724 fix(crc): Hides mocking implementation
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.service.ts
  libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
Labels: automerge

#4653 feat(Pdpp): changing charge type to string
  libs/api/domains/payment-schedule/src/lib/graphql/models/chargeType.model.ts
  libs/application/templates/public-debt-payment-plan/src/fields/PrerequisitesErrorModal/PrerequisitesErrorModal.tsx
  libs/application/templates/public-debt-payment-plan/src/lib/paymentPlanUtils.spec.ts
  libs/application/templates/public-debt-payment-plan/src/lib/paymentPlanUtils.ts
  libs/clients/payment-schedule/src/lib/types/debtSchedules.type.ts
  libs/clients/payment-schedule/src/lib/types/deptCharge.enum.ts
Labels: automerge

#4679 feat(service-portal): allow dynamic routes in service-portal
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/SubNavItem.tsx
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  apps/service-portal/src/store/actions.ts
  apps/service-portal/src/store/store.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/finance/src/index.ts
Labels: automerge

#4465 feat(appication-system-api): Opening for acess over X-Road
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#4730 fix(judicial-system): Fixes issues with court date notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#4519 fix(web): Fix event slice styling
  apps/web/components/Organization/Slice/EventSlice/EventSlice.treat.ts
  apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx
Labels: automerge

#4733 fix(web): Fix event slice styles
  apps/web/components/Organization/Slice/EventSlice/EventSlice.treat.ts
  apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx
Labels: automerge

#4735 feat(judicial-system): Unhide Investigation Cases on Staging
  apps/judicial-system/api/infra/judicial-system-api.ts
  charts/judicial-system/values.staging.yaml
Labels: automerge

#4728 fix(web): Add open data sub page to cms
  apps/web/components/Charts/ChartsCard/ChartsCard.tsx
  apps/web/components/Charts/MixedChart/MixedChart.tsx
  apps/web/components/Charts/SimpleBarChart/SimpleBarChart.tsx
  apps/web/components/Charts/SimpleLineChart/SimpleLineChart.tsx
  apps/web/components/Charts/SimplePieChart/SimplePieChart.tsx
  apps/web/components/Charts/charts.treat.ts
  apps/web/components/Charts/sharedChartComponents.tsx
  apps/web/components/Charts/utils.tsx
  apps/web/components/StatisticsCardsSection/StatisticsCardsSection.tsx
  apps/web/screens/OpenData/OpenData.tsx
  apps/web/screens/OpenDataSubPage/OpenDataSubPage.tsx
  apps/web/screens/OpenDataSubPage/data.js
  apps/web/screens/queries/OpenDataPage.ts
  apps/web/screens/queries/OpenDataSubpage.ts
  apps/web/screens/queries/index.tsx
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getOpenDataSubpage.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/graphCard.model.ts
  libs/cms/src/lib/models/openDataPage.model.ts
  libs/cms/src/lib/models/openDataSubpage.model.ts
Labels: automerge

#4731 feat(application-system-api): add internal ingress for api from x-road
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#4741 fix(services-search-indexer): Reduce bulk import chunk size
  libs/content-search-toolkit/src/services/elastic.service.ts
Labels: automerge

#4744 fix(endorsement-api): fixing TLS issue with SOFFIA endpoint
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#4746 fix(endorsement-api): fixing TLS issue with SOFFIA endpoint (#4744)
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#4777 chore(codeowners): making @island-is/kosmos-kaos own the driving-license api domain
  .github/CODEOWNERS
Labels: automerge

#4783 fix(application-template-driving-assessment): fixing an undefined value in the student lookup
  libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx
Labels: automerge

#4778 fix(judicial-system): Disables editing of the court case number until the case has been submitted to court
  apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
Labels: automerge

#4784 feat(financial-aid): Applicant timeline and comment section
  apps/financial-aid/backend/src/app/modules/applicationEvent/applicationEvent.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminLayout/AdminLayout.treat.ts
  apps/financial-aid/web-veita/src/components/CommentSection/CommentSection.treat.ts
  apps/financial-aid/web-veita/src/components/CommentSection/CommentSection.tsx
  apps/financial-aid/web-veita/src/components/History/History.treat.ts
  apps/financial-aid/web-veita/src/components/History/History.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  apps/financial-aid/web-veita/src/routes/Application/application.tsx
  apps/financial-aid/web-veita/src/routes/Login/login.tsx
  apps/financial-aid/web-veita/src/styles.css
Labels: automerge

#4785 fix(application-template-driving-assessment): fixing an undefined value
  libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx
Labels: automerge

#4782 chore(application-system-api): renaming the ingress host for application payment callback
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#4760 fix(parental-leave): application info were missing from review screen
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/ui-components/src/components/DataValue/DataValue.treat.ts
  libs/application/ui-components/src/components/DataValue/DataValue.tsx
  libs/application/ui-components/src/components/ReviewGroup/ReviewGroup.treat.ts
  libs/application/ui-components/src/components/ReviewGroup/ReviewGroup.tsx
Labels: automerge

#4779 chore(application-templates-driving-license): Remove unused code
  libs/application/templates/driving-license/src/dataProviders/EntitlementTypesProvider.ts
  libs/application/templates/driving-license/src/dataProviders/PenaltyPointsProvider.ts
  libs/application/templates/driving-license/src/dataProviders/RequiredResidenceProvider.ts
  libs/application/templates/driving-license/src/dataProviders/index.ts
Labels: automerge

#4786 fix(judicial-system): Remove strings from Contentful
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/messages/requestPdf.ts
Labels: automerge

#4767 feat(ctao): Added alert to court-action screen
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/courtAction.ts
Labels: automerge

#4757 chore(parental-leave): show VMST errors when happening
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/fields/Duration/Duration.treat.ts
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/fields/PeriodEndDate/PeriodEndDate.tsx
  libs/application/templates/parental-leave/src/hooks/useGetOrRequestEndDates.ts
  libs/application/templates/parental-leave/src/hooks/useGetOrRequestLength.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4776 feat(driving-license): allowing the quality photo provider to provide no image
  libs/api/domains/driving-license/src/lib/graphql/models/qualityPhoto.model.ts
  libs/application/templates/driving-license/src/dataProviders/QualityPhotoProvider.ts
  libs/application/templates/driving-license/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#4789 fix(judicial-system): Request PDF
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
Labels: automerge

#4791 fix(web): Open data scroll functionality
  apps/web/components/Charts/ChartsCard/ChartsCard.treat.ts
  apps/web/components/Charts/ChartsCard/ChartsCard.tsx
  apps/web/screens/OpenData/OpenData.treat.ts
  apps/web/screens/OpenData/OpenData.tsx
Labels: automerge

#4739 feat(judicial-system): Create casefiles pdf
  apps/judicial-system/backend/src/app/formatters/casefilesPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/index.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  package.json
  yarn.lock
Labels: automerge

#4775 feat(ctao): Overview edit functionality
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplainedFor.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintInformation.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/overview.ts
Labels: automerge

#4790 fix(service-portal): Minor css layout fixes
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.treat.ts
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/index.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: automerge

#4750 chore(judicial-system): Strict ts in backend
  apps/judicial-system/backend/src/app/formatters/casefilesPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/dto/transitionCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/signatureConfirmation.response.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createPresignedPost.dto.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/models/deleteFile.response.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/presignedPost.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/signedUrl.model.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/sendNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/models/notification.model.ts
  apps/judicial-system/backend/src/app/modules/notification/models/sendNotification.resopnse.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/user/dto/createUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/backend/src/app/sequelizeConfig.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/backend/test/setup.ts
  apps/judicial-system/backend/tsconfig.json
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#4795 fix(fa): Updates env
  apps/financial-aid/api/src/environments/environment.ts
Labels: automerge

#4781 feat(delegation): revamp ux for datepicker in access control
  libs/service-portal/settings/access-control/src/screens/Access/components/AccessItem/AccessItem.treat.ts
  libs/service-portal/settings/access-control/src/screens/Access/components/AccessItem/AccessItem.tsx
Labels: automerge

#4769 fix(judicial-system): Run e2e in pipe
  apps/judicial-system/web-e2e/cypress.json
  apps/judicial-system/web-e2e/src/fixtures/case.json
  apps/judicial-system/web-e2e/src/fixtures/confirmCase.json
  apps/judicial-system/web-e2e/src/fixtures/confirmedCaseJudge.json
  apps/judicial-system/web-e2e/src/fixtures/confirmingCaseJudge.json
  apps/judicial-system/web-e2e/src/fixtures/judgeUsers.json
  apps/judicial-system/web-e2e/src/integration/Judge/confirmation.spec.ts
  apps/judicial-system/web-e2e/src/integration/Judge/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Judge/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Judge/rulingStepOne.spec.ts
  apps/judicial-system/web-e2e/src/integration/Judge/rulingStepTwo.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/createCustodyPetition.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/stepFour.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/stepThree.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/stepTwo.spec.ts
  apps/judicial-system/web-e2e/src/integration/Shared/requests.spec.ts
  apps/judicial-system/web-e2e/src/integration/Shared/signedVerdictOverview.spec.ts
  workspace.json
Labels: automerge

#4787 feat(an): health insurance check
  libs/api/domains/health-insurance/src/lib/graphql/dto/getIsHealthInsuredInput.ts
  libs/api/domains/health-insurance/src/lib/graphql/dto/index.ts
  libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
  libs/api/domains/health-insurance/src/lib/healthInsurance.service.ts
  libs/api/domains/health-insurance/src/lib/soap/healthInsuranceAPI.ts
  libs/application/templates/accident-notification/src/fields/DateOfAccident/index.tsx
  libs/application/templates/accident-notification/src/fields/FieldAlertMessage/index.tsx
  libs/application/templates/accident-notification/src/fields/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm.ts
  libs/application/templates/accident-notification/src/hooks/useLazyIsHealthInsured.ts
  libs/application/templates/accident-notification/src/hooks/useLazyQuery.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/utils/isHealthInsured.ts
Labels: automerge, deploy-feature

#4797 fix(driving-license-assessment-submission): fixing missing env vars and error checking
  apps/application-system/api/infra/application-system-api.ts
  apps/application-system/api/src/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
Labels: automerge

#4800 fix(judicial-system): Add exlanation text for when create Audur case button is diabled in Contentful
  apps/judicial-system/web/messages/Core/courtCaseNumber.ts
  apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
Labels: automerge

#4799 feat(parental-leave): Be able to edit application when waiting for an employer to be assigned
  libs/application/core/src/lib/messages.ts
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/ui-components/src/components/ReviewGroup/ReviewGroup.tsx
Labels: automerge

#4805 chore(parental-leave): Change minimum months from 1 to 0.5
  libs/application/templates/parental-leave/src/config.ts
Labels: automerge

#4802 fix(judicial-system): PDF fixes
  apps/judicial-system/backend/migrations/20210831141153-update-case.js
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/shared-components/InfoCard/InfoCard.tsx
Labels: automerge
