Repository island-is/island.is, pull requests merged in 2021-06, with the labels that each got.

#3978 fix(web): Stafraent Island page - minor fixes
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
  apps/web/components/Organization/Slice/TimelineSlice/Event.treat.ts
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.treat.ts
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
  apps/web/screens/queries/fragments.ts
  libs/api/domains/cms/src/lib/environments/environment.ts
  libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
  libs/api/domains/cms/src/lib/models/timelineSlice.model.ts
  libs/island-ui/core/src/lib/Link/Link.tsx
Labels: automerge

#3967 feat(web): Add footers for Sjukratryggingar and Utlendingastofnun
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.treat.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.treat.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/index.ts
Labels: automerge

#4030 fix(web): Add missing features and fixes to Stafraent page
  apps/web/components/MailingListSignup/MailingListSignup.tsx
  apps/web/components/Organization/Slice/MailingListSignupSlice/MailingListSignupSlice.tsx
  apps/web/components/Organization/Slice/OrganizationSlice.tsx
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
  apps/web/components/Organization/Slice/TimelineSlice/Event.treat.ts
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.treat.ts
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
  apps/web/components/Organization/index.ts
  apps/web/components/real.ts
  apps/web/screens/Organization/Home.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/isValidEmail.ts
  libs/api/domains/cms/src/lib/environments/environment.ts
  libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
  libs/api/domains/cms/src/lib/models/timelineSlice.model.ts
  libs/island-ui/contentful/src/lib/ContactUs/ContactUs.tsx
  libs/island-ui/contentful/src/lib/TellUsAStoryForm/TellUsAStoryForm.tsx
  libs/island-ui/core/src/lib/Link/Link.tsx
Labels: automerge

#4031 build(Financial-aid): Added robin hood to the code owners file.
  .github/CODEOWNERS
  apps/financial-aid/.gitkeep
  libs/financial-aid/.gitkeep
Labels: automerge

#4021 fix(parental-leave): don't use title on action card for now
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
Labels: automerge

#4033 chore(gjafakort): Removing configcat configuration
  apps/gjafakort/api/src/environments/environment.ts
  apps/gjafakort/api/src/services/versionConfiguration.ts
Labels: automerge

#4034 fix(bundler): Add pdfkit and color* to externals
  apps/application-system/api/esbuild.json
  apps/judicial-system/backend/esbuild.json
Labels: automerge

#3996 feat(auth): support space separated scopes
  apps/application-system/api/test/setup.ts
  libs/auth-nest-tools/src/lib/auth.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/nest/audit/src/lib/audit.service.spec.ts
Labels: automerge

#4029 fix(serve): Temporary fix for nx serve for express apps
  package.json
  yarn.lock
Labels: automerge

#4038 fix(ads-backend): Add missing color* externals
  apps/air-discount-scheme/backend/esbuild.json
Labels: automerge

#4043 fix(core): resolve ws dependency to a newer version
  package.json
  yarn.lock
Labels: automerge

#4036 fix(gjafakort-application): Add sequelize assets
  workspace.json
Labels: automerge

#4042 fix(api): use XROAD_CLIENT_ID for national registry
  apps/api/src/app/environments/environment.ts
Labels: automerge

#4039 fix(parental-leave): avoid duplicated periods and define default value of spouse allowance
  libs/application/templates/parental-leave/src/hooks/useApplicationAnswers.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/parentalLeaveUtils.ts
  libs/application/ui-components/src/components/RadioValue/RadioValue.tsx
Labels: automerge, deploy-feature

#4035 refactor(application-system): provider for header information
  apps/application-system/form/src/app/App.tsx
  apps/application-system/form/src/components/Header.tsx
  apps/application-system/form/src/components/Header/Header.tsx
  apps/application-system/form/src/components/Layout/Layout.tsx
  apps/application-system/form/src/context/InfoProvider.tsx
  apps/application-system/form/src/routes/Application.tsx
  libs/application/core/src/types/Application.ts
  libs/application/ui-shell/src/components/FormField.tsx
  libs/application/ui-shell/src/components/FormRepeater.tsx
  libs/application/ui-shell/src/context/FieldContext.tsx
  libs/application/ui-shell/src/context/HeaderInfoProvider.tsx
  libs/application/ui-shell/src/index.ts
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
Labels: automerge

#4046 fix(crc): children legal residence check
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
  libs/application/templates/family-matters/children-residence-change/src/dataProviders/MockNationalRegistryProvider.ts
Labels: automerge

#3942 fix(parental-leave): Show timeline in employer approval state
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#4048 chore(application-templates-parental-leave): Validate bank account length
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4032 feat(auth-lib): Add delegations from wards
  apps/services/auth-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-api/src/app/modules/delegations/national-registry.config.ts
  apps/services/auth-api/src/app/modules/delegations/rsk.config.ts
  apps/services/auth-api/src/environments/environment.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-public-api/src/app/modules/delegations/national-registry.config.ts
  apps/services/auth-public-api/src/environments/environment.prod.ts
  apps/services/auth-public-api/src/environments/environment.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
  libs/auth-nest-tools/src/index.ts
  libs/auth-nest-tools/src/lib/auth.middleware.ts
  libs/clients/national-registry/v2/src/index.ts
Labels: automerge

#4045 feat(judicial-system): Support multiple courts
  apps/judicial-system/README.md
  apps/judicial-system/api/src/app/modules/court/court.module.ts
  apps/judicial-system/api/src/app/modules/court/court.resolver.ts
  apps/judicial-system/api/src/app/modules/court/court.service.ts
  apps/judicial-system/api/src/app/modules/court/court.spec.ts
  apps/judicial-system/api/src/app/modules/court/dto/createCourtCase.input.ts
  apps/judicial-system/api/src/environments/environment.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/court/court.module.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
  libs/judicial-system/court-client/src/index.ts
  libs/judicial-system/court-client/src/lib/courtClient.module.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4051 chore(core): Updating codeowners for `services/documents`
  .github/CODEOWNERS
Labels: automerge

#4049 feat(auth-admin-web): Add Domains and public api changes
  apps/auth-admin-web/components/Admin/form/DomainCreateForm.tsx
  apps/auth-admin-web/components/Admin/lists/DomainList.tsx
  apps/auth-admin-web/components/Admin/nav/AdminTabNav.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeGroupCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeResourceForm.tsx
  apps/auth-admin-web/components/Resource/lists/ApiScopeGroupList.tsx
  apps/auth-admin-web/entities/common/AdminTab.ts
  apps/auth-admin-web/entities/dtos/api-scope-group.dto.ts
  apps/auth-admin-web/entities/dtos/domain.dto.ts
  apps/auth-admin-web/entities/models/api-scope-group.model.ts
  apps/auth-admin-web/entities/models/domain.model.ts
  apps/auth-admin-web/entities/models/paged-rows.dto.ts
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/pages/admin/domain/[domainName].tsx
  apps/auth-admin-web/pages/admin/domain/index.tsx
  apps/auth-admin-web/pages/admin/index.tsx
  apps/auth-admin-web/services/ResourcesService.ts
  apps/auth-admin-web/styles/_FormLayout.scss
  apps/auth-admin-web/styles/_ListLayout.scss
  apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
  apps/services/auth-api/src/app/modules/grants/grants.controller.ts
  apps/services/auth-public-api/src/app/app.module.ts
  apps/services/auth-public-api/src/app/modules/resources/api-scope.controller.ts
  apps/services/auth-public-api/src/app/modules/resources/api-scope.module.ts
  apps/services/auth-public-api/src/app/modules/translation/translation.controller.ts
  apps/services/auth-public-api/src/app/modules/translation/translation.module.ts
  libs/auth-api-lib/migrations/20210531143042-modify_api-scope-group.js
  libs/auth-api-lib/src/lib/entities/dto/api-scope-group.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/domain.dto.ts
  libs/auth-api-lib/src/lib/entities/models/api-scope-group.model.ts
  libs/auth-api-lib/src/lib/entities/models/domain.model.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
Labels: automerge

#4047 feat(access-control): Setup skeleton for editing an access
  libs/island-ui/core/src/lib/Checkbox/Checkbox.treat.ts
  libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
  libs/service-portal/settings/access-control/src/index.ts
  libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
  libs/service-portal/settings/access-control/src/screens/Access/components/AccessItem/AccessItem.tsx
  libs/service-portal/settings/access-control/src/screens/Access/components/AccessItem/index.ts
  libs/service-portal/settings/access-control/src/screens/Access/components/index.ts
  libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx
  libs/service-portal/settings/access-control/src/screens/AccessControl/components/AccessCard/AccessCard.tsx
  libs/service-portal/settings/access-control/src/screens/AccessControl/components/Accesses/Accesses.tsx
  libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
  libs/shared/form-fields/src/lib/DatePickerController/DatePickerController.tsx
Labels: automerge

#3924 chore(core): split up aranja codeowner teams
  .github/CODEOWNERS
Labels: automerge

#4052 feat(auth-public-api): delegation modifications
  libs/auth-api-lib/migrations/20210602131057-modify_delegations.js
  libs/auth-api-lib/src/lib/entities/dto/delegation-scope.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts
  libs/auth-api-lib/src/lib/entities/models/delegation-scope.model.ts
  libs/auth-api-lib/src/lib/entities/models/delegation.model.ts
  libs/auth-api-lib/src/lib/services/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
Labels: automerge

#4053 fix(ads-backend): Add sequelizerc to assets
  workspace.json
Labels: automerge

#4037 fix(auth-public-api): Move to esbuild
  apps/services/auth-public-api/esbuild.json
  apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-public-api/src/environments/environment.prod.ts
  apps/services/auth-public-api/src/environments/environment.ts
  workspace.json
Labels: automerge

#4055 fix(docs): link to ADR 13
  handbook/technical-overview/adr/README.md
Labels: automerge

#4056 feat(auth-api-lib): Fix delegation find valid custom to
  libs/auth-api-lib/src/lib/services/delegations.service.ts
Labels: automerge

#4044 chore(core): Improving e2e in CI
  scripts/e2e-ci.js
  scripts/schemas.js
  scripts/static-serve.js
  scripts/utils.js
Labels: automerge

#4058 fix(docs): link to root doc
  .nxignore
  README.md
  SUMMARY.md
  apps/services/auth-admin-api/README.md
  apps/services/auth-api/README.md
  apps/web/README.md
  handbook/technical-overview/auth/service-provider-manual/authentication-service-provision.md
  libs/application/templates/README.md
  libs/application/templates/health-insurance/README.md
  libs/application/templates/party-letter/README.md
Labels: automerge

#4057 fix(auth-public-api): Add global prefix
  apps/services/auth-public-api/src/main.ts
Labels: automerge

#4061 fix(judicial-system): Fixes active travel ban text
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
Labels: automerge

#4062 fix(judicial-system): Hides open button from registrars on ruling page
  apps/judicial-system/web/src/routes/Judge/Ruling/StepOne/RulingStepOne.tsx
Labels: automerge

#4067 chore(codeowners): hugsmidjan for service-portal
  .github/CODEOWNERS
Labels: automerge

#4065 chore(application-templates-parental-leave): Update copy in email when application is approved by employer
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#3813 feat(web): Add CTA version for accordion slice
  apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
  apps/web/screens/queries/fragments.ts
  libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
  libs/api/domains/cms/src/lib/models/accordionSlice.model.ts
Labels: automerge

#4073 fix(api): add prefix to authPublicApi url
  apps/api/src/app/environments/environment.ts
Labels: automerge

#4071 fix(web): Organization web hot-fixes
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  libs/api/domains/cms/src/lib/cms.contentful.service.ts
  package.json
  yarn.lock
Labels: automerge

#4075 feat(parental-leave): new checkbox label message
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4068 feat(island-ui): Add zIndex to useBoxStyles
  apps/judicial-system/web/src/shared-components/DropdownMenu/DropdownMenu.tsx
  libs/island-ui/core/src/lib/Box/useBoxStyles.treat.ts
  libs/island-ui/core/src/lib/Box/useBoxStyles.ts
Labels: automerge

#4074 fix(parental-leave): missing tiles and wrong ids
  libs/application/core/src/lib/formBuilders.ts
  libs/application/templates/parental-leave/src/forms/DraftRequiresAction.ts
  libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
  libs/application/templates/parental-leave/src/forms/EditsInReview.ts
  libs/application/templates/parental-leave/src/forms/EditsRequireAction.ts
  libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
  libs/application/templates/parental-leave/src/forms/InReview.ts
  libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
Labels: automerge

#4070 fix(judicial-sytem): Stop current user spam
  apps/judicial-system/web/src/routes/Judge/Confirmation/Confirmation.spec.tsx
  apps/judicial-system/web/src/routes/Judge/Overview/Overview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/DetentionRequests/DetentionRequests.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Login/Login.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/shared-components/Logo/Logo.spec.tsx
  apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.spec.tsx
  apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.tsx
Labels: automerge

#4077 fix(judicial-system): Adds islandis-login refereence to esbuild
  apps/judicial-system/api/esbuild.json
Labels: automerge

#4080 feat(auth-public-api): Feature/fix endpoints
  apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-public-api/src/app/modules/resources/api-scope.controller.ts
  apps/services/auth-public-api/src/app/modules/translation/translation.controller.ts
  apps/services/auth-public-api/src/main.ts
Labels: automerge

#4081 fix(auth-public-api): Fix audience
  apps/services/auth-public-api/src/environments/environment.ts
Labels: automerge

#4079 feat(parental-leave): Show union and pension fund info in employer approval screen
  libs/application/templates/parental-leave/src/fields/EmployerApprovalExtraInformation/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4076 docs: Explain the `extract-strings` script, improve examples
  libs/localization/README.md
Labels: automerge

#4084 fix(auth-public-api): scopes array should be optional
  libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts
Labels: automerge

#4095 fix(application-templates-party-application): Schema generation
  workspace.json
Labels: automerge

#4064 chore(application-templates-parental-leave): Ask for other parent email and update approval process
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/Review/index.tsx
  libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/hooks/useApplicationAnswers.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge

#4096 fix(crc): sort children by age
  apps/application-system/api/src/app/modules/application/files/pdfGenerators/residenceChange.ts
  libs/application/templates/family-matters/children-residence-change/src/fields/components/TransferOverview.tsx
  libs/application/templates/family-matters/core/src/fields/SelectChildren/index.tsx
  libs/application/templates/family-matters/core/src/utils/index.ts
Labels: automerge

#4097 fix(search-indexer): Fix conditional server start
  apps/services/search-indexer/src/main.ts
Labels: automerge

#4091 fix(application-templates-health-insurance): Patch flaky test
  libs/application/templates/health-insurance/src/healthInsuranceUtils.spec.ts
Labels: automerge

#3835 feat(web): Add a multi-line statistics slice
  apps/web/components/Organization/Slice/MultipleStatistics/MultipleStatistics.tsx
  apps/web/components/Organization/Slice/Offices/OfficesSlice.treat.ts
  apps/web/components/Organization/Slice/Offices/OfficesSlice.tsx
  apps/web/components/Organization/Slice/OrganizationSlice.tsx
  apps/web/components/Organization/index.ts
  apps/web/screens/queries/fragments.ts
  libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
  libs/api/domains/cms/src/lib/models/multipleStatistics.model.ts
  libs/api/domains/cms/src/lib/models/offices.model.ts
  libs/api/domains/cms/src/lib/unions/slice.union.ts
Labels: automerge

#4017 feat(services-documents): Add audit logs
  apps/services/documents/src/app/app.module.ts
  apps/services/documents/src/app/modules/document-provider/controllers/organisation.controller.ts
  apps/services/documents/src/app/modules/document-provider/controllers/provider.controller.ts
  apps/services/documents/src/app/modules/document-provider/document-provider.service.ts
  apps/services/documents/src/app/modules/document-provider/e2e/document-provider.spec.ts
  apps/services/documents/src/app/modules/document-provider/utils/authorizationHeader.decorator.ts
  apps/services/documents/src/app/modules/document-provider/utils/nationalId.decorator.ts
  apps/services/documents/src/app/modules/document-provider/utils/tokenUtils.ts
  apps/services/documents/src/environments/environment.ts
Labels: automerge

#4104 fix(core): Fixes security audit errors
  package.json
  yarn.lock
Labels: automerge

#4101 feat(crc): applicant sole custody
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
  libs/application/templates/family-matters/children-residence-change/src/dataProviders/MockNationalRegistryProvider.ts
  libs/application/templates/family-matters/children-residence-change/src/fields/MockData/children.tsx
  libs/application/templates/family-matters/children-residence-change/src/fields/SelectChildren/index.tsx
  libs/application/templates/family-matters/children-residence-change/src/fields/SoleCustodyModal/index.tsx
  libs/application/templates/family-matters/children-residence-change/src/fields/index.ts
  libs/application/templates/family-matters/children-residence-change/src/forms/ChildrenResidenceChangeForm.ts
  libs/application/templates/family-matters/children-residence-change/src/lib/messages/index.ts
  libs/application/templates/family-matters/children-residence-change/src/lib/messages/selectChildren.ts
  libs/application/templates/family-matters/children-residence-change/src/lib/messages/soleCustody.ts
  libs/application/templates/family-matters/core/src/components/ErrorModal/ErrorModal.tsx
  libs/application/templates/family-matters/core/src/fields/SelectChildren/index.tsx
  libs/application/templates/family-matters/core/src/types/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/SelectChildren/index.tsx
Labels: automerge

#4099 chore(web): Remove old Stafraent Island route in english version
  apps/web/pages/en/organizations/stafraent-island/[slug]/index.ts
  apps/web/pages/en/organizations/stafraent-island/index.ts
Labels: automerge

#4041 fix(web): FixedNav according to design
  apps/web/components/FixedNav/FixedNav.treat.ts
  apps/web/components/FixedNav/FixedNav.tsx
Labels: automerge

#4063 feat(access-control): create resolvers for auth-public-api
  apps/api/src/main.ts
  apps/service-portal/src/auth.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
  libs/api/domains/auth/src/index.ts
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/auth.resolver.ts
  libs/api/domains/auth/src/lib/auth.service.ts
  libs/api/domains/auth/src/lib/dto/delegation.input.ts
  libs/api/domains/auth/src/lib/dto/index.ts
  libs/api/domains/auth/src/lib/dto/updateDelegation.input.ts
  libs/api/domains/auth/src/lib/models/authScope.model.ts
  libs/api/domains/auth/src/lib/models/delegation.model.ts
  libs/api/domains/auth/src/lib/models/delegationScope.model.ts
  libs/api/domains/auth/src/lib/models/index.ts
  libs/api/domains/auth/src/lib/resolvers/authScope.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/delegationScope.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/index.ts
  libs/api/domains/auth/src/lib/resolvers/main.resolver.ts
  libs/auth-api-lib/src/lib/entities/dto/delegation-scope.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts
  libs/auth-api-lib/src/lib/entities/models/delegation-scope.model.ts
  libs/auth-api-lib/src/lib/services/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
Labels: automerge

#4106 fix(search-indexer-service): Revert conditional server start fix
  apps/services/search-indexer/src/main.ts
Labels: automerge

#4114 fix(core): Fixes security audit errors
  package.json
  yarn.lock
Labels: automerge

#4115 chore(deps): Enable dependabot pull requests
  .github/dependabot.yml
Labels: automerge

#4112 chore(parental-leave): fix codeowner on vmst api domain
  .github/CODEOWNERS
Labels: automerge

#4102 fix(parental-leave): added tests for utils + minor changes
  libs/api/domains/directorate-of-labour/src/dto/getParentalLeavesEntitlements.input.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/types/Fields.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.ts
  libs/application/templates/parental-leave/src/dataProviders/Children/Children.ts
  libs/application/templates/parental-leave/src/fields/DraftRequiresAction/index.tsx
  libs/application/templates/parental-leave/src/fields/Duration/index.tsx
  libs/application/templates/parental-leave/src/fields/EditPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/fields/EditsRequireAction/index.tsx
  libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/EditsInReviewSteps.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/PaymentsTable.tsx
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/index.tsx
  libs/application/templates/parental-leave/src/fields/Rights/SummaryRights.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/SummaryTimeline.tsx
  libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
  libs/application/templates/parental-leave/src/forms/InReview.ts
  libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/parental-leave/src/hooks/useApplicationAnswers.ts
  libs/application/templates/parental-leave/src/index.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveClientUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/ui-components/src/components/DataValue/DataValue.tsx
  libs/application/ui-fields/src/lib/RadioFormField.tsx
  libs/application/ui-shell/src/components/FormMultiField.tsx
Labels: automerge

#4113 feat(judicial-system): Add an AlertBox to the top of StepOne if the request has been received by the courts
  apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOne.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/CreateDetentionRequest/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/utils/mocks.ts
Labels: automerge

#4094 chore(runtime): Upgrade docker base to 14.17.0
  .github/workflows/push.yml
  package.json
  scripts/ci/Dockerfile
Labels: automerge, deploy-feature

#4107 fix: rename License to EducationLicense in api
  libs/api/domains/education/src/lib/education.service.ts
  libs/api/domains/education/src/lib/education.type.ts
  libs/api/domains/education/src/lib/graphql/license/educationLicense.input.ts
  libs/api/domains/education/src/lib/graphql/license/educationLicense.model.ts
  libs/api/domains/education/src/lib/graphql/license/educationSignedLicense.model.ts
  libs/api/domains/education/src/lib/graphql/license/index.ts
  libs/api/domains/education/src/lib/graphql/main.resolver.ts
Labels: automerge

#4134 chore(judicial-system): update readme
  apps/judicial-system/README.md
Labels: automerge

#4139 feat(judicial-system): Change placeholder text is appeal date pickers on SignedVerdictOverview page
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Accused/AccusedAppealDatePicker.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Prosecutor/ProsecutorAppealDatePicker.tsx
  apps/judicial-system/web/src/shared-components/DateTime/DateTime.tsx
Labels: automerge

#4142 chore: Remove package-lock.json
  package-lock.json
Labels: automerge

#4141 chore(gjafakort): Update heading text for "Ferðagjöfin þín"
  apps/gjafakort/web/i18n/locales/en.json
  apps/gjafakort/web/i18n/locales/is.json
Labels: automerge

#4147 chore(core): Update dockerfile node versions from 14.16 to 14.17
  README.md
  scripts/ci/Dockerfile.cypress
  scripts/ci/Dockerfile.test
Labels: automerge

#4145 fix: add correct License type
  libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
Labels: automerge

#4103 feat(parental-leave): Implement rights code util
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/dataProviders/Children/Children-utils.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/ui-shell/src/components/Screen.tsx
Labels: automerge

#4092 feat(party-application): Bulk upload in party application
  libs/application/templates/party-application/src/fields/BulkUpload/index.tsx
  libs/application/templates/party-application/src/fields/EndorsementList/EndorsementTable.tsx
  libs/application/templates/party-application/src/fields/EndorsementList/index.tsx
  libs/application/templates/party-application/src/fields/EndorsementListSubmission/EndorsementTable.tsx
  libs/application/templates/party-application/src/fields/EndorsementListSubmission/index.tsx
  libs/application/templates/party-application/src/fields/FileUploadDisclaimer/index.tsx
  libs/application/templates/party-application/src/fields/index.ts
  libs/application/templates/party-application/src/forms/CollectEndorsementsForm.ts
  libs/application/templates/party-application/src/graphql/mutations.ts
  libs/application/templates/party-application/src/graphql/queries.ts
  libs/application/templates/party-application/src/lib/dataSchema.ts
  libs/application/templates/party-application/src/lib/messages.ts
  package.json
  yarn.lock
Labels: automerge

#4152 fix(tests): Run tests as current user
  apps/air-discount-scheme/backend/docker-compose.base.yml
  apps/air-discount-scheme/backend/docker-compose.ci.yml
  apps/application-system/api/docker-compose.base.yml
  apps/application-system/api/docker-compose.ci.yml
  apps/gjafakort/application/docker-compose.base.yml
  apps/gjafakort/application/docker-compose.ci.yml
  apps/icelandic-names-registry/backend/docker-compose.base.yml
  apps/icelandic-names-registry/backend/docker-compose.ci.yml
  apps/judicial-system/backend/docker-compose.base.yml
  apps/judicial-system/backend/docker-compose.ci.yml
  apps/reference-backend/docker-compose.base.yml
  apps/reference-backend/docker-compose.ci.yml
  apps/services/auth-api/docker-compose.base.yml
  apps/services/auth-api/docker-compose.ci.yml
  apps/services/documents/docker-compose.base.yml
  apps/services/documents/docker-compose.ci.yml
  apps/services/endorsements/api/docker-compose.base.yml
  apps/services/endorsements/api/docker-compose.ci.yml
  apps/services/party-letter-registry-api/docker-compose.base.yml
  apps/services/party-letter-registry-api/docker-compose.ci.yml
  apps/services/temporary-voter-registry-api/docker-compose.base.yml
  apps/services/temporary-voter-registry-api/docker-compose.ci.yml
  apps/services/user-profile/docker-compose.base.yml
  apps/services/user-profile/docker-compose.ci.yml
  apps/skilavottord/ws/docker-compose.base.yml
  apps/skilavottord/ws/docker-compose.ci.yml
Labels: automerge

#4098 feat(party-letter): Bulk upload
  libs/application/templates/party-letter/src/fields/BulkUpload/index.tsx
  libs/application/templates/party-letter/src/fields/EndorsementList/EndorsementTable.tsx
  libs/application/templates/party-letter/src/fields/EndorsementList/index.tsx
  libs/application/templates/party-letter/src/fields/FileUploadDisclaimer/index.tsx
  libs/application/templates/party-letter/src/fields/index.ts
  libs/application/templates/party-letter/src/forms/CollectEndorsements.ts
  libs/application/templates/party-letter/src/graphql/mutations.ts
  libs/application/templates/party-letter/src/graphql/queries.ts
  libs/application/templates/party-letter/src/lib/dataSchema.ts
  libs/application/templates/party-letter/src/lib/messages.ts
Labels: automerge

#4156 fix(api-domains-endorsement-system): Open endorsement list not working
  libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts
Labels: automerge

#4132 feat: ReadSpeaker webreader on articles
  apps/web/components/Webreader/Webreader.tsx
  apps/web/components/Webreader/config.ts
  apps/web/components/real.ts
  apps/web/screens/Article.tsx
  libs/island-ui/core/src/lib/Breadcrumbs/Breadcrumbs.tsx
Labels: automerge

#4159 fix: Create folder for docker to write terminal results to and give postgres more time to start
  scripts/ci/30_test.sh
  scripts/ci/Dockerfile.test
Labels: automerge, high priority

#4130 fix(parental-leave): Fix and refactor InReview screen steps and status
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/forms/InReview.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#4072 docs: Updating Monitoring Security Server IP addresses in the X-Road documentation
  handbook/technical-overview/x-road/x-road-system-requirements.md
Labels: automerge

#4158 fix(judicial-system): Fixes migration
  apps/judicial-system/backend/migrations/20210608081018-update-case.js
Labels: automerge

#4143 chore(web): Change organization routes from /stofnanir to /s
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/o/[slug]/[subSlug]/index.ts
  apps/web/pages/en/o/[slug]/index.ts
  apps/web/pages/en/o/[slug]/services/index.ts
  apps/web/pages/en/o/index.ts
  apps/web/pages/en/organizations/[slug]/index.tsx
  apps/web/pages/en/organizations/index.tsx
  apps/web/pages/s/[slug]/[subSlug]/index.ts
  apps/web/pages/s/[slug]/frett/[newsSlug]/index.tsx
  apps/web/pages/s/[slug]/frett/index.tsx
  apps/web/pages/s/[slug]/index.ts
  apps/web/pages/s/[slug]/thjonusta/index.ts
  apps/web/pages/s/index.ts
  apps/web/pages/s/stafraent-island/vefthjonustur/[slug]/index.ts
  apps/web/pages/s/stafraent-island/vefthjonustur/index.ts
  apps/web/pages/s/syslumenn/heimagisting/index.ts
  apps/web/pages/s/syslumenn/uppbod/[slug]/index.ts
  apps/web/pages/s/syslumenn/uppbod/index.ts
  apps/web/pages/stofnanir/[slug]/index.tsx
  apps/web/pages/stofnanir/index.tsx
  apps/web/screens/Organization/Services.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
Labels: automerge

#4160 feat(judicial-system): Generates request pdf for r-cases
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
Labels: automerge

#4155 feat(judicial-system): Autofills other restrictions
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/routes/Court/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
Labels: automerge

#4108 fix(crc): autofill phone numbers
  libs/application/templates/family-matters/children-residence-change/src/fields/ContactInfo/index.tsx
  libs/application/templates/family-matters/children-residence-change/src/fields/ContactInfoParentB/index.tsx
  libs/application/templates/family-matters/core/src/components/ContactInfoRow.tsx
  libs/application/templates/family-matters/core/src/utils/dataSchema.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/ContactInfo/index.tsx
Labels: automerge

#4164 feat(auth-admin-web): api scope validation
  apps/auth-admin-web/components/Admin/form/ApiScopeUserCreateForm.tsx
  apps/auth-admin-web/components/Admin/lists/DomainList.tsx
  apps/auth-admin-web/components/Client/form/ClientAllowedScopesForm.tsx
  apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiResourceScopeForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeGroupCreateForm.tsx
  apps/auth-admin-web/components/common/HintBox.tsx
  apps/auth-admin-web/entities/common/Localization.ts
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/pages/admin/domain/[domainName].tsx
  apps/auth-admin-web/styles/App.scss
  apps/auth-admin-web/styles/HintBox.scss
  apps/auth-admin-web/utils/validation.utils.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
Labels: automerge

#4168 chore(content-search-indexer): Add baby articles to nested types in search indexer
  libs/api/domains/cms/src/lib/environments/environment.ts
Labels: automerge

#4163 feat(judicial-system): Add a line divider in the case type dropdown in investigation cases
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4169 feat(judicial-system): Autofill prosecutorOnlySessionRequest
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/shared-components/AccordionItems/CaseFactsAndLegalArgumentsAccordionItem/CaseFactsAndLegalArgumentsAccordionItem.tsx
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
Labels: automerge

#4170 fix(judicial-system): Update investigation case state
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
Labels: automerge

#4146 chore(application-templates-party-application): Swapped node-xlsx for xlsx
  apps/services/party-letter-registry-api/seeders/party-letter-registry.js
  apps/services/temporary-voter-registry-api/seeders/voter-registry.js
  package.json
Labels: automerge

#4167 fix(island-ui): Fix numbering and styles on nested bullet lists within ordered lists.
  libs/island-ui/contentful/src/lib/RichTextRC/RichText.treat.ts
Labels: automerge

#4173 fix(codeowners): Add Party Application Template API Module to Code Owners file
  .github/CODEOWNERS
Labels: automerge

#4174 feat(auth-public-api): Add endpoint for identity resources that can b…
  apps/services/auth-public-api/src/app/app.module.ts
  apps/services/auth-public-api/src/app/modules/resources/identity-resources.controller.ts
  apps/services/auth-public-api/src/app/modules/resources/resources.module.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
Labels: automerge

#4175 fix: Fixed reattachment issues for ReadSpeaker
  apps/web/components/Webreader/Webreader.tsx
Labels: automerge

#4157 feat(judicial-system): Hide booking of accused rights
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20210610130920-update-case.js
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/src/routes/Court/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/shared-components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
  apps/judicial-system/web/src/shared-components/AccordionItems/RulingAccordionItem/RulingAccordionItem.tsx
  apps/judicial-system/web/src/shared-components/HideableText/HideableText.treat.ts
  apps/judicial-system/web/src/shared-components/HideableText/HideableText.tsx
  apps/judicial-system/web/src/shared-components/index.ts
  apps/judicial-system/web/src/utils/Restrictions.ts
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/formatters.ts
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/mutations.ts
  apps/judicial-system/web/src/utils/stepHelper.tsx
  apps/judicial-system/web/src/utils/utils.spec.tsx
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/Eye.tsx
  libs/island-ui/core/src/lib/IconRC/icons/EyeOutline.tsx
  libs/island-ui/core/src/lib/Text/Text.treat.ts
  libs/island-ui/core/src/lib/Text/Text.tsx
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4178 chore(skilavottord): Adding dependency that cannot be js-bundled
  apps/skilavottord/ws/esbuild.json
Labels: automerge

#4179 feat(judicial-system): Display case type on overview screen
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Shared/Requests/ActiveRequests.tsx
  apps/judicial-system/web/src/utils/stepHelper.tsx
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4180 chore(core): Yarn lock updated
  yarn.lock
Labels: automerge

#4182 chore(crc): change heading text
  apps/application-system/api/src/app/modules/application/files/pdfGenerators/residenceChange.ts
Labels: automerge

#4183 fix(crc): children order
  libs/application/templates/family-matters/core/src/utils/index.ts
Labels: automerge

#4189 fix(judicial-system): Update case from DRAFT to SUBMITTED
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/shared-components/HideableText/HideableText.tsx
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
Labels: automerge

#4060 test: Running tests sequentially to avoid potential concurrency issues in the CI
  .github/workflows/pullrequest.yml
  apps/air-discount-scheme/backend/test/setup.ts
  apps/application-system/api/test/setup.ts
  apps/financial-aid/backend/test/setup.ts
  apps/gjafakort/application/test/setup.ts
  apps/icelandic-names-registry/backend/test/setup.ts
  apps/judicial-system/backend/test/setup.ts
  apps/reference-backend/test/setup.ts
  apps/services/auth-admin-api/test/setup.ts
  apps/services/auth-api/test/setup.ts
  apps/services/documents/test/setup.ts
  apps/services/user-profile/test/setup.ts
  scripts/ci/30_test.sh
  scripts/ci/Dockerfile.test
  scripts/ci/_common.sh
Labels: automerge

#4184 feat(web): Add organization content to search engine
  apps/web/screens/Search/Search.tsx
  apps/web/screens/queries/Search.tsx
  libs/api/domains/cms/src/index.ts
  libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts
  libs/api/domains/cms/src/lib/models/organizationSubpage.model.ts
  libs/api/domains/content-search/src/lib/enums/searchableContentTypes.ts
  libs/api/domains/content-search/src/lib/models/searchResult.model.ts
Labels: automerge

#4138 feat(web): Focus Digital Iceland timeline on current month
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
Labels: automerge

#4185 fix(web): Fix organization wrapper grid layout issues
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#4171 feat(services-endorsements-api): Add endorsement list meta field
  .github/CODEOWNERS
  apps/services/endorsements/api/migrations/20210610144917-endorsement-list-meta.js
  apps/services/endorsements/api/seeders/20210325171826-development.js
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementList.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/createEndorsementList/createEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  libs/api/domains/endorsement-system/src/lib/dto/createEndorsementList.input.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsementList.model.ts
  libs/api/domains/party-letter-registry/src/lib/partyLetterRegistry.service.ts
  libs/api/domains/temporary-voter-registry/src/lib/temporaryVoterRegistry.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/party-application/party-application.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/party-letter/party-letter.service.ts
Labels: automerge

#4176 feat(judicial-system): connect to cms
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/web/graphql/httpLink.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/messages/login.ts
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/src/environments/environment.ts
  apps/judicial-system/web/src/routes/Shared/Login/Login.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Login/Login.tsx
  apps/judicial-system/web/src/shared-components/UserProvider/UserProvider.spec.tsx
  libs/api/domains/cms/src/lib/models/districts.model.ts
  libs/api/domains/cms/src/lib/models/featuredArticles.model.ts
  libs/api/domains/cms/src/lib/models/frontpageSlider.model.ts
  libs/api/domains/cms/src/lib/models/lifeEventPage.model.ts
  libs/api/domains/cms/src/lib/models/organization.model.ts
  libs/api/domains/cms/src/lib/models/organizationPage.model.ts
  libs/api/domains/cms/src/lib/models/organizationSubpage.model.ts
  libs/api/domains/cms/src/lib/models/sectionWithImage.model.ts
  libs/api/domains/cms/src/lib/models/tabContent.model.ts
  libs/api/domains/cms/src/lib/models/tellUsAStory.model.ts
  workspace.json
Labels: automerge

#4192 feat(financial-aid): Veita login flow
  apps/financial-aid/api/src/app/modules/auth/auth.controller.ts
  apps/financial-aid/api/src/environments/environment.ts
Labels: automerge

#4190 fix(web): Add redirect for organization subpages
  apps/web/pages/stofnanir/[slug]/[subSlug]/index.tsx
Labels: automerge

#4191 feat(auth-api-lib): Get delegated scopes
  apps/services/auth-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-api/tsconfig.json
  apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/entities/models/delegation-scope.model.ts
  libs/auth-api-lib/src/lib/services/delegation-scope.service.ts
Labels: automerge

#4194 fix(judicial-system): Fixes transitions
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx
  apps/judicial-system/web/src/utils/hooks/useCase.tsx
Labels: automerge

#4066 feat(api): license service shell
  SUMMARY.md
  apps/api/src/app/app.module.ts
  apps/service-portal/src/store/modules.ts
  jest.config.js
  libs/api/domains/license-service/.eslintrc.json
  libs/api/domains/license-service/README.md
  libs/api/domains/license-service/jest.config.js
  libs/api/domains/license-service/src/index.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseMappers.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.type.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/index.ts
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/graphql/payload.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/api/domains/license-service/tsconfig.json
  libs/api/domains/license-service/tsconfig.lib.json
  libs/api/domains/license-service/tsconfig.spec.json
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/licenses/.babelrc
  libs/service-portal/licenses/.eslintrc.json
  libs/service-portal/licenses/README.md
  libs/service-portal/licenses/babel-jest.config.json
  libs/service-portal/licenses/jest.config.js
  libs/service-portal/licenses/src/index.ts
  libs/service-portal/licenses/src/lib/service-portal-licenses.tsx
  libs/service-portal/licenses/src/screens/Licenses.tsx
  libs/service-portal/licenses/src/screens/components/LicenseCards/LicenseCards.tsx
  libs/service-portal/licenses/src/screens/components/LicenseCards/index.ts
  libs/service-portal/licenses/tsconfig.json
  libs/service-portal/licenses/tsconfig.lib.json
  libs/service-portal/licenses/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#4195 feat(auth-admin-web): Allow / in identifier
  apps/auth-admin-web/utils/validation.utils.ts
Labels: automerge

#4197 feat(dpo): Update terms agreement screen
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/TermsOfAgreement/index.tsx
  libs/application/templates/document-provider-onboarding/src/forms/messages.ts
  libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
Labels: automerge

#4199 feat(dpo): Help Desk Screen Updates
  libs/application/templates/document-provider-onboarding/src/forms/messages.ts
Labels: automerge

#4198 feat(dpo): Contact Screen Updates
  libs/application/templates/document-provider-onboarding/src/forms/DocumentProviderApplication.ts
  libs/application/templates/document-provider-onboarding/src/forms/messages.ts
  libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
Labels: automerge

#4140 feat(parental-leave): add 30 days VMST api + create periods DTO
  apps/application-system/api/src/app/modules/application/utils/validationUtils.ts
  libs/api/domains/directorate-of-labour/src/dto/getParentalLeavesPeriodEndDate.input.ts
  libs/api/domains/directorate-of-labour/src/dto/getParentalLeavesPeriodLength.input.ts
  libs/api/domains/directorate-of-labour/src/index.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.repository.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.service.ts
  libs/api/domains/directorate-of-labour/src/models/parentalLeavePaymentInfo.model.ts
  libs/api/domains/directorate-of-labour/src/models/parentalLeavePeriodEndDate.model.ts
  libs/api/domains/directorate-of-labour/src/models/parentalLeavePeriodLength.model.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/formUtils.spec.ts
  libs/application/core/src/types/Fields.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/dataProviders/Children/Children.ts
  libs/application/templates/parental-leave/src/fields/Duration/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/index.tsx
  libs/application/templates/parental-leave/src/fields/Rights/GiveRightsRadio.tsx
  libs/application/templates/parental-leave/src/fields/Rights/RequestRightsRadio.tsx
  libs/application/templates/parental-leave/src/fields/Rights/SummaryRights.tsx
  libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/index.tsx
  libs/application/templates/parental-leave/src/forms/EditOrAddPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/hooks/useGetOrRequestEndDates.ts
  libs/application/templates/parental-leave/src/hooks/useLazyParentalLeavePeriodEndDate.ts
  libs/application/templates/parental-leave/src/hooks/useLazyQuery.ts
  libs/application/templates/parental-leave/src/index.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
  libs/application/ui-shell/src/utils.spec.ts
  libs/application/ui-shell/src/utils.ts
  libs/clients/vmst/src/clientConfig.yaml
Labels: automerge

#4204 fix(judicial-system): use absolute url instead of relative
  apps/judicial-system/web/graphql/httpLink.ts
  apps/judicial-system/web/src/environments/environment.ts
  apps/judicial-system/web/src/services/api.ts
Labels: automerge

#4201 fix(judicial-system): fix getNamespace error
  apps/judicial-system/web/pages/_app.tsx
Labels: automerge

#4200 feat(judicial-system): court claim pre-filled text
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/messages/policeDemandsForm.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
Labels: automerge

#4144 feat: Enforce yarn install
  .npmrc
  package.json
Labels: automerge

#4203 feat(judicial-system): Investigation Notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/src/routes/Admin/ChangeUser/ChangeUser.tsx
  apps/judicial-system/web/src/routes/Admin/NewUser/NewUser.tsx
  apps/judicial-system/web/src/routes/Court/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepOne/StepOne.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/LokeCaseNumber/LokeCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectProsecutor/SelectProsecutor.tsx
  apps/judicial-system/web/src/routes/Shared/Requests/Requests.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/shared-components/CaseFileList/CaseFileList.tsx
  apps/judicial-system/web/src/shared-components/Decision/Decision.tsx
  apps/judicial-system/web/src/shared-components/RulingInput/RulingInput.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/use-case/createCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/createCourtCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/sendNotificationGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/transitionCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/updateCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/mutations.ts
  apps/judicial-system/web/src/utils/useFormHelper.ts
  libs/judicial-system/types/src/lib/types.ts
Labels: automerge

#4206 fix(auth-api-lib): Fix error logging
  libs/auth-api-lib/src/lib/services/delegations.service.ts
Labels: automerge

#4193 fix(icelandic-names-registry): a few minor changes
  apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.treat.ts
  apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.tsx
Labels: automerge

#4196 fix(services-endorsements-api): Fix for undefined enum tags
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsementListOpen.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/constants.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementList.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/findEndorsementListsByTags.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/createEndorsementList/createEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/findByTagsEndorsementList/findByTagsEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/endorsementMetadata.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/endorsementSystem/endorsementSystemSignedLists.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementValidator/endorsementValidator.decorator.ts
  apps/services/endorsements/api/src/app/modules/endorsementValidator/validators/uniqueWithinTags/uniqueWithinTagsValidator.service.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementValidator/validators/uniqueWithinTags/uniqueWithinTagsValidator.service.ts
Labels: automerge

#4208 chore(parental-leave): Mark parental leave application as ready for production
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge, high priority

#4218 fix(feature-flags): Use nationalId as a user identifier
  libs/feature-flags/src/lib/context.tsx
Labels: automerge

#4207 fix(judicial-system): fix use of env variables
  apps/judicial-system/web/graphql/httpLink.ts
  apps/judicial-system/web/next.config.js
  apps/judicial-system/web/src/services/api.ts
Labels: automerge

#4215 fix(auth-admin-api): Add DelegationScope and Delegation to Resources.Module
  apps/services/auth-admin-api/src/app/modules/resources/resources.module.ts
Labels: automerge

#4212 fix(parental-leave): Refactor Conclusion screen to use dynamic text
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/ConclusionImageScreen.tsx
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#4220 chore(parental-leave): Fix other parent issues
  apps/application-system/api/src/environments/environment.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#4229 feat(judicial-system): Fixes error introduced by transition refactoring
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/Overview.tsx
Labels: automerge

#4228 fix(auth-admin-api): Add DelegationScope and Delegation to Resources.…
  apps/services/auth-admin-api/src/app/modules/resources/resources.module.ts
Labels: automerge

#4222 chore(parental-leave): Fix other parent issues (#4220)
  apps/application-system/api/src/environments/environment.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#4216 feat(dpo): Remove redundant applicant fields
  apps/services/documents/src/app/modules/document-provider/dto/createOrganisation.dto.ts
  libs/application/templates/document-provider-onboarding/src/forms/DocumentProviderApplication.ts
  libs/application/templates/document-provider-onboarding/src/forms/ReviewApplication.ts
Labels: automerge

#4230 fix(judicial-system): error log when translations are not fetched
  apps/judicial-system/web/pages/_app.tsx
Labels: automerge

#4233 fix(parental-leave): Fixes duration slider events not called
  libs/application/templates/parental-leave/src/fields/Duration/index.tsx
  libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx
Labels: automerge, high priority

#4234 feat(application-templates-party-application): Move emails to environment variables
  libs/application/template-api-modules/src/lib/modules/templates/party-application/emailGenerators/assignSupremeCourtEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/party-letter/emailGenerators/assignToMinistryOfJustice.ts
Labels: automerge

#4237 fix(parental-leave): Fixes duration slider events not called (#4233)
  libs/application/templates/parental-leave/src/fields/Duration/index.tsx
  libs/application/templates/parental-leave/src/fields/components/Slider/index.tsx
Labels: automerge

#4240 feat(auth-admin-web): validations and hint boxes
  apps/auth-admin-web/components/Admin/form/DomainCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/GrantTypeCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/IdpProviderCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/LanguageCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/TranslationCreateForm.tsx
  apps/auth-admin-web/components/Client/form/ClientBasicCreateForm.tsx
  apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiResourceCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
  apps/auth-admin-web/components/common/HintBox.tsx
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/styles/HintBox.scss
  apps/auth-admin-web/styles/_FormLayout.scss
  apps/auth-admin-web/utils/validation.utils.ts
Labels: automerge

#4090 feat(service-portal): Request scope for national registry api
  apps/service-portal/src/auth.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/nationalRegistry.scope.ts
Labels: automerge

#4219 fix(party-application): Use endorsementshook
  libs/application/templates/party-application/src/fields/EndorsementList/EndorsementTable.tsx
  libs/application/templates/party-application/src/fields/EndorsementList/index.tsx
  libs/application/templates/party-application/src/fields/EndorsementListSubmission/EndorsementTable.tsx
  libs/application/templates/party-application/src/fields/EndorsementListSubmission/index.tsx
  libs/application/templates/party-application/src/fields/Overview/index.tsx
  libs/application/templates/party-application/src/fields/PartyApplicationApprovedOverview/index.tsx
  libs/application/templates/party-application/src/fields/SupremeCourtOverview/index.tsx
  libs/application/templates/party-application/src/fields/index.ts
  libs/application/templates/party-application/src/forms/ApprovedOverview.ts
  libs/application/templates/party-application/src/hooks/fetch-endorsements.ts
  libs/application/templates/party-application/src/lib/dataSchema.ts
  libs/application/templates/party-letter/src/fields/EndorsementList/EndorsementTable.tsx
  libs/application/templates/party-letter/src/fields/MinistryOfJusticeOverview/index.tsx
Labels: automerge

#4247 fix(api): move driving license xroad path into env
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
Labels: automerge

#4248 fix(auth-admin-web): validations and hint boxes (#4240)
  apps/auth-admin-web/components/Admin/form/DomainCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/GrantTypeCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/IdpProviderCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/LanguageCreateForm.tsx
  apps/auth-admin-web/components/Admin/form/TranslationCreateForm.tsx
  apps/auth-admin-web/components/Client/form/ClientBasicCreateForm.tsx
  apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiResourceCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/IdentityResourceCreateForm.tsx
  apps/auth-admin-web/components/common/HintBox.tsx
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/styles/HintBox.scss
  apps/auth-admin-web/styles/_FormLayout.scss
  apps/auth-admin-web/utils/validation.utils.ts
Labels: automerge

#4054 feat(web): new organizations overview page
  apps/web/components/BackgroundImage/BackgroundImage.treat.ts
  apps/web/components/Card/Card.tsx
  apps/web/components/FrontpageSlider/FrontpageSlider.treat.ts
  apps/web/components/FrontpageSlider/FrontpageSlider.tsx
  apps/web/screens/Organizations/FilterMenu.tsx
  apps/web/screens/Organizations/Organiziations.tsx
  libs/island-ui/contentful/src/lib/BackgroundImage/BackgroundImage.treat.ts
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.treat.ts
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
  libs/island-ui/core/src/lib/Pagination/Pagination.treat.ts
  libs/island-ui/core/src/lib/Pagination/Pagination.tsx
  libs/island-ui/theme/src/index.ts
  libs/island-ui/theme/src/lib/helperStyles.treat.ts
Labels: automerge
