Repository island-is/island.is, pull requests merged in 2021-12, with the labels that each got.

#5824 fix(application-system): Extending timeout (#5821)
  libs/api/domains/application/src/lib/application.module.ts
Labels: automerge

#5742 fix(service-portal): update faker number
  libs/api/mocks/src/domains/assets/factories.ts
Labels: automerge

#5816 fix(web): set fixed height for search section on desktop
  apps/web/components/SearchSection/SearchSection.css.ts
  apps/web/components/SearchSection/SearchSection.tsx
  libs/cms/src/lib/models/lifeEventPage.model.ts
Labels: automerge

#5835 fix(application-system-api): use v1 path for v2 endpoint
  apps/application-system/api/src/environments/environment.ts
Labels: automerge

#5836 fix(application-system-api): use v1 path for v2 endpoint
  apps/application-system/api/src/environments/environment.ts
Labels: automerge

#5827 chore(judicial-system): Updated lawyer db
  apps/judicial-system/web/src/utils/lawyerScraper/db.json
Labels: automerge

#5811 feat(fa): Activates admin
  apps/financial-aid/backend/src/app/guards/staff.guard.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/web-osk/src/utils/hooks/useLogOut.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
  apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
  apps/financial-aid/web-veita/src/routes/Supervisors/supervisors.tsx
  apps/financial-aid/web-veita/src/routes/Users/users.tsx
  apps/financial-aid/web-veita/src/utils/useLogOut.ts
  apps/financial-aid/web-veita/src/utils/useStaff.ts
Labels: automerge

#5813 feat(fa): Adding spouse comment
  apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts
  apps/financial-aid/api/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/migrations/20211130110951-application-add-column-spouse_form_comment.js
  apps/financial-aid/backend/src/app/modules/application/dto/updateApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/models/application.model.ts
  apps/financial-aid/web-osk/src/components/Summary/FormComment.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useUpdateApplication.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/FilesListWithHeader/FilesListWithHeader.css.ts
  apps/financial-aid/web-veita/src/components/FilesListWithHeader/FilesListWithHeaderContainer.tsx
  apps/financial-aid/web-veita/src/components/History/History.css.ts
  apps/financial-aid/web-veita/src/components/History/History.tsx
  apps/financial-aid/web-veita/src/components/ProfileUnit/ProfileUnit.tsx
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5798 feat(fa): Create admin, adding municipality to create staff
  apps/financial-aid/api/src/app/modules/staff/dto/createStaff.input.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/staff/dto/createStaff.dto.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5840 fix(fa): Fixes month in emails
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  libs/financial-aid/shared/src/lib/formatters.ts
Labels: automerge

#5841 fix(fa): national registry spouse type
  apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useApplication.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5846 fix(public-debt-payment-plan): fixes after testing
  libs/application/templates/public-debt-payment-plan/src/lib/dataSchema.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/employer.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/externalData.ts
Labels: automerge

#5850 feat(public-debt-payment-plan): add submit form
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanSubmittedForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
Labels: automerge

#5849 fix(parental-leave): Fetch spouse from deprecated provider if not found in person provider
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#5856 fix(parental-leave): Fetch spouse from deprecated provider data as backup
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#5847 feat(island-ui): Add a createable ReactSelect component
  libs/island-ui/core/src/lib/Select/Components/index.tsx
  libs/island-ui/core/src/lib/Select/Select.css.ts
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#5857 fix(accident-notification): fix edit buttons
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
Labels: automerge

#5844 fix(service-portal): missing data in detail view properties
  .github/CODEOWNERS
  libs/api/domains/assets/src/lib/api-domains-assets.service.ts
Labels: automerge

#5855 chore(ci): Skip flaky application-system-form-e2e test
  workspace.json
Labels: automerge

#5823 feat(core): Feature flag library for Nest APIs
  SUMMARY.md
  jest.config.js
  libs/feature-flags/README.md
  libs/feature-flags/src/lib/configcat.ts
  libs/feature-flags/src/lib/types.ts
  libs/infra-nest-server/src/lib/buildOpenApi.ts
  libs/nest/feature-flags/.eslintrc.json
  libs/nest/feature-flags/README.md
  libs/nest/feature-flags/jest.config.js
  libs/nest/feature-flags/src/index.ts
  libs/nest/feature-flags/src/lib/feature-flag.client.ts
  libs/nest/feature-flags/src/lib/feature-flag.config.ts
  libs/nest/feature-flags/src/lib/feature-flag.decorator.ts
  libs/nest/feature-flags/src/lib/feature-flag.guard.spec.ts
  libs/nest/feature-flags/src/lib/feature-flag.guard.ts
  libs/nest/feature-flags/src/lib/feature-flag.module.ts
  libs/nest/feature-flags/src/lib/feature-flag.service.ts
  libs/nest/feature-flags/tsconfig.json
  libs/nest/feature-flags/tsconfig.lib.json
  libs/nest/feature-flags/tsconfig.spec.json
  libs/react/feature-flags/src/lib/context.tsx
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#5804 feat(core/web): External/Internal links
  apps/air-discount-scheme/web/components/Link/Link.tsx
  apps/web/screens/Adgerdir/components/UI/Tag/Tag.tsx
  libs/island-ui/core/src/lib/ButtonDeprecated/Button.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
  libs/island-ui/core/src/lib/Link/Link.tsx
  libs/island-ui/core/src/lib/Tag/Tag.tsx
  libs/island-ui/storybook/config/main.js
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/shouldLinkOpenInNewWindow.spec.ts
  libs/shared/utils/src/lib/shouldLinkOpenInNewWindow.ts
Labels: automerge

#5845 fix(fa): Adds loading indicator to info page
  apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
Labels: automerge

#5851 fix(skilavottord): auth and add guard
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
  apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
  apps/skilavottord/ws/src/app/modules/user/user.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
Labels: automerge

#5859 fix(fa): Adds error msg for data fetching
  apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
Labels: automerge

#5833 feat(delegations): Delegation feature flags
  apps/services/auth-api/src/app/app.module.ts
  apps/services/auth-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-public-api/src/app/app.module.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.controller.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
  libs/feature-flags/src/lib/features.ts
  libs/nest/feature-flags/src/lib/feature-flag.module.ts
  libs/nest/feature-flags/src/lib/feature-flag.service.ts
Labels: automerge

#5702 feat(application-system-form): adding plausible for stats
  apps/application-system/form/src/index.html
Labels: automerge

#5854 chore(codeql): Analyze merge commit
  .github/workflows/codeql-analysis.yml
Labels: automerge

#5864 chore(github): set github actions node-based tasks to use node 14
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#5869 fix(ci): missing deps
  apps/services/auth-api/esbuild.json
  apps/services/auth-public-api/esbuild.json
Labels: automerge

#5594 feat(service-portal): Display finance pdf's using the download-service
  apps/download-service/infra/download-service.ts
  apps/download-service/src/app/app.module.ts
  apps/download-service/src/app/modules/finance-documents/document.controller.ts
  apps/download-service/src/app/modules/finance-documents/dto/getFinanceDocument.dto.ts
  apps/download-service/src/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/finance/src/lib/api-domains-finance.module.ts
  libs/api/domains/finance/src/lib/models/documentsList.model.ts
  libs/clients/finance/src/lib/finance.ts
  libs/clients/finance/src/lib/finance.types.ts
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatusData.types.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/finance/src/utils/documentFormSubmission.ts
  libs/service-portal/graphql/src/hooks/finance/loadPdfDocument.ts
  libs/service-portal/graphql/src/index.ts
Labels: automerge, deploy-feature

#5862 feat(web/service-web): custom backgrounds for institutions and other tweaks
  apps/web/components/ServiceWeb/Background/Background.css.ts
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/Default/Default.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Default/Default.tsx
  apps/web/components/ServiceWeb/Background/Variations/Default/index.ts
  apps/web/components/ServiceWeb/Background/Variations/StafraentIsland/Illustration.tsx
  apps/web/components/ServiceWeb/Background/Variations/StafraentIsland/StafraentIsland.css.ts
  apps/web/components/ServiceWeb/Background/Variations/StafraentIsland/StafraentIsland.tsx
  apps/web/components/ServiceWeb/Background/Variations/StafraentIsland/index.ts
  apps/web/components/ServiceWeb/Background/Variations/Syslumenn/Illustration.tsx
  apps/web/components/ServiceWeb/Background/Variations/Syslumenn/Syslumenn.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Syslumenn/Syslumenn.tsx
  apps/web/components/ServiceWeb/Background/Variations/Syslumenn/index.ts
  apps/web/components/ServiceWeb/Background/Variations/index.ts
  apps/web/components/ServiceWeb/Background/index.tsx
  apps/web/components/ServiceWeb/DynamicFooter/DynamicFooter.tsx
  apps/web/components/ServiceWeb/DynamicFooter/index.tsx
  apps/web/components/ServiceWeb/Header/Header.css.ts
  apps/web/components/ServiceWeb/Header/Header.tsx
  apps/web/components/ServiceWeb/SearchSection/SearchSection.tsx
  apps/web/components/ServiceWeb/Wrapper/Wrapper.css.ts
  apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
  apps/web/components/ServiceWeb/Wrapper/index.tsx
  apps/web/components/ServiceWeb/config.ts
  apps/web/components/ServiceWeb/index.ts
  apps/web/components/ServiceWeb/types.ts
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organization.model.ts
Labels: automerge

#5838 fix(syslumenn-api): Tests for syslumenn api
  libs/api/domains/syslumenn/jest.config.js
  libs/api/domains/syslumenn/src/lib/__mock-data__/requestHandlers.ts
  libs/api/domains/syslumenn/src/lib/__mock-data__/responses.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.spec.ts
Labels: automerge

#5865 feat(regulations/web): Fix cache issues, and esoteric Regulation history time-travel bugs
  apps/web/components/Regulations/DiffModeToggle.tsx
  apps/web/components/Regulations/HistoryStepper.tsx
  apps/web/components/Regulations/RegulationChangelog.tsx
  apps/web/components/Regulations/RegulationInfoBox.tsx
  apps/web/components/Regulations/RegulationStatus.tsx
  apps/web/components/Regulations/RegulationTexts.types.ts
  apps/web/components/Regulations/RegulationsSidebarBox.css.ts
  apps/web/components/Regulations/useRegulationIndexer.ts
  libs/clients/regulations/src/lib/regulations.ts
  libs/regulations/src/lib/styling.ts
  libs/regulations/src/lib/types-admin-database.ts
  libs/regulations/src/lib/types-web.ts
  package.json
  yarn.lock
Labels: automerge

#5752 feat(endorsement-service-api): Xroad connection to national registry in endorsementMetaData
  apps/services/endorsements/api/infra/endorsement-system-scripts-update-metadata.ts
  apps/services/endorsements/api/jest.config.js
  apps/services/endorsements/api/script-entrypoints/updateMetadata.js
  apps/services/endorsements/api/scripts/updateMetadata.ts
  apps/services/endorsements/api/src/app/app.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/endorsementMetadata.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/endorsementMetadata.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/nationalRegistry.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/nationalRegistry/mock/nationalRegistryApiMock.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/nationalRegistry/mock/nationalRegistryMock.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/nationalRegistry/nationalRegistry.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/nationalRegistry/nationalRegistryUser.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/temporaryVoterRegistry/mock/temporaryVoterRegistryApiMock.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/providers/temporaryVoterRegistry/mock/temporaryVoterRegistryMock.ts
  apps/services/endorsements/api/src/app/modules/endorsementMetadata/types/index.ts
  apps/services/endorsements/api/src/environments/environment.ts
  apps/services/endorsements/api/src/main.ts
  apps/services/endorsements/api/test/setup.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  workspace.json
Labels: automerge

#5875 fix(an): fix files on overview
  libs/application/templates/accident-notification/src/utils/index.ts
Labels: automerge

#5877 feat(fa): Adds employee email
  apps/financial-aid/backend/src/app/modules/application/emailTemplates/employeeEmailTemplate.ts
  apps/financial-aid/backend/src/app/modules/application/emailTemplates/index.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.module.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/backend/src/environments/environment.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5863 feat(auth-admin-web): Misc minor changes
  apps/auth-admin-web/components/common/Paginator.tsx
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/pages/client/[client].tsx
  apps/services/auth-admin-api/src/app/modules/clients/clients.controller.ts
  apps/services/auth-admin-api/src/app/modules/grant-types/grant-types.controller.ts
  apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
  libs/auth-api-lib/src/lib/services/clients.service.ts
  libs/auth-api-lib/src/lib/services/grant-types.service.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
Labels: automerge

#5858 fix(an): add letter limit
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/accident-notification/src/fields/FormOverviewInReview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/applicantInformationSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/whoIsTheNotificationForSection.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/ui-fields/src/lib/TextFormField/TextFormField.tsx
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#5884 feat(cms/web): Embedded entries, import and rendering
  libs/cms/src/lib/search/importers/article.service.ts
  libs/cms/src/lib/search/importers/subArticle.service.ts
  libs/cms/src/lib/search/importers/utils.ts
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
Labels: automerge

#5808 feat(fa): Update you own settings
  apps/financial-aid/api/src/app/modules/staff/dto/updateStaff.input.ts
  apps/financial-aid/api/src/app/modules/staff/models/staff.model.ts
  apps/financial-aid/backend/migrations/20211130093506-staff-add-pseudoname.js
  apps/financial-aid/backend/src/app/modules/staff/dto/updateStaff.dto.ts
  apps/financial-aid/backend/src/app/modules/staff/models/staff.model.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/ApplicationHeader/ApplicationHeader.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/Generator/GenerateName.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/TableBody/TableBody.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  apps/financial-aid/web-veita/src/routes/MySettings/MySettings.tsx
  apps/financial-aid/web-veita/src/routes/Search/search.tsx
  apps/financial-aid/web-veita/src/utils/useStaff.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5866 feat(service-portal): Configure access control on all service portal modules
  apps/api/src/app/environments/environment.ts
  apps/application-system/form/src/auth.ts
  apps/download-service/src/app/modules/documents/document.controller.ts
  apps/icelandic-names-registry/backend/src/app/modules/icelandic-name/icelandic-name.controller.ts
  apps/service-portal/src/auth.ts
  apps/services/documents/src/app/modules/document-provider/controllers/changelog.controller.ts
  apps/services/documents/src/app/modules/document-provider/controllers/organisation.controller.ts
  apps/services/documents/src/app/modules/document-provider/controllers/provider.controller.ts
  apps/services/documents/src/app/modules/document-provider/e2e/document-provider.spec.ts
  libs/api/domains/assets/src/lib/api-domains-assets.resolver.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/education/src/lib/graphql/main.resolver.ts
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/health-insurance/src/lib/graphql/accident-notification.resolver.ts
  libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/familyMember.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/user.resolver.ts
  libs/api/domains/party-letter-registry/src/lib/partyLetterRegistry.resolver.ts
  libs/api/domains/payment-schedule/src/lib/graphql/payment-schedule.resolver.ts
  libs/api/domains/rsk/src/lib/api-domains-rsk.resolver.ts
  libs/auth-nest-tools/src/lib/scopes.guard.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/assets/src/index.ts
  libs/service-portal/document-provider/src/index.ts
  libs/service-portal/driving-license/src/index.ts
  libs/service-portal/education-career/src/index.ts
  libs/service-portal/education-degree/src/index.ts
  libs/service-portal/education-license/src/index.ts
  libs/service-portal/education-student-assessment/src/index.ts
  libs/service-portal/education/src/index.ts
  libs/service-portal/eligibility/src/index.ts
  libs/service-portal/endorsements/src/index.ts
  libs/service-portal/family/src/index.ts
  libs/service-portal/finance/src/index.ts
  libs/service-portal/health/src/index.ts
  libs/service-portal/icelandic-names-registry/src/index.ts
  libs/service-portal/licenses/src/index.ts
  libs/service-portal/settings/access-control/src/index.ts
  libs/service-portal/settings/islykill/src/index.ts
  libs/service-portal/settings/personal-information/src/index.ts
Labels: deploy-feature

#5885 fix(api): Fixing possbile null and undefined values in auth and identity domains
  libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
  libs/api/domains/identity/src/lib/identity.service.ts
Labels: automerge

#5886 chore(auth): Add new scopes to our clients
  apps/application-system/form/src/auth.ts
  apps/service-portal/src/auth.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#5868 feat(judicial-system): Add ruling date to subtitles on signed verdict overview
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/mocks.ts
Labels: automerge

#5860 feat(judicial-system): Enable lawyer lookup from Lögmannaskrá
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.css.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepOne/StepOneForm.tsx
Labels: automerge

#5891 fix(api): Adding nullable true for resolve fields in auth domain.
  libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
Labels: automerge

#5894 fix(service-portal): Fixing toast error handling in GrantAccess and typescript issues for delegations
  libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
  libs/service-portal/settings/access-control/src/screens/AccessControl/components/Accesses/Accesses.tsx
  libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
  libs/shared/components/src/auth/UserMenu/UserDelegations.tsx
Labels: automerge

#5889 fix(public-debt-payment-plan): Info screen for users that have no debts
  libs/application/templates/public-debt-payment-plan/src/fields/PrerequisitesErrorModal/PrerequisitesErrorModal.tsx
  libs/application/templates/public-debt-payment-plan/src/lib/messages/errorModal.ts
  libs/application/templates/public-debt-payment-plan/src/lib/paymentPlanUtils.ts
Labels: automerge

#5890 fix(pubic-debt-payment-plan): update employer fix
  libs/api/domains/payment-schedule/src/lib/graphql/payment-schedule.resolver.ts
  libs/api/domains/payment-schedule/src/lib/payment-schedule.service.ts
Labels: automerge

#5822 fix(accident-notification): Fix issues with application
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/lib/messages/companyInfo.ts
Labels: automerge

#5899 fix(endorsement-system-api): xroad config for national registry
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#5842 fix(service-portal): updates + bugfixes in user profile
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/mutations/updateIslykillSettings.ts
  libs/service-portal/settings/personal-information/src/components/Forms/PhoneForm/Steps/FormStep.tsx
  libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/Islykill/PhoneForm.tsx
  libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
  libs/service-portal/settings/personal-information/src/index.ts
  libs/service-portal/settings/personal-information/src/screens/EditNudge/EditNudge.tsx
  libs/service-portal/settings/personal-information/src/screens/UserProfile/UserProfile.tsx
  libs/service-portal/settings/personal-information/src/utils/phoneHelper.ts
  libs/shared/components/src/auth/UserMenu/UserDropdown.tsx
  libs/shared/components/src/auth/UserMenu/UserProfileInfo.tsx
  libs/shared/components/src/auth/UserMenu/userProfile.graphql.ts
  libs/shared/translations/src/lib/shared.ts
Labels: automerge

#5881 feat(fa): Adds spouse email
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/emailTemplates/applicantEmailTemplate.ts
  apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutFormSpouse.tsx
  libs/financial-aid/shared/src/lib/const.ts
  libs/financial-aid/shared/src/lib/formatters.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#5906 fix(endorsement-system-api): XRoad client id
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#5895 fix(service-portal): Configure access control for remaining routes
  apps/download-service/src/app/modules/finance-documents/document.controller.ts
  libs/service-portal/wip/src/index.ts
Labels: automerge

#5883 chore(fa): refactors application update
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
Labels: automerge

#5901 fix(skilavottord): fix logout
  apps/skilavottord/web/graphql/errorLink.ts
  apps/skilavottord/web/services/api.ts
Labels: automerge

#5905 fix(auth-public-api): Regression when creating a new delegation with no scopes
  .github/CODEOWNERS
  apps/services/auth-public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.ts
  apps/services/auth-public-api/test/utils.ts
  libs/auth-api-lib/src/lib/entities/dto/delegation.dto.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
Labels: automerge

#5810 feat(judicial-system): PDF table for signed verdicts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/components/PdfRow/PdfRow.css.ts
  apps/judicial-system/web/src/components/PdfRow/PdfRow.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/SignedDocument.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/courtRecordSignatureConfirmationGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/extendCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/requestCourtRecordSignatureGql.ts
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
  apps/judicial-system/web/src/utils/mutations.ts
Labels: automerge

#5898 fix(an): trim whitespace
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/error.ts
Labels: automerge

#5897 feat(island-ui): add description field for select option
  libs/island-ui/core/src/lib/Input/Input.mixins.ts
  libs/island-ui/core/src/lib/Select/Components/index.tsx
  libs/island-ui/core/src/lib/Select/Select.css.ts
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#5911 fix(skilavottord): using currentUser
  apps/skilavottord/web/components/GDPR/GDPR.tsx
  apps/skilavottord/web/components/GDPR/withGDPR.tsx
  apps/skilavottord/web/screens/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/Handover/Handover.tsx
  apps/skilavottord/web/screens/Overview/Overview.tsx
  apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts
  apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
Labels: automerge

#5916 fix(service-portal): Add prefix to phone create islykill settings
  libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
Labels: automerge

#5910 feat(judicial-system): Added judge, registrar and prosecutor to email sent to defenders about a court date being set
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#5912 chore(judicial-system): Updated lawyer db
  apps/judicial-system/web/src/utils/lawyerScraper/db.json
Labels: automerge

#5914 fix(service-portal): Add mobile prefix to create
  libs/service-portal/settings/personal-information/src/components/UserOnboardingModal/UserOnboardingModal.tsx
Labels: automerge

#5902 fix(fa): Use our own scope for national registry
  apps/financial-aid/api/src/app/app.module.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/index.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/models/person.model.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/models/userAddress.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/models/userResidence.model.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/models/userSpouse.model.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/nationalRegistryXRoad.resolver.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/nationalRegistryXRoadModule.module.ts
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/src/routes/application/Info/info.tsx
Labels: automerge

#5892 feat(skilavottord): delete access control functionality
  apps/skilavottord/web/components/Header/Header.tsx
  apps/skilavottord/web/components/Layouts/PageLayout.tsx
  apps/skilavottord/web/components/Modal/Modal.tsx
  apps/skilavottord/web/context/UserContext.ts
  apps/skilavottord/web/i18n/locales/en.json
  apps/skilavottord/web/i18n/locales/is.json
  apps/skilavottord/web/i18n/locales/translation.d.ts
  apps/skilavottord/web/screens/AccessControl/AccessControl.css.ts
  apps/skilavottord/web/screens/AccessControl/AccessControl.tsx
  apps/skilavottord/web/screens/CompanyInfo/CompanyInfo.tsx
  apps/skilavottord/web/screens/Completed/Completed.tsx
  apps/skilavottord/web/screens/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Select.tsx
  apps/skilavottord/web/screens/Handover/Handover.tsx
  apps/skilavottord/web/screens/Overview/Overview.tsx
  apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx
  apps/skilavottord/web/screens/Overview/components/ActionCardContainer/ActionCardContainer.tsx
  apps/skilavottord/web/screens/Overview/components/ProgressCard/ProgressCard.tsx
  apps/skilavottord/web/screens/Overview/components/ProgressCardContainer/ProgressCardContainer.tsx
  apps/skilavottord/web/screens/Overview/types.ts
  apps/skilavottord/web/screens/RecyclingFund/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/web/tsconfig.json
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.input.ts
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.resolver.ts
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.service.ts
Labels: automerge

#5915 fix(an): few small issues
  libs/application/templates/accident-notification/src/fields/DateOfAccident/index.tsx
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/addDocuments.ts
  libs/application/templates/accident-notification/src/lib/messages/attachments.ts
Labels: automerge

#5903 chore(service-portal): Move authorization identity header
  libs/api/domains/assets/src/lib/api-domains-assets.service.ts
  libs/api/domains/assets/src/lib/authorization-identity.middleware.ts
  libs/auth-nest-tools/src/lib/auth.middleware.ts
Labels: automerge

#5882 fix(dpac): minor text changes
  libs/application/templates/data-protection-complaint/src/fields/AgreementDescription.tsx
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/delimitation.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/error.ts
Labels: automerge

#5900 fix(fa): reload on status page
  apps/financial-aid/backend/src/app/guards/application.guard.ts
  apps/financial-aid/web-osk/src/utils/hooks/useMyApplication.ts
Labels: automerge

#5887 chore(judicial-system): Move from uncontrolled inputs to controlled inputs
  apps/judicial-system/web/src/components/DateTime/DateTime.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
  apps/judicial-system/web/src/components/TimeInputField/TimeInputField.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/LokeCaseNumber/LokeCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx
Labels: automerge

#5917 fix(public-debt-payment-plan): Allow employer to be a person
  libs/application/templates/public-debt-payment-plan/src/fields/DisposableIncome/DisposableIncome.tsx
Labels: automerge

#5921 fix(fa): Removing double comment
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
Labels: automerge

#5893 feat(fa): Audit logs
  apps/financial-aid/backend/src/app/app.module.ts
  apps/financial-aid/backend/src/app/decorators/application.decorator.ts
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/environments/environment.ts
Labels: automerge

#5922 fix(fa): Adding rejection comment to email
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-osk/src/components/Status/Rejected.tsx
  libs/financial-aid/shared/src/lib/formatters.ts
Labels: automerge

#5918 fix(ci): fixing node version issues
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge, deploy-feature

#5931 fix(endorsement-system-api): National registry soap prod config
  apps/services/endorsements/api/src/environments/environment.ts
Labels: automerge

#5927 fix(core): Fix empty response body handling in enhanced fetch cache
  libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/withCache/CacheResponse.ts
Labels: automerge

#5926 fix(core): Fix empty response body handling in enhanced fetch cache
  libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/withCache/CacheResponse.ts
Labels: automerge

#5925 fix(fa): Admin can not deactivate himself
  apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
Labels: automerge

#5930 fix(fa): Malskot text added
  apps/financial-aid/web-osk/src/components/Status/Rejected.tsx
Labels: automerge

#5938 fix(endorsement-system-api): Hotfix endorsement system api
  apps/services/endorsements/api/src/environments/environment.ts
Labels: automerge

#5936 fix(judicial-system): Only autofill ruling on initial render
  apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
Labels: automerge

#5923 fix(judicial-system): Fix attendees
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#5932 feat(judicial-system): Added comments on hearing arrangements screen
  apps/judicial-system/web-e2e/src/integration/Court/hearingArrangements.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#5940 fix(an): overview fixes and upgrades
  libs/application/templates/accident-notification/src/fields/FormOverview/FormOverview.css.ts
  libs/application/templates/accident-notification/src/fields/FormOverview/ValueLine.tsx
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/whoIsTheNotificationForSection.ts
  libs/application/templates/accident-notification/src/types/index.ts
  libs/application/templates/accident-notification/src/utils/index.ts
Labels: automerge

#5924 feat(judicial-system): Add ".sml" to legal provisions
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/web/messages/Core/laws.ts
  apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/laws.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#5913 feat(judicial-system): Match search for defenders from start
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#5942 feat(web): Syslumenn / Alert quick fix
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home.tsx
Labels: automerge

#5944 feat(web): Hotfix - Syslumenn / Alert quick fix
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home.tsx
Labels: automerge

#5945 fix(judicial-system): Update state with new case files when uploading case files
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFive/StepFiveForm.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload.ts
Labels: automerge

#5907 feat(web): Add new design for Sjukratryggingar page
  apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarHeader.tsx
  apps/web/public/assets/sjukratryggingar_heilbrigdisraduneytid.png
  apps/web/public/assets/sjukratryggingar_logo.png
  apps/web/public/assets/sjukratryggingar_norraent_samstarf.png
  apps/web/public/assets/sjukratryggingar_seniors.png
  apps/web/public/assets/sjukratryggingar_title.svg
  apps/web/public/assets/sjukratryggingar_triangles_left.png
  apps/web/public/assets/sjukratryggingar_triangles_right.png
  apps/web/public/assets/sjukratryggingar_triangles_top.png
Labels: automerge

#5951 fix(skilavottord): Hotfix - using currentUser (#5911) and delete access control (#5892)
  apps/skilavottord/web/components/GDPR/GDPR.tsx
  apps/skilavottord/web/components/GDPR/withGDPR.tsx
  apps/skilavottord/web/components/Header/Header.tsx
  apps/skilavottord/web/components/Layouts/PageLayout.tsx
  apps/skilavottord/web/components/Modal/Modal.tsx
  apps/skilavottord/web/context/UserContext.ts
  apps/skilavottord/web/i18n/locales/en.json
  apps/skilavottord/web/i18n/locales/is.json
  apps/skilavottord/web/i18n/locales/translation.d.ts
  apps/skilavottord/web/screens/AccessControl/AccessControl.css.ts
  apps/skilavottord/web/screens/AccessControl/AccessControl.tsx
  apps/skilavottord/web/screens/CompanyInfo/CompanyInfo.tsx
  apps/skilavottord/web/screens/Completed/Completed.tsx
  apps/skilavottord/web/screens/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Select.tsx
  apps/skilavottord/web/screens/Handover/Handover.tsx
  apps/skilavottord/web/screens/Overview/Overview.tsx
  apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx
  apps/skilavottord/web/screens/Overview/components/ActionCardContainer/ActionCardContainer.tsx
  apps/skilavottord/web/screens/Overview/components/ProgressCard/ProgressCard.tsx
  apps/skilavottord/web/screens/Overview/components/ProgressCardContainer/ProgressCardContainer.tsx
  apps/skilavottord/web/screens/Overview/types.ts
  apps/skilavottord/web/screens/RecyclingFund/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/web/tsconfig.json
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.input.ts
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.resolver.ts
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.service.ts
  apps/skilavottord/ws/src/app/modules/fjarsysla/fjarsysla.resolver.ts
  apps/skilavottord/ws/src/app/modules/gdpr/gdpr.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
Labels: automerge

#5949 fix: (service-portal): Update basepath islykill service
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#5939 fix(fa): Updating privacy text
  apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutFormApplicant.tsx
Labels: automerge

#5946 fix(service-portal): Update basepath islykill service
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#5867 chore(island-core-ui): remove loading icon
  apps/skilavottord/web/components/Modal/Modal.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/Handover/Handover.tsx
  apps/web/components/OpenApiView/OpenApiView.tsx
  apps/web/screens/Adgerdir/components/AdgerdirArticles/AdgerdirArticles.tsx
  apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
  apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  libs/island-ui/core/src/index.ts
  libs/island-ui/core/src/lib/LoadingIcon/AnimatedLine.tsx
  libs/island-ui/core/src/lib/LoadingIcon/LoadingIcon.stories.tsx
  libs/island-ui/core/src/lib/LoadingIcon/LoadingIcon.tsx
Labels: automerge

#5957 fix(service-portal): wrong data for user inputs
  libs/service-portal/settings/personal-information/src/screens/EditEmail/EditEmail.tsx
  libs/service-portal/settings/personal-information/src/screens/EditPhoneNumber/EditPhoneNumber.tsx
Labels: automerge

#5956 fix(service-portal): data display for user fix
  libs/service-portal/settings/personal-information/src/screens/EditEmail/EditEmail.tsx
  libs/service-portal/settings/personal-information/src/screens/EditPhoneNumber/EditPhoneNumber.tsx
Labels: automerge

#5962 fix(regulations/web): missing appendixes diff styles and tweak pager links
  apps/web/components/Regulations/Appendixes.tsx
  apps/web/components/Regulations/regulationUtils.ts
Labels: automerge

#5958 fix(dpac): few small fixes
  libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeRepeaterItem.tsx
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
Labels: automerge

#5963 fix(regulations/web): Hotfix - missing appendixes diff styles and tweak pager links
  apps/web/components/Regulations/Appendixes.tsx
  apps/web/components/Regulations/regulationUtils.ts
Labels: automerge

#5960 fix(pdpp): fix refresh issue
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
Labels: automerge

#5943 fix(an): fixing few minor errors
  libs/application/templates/accident-notification/src/assets/Logo.tsx
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/StatusStep/ReviewSection.css.ts
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/StatusStep/index.tsx
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/lib/messages/conclusion.ts
Labels: automerge

#5964 feat(an): add reviewer comment
  libs/application/templates/accident-notification/src/fields/FormOverviewInReview/ConfirmationModal.tsx
  libs/application/templates/accident-notification/src/fields/FormOverviewInReview/index.tsx
Labels: automerge

#5965 feat(an): added confirmation message
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/accident-notification/src/lib/messages/inReview.ts
Labels: automerge

#5888 fix(fa): Updates env variables
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/backend/src/environments/environment.ts
Labels: automerge

#5879 feat(user-profile): Adding user device tokens support
  apps/services/user-profile/README.md
  apps/services/user-profile/migrations/20211201000001-user-device-tokens.js
  apps/services/user-profile/migrations/20211201000002-update-user-profile.js
  apps/services/user-profile/seeders/test-user-profiles.js
  apps/services/user-profile/src/app/user-profile/dto/deleteTokenResponseDto.ts
  apps/services/user-profile/src/app/user-profile/dto/deviceToken.dto.ts
  apps/services/user-profile/src/app/user-profile/dto/updateUserDeviceToken.dto.ts
  apps/services/user-profile/src/app/user-profile/dto/updateUserProfileDto.ts
  apps/services/user-profile/src/app/user-profile/dto/userDeviceTokens.dto.ts
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userDeviceTokens.model.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/userProfile.model.ts
  apps/services/user-profile/src/app/user-profile/userProfile.module.ts
  apps/services/user-profile/src/app/user-profile/userProfile.service.ts
  apps/services/user-profile/src/main.ts
  apps/services/user-profile/src/openApi.ts
  libs/api/domains/user-profile/src/lib/dto/deleteTokenResponse.ts
  libs/api/domains/user-profile/src/lib/dto/userDeviceTokenInput.ts
  libs/api/domains/user-profile/src/lib/userDeviceToken.model.ts
  libs/api/domains/user-profile/src/lib/userProfile.model.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
Labels: automerge

#5966 fix(application-templates): only giving the applicant a role in the driving-* applications, and disabling the general petitions module in prod
  libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
Labels: automerge

#5968 fix(application-templates): only giving the applicant a role -- cherry-pick from main
  libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
Labels: automerge

#5970 feat(an): adding check if assignee is unique
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/accident-notification/src/forms/InReviewForm/addAttachmentsSection.ts
  libs/application/templates/accident-notification/src/utils/hasMissingDocuments.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isUniqueAssignee.spec.ts
  libs/application/templates/accident-notification/src/utils/isUniqueAssignee.ts
Labels: automerge

#5972 feat(fa): Adds national registry address
  apps/financial-aid/api/src/app/app.module.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/index.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/models/person.model.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/models/userAddress.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/models/userResidence.model.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/models/userSpouse.model.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/municipalityNationalRegistry.resolver.ts
  apps/financial-aid/api/src/app/modules/municpalityNationalRegistryModule/municipalityNationalRegistryModule.module.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/index.ts
  apps/financial-aid/api/src/app/modules/nationalRegistryXRoadModule/nationalRegistryXRoadModule.module.ts
  apps/financial-aid/web-osk/src/components/Spouse/SpouseInfo.tsx
  apps/financial-aid/web-osk/src/components/SpouseEmailInput/SpouseEmailInput.tsx
  apps/financial-aid/web-osk/src/components/index.ts
  apps/financial-aid/web-osk/src/routes/application/RelationshipStatusForm/InRelationshipForm.tsx
  apps/financial-aid/web-osk/src/routes/application/RelationshipStatusForm/UnknownRelationshipForm.tsx
  apps/financial-aid/web-osk/src/routes/application/RelationshipStatusForm/relationshipStatusForm.tsx
Labels: automerge

#5981 fix(endorsement-system-api): create endorsement on list gets fullName from national registry v1 and skips metadata steps
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/bulkCreateEndorsement/bulkCreateEndorsement.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/createEndorsement.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/test/testHelpers.ts
Labels: automerge, high priority

#5967 fix(fa): Fixing file upload history
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/src/components/AppProvider/AppProvider.tsx
  apps/financial-aid/web-osk/src/routes/status/FileUpload/fileUpload.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useMyApplication.ts
  apps/financial-aid/web-veita/src/components/Timeline/TimeLineContainer.tsx
  libs/financial-aid/shared/src/components/FileList/FileList.css.ts
Labels: automerge

#5982 fix(fa): Removing double underline on link in text
  apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutFormApplicant.tsx
Labels: automerge

#5928 fix(fa): Showing accepted aid calculations and refactoring
  apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx
  apps/financial-aid/web-osk/src/components/Status/Approved.tsx
  apps/financial-aid/web-veita/src/components/AidAmountModal/AidAmountModal.tsx
  apps/financial-aid/web-veita/src/components/ApplicationHeader/ApplicationHeader.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  libs/financial-aid/shared/src/components/Breakdown/Breakdown.tsx
  libs/financial-aid/shared/src/components/index.ts
  libs/financial-aid/shared/src/lib/enums.ts
  libs/financial-aid/shared/src/lib/formatters.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#5977 feat(service-portal): add scopes to mocked user
  apps/service-portal/src/auth.ts
Labels: automerge

#5690 chore(accident-notification): Refactor of how we get values from answers
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/templates/accident-notification/src/types/index.ts
  libs/application/templates/accident-notification/src/utils/fishermanUtils.ts
  libs/application/templates/accident-notification/src/utils/getInjuredPersonInformation.ts
  libs/application/templates/accident-notification/src/utils/getWorkplaceData.ts
  libs/application/templates/accident-notification/src/utils/hasMissingDocuments.ts
  libs/application/templates/accident-notification/src/utils/hideLocationAndPurpose.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isAgricultureAccident.ts
  libs/application/templates/accident-notification/src/utils/isDateOlderThanAYear.ts
  libs/application/templates/accident-notification/src/utils/isFatalAccident.ts
  libs/application/templates/accident-notification/src/utils/isGeneralWorkplaceAccident.ts
  libs/application/templates/accident-notification/src/utils/isHealthInsured.ts
  libs/application/templates/accident-notification/src/utils/isHomeActivitiesAccident.ts
  libs/application/templates/accident-notification/src/utils/isInternshipStudiesAccident.ts
  libs/application/templates/accident-notification/src/utils/isMachineRelatedAccident.ts
  libs/application/templates/accident-notification/src/utils/isPowerOfAttorney.ts
  libs/application/templates/accident-notification/src/utils/isProfessionalAthleteAccident.ts
  libs/application/templates/accident-notification/src/utils/isReportingBehalfOfSelf.ts
  libs/application/templates/accident-notification/src/utils/isReportingOnBehalfOfChild.ts
  libs/application/templates/accident-notification/src/utils/isReportingOnBehalfOfEmployee.ts
  libs/application/templates/accident-notification/src/utils/isReportingOnBehalfOfInjured.ts
  libs/application/templates/accident-notification/src/utils/isRescueWorkAccident.ts
  libs/application/templates/accident-notification/src/utils/isStudiesAccident.ts
  libs/application/templates/accident-notification/src/utils/isUploadNow.ts
  libs/application/templates/accident-notification/src/utils/isWorkAccident.ts
Labels: automerge

#5920 feat(island-ui): add medium variant for Text component
  libs/island-ui/core/src/lib/Text/Text.css.ts
  libs/island-ui/core/src/lib/Text/Text.stories.mdx
Labels: automerge

#5819 feat(personal-representative): Base serviceAPI and database addons to auth api
  .github/CODEOWNERS
  SUMMARY.md
  apps/services/auth-api/src/environments/environment.ts
  apps/services/personal-representative/.eslintrc.json
  apps/services/personal-representative/README.md
  apps/services/personal-representative/jest.config.js
  apps/services/personal-representative/src/app/.gitkeep
  apps/services/personal-representative/src/app/app.module.ts
  apps/services/personal-representative/src/app/modules/rightTypes/e2e/rightTypes.spec.ts
  apps/services/personal-representative/src/app/modules/rightTypes/rightTypes.controller.ts
  apps/services/personal-representative/src/app/modules/rightTypes/rightTypes.module.ts
  apps/services/personal-representative/src/assets/.gitkeep
  apps/services/personal-representative/src/buildOpenApi.ts
  apps/services/personal-representative/src/environments/environment.ts
  apps/services/personal-representative/src/environments/index.ts
  apps/services/personal-representative/src/main.ts
  apps/services/personal-representative/src/openApi.ts
  apps/services/personal-representative/test/environment.jest.ts
  apps/services/personal-representative/test/setup.ts
  apps/services/personal-representative/test/testHelpers.ts
  apps/services/personal-representative/tsconfig.app.json
  apps/services/personal-representative/tsconfig.json
  apps/services/personal-representative/tsconfig.spec.json
  apps/services/personal-representative/types/index.d.ts
  jest.config.js
  libs/auth-api-lib/migrations/20211126132642-add-personal-representative-right-type-table.js
  libs/auth-api-lib/seeders/20200831152525-grants.js
  libs/auth-api-lib/sequelize.config.js
  libs/auth-api-lib/src/lib/entities/dto/personal-representative-right-type.dto.ts
  libs/auth-api-lib/src/lib/entities/models/api-scope.model.ts
  libs/auth-api-lib/src/lib/entities/models/personal-representative-right-type.model.ts
  libs/auth-api-lib/src/lib/personal-representative/index.ts
  libs/auth-api-lib/src/lib/services/personalRepresentativeRightType.service.ts
  libs/auth-api-lib/src/lib/services/sequelizeConfig.service.ts
  libs/auth/scopes/src/lib/auth.scope.ts
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#5947 fix(accident-notification): review flow errors
  libs/api/domains/health-insurance/src/lib/accident-notification.service.ts
  libs/application/templates/accident-notification/src/forms/InReviewForm/addAttachmentsSection.ts
  libs/application/templates/accident-notification/src/utils/hasMissingDocuments.ts
  libs/clients/health-insurance-v2/src/openapi.yml
Labels: automerge

#5979 feat(an): extra attachments
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/config/index.ts
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/accident-notification/src/forms/InReviewForm/addAttachmentsSection.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/attachments.ts
  libs/application/templates/accident-notification/src/utils/index.ts
Labels: automerge

#5995 fix(ci): Upgraded configcat to version 6.7.0 to fix buildbreaking bug
  package.json
  yarn.lock
Labels: automerge

#5992 chore(judicial-system): Larger textareas
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
Labels: automerge

#5998 fix(judicial-system): Fix Contentful strings ids
  apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepTwo.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
Labels: automerge

#5980 fix(judicial-sysem): Refreshes case on navigation to a new page
  apps/judicial-system/web-e2e/src/integration/Court/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/rulingStepOne.spec.ts
  apps/judicial-system/web/src/components/ConclusionDraft/ConclusionDraft.tsx
  apps/judicial-system/web/src/components/DateTime/DateTime.tsx
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Court/SharedComponents/DraftConclusionModal/DraftConclusionModal.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThree.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/RequestCourtDate/RequestCourtDate.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
Labels: automerge

#5975 fix(fa): typo
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
Labels: automerge

#5999 fix(air-discount-scheme-web): remove no longer used props from Footer
  apps/air-discount-scheme/web/components/AppLayout/AppLayout.tsx
Labels: automerge

#6000 feat(judicial-system): Defender info bubble
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
Labels: automerge

#6005 fix(skilavottord): fix failing tests
  apps/skilavottord/ws/src/app/app.module.ts
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.module.ts
  apps/skilavottord/ws/src/app/modules/auth/index.ts
  apps/skilavottord/ws/src/app/modules/index.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/test/samgongustofa.service.spec.ts
  apps/skilavottord/ws/src/app/modules/user/user.module.ts
  apps/skilavottord/ws/tsconfig.spec.json
Labels: automerge

#5989 fix(feature-flags): Allow feature flagging an entire controller/resolver
  libs/nest/feature-flags/README.md
  libs/nest/feature-flags/src/lib/feature-flag.guard.spec.ts
  libs/nest/feature-flags/src/lib/feature-flag.guard.ts
Labels: automerge

#5986 fix(service-portal): featureflag islykill
  apps/api/src/app/app.module.ts
  libs/api/domains/islykill/src/lib/graphql/main.resolver.ts
  libs/api/domains/islykill/src/lib/islykill.module.ts
  libs/feature-flags/src/lib/features.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
  scripts/build-graphql-schema.ts
Labels: automerge

#5988 fix(application-system): Tweak audit.
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/payment/payment.controller.ts
Labels: automerge

#6004 chore(judicial-system): Dead code cleanup
  apps/judicial-system/web/messages/Core/selectProsecutor.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Defendant/DefendantForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionRequest/StepTwo/StepTwoForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectProsecutor/SelectProsecutor.tsx
  apps/judicial-system/web/src/utils/useFormHelper.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#5993 fix(core): Don't mix in-memory memoization and singletons
  apps/air-discount-scheme/api/src/app/app.module.ts
  apps/financial-aid/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/app.module.ts
  libs/clients/finance/src/lib/finance.ts
  libs/clients/payment-schedule/src/lib/payment-schedule.ts
  libs/clients/payment/src/lib/payment.ts
  libs/clients/rsk/v1/src/lib/rsk.ts
  libs/nova-sms/src/lib/sms.service.ts
Labels: automerge

#6008 chore(Accident notification): Comment role for assignee for clarity
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
Labels: automerge

#5990 feat(fa): Adding seed to financial-aid-backend
  apps/financial-aid/backend/seeders/seed_user.js
  workspace.json
Labels: automerge

#6015 fix(fa): Fixing spacing in privacy text
  apps/financial-aid/web-osk/src/routes/application/AboutForm/aboutFormApplicant.tsx
Labels: automerge

#6013 fix(island-ui): Fix "div inside a p tag" warning in UploadedFile component
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
Labels: automerge

#6016 fix(fa): Children section removed in Veitu
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
Labels: automerge

#6018 fix(workspace): Restoring accidental removals
  apps/services/temporary-voter-registry-api/esbuild.json
  nx.json
  workspace.json
Labels: automerge, high priority

#5997 chore(application-templates): Removing driving-lessons template
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-lessons/.babelrc
  libs/application/templates/driving-lessons/.eslintrc
  libs/application/templates/driving-lessons/README.md
  libs/application/templates/driving-lessons/babel-jest.config.json
  libs/application/templates/driving-lessons/jest.config.js
  libs/application/templates/driving-lessons/src/forms/Approved.ts
  libs/application/templates/driving-lessons/src/forms/DrivingLessonsApplication.ts
  libs/application/templates/driving-lessons/src/forms/PendingReview.ts
  libs/application/templates/driving-lessons/src/forms/Rejected.ts
  libs/application/templates/driving-lessons/src/forms/ReviewApplication.ts
  libs/application/templates/driving-lessons/src/forms/messages.ts
  libs/application/templates/driving-lessons/src/index.ts
  libs/application/templates/driving-lessons/src/lib/DrivingLessonsTemplate.ts
  libs/application/templates/driving-lessons/tsconfig.json
  libs/application/templates/driving-lessons/tsconfig.lib.json
  libs/application/templates/driving-lessons/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#6009 fix(web): fix process entry links that are using NextLink
  apps/web/next.config.js
  libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx
Labels: automerge

#6023 fix(skilavottord): RecyclingRequestTypes argument for resolver
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
Labels: automerge

#6024 fix(web): Process Entries linking to external
  apps/web/next.config.js
  libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx
  libs/island-ui/core/src/lib/BulletList/BulletList.css.ts
  libs/island-ui/core/src/lib/BulletList/BulletList.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
  libs/island-ui/core/src/lib/Text/Text.css.ts
Labels: automerge

#5937 feat(judicial-system): Makes registrars optional
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/messages/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web-e2e/src/integration/Court/hearingArrangements.spec.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#6017 fix(web): add missing type from cleared categories filter
  apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.tsx
Labels: automerge

#6014 feat(fa): Guards tested in staff controller
  apps/financial-aid/backend/jest.config.js
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getStaffControllerGuards.spec.ts
  apps/financial-aid/backend/test/setup.ts
  apps/financial-aid/backend/tsconfig.spec.json
Labels: automerge
