Repository island-is/island.is, pull requests merged in 2022-06, with the labels that each got.

#7556 feat(j-s): Iteration on the modify ruling page
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/api/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdf.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/modifyRuling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/modifyRuling.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/ruling.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/ruling.ts
  apps/judicial-system/web/src/components/Decision/Decision.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.tsx
Labels: automerge

#7587 fix(skilavottord): add more logs (#7586)
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge, deploy-feature

#7584 fix(fa): Fix missing municipality page
  libs/application/templates/financial-aid/src/forms/MuncipalityNotRegistered.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
Labels: automerge

#7570 feat(fa): Autofill spouse email
  libs/application/templates/financial-aid/src/fields/ContactInfo/ContactInfo.tsx
Labels: automerge

#7566 fix(fa): Add placeholder texts for bank info inputs
  libs/application/templates/financial-aid/src/fields/BankInfoForm/BankInfoForm.tsx
  libs/application/templates/financial-aid/src/lib/messages/bankInfoForm.ts
Labels: automerge

#7588 fix(skuldleysisvottord): Change error message if not debtless
  libs/application/templates/no-debt-certificate/src/dataProviders/NoDebtCertificateProvider.ts
  libs/application/templates/no-debt-certificate/src/lib/messages.ts
Labels: automerge

#7543 feat(core): Contentful entry tagging service
  .github/CODEOWNERS
  SUMMARY.md
  apps/services/contentful-entry-tagger/.eslintrc.json
  apps/services/contentful-entry-tagger/README.md
  apps/services/contentful-entry-tagger/infra/contentful-entry-tagger-service.ts
  apps/services/contentful-entry-tagger/jest.config.js
  apps/services/contentful-entry-tagger/src/app/.gitkeep
  apps/services/contentful-entry-tagger/src/app/app.controller.ts
  apps/services/contentful-entry-tagger/src/app/app.module.ts
  apps/services/contentful-entry-tagger/src/app/app.repository.ts
  apps/services/contentful-entry-tagger/src/app/app.service.ts
  apps/services/contentful-entry-tagger/src/app/types.ts
  apps/services/contentful-entry-tagger/src/assets/.gitkeep
  apps/services/contentful-entry-tagger/src/main.ts
  apps/services/contentful-entry-tagger/tsconfig.app.json
  apps/services/contentful-entry-tagger/tsconfig.json
  apps/services/contentful-entry-tagger/tsconfig.spec.json
  charts/islandis/values.dev.yaml
  infra/src/uber-charts/islandis.ts
  jest.config.js
  nx.json
  package.json
  workspace.json
  yarn.lock
Labels: automerge

#7560 fix(driving-license-servive): Handle temporary license resubmit
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/driving-license/src/v2/clientConfig.json
Labels: automerge

#7589 feat(service-portal): Update vehicle service
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
Labels: automerge

#7579 fix(j-s): Update lost contentful strings ids
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
Labels: automerge

#7510 feat(j-s): send prison admin link instead of email attachment
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7597 feat(service-portal): Hotfix vehicle additions.
  apps/service-portal/src/auth.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/clients/vehicles/src/lib/vehiclesClient.service.ts
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/utils/dateUtils.ts
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/vehicles/src/components/DetailTable/CoOwnerInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/Column.tsx
  libs/service-portal/vehicles/src/components/DetailTable/FeeInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/InspectionInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OperatorInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OwnerInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OwnersTable.tsx
  libs/service-portal/vehicles/src/components/DetailTable/RegistrationInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/TechnicalInfoItem.tsx
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/index.ts
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/mock/BasicVehicleInformation-permno=RIF88.json
  libs/service-portal/vehicles/src/mock/vehicleSearch-permno=RIF88.json
  libs/service-portal/vehicles/src/mock/vehiclesForPersidno-requestedPersidNo=2811882089.json
  libs/service-portal/vehicles/src/mock/vehiclesList.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicles.ts
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/utils/displayWithUnit.ts
  workspace.json
Labels: automerge

#7561 chore(driving-licence-book): Refactor configModule for driving licence and driving licence book
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/environments/environment.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.module.ts
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.module.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-school-confirmation/driving-school-confirmation.module.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/application/templates/driving-school-confirmation/README.md
  libs/clients/driving-license-book/README.md
  libs/clients/driving-license-book/src/clientConfig.json
  libs/clients/driving-license/README.md
  libs/clients/driving-license/src/index.ts
  libs/clients/driving-license/src/lib/apiConfiguration.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.module.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#7573 fix(j-s): Error message doesn't go away after successfully uploading a file that previously failed to upload
  apps/judicial-system/web-e2e/src/fixtures/createFileMutationResponse.json
  apps/judicial-system/web-e2e/src/fixtures/createPresignedPostMutationResponse.json
  apps/judicial-system/web-e2e/src/fixtures/lorem-ipsum.txt
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/caseFiles.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/caseFiles.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web-e2e/tsconfig.json
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFiveForm.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
  package.json
  yarn.lock
Labels: automerge

#7289 feat(financial-statements-inao): financial statements inao template init
  .github/CODEOWNERS
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/financial-statements-inao/.babelrc
  libs/application/templates/financial-statements-inao/.eslintrc
  libs/application/templates/financial-statements-inao/README.md
  libs/application/templates/financial-statements-inao/babel-jest.config.json
  libs/application/templates/financial-statements-inao/codegen.yml
  libs/application/templates/financial-statements-inao/jest.config.js
  libs/application/templates/financial-statements-inao/src/components/Logo.tsx
  libs/application/templates/financial-statements-inao/src/components/index.ts
  libs/application/templates/financial-statements-inao/src/dataProviders/index.ts
  libs/application/templates/financial-statements-inao/src/fields/Done/Success.tsx
  libs/application/templates/financial-statements-inao/src/fields/Done/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionStatement/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/Overview/ValueLine.tsx
  libs/application/templates/financial-statements-inao/src/fields/Overview/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/index.ts
  libs/application/templates/financial-statements-inao/src/forms/application/application.ts
  libs/application/templates/financial-statements-inao/src/forms/application/index.ts
  libs/application/templates/financial-statements-inao/src/forms/application/personalElection/clientInfoSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/keyNumbers/keyNumbersSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/overviewSection.tsx
  libs/application/templates/financial-statements-inao/src/forms/done.ts
  libs/application/templates/financial-statements-inao/src/index.ts
  libs/application/templates/financial-statements-inao/src/lib/constants.ts
  libs/application/templates/financial-statements-inao/src/lib/financialStatementsInao.ts
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/dataSchema.ts
  libs/application/templates/financial-statements-inao/tsconfig.json
  libs/application/templates/financial-statements-inao/tsconfig.lib.json
  libs/application/templates/financial-statements-inao/tsconfig.spec.json
  libs/feature-flags/src/lib/features.ts
  nx.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: automerge

#7576 fix(data-protection-complaint): Updating PDF
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/complaint.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfUtils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeRepeaterItem.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Sections.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Shared.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/messagesUtils.ts
  libs/application/templates/data-protection-complaint/src/fields/ReasonsForComplaint.tsx
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/index.ts
  libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/complaint.ts
  libs/application/templates/data-protection-complaint/src/shared/mappers.ts
Labels: automerge

#7442 feat(login-service): company search
  libs/application/templates/login-service/src/fields/InformationAboutApplication/InformationAboutApplication.tsx
  libs/application/templates/login-service/src/fields/index.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/templates/login-service/src/lib/dataSchema.ts
  libs/application/templates/login-service/src/lib/messages/applicant.ts
  libs/application/templates/login-service/src/lib/messages/errors.ts
  libs/shared/form-fields/src/lib/CompanySearchController/CompanySearchController.tsx
Labels: automerge

#7607 fix(driving-license-servive): Handle temporary license resubmit (#7560)
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/driving-license/src/v2/clientConfig.json
Labels: automerge

#7609 fix(parental-leave): fix rights calculator
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7517 feat(j-s): rename restrictedCase to limitedAccessCase
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
  apps/judicial-system/api/src/app/modules/case/case.module.ts
  apps/judicial-system/api/src/app/modules/case/limitedAccessCase.resolver.ts
  apps/judicial-system/api/src/app/modules/file/file.module.ts
  apps/judicial-system/api/src/app/modules/file/limitedAccessFile.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/guards/limitedAccessCaseExists.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessCaseExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalId.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getById.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfRolesRules.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/PdfRow/PdfRow.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverviewForm.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#7507 chore(j-s): rename env variable
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/modules/case/case.config.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#7611 chore(system-e2e): Making the System E2E tests target localhost by default
  apps/system-e2e/cypress.json
  apps/system-e2e/src/integration/service-portal.spec.ts
  apps/system-e2e/src/integration/web.spec.ts
  apps/system-e2e/src/plugins/index.js
Labels: automerge

#7613 fix(parental-leave): fix rights calculator (#7609)
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: deploy-feature

#7600 chore(service-portal): Add vehicle extract strings
  libs/service-portal/vehicles/src/lib/messages.ts
  workspace.json
Labels: automerge

#7608 chore(user-notification): Remove unnecessary error throwing
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
  apps/services/user-profile/src/app/user-profile/userToken.controller.ts
Labels: automerge

#7618 fix(service-portal): using permno instead of regno
  libs/api/domains/vehicles/src/dto/getVehicleDetailInput.ts
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
Labels: automerge

#7624 fix(parental-leave): db intact on spouse approval
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#7627 fix(web): Removed unused runtime config from Homestay page
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
Labels: automerge

#7628 fix(web): Hotfix - Removed unused runtime config from Homestay page (#7627)
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
Labels: automerge

#7629 fix(driving-license): Fix env names
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/driving-license/README.md
  libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
Labels: automerge

#7619 feat(j-s): report errors when creating cases through x-road
  apps/judicial-system/xrd-api/src/app/app.config.ts
  apps/judicial-system/xrd-api/src/app/app.module.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/test/create.spec.ts
  apps/judicial-system/xrd-api/src/app/test/createTestingAppModule.ts
  apps/judicial-system/xrd-api/src/environments/environment.ts
Labels: automerge

#7643 fix(application-system): Adding conficat dependencies
  apps/application-system/api/esbuild.json
Labels: automerge

#7646 fix(ci): Config Values run on release branch creation
  .github/workflows/config-values.yaml
Labels: automerge

#7632 feat(parental leave): add sms notification to employer on form submit
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#7648 fix(j-s): Updates Helm Charts
  apps/judicial-system/xrd-api/infra/judicial-system-xrd-api.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#7633 fix(contentful-entry-tagger): Health checks for contentful-entry-tagging service
  apps/services/contentful-entry-tagger/infra/contentful-entry-tagger-service.ts
  apps/services/contentful-entry-tagger/src/app/app.controller.ts
  apps/services/contentful-entry-tagger/src/app/app.middleware.ts
  apps/services/contentful-entry-tagger/src/app/app.module.ts
  apps/services/contentful-entry-tagger/src/app/health.controller.ts
  apps/services/contentful-entry-tagger/src/main.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#7645 fix(j-s): only check failed courtRecord upload when not modifying ruling
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#7639 feat(web): Hide the Watson chat bot launcher if the locale is not 'is'
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
Labels: automerge

#7569 feat(core): clean up delegationType claims & remove nat
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
  apps/services/auth-public-api/src/app/modules/resources/scopes.controller.spec.ts
  apps/services/auth-public-api/test/setup.ts
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
  libs/auth-nest-tools/src/lib/auth.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/shared/types/src/lib/user.ts
Labels: automerge

#7653 fix(data-protection-complaint): fixes after qa session
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/providers/applicationAttachmentProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/providers/pdfFileProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/complaint.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeTable.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Sections.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/Shared.tsx
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/info.ts
Labels: automerge

#7634 feat(fa): Add email to timeline
  apps/financial-aid/api/src/app/modules/application/models/applicationEvent.model.ts
  apps/financial-aid/backend/migrations/20220607111519-application_events-add-notification-email-sent.js
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/dto/createApplicationEvent.dto.ts
  apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/update.spec.ts
  apps/financial-aid/backend/src/app/modules/applicationEvent/models/applicationEvent.model.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/History/History.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/components/Timeline/ChatElement.tsx
  apps/financial-aid/web-veita/src/components/Timeline/EmailElement.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7649 fix(application-system): link around header icon
  apps/application-system/form/src/components/Header/Header.tsx
Labels: automerge

#7553 fix(web): Sub Article language toggle
  apps/web/components/LanguageToggler/LanguageToggler.tsx
  apps/web/screens/queries/Article.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/models/contentSlug.model.ts
Labels: automerge

#7657 fix(auth-react): Disabling automatic access token refresh
  libs/auth/react/src/lib/AuthSettings.spec.ts
  libs/auth/react/src/lib/AuthSettings.ts
Labels: automerge

#7659 fix(auth-react): HOTFIX Auth React automatic token refresh
  libs/auth/react/src/lib/AuthSettings.spec.ts
  libs/auth/react/src/lib/AuthSettings.ts
Labels: automerge

#7663 fix(service-portal): Datepicker and finance loading
  libs/service-portal/core/src/screens/DynamicWrapper/DynamicWrapper.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.css.ts
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/Finance.css.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: automerge

#7652 fix(service-portal): Fix local tax tab check
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
Labels: automerge

#7626 fix(service-portal): Add more detailed logging for userprofile service
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/service-portal/graphql/src/hooks/profile/useUpdateOrCreateUserProfile.ts
Labels: automerge, deploy-feature

#7660 chore(infra): Revert #7580 split auth-api and IDS
  charts/auth-api/values.dev.yaml
  charts/auth-api/values.prod.yaml
  charts/auth-api/values.staging.yaml
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  infra/src/uber-charts/all-charts.ts
  infra/src/uber-charts/auth-api.ts
  infra/src/uber-charts/identity-server.ts
Labels: automerge

#7665 fix(service-portal): Settings and minor finance
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/graphql/src/hooks/profile/useUpdateOrCreateUserProfile.ts
Labels: automerge

#7670 fix(service-portal): Hide insurance
  libs/service-portal/vehicles/src/components/DetailTable/FeeInfoItem.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
Labels: automerge

#7644 refactor(service-portal): vehicles cleanup
  libs/api/domains/vehicles/README.md
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
Labels: automerge

#7672 fix(j-s): Fix a broken back link on ruling page
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
Labels: automerge

#7655 feat(web): Organization page, sidebar card images
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/sidebarCard.model.ts
Labels: automerge

#7656 feat(web): Organization page - only show secondary menu if there are any items
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#7668 fix(skuldleysisvottord): fix error message and increase timeout (again)
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/application/templates/no-debt-certificate/src/dataProviders/NoDebtCertificateProvider.ts
  libs/application/templates/no-debt-certificate/src/lib/messages.ts
  libs/clients/finance/src/lib/FinanceClientConfig.ts
  libs/clients/finance/src/lib/FinanceClientService.ts
Labels: automerge

#7676 fix(infra): Missing env vars that fail startups for IDS and auth-api
  apps/services/auth-api/infra/auth-api.ts
  apps/services/auth-api/infra/identity-server.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#7674 fix(web): Article group href mismatch
  apps/web/screens/Category/Category/Category.tsx
Labels: automerge

#7678 feat(application-system): redirect to service portal form field
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/types/Fields.ts
  libs/application/templates/reference-template/src/forms/ExampleForm.ts
  libs/application/ui-fields/src/lib/RedirectToServicePortalFormField/RedirectToServicePortalFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
Labels: automerge

#7582 test(web): Adding tests for life events
  apps/system-e2e/src/integration/web.spec.ts
  apps/web/components/IconTitleCard/IconTitleCard.tsx
  apps/web/components/LifeEventsSection/LifeEventsSection.tsx
Labels: automerge

#7679 feat(service-portal): remove "eldri utgafa"
  apps/service-portal-e2e/src/integration/app.spec.ts
  apps/service-portal/src/components/Greeting/Greeting.tsx
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#7677 fix(parental-leave): Add validation on startDate on OtherParent's approval and employer's approval
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
  libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
Labels: automerge

#7673 feat(j-s): Use police star icon for prosecutor offices
  apps/judicial-system/web/src/components/Logo/Logo.tsx
  apps/judicial-system/web/src/components/Logo/PoliceStar.tsx
Labels: automerge

#7685 fix(api): setting feature flag for INAO_client
  apps/api/infra/api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/features.ts
  infra/src/environments.ts
Labels: automerge

#7683 feat(parental leave): add sms notification to other parent on submit
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#7691 chore(j-s): Turn off Email Upload
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7693 refactor(service-portal): use data-testid instaed of id
  apps/service-portal-e2e/src/integration/app.spec.ts
  apps/service-portal/src/components/Greeting/Greeting.tsx
Labels: automerge

#7686 feat(web): Fiskistofa header
  apps/web/components/Organization/Wrapper/FiskistofaTheme/FiskistofaHeader.css.ts
  apps/web/components/Organization/Wrapper/FiskistofaTheme/FiskistofaHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#7681 fix(infra): Allow other than string type in extraAttributes, increase contextDeadline on auth-admin-web add missing env/secrets
  .github/workflows/push.yml
  apps/auth-admin-web/infra/auth-admin-web.ts
  apps/services/auth-api/infra/auth-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  infra/src/dsl/types/input-types.ts
Labels: automerge, deploy-feature

#7605 fix(service-portal): string issues
  libs/application/core/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#7700 feat(infra): Add deployment step for IDS
  .github/workflows/push.yml
Labels: automerge

#7606 refactor(service-portal): move delegation + logout buttons
  apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/LogOutItem.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.css.ts
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/settings/access-control/src/components/Accesses/Accesses.tsx
  libs/service-portal/settings/access-control/src/index.ts
  libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx
  libs/shared/components/src/auth/UserMenu/UserDropdown.tsx
  libs/shared/components/src/auth/UserMenu/UserMenu.spec.tsx
  libs/shared/components/src/auth/UserMenu/UserProfileInfo.tsx
Labels: automerge, deploy-feature

#7702 fix(infra): Revert "Add deployment step for IDS"
  .github/workflows/push.yml
Labels: automerge

#7701 feat(service-portal): add profile information
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Labels: automerge

#7689 fix(j-s): Use non-signed verdict when modifying a ruling
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/api/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdf.spec.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfRow.css.ts
  apps/judicial-system/web/src/components/PdfRow/PdfRow.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#7705 infra: Pinning the dependencies for those using Volta - https://volta.sh
  package.json
Labels: automerge

#7697 feat(web): Rank increase for articles in search results
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge

#7650 feat(j-s): remove feature flag for modify ruling
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/web/src/components/FeatureProvider/FeatureProvider.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/types/src/lib/feature.ts
Labels: automerge

#6645 feat(application-system): delegations
  SUMMARY.md
  apps/application-system/api/migrations/20222102112600-add-actors-col.js
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/dto/application.response.dto.ts
  apps/application-system/api/src/app/modules/application/e2e/delegationGuard.spec.ts
  apps/application-system/api/src/app/modules/application/guards/delegation.guard.ts
  apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  apps/application-system/api/src/app/modules/application/utils/delegationUtils.ts
  apps/application-system/form/src/routes/Application.tsx
  apps/application-system/form/src/routes/Applications.tsx
  handbook/reference/problems/README.md
  handbook/reference/problems/bad-subject.md
  libs/api/domains/application/src/lib/application.model.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
  libs/api/mocks/src/domains/applications/factories.ts
  libs/application/api/core/src/lib/application/application.model.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.spec.ts
  libs/application/core/src/lib/dataProviderUtils.spec.ts
  libs/application/core/src/lib/formUtils.spec.ts
  libs/application/core/src/lib/messages.ts
  libs/application/core/src/types/Application.ts
  libs/application/core/src/types/ApplicationTemplate.ts
  libs/application/graphql/src/index.ts
  libs/application/graphql/src/lib/fragments/application.ts
  libs/application/graphql/src/lib/queries/actorDelegations.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.spec.ts
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.spec.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/templates/reference-template/README.md
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
  libs/application/ui-shell/src/index.ts
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/types.ts
  libs/feature-flags/src/lib/features.ts
  libs/nest/problem/src/index.ts
  libs/nest/problem/src/lib/BadSubject.ts
  libs/shared/problem/src/Problem.ts
  libs/shared/problem/src/ProblemType.ts
  libs/shared/problem/src/problems.ts
  libs/testing/fixtures/src/lib/application.ts
  libs/testing/nest/src/index.ts
  libs/testing/nest/src/lib/requestMethod.ts
  workspace.json
Labels: automerge, deploy-feature

#7242 feat(service-portal): Block access if legal guardian & child >= 16 years
  libs/auth/react/src/lib/Authenticator/Authenticator.state.ts
  libs/auth/react/src/lib/utils/getBirthday.spec.ts
  libs/auth/react/src/lib/utils/getBirthday.ts
  libs/service-portal/documents/src/index.ts
  libs/shared/types/src/lib/user.ts
Labels: automerge, deploy-feature

#7704 fix(skuldleysisvottord): Remove feature flag
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#7554 feat(passport): Passport Application
  .github/CODEOWNERS
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  libs/application/templates/passport/src/dataProviders/DistrictsProvider.ts
  libs/application/templates/passport/src/dataProviders/FeeInfoProvider.ts
  libs/application/templates/passport/src/dataProviders/IdentityDocumentProvider.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/fields/AuthWarning/index.tsx
  libs/application/templates/passport/src/fields/PaymentCharge/index.tsx
  libs/application/templates/passport/src/fields/PaymentPending/index.tsx
  libs/application/templates/passport/src/fields/index.ts
  libs/application/templates/passport/src/forms/Approved.ts
  libs/application/templates/passport/src/forms/Done.ts
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/Payment.tsx
  libs/application/templates/passport/src/forms/messages.ts
  libs/application/templates/passport/src/index.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/constants.ts
  libs/application/templates/passport/src/lib/dataSchema.ts
  libs/application/templates/passport/src/lib/error.ts
  libs/application/templates/passport/src/lib/messages.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge, deploy-feature

#7714 chore(web): Removed phone and email field from landlaeknir footer since it can be displayed via footer item
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
Labels: automerge

#7703 feat(infra): Add workflow for IDS
  .github/workflows/push.yml
Labels: automerge, deploy-feature

#7471 feat(skilavottord): update recycling-partner model
  apps/skilavottord/web/screens/RecyclingCompanies/components/RecyclingCompanyForm/RecyclingCompanyForm.tsx
  apps/skilavottord/ws/migrations/20220318210715-alow-null-recycling-partners.js
  apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.input.ts
  apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.model.ts
Labels: automerge

#7671 feat(j-s): Set court date again
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdf.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/src/components/CourtArrangements/index.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#7717 feat(web): Custom chat for evrópska sjúkratryggingarkortið article
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#7690 fix(service-portal): Update email + tel profile state on deletion
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
Labels: automerge, deploy-feature

#7716 fix(fa): Only show second part of approved comment
  libs/application/templates/financial-aid/src/fields/Status/ApprovedAlert/ApprovedAlert.tsx
Labels: automerge

#7707 refactor(j-s): move modify date modal to seperate component
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.spec.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/formHelper.spec.ts
  apps/judicial-system/web/src/utils/formHelper.ts
Labels: automerge

#7333 feat(service-portal): Inbox UI updates
  libs/api/domains/documents/src/lib/documentBuilder.ts
  libs/api/domains/documents/src/lib/models/document.model.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/HeaderArrow/HeaderArrow.css.ts
  libs/service-portal/documents/src/components/HeaderArrow/HeaderArrow.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.css.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/messages.ts
  libs/service-portal/graphql/src/lib/queries/listDocuments.ts
Labels: automerge, deploy-feature

#7596 feat(web): Organization slice padding changes
  apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
  apps/web/components/Organization/Slice/OrganizationSlice.tsx
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/components/Organization/Slice/TwoColumnText/TwoColumnTextSlice.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/oneColumnText.model.ts
  libs/cms/src/lib/models/twoColumnText.model.ts
Labels: automerge, deploy-feature

#7502 feat(web): Cleared watson chat session storage on organization page
  apps/web/components/Organization/Wrapper/config.ts
Labels: automerge

#7723 feat: add bullet to login screen
  apps/web/components/Login/LoginTexts.types.ts
  apps/web/components/Login/svgLogin.tsx
  apps/web/screens/Login/Login.tsx
Labels: automerge

#7708 chore(ci): Upgrade cypress runner in container
  scripts/ci/Dockerfile.cypress
Labels: automerge, deploy-feature

#7572 fix(island-ui): Update invalid svg attributes
  libs/island-ui/core/src/lib/IconRC/icons/QRCodeOutline.tsx
Labels: automerge

#7727 refactor(system-e2e): restructuring system E2E tests to be feature-focused
  apps/system-e2e/entrypoint.sh
  apps/system-e2e/src/integration/air-discount-scheme-web.spec.ts
  apps/system-e2e/src/integration/application-system-form.spec.ts
  apps/system-e2e/src/integration/auth-admin-web.spec.ts
  apps/system-e2e/src/integration/island-ui-storybook.spec.ts
  apps/system-e2e/src/integration/judicial-system-web.spec.ts
  apps/system-e2e/src/integration/service-portal/homepage.spec.ts
  apps/system-e2e/src/integration/skilavottord-web.spec.ts
  apps/system-e2e/src/integration/web/homepage.spec.ts
Labels: automerge

#7724 test(web): Search results
  apps/system-e2e/src/integration/web/search.spec.ts
  apps/web/components/Card/Card.tsx
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/components/SearchSection/SearchSection.tsx
  apps/web/screens/Search/Search.tsx
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
  libs/island-ui/utils/src/index.ts
  libs/island-ui/utils/src/lib/testSupport.ts
Labels: automerge

#7729 feat(parental leave): send sms to applicant on spouse rejection
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#7733 feat(fa): Add ApprovedAlert to Ósk
  apps/financial-aid/web-osk/src/components/ApprovedAlert/ApprovedAlert.tsx
  apps/financial-aid/web-osk/src/components/Status/Approved.tsx
  apps/financial-aid/web-osk/src/components/index.ts
  apps/financial-aid/web-osk/src/routes/status/MainPage/mainPage.tsx
Labels: automerge

#7732 feat(j-s): new police star in requestPDF
  apps/judicial-system/backend/src/app/formatters/policeStar.ts
Labels: automerge

#7741 chore(j-s): Disable Queuing
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
Labels: automerge

#7740 fix(infra): Fix env vars for auth-api/auth-public-api
  apps/services/auth-api/infra/auth-api.ts
  apps/services/auth-public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  infra/src/environments.ts
Labels: automerge

#7614 chore(j-s): Refactor autofill
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
Labels: automerge

#7745 fix(driving-license-api): versioning on prod
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#7747 feat(web): Added support for fetching english related articles (#7719)
  libs/cms/src/lib/cms.resolver.ts
Labels: automerge

#7737 chore(service-portal): Add more details to vehicle logging
  libs/api/domains/vehicles/README.md
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Labels: automerge

#7749 fix(parental leave): period and other parent bugs
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
Labels: automerge, deploy-feature

#7722 chore(j-s): Allow five digits in court case number
  apps/judicial-system/web/src/utils/validate.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#7752 feat(ads): Polling every minute instead of every ten seconds
  apps/air-discount-scheme/web/screens/Subsidy/components/Benefits/Benefits.tsx
Labels: automerge

#7759 fix(parental-leave): change otherParent type (#7756)
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge, deploy-feature

#7736 fix(infra): Allow MissingSetting in ingress, use it in personal-representative staging/prod demo alb's
  apps/services/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/map-to-values.ts
Labels: automerge

#7710 refactor(service-portal): refactoring sidebar code
  apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/Chevron.tsx
  apps/service-portal/src/components/Sidebar/NavItem/LogOutItem.tsx
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  apps/service-portal/src/components/Sidebar/NavItem/SubNavItem.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.css.ts
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
  apps/service-portal/src/components/Sidebar/SubNavModal.css.ts
  apps/service-portal/src/components/Sidebar/SubNavModal.tsx
Labels: automerge

#7755 fix(ids): missing dogstatd annotation
  apps/services/auth-api/infra/identity-server.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#7715 fix(skuldleysisvottord): Add possibility to hide submit error for specific
  libs/application/core/src/lib/dataProviderUtils.ts
  libs/application/core/src/types/DataProviderResult.ts
  libs/application/templates/no-debt-certificate/src/dataProviders/NoDebtCertificateProvider.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
  libs/application/ui-shell/src/utils.ts
Labels: automerge

#7754 feat(parental leave): send notification sms to applicant on employer reject
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#7762 fix(infra): Auth-api using wrong configuration
  apps/services/auth-api/infra/auth-api.ts
  charts/identity-server/values.prod.yaml
Labels: automerge

#7761 fix(auth-admin-web): Adding IDS secret in infra
  apps/auth-admin-web/infra/auth-admin-web.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#7764 fix(ci): Fix IDS deployment
  .github/workflows/push.yml
Labels: automerge

#7765 fix(infra): IDS DSL and configuration fixes
  apps/auth-admin-web/infra/auth-admin-web.ts
  apps/services/auth-api/infra/auth-api.ts
  apps/services/auth-api/infra/identity-server.ts
  apps/services/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/map-to-values.ts
Labels: automerge

#7772 fix(service-portal): login old url
  apps/web/components/Login/LoginTexts.types.ts
  apps/web/screens/Login/Login.tsx
Labels: automerge

#7770 fix(service-portal): Increase islykill service timeout
  .github/CODEOWNERS
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/clients/islykill/src/lib/islykill.module.ts
Labels: automerge

#7763 fix(j-s): temporarly disable queue
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
Labels: automerge

#7777 test(web): home page basic tests
  apps/system-e2e/cypress.json
  apps/system-e2e/src/integration/web/homepage.spec.ts
  apps/web/components/NewsItems/NewsItems.tsx
  apps/web/components/SearchSection/SearchSection.tsx
  libs/island-ui/core/src/lib/Text/Text.tsx
Labels: automerge

#7731 fix(web): Fixed how we compare urls to activate menu links in sidebar on Organization subpages
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#7492 feat(application system): add optional feature for handling rejected file uploads
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/types/Fields.ts
  libs/application/ui-components/src/components/InputImageUpload/InputImageUpload.tsx
  libs/application/ui-fields/src/lib/FileUploadFormField/FileUploadFormField.tsx
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
  libs/shared/form-fields/src/lib/FileUploadController/index.tsx
Labels: automerge

#7787 feat(parental leave): file upload max size error
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#7786 fix(infra): Remove enable-global-auth for auth-admin-web staging
  apps/auth-admin-web/infra/auth-admin-web.ts
  charts/identity-server/values.staging.yaml
Labels: automerge

#7774 feat(web): Fiskistofa footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaHeader.tsx
Labels: automerge

#7798 chore(service-portal): hotfix - Update client config in islyklar service
  libs/clients/islykill/src/clientConfig.yaml
Labels: automerge

#7793 feat(service-portal): Adding license and education-license scopes to service-portal for legal guardian support
  apps/service-portal/src/auth.ts
  libs/api/domains/education/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/auth-api-lib/seeders/data/scope-education-license.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/education-license/src/index.ts
  libs/service-portal/licenses/src/index.ts
Labels: automerge

#7804 fix(ci): search feature e2e tests
  apps/system-e2e/src/integration/web/search.spec.ts
Labels: automerge

#7811 fix(service-portal): Adding missing licenses scope in requested scopes.
  apps/service-portal/src/auth.ts
Labels: automerge

#7769 fix(j-s): include tests files in ts build
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/tsconfig.json
Labels: automerge

#7809 chore(j-s): Disable Queuing on Backend
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
Labels: automerge

#7805 infra(skilavottord): adding DataDog RUM integration to frontend
  apps/skilavottord/web/next.config.js
  apps/skilavottord/web/pages/_app.tsx
Labels: automerge, deploy-feature

#7815 fix(api): hotfix - Provide getIdentityWithFallback method in identity service (#7718)
  libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
  libs/api/domains/identity/src/lib/identity.resolver.ts
  libs/api/domains/identity/src/lib/identity.service.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
Labels: automerge

#7816 fix(web): Fix styles for Fiskistofa footer
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.tsx
Labels: automerge

#7819 chore(infra): increase resources for api and auth-api
  apps/api/infra/api.ts
  apps/services/auth-api/infra/auth-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#7810 feat(service-portal): Adding scopes to enable education-license and license for legal guardian
  apps/service-portal/src/auth.ts
  libs/api/domains/education/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/auth-api-lib/seeders/data/scope-education-license.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/education-license/src/index.ts
  libs/service-portal/licenses/src/index.ts
Labels: automerge

#7797 fix(infra): Remove enable-global-auth for auth-admin-web staging (#7786)
  apps/auth-admin-web/infra/auth-admin-web.ts
  charts/identity-server/values.staging.yaml
Labels: automerge

#7817 feat(applications-institution-collaboration): Add company search into the form flow
  libs/application/templates/institution-collaboration/src/fields/ReviewScreen/ReviewScreen.tsx
  libs/application/templates/institution-collaboration/src/forms/application.ts
  libs/application/templates/institution-collaboration/src/lib/template.ts
  libs/clients/data-protection-complaint/src/lib/data-protection-complaint.module.ts
Labels: automerge

#7766 chore(application-login-service): Implement new company search in login service
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/types/Fields.ts
  libs/application/templates/login-service/src/fields/InformationAboutApplication/InformationAboutApplication.tsx
  libs/application/templates/login-service/src/fields/IsatInvalid/IsatInvalid.tsx
  libs/application/templates/login-service/src/fields/index.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/templates/login-service/src/lib/dataSchema.ts
  libs/application/templates/login-service/src/lib/messages/applicant.ts
  libs/application/templates/login-service/src/lib/messages/application.ts
  libs/application/templates/login-service/src/lib/messages/errors.ts
  libs/application/templates/login-service/src/lib/messages/index.ts
  libs/application/templates/login-service/src/lib/messages/selectCopmany.ts
  libs/application/ui-components/codegen.yml
  libs/application/ui-components/src/components/CompanySearchController/CompanySearchController.tsx
  libs/application/ui-components/src/components/CompanySearchController/CompanySearchItem.tsx
  libs/application/ui-components/src/components/CompanySearchController/companySearchController.graphql.ts
  libs/application/ui-components/src/index.ts
  libs/application/ui-components/src/types.ts
  libs/application/ui-fields/src/lib/CompanySearchFormField/CompanySearchFormField.tsx
  libs/shared/form-fields/src/index.ts
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
  workspace.json
Labels: automerge

#7799 feat(web): HSN footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.tsx
Labels: automerge

#7826 fix(e2e): expose TEST_ENVIRONMENT in cypress logs, remove default bas…
  apps/system-e2e/cypress.json
  apps/system-e2e/entrypoint.sh
Labels: automerge

#7739 feat(j-s): fetch parent case files
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/caseFiles.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/caseFiles.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/ParentCaseFiles/ParentCaseFiles.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFiveForm.tsx
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
Labels: automerge

#7807 fix(application-system): Submit button spacing
  libs/application/ui-shell/src/components/ScreenFooter.tsx
Labels: automerge

#7790 chore(j-s): Autofilling conclusion in investigation cases
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/ruling.spec.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
Labels: automerge

#7818 chore(j-s): All types of investigation cases can now have multiple defendants
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/DefendantForm.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#7829 fix(application-system): Button spacing
  libs/application/ui-shell/src/components/ScreenFooter.tsx
Labels: automerge
