Repository island-is/island.is, pull requests merged in 2022-09, with the labels that each got.

#8308 fix(p-sign-application): Email and phone from user profile and answer…
  libs/application/templates/p-sign/src/forms/applicationSections/sectionInformation.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionOverview.ts
Labels: automerge

#8307 fix(mortgage-certificate): buttons to span
  libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx
  libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx
  tsconfig.base.json
Labels: automerge

#8309 feat(financial-statements-inao): Client Financial Limit
  libs/api/domains/financial-statements-inao/src/lib/dto/clientFinancialLimit.input.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
Labels: automerge

#8310 fix(fa): Fix the data sent to nav and the error text
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
Labels: automerge

#8252 feat(service-portal): Vehicle owned cars Excel
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/vehicles/src/queries/getUsersVehicles.ts
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/utils/dataHeaders.ts
  libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Labels: automerge

#8315 chore(j-s): Hotfixes for 17.2
  apps/judicial-system/backend/migrations/20220824084711-update-case.js
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/test/create.spec.ts
Labels: automerge

#8316 fix(parental-leave): approved state texts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#8296 chore(j-s): Court API Availability
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  libs/judicial-system/court-client/src/lib/courtClient.config.ts
  libs/judicial-system/court-client/src/lib/courtClient.module.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
  libs/judicial-system/court-client/src/lib/courtClientAvailable.service.ts
  libs/judicial-system/court-client/src/lib/courtClientUnavailable.service.ts
Labels: automerge

#8293 feat(web): Optionally render timeline border based on CMS
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/timelineSlice.model.ts
Labels: automerge

#8318 fix(web): Filter out slices that failed mapping
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/models/organizationSubpage.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
  libs/cms/src/lib/models/projectSubpage.model.ts
Labels: automerge

#8319 fix(p-sign-application): Delivery fix
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Labels: automerge, high priority

#8320 fix(p-sign-application): delivery
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Labels: automerge

#8317 chore(core): Fix circular dependency dev regression in node apps
  tools/executors/node/impl.js
  tools/executors/node/impl.js.map
  tools/executors/node/impl.ts
  tools/executors/node/utils.js
  tools/executors/node/utils.js.map
  tools/executors/node/utils.ts
Labels: automerge

#8321 feat: reverting email changes
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/employerRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#8322 fix(service-portal): No showing family members in delegation
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Labels: automerge

#8288 chore(dpac): change text to markdown to fix line breaks and links
  libs/application/templates/data-protection-complaint/src/lib/messages/info.ts
  libs/application/templates/health-insurance/src/forms/messages.ts
Labels: automerge

#8323 fix(qa): Disabling unstable tests, improving base url prefix support
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/src/integration/air-discount-scheme/smoke/discount-data.spec.ts
  apps/system-e2e/src/integration/web/smoke/homepage.spec.ts
  apps/system-e2e/src/support/index.d.ts
  apps/system-e2e/src/support/utils.ts
Labels: automerge

#8242 feat(service-portal): new empty screen for accesses
  libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx
Labels: automerge

#8289 feat(web): Organization page sidebar card update
  apps/web/components/MailingListSignup/MailingListSignup.tsx
  apps/web/components/Organization/LatestNewsCardConnectedComponent/LatestNewsCardConnectedComponent.css.ts
  apps/web/components/Organization/LatestNewsCardConnectedComponent/LatestNewsCardConnectedComponent.tsx
  apps/web/components/Organization/LatestNewsCardConnectedComponent/index.ts
  apps/web/components/Organization/SidebarCard/SidebarCard.tsx
  apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
  apps/web/components/Organization/Slice/MailingListSignupSlice/MailingListSignupSlice.tsx
  apps/web/components/Organization/Slice/OrganizationSlice.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.css.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/queries/News.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/models/sidebarCard.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#8327 fix(applications): Update PDF for data protection complaint & form rendering error
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaineeRepeater/ComplaineeTable.tsx
Labels: automerge

#8326 fix(service-portal): hotfix - No showing family members in delegation
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Labels: automerge

#8292 fix(ads): Void national ids handled against invalid json
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8325 fix(ci): attempting to fix connectivity issues while running System E2E tests
  apps/system-e2e/src/integration/web/smoke/homepage.spec.ts
Labels: automerge

#8324 feat(web): Life event list slice
  apps/web/components/Organization/Slice/LifeEventListPageSlice/LifeEventListPageSlice.tsx
  apps/web/components/Organization/Slice/OrganizationSlice.tsx
  apps/web/components/Organization/index.ts
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/lifeEventPageListSlice.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#8330 fix(application-system): Fixing UI layout
  apps/system-e2e/src/integration/applications/acceptance/parental-leave.spec.ts
  libs/application/ui-shell/src/components/FormMultiField.tsx
Labels: automerge

#8231 feat(service-portal): Dashboard and animated icons
  apps/service-portal/src/assets/icons/sidebar/business.svg
  apps/service-portal/src/assets/icons/sidebar/car.svg
  apps/service-portal/src/assets/icons/sidebar/cellular.svg
  apps/service-portal/src/assets/icons/sidebar/fileTrayFull.svg
  apps/service-portal/src/assets/icons/sidebar/home.svg
  apps/service-portal/src/assets/icons/sidebar/lockClosed.svg
  apps/service-portal/src/assets/icons/sidebar/logOut.svg
  apps/service-portal/src/assets/icons/sidebar/menntun.svg
  apps/service-portal/src/assets/icons/sidebar/person.svg
  apps/service-portal/src/assets/icons/sidebar/reader.svg
  apps/service-portal/src/assets/icons/sidebar/receipt.svg
  apps/service-portal/src/assets/icons/sidebar/school.svg
  apps/service-portal/src/assets/icons/sidebar/wallet.svg
  apps/service-portal/src/assets/images/dashboard.svg
  apps/service-portal/src/components/AnimatedIcon/Business.jsx
  apps/service-portal/src/components/AnimatedIcon/Car.jsx
  apps/service-portal/src/components/AnimatedIcon/Cellular.jsx
  apps/service-portal/src/components/AnimatedIcon/FileTrayFull.jsx
  apps/service-portal/src/components/AnimatedIcon/Home.jsx
  apps/service-portal/src/components/AnimatedIcon/LockClosed.jsx
  apps/service-portal/src/components/AnimatedIcon/LogOut.jsx
  apps/service-portal/src/components/AnimatedIcon/Person.jsx
  apps/service-portal/src/components/AnimatedIcon/Reader.jsx
  apps/service-portal/src/components/AnimatedIcon/Receipt.jsx
  apps/service-portal/src/components/AnimatedIcon/School.jsx
  apps/service-portal/src/components/AnimatedIcon/Wallet.jsx
  apps/service-portal/src/components/Greeting/Greeting.css.ts
  apps/service-portal/src/components/Greeting/Greeting.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.css.ts
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/utils/Icons/idMapper.tsx
  apps/web/screens/Login/Login.tsx
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.css.ts
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
Labels: automerge

#8164 feat(general-fishing-license): Delegation for companies
  apps/application-system/form/src/auth.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.resolver.ts
  libs/api/domains/fishing-license/src/graphql/fishing-license.resolver.ts
  libs/api/domains/identity/src/lib/identity.service.ts
  libs/application/data-providers/src/index.ts
  libs/application/data-providers/src/providers/IdentityProvider.ts
  libs/application/templates/general-fishing-license/codegen.yml
  libs/application/templates/general-fishing-license/project.json
  libs/application/templates/general-fishing-license/src/dataProviders/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/applicantInformationSection.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/externalDataSection.ts
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
  libs/application/templates/general-fishing-license/src/types/index.ts
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#8332 feat(service-portal): add option to open HTML "files"
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#8333 fix(service-portal): add close to doc write
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
Labels: automerge

#7279 feat(marriage-conditions): Marriage conditions application template
  .github/CODEOWNERS
  .github/actions/ci-io.ts
  .github/actions/dist/index.js
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
  libs/api/domains/national-registry-x-road/src/models/nationalRegistryBirthplace.model.ts
  libs/api/domains/national-registry-x-road/src/models/nationalRegistryCitizenship.model.ts
  libs/api/domains/national-registry-x-road/src/models/nationalRegistryPerson.model.ts
  libs/application/core/src/lib/institutionMapper.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/assets/digital-services.jpg
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/assets/logo.jpg
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/assignOtherSpouseEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/types.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/marriage-conditions/.babelrc
  libs/application/templates/marriage-conditions/.eslintrc
  libs/application/templates/marriage-conditions/README.md
  libs/application/templates/marriage-conditions/babel-jest.config.json
  libs/application/templates/marriage-conditions/codegen.yml
  libs/application/templates/marriage-conditions/jest.config.js
  libs/application/templates/marriage-conditions/project.json
  libs/application/templates/marriage-conditions/src/dataProviders/DistrictsProvider.ts
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/dataProviders/index.ts
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/index.tsx
  libs/application/templates/marriage-conditions/src/fields/Done/NextSteps.tsx
  libs/application/templates/marriage-conditions/src/fields/Done/index.tsx
  libs/application/templates/marriage-conditions/src/fields/InfoAlert/InfoAlert.tsx
  libs/application/templates/marriage-conditions/src/fields/InfoAlert/index.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/NationalIdWithName.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/PaymentInfo.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentPending/index.tsx
  libs/application/templates/marriage-conditions/src/fields/index.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/done.ts
  libs/application/templates/marriage-conditions/src/forms/payment.tsx
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/forms/spouseDone.ts
  libs/application/templates/marriage-conditions/src/index.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/constants.ts
  libs/application/templates/marriage-conditions/src/lib/dataSchema.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
  libs/application/templates/marriage-conditions/src/lib/utils.ts
  libs/application/templates/marriage-conditions/src/types.ts
  libs/application/templates/marriage-conditions/tsconfig.json
  libs/application/templates/marriage-conditions/tsconfig.lib.json
  libs/application/templates/marriage-conditions/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#8338 fix(login-service): Allow all companies
  libs/application/templates/login-service/src/fields/IsatInvalid/IsatInvalid.tsx
  libs/application/templates/login-service/src/lib/dataSchema.ts
Labels: automerge

#8336 fix(public-debt-payment-plan): Fixed overflowing slider
  libs/application/templates/public-debt-payment-plan/src/fields/components/PlanSlider/PlanSlider.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/components/Slider/Slider.tsx
Labels: automerge

#8341 fix(marriage-conditions-application): fakedata featureflagged
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/getApplicationFeatureFlags.ts
Labels: automerge, high priority

#8342 fix(marriage-conditions-application): fakedata featureflagged (#8341)
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/getApplicationFeatureFlags.ts
Labels: automerge, high priority

#8301 feat(j-s): more multiple loke fixes
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/messages/courtUpload.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/messages/pdfRequest.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#7913 test(application-system): Add small acceptance test for application-system
  apps/system-e2e/src/fixtures/service-portal/users.json
  apps/system-e2e/src/integration/applications/acceptance/p-sign.spec.ts
  apps/system-e2e/src/integration/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/lib/i18n-messages.ts
  apps/system-e2e/src/lib/types.ts
  apps/system-e2e/src/support/commands.ts
  apps/system-e2e/src/support/index.d.ts
Labels: automerge

#8334 chore(application-system): Add default values and improve error message on fileuploader field
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
  libs/shared/form-fields/src/lib/FileUploadController/index.tsx
Labels: automerge

#8347 fix(service-portal): Remove close
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
Labels: automerge

#8349 fix(service-portal): Add default value to usersvehicle
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
Labels: automerge

#7636 chore(web): tests for frontpage items
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/src/integration/web/smoke/homepage.spec.ts
Labels: automerge

#8357 fix(mortgage-certificate): buttons to span
  libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx
  libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx
Labels: automerge

#8353 feat(j-s): remove message when court record is unsigned
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#8360 fix(announcement of death): Map relations from API instead of hardcoding
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#8362 chore(web): Increase number of articles fetched on category page
  apps/web/screens/Category/Category/Category.tsx
Labels: automerge

#8359 fix(p-sign-application): Delivery submission requires name
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionDelivery.ts
Labels: automerge

#8356 test(service-portal): Navigation & inbox tests
  apps/system-e2e/src/integration/service-portal/smoke/homepage.spec.ts
  apps/system-e2e/src/integration/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/lib/types.ts
Labels: automerge

#8352 feat(j-s): Court indictments overview page
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/overview.spec.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.strings.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/PageTitle/PageTitle.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#8366 fix(p-sign-application): Delivery submission requires name (#8359)
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionDelivery.ts
Labels: automerge

#8367 feat(j-s): remove capitalized case type for court upload files
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#8374 feat(service-portal): Print finance details
  libs/service-portal/core/src/components/ExpandableTable/Row.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/Table.css.ts
Labels: automerge

#8305 feat(application-system): shared sms module for application system
  libs/application/template-api-modules/src/lib/modules/shared/shared.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/document-provider-onboarding/document-provider-onboarding.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/assignEmployerSms.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/assignOtherParentSms.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/employerRejectedSms.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/otherParentRejectedSms.ts
  libs/application/template-api-modules/src/lib/modules/templates/reference-template/reference-template.service.ts
  libs/application/template-api-modules/src/lib/types/index.ts
Labels: automerge

#8372 fix(j-s): fix validation for police case numbers input
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/PoliceCaseNumbers/PoliceCaseNumbers.tsx
Labels: automerge

#8370 feat(j-s): make judge overview the first step in Indictments
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/receptionAndAssignment.spec.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#8369 fix(j-s): fix tooltip for SelectCourtOfficials
  apps/judicial-system/web/src/components/SelectCourtOfficials/SelectCourtOfficials.tsx
Labels: automerge

#8364 fix(service-portal): vehicles typos and timeout
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
  libs/clients/vehicles/src/lib/vehiclesClient.config.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/queries/getVehiclesSearch.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/utils/createUnits.ts
  libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Labels: automerge

#8371 feat(j-s): multi loke cleanup
  apps/judicial-system/backend/src/app/formatters/casefilesPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/courtUpload.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/messages/pdfCasefiles.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#8377 fix(j-s): fix delete case button peeking out
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
Labels: automerge

#8379 feat(j-s): change wording for request to case
  apps/judicial-system/web-e2e/src/integration/Shared/cases.spec.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/Core/requests.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/DropdownMenu/DropdownMenu.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
Labels: automerge

#8380 test(service-portal): Fix system-e2e failures
  apps/system-e2e/src/integration/service-portal/smoke/homepage.spec.ts
Labels: automerge

#8382 fix(service-portal): hotfix vehicles typos and timeout (#8364)
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
  libs/clients/vehicles/src/lib/vehiclesClient.config.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/queries/getVehiclesSearch.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/utils/createUnits.ts
  libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Labels: automerge

#8373 chore(auth-api): Clean up deprecated supports_delegation
  apps/services/auth-api/project.json
  libs/auth-api-lib/migrations/20220908113320-remove-supportsdelegation.js
  libs/auth-api-lib/seeders/20200819081415-identity-resources.js
  libs/auth-api-lib/seeders/20200825111626-api-scopes.js
  libs/auth-api-lib/seeders/20200825121317-api-resources.js
  libs/auth-api-lib/seeders/20200831152525-grants.js
  libs/auth-api-lib/seeders/20200831152526-clients.js
  libs/auth-api-lib/seeders/20201030145231-rename-user-claims.js
  libs/auth-api-lib/seeders/20201110133714-rename-user-claims2.js
  libs/auth-api-lib/seeders/20201110133943-island-is-redirect-uri-prod.js
  libs/auth-api-lib/seeders/20201113110445-island-is-add-redirecturi.js
  libs/auth-api-lib/seeders/20201115110446-island-is-add-scope.js
  libs/auth-api-lib/seeders/20201115110448-update-secret.js
  libs/auth-api-lib/seeders/20201120204558-update-clients-with-new-fields.js
  libs/auth-api-lib/seeders/20201128073638-island-is-add-redirecturis.js
  libs/auth-api-lib/seeders/20201128073659-island-is-add-cors-origins.js
  libs/auth-api-lib/seeders/20201128073715-island-is-add-post-logout-uris.js
  libs/auth-api-lib/seeders/20201209073715-island-is-add-hms-data.js
  libs/auth-api-lib/seeders/20201209073716-island-is-add-scope-for-hms.js
  libs/auth-api-lib/seeders/20201210073716-island-is-add-ark-client-and-modify-hms-client.js
  libs/auth-api-lib/seeders/20201215073716-update-redirect-uri-for-apex-client.js
  libs/auth-api-lib/seeders/20201215083716-add-redirect-uri-for-minar-sidur.js
  libs/auth-api-lib/seeders/20201216083716-add-post-log-out-and-cors-for-minar-sidur.js
  libs/auth-api-lib/seeders/20201228140544-add-ids-admin.js
  libs/auth-api-lib/seeders/20201229083716-add-default-national-id.js
  libs/auth-api-lib/seeders/20201231135419-update-ids-admin.js
  libs/auth-api-lib/seeders/20210104140855-auth-admin-api-add-user-claim.js
  libs/auth-api-lib/seeders/20210108121154-idp-restrictions.js
  libs/auth-api-lib/seeders/20210113122509-add-ids-admin-postlogouturl.js
  libs/auth-api-lib/seeders/20210115122509-add-ids-admin-dev-data.js
  libs/auth-api-lib/seeders/20210118150729-add-island-is-uris.js
  libs/auth-api-lib/seeders/20210120150729-service-portalbase-url-changes.js
  libs/auth-api-lib/seeders/20210121150729-service-portalbase-url-fix.js
  libs/auth-api-lib/seeders/20210122152137-add-app-provider.js
  libs/auth-api-lib/seeders/20210208150729-prod-update.js
  libs/auth-api-lib/seeders/20210216150729-hms-prod-update.js
  libs/auth-api-lib/seeders/20210303101659-clients-delegations-default.js
  libs/auth-api-lib/seeders/20210304093600-api-scope-delegations-to-false.js
  libs/auth-api-lib/seeders/20210304105008-identity-resource-delegations-to-false.js
  libs/auth-api-lib/seeders/20210324144627-applications-resources2.js
  libs/auth-api-lib/seeders/20210425152526-app-client.js
  libs/auth-api-lib/seeders/20211209101232-add-personal-representative-type.js
  libs/auth-api-lib/seeders/data/helpers/createClient.ts
  libs/auth-api-lib/seeders/data/helpers/types.ts
  libs/auth-api-lib/seeders/local/003-ids-admin.client.js
  libs/auth-api-lib/seeders/local/004-island.is.client.js
  libs/auth-api-lib/seeders/local/005-skra.is.client.js
  libs/auth-api-lib/seeders/local/006-delegations.js
  libs/auth-api-lib/seeders/local/007-personal_representative.js
Labels: automerge

#8383 fix(j-s): fix contentful namespace
  apps/judicial-system/web/src/components/SelectCourtOfficials/SelectCourtOfficials.strings.ts
Labels: automerge

#8335 feat(web): Project page news
  apps/web/components/Form/Form.tsx
  apps/web/components/NewsList/NewsList.tsx
  apps/web/components/NewsList/NewsListSidebar.tsx
  apps/web/components/NewsList/utils.ts
  apps/web/components/Organization/Slice/LatestNewsSlice/LatestNewsSlice.tsx
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/Organization/index.ts
  apps/web/components/Stepper/Stepper/Stepper.tsx
  apps/web/components/real.ts
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/o/[slug]/news/[newsSlug]/index.tsx
  apps/web/pages/en/o/[slug]/news/index.tsx
  apps/web/pages/en/p/[slug]/news/[newsSlug].ts
  apps/web/pages/en/p/[slug]/news/index.ts
  apps/web/pages/s/[slug]/frett/[newsSlug]/index.tsx
  apps/web/pages/s/[slug]/frett/index.tsx
  apps/web/pages/v/[slug]/frett/[newsSlug].ts
  apps/web/pages/v/[slug]/frett/index.ts
  apps/web/screens/Organization/Home/Home.tsx
  apps/web/screens/Organization/NewsList.tsx
  apps/web/screens/Organization/OrganizationNewsArticle.tsx
  apps/web/screens/Organization/OrganizationNewsList.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/ProjectNewsArticle.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/Project/components/ProjectWrapper/ProjectWrapper.tsx
  apps/web/screens/Project/utils.tsx
  apps/web/screens/queries/Project.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/graphCard.model.ts
  libs/cms/src/lib/models/linkGroup.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#8375 feat(service-portal): add mailbox empty screen
  libs/service-portal/documents/src/screens/Overview/Overview.css.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#8389 fix(mortgage-certificate): buttons to span (#8357)
  libs/application/templates/mortgage-certificate/src/fields/PendingRejected/index.tsx
  libs/application/templates/mortgage-certificate/src/fields/PendingRejectedTryAgain/index.tsx
Labels: automerge

#8391 chore(auth-api): Hotfix - Clean up deprecated supports_delegation (#8373)
  apps/services/auth-api/project.json
  libs/auth-api-lib/migrations/20220908113320-remove-supportsdelegation.js
  libs/auth-api-lib/seeders/20200819081415-identity-resources.js
  libs/auth-api-lib/seeders/20200825111626-api-scopes.js
  libs/auth-api-lib/seeders/20200825121317-api-resources.js
  libs/auth-api-lib/seeders/20200831152525-grants.js
  libs/auth-api-lib/seeders/20200831152526-clients.js
  libs/auth-api-lib/seeders/20201030145231-rename-user-claims.js
  libs/auth-api-lib/seeders/20201110133714-rename-user-claims2.js
  libs/auth-api-lib/seeders/20201110133943-island-is-redirect-uri-prod.js
  libs/auth-api-lib/seeders/20201113110445-island-is-add-redirecturi.js
  libs/auth-api-lib/seeders/20201115110446-island-is-add-scope.js
  libs/auth-api-lib/seeders/20201115110448-update-secret.js
  libs/auth-api-lib/seeders/20201120204558-update-clients-with-new-fields.js
  libs/auth-api-lib/seeders/20201128073638-island-is-add-redirecturis.js
  libs/auth-api-lib/seeders/20201128073659-island-is-add-cors-origins.js
  libs/auth-api-lib/seeders/20201128073715-island-is-add-post-logout-uris.js
  libs/auth-api-lib/seeders/20201209073715-island-is-add-hms-data.js
  libs/auth-api-lib/seeders/20201209073716-island-is-add-scope-for-hms.js
  libs/auth-api-lib/seeders/20201210073716-island-is-add-ark-client-and-modify-hms-client.js
  libs/auth-api-lib/seeders/20201215073716-update-redirect-uri-for-apex-client.js
  libs/auth-api-lib/seeders/20201215083716-add-redirect-uri-for-minar-sidur.js
  libs/auth-api-lib/seeders/20201216083716-add-post-log-out-and-cors-for-minar-sidur.js
  libs/auth-api-lib/seeders/20201228140544-add-ids-admin.js
  libs/auth-api-lib/seeders/20201229083716-add-default-national-id.js
  libs/auth-api-lib/seeders/20201231135419-update-ids-admin.js
  libs/auth-api-lib/seeders/20210104140855-auth-admin-api-add-user-claim.js
  libs/auth-api-lib/seeders/20210108121154-idp-restrictions.js
  libs/auth-api-lib/seeders/20210113122509-add-ids-admin-postlogouturl.js
  libs/auth-api-lib/seeders/20210115122509-add-ids-admin-dev-data.js
  libs/auth-api-lib/seeders/20210118150729-add-island-is-uris.js
  libs/auth-api-lib/seeders/20210120150729-service-portalbase-url-changes.js
  libs/auth-api-lib/seeders/20210121150729-service-portalbase-url-fix.js
  libs/auth-api-lib/seeders/20210122152137-add-app-provider.js
  libs/auth-api-lib/seeders/20210208150729-prod-update.js
  libs/auth-api-lib/seeders/20210216150729-hms-prod-update.js
  libs/auth-api-lib/seeders/20210303101659-clients-delegations-default.js
  libs/auth-api-lib/seeders/20210304093600-api-scope-delegations-to-false.js
  libs/auth-api-lib/seeders/20210304105008-identity-resource-delegations-to-false.js
  libs/auth-api-lib/seeders/20210324144627-applications-resources2.js
  libs/auth-api-lib/seeders/20210425152526-app-client.js
  libs/auth-api-lib/seeders/20211209101232-add-personal-representative-type.js
  libs/auth-api-lib/seeders/data/helpers/createClient.ts
  libs/auth-api-lib/seeders/data/helpers/types.ts
  libs/auth-api-lib/seeders/local/003-ids-admin.client.js
  libs/auth-api-lib/seeders/local/004-island.is.client.js
  libs/auth-api-lib/seeders/local/005-skra.is.client.js
  libs/auth-api-lib/seeders/local/006-delegations.js
  libs/auth-api-lib/seeders/local/007-personal_representative.js
Labels: automerge

#8381 feat(j-s): update ready for court sms-notification sent to court
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#8384 fix(j-s): hide court record unsigned message for defenders
  apps/judicial-system/web/messages/Core/defenderCaseOverview.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#8361 feat(j-s): Indictments - Subpoena screen
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20220908085534-update-case.js
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliver.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/subpoena.spec.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/pages/domur/akaera/fyrirkall/[id].ts
  apps/judicial-system/web/src/components/CourtArrangements/index.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/SelectSubpoenaType/SelectSubpoenaType.css.ts
  apps/judicial-system/web/src/components/SelectSubpoenaType/SelectSubpoenaType.strings.ts
  apps/judicial-system/web/src/components/SelectSubpoenaType/SelectSubpoenaType.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#8387 fix(service-portal): null and year fields in vehicles
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/utils/createUnits.ts
Labels: automerge

#8378 fix(fa): Add safer-buffer to build
  apps/financial-aid/api/esbuild.json
Labels: automerge

#8399 fix(service-portal): hotfix - null and year fields in vehicles (#8387)
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/utils/createUnits.ts
Labels: automerge

#8400 fix(fa): Use another build executor
  apps/financial-aid/api/project.json
Labels: automerge

#8404 fix(fa): Revert change to build
  apps/financial-aid/api/project.json
Labels: automerge

#8355 feat(web): Don't show the FAQ List title in navigation if it's hidden on Life Event page
  apps/web/utils/navigation.ts
Labels: automerge

#8350 feat(web): Form field can decide form email recipient
  apps/web/components/Form/Form.tsx
  apps/web/screens/queries/fragments.ts
  libs/api/domains/communications/src/lib/communications.service.ts
  libs/api/domains/communications/src/lib/dto/genericForm.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/form.model.ts
  libs/cms/src/lib/models/formField.model.ts
Labels: automerge

#8390 fix(web): Project subpage double breadcrumbs
  apps/web/screens/Project/Project.tsx
Labels: automerge

#8395 revert(service-portal): image going under cards
  apps/service-portal/src/components/Greeting/Greeting.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.css.ts
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
Labels: automerge

#8407 fix(fa): Change nav status to 'Umsókn'
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
Labels: automerge

#8403 fix(j-s): Fix text in notifications in indictments
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#8376 chore: Implement more methods in NationalRegistryClientService
  apps/air-discount-scheme/backend/infra/backend.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
  apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.module.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
  apps/air-discount-scheme/backend/src/environments/environment.ts
  apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistry.resolver.ts
  apps/financial-aid/api/src/app/modules/municipalityNationalRegistryModule/municipalityNationalRegistry.service.ts
  apps/services/auth-api/src/app/modules/delegations/delegations.controller.spec.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
  apps/services/auth-api/test/setup.ts
  apps/services/auth-public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
  apps/services/auth-public-api/test/mocks/einstaklingurApi.mock.ts
  apps/services/auth-public-api/test/setup.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
  libs/api/domains/national-registry-x-road/src/models/nationalRegistryPerson.model.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/nodeFetch.ts
  libs/clients/national-registry/v2/README.md
  libs/clients/national-registry/v2/src/clientConfig.json
  libs/clients/national-registry/v2/src/index.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
  libs/clients/national-registry/v2/src/lib/types/birthplace.dto.ts
  libs/clients/national-registry/v2/src/lib/types/citizenship.dto.ts
  libs/clients/national-registry/v2/src/lib/types/cohabitation.dto.ts
  libs/clients/national-registry/v2/src/lib/types/family.dto.ts
  libs/clients/national-registry/v2/src/lib/types/residence-history-entry.dto.ts
  libs/shared/types/src/lib/national-registry-client.ts
  libs/testing/fixtures/src/lib/nationalRegistryUser.ts
  yarn.lock
Labels: automerge

#8411 feat(service-portal): vehicles add root path
  libs/service-portal/vehicles/src/index.ts
Labels: automerge

#8245 chore(core): Adding local ESLint rule to disallow async module initialisation
  .eslintrc.json
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  eslint-local-rules.js
  libs/api/domains/application/src/lib/application.module.ts
  libs/api/domains/education/src/lib/education.module.ts
  libs/api/domains/education/src/lib/education.spec.ts
  libs/api/domains/endorsement-system/src/lib/endorsementSystem.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-petition/general-petition.module.ts
  libs/clients/islykill/src/lib/islykill.module.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
  libs/clients/national-registry/v1/src/lib/soapClient.ts
  nx.json
  package.json
  yarn.lock
Labels: automerge

#8409 feat(j-s): Case Received by Court Notification
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#8410 chore(service-portal): GraphQL queries updates
  libs/service-portal/assets/src/components/AssetGrid/index.tsx
  libs/service-portal/assets/src/lib/queries.ts
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/fragments/assets.ts
  libs/service-portal/graphql/src/lib/fragments/license.ts
  libs/service-portal/graphql/src/lib/queries/getAnnualStatusDocument.ts
  libs/service-portal/graphql/src/lib/queries/getDocumentCategories.ts
  libs/service-portal/graphql/src/lib/queries/getFinanceDocument.ts
  libs/service-portal/graphql/src/lib/queries/getLicenses.ts
  libs/service-portal/graphql/src/lib/queries/getUserProfileStatus.ts
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCardsNotUsed.tsx
  libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicleHistory.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicleSearchLimit.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicles.ts
  libs/service-portal/vehicles/src/queries/getVehiclesSearch.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx
Labels: automerge, deploy-feature

#8401 feat(j-s): Indictments - Court record route
  apps/judicial-system/backend/migrations/20220912112127-update-case.js
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/createCaseFileRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/createPresignedPostRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/deleteCaseFileRolesRules.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/subpoena.spec.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/pages/domur/akaera/thingbok/[id].ts
  apps/judicial-system/web/src/components/PageLayout/utils/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#8415 feat(web): Add new variant to ProfileCard
  libs/island-ui/core/src/lib/ProfileCard/ProfileCard.css.ts
  libs/island-ui/core/src/lib/ProfileCard/ProfileCard.stories.tsx
  libs/island-ui/core/src/lib/ProfileCard/ProfileCard.tsx
Labels: automerge

#8424 fix(national-registry): Transgender adults can be parents
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
Labels: automerge

#8408 fix(service-portal): axle data, timeout, null values
  libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/clients/vehicles/src/lib/vehiclesClient.service.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/components/DetailTable/AxleTable.tsx
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/utils/createUnits.ts
Labels: automerge

#8428 feat(j-s): Notifications for Completed Criminal Cases
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.config.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.config.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/message-handler/src/app/message.service.ts
  apps/judicial-system/web/infra/judicial-system-web.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#8430 chore(j-s): Revoked Indictments
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#8433 fix(fa): Test fix
  libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts
  libs/application/templates/financial-aid/src/forms/Prerequisites.ts
Labels: automerge

#8431 chore(web): Hotfix - Increase number of articles fetched on category page (#8362)
  apps/web/screens/Category/Category/Category.tsx
Labels: automerge

#8439 fix(service-portal): hotfix axle data, timeout, null values (#8408)
  libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/clients/vehicles/src/lib/vehiclesClient.service.ts
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/vehicles/src/components/DetailTable/AxleTable.tsx
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/utils/createUnits.ts
Labels: automerge

#8386 feat(web): Table embed
  apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/oneColumnText.model.ts
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
  package.json
  yarn.lock
Labels: automerge

#8441 fix(fa): Add safer buffer to financial-aid-backend
  apps/financial-aid/backend/esbuild.json
Labels: automerge

#8440 fix(fa): Add logging to api
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.resolver.ts
  libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts
  libs/application/templates/financial-aid/src/forms/Prerequisites.ts
Labels: automerge

#8419 fix(p-sign-application): Message ids
  libs/application/templates/p-sign/src/forms/applicationSections/sectionInformationActor.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  yarn.lock
Labels: automerge

#8444 fix(fa): Add logging to financial-aid-backend
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/personalTaxReturn.controller.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/test/createTestingPersonalTaxReturnModule.ts
Labels: automerge

#8434 fix(web): Change select box ordering for published material page and add a check for whether a tag is in a tag group
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/Organization/PublishedMaterial/utils.ts
Labels: automerge

#8448 fix(j-s): S-Case Court Date Notifications
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
Labels: automerge

#8449 feat(parental-leave): add assign VMST to states
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#8429 feat(web): Landskjörstjórn Footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandkjorstjornFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornFooter.css.ts
Labels: automerge

#8426 feat(web): Reuse life event pages for Stafrænt Ísland services
  apps/web/components/Organization/Slice/LifeEventListPageSlice/LifeEventListPageSlice.tsx
  apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.css.ts
  apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/Organization/index.ts
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/o/digital-iceland/island-services/[slug].ts
  apps/web/pages/s/stafraent-island/thjonustur/[slug].ts
  apps/web/screens/LifeEvent/LifeEvent.tsx
  apps/web/screens/Organization/Home/Home.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/lifeEventPage.model.ts
  libs/island-ui/core/src/lib/ProfileCard/ProfileCard.css.ts
  libs/island-ui/core/src/lib/ProfileCard/ProfileCard.tsx
Labels: automerge

#8425 feat(fsinao): Application/financial-statement-inao - new application paths
  libs/application/templates/financial-statements-inao/src/components/Logo.tsx
  libs/application/templates/financial-statements-inao/src/dataProviders/currentUserTypeProvider.ts
  libs/application/templates/financial-statements-inao/src/dataProviders/index.ts
  libs/application/templates/financial-statements-inao/src/fields/CemetryCaretaker/CemetryCaretaker.css.ts
  libs/application/templates/financial-statements-inao/src/fields/CemetryCaretaker/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/CemetryEquities/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/cemetryExpenses.tsx
  libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/cemetryIncome.tsx
  libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/CemetryOverview/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionEquties/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionStatement/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/IndividualElectionOperatingIncome/expenses.tsx
  libs/application/templates/financial-statements-inao/src/fields/IndividualElectionOperatingIncome/income.tsx
  libs/application/templates/financial-statements-inao/src/fields/IndividualElectionOperatingIncome/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/KeyNumbers/Total.tsx
  libs/application/templates/financial-statements-inao/src/fields/KeyNumbers/index.ts
  libs/application/templates/financial-statements-inao/src/fields/KeyNumbersCapital/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/OperatingYear/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/OperatingYear/styles.css.ts
  libs/application/templates/financial-statements-inao/src/fields/Overview/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/PartyOperatingIncome/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/PartyOperatingIncome/partyExpenses.tsx
  libs/application/templates/financial-statements-inao/src/fields/PartyOperatingIncome/partyIncome.tsx
  libs/application/templates/financial-statements-inao/src/fields/PartyOverview/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/Shared/FileValueLine.tsx
  libs/application/templates/financial-statements-inao/src/fields/Shared/ValueLine.tsx
  libs/application/templates/financial-statements-inao/src/fields/Shared/index.ts
  libs/application/templates/financial-statements-inao/src/fields/Shared/styles/overviewStyles.css.ts
  libs/application/templates/financial-statements-inao/src/fields/index.ts
  libs/application/templates/financial-statements-inao/src/forms/application/application.ts
  libs/application/templates/financial-statements-inao/src/forms/application/cemetry/cemetryKeyNumbers.ts
  libs/application/templates/financial-statements-inao/src/forms/application/cemetry/sectionCemetryCaretaker.ts
  libs/application/templates/financial-statements-inao/src/forms/application/individual/individualKeyNumbers.ts
  libs/application/templates/financial-statements-inao/src/forms/application/party/partyKeyNumbers.ts
  libs/application/templates/financial-statements-inao/src/forms/application/personalElection/clientInfoSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/about/clientInfoSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/electionInfo/electionInfo.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/keyNumbers/capitalNumbers.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/keyNumbers/keyNumbersSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/overviewSection.tsx
  libs/application/templates/financial-statements-inao/src/forms/done.ts
  libs/application/templates/financial-statements-inao/src/forms/prerequisites/fakeDataSection.ts
  libs/application/templates/financial-statements-inao/src/forms/prerequisites/index.ts
  libs/application/templates/financial-statements-inao/src/hooks/index.ts
  libs/application/templates/financial-statements-inao/src/hooks/useTotals.ts
  libs/application/templates/financial-statements-inao/src/lib/constants.ts
  libs/application/templates/financial-statements-inao/src/lib/financialStatementsInao.ts
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/dataSchema.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/getApplicationFeatureFlags.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/helpers.ts
Labels: automerge

#8453 fix(financial-statement-inao): rename message duplicate
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
Labels: automerge

#8177 feat(service-portal): print child data
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/information/src/components/ChildView/ChildView.css.ts
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/components/Parents/Parents.tsx
Labels: automerge

#8087 feat(service-portal): firearm license and pkpass client integration
  .github/CODEOWNERS
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/license-service/README.md
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/pkpass.client.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/firearmLicenseMapper.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/firearmLicenseService.api.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/index.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/clients/adr-and-machine-license/README.md
  libs/clients/firearm-license/.eslintrc.json
  libs/clients/firearm-license/README.md
  libs/clients/firearm-license/jest.config.js
  libs/clients/firearm-license/project.json
  libs/clients/firearm-license/src/clientConfig.json
  libs/clients/firearm-license/src/index.ts
  libs/clients/firearm-license/src/lib/firearmApi.services.ts
  libs/clients/firearm-license/src/lib/firearmApi.types.ts
  libs/clients/firearm-license/src/lib/firearmApiProvider.ts
  libs/clients/firearm-license/src/lib/firearmLicenseClient.config.ts
  libs/clients/firearm-license/src/lib/firearmLicenseClient.module.ts
  libs/clients/firearm-license/tsconfig.json
  libs/clients/firearm-license/tsconfig.lib.json
  libs/clients/firearm-license/tsconfig.spec.json
  libs/clients/smartsolutions/.babelrc
  libs/clients/smartsolutions/.eslintrc.json
  libs/clients/smartsolutions/README.md
  libs/clients/smartsolutions/codegen.yml
  libs/clients/smartsolutions/jest.config.js
  libs/clients/smartsolutions/project.json
  libs/clients/smartsolutions/src/index.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.types.ts
  libs/clients/smartsolutions/src/lib/smartsolutionsApi.module.ts
  libs/clients/smartsolutions/src/lib/utils.ts
  libs/clients/smartsolutions/tsconfig.json
  libs/clients/smartsolutions/tsconfig.lib.json
  libs/clients/smartsolutions/tsconfig.spec.json
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/graphql/src/hooks/licenses/useLicenses.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, deploy-feature

#8432 fix(marriage-conditions): fixing after testing session
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollectionSection.ts
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
Labels: automerge

#8458 feat(financial-statements-inao): Submit financial statements
  libs/api/domains/financial-statements-inao/src/lib/dto/cemeteryFinancialStatement.input.ts
  libs/api/domains/financial-statements-inao/src/lib/dto/cemeteryFinancialStatemetnValues.input.ts
  libs/api/domains/financial-statements-inao/src/lib/dto/personalElectionFinancialStatement.input.ts
  libs/api/domains/financial-statements-inao/src/lib/dto/personalElectionFinancialStatementValues.input.ts
  libs/api/domains/financial-statements-inao/src/lib/dto/politicalPartyFinancialStatement.input.ts
  libs/api/domains/financial-statements-inao/src/lib/dto/politicalPartyFinancialStatementValues.input.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
  libs/clients/financial-statements-inao/src/lib/types/index.ts
  libs/clients/financial-statements-inao/src/lib/utils/lookup.ts
Labels: automerge

#8452 feat(institution-collaboration): form adjustments
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationOverviewTemplate.ts
  libs/application/templates/institution-collaboration/README.md
  libs/application/templates/institution-collaboration/src/fields/ConfirmationScreen/ConfirmationScreen.tsx
  libs/application/templates/institution-collaboration/src/fields/Constraints/ConstraintController.tsx
  libs/application/templates/institution-collaboration/src/fields/Constraints/Constraints.tsx
  libs/application/templates/institution-collaboration/src/fields/FieldDescription/FieldDescription.tsx
  libs/application/templates/institution-collaboration/src/fields/ReviewScreen/ReviewScreen.tsx
  libs/application/templates/institution-collaboration/src/fields/SecondaryContact/SecondaryContact.tsx
  libs/application/templates/institution-collaboration/src/forms/application.ts
  libs/application/templates/institution-collaboration/src/lib/dataSchema.ts
  libs/application/templates/institution-collaboration/src/lib/messages.ts
  libs/application/templates/institution-collaboration/src/lib/template.ts
Labels: automerge

#8461 fix(service-portal): wrong key
  apps/api/src/app/environments/environment.ts
Labels: automerge

#8368 fix(service-portal): Display delegated applications on overview if permitted.
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/e2e/applicationAccess.spec.ts
  apps/application-system/api/src/app/modules/application/e2e/delegationGuard.spec.ts
  apps/application-system/api/src/app/modules/application/guards/bypass-delegation.decorator.ts
  apps/application-system/api/src/app/modules/application/guards/delegation.guard.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  libs/application/api/core/src/lib/application/application.service.ts
Labels: automerge

#8468 feat(financial-statements-inao): Add config values query
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/api/domains/financial-statements-inao/src/lib/models/config.model.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
  libs/clients/financial-statements-inao/src/lib/types/index.ts
Labels: automerge

#8466 feat(financial-statements-inao): improved success screen
  libs/application/templates/financial-statements-inao/src/fields/Done/Success.tsx
  libs/application/templates/financial-statements-inao/src/forms/done.ts
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/helpers.ts
Labels: automerge

#8472 fix(air-discount-scheme): Add pseudomap to air-discount-scheme
  apps/air-discount-scheme/backend/esbuild.json
Labels: automerge

#8450 feat(j-s): add message when no police case number is assigned
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseNumbers/PoliceCaseNumbers.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseNumbers/PoliceCaseNumbers.tsx
Labels: automerge

#8456 fix(j-s): fix back button on oveview Prosecutor Indictments
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#8420 feat(j-s): defentant party screen
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20220914145255-update-case.js
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web-e2e/src/fixtures/lawyersResponse.json
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/defendantParty.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/subpoena.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/Core/defenderInfo.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/defendantForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/pages/domur/akaera/malflytjendur/[id].ts
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.spec.tsx
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInput.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInput.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderNotFound.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderNotFound.tsx
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/ProsecutorSelection/ProsecutorSelection.strings.ts
  apps/judicial-system/web/src/components/ProsecutorSelection/ProsecutorSelection.tsx
  apps/judicial-system/web/src/components/ProsecutorSelection/prosecutorSelectionUsersGql.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/ProsecutorAndDefender/ProsecutorAndDefender.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/ProsecutorAndDefender/ProsecutorAndDefender.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/ProsecutorAndDefender/SelectDefender.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSection.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSectionHeightenedSecurity.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSelection.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSelection.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#8475 chore(web): Add hsn slug to footerEnabled list
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#8460 fix(j-s): Fix validation of court case number in S cases
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.strings.ts
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseNumbers/PoliceCaseNumbers.strings.ts
  apps/judicial-system/web/src/utils/validate.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#8464 chore(j-s): Move all hard coded strings in SigningModal to CF
  apps/judicial-system/web/messages/InvestigationCases/Court/confirmation.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/confirmation.ts
  apps/judicial-system/web/src/components/SigningModal/SigningModal.spec.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.strings.ts
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
Labels: automerge

#8476 feat(identity-client): Identity shared provider and identity service moved to client lib
  SUMMARY.md
  apps/application-system/api/src/app/app.module.ts
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
  libs/api/domains/identity/src/index.ts
  libs/api/domains/identity/src/lib/identity.module.ts
  libs/api/domains/identity/src/lib/identity.resolver.ts
  libs/api/domains/identity/src/lib/models/identity.model.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/identity/identity.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/identity/identity.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/index.ts
  libs/application/templates/family-matters/children-residence-change/README.md
  libs/application/templates/general-fishing-license/README.md
  libs/application/templates/general-fishing-license/project.json
  libs/application/templates/general-fishing-license/src/dataProviders/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/externalDataSection.ts
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/identity.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/index.ts
  libs/clients/identity/.eslintrc.json
  libs/clients/identity/README.md
  libs/clients/identity/jest.config.js
  libs/clients/identity/project.json
  libs/clients/identity/src/index.ts
  libs/clients/identity/src/lib/identityClient.module.ts
  libs/clients/identity/src/lib/identityClient.service.ts
  libs/clients/identity/src/lib/types/address.ts
  libs/clients/identity/src/lib/types/identity.ts
  libs/clients/identity/src/lib/types/identityType.ts
  libs/clients/identity/tsconfig.json
  libs/clients/identity/tsconfig.lib.json
  libs/clients/identity/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#8469 feat: adding union and pension back
  libs/application/templates/parental-leave/src/forms/EmployerApproveEdits.ts
Labels: automerge

#8345 fix(ads): Re-introduce skeleton loader
  apps/air-discount-scheme/web/screens/Auth/Auth.tsx
  apps/air-discount-scheme/web/screens/Subsidy/Subsidy.tsx
Labels: automerge

#8479 feat(j-s): Created a project for e2e tests that call the server
  apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
  apps/judicial-system/codegen.yml
  apps/judicial-system/web-e2e-regression/.eslintrc.json
  apps/judicial-system/web-e2e-regression/cypress.config.ts
  apps/judicial-system/web-e2e-regression/project.json
  apps/judicial-system/web-e2e-regression/src/integration/Prosecutor/Indictments/defendant.spec.ts
  apps/judicial-system/web-e2e-regression/src/integration/Prosecutor/Indictments/processing.spec.ts
  apps/judicial-system/web-e2e-regression/src/support/commands.ts
  apps/judicial-system/web-e2e-regression/src/support/index.ts
  apps/judicial-system/web-e2e-regression/src/utils/index.ts
  apps/judicial-system/web-e2e-regression/tsconfig.e2e.json
  apps/judicial-system/web-e2e-regression/tsconfig.json
  workspace.json
Labels: automerge

#8488 fix(parental-leave): keep application in correct state
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#8489 fix(ads): Anticipate null names from NREG
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8473 feat(j-s): fail signature confirmation if upload S3 fails
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
Labels: automerge

#8487 fix(j-s): Upload Court Documents
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliver.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/index.ts
  apps/judicial-system/backend/src/app/modules/court/test/createDocument.spec.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/uploadCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
  libs/judicial-system/court-client/src/lib/courtClientAvailable.service.ts
  libs/judicial-system/court-client/src/lib/courtClientUnavailable.service.ts
Labels: automerge

#8492 chore(web): Add Stefna as codeowner of web project
  .github/CODEOWNERS
Labels: automerge

#8494 fix(ads): Revert to old name functionality in ADS for now
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8495 fix(ads): revert to last known good state
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8485 feat(j-s): send defender assigned notifications
  apps/judicial-system/backend/migrations/20220922140210-update-notification.js
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/sendCaseNotificationRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/sendDefenderAssignedEmailNotifications.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/prosecutorAndDefender.spec.ts
  apps/judicial-system/web/src/routes/Court/Indictments/ProsecutorAndDefender/ProsecutorAndDefender.tsx
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#8354 feat(no debt certificate): Add delegation
  apps/application-system/api/src/app/modules/application/guards/delegation.guard.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  apps/application-system/form/src/auth.ts
  apps/services/auth/public-api/README.md
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
  libs/application/templates/no-debt-certificate/src/dataProviders/index.ts
  libs/application/templates/no-debt-certificate/src/forms/NoDebtCertificateForm.ts
  libs/application/templates/no-debt-certificate/src/lib/messages.ts
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/templates/reference-template/README.md
  libs/application/types/src/lib/ApplicationAllowedDelegations.ts
  libs/application/types/src/lib/ApplicationTemplate.ts
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
  libs/auth/scopes/src/lib/api.scope.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#8500 refactor(service-portal): move name in vehicle lookup table
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
Labels: automerge

#8478 fix(infra): Reflect personal representative name change in DSL
  apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
  apps/services/auth/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#8491 fix(mac): Fixes in marriage conditions
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollectionSection.ts
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
Labels: automerge

#8503 chore(user-profile): Refactor user-profile verification service.
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
Labels: automerge

#8501 fix: verify pkpass
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
Labels: automerge

#8499 chore(j-s): Case Files PDF Removal
  apps/judicial-system/backend/src/app/formatters/casefilesPdf.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/pdfCasefiles.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#8508 feat(web): Hotfix - add hsn slug to footer enabled list (#8475)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#8510 fix(web): Wrong english project news link
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
Labels: automerge

#8498 fix(j-s): have name of creatingProsecutor instead of institution
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/overview.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
Labels: automerge

#8504 fix(marriage-conditions): adding assets to appear in email
  apps/application-system/api/project.json
Labels: automerge

#8505 feat(j-s): no edit indictments after submit to court
  apps/judicial-system/web-e2e/src/fixtures/cases.json
  apps/judicial-system/web-e2e/src/fixtures/translationsResponse.json
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/overview.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#8511 chore(j-s): default to block access too new states
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
Labels: automerge

#8514 fix(ui-shell): Changing default message to icelandic for the Back to service portal button
  libs/application/ui-shell/src/components/ScreenFooter.tsx
Labels: automerge

#8496 feat(financial-statements-inao): Fetch financial limit for election
  libs/application/templates/financial-statements-inao/src/fields/AvailableElections/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/ElectionSelect.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/IncomeLimitField.tsx
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/electionReducer.ts
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/index.tsx
  libs/application/templates/financial-statements-inao/src/fields/index.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/electionInfo/electionInfo.ts
  libs/application/templates/financial-statements-inao/src/graphql/index.ts
  libs/application/templates/financial-statements-inao/src/lib/constants.ts
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/types.ts
Labels: automerge

#8394 refactor(service-portal): error screens, action card, loading states
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/assets/src/components/AssetCardLoader/index.tsx
  libs/service-portal/assets/src/components/AssetListCards/index.tsx
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/core/src/components/ActionCard/ActionCard.css.ts
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/document-provider/src/screens/DocumentProviders/DocumentProvidersSearch.tsx
  libs/service-portal/documents/src/components/DocumentCard/DocumentCard.tsx
  libs/service-portal/education-career/src/screens/EducationCareer/components/CareerCards/CareerCards.tsx
  libs/service-portal/education-degree/src/screens/EducationDegree/components/DegreeCards/DegreeCards.tsx
  libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
  libs/service-portal/endorsements/src/screens/Petitions/Petitions.tsx
  libs/service-portal/endorsements/src/screens/PetitionsAdmin/PetitionsAdmin.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCardLoader.tsx
  libs/service-portal/information/src/components/InfoAccordionCard/InfoAccordionCard.tsx
  libs/service-portal/information/src/components/UserInfoItem/UserInfoItem.tsx
  libs/service-portal/information/src/components/forms/ExternalFormDirect/ExternalFormDirect.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/LicensesOverview/LicensesOverview.tsx
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx
  libs/service-portal/vehicles/src/utils/constants.ts
  libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Labels: automerge
