Repository island-is/island.is, pull requests merged in 2022-08, with the labels that each got.

#8083 feat(web): Allow Process entry asset reference instead of url
  apps/web/screens/Adgerdir/Article.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/queries/Adgerdir.tsx
  apps/web/screens/queries/Article.ts
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/processEntry.model.ts
  libs/island-ui/contentful/src/lib/ProcessEntry/ProcessEntry.tsx
Labels: automerge

#8077 feat(web): Add a way to embed stepper in article body
  apps/web/components/Stepper/Stepper/Stepper.tsx
  apps/web/components/Stepper/utils.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/models/stepper.model.ts
  libs/cms/src/lib/models/subArticle.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#8085 fix: parental-leave add validation for employer's email
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/isValidEmail.ts
Labels: automerge

#8068 feat(web): Add Mailchimp module for email signup forms
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/web/components/MailingListSignup/MailingListSignup.tsx
  apps/web/components/NameSignupForm/NameSignupForm.tsx
  apps/web/components/Organization/Slice/MailingListSignupSlice/MailingListSignupSlice.tsx
  apps/web/screens/queries/Organization.tsx
  libs/api/domains/mailchimp/.babelrc
  libs/api/domains/mailchimp/.eslintrc.json
  libs/api/domains/mailchimp/README.md
  libs/api/domains/mailchimp/jest.config.js
  libs/api/domains/mailchimp/src/index.ts
  libs/api/domains/mailchimp/src/lib/dto/mailchimpSubscribe.input.ts
  libs/api/domains/mailchimp/src/lib/fixtures/mailingSlice.ts
  libs/api/domains/mailchimp/src/lib/mailchimp.module.ts
  libs/api/domains/mailchimp/src/lib/mailchimp.resolver.spec.ts
  libs/api/domains/mailchimp/src/lib/mailchimp.resolver.ts
  libs/api/domains/mailchimp/src/lib/models/mailchimpSubscribeResponse.model.ts
  libs/api/domains/mailchimp/tsconfig.json
  libs/api/domains/mailchimp/tsconfig.lib.json
  libs/api/domains/mailchimp/tsconfig.spec.json
  libs/cms/src/index.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/dto/getMailingListSignupSlice.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#8012 feat(service-portal): add download csv and excel to more finance screens
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/utils/dataHeaders.ts
  libs/service-portal/finance/src/utils/filesGeneral.ts
Labels: automerge

#7980 fix(service-portal): translations
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
  workspace.json
Labels: automerge

#8090 feat(web): Add select component to organization published material page
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.css.ts
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/OrderByItem.css.ts
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/OrderByItem.tsx
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/index.ts
  apps/web/screens/Organization/PublishedMaterial/utils.ts
Labels: automerge

#8076 feat(web): Add RSS news feed
  apps/web/next.config.js
  apps/web/pages/api/rss/index.ts
Labels: automerge

#8026 feat(service-portal): add skuldleysisvottord button
  libs/service-portal/finance/src/components/DropdownExport/DropdownExport.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#8029 fix(service-portal): mismatch on web and file
  libs/service-portal/finance/src/utils/dataHeaders.ts
Labels: automerge

#8031 fix(service-portal): minor text changes for vehicles
  libs/service-portal/documents/src/utils/messages.ts
  libs/service-portal/vehicles/src/lib/messages.ts
Labels: automerge

#8088 feat(service-portal): Change delegation access default time
  libs/service-portal/settings/access-control/src/components/AccessItem/AccessItem.tsx
Labels: automerge

#8005 fix(ads): National registry client rewrite
  apps/air-discount-scheme/api/src/app/modules/discount/discount.resolver.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.controller.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.model.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.module.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/e2e/discount.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.controller.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/flight.controller.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/test/e2e/flight.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/test/integration/flight.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.controller.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.module.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.types.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/test/unit/nationalRegistry.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/test/e2e/user.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.controller.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.controller.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.module.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
  apps/air-discount-scheme/backend/test/createTestUser.ts
  libs/air-discount-scheme/types/src/lib/flight.ts
  libs/air-discount-scheme/types/src/lib/user.ts
  libs/testing/containers/src/lib/testing-containers.ts
Labels: automerge

#8003 fix(passport): Passport template - tweaks and fixes
  libs/application/template-api-modules/src/lib/modules/templates/passport/emailGenerators/assignParentBEmail.ts
  libs/application/templates/passport/src/fields/PassportSelection/index.tsx
  libs/application/templates/passport/src/forms/Done.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/forms/WaitingForParentBConfirmation.ts
  libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/messages.ts
  workspace.json
Labels: automerge

#8096 fix(driving-license-application): Temp success message
  libs/application/templates/driving-license/src/fields/Done/Congratulations.tsx
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#8051 refactor(service-portal): use IntroHeader on all screens
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/core/src/screens/NavigationOverviewScreen/NavigationOverviewScreen.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx
  libs/service-portal/endorsements/src/screens/Petitions/Petitions.tsx
  libs/service-portal/endorsements/src/screens/PetitionsAdmin/PetitionsAdmin.tsx
  libs/service-portal/endorsements/src/screens/PetitionsTable/PetitionsTable.tsx
  libs/service-portal/endorsements/src/screens/ViewPetition/ViewPetition.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/finance/src/screens/PaymentOverview/PaymentOverview.tsx
  libs/service-portal/graphql/src/hooks/documents/useListDocuments.ts
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/screens/Company/CompanyInfo.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfoSidebars.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx
Labels: automerge

#8098 fix(fa): Add nullish check for missing municipalities
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
Labels: automerge

#8072 feat(devx): Allow multiple projects and --reset anywhere
  scripts/get-secrets.sh
Labels: automerge

#8053 fix(Data Protection Complaint): Fix import error data protection complaint
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/data-protection-complaint/src/index.ts
Labels: automerge

#8101 fix(fa): Add check if municipality is active
  libs/application/templates/financial-aid/src/lib/utils.ts
Labels: automerge

#8103 fix(passport): removing country code from default value in personal info
  libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts
  libs/application/templates/passport/src/forms/infoSection/personalInfo.ts
  libs/application/templates/passport/src/utils/removeCountryCode.ts
Labels: automerge

#8084 chore(application): Update pdf for "Kvörtun til persónuverndar"
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
Labels: automerge

#8054 feat(application-system): Add client side pagination on application overview
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
Labels: automerge

#8048 feat(application-system): Unlist applications for certain role/state combinations
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/e2e/applicationAccess.spec.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.spec.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/StateMachine.ts
  libs/testing/fixtures/src/index.ts
  libs/testing/fixtures/src/lib/application.ts
Labels: automerge

#8082 feat(ci): pre release feature deploy v2
  .github/workflows/push.yml
Labels: automerge

#8086 chore(web): Remove old feature flags from the code
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx
  apps/web/hooks/useFeatureFlag.ts
Labels: automerge

#8040 chore(accident-notification): Add max file size and message to file uploads
  libs/application/templates/accident-notification/src/constants/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/whoIsTheNotificationForSection.ts
  libs/application/templates/accident-notification/src/forms/InReviewForm/addAttachmentsSection.ts
  libs/application/templates/accident-notification/src/lib/messages/error.ts
Labels: automerge

#8108 fix(announcement-of-death): Removed unused and insecure endpoint
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.resolver.ts
Labels: automerge

#8107 fix(ads): Accessibility fixes and type fixes
  apps/air-discount-scheme/web/assets/loftbru.svg
  apps/air-discount-scheme/web/assets/srn.svg
  apps/air-discount-scheme/web/assets/veg.svg
  apps/air-discount-scheme/web/components/Link/Link.tsx
  apps/air-discount-scheme/web/screens/GenericPage/GenericPage.tsx
  apps/air-discount-scheme/web/screens/NotFound/NotFound.tsx
  apps/air-discount-scheme/web/screens/Subsidy/Subsidy.tsx
  apps/air-discount-scheme/web/screens/Subsidy/components/Benefits/Benefits.tsx
  apps/air-discount-scheme/web/screens/Subsidy/components/NoBenefits/NoBenefits.tsx
Labels: automerge

#8111 fix(passport): phone number tweak for country code
  libs/application/templates/passport/src/utils/removeCountryCode.ts
Labels: automerge

#8028 fix(j-s): Gender Leak
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOne.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
Labels: automerge

#8093 fix(j-s): fix small print fallback when institution is missing
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfCourtRecord.ts
Labels: automerge

#8095 feat(j-s): add service interruption banner
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/src/components/ServiceInterruptionBanner/ServiceInterruptionBanner.tsx
  apps/judicial-system/web/src/components/index.ts
Labels: automerge

#8043 chore(login service and institution collaboration application): Use applicant email and contact email for 2 applications
  libs/application/template-api-modules/src/lib/modules/templates/funding-government-projects/emailGenerators/applicationConfirmationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationConfirmationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationOverviewTemplate.ts
  libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationEmail.ts
Labels: automerge

#7956 feat(operating-licnese-application): New application
  .github/CODEOWNERS
  libs/application/core/src/lib/institutionMapper.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-license/src/fields/QualityPhoto/Bullets/Bullets.tsx
  libs/application/templates/operating-license/.babelrc
  libs/application/templates/operating-license/.eslintrc
  libs/application/templates/operating-license/README.md
  libs/application/templates/operating-license/babel-jest.config.json
  libs/application/templates/operating-license/jest.config.js
  libs/application/templates/operating-license/src/assets/DigitalServices.tsx
  libs/application/templates/operating-license/src/dataProviders/FeeInfoProvider.ts
  libs/application/templates/operating-license/src/dataProviders/index.ts
  libs/application/templates/operating-license/src/fields/Bullets/index.tsx
  libs/application/templates/operating-license/src/fields/Done/Congratulations.tsx
  libs/application/templates/operating-license/src/fields/Done/index.tsx
  libs/application/templates/operating-license/src/fields/FileOverview/index.tsx
  libs/application/templates/operating-license/src/fields/PaymentCharge/index.tsx
  libs/application/templates/operating-license/src/fields/PaymentPending/index.tsx
  libs/application/templates/operating-license/src/fields/PropertyOverviewRepeater/index.tsx
  libs/application/templates/operating-license/src/fields/PropertyRepeater/PropertyRepeater.css.ts
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/operating-license/src/fields/index.ts
  libs/application/templates/operating-license/src/forms/Done.ts
  libs/application/templates/operating-license/src/forms/Payment.tsx
  libs/application/templates/operating-license/src/forms/draft/draft.ts
  libs/application/templates/operating-license/src/forms/draft/index.ts
  libs/application/templates/operating-license/src/forms/draft/sectionApplicationInfo.ts
  libs/application/templates/operating-license/src/forms/draft/sectionOverview.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOpeningHours.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOperationInfo.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOtherInfo.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionPropertyRepeater.ts
  libs/application/templates/operating-license/src/graphql/index.ts
  libs/application/templates/operating-license/src/index.ts
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/application/templates/operating-license/src/lib/constants.ts
  libs/application/templates/operating-license/src/lib/dataSchema.ts
  libs/application/templates/operating-license/src/lib/error.ts
  libs/application/templates/operating-license/src/lib/messages.ts
  libs/application/templates/operating-license/src/lib/utils.ts
  libs/application/templates/operating-license/tsconfig.json
  libs/application/templates/operating-license/tsconfig.lib.json
  libs/application/templates/operating-license/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, high priority

#8113 fix(j-s): Defender pdf fix
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
Labels: automerge

#8115 fix(operating-license-application): slug
  libs/application/templates/operating-license/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#8118 fix(applications): Add dynamic url to service portal application url
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
Labels: automerge

#8120 fix(application-system): added reply and reverted from changes
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationEmail.ts
Labels: automerge

#8121 fix(applications): Add dynamic url to service portal application url
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
Labels: automerge

#8122 fix(application-system): Reverted tell us a story and added reply to application emails
  libs/api/domains/communications/src/lib/emailTemplates/tellUsAStory.ts
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/login-service/emailGenerators/applicationEmail.ts
Labels: automerge

#7735 fix(service-portal): Update translations for information
  libs/service-portal/information/src/helpers/localizationHelpers.ts
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/Company/CompanyInfo.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  workspace.json
Labels: automerge

#8125 fix(web): Fix FeaturedArticles display condition for resolved articles
  apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
Labels: automerge

#8126 fix(fa): Hotfix for thjodskra spouse error
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
Labels: automerge

#8127 fix(fa): Fix thjodskra spouse error
  libs/api/domains/national-registry-x-road/src/lib/nationalRegistryXRoad.service.ts
Labels: automerge

#7952 feat(service-portal): Passport client
  .github/CODEOWNERS
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/auth/scopes/src/lib/nationalRegistry.scope.ts
  libs/clients/passports/.eslintrc.json
  libs/clients/passports/README.md
  libs/clients/passports/jest.config.js
  libs/clients/passports/src/clientConfig.yaml
  libs/clients/passports/src/index.ts
  libs/clients/passports/src/lib/PassportsApiProvider.ts
  libs/clients/passports/src/lib/passports.config.ts
  libs/clients/passports/src/lib/passports.module.ts
  libs/clients/passports/tsconfig.json
  libs/clients/passports/tsconfig.lib.json
  libs/clients/passports/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#8134 fix(accident-notification): Remove unlisted application in template temporarily
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
Labels: automerge

#8138 feat(user-profile): Add english translations to confirmation code email
  apps/services/user-profile/src/app/user-profile/verification.service.ts
Labels: automerge

#8139 fix(accident-notification): Reintroduce unlist for last role
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
Labels: automerge

#7900 refactor(j-s): Replace setAndSendToServer and setAndSendDateToServer with autofill
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/ConclusionDraft/ConclusionDraft.tsx
  apps/judicial-system/web/src/components/CourtArrangements/index.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/ReceptionAndAssignment/ReceptionAndAssignmentForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/ReceptionAndAssignment/ReceptionAndAssignmentForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/ArrestDate.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectCourt/SelectCourt.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/SelectProsecutor/SelectProsecutor.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/useCase.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#8133 fix(accident-notification): Remove unlisted application in template temporarily
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
Labels: automerge

#8104 feat(j-s): cases mobile view
  apps/judicial-system/web/messages/Core/requests.ts
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/ViewportProvider/ViewportProvider.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/TableSkeleton.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useViewport/useViewport.ts
Labels: automerge

#8142 build: fix openapi attribute injection race condition
  libs/clients/adr-and-machine-license/project.json
  libs/clients/driving-license-book/project.json
  libs/clients/driving-license/project.json
  libs/clients/fishing-license/project.json
  libs/clients/national-registry/v2/project.json
  libs/clients/rsk/company-registry/project.json
  libs/clients/syslumenn/project.json
  libs/clients/vehicles/project.json
Labels: automerge

#8129 fix(j-s): make case type required to continue for investigation cases
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#8144 chore(core): Update kennitala package
  package.json
  yarn.lock
Labels: automerge

#8146 fix(service-portal): client build failing
  libs/clients/vehicles/project.json
Labels: automerge

#8117 chore(web): Update contentful types
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/processEntry.model.ts
  libs/cms/src/lib/search/importers/article.service.ts
Labels: automerge

#8136 fix(service-portal): vehicles add null check to reggroup
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Labels: automerge

#8149 feat(ids): Add license key secret to config.
  .github/actions/ci-io.ts
  .github/actions/dist/index.js
  .github/actions/main.ts
  apps/services/auth-api/infra/identity-server.ts
  apps/services/auth-api/src/app/modules/clients/clients.controller.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#8151 fix(ci): Removing quotes from branch name
  .github/actions/dist/index.js
  .github/actions/main.ts
Labels: automerge

#8116 chore(applications): Update default state lifecycle for applications
  libs/application/core/src/lib/ApplicationTemplateHelper.spec.ts
  libs/application/core/src/lib/constants.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/ComplaintsToAlthingiOmbudsmanTemplate.ts
  libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/example-payment/src/lib/examplePaymentTemplate.ts
  libs/application/templates/financial-statements-inao/src/lib/financialStatementsInao.ts
  libs/application/templates/funding-government-projects/src/lib/FundingGovernmentProjectsTemplate.ts
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
  libs/application/templates/institution-collaboration/src/lib/template.ts
  libs/application/templates/login-service/src/lib/LoginServiceTemplate.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
Labels: automerge

#8140 feat(j-s): court end date field
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/validate.spec.ts
Labels: automerge

#8152 judicial-system(fix): Update README.md
  apps/judicial-system/README.md
Labels: automerge

#8153 fix(operating-license-application): Opening hours validation
  libs/application/templates/operating-license/src/lib/dataSchema.ts
  libs/application/templates/operating-license/src/lib/error.ts
Labels: automerge

#8150 feat(web): Article statistics embed
  apps/web/components/Charts/SimplePieChart/SimplePieChart.tsx
  apps/web/components/Charts/charts.css.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/models/graphCard.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#8128 feat(service-portal): add samgöngustofa scope to client config
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/vehicles.scope.ts
  libs/clients/vehicles/src/lib/vehiclesClient.config.ts
Labels: automerge

#7974 test(e2e): air-discount-scheme
  apps/air-discount-scheme/README.md
  apps/air-discount-scheme/backend/docker-compose.yml
  apps/air-discount-scheme/web/components/Toast/Toast.tsx
  apps/air-discount-scheme/web/screens/Subsidy/components/Benefits/Benefits.tsx
  apps/air-discount-scheme/web/screens/Subsidy/components/CodeCard/CodeCard.tsx
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/cypress.env.json
  apps/system-e2e/src/integration/air-discount-scheme/homepage.spec.ts
  apps/system-e2e/src/integration/service-portal/homepage.spec.ts
  apps/system-e2e/src/integration/web/homepage.spec.ts
  apps/system-e2e/src/support/commands.ts
  apps/system-e2e/src/support/index.d.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/tsconfig.json
  apps/web/README.md
  libs/island-ui/core/src/lib/Text/Text.tsx
  package.json
  yarn.lock
Labels: automerge

#8132 feat(service-portal): Correction for family data
  libs/api/domains/national-registry/src/lib/dto/FamilyCorrectionInput.input.ts
  libs/api/domains/national-registry/src/lib/graphql/correction.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/index.ts
  libs/api/domains/national-registry/src/lib/graphql/models/familyCorrection.model.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/clients/national-registry/v1/src/lib/dto/familyCorrection.dto.ts
  libs/clients/national-registry/v1/src/lib/dto/index.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
  libs/service-portal/core/src/components/Modal/Modal.tsx
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/FamilyMember/Child.tsx
  libs/service-portal/information/src/screens/FamilyMember/ChildRegistrationModal.tsx
  libs/service-portal/information/src/screens/FamilyMember/FamilyMember.tsx
Labels: automerge

#8158 fix(j-s): dont render invalid dates in case list
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
Labels: automerge

#8167 test(system-e2e): tsconfig, fixtures and loftbru bug workaround
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/cypress.env.json
  apps/system-e2e/src/fixtures/air-discount-scheme/users.json
  apps/system-e2e/src/fixtures/service-portal/users.json
  apps/system-e2e/src/integration/air-discount-scheme/homepage.spec.ts
  apps/system-e2e/src/integration/service-portal/homepage.spec.ts
  apps/system-e2e/src/integration/web/homepage.spec.ts
  apps/system-e2e/src/integration/web/search.spec.ts
  apps/system-e2e/src/lib/types.ts
  apps/system-e2e/src/support/commands.ts
  apps/system-e2e/src/support/index.d.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/tsconfig.app.json
  apps/system-e2e/tsconfig.json
  scripts/ci/Dockerfile.cypress
Labels: automerge

#8168 test(system-e2e): fix environment name bug
  apps/system-e2e/cypress.config.ts
Labels: automerge

#8141 refactor(auth-react): Refactor Check IDP Session
  libs/auth/react/src/lib/Authenticator/CheckIdpSession.tsx
Labels: automerge

#8163 test(skilavottord): Smoke test
  apps/skilavottord/web/components/GDPR/withGDPR.tsx
  apps/system-e2e/src/fixtures/skilavottord/users.json
  apps/system-e2e/src/integration/skilavottord/citizen.spec.ts
  apps/system-e2e/src/support/commands.ts
Labels: automerge

#8173 feat(service-portal): Add feature flag option for single pages
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
Labels: automerge

#8172 feat(j-s): fix for court end date
  apps/judicial-system/backend/src/app/formatters/courtRecord.spec.ts
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfCourtRecord.ts
  apps/judicial-system/web/messages/Core/courtRecordAccordion.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
  apps/judicial-system/web/src/components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
Labels: automerge

#8176 chore(service-portal): documentation for route key in service portal
  libs/service-portal/core/src/lib/service-portal-core.ts
Labels: automerge

#8180 feat(service-portal): Add defaultvalue to child registration modal
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/utils/phoneHelper.ts
  libs/service-portal/information/src/screens/FamilyMember/ChildRegistrationModal.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
Labels: automerge

#8179 fix(p-sign-application): Legal Guardian contact info
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/templates/p-sign/src/forms/application.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionDataProviders.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionDelivery.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionInformation.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionInformationActor.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionOverview.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionPhoto.ts
  libs/application/templates/p-sign/src/forms/applicationWithActor.ts
  libs/application/templates/p-sign/src/lib/constants.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
Labels: automerge

#8109 fix(web): Stafrænt Ísland news language toggle correction
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
Labels: automerge

#8170 feat(web): Form - use field from content type instead of from UI configuration
  apps/web/components/Form/Form.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/form.model.ts
Labels: automerge

#8182 fix(service-portal): Update phoneHelper.ts
  libs/service-portal/core/src/utils/phoneHelper.ts
Labels: automerge

#8165 feat(web): Allow news to be filtered by multiple tags in rss feed
  apps/web/pages/api/rss/index.ts
  apps/web/screens/Home/Home.tsx
  apps/web/screens/News.tsx
  apps/web/screens/Organization/NewsList.tsx
  apps/web/screens/Project/Project.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/dto/getNews.input.ts
  libs/cms/src/lib/models/latestNewsSlice.model.ts
Labels: automerge

#8174 feat(j-s): add case types for indictment cases
  apps/judicial-system/backend/migrations/20220819104956-update-case.js
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#8155 chore(core): Update API Design Guide
  SUMMARY.md
  handbook/technical-overview/api-design-guide/README.md
  handbook/technical-overview/api-design-guide/documentation.md
  handbook/technical-overview/api-design-guide/errors.md
  handbook/technical-overview/api-design-guide/http-status-codes.md
  handbook/technical-overview/api-design-guide/pagination.md
  handbook/technical-overview/api-design-guide/rest-response.md
  handbook/technical-overview/api-design-guide/security.md
  handbook/technical-overview/auth/postman-test.md
Labels: automerge

#8131 fix(island-ui): Update dialogprompt to match other island.is designs
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.css.ts
  libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.tsx
Labels: automerge

#7997 feat(service-portal): document services sort
  apps/download-service/src/app/modules/documents/document.controller.ts
  apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
  apps/service-portal/src/store/modules.ts
  libs/api/domains/documents/src/lib/document.resolver.ts
  libs/api/domains/documents/src/lib/document.service.ts
  libs/api/domains/documents/src/lib/dto/getDocumentListInput.ts
  libs/api/domains/documents/src/lib/models/document.model.ts
  libs/api/domains/documents/src/lib/models/documentSender.model.ts
  libs/api/domains/documents/src/lib/models/documentType.model.ts
  libs/clients/documents/src/lib/documentClient.ts
  libs/clients/documents/src/lib/models/DocumentDTO.ts
  libs/clients/documents/src/lib/models/DocumentInput.ts
  libs/clients/documents/src/lib/models/ListDocumentsResponse.ts
  libs/clients/documents/src/lib/models/SenderDTO.ts
  libs/clients/documents/src/lib/models/SendersResponse.ts
  libs/clients/documents/src/lib/models/TypeDTO.ts
  libs/clients/documents/src/lib/models/TypesResponse.ts
  libs/clients/documents/src/lib/models/index.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/island-ui/core/src/lib/Filter/Filter.tsx
  libs/island-ui/core/src/lib/Filter/FilterMultiChoice/FilterMultiChoice.tsx
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.css.ts
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.tsx
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilterTags.tsx
  libs/service-portal/documents/src/components/HeaderArrow/HeaderArrow.tsx
  libs/service-portal/documents/src/components/TableHeading/TableHeading.css.ts
  libs/service-portal/documents/src/components/TableHeading/TableHeading.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/types.ts
  libs/service-portal/documents/src/widgets/documentList.tsx
  libs/service-portal/graphql/src/hooks/documents/useListDocuments.ts
  libs/service-portal/graphql/src/lib/queries/listDocuments.ts
Labels: automerge, deploy-feature

#8175 fix(auth-react): Disable user session monitoring on localhost
  libs/auth/react/src/lib/Authenticator/CheckAuth.tsx
  libs/auth/react/src/lib/Authenticator/CheckIdpSession.tsx
Labels: automerge

#8185 feat(service-portal): Add back vehicle lookup. Behind feature flag
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/vehicles/src/index.ts
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
Labels: automerge

#8189 feat(operating-license-application): ProcurationHolder delegation
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/templates/operating-license/codegen.yml
  libs/application/templates/operating-license/project.json
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
Labels: automerge

#8064 feat(service-portal): Add application status subpages overview
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/service-portal/applications/src/components/ApplicationGroup.tsx
  libs/service-portal/applications/src/index.ts
  libs/service-portal/applications/src/lib/messages.ts
  libs/service-portal/applications/src/lib/service-portal-applications.tsx
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/applications/src/shared/types/index.ts
  libs/service-portal/applications/src/shared/utils/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
Labels: automerge

#8147 feat(service-portal): remove family from path
  apps/service-portal/src/components/MobileMenu/figuresMapper.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/information/src/index.ts
  libs/service-portal/information/src/screens/UserInfoOverview/mockUserInfoList.ts
Labels: automerge

#8046 feat(application-system): Only allow only one application of each type as default behaviour
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/ApplicationTemplate.ts
Labels: automerge

#8162 feat(auth-public-api): Add scopes value to audit log on create and update on delegation.
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/services/delegations.service.ts
  libs/auth-api-lib/src/lib/utils/compareScopes.spec.ts
  libs/auth-api-lib/src/lib/utils/compareScopes.ts
Labels: automerge

#8143 chore(system-e2e): package code similar to other services so it use code outside of its workspace
  .gitignore
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/project.json
  apps/system-e2e/src/integration/air-discount-scheme/acceptance-test/homepage.spec.ts
  apps/system-e2e/src/integration/service-portal/smoke-test/homepage.spec.ts
  apps/system-e2e/src/integration/skilavottord/smoke-test/citizen.spec.ts
  apps/system-e2e/src/integration/web/smoke-test/homepage.spec.ts
  apps/system-e2e/src/integration/web/smoke-test/search.spec.ts
  apps/system-e2e/src/lib/types.ts
  apps/system-e2e/src/main.ts
  apps/system-e2e/src/support/commands.ts
  apps/system-e2e/src/support/index.ts
  apps/system-e2e/src/support/uncaughtExceptions.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/tsconfig.app.json
  apps/system-e2e/tsconfig.json
  apps/system-e2e/webpack.config.js
  scripts/ci/90_docker-cypress.sh
  scripts/ci/Dockerfile.cypress
  scripts/ci/_docker.sh
  scripts/run-cypress-tests.sh
Labels: automerge

#8102 feat(service-portal): use generic licenses in license UI
  apps/service-portal/src/assets/images/adr_machine.svg
  apps/service-portal/src/assets/images/island.svg
  libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseMapper.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseMappers.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseMappers.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseService.api.ts
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/graphql/payload.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/education-degree/src/screens/EducationDegree/components/DegreeCards/DegreeCards.tsx
  libs/service-portal/graphql/src/hooks/licenses/useLicenses.ts
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/queries/getLicenses.ts
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.css.ts
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.tsx
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCards.tsx
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCardsNotUsed.tsx
  libs/service-portal/licenses/src/components/LicenseCards/index.ts
  libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx
  libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.tsx
  libs/service-portal/licenses/src/index.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/ExpandableLine.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/index.ts
  libs/service-portal/licenses/src/screens/LicenseDetail/ExpandableLine.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.css.ts
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/LicensesOverview.tsx
  libs/service-portal/licenses/src/utils/dataMapper.ts
Labels: automerge, deploy-feature

#8161 feat(application-system): Add attachment delete to application delete
  SUMMARY.md
  apps/api/src/app/app.module.ts
  apps/application-system/api/infra/application-system-api.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.module.ts
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
  apps/application-system/api/src/app/modules/application/lifecycle/test/application-lifecycle-unit.spec.ts
  apps/application-system/api/src/environments/environment.interface.ts
  apps/application-system/api/src/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/file-upload/src/lib/file-upload.module.ts
  libs/application/api/files/.eslintrc.json
  libs/application/api/files/README.md
  libs/application/api/files/jest.config.js
  libs/application/api/files/project.json
  libs/application/api/files/src/index.ts
  libs/application/api/files/src/lib/file.service.spec.ts
  libs/application/api/files/src/lib/file.service.ts
  libs/application/api/files/src/lib/files.config.ts
  libs/application/api/files/src/lib/files.module.ts
  libs/application/api/files/src/lib/index.ts
  libs/application/api/files/src/lib/pdfGenerators/familyMatters.ts
  libs/application/api/files/src/lib/pdfGenerators/index.ts
  libs/application/api/files/src/lib/pdfGenerators/residenceChange.ts
  libs/application/api/files/src/lib/upload.processor.ts
  libs/application/api/files/src/lib/utils/constants.ts
  libs/application/api/files/src/lib/utils/districtCommissionerLogo.ts
  libs/application/api/files/src/lib/utils/pdfUtils.ts
  libs/application/api/files/src/lib/utils/types.ts
  libs/application/api/files/tsconfig.json
  libs/application/api/files/tsconfig.lib.json
  libs/application/api/files/tsconfig.spec.json
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/funding-government-projects/funding-government-projects.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/institution-collaboration.module.ts
  libs/file-storage/src/index.ts
  libs/file-storage/src/lib/file-storage.configuration.ts
  libs/file-storage/src/lib/file-storage.module.ts
  libs/file-storage/src/lib/file-storage.service.spec.ts
  libs/file-storage/src/lib/file-storage.service.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, deploy-feature

#8194 fix(service-portal): remove vehicle csv, data missing
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Labels: automerge

#8188 fix(j-s): Restrict Ruling Modification
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/ruling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#8191 fix(j-s): Restrict Court Record Signature
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#8193 feat(j-s): Mask filenames
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#8199 fix(download-service): Add env vars for vehicles
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#8186 feat(j-s): Indictments - Defendant screen
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/defendant.spec.ts
  apps/judicial-system/web/messages/Core/courtDocuments.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/Core/policeCaseNumber.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/messages/Indictments/Prosecutor/defendant.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.css.ts
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/MultipleValueList/MultipleValueList.css.ts
  apps/judicial-system/web/src/components/MultipleValueList/MultipleValueList.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOne.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/PoliceCaseNumbers/PoliceCaseNumbers.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#8201 fix(download-service): Vehicle env
  apps/download-service/infra/download-service.ts
  apps/download-service/src/app/modules/vehicles-documents/vehicle-document.controller.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#8200 fix(download-service): correct scope
  apps/download-service/src/app/modules/vehicles-documents/vehicle-document.controller.ts
Labels: automerge

#8206 fix(ads): temporary heightened logging
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8203 fix(application-system): Add missing envs to application api worker
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#8209 chore(docker-compose): Remove obsolete somaxconn sysctl
  apps/application-system/api/docker-compose.yml
  apps/github-actions-cache/docker-compose.yml
Labels: automerge

#8213 fix(j-s): fix migration for case type enums
  apps/judicial-system/backend/migrations/20220819104956-update-case.js
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#8198 chore(system-e2e): fix dockerfile cypress dist folder
  .gitignore
  apps/system-e2e/cypress.config.ts
  apps/system-e2e/project.json
  apps/system-e2e/src/integration/air-discount-scheme/acceptance/discount-data.spec.ts
  apps/system-e2e/src/integration/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/integration/skilavottord/smoke/vehicles.ts
  apps/system-e2e/src/integration/web/smoke/homepage.spec.ts
  apps/system-e2e/src/integration/web/smoke/search.spec.ts
  apps/system-e2e/src/lib/types.ts
  apps/system-e2e/src/main.ts
  apps/system-e2e/src/support/commands.ts
  apps/system-e2e/src/support/index.ts
  apps/system-e2e/src/support/uncaughtExceptions.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/tsconfig.app.json
  apps/system-e2e/tsconfig.json
  apps/system-e2e/webpack.config.js
  scripts/ci/90_docker-cypress.sh
  scripts/ci/Dockerfile
  scripts/ci/Dockerfile.cypress
  scripts/ci/_docker.sh
  scripts/run-cypress-tests.sh
Labels: automerge

#8197 feat(j-s): Indictments - processing screen
  apps/judicial-system/web/messages/Core/commentsInput.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/messages/Indictments/Prosecutor/processing.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/reportForm.tsx
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/pages/akaerur/malsmedferd/[id].ts
  apps/judicial-system/web/src/components/CommentsInput/CommentsInput.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#8212 fix(service-portal): This reverts license UI
  apps/service-portal/src/assets/images/adr_machine.svg
  apps/service-portal/src/assets/images/island.svg
  libs/api/domains/license-service/src/lib/client/adr-license-client/adrLicenseMapper.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseMappers.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseMappers.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseService.api.ts
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/graphql/payload.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/education-degree/src/screens/EducationDegree/components/DegreeCards/DegreeCards.tsx
  libs/service-portal/graphql/src/hooks/licenses/useLicenses.ts
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/queries/getLicenses.ts
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.css.ts
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.tsx
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCards.tsx
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCardsNotUsed.tsx
  libs/service-portal/licenses/src/components/LicenseCards/index.ts
  libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx
  libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.tsx
  libs/service-portal/licenses/src/index.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.css.ts
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/ExpandableLine.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/index.ts
  libs/service-portal/licenses/src/screens/LicenseDetail/ExpandableLine.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/LicensesOverview.tsx
  libs/service-portal/licenses/src/utils/dataMapper.ts
Labels: automerge

#8216 chore(system-e2e): fix wrong spec file extension
  apps/system-e2e/src/integration/skilavottord/smoke/vehicles.spec.ts
Labels: automerge

#8220 fix(ads): Ensure callee parent is included in custodians
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8202 feat(service-portal): style sidebar scrollbar
  apps/service-portal/src/components/Sidebar/Sidebar.css.ts
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
Labels: automerge, deploy-feature

#8217 fix(j-s): Regression - Add label to noNationalId in DefendantInfo back
  apps/judicial-system/web/messages/Indictments/Prosecutor/defendant.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/defendantForm.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/DefendantInfo/DefendantInfo.tsx
Labels: automerge

#8187 feat(j-s): cases pagee supporting indictment
  apps/judicial-system/web/messages/Core/requests.ts
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
Labels: automerge

#8227 fix(service-portal): Remove user correction
  libs/api/domains/national-registry/src/lib/graphql/correction.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/index.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
Labels: automerge

#8229 chore: Removing a dangerous method that is not used and warning about another
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/environment.ts
Labels: automerge

#8211 fix(application-system-ui): fix for redirect effect
  libs/application/ui-fields/src/lib/RedirectToServicePortalFormField/RedirectToServicePortalFormField.tsx
Labels: automerge

#8178 chore(web): Add codeowners to files
  .github/CODEOWNERS
Labels: automerge

#8233 fix(ads): Ensure callee parent is included in custodians (#8220)
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
Labels: automerge

#8235 chore(system-e2e): resizing timeouts
  apps/system-e2e/src/lib/types.ts
Labels: automerge

#8236 infra(api): more RAM
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#8230 feat(devx): Improve/add dev & dev/init for application-system-api & services-user-profile
  apps/application-system/api/project.json
  apps/services/user-profile/README.md
  apps/services/user-profile/project.json
  package.json
Labels: automerge

#8241 feat(national-registry-v1): Add child registration service back in
  libs/api/domains/national-registry/src/lib/dto/FamilyCorrectionInput.input.ts
  libs/api/domains/national-registry/src/lib/graphql/correction.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/index.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/clients/national-registry/v1/src/lib/dto/familyCorrection.dto.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
  libs/service-portal/information/src/screens/FamilyMember/Child.tsx
  libs/service-portal/information/src/screens/FamilyMember/ChildRegistrationModal.tsx
Labels: automerge

#8181 feat(financial-statements-inao): Add application-api-template module and client
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/environments.ts
  libs/api/domains/financial-statements-inao/src/index.ts
  libs/api/domains/financial-statements-inao/src/lib/client/dataverseClient.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.module.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/api/domains/financial-statements-inao/src/lib/models/clientType.model.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/clients/financial-statements-inao/.eslintrc.json
  libs/clients/financial-statements-inao/README.md
  libs/clients/financial-statements-inao/jest.config.js
  libs/clients/financial-statements-inao/project.json
  libs/clients/financial-statements-inao/src/index.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInao.config.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.module.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
  libs/clients/financial-statements-inao/src/lib/types/index.ts
  libs/clients/financial-statements-inao/tsconfig.json
  libs/clients/financial-statements-inao/tsconfig.lib.json
  libs/clients/financial-statements-inao/tsconfig.spec.json
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#8246 feat(parental-leave): change emails sender to noreply@island.is
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/employerRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/otherParentRejectedEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#8249 feat(j-s): Feedback Iteration
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/confirmation.ts
  apps/judicial-system/web/src/components/Header/Header.strings.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
Labels: automerge

#8253 chore(skilavottord-web): Update client secret env name
  apps/skilavottord/web/environments/environment.ts
  apps/skilavottord/web/infra/web.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#8262 fix(ci): disabling the tests that do not work on deployment to Dev
  apps/system-e2e/src/integration/air-discount-scheme/smoke/discount-data.spec.ts
  apps/system-e2e/src/integration/skilavottord/smoke/vehicles.spec.ts
Labels: automerge

#8263 chore(ci): allow to render values for all services when service name is '*'
  infra/src/feature-env.ts
Labels: automerge

#8265 fix: added required signature crt package for aws client-ses
  scripts/local-e2e.sh
Labels: automerge

#8268 chore(web): Stepper helper changes
  apps/web/components/Stepper/StepperHelper/StepperHelper.tsx
Labels: automerge

#8258 fix(operating-license-application): submit with no opening hours
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/types/application.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/utils.ts
Labels: automerge

#8260 feat(service-portal): Vehicles insured in main info
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
Labels: automerge

#8256 chore: bump ioredis from v4 to v5
  libs/cache/src/lib/cache.ts
  package.json
  yarn.lock
Labels: automerge

#8271 feat(parental-leave): only use noreply email on production
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#8270 fix(j-s): display first police case number in list
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  libs/judicial-system/formatters/src/lib/formatters.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#8250 feat(j-s): CourtRecord accordion date fixes
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/project.json
  apps/judicial-system/web/src/components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordion.strings.ts
  apps/judicial-system/web/src/components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
Labels: automerge

#8238 feat(j-s): Indictments - Case Files screen
  apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/migrations/20220824084711-update-case.js
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/pages/akaerur/domskjol/[id].ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#8272 fix(fa): Add size and type restriction to upload files
  libs/application/templates/financial-aid/src/fields/Files/Files.tsx
  libs/application/templates/financial-aid/src/lib/constants.ts
  libs/application/templates/financial-aid/src/lib/hooks/useFileUpload.ts
  libs/application/templates/financial-aid/src/lib/messages/application.ts
Labels: automerge

#8278 revert(dependency): downgrade ioredis from v5 to v4
  libs/cache/src/lib/cache.ts
  package.json
  yarn.lock
Labels: automerge

#8273 feat(j-s): court and defendants on every step in indictment cases
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/IndictmentCaseIntro/IndictmentCaseIntro.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/IndictmentCaseIntro/IndictmentCaseIntro.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/PoliceCaseNumbersTags/PoliceCaseNumbersTags.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#8264 test(ci): acceptance test config values
  .github/workflows/push.yml
  apps/application-system/api/infra/application-system-api.ts
  apps/system-e2e/src/integration/air-discount-scheme/smoke/discount-data.spec.ts
  apps/system-e2e/src/lib/types.ts
  apps/system-e2e/src/support/utils.ts
  infra/src/dsl/serialize-to-yaml.ts
Labels: automerge, deploy-feature

#8243 chore(service-portal): cleanup unused feature flags
  apps/service-portal/src/store/modules.ts
Labels: automerge

#8257 fix(service-portal): translation bug
  apps/service-portal/src/components/Layout/Layout.tsx
Labels: automerge

#8275 fix(service-portal): date picker popper
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.css.ts
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.tsx
Labels: automerge

#8279 feat(get-secrets): Better secret rendering
  infra/src/cli/render-secrets.ts
Labels: automerge

#8282 fix(skilavottord): import of pagelayout
  apps/skilavottord/web/components/Footer/Footer.tsx
  apps/skilavottord/web/components/index.ts
  apps/skilavottord/web/types.tsx
Labels: automerge

#8281 fix(cd): excluding main branch from beeing treated like a feature deployment
  apps/system-e2e/src/support/utils.ts
Labels: automerge
