Repository island-is/island.is, pull requests merged in 2022-01, with the labels that each got.

#6099 ci: Retry if cache fails
  .github/actions/cache/action.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#6105 fix(user-notification): Change to default swagger path
  apps/services/user-notification/src/main.ts
Labels: automerge

#5700 feat(web): Adding datadog-rum to islandis web
  SUMMARY.md
  apps/web/infra/web.ts
  apps/web/layouts/main.tsx
  apps/web/next.config.js
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  jest.config.js
  libs/infra-tracing/src/lib/datadog-tracer.spec.ts
  libs/infra-tracing/src/lib/datadog-tracer.ts
  libs/logging/src/lib/formatters.spec.ts
  libs/logging/src/lib/formatters.ts
  libs/logging/src/lib/logging.ts
  libs/logging/src/lib/remove-national-ids.ts
  libs/shared/pii/.eslintrc.json
  libs/shared/pii/README.md
  libs/shared/pii/jest.config.js
  libs/shared/pii/src/index.ts
  libs/shared/pii/src/lib/maskNationalId.spec.ts
  libs/shared/pii/src/lib/maskNationalId.ts
  libs/shared/pii/tsconfig.json
  libs/shared/pii/tsconfig.lib.json
  libs/shared/pii/tsconfig.spec.json
  libs/user-monitoring/.eslintrc.json
  libs/user-monitoring/README.md
  libs/user-monitoring/jest.config.js
  libs/user-monitoring/src/index.ts
  libs/user-monitoring/src/lib/user-monitoring.ts
  libs/user-monitoring/tsconfig.json
  libs/user-monitoring/tsconfig.lib.json
  libs/user-monitoring/tsconfig.spec.json
  nx.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: automerge, deploy-feature

#6107 fix(judicial-system): Remove autofill from litigationPresentations when SESSION_ARRANGEMENTS are REMOTE_SESSION
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecord.tsx
Labels: automerge

#6094 fix(web): HTML/CSS errors fix
  apps/web/components/IconTitleCard/IconTitleCard.tsx
  apps/web/components/Menu/Menu.tsx
  apps/web/components/NewsItems/Item.tsx
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.css.ts
  apps/web/components/StoryList/StoryList.css.ts
  apps/web/screens/Adgerdir/components/UI/Button/Button.css.ts
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.css.ts
  libs/island-ui/core/src/lib/Button/Button.css.ts
Labels: automerge

#6111 feat(web): Organization page external links only on organization homepage
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarHeader.css.ts
  apps/web/screens/Organization/Home.tsx
Labels: automerge

#6110 fix(skilavottord): fix ingress path for ws
  apps/skilavottord/web/components/Header/Header.tsx
  apps/skilavottord/web/graphql/errorLink.ts
  apps/skilavottord/web/server.ts
  apps/skilavottord/ws/infra/ws.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, deploy-feature

#6116 fix(skilavottord): use request.auth instead of cookies
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
Labels: automerge

#6045 feat(personal-representative): Add step for apiScope in auth-admin-web to associate scope with personal representative permissions
  apps/auth-admin-web/components/Resource/forms/ApiScopePersonalRepresentativePermissionsForm.tsx
  apps/auth-admin-web/components/Resource/nav/ApiScopeStepNav.tsx
  apps/auth-admin-web/entities/common/ApiScopeStep.ts
  apps/auth-admin-web/entities/dtos/personal-representative-scope-permission.dto.ts
  apps/auth-admin-web/entities/models/personal-representative-permission-type.model.ts
  apps/auth-admin-web/entities/models/personal-representative-scope-permission.model.ts
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/pages/resource/api-scope/[edit].tsx
  apps/auth-admin-web/services/ResourcesService.ts
  apps/auth-admin-web/styles/_FormLayout.scss
  apps/services/auth-admin-api/src/app/app.module.ts
  apps/services/auth-admin-api/src/app/modules/personal-representative/personal-representative.controller.ts
  apps/services/auth-admin-api/src/app/modules/personal-representative/personal-representative.module.ts
  libs/auth-api-lib/migrations/20211206134347-add-personal-representative-scope-permission-table.js
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/entities/dto/personal-representative-scope-permission.dto.ts
  libs/auth-api-lib/src/lib/entities/models/personal-representative-scope-permission.model.ts
  libs/auth-api-lib/src/lib/services/personal-representative-scope-permission.service.ts
Labels: automerge

#6119 chore(skilavottord): cleanup charts
  apps/skilavottord/README.md
  apps/skilavottord/web/environments/environment.ts
  apps/skilavottord/ws/infra/ws.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#6117 feat(application-templates-driving-license): Changes to the payment field
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/fields/ExamplePaymentPendingField.tsx
  libs/application/templates/driving-license/src/fields/PaymentPending/PaymentPending.tsx
  libs/application/templates/driving-license/src/fields/PaymentPending/hooks/index.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/hooks/queries.graphql.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/hooks/useMsg.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/hooks/usePaymentStatus.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/hooks/useSubmitApplication.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/index.tsx
  libs/application/templates/driving-license/src/fields/PaymentPending/types.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/util.ts
  libs/application/templates/driving-license/src/fields/index.ts
  libs/application/templates/driving-license/src/forms/payment.tsx
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/utils/handleCreateResponse.spec.ts
  libs/clients/driving-license/src/lib/utils/handleCreateResponse.ts
Labels: automerge

#6098 feat(user-profile): Client scope migration
  libs/auth-api-lib/seeders/data/client-scope-user-profile-notifications.ts
Labels: automerge

#6113 ci: Use composite cache action in all jobs
  .github/actions/unit-test/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#6114 feat(user-profile): Adding admin:scoped settings endpoint
  apps/services/user-profile/src/app/user-profile/dto/userDeviceTokens.dto.ts
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.service.ts
  apps/services/user-profile/src/app/user-profile/userToken.controller.ts
Labels: automerge

#6011 fix(service-portal): featureflag islykill (#5986)
  apps/api/src/app/app.module.ts
  libs/api/domains/islykill/src/lib/graphql/main.resolver.ts
  libs/api/domains/islykill/src/lib/islykill.module.ts
  libs/feature-flags/src/lib/features.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
  scripts/build-graphql-schema.ts
Labels: automerge

#6112 feat(judicial-system): Add case type ELECTRONIC_DATA_DISCOVERY_INVESTIGATION
  apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.spec.ts
  apps/judicial-system/api/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/migrations/20220103144916-update-case.js
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/case.spec.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#6118 feat(web): Added unique key prop to Sjukratryggingar footer
  apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
Labels: automerge

#6129 feat(web): Syslumenn / Remove outdated temporary alert
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home.tsx
Labels: automerge

#6067 chore(judicial-system): Investigation cases e2e tests
  apps/judicial-system/web-e2e/src/fixtures/judgeUser.json
  apps/judicial-system/web-e2e/src/fixtures/judgeUsers.json
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/confirmation.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/rulingStepOne.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/rulingStepTwo.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationRequests/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationRequests/demands.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationRequests/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationRequests/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationRequests/report.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/accused.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/stepFour.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/stepThree.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionRequests/stepTwo.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web-e2e/src/support/index.d.ts
  apps/judicial-system/web/src/components/PageLayout/utils/index.spec.ts
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/formatters/src/lib/testData.ts
Labels: automerge

#6066 fix(web): correct color scheme for search result card
  apps/web/screens/Search/Search.tsx
Labels: automerge

#6087 test(fa): application controller test - get by id
  apps/financial-aid/backend/src/app/modules/application/test/getById.spec.ts
Labels: automerge

#6138 fix(skilavottord): use cookies to get user info from session token
  apps/skilavottord/web/components/Header/Header.tsx
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
  apps/skilavottord/ws/src/environments/environment.ts
Labels: automerge

#6083 fix(skilavottord): added check on vehicle before recycling
  apps/skilavottord/web/components/Layouts/AppLayout.tsx
  apps/skilavottord/web/context/UserContext.ts
  apps/skilavottord/web/screens/Completed/Completed.tsx
  apps/skilavottord/web/screens/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/Handover/Handover.tsx
  apps/skilavottord/ws/src/app/modules/accessControl/accessControl.resolver.ts
  apps/skilavottord/ws/src/app/modules/auth/user.model.ts
  apps/skilavottord/ws/src/app/modules/recyclingPartner/recyclingPartner.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.module.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/index.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.module.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/test/samgongustofa.service.spec.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.module.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
Labels: automerge

#6135 fix(infra): Change the postgres image for the m1 chip
  apps/air-discount-scheme/backend/docker-compose.yml
  apps/application-system/api/docker-compose.yml
  apps/financial-aid/backend/docker-compose.yml
  apps/gjafakort/application/docker-compose.yml
  apps/icelandic-names-registry/backend/docker-compose.yml
  apps/judicial-system/backend/docker-compose.yml
  apps/reference-backend/docker-compose.yml
  apps/services/auth-api/docker-compose.yml
  apps/services/documents/docker-compose.yml
  apps/services/endorsements/api/docker-compose.yml
  apps/services/user-profile/docker-compose.yml
  apps/skilavottord/ws/docker-compose.yml
  libs/testing/containers/src/lib/testing-containers.ts
Labels: automerge

#6137 test(fa): application controller - update
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/test/createTestingApplicationModule.ts
  apps/financial-aid/backend/src/app/modules/application/test/update.spec.ts
Labels: automerge

#6134 chore(cms): Updated contentful types
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getSupportFormInOrganization.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/supportForm.model.ts
Labels: automerge

#6109 fix(fa): Fixing amounts calculations
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#6143 fix(fa): Text changes when staff is updated
  apps/financial-aid/web-veita/src/utils/useStaff.ts
Labels: automerge

#6146 fix(skilavottord): fix permissions for citizen
  apps/skilavottord/web/screens/Completed/Completed.tsx
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
Labels: automerge

#6148 test(fa): Application controller - create
  apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/createTestingApplicationModule.ts
Labels: automerge

#6150 test(fa): application controller - create event
  apps/financial-aid/backend/src/app/modules/application/test/createEvent.spec.ts
Labels: automerge

#6128 feat(web): Organization english news items
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/pages/en/o/[slug]/news/[newsSlug]/index.tsx
  apps/web/pages/en/o/[slug]/news/index.tsx
  apps/web/screens/Organization/Services.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge, deploy-feature

#6152 fix(fa): status page minor text updates
  apps/financial-aid/web-osk/src/components/Timeline/timeline.tsx
Labels: automerge

#6136 chore(application-templates-driving-license): remove types.ts
  libs/application/templates/driving-license/src/fields/PaymentPending/types.ts
Labels: automerge

#6151 chore(syslumenn-api): CodeOwners / Add CodeOwners of refactored Syslumenn Client
  .github/CODEOWNERS
  libs/clients/syslumenn/README.md
Labels: automerge

#6063 feat(island-ui): add new popover variant for filter
  apps/web/components/ApiCatalogueFilter/ApiCatalogueFilter.tsx
  apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
  apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
  apps/web/screens/Organizations/FilterMenu.tsx
  apps/web/screens/Organizations/Organiziations.tsx
  libs/island-ui/core/src/lib/Filter/Filter.css.ts
  libs/island-ui/core/src/lib/Filter/Filter.stories.tsx
  libs/island-ui/core/src/lib/Filter/Filter.tsx
  libs/island-ui/core/src/lib/Filter/FilterMultiChoice/FilterMultiChoice.tsx
Labels: automerge

#6157 fix(ci): giving CI last good build script bigger window of SHAs to choose from
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge

#6147 fix(fa): Fixing click outside of aid amount modal
  apps/financial-aid/web-veita/src/components/AidAmountModal/AidAmountModal.css.ts
  apps/financial-aid/web-veita/src/components/AidAmountModal/AidAmountModal.tsx
Labels: automerge

#6122 feat(personal-representative): personal representative delegation support
  apps/auth-admin-web/components/Client/form/ClientCreateForm.tsx
  apps/auth-admin-web/components/Resource/forms/ApiScopeCreateForm.tsx
  apps/auth-admin-web/entities/dtos/api-scope-dto.ts
  apps/auth-admin-web/entities/dtos/base/client-base.dto.ts
  apps/auth-admin-web/entities/models/api-scope.model.ts
  apps/auth-admin-web/entities/models/client.model.ts
  apps/auth-admin-web/i18n/locales/en.json
  libs/auth-api-lib/migrations/20211210103308-add-personal-representative-delegation-support.js
  libs/auth-api-lib/src/lib/entities/dto/api-scopes.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/base/client-base.dto.ts
  libs/auth-api-lib/src/lib/entities/models/api-scope.model.ts
  libs/auth-api-lib/src/lib/entities/models/client.model.ts
Labels: automerge

#6161 feat(fa): data gathering
  libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/application-templates-financial-aid.tsx
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/application.ts
  libs/application/templates/financial-aid/src/lib/messages/error.ts
  libs/application/templates/financial-aid/src/lib/messages/externalData.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/types/index.ts
Labels: automerge

#6142 chore(as): Remove dead code
  SUMMARY.md
  apps/application-system/api/src/app/modules/application/files/file.service.ts
  apps/application-system/api/src/app/modules/application/files/pdfGenerators/index.ts
  apps/application-system/api/src/app/modules/application/files/pdfGenerators/jointCustody.ts
  apps/application-system/api/src/app/modules/application/files/utils/constants.ts
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/core/src/types/PdfTypes.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/family-matters/joint-custody-agreement/.babelrc
  libs/application/templates/family-matters/joint-custody-agreement/.eslintrc
  libs/application/templates/family-matters/joint-custody-agreement/README.md
  libs/application/templates/family-matters/joint-custody-agreement/babel-jest.config.json
  libs/application/templates/family-matters/joint-custody-agreement/src/dataProviders/NationalRegistryProvider.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/dataProviders/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/ChildSupport/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/ContactInfo/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Duration/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Overview/SignatureModal/Modal.css.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Overview/SignatureModal/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Overview/fileSignatureReducer.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Overview/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/SelectChildren/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/SelectLegalResidence/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Shared.css.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/Terms/index.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/components/ContractOverview.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/components/CustodyOverview.tsx
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/components/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/fields/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/forms/JointCustodyAgreementForm.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/JointCustodyAgreementTemplate.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/constants.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/dataSchema.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/application.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/childSupport.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/contactInfo.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/contract.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/duration.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/error.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/externalData.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/selectChildren.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/selectLegalResidence.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/signatureModal.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/lib/messages/terms.ts
  libs/application/templates/family-matters/joint-custody-agreement/src/types/index.ts
  libs/application/templates/family-matters/joint-custody-agreement/tsconfig.json
  libs/application/templates/family-matters/joint-custody-agreement/tsconfig.lib.json
  libs/application/templates/family-matters/joint-custody-agreement/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#5767 fix(web): SearchBox update for search in /s/syslumenn
  apps/web/components/Organization/SearchBox/SearchBox.tsx
Labels: automerge

#6062 chore(judicial-system): Improved error responses
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/filters/allExceptions.filter.ts
  apps/judicial-system/backend/src/app/filters/index.ts
  apps/judicial-system/backend/src/app/modules/aws-s3/awsS3.service.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseExists.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseRead.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseWrite.guard.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/case/test/getCourtRecordSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/requestCourtRecordSignature.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/requestRulingSignature.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileExists.guard.ts
  apps/judicial-system/backend/src/app/modules/file/test/createCaseFile.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/uploadCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.controller.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/police/police.controller.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/user/user.controller.ts
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/xrd-api/src/app/app.controller.ts
  apps/judicial-system/xrd-api/src/app/app.module.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/test/create.spec.ts
  libs/infra-nest-server/src/lib/infra/infra.module.ts
  libs/nest/problem/src/lib/base-problem.filter.spec.ts
  libs/nest/problem/src/lib/base-problem.filter.ts
  libs/nest/problem/src/lib/error.filter.spec.ts
  libs/nest/problem/src/lib/error.filter.ts
  libs/nest/problem/src/lib/problem.module.ts
  libs/nest/problem/src/lib/problem.options.ts
  libs/nest/problem/src/lib/test/setup.ts
Labels: automerge

#6124 chore(services-user-notification): set worker argument correctly
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#6132 feat(judicial-system): Send a calendar invite with court date notification to defender and prosecutor
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
  package.json
  yarn.lock
Labels: automerge

#6164 chore(cms): Removed unused content model, 'location'
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/location.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#6159 fix(user-profile): Hook up to new user profile client
  libs/api/domains/user-profile/src/lib/userProfile.module.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  workspace.json
Labels: automerge

#6163 fix(island-ui): fix icon size for small button
  libs/island-ui/core/src/lib/Button/Button.css.ts
Labels: automerge

#5874 feat(p-sign): P-Sign Application Template
  .github/CODEOWNERS
  SUMMARY.md
  libs/api/domains/syslumenn/src/lib/models/districtCommissionerAgencies.ts
  libs/api/domains/syslumenn/src/lib/models/districtCommissionersAgencies.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/types/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/p-sign/.babelrc
  libs/application/templates/p-sign/.eslintrc
  libs/application/templates/p-sign/README.md
  libs/application/templates/p-sign/babel-jest.config.json
  libs/application/templates/p-sign/codegen.yml
  libs/application/templates/p-sign/jest.config.js
  libs/application/templates/p-sign/src/assets/CoatOfArms.tsx
  libs/application/templates/p-sign/src/assets/School.tsx
  libs/application/templates/p-sign/src/dataProviders/DistrictsProvider.ts
  libs/application/templates/p-sign/src/dataProviders/DoctorsNoteProvider.ts
  libs/application/templates/p-sign/src/dataProviders/index.ts
  libs/application/templates/p-sign/src/fields/Bullets/index.tsx
  libs/application/templates/p-sign/src/fields/Done/Congratulations.tsx
  libs/application/templates/p-sign/src/fields/Done/WarningSection/WarningSection.css.ts
  libs/application/templates/p-sign/src/fields/Done/WarningSection/index.tsx
  libs/application/templates/p-sign/src/fields/Done/index.tsx
  libs/application/templates/p-sign/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/p-sign/src/fields/QualityPhoto/index.tsx
  libs/application/templates/p-sign/src/fields/index.ts
  libs/application/templates/p-sign/src/fields/styles.css.ts
  libs/application/templates/p-sign/src/forms/application.ts
  libs/application/templates/p-sign/src/forms/done.ts
  libs/application/templates/p-sign/src/index.ts
  libs/application/templates/p-sign/src/lib/constants.ts
  libs/application/templates/p-sign/src/lib/dataSchema.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/templates/p-sign/src/types.ts
  libs/application/templates/p-sign/tsconfig.json
  libs/application/templates/p-sign/tsconfig.lib.json
  libs/application/templates/p-sign/tsconfig.spec.json
  libs/clients/syslumenn/src/lib/__mock-data__/responses.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge, high priority

#6154 fix(island-ui): revisit disabled state, fix missing disabled states, add missing stories
  libs/island-ui/core/src/lib/Checkbox/Checkbox.stories.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
  libs/island-ui/core/src/lib/Input/Input.css.ts
  libs/island-ui/core/src/lib/Input/Input.stories.tsx
  libs/island-ui/core/src/lib/Input/Input.tsx
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.css.ts
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.stories.tsx
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
  libs/island-ui/core/src/lib/RadioButton/RadioButton.stories.tsx
  libs/island-ui/core/src/lib/Select/Components/index.tsx
  libs/island-ui/core/src/lib/Select/Select.css.ts
  libs/island-ui/core/src/lib/Select/Select.stories.tsx
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#6169 fix(web): Organization searchbox should appear when language is set to english
  apps/web/screens/Organization/Home.tsx
Labels: automerge

#6171 chore(judicial-system): Use "Varnaraðili" instead of "Sakborningur" everywhere
  apps/judicial-system/web/messages/Core/requests.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationRequest/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/Requests/ActiveRequests.tsx
  apps/judicial-system/web/src/routes/Shared/Requests/PastRequests.tsx
Labels: automerge

#6125 feat(island-ui): image/logo option for CategoryCard
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.css.ts
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.stories.tsx
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx
Labels: automerge

#6172 fix(P-Sign-application): Adding to json
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Labels: automerge

#6168 feat(fa): Adding about form page for applicant
  libs/application/templates/financial-aid/src/fields/AboutForm/AboutForm.tsx
  libs/application/templates/financial-aid/src/fields/DescriptionText/DescriptionText.css.ts
  libs/application/templates/financial-aid/src/fields/DescriptionText/DescriptionText.tsx
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/index.ts
  libs/application/templates/financial-aid/src/lib/application-templates-financial-aid.tsx
  libs/application/templates/financial-aid/src/lib/messages/aboutForm.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
Labels: automerge

#6175 fix(island-ui): fix datepicker without label
  libs/island-ui/core/src/lib/DatePicker/DatePicker.css.ts
  libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
Labels: automerge

#6174 fix(endorsement-system): Text fixes
  libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/service-portal/endorsements/src/lib/messages.ts
  libs/service-portal/endorsements/src/screens/ViewPetitionAdmin/ViewPetitionAdmin.tsx
Labels: automerge

#6176 fix(general-petition): adding access to endorsement id with externalData for signaturee
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
Labels: automerge

#6170 chore(web): a11y tweaks
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/screens/Layouts/SidebarLayout.tsx
Labels: automerge

#6177 chore(user-notification): removing worker health check
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#5771 feat(testing): Infra/support for external contract tests
  .github/workflows/push.yml
  apps/external-contracts-tests/.eslintrc
  apps/external-contracts-tests/esbuild.json
  apps/external-contracts-tests/infra/external-contracts-tests.ts
  apps/external-contracts-tests/jest-to-dd.ts
  apps/external-contracts-tests/jest.config.js
  apps/external-contracts-tests/main.spec.ts
  apps/external-contracts-tests/test-suites/index.ts
  apps/external-contracts-tests/test-suites/soffia.spec.ts
  apps/external-contracts-tests/tsconfig.json
  charts/islandis/values.dev.yaml
  infra/src/uber-charts/islandis.ts
  nx.json
  package.json
  scripts/ci/90_docker-jest.sh
  scripts/ci/Dockerfile
  workspace.json
  yarn.lock
Labels: automerge

#6131 chore(assets): Configure token exchange for Properties API
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  apps/service-portal/src/auth.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/assets/src/lib/api-domains-assets.module.ts
  libs/api/domains/assets/src/lib/api-domains-assets.service.ts
  libs/api/domains/assets/src/lib/authorization-identity.middleware.ts
  libs/clients/assets/src/index.ts
  libs/clients/assets/src/lib/PropertiesApiProvider.ts
  libs/clients/assets/src/lib/assets.config.ts
  libs/clients/assets/src/lib/assets.module.ts
  libs/nest/config/src/index.ts
  libs/nest/config/src/lib/LazyDuringDevScope.ts
Labels: automerge

#6182 chore(dependabot): Remove hard-coded reviewers
  .github/dependabot.yml
Labels: automerge

#6166 fix(auth-nest-tools): Use x-forwarded-for in audit logs
  libs/auth-nest-tools/src/lib/auth.middleware.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/clients/middlewares/src/lib/withAuth.ts
Labels: automerge

#6165 feat(audit): Updating audit to support auditing from auth object without nationalId.
  libs/nest/audit/src/lib/audit.interceptor.spec.ts
  libs/nest/audit/src/lib/audit.interceptor.ts
  libs/nest/audit/src/lib/audit.service.spec.ts
  libs/nest/audit/src/lib/audit.service.ts
Labels: automerge

#6179 feat(island-ui): allow no heading for AlertMessage
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.css.ts
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.stories.tsx
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.tsx
Labels: automerge

#6185 fix(web): Article organization slug not changing on sync
  libs/cms/src/lib/environments/environment.ts
Labels: automerge

#6189 fix(skilavottord): fix permno of undefined
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
Labels: automerge

#6190 fix(skilavottord): fix permno of undefined (#6189)
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
Labels: automerge

#6187 chore(fa): Changing ports to be able to run both as and fa together locally
  apps/financial-aid/api/src/main.ts
  apps/financial-aid/backend/docker-compose.yml
  apps/financial-aid/web-osk/next.config.js
  apps/financial-aid/web-osk/proxy.config.json
Labels: automerge

#6178 feat(fa): In relationship
  libs/application/templates/financial-aid/src/dataProviders/NationalRegistryProvider.ts
  libs/application/templates/financial-aid/src/fields/InRelationship/InRelationship.tsx
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/index.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/application.ts
  libs/application/templates/financial-aid/src/lib/messages/error.ts
  libs/application/templates/financial-aid/src/lib/messages/externalData.ts
  libs/application/templates/financial-aid/src/lib/messages/inRelationship.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/types.ts
  libs/application/templates/financial-aid/src/lib/utils.ts
  libs/application/templates/financial-aid/src/types/index.ts
Labels: automerge

#6193 fix(judicial-system): Fixes to iCal invites
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#6196 chore(codeowners): Simplify aranja teams
  .github/CODEOWNERS
Labels: automerge

#6195 feat(skilavottord): pagination and infinite scroll
  apps/skilavottord/web/screens/RecyclingFund/Overview/Overview.tsx
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
  libs/nest/pagination/src/lib/paginate.ts
Labels: automerge

#6162 feat(judicial-system): End of session bookings
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.spec.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20220103144723-update-case.js
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/rulingStepOne.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/rulingStepTwo.spec.ts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/messages/Core/courtRecordAccordion.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/rulingStepTwo.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/rulingStepTwo.ts
  apps/judicial-system/web/src/components/AccordionItems/CourtRecordAccordionItem/CourtRecordAccordionItem.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepOne/RulingStepOneForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationRequest/Ruling/StepTwo/RulingStepTwoForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepOne/RulingStepOne.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionRequest/Ruling/StepTwo/RulingStepTwo.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/hooks/use-case/useCase.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  libs/judicial-system/formatters/src/lib/formatters.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#6091 fix(web): correcting the look of the back buttons on news article screens
  apps/web/screens/Article.tsx
  apps/web/screens/News.tsx
  libs/island-ui/core/src/lib/Button/Button.css.ts
  libs/island-ui/core/src/lib/Button/Button.tsx
Labels: automerge

#6198 feat(skilavottord): pagination and infinite scroll (#6195)
  apps/skilavottord/web/screens/RecyclingFund/Overview/Overview.tsx
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
  libs/nest/pagination/src/lib/paginate.ts
Labels: automerge

#6197 chore(application-templates-driving-license): instrumenting more logging in the submit application action
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
Labels: automerge

#6184 feat(service-portal): Tablet UI
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/components/Layout/helpers.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.css.ts
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
Labels: automerge

#6199 fix(web): Organization subpage not updating the data regarding Organization page on sync
  libs/cms/src/lib/environments/environment.ts
Labels: automerge

#6188 chore(core): Rename user to auth for dependents of Audit library
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/payment/payment.controller.ts
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/icelandic-names-registry/backend/src/app/modules/icelandic-name/icelandic-name.controller.ts
  apps/services/auth-admin-api/src/app/modules/access/access.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/client-allowed-scope.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/client-claim.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/client-grant-type.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/client-post-logout-redirect-uri.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/client-secret.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/clients.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/cors.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/idp-restriction.controller.ts
  apps/services/auth-admin-api/src/app/modules/clients/redirect-uri.controller.ts
  apps/services/auth-admin-api/src/app/modules/grant-types/grant-types.controller.ts
  apps/services/auth-admin-api/src/app/modules/idp-provider/idp-provider.controller.ts
  apps/services/auth-admin-api/src/app/modules/personal-representative/personal-representative.controller.ts
  apps/services/auth-admin-api/src/app/modules/resources/resources.controller.ts
  apps/services/auth-admin-api/src/app/modules/translation/translation.controller.ts
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.ts
  apps/services/documents/src/app/modules/document-provider/controllers/organisation.controller.ts
  apps/services/documents/src/app/modules/document-provider/controllers/provider.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/services/personal-representative/src/app/modules/personalRepresentatives/personalRepresentatives.controller.ts
  apps/services/personal-representative/src/app/modules/rightTypes/rightTypes.controller.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  libs/api/domains/document-provider/src/lib/document-provider.resolver.ts
  libs/api/domains/documents/src/lib/document.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/education/src/lib/graphql/main.resolver.ts
  libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
  libs/nest/audit/README.md
  libs/nest/audit/src/lib/audit.interceptor.spec.ts
  libs/nest/audit/src/lib/audit.interceptor.ts
  libs/nest/audit/src/lib/audit.service.spec.ts
  libs/nest/audit/src/lib/audit.service.ts
Labels: automerge

#6207 fix(judicial-system): Fix iCal end time
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#6206 chore(application-templates-driving-license): instrumenting more logging in the DL application
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
Labels: automerge

#6205 feat(sakavottord): Update xroad path for prod
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#6194 feat(fa): Home circumstances added to application
  libs/application/templates/financial-aid/src/fields/HomeCircumstancesForm/HomeCircumstancesForm.tsx
  libs/application/templates/financial-aid/src/fields/InRelationshipForm/InRelationshipForm.tsx
  libs/application/templates/financial-aid/src/fields/Shared.css.ts
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/error.ts
  libs/application/templates/financial-aid/src/lib/messages/homeCircumstancesForm.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/types.ts
Labels: automerge

#6201 chore(judicial-system): Use Sækjandi instead of Ákærandi in SMS notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
Labels: automerge

#6203 chore(core): update package react-number-format
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
  package.json
  yarn.lock
Labels: automerge

#6216 feat(fa): Prereq
  libs/application/templates/financial-aid/src/fields/AboutForm/AboutForm.tsx
  libs/application/templates/financial-aid/src/fields/InRelationshipForm/InRelationshipForm.tsx
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/forms/Prerequisites.ts
  libs/application/templates/financial-aid/src/index.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/application-templates-financial-aid.spec.tsx
  libs/application/templates/financial-aid/src/lib/application-templates-financial-aid.tsx
  libs/application/templates/financial-aid/src/lib/constants.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/aboutForm.ts
Labels: automerge

#6167 feat(core): simplify swagger documentation
  .github/CODEOWNERS
  SUMMARY.md
  apps/services/auth-public-api/src/app/modules/delegations/meDelegations.controller.ts
  jest.config.js
  libs/nest/swagger/.eslintrc.json
  libs/nest/swagger/README.md
  libs/nest/swagger/jest.config.js
  libs/nest/swagger/src/index.ts
  libs/nest/swagger/src/lib/documentation.decorator.spec.ts
  libs/nest/swagger/src/lib/documentation.decorator.ts
  libs/nest/swagger/tsconfig.json
  libs/nest/swagger/tsconfig.lib.json
  libs/nest/swagger/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#6204 feat(fa): Student form added to application
  libs/application/templates/financial-aid/src/fields/StudentForm/StudentForm.tsx
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/messages/studentForm.ts
  libs/application/templates/financial-aid/src/lib/types.ts
Labels: automerge

#6208 fix(web): Fixing typo for dd rum
  apps/web/layouts/main.tsx
Labels: automerge

#6219 refactor(application-templates-driving-license): address & type fixes in email generator
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.ts
Labels: automerge

#6210 chore(application-templates-driving-license): removing unused strings
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#6222 fix(skilavottord): add missing offline_access scope
  apps/skilavottord/web/pages/api/auth/[...nextauth].ts
Labels: automerge

#6226 fix(skilavottord): add offline access scope
  apps/skilavottord/web/pages/api/auth/[...nextauth].ts
Labels: automerge

#6224 fix(judicial-system): Fix form stepper navigation
  apps/judicial-system/web/src/components/PageLayout/utils/index.ts
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/sections.ts
Labels: automerge

#6228 feat(fa): Income form added to application
  libs/application/templates/financial-aid/src/fields/AboutForm/AboutForm.tsx
  libs/application/templates/financial-aid/src/fields/DescriptionText/DescriptionText.tsx
  libs/application/templates/financial-aid/src/fields/IncomeForm/IncomeForm.tsx
  libs/application/templates/financial-aid/src/fields/Shared.css.ts
  libs/application/templates/financial-aid/src/fields/StudentForm/StudentForm.tsx
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/aboutForm.ts
  libs/application/templates/financial-aid/src/lib/messages/application.ts
  libs/application/templates/financial-aid/src/lib/messages/incomeForm.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/messages/studentForm.ts
Labels: automerge

#6233 fix: general petition template access
  libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/service-portal/endorsements/src/lib/messages.ts
  libs/service-portal/endorsements/src/screens/ViewPetitionAdmin/ViewPetitionAdmin.tsx
Labels: automerge

#6229 feat(fa): Personal tax credit form added to application
  libs/application/templates/financial-aid/src/fields/PersonalTaxCreditForm/PersonalTaxCreditForm.tsx
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/messages/personalTaxCreditForm.ts
Labels: automerge

#6243 chore(web): add breadcrumb tag link back to news overview
  apps/web/screens/Organization/NewsItem.tsx
Labels: automerge

#6242 feat(sakavottord): Update ready for production flag
  libs/application/templates/criminal-record/src/lib/CriminalRecordTemplate.ts
Labels: automerge

#6244 feat(web): Syslumenn auctions, show respondents and petitioners for ships and real estate
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/queries/Organization.tsx
  libs/api/domains/syslumenn/src/lib/models/syslumennAuction.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#6240 feat(service-portal): National registry children
  libs/api/domains/national-registry/src/lib/graphql/child.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/index.ts
  libs/api/domains/national-registry/src/lib/graphql/models/child.model.ts
  libs/api/domains/national-registry/src/lib/graphql/models/index.ts
  libs/api/domains/national-registry/src/lib/graphql/models/user.model.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/types/child.type.ts
  libs/api/domains/national-registry/src/lib/types/index.ts
  libs/api/domains/national-registry/src/lib/types/user.type.ts
  libs/clients/national-registry/v1/src/lib/dto/getViewISLBorninMin.dto.ts
  libs/clients/national-registry/v1/src/lib/dto/index.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/family/src/index.ts
  libs/service-portal/family/src/screens/FamilyMember/FamilyMember.tsx
  libs/service-portal/family/src/screens/Spouse/Spouse.tsx
  libs/service-portal/family/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge, deploy-feature

#6230 feat(service-portal): New design fixes - 2
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  apps/service-portal/src/components/Sidebar/NavItem/SubNav.tsx
  libs/service-portal/core/src/screens/ErrorScreen/ErrorScreen.css.ts
  libs/service-portal/core/src/screens/ErrorScreen/ErrorScreen.tsx
  libs/shared/components/src/auth/UserMenu/UserButton.tsx
  libs/shared/components/src/auth/UserMenu/UserLanguageSwitcher.tsx
Labels: automerge

#6251 feat(web): Hotfix - Syslumenn auctions, show respondents and petitioners for ships and real estate
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/queries/Organization.tsx
  libs/api/domains/syslumenn/src/lib/models/syslumennAuction.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#6253 fix(skilavottord): show vehicle list for recycling partners
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/ws/src/app/graphql/connection.ts
  apps/skilavottord/ws/src/app/graphql/index.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/index.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.service.ts
Labels: automerge

#6254 fix(skilavottord): fix role check for fetching vehicles
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/ws/src/app/graphql/connection.ts
  apps/skilavottord/ws/src/app/graphql/index.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/index.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.service.ts
Labels: automerge

#6234 refactor(api-domains-driving-license): better error handling for invalid licenses and fixing graphql types
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/application/templates/driving-license/src/dataProviders/CurrentLicenseProvider.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
Labels: automerge

#6173 chore(web): tweak headings
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
  apps/web/components/SearchSection/SearchSection.tsx
  apps/web/components/SimpleSlider/SimpleSlider.tsx
  apps/web/screens/Organization/SubPage.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
  libs/island-ui/core/src/lib/NewsletterSignup/NewsletterSignup.tsx
Labels: automerge

#6255 fix(service-portal): empty mychildren response
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
Labels: automerge

#6252 feat(service-portal): National registry children - hotfix
  libs/api/domains/national-registry/src/lib/graphql/child.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/index.ts
  libs/api/domains/national-registry/src/lib/graphql/models/child.model.ts
  libs/api/domains/national-registry/src/lib/graphql/models/index.ts
  libs/api/domains/national-registry/src/lib/graphql/models/user.model.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/types/child.type.ts
  libs/api/domains/national-registry/src/lib/types/index.ts
  libs/api/domains/national-registry/src/lib/types/user.type.ts
  libs/clients/national-registry/v1/src/lib/dto/getViewISLBorninMin.dto.ts
  libs/clients/national-registry/v1/src/lib/dto/index.ts
  libs/clients/national-registry/v1/src/lib/nationalRegistryApi.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/family/src/index.ts
  libs/service-portal/family/src/screens/FamilyMember/FamilyMember.tsx
  libs/service-portal/family/src/screens/Spouse/Spouse.tsx
  libs/service-portal/family/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge

#6236 feat(fa): Bank information added to application
  libs/application/templates/financial-aid/src/fields/BankInfoForm/BankInfoForm.tsx
  libs/application/templates/financial-aid/src/fields/Shared.css.ts
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/Application.ts
  libs/application/templates/financial-aid/src/lib/dataSchema.ts
  libs/application/templates/financial-aid/src/lib/messages/bankInfoForm.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
Labels: automerge

#6259 fix(service-portal): change real estate asset text
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
Labels: automerge

#6238 fix(application-templates-driving-license): fixing applicationFor check when filled
  libs/application/templates/driving-license/src/lib/utils/formUtils.spec.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
Labels: automerge

#5861 fix(service-portal): remove finance from feature flagged modules
  apps/service-portal/src/store/modules.ts
Labels: automerge

#6239 refactor(application-templates-driving-license): splitting the draft state into separate files
  libs/application/templates/driving-license/src/forms/application.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/index.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionOtherCountry.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionOtherCountryDirections.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#6214 feat(data-protection-complaint): Go pro application submit
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/attachment-s3.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/providers/applicationAttachmentProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/providers/pdfFileProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/mappers/complaintCategoryMapper.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/attachments.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/complaint.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/models/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfGenerator.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfUtils.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/templates/data-protection-complaint/src/index.ts
  libs/application/templates/data-protection-complaint/src/shared/index.ts
  libs/application/templates/data-protection-complaint/src/shared/mappers.ts
Labels: automerge, deploy-feature

#6237 feat(nest/audit): Support token exchange client chain in audit logs
  libs/auth-nest-tools/src/lib/auth.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/nest/audit/src/lib/audit.service.spec.ts
  libs/nest/audit/src/lib/audit.service.ts
Labels: automerge

#6265 fix(web): no longer allow submitting empty search terms
  apps/web/components/SearchInput/SearchInput.tsx
Labels: automerge

#6263 fix(service-portal): Sidebar nav item animation fixes
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
Labels: automerge

#6213 chore(web/island-ui): organization/service-list changes
  apps/web/components/ServiceList/ServiceList.tsx
  apps/web/screens/ApiCatalogue/ApiCatalogue.tsx
  apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
  apps/web/screens/Organizations/Organiziations.tsx
  apps/web/screens/queries/Organization.tsx
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.css.ts
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx
  libs/island-ui/core/src/lib/Tag/Tag.css.ts
  libs/island-ui/core/src/lib/Tag/Tag.tsx
Labels: automerge

#6241 fix(service-portal): Unread document badge bug
  apps/service-portal/src/app/App.tsx
  apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
  libs/service-portal/core/src/contexts/BadgeContext.tsx
  libs/service-portal/core/src/hooks/useUpdateUnreadDocuments/useUpdateUnreadDocuments.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/mockData.ts
  libs/service-portal/graphql/src/hooks/documents/useListDocuments.ts
  libs/service-portal/graphql/src/hooks/documents/useUnreadDocumentsCounter.ts
  libs/service-portal/graphql/src/index.ts
Labels: automerge, deploy-feature

#6267 fix(island-ui): utility button with icon size
  libs/island-ui/core/src/lib/Button/Button.css.ts
Labels: automerge

#6115 feat(web): Project subpage tab support
  apps/web/screens/Project/Project.tsx
  apps/web/screens/queries/Project.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/models/projectSubpage.model.ts
  libs/island-ui/core/src/lib/TableOfContents/TableOfContents.tsx
Labels: automerge, deploy-feature

#6246 fix(ci): Adding Origo to codeowners for sakavottord code
  .github/CODEOWNERS
Labels: automerge

#6268 fix(general-petitions): updating scheme for correct dates validation
  libs/application/template-api-modules/src/lib/modules/templates/general-petition/general-petition.service.ts
  libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx
  libs/application/templates/general-petition/src/fields/Overview/index.tsx
  libs/application/templates/general-petition/src/forms/ApplicationForm.ts
  libs/application/templates/general-petition/src/lib/dataSchema.ts
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.spec.ts
  libs/application/templates/general-petition/src/lib/generalPetitionApplicationTemplate.ts
  libs/application/templates/general-petition/src/lib/messages.ts
Labels: automerge

#6218 feat(service-portal): Update numbered inputs and buttons
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#6269 ci: Cache action success
  .github/actions/cache/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#6249 feat(web): Changed Sjukratryggingar header and added support for new header color scheme
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/layouts/main.tsx
  apps/web/screens/Organization/Home.tsx
  apps/web/screens/Organization/NewsItem.tsx
  apps/web/screens/Organization/NewsList.tsx
  apps/web/screens/Organization/Services.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Project/Project.tsx
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.css.ts
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
  libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.css.ts
  libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.tsx
  libs/island-ui/core/src/lib/Button/Button.css.ts
  libs/island-ui/core/src/lib/FocusableBox/FocusableBox.css.ts
  libs/island-ui/core/src/lib/context/ColorSchemeContext/ColorSchemeContext.ts
Labels: automerge

#6275 chore(data-protection-complaint): add configs and xroad values
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#6279 fix(web): updated mint tag
  libs/island-ui/core/src/lib/Tag/Tag.css.ts
  libs/island-ui/core/src/lib/Tag/Tag.tsx
  libs/island-ui/theme/src/lib/colors.ts
Labels: automerge

#6282 ci: Bump cache action version to handle 404
  .github/actions/cache/action.yml
Labels: automerge

#6090 feat(user-notification): worker logic to send push notifications
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/e2e/notifications.spec.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
  apps/services/user-notification/src/app/modules/notifications/types.ts
  apps/services/user-notification/src/app/modules/notifications/utils.ts
  apps/services/user-notification/src/buildOpenApi.ts
  apps/services/user-notification/src/constants.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-notification/src/messages.ts
  apps/services/user-notification/test/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  package.json
  workspace.json
  yarn.lock
Labels: automerge

#6212 feat(quality-photo): Provides if photo exists, components queries on demand
  libs/api/domains/driving-license/src/lib/drivingLicense.module.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/index.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/qualityPhoto.model.ts
  libs/api/domains/driving-license/src/lib/graphql/qualityPhoto.resolver.ts
  libs/application/data-providers/src/providers/QualityPhotoProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/templates/driving-license/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/driving-license/src/fields/QualityPhoto/hooks/queries.graphql.ts
  libs/application/templates/driving-license/src/fields/QualityPhoto/hooks/useQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/application/templates/p-sign/src/dataProviders/DoctorsNoteProvider.ts
  libs/application/templates/p-sign/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/p-sign/src/fields/QualityPhoto/hooks/queries.graphql.ts
  libs/application/templates/p-sign/src/fields/QualityPhoto/hooks/useQualityPhoto.ts
  libs/application/templates/p-sign/src/forms/application.ts
Labels: automerge

#6284 chore(judicial-system): Stops masking national id and name in investigation cases
  apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.mask.ts
Labels: automerge

#6285 fix(web): forgot to update Tag stories
  libs/island-ui/core/src/lib/Tag/Tag.css.ts
  libs/island-ui/core/src/lib/Tag/Tag.stories.tsx
Labels: automerge

#6277 fix(config): Support feature deployments network access to islandis namespace
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/cli/render-env.ts
  infra/src/dsl/serialize-to-yaml.ts
  infra/src/feature-env.ts
Labels: automerge

#6286 feat(web): service web changes
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  apps/web/screens/queries/ServiceWeb.ts
  apps/web/utils/sortAlpha.ts
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/supportCategory.model.ts
Labels: automerge

#6266 feat(plausible): Search Query analytics
  apps/web/hooks/usePlausible.ts
  apps/web/screens/Search/Search.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
Labels: automerge

#6060 fix(parental-leave): Be able to edit application when waiting for other parent approval
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#6287 fix(hi): Fix issue when no date was defined in ishealthinsured call
  libs/api/domains/health-insurance/src/lib/graphql/dto/getIsHealthInsuredInput.ts
  libs/api/domains/health-insurance/src/lib/graphql/healthInsurance.resolver.ts
Labels: automerge

#5034 feat(rsk): Implement rsk company info search and company info
  .github/CODEOWNERS
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  jest.config.js
  libs/api/domains/company-registry/.eslintrc
  libs/api/domains/company-registry/README.md
  libs/api/domains/company-registry/jest.config.js
  libs/api/domains/company-registry/src/index.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.module.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.resolver.ts
  libs/api/domains/company-registry/src/lib/dto/RskCompanyInfo.input.ts
  libs/api/domains/company-registry/src/lib/dto/RskCompanyInfoSearch.input.ts
  libs/api/domains/company-registry/src/lib/models/currentUserCompanies.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompany.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyAddress.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyClassification.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyFormOfOperation.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyLink.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyRelatedParty.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanySearchItems.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyVat.model.ts
  libs/api/domains/company-registry/src/lib/rsk-company-info.service.ts
  libs/api/domains/company-registry/src/lib/rsk-company-info.utils.ts
  libs/api/domains/company-registry/tsconfig.json
  libs/api/domains/company-registry/tsconfig.lib.json
  libs/api/domains/company-registry/tsconfig.spec.json
  libs/api/domains/rsk/.eslintrc
  libs/api/domains/rsk/src/index.ts
  libs/api/domains/rsk/src/lib/api-domains-rsk.module.ts
  libs/api/domains/rsk/src/lib/api-domains-rsk.resolver.ts
  libs/clients/rsk/company-registry/.eslintrc.json
  libs/clients/rsk/company-registry/README.md
  libs/clients/rsk/company-registry/jest.config.js
  libs/clients/rsk/company-registry/src/index.ts
  libs/clients/rsk/company-registry/src/lib/company-registry.module.ts
  libs/clients/rsk/company-registry/src/lib/types/index.ts
  libs/clients/rsk/company-registry/src/lib/types/service-options.type.ts
  libs/clients/rsk/company-registry/src/openapi.yml
  libs/clients/rsk/company-registry/tsconfig.json
  libs/clients/rsk/company-registry/tsconfig.lib.json
  libs/clients/rsk/company-registry/tsconfig.spec.json
  libs/clients/rsk/v1/src/lib/rsk.ts
  libs/nest/pagination/src/lib/dto/pageinfo.dto.ts
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#6123 feat(island-ui): add avatar + refactoring on action card
  libs/island-ui/core/src/lib/ActionCard/ActionCard.css.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#5978 fix(island-ui): a11y inputs
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#6288 fix(plausible): Normalize queries with lowercase
  apps/web/screens/Search/Search.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
Labels: automerge

#6290 chore(user-notification): add firebase-admin to esbuild externals
  apps/services/user-notification/esbuild.json
Labels: automerge

#6291 chore(user-notification): add firebase-admin to esbuild externals
  apps/services/user-notification/esbuild.json
Labels: automerge

#6292 feat(documentation): allows setting summary
  libs/nest/swagger/src/lib/documentation.decorator.spec.ts
  libs/nest/swagger/src/lib/documentation.decorator.ts
Labels: automerge

#6293 fix(service-portal): remove assets from feature flagged modules
  apps/service-portal/src/store/modules.ts
Labels: automerge

#6271 feat(as): Connect to Veita
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/environments/environment.ts
  libs/api/domains/municipalities-financial-aid/.eslintrc
  libs/api/domains/municipalities-financial-aid/README.md
  libs/api/domains/municipalities-financial-aid/jest.config.js
  libs/api/domains/municipalities-financial-aid/src/index.ts
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.module.ts
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.resolver.ts
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.service.ts
  libs/api/domains/municipalities-financial-aid/tsconfig.json
  libs/api/domains/municipalities-financial-aid/tsconfig.lib.json
  libs/api/domains/municipalities-financial-aid/tsconfig.spec.json
  libs/application/templates/financial-aid/src/dataProviders/VeitaProvider.ts
  libs/application/templates/financial-aid/src/dataProviders/index.ts
  libs/application/templates/financial-aid/src/forms/Prerequisites.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/types.ts
  libs/clients/municipalities-financial-aid/.eslintrc.json
  libs/clients/municipalities-financial-aid/README.md
  libs/clients/municipalities-financial-aid/jest.config.js
  libs/clients/municipalities-financial-aid/src/applicationApiProvider.ts
  libs/clients/municipalities-financial-aid/src/index.ts
  libs/clients/municipalities-financial-aid/src/municipalitiesFinancialAid.config.ts
  libs/clients/municipalities-financial-aid/tsconfig.json
  libs/clients/municipalities-financial-aid/tsconfig.lib.json
  libs/clients/municipalities-financial-aid/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge
