Repository island-is/island.is, pull requests merged in 2022-04, with the labels that each got.

#7030 feat(fa): Allow all roles to have multiple municipalities
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/LogoMunicipality/Logo.css.ts
  apps/financial-aid/web-veita/src/components/LogoMunicipality/index.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/Nav/Nav.css.ts
  apps/financial-aid/web-veita/src/components/Nav/Nav.tsx
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/routes/Application/application.tsx
  apps/financial-aid/web-veita/src/routes/MunicipalitySettings/municipalitySettings.tsx
  libs/financial-aid/shared/src/components/Breakdown/Breakdown.tsx
  libs/financial-aid/shared/src/components/hooks/useMunicipality.ts
Labels: automerge

#7020 fix(judicial-system): remove web permission check in court
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#7043 fix(p-sign): Schema fixes in P-Sign
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/templates/p-sign/src/fields/UploadedPhoto/index.tsx
  libs/application/templates/p-sign/src/forms/application.ts
  libs/application/templates/p-sign/src/lib/constants.ts
  libs/application/templates/p-sign/src/lib/dataSchema.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  libs/application/templates/p-sign/src/types.ts
Labels: automerge

#7049 feat(personal-rep-ids-admin): Add permission type to scope connector
  apps/auth-admin-web/components/Resource/forms/ApiScopePersonalRepresentativePermissionsForm.tsx
  apps/auth-admin-web/entities/models/personal-representative-scope-permission.model.ts
  apps/auth-admin-web/styles/_FormLayout.scss
  libs/auth-api-lib/src/lib/personal-representative/services/personal-representative-scope-permission.service.ts
Labels: automerge

#7048 fix(fa): Revert allow all roles to have multiple municipalities
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/LogoMunicipality/Logo.css.ts
  apps/financial-aid/web-veita/src/components/LogoMunicipality/index.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/Nav/Nav.css.ts
  apps/financial-aid/web-veita/src/components/Nav/Nav.tsx
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/routes/Application/application.tsx
  apps/financial-aid/web-veita/src/routes/MunicipalitySettings/municipalitySettings.tsx
  libs/financial-aid/shared/src/components/Breakdown/Breakdown.tsx
  libs/financial-aid/shared/src/components/hooks/useMunicipality.ts
Labels: automerge

#7046 fix(fa): Status page aid amount calculation
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx
Labels: automerge

#7017 feat(Application-system): Feature flag for applications
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  apps/application-system/api/src/app/modules/application/e2e/applicationTemplateValidation.spec.ts
  apps/application-system/api/src/app/modules/application/e2e/mockFeatureFlagService.ts
  apps/application-system/api/src/app/modules/application/lifecycle/test/application-lifecycle-integration.spec.ts
  apps/application-system/api/src/app/modules/application/tools/applicationTemplateValidation.service.ts
  apps/application-system/api/src/app/modules/application/utils/validationUtils.spec.ts
  apps/application-system/api/src/app/modules/application/utils/validationUtils.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/application/core/src/types/ApplicationTemplate.ts
  libs/application/templates/accident-notification/babel-jest.config.json
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/feature-flags/src/lib/features.ts
  libs/nest/feature-flags/src/lib/feature-flag.service.ts
  libs/testing/fixtures/src/lib/application.ts
  package.json
  yarn.lock
Labels: automerge

#7057 fix(download-service): increase available resources
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#6767 feat(service-portal): finance schedule new module
  apps/service-portal/src/store/modules.ts
  jest.config.js
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/finance/src/lib/dto/getFinancePaymentSchedule.input.ts
  libs/api/domains/finance/src/lib/dto/getPaymentSchedule.input.ts
  libs/api/domains/finance/src/lib/models/debtStatus.model.ts
  libs/api/domains/finance/src/lib/models/paymentSchedule.model.ts
  libs/clients/finance/src/lib/FinanceClientService.ts
  libs/clients/finance/src/lib/types.ts
  libs/service-portal/core/src/components/ExpandableTable/ExpandableTable.css.ts
  libs/service-portal/core/src/components/ExpandableTable/Header.tsx
  libs/service-portal/core/src/components/ExpandableTable/Row.tsx
  libs/service-portal/core/src/components/ExpandableTable/index.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/core/src/screens/ErrorScreen/ErrorScreen.css.ts
  libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
  libs/service-portal/core/src/utils/amountFormat.ts
  libs/service-portal/core/src/utils/dateUtils.ts
  libs/service-portal/core/src/utils/documentFormSubmission.ts
  libs/service-portal/core/src/utils/utils.ts
  libs/service-portal/finance-schedule/.babelrc
  libs/service-portal/finance-schedule/.eslintrc.json
  libs/service-portal/finance-schedule/README.md
  libs/service-portal/finance-schedule/babel-jest.config.json
  libs/service-portal/finance-schedule/jest.config.js
  libs/service-portal/finance-schedule/src/components/FinanceScheduleDetailTable/FinanceScheduleDetailTable.css.ts
  libs/service-portal/finance-schedule/src/components/FinanceScheduleDetailTable/FinanceScheduleDetailTable.tsx
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTable.css.ts
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTable.tsx
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTableRow.tsx
  libs/service-portal/finance-schedule/src/index.ts
  libs/service-portal/finance-schedule/src/lib/service-portal-finance-schedule.spec.tsx
  libs/service-portal/finance-schedule/src/lib/service-portal-finance-schedule.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.types.ts
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/index.ts
  libs/service-portal/finance-schedule/tsconfig.json
  libs/service-portal/finance-schedule/tsconfig.lib.json
  libs/service-portal/finance-schedule/tsconfig.spec.json
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceDebtStatus/FinanceDebtStatus.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/finance/src/components/FinanceTransactionsTable/FinanceTransactionsTable.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge, deploy-feature

#7024 feat(web): Organization page default theme header
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/DefaultHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/DefaultHeader.tsx
  apps/web/components/Project/Header/DefaultProjectHeader.css.ts
  apps/web/components/Project/Header/DefaultProjectHeader.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/models/organizationTheme.model.ts
Labels: automerge, deploy-feature

#7063 fix(fa): Salary breakdown in direct payments and minor fixes
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/personalTaxReturn.service.ts
  apps/financial-aid/web-osk/src/components/Status/Rejected.tsx
  apps/financial-aid/web-osk/src/routes/application/DataGathering/dataGathering.tsx
  libs/clients/rsk/personal-tax-return/src/lib/personalTaxReturnApi.service.ts
  libs/clients/rsk/personal-tax-return/src/lib/responses/directTaxPayment.response.ts
  libs/clients/rsk/personal-tax-return/src/lib/transformers/transformers.ts
Labels: automerge

#7064 fix(application-system-api): Marking configcat-node as external in esbuild.json
  apps/application-system/api/esbuild.json
Labels: automerge

#7053 feat(web): Added a chat panel related to Ukraine to a specific project page
  apps/web/components/UkraineChatPanel/UkraineChatPanel.tsx
  apps/web/components/real.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Project/Project.tsx
Labels: automerge

#7051 fix(core): Fix renewal time check in next-ids-auth
  libs/next-ids-auth/src/lib/utils.ts
Labels: automerge

#6802 feat(service-portal): add driving license url when on mobile
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.tsx
  libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx
  libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.css.ts
  libs/service-portal/licenses/src/components/QRCodeModal/QRCodeModal.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
Labels: automerge, deploy-feature

#7069 fix(ads): doubling available resources for air-discount-scheme
  apps/air-discount-scheme/backend/infra/backend.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#7054 feat(ids): Add more claim integrations to auth-api, integrate company-registry in identity domain
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  apps/services/auth-api/src/app/app.module.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.module.ts
  apps/services/auth-api/test/setup.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  jest.config.js
  libs/api/domains/company-registry/src/index.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.module.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.resolver.ts
  libs/api/domains/company-registry/src/lib/models/currentUserCompanies.model.ts
  libs/api/domains/identity/src/lib/identity.module.ts
  libs/api/domains/identity/src/lib/identity.service.ts
  libs/api/domains/identity/src/lib/models/address.model.ts
  libs/api/mocks/src/domains/applications/resolvers.ts
  libs/api/mocks/src/domains/applications/store.ts
  libs/application/templates/driving-instructor-registrations/README.md
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/entities/dto/address.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/individual-info.dto.ts
  libs/auth-api-lib/src/lib/entities/dto/user-profile.dto.ts
  libs/auth-api-lib/src/lib/services/user-profile.service.ts
  libs/clients/rsk/v1/.eslintrc
  libs/clients/rsk/v1/README.md
  libs/clients/rsk/v1/jest.config.js
  libs/clients/rsk/v1/src/index.ts
  libs/clients/rsk/v1/src/lib/rsk.spec.ts
  libs/clients/rsk/v1/src/lib/rsk.ts
  libs/clients/rsk/v1/tsconfig.json
  libs/clients/rsk/v1/tsconfig.lib.json
  libs/clients/rsk/v1/tsconfig.spec.json
  libs/nest/swagger/src/lib/documentation.decorator.spec.ts
  libs/nest/swagger/src/lib/documentation.decorator.ts
  libs/testing/fixtures/src/lib/currentUser.ts
  libs/testing/fixtures/src/lib/nationalId.ts
  libs/testing/fixtures/src/lib/nationalRegistryUser.ts
  nx.json
  scripts/gitbook.js
  tsconfig.base.json
  workspace.json
Labels: automerge

#7055 refactor(j-s): Request file name improvements
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7052 fix(service-portal): Add case where 6 mo old accounts can drop modal
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/settings/personal-information/src/utils/showModal.ts
Labels: automerge, deploy-feature

#6950 docs(auth): Add IAS technical documentation to handbook
  SUMMARY.md
  handbook/technical-overview/auth/README.md
  handbook/technical-overview/auth/assets/absolute_expiration.png
  handbook/technical-overview/auth/assets/authorising_apis.jpg
  handbook/technical-overview/auth/assets/authorization_code.jpg
  handbook/technical-overview/auth/assets/client_credentials.jpg
  handbook/technical-overview/auth/assets/delegation_token.png
  handbook/technical-overview/auth/assets/example-test-auth.postman_collection.json
  handbook/technical-overview/auth/assets/inactive_expiration.png
  handbook/technical-overview/auth/assets/refresh_token.png
  handbook/technical-overview/auth/assets/refresh_token_leak.png
  handbook/technical-overview/auth/assets/session_lifecycle.png
  handbook/technical-overview/auth/assets/step1_click_collection.png
  handbook/technical-overview/auth/assets/step2_fill_in_variables.png
  handbook/technical-overview/auth/assets/step3_get_new_access_token.png
  handbook/technical-overview/auth/assets/step4_authenticate.png
  handbook/technical-overview/auth/assets/step5_receive_token.png
  handbook/technical-overview/auth/assets/ts_invalid_client_id.png
  handbook/technical-overview/auth/assets/ts_invalid_client_secret.png
  handbook/technical-overview/auth/assets/ts_invalid_redirect_uri.png
  handbook/technical-overview/auth/assets/ts_invalid_scope.png
  handbook/technical-overview/auth/authentication-flows.md
  handbook/technical-overview/auth/authorising-apis.md
  handbook/technical-overview/auth/configuration.md
  handbook/technical-overview/auth/delegations.md
  handbook/technical-overview/auth/environments.md
  handbook/technical-overview/auth/integration-guidance.md
  handbook/technical-overview/auth/integration-options.md
  handbook/technical-overview/auth/postman-test.md
  handbook/technical-overview/auth/scopes-and-tokens.md
  handbook/technical-overview/auth/service-provider-manual/README.md
  handbook/technical-overview/auth/service-provider-manual/assets/authentication-service-provision-1.png
  handbook/technical-overview/auth/service-provider-manual/assets/authentication-service-provision-2.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-1.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-2.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-3.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-4.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-5.png
  handbook/technical-overview/auth/service-provider-manual/assets/trouble-shooting-6.png
  handbook/technical-overview/auth/service-provider-manual/authentication-service-provision.md
  handbook/technical-overview/auth/service-provider-manual/incidents.md
  handbook/technical-overview/auth/service-provider-manual/intervention-by-code-change.md
  handbook/technical-overview/auth/service-provider-manual/trouble-shooting.md
  handbook/technical-overview/auth/session-lifecycle.md
  handbook/technical-overview/auth/system-manual/README.md
  handbook/technical-overview/auth/system-manual/assets/introduction.png
  handbook/technical-overview/auth/system-manual/assets/service-provider-role.png
  handbook/technical-overview/auth/system-manual/service-provider-role.md
  handbook/technical-overview/auth/terminology.md
  handbook/technical-overview/auth/third-party-manual/README.md
Labels: automerge

#7029 fix(application-system): Store a nonce token for assignments
  apps/application-system/api/migrations/20220329161604-add-assignNonce.js
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  apps/application-system/api/src/app/modules/application/template-api.service.ts
  apps/application-system/api/src/app/modules/application/types/index.ts
  libs/application/api/core/src/lib/application/application.model.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.utils.ts
  libs/application/template-api-modules/src/lib/types/index.ts
Labels: automerge

#7045 refactor(auth-react): CheckIdpSession refactor
  libs/auth/react/src/lib/Authenticator/CheckIdpSession.tsx
Labels: automerge

#7044 feat(judicial-system): Archive Old Cases
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/api/src/environments/environment.ts
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/migrations/20220329172535-update-case.js
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/factories/date.factory.ts
  apps/judicial-system/backend/src/app/factories/index.ts
  apps/judicial-system/backend/src/app/factories/uuid.factory.ts
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.config.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/caseExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/models/archive.response.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseArchive.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/archiveGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/case/test/extend.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCreate.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/index.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/scheduler/infra/judicial-system-scheduler.ts
  apps/judicial-system/scheduler/src/app/app.config.ts
  apps/judicial-system/scheduler/src/app/app.module.ts
  apps/judicial-system/scheduler/src/app/app.service.ts
  apps/judicial-system/scheduler/src/app/date.factory.ts
  apps/judicial-system/scheduler/src/app/test/run.spec.ts
  apps/judicial-system/scheduler/src/environments/environment.ts
  apps/judicial-system/scheduler/src/environments/index.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/utils/hooks/useLawyers/useLawyers.ts
  apps/judicial-system/xrd-api/infra/judicial-system-xrd-api.ts
  apps/judicial-system/xrd-api/src/environments/environment.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#7074 fix(fa): Adding prop to direct tax payment response
  apps/financial-aid/api/src/app/modules/personalTaxReturn/models/directTaxPayments.response.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/models/directTaxPayments.response.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/personalTaxReturn.service.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/test/municipalitiesDirectTaxPayments.spec.ts
  apps/financial-aid/web-osk-e2e/src/fixtures/gatherTaxDataQuery.json
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx
  apps/financial-aid/web-osk/src/components/PrivacyPolicyAccordion/PrivacyPolicyAccordion.tsx
  apps/financial-aid/web-osk/src/components/Summary/DirectTaxPaymentCell.tsx
  apps/financial-aid/web-osk/src/routes/application/SummaryForm/summaryForm.tsx
  apps/financial-aid/web-osk/src/routes/application/TaxReturnForm/taxFormContent.tsx
  apps/financial-aid/web-osk/src/routes/application/TaxReturnForm/taxReturnForm.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useNavigationTree.ts
  apps/financial-aid/web-osk/src/utils/hooks/useTaxData.ts
Labels: automerge

#7082 fix(service-portal-api): open access from IDS namespace
  apps/services/user-profile/infra/service-portal-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#7084 fix(ci): change detector to use create events as a fallback when push ones are not present
  .github/actions/ci-io.ts
  .github/actions/dist/index.js
Labels: automerge

#7085 feat(fa): Adding boolean on if payments were fetched
  apps/financial-aid/api/src/app/modules/application/dto/createApplication.input.ts
  apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts
  apps/financial-aid/api/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/migrations/20220405154052-update-applications-has-fetched-spouse-and-applicatant-direct-tax.js
  apps/financial-aid/backend/src/app/modules/application/dto/createApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/dto/updateApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/createEvent.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/getById.spec.ts
  apps/financial-aid/web-osk/src/components/AppLayout/AppLayout.tsx
  apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx
  apps/financial-aid/web-osk/src/components/Summary/DirectTaxPaymentCell.tsx
  apps/financial-aid/web-osk/src/routes/application/SummaryForm/spouseSummary.tsx
  apps/financial-aid/web-osk/src/routes/application/SummaryForm/summaryForm.tsx
  apps/financial-aid/web-osk/src/routes/application/TaxReturnForm/taxReturnForm.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useApplication.ts
  apps/financial-aid/web-osk/src/utils/hooks/useNavigationTree.ts
  apps/financial-aid/web-osk/src/utils/hooks/useTaxData.ts
  apps/financial-aid/web-osk/src/utils/hooks/useUpdateApplication.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7086 fix(fa): Add text to rejected email
  libs/financial-aid/shared/src/lib/formatters.ts
Labels: automerge

#7061 fix(ci): Adding run attempt to the e2e id to allow for re-runs
  .github/workflows/pullrequest.yml
Labels: automerge

#7093 fix(fa): Fixing minor spelling in veita
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
Labels: automerge

#7096 feat(web): Project page featured description
  apps/web/components/Project/Header/DefaultProjectHeader.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#7092 fix(fa): Make sure tax allowance is not higher then tax amount
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#7088 feat(infra): NestJS interceptor for DataDog APM
  libs/infra-nest-server/src/lib/infra/apm.interceptor.ts
  libs/infra-nest-server/src/lib/infra/infra.module.ts
Labels: automerge

#7081 fix(auth-api): Handle integration errors better
  .github/CODEOWNERS
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.ts
  apps/services/auth-api/test/setup.ts
  libs/auth-api-lib/src/lib/entities/dto/user-profile.dto.ts
  libs/auth-api-lib/src/lib/services/user-profile.service.ts
  libs/clients/national-registry/v2/src/index.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.module.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
  libs/clients/national-registry/v2/src/lib/types/address.dto.ts
  libs/clients/national-registry/v2/src/lib/types/individual.dto.ts
Labels: automerge

#7099 fix(j-s): add missing required env
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#7097 fix(fa): Allow longer text on comments
  apps/financial-aid/backend/migrations/20220406124843-update-applications-comments.js
  apps/financial-aid/backend/src/app/modules/application/models/application.model.ts
Labels: automerge

#7101 fix(fa): Fix attachments placement when printing application
  apps/financial-aid/web-veita/src/routes/PrintableApplication/printableApplication.tsx
  apps/financial-aid/web-veita/src/styles.css
Labels: automerge

#7091 chore(prod): Increase default replica count on production
  apps/application-system/api/infra/application-system-api.ts
  apps/service-portal/infra/service-portal.ts
  apps/web/infra/web.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.prod.yaml
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/env.spec.ts
  infra/src/dsl/extraAttributes.spec.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/healthcheck.spec.ts
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/initContainer.spec.ts
  infra/src/dsl/map-to-values.ts
  infra/src/dsl/postgres.spec.ts
  infra/src/dsl/target-port.spec.ts
  infra/src/dsl/toggles.spec.ts
  infra/src/dsl/types/charts.ts
  infra/src/dsl/xroad.spec.ts
  infra/src/environments.ts
Labels: automerge

#7098 fix(ads): Increase available memory
  apps/air-discount-scheme/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#7067 feat(fa): Multiple muni & update staff add on muni
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
  apps/financial-aid/api/src/app/modules/staff/dto/updateStaff.input.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/staff/dto/updateStaff.dto.ts
  apps/financial-aid/web-osk/src/components/AppProvider/AppProvider.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useMunicipality.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/LogoMunicipality/Logo.css.ts
  apps/financial-aid/web-veita/src/components/LogoMunicipality/index.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.css.ts
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/Nav/Nav.css.ts
  apps/financial-aid/web-veita/src/components/Nav/Nav.tsx
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/routes/Application/application.tsx
  apps/financial-aid/web-veita/src/routes/Employee/employee.tsx
  apps/financial-aid/web-veita/src/routes/MunicipalitySettings/municipalitySettings.tsx
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
  apps/financial-aid/web-veita/src/utils/formHelper.ts
  apps/financial-aid/web-veita/src/utils/useMunicipalities.ts
  apps/financial-aid/web-veita/src/utils/useStaff.ts
  libs/financial-aid/shared/src/components/Breakdown/Breakdown.tsx
  libs/financial-aid/shared/src/components/hooks/index.ts
  libs/financial-aid/shared/src/components/index.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7104 fix(driving-instructor-application): query was missing variables and codeowners
  .github/CODEOWNERS
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
Labels: automerge

#7087 feat(clients): Add cache support in UserProfile and CompanyRegistry clients
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/rsk/company-registry/src/index.ts
  libs/clients/rsk/company-registry/src/lib/GetCompanyApiProvider.ts
  libs/clients/rsk/company-registry/src/lib/SearchCompanyRegistryApiProvider.ts
  libs/clients/rsk/company-registry/src/lib/ServiceInformationApiProvider.ts
  libs/clients/rsk/company-registry/src/lib/apiConfiguration.ts
  libs/clients/rsk/company-registry/src/lib/apis.ts
  libs/clients/rsk/company-registry/src/lib/company-registry-factory.config.ts
  libs/clients/rsk/company-registry/src/lib/company-registry.config.ts
  libs/clients/rsk/company-registry/src/lib/company-registry.module.ts
  libs/clients/rsk/company-registry/src/lib/types/index.ts
  libs/clients/rsk/company-registry/src/lib/types/service-options.type.ts
  libs/clients/user-profile/src/lib/apiConfiguration.ts
  libs/clients/user-profile/src/lib/userProfileClient.config.ts
Labels: automerge

#7111 feat(fa): Many municipalites settings
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/web-veita/src/components/AdminProvider/AdminProvider.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/EmailFormatInputModal.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/components/NumberInput/NumberInput.tsx
  apps/financial-aid/web-veita/src/components/SelectedMunicipality/SelectedMunicipality.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  apps/financial-aid/web-veita/src/routes/MunicipalitySettings/municipalitySettings.tsx
  apps/financial-aid/web-veita/src/utils/formHelper.ts
  apps/financial-aid/web-veita/src/utils/useMunicipalities.ts
Labels: automerge

#7114 feat(service-portal): Update code inputs.
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#7102 fix(service-portal): finance schedule negative value
  libs/service-portal/finance-schedule/src/components/FinanceScheduleDetailTable/FinanceScheduleDetailTable.tsx
Labels: automerge

#7120 fix(fa): Removing municipality name from staff
  apps/financial-aid/api/src/app/modules/staff/dto/createStaff.input.ts
  apps/financial-aid/api/src/app/modules/staff/models/staff.model.ts
  apps/financial-aid/backend/migrations/20220407131745-update-staff-removing-municipality_name.js
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/staff/dto/createStaff.dto.ts
  apps/financial-aid/backend/src/app/modules/staff/models/staff.model.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/backend/src/app/modules/staff/test/createStaff.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getStaffById.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getStaffByNationalId.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getStaffForMunicipality.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getSupervisors.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/getUsers.spec.ts
  apps/financial-aid/backend/src/app/modules/staff/test/update.spec.ts
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.tsx
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
  apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7121 fix(fa): Double header on print
  libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.css.ts
Labels: automerge

#7115 fix(web): Entry Hyperlink Circularity
  libs/cms/src/lib/models/html.model.ts
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#7100 feat(web): Secure asset links (https)
  libs/cms/src/lib/models/asset.model.ts
  libs/cms/src/lib/models/image.model.ts
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
Labels: automerge

#7122 fix(fa): Update municipality settings fixed
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
Labels: automerge

#7105 fix(fa): Make comments full width
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
Labels: automerge

#6906 feat(web): Organization published material page
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/o/[slug]/published-material.ts
  apps/web/pages/s/[slug]/utgefid-efni/index.ts
  apps/web/screens/Organization/NewsList.tsx
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.css.ts
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/Organization/PublishedMaterial/components/FilterTag/FilterTag.css.ts
  apps/web/screens/Organization/PublishedMaterial/components/FilterTag/FilterTag.tsx
  apps/web/screens/Organization/PublishedMaterial/components/FilterTag/index.ts
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/OrderByItem.css.ts
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/OrderByItem.tsx
  apps/web/screens/Organization/PublishedMaterial/components/OrderByItem/index.ts
  apps/web/screens/Organization/PublishedMaterial/components/PublishedMaterialItem/PublishedMaterialItem.tsx
  apps/web/screens/Organization/PublishedMaterial/components/PublishedMaterialItem/index.ts
  apps/web/screens/Organization/PublishedMaterial/index.ts
  apps/web/screens/Organization/PublishedMaterial/utils.ts
  apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/PublishedMaterial.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getPublishedMaterial.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/enhancedAsset.model.ts
  libs/cms/src/lib/models/enhancedAssetSearchResult.model.ts
  libs/cms/src/lib/models/genericTag.model.ts
  libs/cms/src/lib/models/genericTagGroup.model.ts
  libs/cms/src/lib/models/organization.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/importers/enhancedAsset.service.ts
  libs/content-search-index-manager/src/lib/index-templates/template-en.ts
  libs/content-search-index-manager/src/lib/index-templates/template-is.ts
Labels: automerge, deploy-feature

#7123 chore(j-s): DB Cleanup
  apps/judicial-system/backend/migrations/20220408094933-update-case.js
Labels: automerge

#7125 fix(driving-assessment-application): minor text fix
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingAssessmentApproval.ts
Labels: automerge

#7116 fix(service-portal): Increase timeout of nat reg service
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
Labels: automerge

#7128 feat(fa): Super admin can make existing user as admin
  apps/financial-aid/api/src/app/modules/municipality/models/municipality.model.ts
  apps/financial-aid/api/src/app/modules/municipality/municipality.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelection.css.ts
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionAdmins.tsx
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionMunicipality.tsx
  apps/financial-aid/web-veita/src/components/NewUserModal/NewUserModal.tsx
  apps/financial-aid/web-veita/src/components/Profile/EmployeeProfile.tsx
  apps/financial-aid/web-veita/src/components/Profile/MunicipalityProfile.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7129 fix(web): Featured Articles causing 500 error
  libs/cms/src/lib/models/articleReference.ts
  libs/cms/src/lib/models/featuredArticles.model.ts
Labels: automerge

#7130 feat(fa): When creating municipality being able to use existing admin
  apps/financial-aid/api/src/app/modules/municipality/dto/createMunicipality.input.ts
  apps/financial-aid/api/src/app/modules/staff/staff.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.controller.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.controller.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.service.ts
  apps/financial-aid/backend/src/app/modules/staff/test/numberOfUsersForMunicipality.spec.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/NewMunicipalityModal/NewMunicipalityModal.tsx
  apps/financial-aid/web-veita/src/routes/Municipalities/municipalities.tsx
Labels: automerge

#7132 feat(fa): When access to one municipality default will select one
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionMunicipality.tsx
  apps/financial-aid/web-veita/src/utils/formHelper.ts
Labels: automerge

#7134 fix(core): Update winston and winston-transport to resolve memory leak
  package.json
  yarn.lock
Labels: automerge

#7136 feat: Loading Input
  libs/island-ui/core/src/lib/Input/Input.css.ts
  libs/island-ui/core/src/lib/Input/Input.tsx
  libs/island-ui/core/src/lib/Input/types.ts
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#7139 fix(core): Update winston and winston-transport
  package.json
  yarn.lock
Labels: automerge

#7133 refactor(j-s): Cleanup Parse
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecordForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFiveForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/formatters.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
Labels: automerge, high priority

#7141 fix(fa): Text update on select
  .github/actions/unit-test/action.yml
  apps/financial-aid/web-veita/src/components/MultiSelection/MultiSelectionMunicipality.tsx
Labels: automerge, high priority

#7153 fix(fa): Fix long comments bug
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
Labels: automerge

#7119 fix(fa): Tax breakdown when missing months
  libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.tsx
  libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdownHeadline.tsx
  libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdownItem.tsx
Labels: automerge, high priority

#7062 fix(j-s): Fixes incorrect use of set case
  apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReportForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.tsx
Labels: automerge

#7068 feat(j-s): handle admission to facility in formatters
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  libs/cms-translations/src/lib/intl.service.spec.ts
  libs/cms-translations/src/lib/intl.service.ts
  libs/cms-translations/src/test/index.ts
  libs/cms-translations/src/test/testIntl.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: automerge

#7147 fix(j-s): fix audit action when getting custody notice
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
Labels: automerge

#6743 feat(driving-school-confirmation): driving school confirmation process
  .github/CODEOWNERS
  libs/api/domains/driving-license-book/src/drivinLicenceBook.type.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.module.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.resolver.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.service.ts
  libs/api/domains/driving-license-book/src/dto/createDrivingSchoolTestResult.input.ts
  libs/api/domains/driving-license-book/src/guards/drivingSchoolEmployee.guard.ts
  libs/api/domains/driving-license-book/src/index.ts
  libs/api/domains/driving-license-book/src/models/drivingLicenseBookSchoolType.response.ts
  libs/api/domains/driving-license-book/src/models/drivingLicenseTestResult.response.ts
  libs/api/domains/driving-license-book/src/models/drivingSchool.response.ts
  libs/application/core/src/types/ApplicationTypes.ts
  libs/application/template-api-modules/src/lib/modules/template-api.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-school-confirmation/driving-school-confirmation.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-school-confirmation/driving-school-confirmation.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-school-confirmation/types.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
  libs/application/templates/driving-school-confirmation/.babelrc
  libs/application/templates/driving-school-confirmation/.eslintrc
  libs/application/templates/driving-school-confirmation/README.md
  libs/application/templates/driving-school-confirmation/babel-jest.config.json
  libs/application/templates/driving-school-confirmation/codegen.yml
  libs/application/templates/driving-school-confirmation/jest.config.js
  libs/application/templates/driving-school-confirmation/src/assets/Jobs.tsx
  libs/application/templates/driving-school-confirmation/src/dataProviders/EmployeeProvider.ts
  libs/application/templates/driving-school-confirmation/src/dataProviders/index.ts
  libs/application/templates/driving-school-confirmation/src/fields/ConfirmationDate/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/SchoolConfirmed/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/SelectSchool/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/Skeleton.tsx
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/index.ts
  libs/application/templates/driving-school-confirmation/src/forms/done.ts
  libs/application/templates/driving-school-confirmation/src/forms/drivingSchoolConfirmtation.ts
  libs/application/templates/driving-school-confirmation/src/graphql/queries.ts
  libs/application/templates/driving-school-confirmation/src/index.ts
  libs/application/templates/driving-school-confirmation/src/lib/DrivingSchoolConfirmationTemplate.ts
  libs/application/templates/driving-school-confirmation/src/lib/constants.ts
  libs/application/templates/driving-school-confirmation/src/lib/dataSchema.ts
  libs/application/templates/driving-school-confirmation/src/lib/messages.ts
  libs/application/templates/driving-school-confirmation/tsconfig.json
  libs/application/templates/driving-school-confirmation/tsconfig.lib.json
  libs/application/templates/driving-school-confirmation/tsconfig.spec.json
  libs/clients/driving-license-book/src/clientConfig.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#7124 chore(j-s): Test Cleanup
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/confirmation.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/ruling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/demands.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/report.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepFour.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepThree.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepTwo.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/PageLayout/utils/index.spec.ts
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/tsconfig.app.json
  libs/judicial-system/formatters/src/index.ts
  libs/judicial-system/formatters/src/lib/testData.ts
Labels: automerge

#7166 feat(fa): Get only applications from staff munici when filtering
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
Labels: automerge

#7148 fix(j-s): Fixes File Upload
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/getAll.spec.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
Labels: automerge

#7143 feat(web): Sýslumenn published material page override
  apps/web/pages/s/syslumenn/utgefid-efni/index.ts
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#7157 feat(web): Project page code refactor and IBM Watson Chat bot support added
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.css.ts
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
  apps/web/components/ChatPanel/BoostChatPanel/config.ts
  apps/web/components/ChatPanel/BoostChatPanel/index.ts
  apps/web/components/ChatPanel/BoostChatPanel/types.d.ts
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
  apps/web/components/ChatPanel/LiveChatIncChatPanel/index.ts
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/WatsonChatPanel/index.ts
  apps/web/components/ChatPanel/index.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/real.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Article/config.ts
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/components/ProjectChatPanel/ProjectChatPanel.tsx
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/index.ts
  apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
  apps/web/screens/Project/components/ProjectHeader/index.ts
  apps/web/screens/Project/components/ProjectWrapper/ProjectWrapper.tsx
  apps/web/screens/Project/components/ProjectWrapper/index.ts
  apps/web/screens/Project/utils.ts
Labels: automerge

#7170 fix(island-ui): input padding on xs
  libs/island-ui/core/src/lib/Input/Input.mixins.ts
Labels: automerge

#7176 feat(web): Ukraine chat panel added to an article
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Article/config.ts
Labels: automerge

#7150 feat(j-s): File Upload Explanations
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFiveForm.tsx
Labels: automerge

#7172 feat(service-portal): hide content when printing
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  libs/service-portal/assets/src/components/AssetDisclaimer/index.tsx
  libs/service-portal/core/src/components/ExpandableTable/Header.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceTransactionsTable/FinanceTransactionsTable.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: automerge

#7177 fix(service-portal): remove prepended https
  libs/service-portal/documents/src/utils/getOrganizationLogoUrl.ts
Labels: automerge

#7179 fix(ci): another attempt to be able to re-run failing e2e tests
  .github/workflows/pullrequest.yml
Labels: automerge, high priority

#7151 fix(j-s): Fixes Validation of Legal Basis
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepThree.spec.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#7181 chore(core): Fix IDS client credential DX
  infra/src/cli/render-secrets.ts
Labels: automerge

#7185 fix(ci): secrets workflow stopped working due to missing nodejs
  .github/workflows/config-values.yaml
Labels: automerge

#7180 feat(service-portal): Update family card loader
  libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCardLoader.tsx
Labels: automerge

#7184 feat(j-s): Prepares Norðurland eystra for Go Live
  apps/judicial-system/backend/migrations/20220419164419-update-institution.js
  apps/judicial-system/backend/test/e2e.spec.ts
Labels: automerge

#7173 feat(ci): Moving all workflows to ec2-runners
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest-close.yml
  .github/workflows/pullrequest-lint.yml
  .github/workflows/pullrequest.yml
Labels: automerge

#7137 fix(service-portal): Update dynamic routes function
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
Labels: automerge, deploy-feature

#7145 fix(driving-license-application): Fixing error message for other country error
  libs/application/templates/driving-license/src/fields/Done/Declined.tsx
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#7190 fix(j-s): fix condition check for caseTypea in pdf
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
Labels: automerge

#7192 fix(j-s): fix ready for court mail sent to prosector
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7194 feat(regulations): show all impacts in history list
  apps/web/components/Regulations/DiffModeToggle.tsx
  apps/web/components/Regulations/HistoryStepper.tsx
  apps/web/components/Regulations/RegulationChangelog.tsx
  package.json
  yarn.lock
Labels: automerge

#7187 chore(deps): Upgrade dd-trace
  package.json
  yarn.lock
Labels: automerge

#7191 fix(ci): codeowners-validation-fix
  .github/CODEOWNERS
  .github/workflows/external-checks.yml
Labels: automerge

#7079 fix(application-system): Persist locale by using userprofile in application system
  apps/application-system/form/src/auth.ts
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge

#7197 feat(regulations): hotfix show all impacts in history list (#7194)
  apps/web/components/Regulations/DiffModeToggle.tsx
  apps/web/components/Regulations/HistoryStepper.tsx
  apps/web/components/Regulations/RegulationChangelog.tsx
  package.json
  yarn.lock
Labels: automerge

#7154 feat(service-portal): Add land usage for real estate
  libs/api/domains/assets/src/lib/api-domains-assets.service.ts
  libs/api/domains/assets/src/models/Land.model.ts
  libs/api/domains/assets/src/models/propertyDetail.model.ts
  libs/api/mocks/src/domains/assets/factories.ts
  libs/api/mocks/src/domains/assets/resolvers.ts
  libs/clients/assets/src/clientConfig.yaml
  libs/service-portal/assets/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/lib/queries.ts
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
Labels: automerge

#7200 fix(j-s): fix date and time format in notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#7108 fix(core): Enhanced Fetch improvements
  libs/clients/middlewares/README.md
  libs/clients/middlewares/src/lib/createEnhancedFetch.ts
  libs/clients/middlewares/src/lib/e2e/enhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/e2e/test-cert.pfx
  libs/clients/middlewares/src/lib/withAgent.ts
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/clients/middlewares/src/lib/withCache/CacheResponse.ts
  libs/clients/middlewares/src/lib/withCache/CacheStatus.ts
  libs/clients/middlewares/src/lib/withCache/types.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/middlewares/src/lib/withClientCertificate.ts
  libs/clients/middlewares/src/lib/withErrorLog.ts
  libs/clients/middlewares/src/lib/withMetrics.spec.ts
  libs/clients/middlewares/src/lib/withMetrics.ts
  libs/clients/middlewares/src/lib/withResponseErrors.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/sleep.ts
  package.json
  yarn.lock
Labels: automerge

#7171 refactor(service-portal): translation strings
  apps/service-portal/src/components/Notifications/NotificationMenu/mockNotifications.ts
  libs/service-portal/applications/src/lib/messages.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/documents/src/components/DocumentCard/DocumentCard.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/widgets/documentList.tsx
  libs/service-portal/family/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/family/src/screens/UserInfoOverview/mockUserInfoList.ts
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
Labels: automerge

#7204 chore(deps): Upgrade dd-trace (#7187)
  package.json
  yarn.lock
Labels: automerge

#7203 fix(service-portal): Update bank input styling
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Nudge.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/ProfileForms.css.ts
Labels: automerge

#7208 fix(j-s): Fixes Investigation Ruling
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
Labels: automerge

#7149 feat(application-system): Delete applications
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/dto/application.response.dto.ts
  apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  apps/application-system/form/src/routes/Applications.tsx
  libs/api/domains/application/src/lib/application.model.ts
  libs/api/domains/application/src/lib/application.resolver.ts
  libs/api/domains/application/src/lib/application.service.ts
  libs/api/domains/application/src/lib/dto/deleteApplication.input.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.ts
  libs/application/core/src/lib/messages.ts
  libs/application/core/src/types/Application.ts
  libs/application/core/src/types/StateMachine.ts
  libs/application/graphql/src/index.ts
  libs/application/graphql/src/lib/fragments/application.ts
  libs/application/graphql/src/lib/mutations/deleteApplication.ts
  libs/application/templates/data-protection-complaint/src/lib/DataProtectionComplaintTemplate.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/application/ui-components/src/components/ApplicationList/hooks/useDeleteApplication.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/service-portal/applications/src/screens/ApplicationList/ApplicationList.tsx
  libs/service-portal/graphql/src/hooks/applications/useApplications.ts
Labels: automerge, deploy-feature

#7199 fix(parental-leave): personalAllowance.usage and personalAllowanceFromSpouse.usage set default to 0
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#7210 fix(j-s): Fix ruling autofill
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
Labels: automerge

#7198 feat(j-s): Request PDF Iteration
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/formatters/policeStar.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
Labels: automerge

#7110 feat(service-portal): Add button in mobile settings
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/FormButton.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Nudge.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/Phone.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/ProfileForms.css.ts
Labels: automerge, deploy-feature

#7178 perf(search-indexer): Cluster reduction for local development performance
  apps/services/search-indexer/dev-services/docker-compose.yml
Labels: automerge

#7164 chore(web): Organization and Project page translation tweaks
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/MannaudstorgFooter.tsx
  apps/web/components/StepperFSM/StepperFSM.tsx
  apps/web/pages/en/o/index.ts
  apps/web/pages/s/index.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Organization/Home.tsx
  apps/web/screens/Organization/Services.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Organizations/Organizations.tsx
  apps/web/screens/Project/Project.tsx
Labels: automerge

#7207 refactor(service-portal): test sidenav icon
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.css.ts
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
Labels: automerge, deploy-feature

#7214 feat: display notification about unmigrated regulation status
  apps/web/components/Regulations/RegulationStatus.tsx
  apps/web/components/Regulations/RegulationTexts.types.ts
Labels: automerge

#7217 fix: show correct final date when viewing original version
  apps/web/components/Regulations/RegulationStatus.tsx
Labels: automerge

#7224 fix(regulations): issue with status order
  apps/web/components/Regulations/RegulationStatus.tsx
Labels: automerge

#6886 feat(service-portal): Add manual plausible script
  apps/service-portal/src/index.html
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/screens/Modules/Modules.tsx
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
  libs/service-portal/core/src/hooks/usePlausibleDetailPageview/usePlausibleDetailPageview.ts
  libs/service-portal/family/src/screens/FamilyMember/FamilyMember.tsx
  libs/service-portal/family/src/screens/Spouse/Spouse.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
Labels: automerge

#7218 refactor(service-portal): Shrink SVG images
  apps/service-portal/src/assets/images/404.svg
  apps/service-portal/src/assets/images/bench.svg
  apps/service-portal/src/assets/images/bus.svg
  apps/service-portal/src/assets/images/coffee.svg
  apps/service-portal/src/assets/images/education.svg
  apps/service-portal/src/assets/images/educationDegree.svg
  apps/service-portal/src/assets/images/educationGrades.svg
  apps/service-portal/src/assets/images/educationLicense.svg
  apps/service-portal/src/assets/images/emptyState.svg
  apps/service-portal/src/assets/images/familyGrid.svg
  apps/service-portal/src/assets/images/health.svg
  apps/service-portal/src/assets/images/hourglass.svg
  apps/service-portal/src/assets/images/individualsGrid.svg
  apps/service-portal/src/assets/images/jobsGrid.svg
  apps/service-portal/src/assets/images/movingTruck.svg
  apps/service-portal/src/assets/images/myDocuments.svg
  apps/service-portal/src/assets/images/myInfo.svg
  apps/service-portal/src/assets/images/myRights.svg
  apps/service-portal/src/assets/images/payment.svg
  apps/service-portal/src/assets/images/retirement.svg
  apps/service-portal/src/assets/images/school.svg
  apps/service-portal/src/assets/images/settings.svg
  apps/service-portal/src/assets/images/shopping.svg
  apps/service-portal/src/assets/images/sofa.svg
  libs/service-portal/education/src/screens/EducationOverview/EducationOverview.tsx
Labels: automerge

#7216 fix(service-portal): empty alt texts for decorative images + cleanup
  apps/service-portal/src/components/ApplicationErrorBoundary/ApplicationErrorBoundary.tsx
  apps/service-portal/src/components/Greeting/Greeting.tsx
  libs/service-portal/core/src/components/EducationCard/EducationCard.tsx
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/screens/ErrorScreen/ErrorScreen.tsx
  libs/service-portal/core/src/screens/InfoScreen/InfoScreen.tsx
  libs/service-portal/core/src/screens/NavigationOverviewScreen/NavigationOverviewScreen.tsx
  libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/eligibility/src/screens/Eligibility/Eligibility.tsx
  libs/service-portal/family/src/components/UserInfoItem/UserInfoItem.tsx
  libs/service-portal/settings/access-control/src/components/AccessModal/AccessModal.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/DropModal.tsx
Labels: automerge

#7220 feat(service-portal): cleanup unused CSS
  libs/service-portal/core/src/components/ExpandableTable/ExpandableTable.css.ts
  libs/service-portal/core/src/components/NavigationScreen/Card/Card.css.ts
  libs/service-portal/core/src/screens/InfoScreen/InfoScreen.css.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
  libs/service-portal/documents/src/screens/Overview/Overview.css.ts
  libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCard.css.ts
  libs/service-portal/family/src/components/UserInfoItem/UserInfo.css.ts
  libs/service-portal/family/src/screens/FamilyOverview/FamilyOverview.css.ts
  libs/service-portal/icelandic-names-registry/src/components/Editor/Editor.css.ts
  libs/service-portal/licenses/src/components/DrivingLicense/DrivingLicense.css.ts
  libs/service-portal/licenses/src/components/LicenseCards/LicenseCards.css.ts
  libs/service-portal/licenses/src/components/LicenseIcon/LicenseIcon.css.ts
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.css.ts
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/DrivingLicenseDetail.tsx
  libs/service-portal/licenses/src/screens/DrivingLicenseDetail/ExpandableLine.tsx
  libs/service-portal/settings/access-control/src/components/AccessItem/AccessItem.css.ts
  libs/service-portal/settings/access-control/src/screens/Access/Access.css.ts
  libs/service-portal/settings/personal-information/src/screens/UserProfile/UserProfile.css.ts
Labels: automerge

#7175 feat(service-portal): finance schedule scope added
  apps/service-portal/src/auth.ts
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge, deploy-feature

#7209 feat(service-portal): Translation support for access control scopes
  apps/services/auth-admin-api/src/app/modules/resources/resources.module.ts
  apps/services/auth-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-api/src/app/modules/permissions/permissions.module.ts
  apps/services/auth-api/src/app/modules/resources/resources.module.ts
  apps/services/auth-public-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth-public-api/src/app/modules/resources/resources.module.ts
  apps/services/auth-public-api/src/app/modules/resources/scopes.controller.spec.ts
  apps/services/auth-public-api/src/app/modules/resources/scopes.controller.ts
  apps/services/auth-public-api/src/environments/environment.ts
  apps/services/auth-public-api/test/fixtures/delegation.fixture.ts
  apps/services/auth-public-api/test/setup.ts
  libs/api/domains/auth/src/lib/apiScope.service.ts
  libs/api/domains/auth/src/lib/dto/apiScopes.input.ts
  libs/api/domains/auth/src/lib/resolvers/apiScope.resolver.ts
  libs/auth-api-lib/migrations/20220422141112-add-index-to-language-table.js
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/modules/translation.module.ts
  libs/auth-api-lib/src/lib/services/resources.service.ts
  libs/auth-api-lib/src/lib/services/translation.service.ts
  libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
Labels: automerge

#7229 chore(public-debt-payment-plan): Add mockdata, prerequisites, better errorhandling, remove lots of code
  libs/application/templates/public-debt-payment-plan/src/dataProviders/mockData.ts
  libs/application/templates/public-debt-payment-plan/src/dataProviders/paymentPlanPrerequisites.ts
  libs/application/templates/public-debt-payment-plan/src/fields/PrerequisitesErrorModal/PrerequisitesErrorModal.css.ts
  libs/application/templates/public-debt-payment-plan/src/fields/PrerequisitesErrorModal/PrerequisitesErrorModal.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/index.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/error.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/externalData.ts
Labels: automerge

#7230 feat(auth-api): Add feature flag for IDS user-profile integration
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.ts
  apps/services/auth-api/src/app/modules/user-profile/user-profile.module.ts
  libs/auth-api-lib/src/lib/services/user-profile.service.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#7233 fix(gfl): missing ready for production
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
Labels: automerge

#7231 fix(gfl): missing ready for production
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
Labels: automerge

#7234 fix(service-portal): Update translation strings family
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
  libs/service-portal/family/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/family/src/lib/messages.ts
  libs/service-portal/family/src/lib/service-portal-family.tsx
  libs/service-portal/family/src/screens/FamilyMember/ChildRegistrationModal.tsx
  libs/service-portal/family/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/family/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge

#7235 fix(parental-leave): tax percentage calculator
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7237 fix(driving-license): Driving instructor guard on student info
  libs/api/domains/driving-license/src/lib/graphql/guards/drivingInstructor.guard.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
Labels: automerge

#7243 fix(application-system): Hotfix/remove userprofile locale logic
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge

#7239 fix(fa): Tax break down adding data fetched
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  libs/financial-aid/shared/src/components/TaxBreakdown/TaxBreakdown.tsx
Labels: automerge

#7244 fix(j-s): fix contentful upload errors
  apps/judicial-system/web/messages/Core/restrictions.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/confirmation.ts
Labels: automerge

#7252 fix(j-s): remove template strings from contentful strings
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/messages/pdfCustodyNotice.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/Core/restrictions.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/courtRecordForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/ruling.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/demandsForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/reportForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/requestedHearingArrangementsForm.ts
Labels: automerge

#7254 feat(web): Organization page english footers
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#7246 fix(core): EnhancedFetch regression when using both cache and auth
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/buildFetch.ts
  libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/createEnhancedFetch.ts
  libs/clients/middlewares/src/lib/nodeFetch.ts
  libs/clients/middlewares/src/lib/withAgent.ts
  libs/clients/middlewares/src/lib/withAuth.ts
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/clients/middlewares/src/lib/withAutoAuth.ts
  libs/clients/middlewares/src/lib/withCache/types.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/middlewares/src/lib/withCircuitBreaker.ts
  libs/clients/middlewares/src/lib/withErrorLog.ts
  libs/clients/middlewares/src/lib/withMetrics.ts
  libs/clients/middlewares/src/lib/withResponseErrors.ts
  libs/clients/middlewares/src/lib/withTimeout.ts
Labels: automerge, deploy-feature

#7255 fix(core): HOTFIX EnhancedFetch regression when using both cache and auth
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/buildFetch.ts
  libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/createEnhancedFetch.ts
  libs/clients/middlewares/src/lib/nodeFetch.ts
  libs/clients/middlewares/src/lib/withAgent.ts
  libs/clients/middlewares/src/lib/withAuth.ts
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/clients/middlewares/src/lib/withAutoAuth.ts
  libs/clients/middlewares/src/lib/withCache/types.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/middlewares/src/lib/withCircuitBreaker.ts
  libs/clients/middlewares/src/lib/withErrorLog.ts
  libs/clients/middlewares/src/lib/withMetrics.ts
  libs/clients/middlewares/src/lib/withResponseErrors.ts
  libs/clients/middlewares/src/lib/withTimeout.ts
Labels: automerge

#7253 fix(parental-leave): answer validation for privatePensionFund and privatePensionFundPercentage
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/UsePrivatePensionFund/index.tsx
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge

#7257 fix(driving-license-book): updating the api name for get school for staff
  libs/api/domains/driving-license-book/src/drivingLicenseBook.service.ts
  libs/application/templates/driving-school-confirmation/src/forms/drivingSchoolConfirmtation.ts
  libs/application/templates/driving-school-confirmation/src/lib/messages.ts
  libs/clients/driving-license-book/src/clientConfig.json
Labels: automerge

#7258 fix(driving-license): title touch up
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#7259 feat(parental-leave): Update spouse/employer email template
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
Labels: automerge

#7261 feat(parental-leave): added application delete button
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#7256 test(j-s): refactor createTestIntl setup
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  libs/cms-translations/src/lib/intl.service.spec.ts
  libs/cms-translations/src/test/testIntl.ts
  package.json
  yarn.lock
Labels: automerge

#7262 feat(parental-leave): added delete button on more application states
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#7260 fix(fa): Fixing application flow after AS merge on main
  apps/financial-aid/api/src/app/modules/file/dto/getSignedUrl.input.ts
  apps/financial-aid/api/src/app/modules/personalTaxReturn/dto/municipalitiesPersonalTaxReturn.input.ts
  apps/financial-aid/api/src/app/modules/personalTaxReturn/personalTaxReturn.resolver.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/personalTaxReturn.controller.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/personalTaxReturn.service.ts
  apps/financial-aid/backend/src/app/modules/personalTaxReturn/test/municipalitiesPersonalTaxReturn.spec.ts
  apps/financial-aid/web-osk/graphql/sharedGql.ts
  apps/financial-aid/web-osk/src/components/Estimation/Estimation.tsx
  apps/financial-aid/web-osk/src/components/FormProvider/FormProvider.tsx
  apps/financial-aid/web-osk/src/components/Status/InProgress.tsx
  apps/financial-aid/web-osk/src/components/Summary/AllFiles.tsx
  apps/financial-aid/web-osk/src/routes/application/SummaryForm/summaryForm.tsx
  apps/financial-aid/web-osk/src/utils/hooks/useFileUpload.ts
  apps/financial-aid/web-osk/src/utils/hooks/useTaxData.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7188 feat(web): Feature flag support for web
  apps/web/README.md
  apps/web/next.config.js
  apps/web/utils/featureFlag/featureFlag.spec.ts
  apps/web/utils/featureFlag/featureFlag.ts
  apps/web/utils/featureFlag/index.ts
Labels: automerge

#7251 fix(application-system): Use UserProfileLocale from service-portal in application
  apps/application-system/form/src/app/App.tsx
  apps/application-system/form/src/routes/Applications.tsx
  apps/service-portal/src/app/App.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/service-portal/graphql/src/lib/client.ts
  libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
  libs/shared/components/src/auth/UserMenu/userProfile.graphql.ts
  libs/shared/components/src/index.ts
Labels: automerge

#7270 feat(service-portal): Add delete functionality on applications
  apps/service-portal/src/auth.ts
  libs/service-portal/graphql/src/lib/fragments/application.ts
Labels: automerge

#7266 feat(j-s): support admission cases in custody restrictions
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/pdfCustodyNotice.ts
  apps/judicial-system/web/messages/Core/restrictions.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/utils/restrictions.spec.tsx
  apps/judicial-system/web/src/utils/restrictions.ts
  libs/judicial-system/formatters/src/lib/formatters.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#7265 chore(application-system): Add documentation for application featureflag
  handbook/technical-overview/feature-flags.md
  libs/application/core/README.md
Labels: automerge

#7271 fix(application-system): Reintroduce userprofile locale logic
  apps/application-system/form/src/app/App.tsx
  apps/application-system/form/src/routes/Applications.tsx
  apps/service-portal/src/app/App.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/service-portal/graphql/src/lib/client.ts
  libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
  libs/shared/components/src/auth/UserMenu/userProfile.graphql.ts
  libs/shared/components/src/index.ts
Labels: automerge

#7272 fix(j-s): support admission case in extend custody modal
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#7274 feat(web): OneColumnText Slice link url
  apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
Labels: automerge
