Repository island-is/island.is, pull requests merged in 2022-05, with the labels that each got.

#7285 feat(web): Hotfix - Feature flag support for web (#7188)
  apps/web/README.md
  apps/web/next.config.js
  apps/web/utils/featureFlag/featureFlag.spec.ts
  apps/web/utils/featureFlag/featureFlag.ts
  apps/web/utils/featureFlag/index.ts
Labels: automerge

#7287 fix(j-s): add missing param to contentful string
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#7238 chore(core): Update oidc-client library
  apps/service-portal/src/components/GlobalModules/GlobalModules.tsx
  apps/service-portal/src/hooks/useNavigation/useNavigation.ts
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/screens/Modules/Modules.tsx
  apps/service-portal/src/utils/http.ts
  libs/auth/react/src/lib/AuthSettings.spec.ts
  libs/auth/react/src/lib/AuthSettings.ts
  libs/auth/react/src/lib/Authenticator/Authenticator.mocked.spec.tsx
  libs/auth/react/src/lib/Authenticator/Authenticator.spec.tsx
  libs/auth/react/src/lib/Authenticator/Authenticator.tsx
  libs/auth/react/src/lib/getAccessToken.ts
  libs/auth/react/src/lib/userManager.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/core/src/utils/utils.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/shared/types/src/lib/user.ts
  libs/testing/fixtures/src/lib/openIDUser.ts
  package.json
  yarn.lock
Labels: automerge, deploy-feature

#7278 chore(swagger): specify what to import in docs
  libs/nest/swagger/README.md
Labels: automerge

#7275 feat(j-s): validate court case number
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web/src/routes/Court/SharedComponents/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/utils/utils.spec.tsx
  apps/judicial-system/web/src/utils/validate.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#7298 fix(parental-leave): tax percentage calculator (#7235)
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.spec.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7297 chore(core): Update oidc-client library (#7238)
  apps/service-portal/src/components/GlobalModules/GlobalModules.tsx
  apps/service-portal/src/hooks/useNavigation/useNavigation.ts
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/screens/Modules/Modules.tsx
  apps/service-portal/src/utils/http.ts
  libs/auth/react/src/lib/AuthSettings.spec.ts
  libs/auth/react/src/lib/AuthSettings.ts
  libs/auth/react/src/lib/Authenticator/Authenticator.mocked.spec.tsx
  libs/auth/react/src/lib/Authenticator/Authenticator.spec.tsx
  libs/auth/react/src/lib/Authenticator/Authenticator.tsx
  libs/auth/react/src/lib/getAccessToken.ts
  libs/auth/react/src/lib/userManager.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/core/src/utils/utils.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/shared/types/src/lib/user.ts
  libs/testing/fixtures/src/lib/openIDUser.ts
  package.json
  yarn.lock
Labels: automerge

#7296 fix(parental-leave): allowance issue when leaving usage field empty and changing answer to yes
  libs/application/templates/parental-leave/src/fields/SpouseUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/fields/personalUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#7288 fix(driving-license): adding delete option for applicant in prereq/draft state
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
Labels: automerge

#7267 feat(fa): UI for state page
  libs/application/templates/financial-aid/src/fields/Status/AidAmount/AidAmount.tsx
  libs/application/templates/financial-aid/src/fields/Status/ApplicantStatus.tsx
  libs/application/templates/financial-aid/src/fields/Status/Estimation/Estimation.tsx
  libs/application/templates/financial-aid/src/fields/Status/Header/Header.tsx
  libs/application/templates/financial-aid/src/fields/Status/MissingFIlesCard/MissingFilesCard.tsx
  libs/application/templates/financial-aid/src/fields/Status/MoreActions/MoreActions.tsx
  libs/application/templates/financial-aid/src/fields/Status/RejectionMessage/RejectionMessage.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseAlert/SpouseAlert.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseApproved/SpouseApproved.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseStatus.tsx
  libs/application/templates/financial-aid/src/fields/Status/Timeline/Timeline.css.ts
  libs/application/templates/financial-aid/src/fields/Status/Timeline/Timeline.tsx
  libs/application/templates/financial-aid/src/fields/Status/index.ts
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/ApplicantSubmitted.ts
  libs/application/templates/financial-aid/src/forms/SpouseSubmitted.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/formatters.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/messages/status.ts
  libs/application/templates/financial-aid/src/lib/types.ts
Labels: automerge

#7304 fix(j-s): Fix Markdown Error
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFilesForm.tsx
Labels: automerge

#7301 fix(service-portal): Update link for greidsluaaetlun
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#7302 chore(judicial-system): Add a tooltip to isAdmissionToFacility checkbox
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/demandsForm.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
Labels: automerge

#7307 fix(parental-leave): fix tax calculator on new year
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7282 feat(infra): DataDog RUM integration for a few web apps
  apps/air-discount-scheme/web/next.config.js
  apps/air-discount-scheme/web/pages/_app.tsx
  apps/application-system/form/infra/application-system-form.ts
  apps/application-system/form/src/environments/environment.ts
  apps/application-system/form/src/main.tsx
  apps/service-portal/infra/service-portal.ts
  apps/service-portal/src/Main.tsx
  apps/service-portal/src/environments/environment.ts
  apps/service-portal/tsconfig.app.json
  apps/skilavottord/web/infra/web.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/shared/pii/src/lib/maskNationalId.ts
  libs/shared/utils/src/lib/getStaticEnv.spec.ts
  libs/shared/utils/src/lib/getStaticEnv.ts
  scripts/dockerfile-assets/bash/extract-environment.sh
Labels: automerge

#7306 fix(parental-leave): copy for pension fund
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#7248 feat(financial-statements-inao): Financial statements for INAO API init
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  jest.config.js
  libs/api/domains/financial-statements-inao/.eslintrc.json
  libs/api/domains/financial-statements-inao/README.md
  libs/api/domains/financial-statements-inao/jest.config.js
  libs/api/domains/financial-statements-inao/src/index.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.module.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/models/election.model.ts
  libs/api/domains/financial-statements-inao/tsconfig.json
  libs/api/domains/financial-statements-inao/tsconfig.lib.json
  libs/api/domains/financial-statements-inao/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#7308 fix(j-s): disable continue btn if court-case-number is invalid
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#7300 fix(driving-school-confirmation): adding name lookup on kt input
  libs/application/templates/driving-school-confirmation/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/SchoolConfirmed/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/index.ts
  libs/application/templates/driving-school-confirmation/src/forms/drivingSchoolConfirmation.ts
  libs/application/templates/driving-school-confirmation/src/lib/DrivingSchoolConfirmationTemplate.ts
  libs/application/templates/driving-school-confirmation/src/lib/dataSchema.ts
  libs/application/templates/driving-school-confirmation/src/lib/messages.ts
  libs/application/templates/driving-school-confirmation/src/types.ts
Labels: automerge

#7310 feat(fa): Setting up contentful in financial-aid
  libs/application/templates/financial-aid/src/lib/messages/personalTaxCreditForm.ts
  libs/application/templates/financial-aid/src/lib/messages/unknownRelationship.ts
  workspace.json
Labels: automerge

#7320 fix(parental-leave): privatepensionfund and percentage validation fix on failed submit
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
Labels: automerge

#7323 hotfix/parental-leave-fixes
  libs/application/templates/parental-leave/src/fields/SpouseUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/fields/personalUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7276 fix(general-fishing-license): Added error on provider when no ships are registered
  apps/api/src/app/environments/environment.ts
  libs/application/templates/general-fishing-license/src/dataProviders/generalFishingLicenseProvider.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/externalDataSection.ts
  libs/application/templates/general-fishing-license/src/lib/messages/error.ts
  libs/application/templates/general-fishing-license/src/lib/messages/externalData.ts
Labels: automerge

#7318 feat(service-portal): Add extra info for family members + my info
  libs/api/domains/national-registry/src/lib/graphql/child.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/familyMember.resolver.ts
  libs/api/domains/national-registry/src/lib/graphql/models/user.model.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/types/user.type.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/family/src/components/ChildView/ChildView.tsx
  libs/service-portal/family/src/lib/messages.ts
  libs/service-portal/family/src/lib/queries/getNationalChildren.ts
  libs/service-portal/family/src/lib/queries/getNationalRegistryFamily.ts
  libs/service-portal/family/src/lib/queries/getNationalRegistryUser.ts
  libs/service-portal/family/src/screens/UserInfo/UserInfo.tsx
Labels: automerge, deploy-feature

#7311 chore(service-portal): Update finance readme
  libs/api/domains/finance/README.md
  libs/clients/finance/README.md
Labels: automerge

#7250 fix(driving-instructor-registrations): adding feature flags
  libs/application/templates/driving-instructor-registrations/src/lib/InstructorRegistrationsTemplate.ts
  libs/application/templates/driving-school-confirmation/src/lib/DrivingSchoolConfirmationTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#7327 feat(driving-license-application): Health check remarks on fullnaðarskírteini
  libs/api/domains/driving-license/src/lib/__mock-data__/validLicense.json
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/dataProviders/CurrentLicenseProvider.ts
  libs/application/templates/driving-license/src/fields/HealthRemarks.tsx
  libs/application/templates/driving-license/src/fields/index.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/driving-license/src/v1/index.ts
Labels: automerge

#7183 feat: configuration DSL supports the new rendering of the HPA, which supports ingress metric scaling
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/map-to-values.ts
  infra/src/dsl/types/input-types.ts
  infra/src/dsl/types/output-types.ts
Labels: deploy-feature

#7324 fix(infra): Adding env variables to configure DD RUM for air-discount-scheme-web
  apps/air-discount-scheme/web/infra/web.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#7319 feat(j-s): Default Court and Police Case Number Prefix
  apps/judicial-system/api/src/app/modules/case/dto/createCase.input.ts
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/api/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/migrations/20220502113246-update-institution.js
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/internalCreate.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/Core/policeCaseNumber.ts
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
  apps/judicial-system/web/src/components/UserProvider/UserProvider.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/LokeCaseNumber/LokeCaseNumber.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  libs/judicial-system/court-client/src/lib/uploadStreamApi/uploadStreamApi.ts
  libs/judicial-system/types/src/lib/case.ts
  libs/judicial-system/types/src/lib/institution.ts
Labels: automerge

#7295 chore: Updating client id references from ids-admin to @island.is/auth-admin-web where it is used
  apps/auth-admin-web/utils/ids.constants.ts
  libs/auth-api-lib/seeders/20210416103546-ids-admin-add-scopes.js
  libs/auth-api-lib/seeders/20210426083138-add-admin-uris.js
  libs/auth-api-lib/seeders/local/003-ids-admin.client.js
  libs/auth-api-lib/seeders/local/004-island.is.client.js
  libs/auth-api-lib/seeders/local/005-skra.is.client.js
Labels: automerge

#7330 fix(parental-leave): change personalAllowance useAsMuchAsPossible copy to correct copy
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#7291 fix(company-registry): Fix client to match server response
  apps/services/auth-api/src/app/modules/user-profile/user-profile.controller.spec.ts
  apps/services/auth-api/test/setup.ts
  libs/api/domains/company-registry/src/lib/api-domains-company-registry.resolver.ts
  libs/api/domains/company-registry/src/lib/models/rskCompany.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyAddress.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyLink.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanySearchItems.model.ts
  libs/api/domains/company-registry/src/lib/models/rskCompanyVat.model.ts
  libs/api/domains/company-registry/src/lib/rsk-company-info.service.ts
  libs/auth-api-lib/src/lib/services/user-profile.service.ts
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/FetchError.ts
  libs/clients/middlewares/src/lib/handle404.spec.ts
  libs/clients/middlewares/src/lib/handle404.ts
  libs/clients/rsk/company-registry/src/clientConfig.json
  libs/clients/rsk/company-registry/src/index.ts
  libs/clients/rsk/company-registry/src/lib/apis.ts
  libs/clients/rsk/company-registry/src/lib/company-registry-client.service.spec.ts
  libs/clients/rsk/company-registry/src/lib/company-registry-client.service.ts
  libs/clients/rsk/company-registry/src/lib/company-registry.module.ts
  libs/clients/rsk/company-registry/src/lib/types.ts
  workspace.json
Labels: automerge

#7336 fix(parental-leave): tax calculator with end date on first day of the…
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
Labels: automerge

#7294 chore: Updating client id references from island-is-1 to @island.is/web where it is used
  apps/application-system/form/src/auth.ts
  apps/auth-admin-web/i18n/locales/en.json
  apps/service-portal/src/auth.ts
  apps/services/auth-api/src/app/modules/case/e2e/auth-api.spec.ts
  libs/auth-api-lib/seeders/20210322163513-applications-resources.js
  libs/auth-api-lib/seeders/20210323153127-applications-redirecturis.js
  libs/auth-api-lib/seeders/20210324144627-applications-resources2.js
  libs/auth-api-lib/seeders/data/scope-endorsements-system-admin.ts
  libs/auth-api-lib/seeders/local/004-island.is.client.js
  libs/auth/react/README.md
Labels: automerge

#7305 fix(dpo): Security patch for document-provider api
  libs/api/domains/document-provider/src/lib/document-provider.resolver.ts
  libs/api/domains/document-provider/src/lib/document-provider.service.ts
Labels: automerge

#7284 feat(web): Landlæknir footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/index.ts
  apps/web/screens/queries/Organization.tsx
Labels: automerge

#7326 feat(web): Categories screen and smaller organization island.is footer
  apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.css.ts
  apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.tsx
  apps/web/components/Organization/OrganizationIslandFooter/index.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/layouts/main.tsx
  apps/web/pages/en/category/index.ts
  apps/web/pages/flokkur/index.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Category/Categories/Categories.tsx
  apps/web/screens/Category/Categories/index.ts
  apps/web/screens/Category/Category/Category.spec.tsx
  apps/web/screens/Category/Category/Category.tsx
  apps/web/screens/Category/Category/index.ts
  apps/web/screens/Organization/Home.tsx
  apps/web/screens/Organization/NewsItem.tsx
  apps/web/screens/Organization/NewsList.tsx
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/Organization/Services.tsx
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
  apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/Globe.tsx
Labels: automerge

#7338 fix(skilavottord): update regex
  apps/skilavottord/web/screens/DeregisterVehicle/Select.tsx
Labels: automerge

#7343 fix(driving-license-book): Mutual guard for employees and instructors
  libs/api/domains/driving-license-book/src/drivingLicenseBook.resolver.ts
  libs/api/domains/driving-license-book/src/guards/drivingInstructorOrEmployee.guard.ts
Labels: automerge

#7340 fix(j-s): Fix Police Case Number Prefix Autofill
  apps/judicial-system/web/src/routes/Prosecutor/SharedComponents/LokeCaseNumber/LokeCaseNumber.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
Labels: automerge

#7345 fix(j-s): Fix Defender View
  apps/judicial-system/api/src/app/modules/case/restrictedCase.resolver.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/restrictedCaseExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/restrictedCase.service.ts
  apps/judicial-system/web/src/components/FormProvider/restrictedCaseGql.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
Labels: automerge

#7351 feat(web): Sýslumenn chat panel change
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#7352 feat(web): Sýslumenn chat panel change (#7351)
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#7202 refactor(core): Refactor type dependencies for localisation and cms-translation
  apps/application-system/api/src/app/modules/application/tools/applicationTemplateValidation.service.ts
  apps/application-system/form/src/routes/Applications.tsx
  apps/judicial-system/backend/test/e2e.spec.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.ts
  libs/application/core/src/lib/dataProviderUtils.ts
  libs/application/core/src/lib/formUtils.ts
  libs/application/core/src/types/Form.ts
  libs/application/core/src/types/external.ts
  libs/application/core/src/validation/validators.ts
  libs/application/templates/accident-notification/src/utils/hasMissingDocuments.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/ui-components/src/utilities/handleServerError.ts
  libs/application/ui-shell/src/hooks/useApplicationNamespaces.ts
  libs/application/ui-shell/src/hooks/useApplicationTitle.ts
  libs/application/ui-shell/src/index.ts
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/validation/resolver.ts
  libs/cms-translations/src/lib/intl.service.ts
  libs/cms-translations/src/types.ts
  libs/localization/src/index.ts
  libs/localization/src/lib/types.ts
  libs/localization/src/lib/useLocale.tsx
  libs/service-portal/assets/src/utils/createUnits.ts
Labels: automerge

#7357 feat(web): Útlendingastofnun header change
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.tsx
Labels: automerge

#7359 fix(j-s): Fix Court Name in Prosecutor Email
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
Labels: automerge

#7362 fix(service-portal): Show parents if there is a parent response
  libs/service-portal/family/src/components/ChildView/ChildView.tsx
Labels: automerge

#7363 fix(general-fishing-license): hotfix remove logger
  libs/application/templates/general-fishing-license/src/dataProviders/generalFishingLicenseProvider.ts
Labels: automerge

#7365 fix(general-fisihing-license): fixing logger
  libs/application/templates/general-fishing-license/src/dataProviders/generalFishingLicenseProvider.ts
Labels: automerge

#7366 fix(service-portal): fixing vehicles graphql errors
  libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicles.ts
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Labels: automerge

#7368 fix(service-portal): fixing vehicles graphql errors (#7366)
  libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts
  libs/service-portal/vehicles/src/queries/getUsersVehicles.ts
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Labels: automerge

#7372 fix(j-s): Use court end time instead of ruling date where relevant
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
Labels: automerge

#7378 chore(j-s): Move info panel about how to resend a case to the overview step
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepOne/StepOneForm.tsx
Labels: automerge

#7376 feat(j-s): mobile stepper
  apps/judicial-system/web/pages/_document.tsx
  apps/judicial-system/web/src/components/PageHeader/PageHeader.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.css.ts
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  libs/island-ui/core/src/lib/FormStepper/FormStepper.tsx
  libs/island-ui/core/src/utils/responsiveProp.ts
Labels: automerge

#7348 feat(j-s): unsupported media type message on upload
  apps/judicial-system/web/messages/Core/caseFiles.ts
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.css.ts
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
Labels: automerge

#7379 fix(service-portal): vehicles wrong path + add logs
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
Labels: automerge

#7381 fix(service-portal): HOTFIX vehicles wrong path + add logs (#7379)
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
Labels: automerge

#7382 fix(data-protection-authority-complaint): icon and error message
  libs/application/templates/data-protection-complaint/src/fields/ReasonsForComplaint.tsx
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
Labels: automerge

#7367 docs(documents): Moving Pósthólfið documentation from static pdf to devland
  SUMMARY.md
  handbook/technical-overview/postholf/README.md
  handbook/technical-overview/postholf/assets/overview.png
  handbook/technical-overview/postholf/assets/sequence-diagram.png
  handbook/technical-overview/postholf/postholf-01-intro-and-overview.md
  handbook/technical-overview/postholf/postholf-02-interface-skjalatilkynning.md
  handbook/technical-overview/postholf/postholf-03-interface-skjalaveita.md
  handbook/technical-overview/postholf/postholf-04-sequence-diagram.md
  handbook/technical-overview/postholf/postholf-05-interfaces.md
Labels: automerge

#7374 feat(web): Útlendingastofnun footer color change
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.css.ts
Labels: automerge, deploy-feature

#7391 feat(j-s): Creates the Correct Type of Court Case for Admission to Facility
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
Labels: automerge

#7386 fix(j-s): Fix re-autofill functionality when changing decision
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
Labels: automerge

#7394 fix(parentalLeave): Validation updates on privatePension
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
Labels: automerge

#7397 feat(j-s): Updated Custody Notice
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7354 feat: update sqlite 5.0.2 > 5.0.8
  apps/api/esbuild.json
  apps/services/auth-admin-api/esbuild.json
  apps/services/auth-public-api/esbuild.json
  apps/services/personal-representative-public/esbuild.json
  apps/services/personal-representative/esbuild.json
  package.json
  yarn.lock
Labels: automerge

#7405 fix(core): Fixing timeout bug in enhancedFetch. (#7392)
  libs/clients/middlewares/src/lib/createEnhancedFetch.ts
  libs/clients/middlewares/src/lib/e2e/enhancedFetch.spec.ts
Labels: automerge

#7387 feat(web): Sýslumenn footer links to support page
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx
  apps/web/context/GlobalContext/GlobalContext.tsx
  apps/web/layouts/main.tsx
Labels: automerge, deploy-feature

#7402 fix(j-s): Fix Client Build
  apps/judicial-system/web/tsconfig.app.json
  apps/judicial-system/web/tsconfig.json
Labels: automerge

#7400 feat(web): Web footer links to support page
  apps/web/layouts/main.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
Labels: automerge

#7406 feat(web): Hotfix - Sýslumenn footer links to support page
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx
  apps/web/context/GlobalContext/GlobalContext.tsx
  apps/web/layouts/main.tsx
Labels: automerge

#7408 feat(web): Hotfix - Web footer links to support page
  apps/web/layouts/main.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
Labels: automerge

#7383 chore(j-s): Responsive InfoCard component
  apps/judicial-system/web/src/components/FormContentContainer/FormContentContainer.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.css.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/Logo/Logo.css.ts
  apps/judicial-system/web/src/components/Logo/Logo.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.css.ts
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  libs/island-ui/core/src/lib/Grid/GridColumn/GridColumn.css.ts
  libs/island-ui/core/src/lib/Grid/GridContainer/GridContainer.css.ts
  libs/island-ui/theme/src/lib/theme.ts
Labels: automerge

#7384 refactor(service-portal): Finance schedule
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/finance/src/lib/models/debtStatus.model.ts
  libs/clients/finance/src/lib/FinanceClientService.ts
  libs/service-portal/core/src/components/ExpandableTable/Header.tsx
  libs/service-portal/finance-schedule/src/components/FinanceScheduleDetailTable/FinanceScheduleDetailTable.tsx
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTableRow.tsx
  libs/service-portal/finance-schedule/src/index.ts
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#7388 chore(web): Updated Sýslumenn's email list
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#7409 feat(fa): Change readyForProduction flag to trur
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
Labels: automerge

#7353 feat(fa): Setup xRoad connection from the application system to the finacnial-aid-backend
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/municipalities-financial-aid/src/apis.ts
  libs/clients/municipalities-financial-aid/src/municipalitiesFinancialAid.config.ts
Labels: automerge

#7413 chore(j-s): Make defender page responsive
  apps/judicial-system/web/src/components/FormFooter/FormFooter.css.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/FormFooter/index.ts
  apps/judicial-system/web/src/components/Header/Header.css.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/InfoBox/InfoBox.css.ts
  apps/judicial-system/web/src/components/InfoBox/InfoBox.tsx
Labels: automerge

#7411 chore(web): Hotfix - Updated Sýslumenn's email list (#7388)
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#7410 chore(web): Syslumenn email refactor
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#7415 feat(web): Service web form checkbox and template update
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
Labels: automerge

#7421 fix(parental leave): filter private pension fund
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#7412 infra(fix): Append $GITHUB_RUN_ATTEMPT to E2E_BUILD_ID inside e2e scope
  .github/workflows/pullrequest.yml
Labels: automerge

#7419 fix(core): feature flag bugs
  package.json
  yarn.lock
Labels: automerge

#7425 fix(service-portal): vehicles resolver nullable
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Labels: automerge

#7396 refactor: replace ed card with action card + translations
  libs/service-portal/education-career/src/screens/EducationCareer/components/CareerCards/CareerCards.css.ts
  libs/service-portal/education-career/src/screens/EducationCareer/components/CareerCards/CareerCards.tsx
  libs/service-portal/education-degree/src/screens/EducationDegree/components/DegreeCards/DegreeCards.tsx
  libs/service-portal/education-license/src/screens/EducationLicense/components/LicenseCards/LicenseCards.tsx
Labels: automerge

#7439 fix(parental leave): submit failure on page refresh
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
Labels: automerge

#7440 fix(parental-leave): self employed and attachment
  libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#7373 chore(web): Stepper - removal of unused fields
  apps/web/components/Stepper/Stepper.css.ts
  apps/web/components/Stepper/Stepper.tsx
  apps/web/components/Stepper/Stepper/Stepper.css.ts
  apps/web/components/Stepper/Stepper/Stepper.tsx
  apps/web/components/Stepper/Stepper/index.ts
  apps/web/components/Stepper/StepperHelper/StepperHelper.css.ts
  apps/web/components/Stepper/StepperHelper/StepperHelper.tsx
  apps/web/components/Stepper/StepperHelper/index.ts
  apps/web/components/Stepper/index.ts
  apps/web/components/Stepper/utils.ts
  apps/web/components/real.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/queries/Article.ts
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/models/step.model.ts
Labels: automerge

#7424 fix(service-portal): remove overflow hidden on container
  apps/service-portal/src/components/Layout/Layout.tsx
Labels: automerge

#7431 feat(j-s): show message when filetype is not supported
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/Core/caseFilesAccordion.ts
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/UploadStateMessage.tsx
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx
Labels: automerge

#7435 fix(service-portal): fetch on click instead load
  libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx
Labels: automerge, deploy-feature

#7441 fix(service-portal): Add padding to grid layout container
  apps/service-portal/src/components/Layout/Layout.css.ts
  apps/service-portal/src/components/Layout/Layout.tsx
Labels: automerge

#7443 fix(j-s): fix demands for restriction cases
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
  apps/judicial-system/web/src/utils/formHelper.spec.ts
  apps/judicial-system/web/src/utils/formHelper.ts
Labels: automerge

#7385 feat(financial-statements-inao): Dataverse connection
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/financial-statements-inao/src/lib/client/dataverseClient.config.ts
  libs/api/domains/financial-statements-inao/src/lib/client/dataverseClient.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.module.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/api/domains/financial-statements-inao/src/lib/models/clientType.model.ts
  libs/clients/middlewares/README.md
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/clients/middlewares/src/lib/withAutoAuth.ts
Labels: automerge

#7375 chore(testing): Improve code coverage by ignoring more
  jest.preset.js
Labels: automerge, deploy-feature

#7448 fix(parental-leave): otherParent's name does not show in Review page
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#7404 feat(Application-system): custom data provider error title and summary
  libs/application/core/src/lib/dataProviderUtils.spec.ts
  libs/application/core/src/lib/dataProviderUtils.ts
  libs/application/core/src/types/DataProviderResult.ts
  libs/application/templates/public-debt-payment-plan/src/dataProviders/paymentPlanPrerequisites.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#7455 fix(doc): Removing wrong statement
  handbook/repository/workspace-settings.md
Labels: automerge

#7344 fix(ci): feature deployment comments fix
  .github/actions/update-comment.js
  .github/workflows/push.yml
Labels: automerge, deploy-feature

#7456 fix(fa): Update tax url
  libs/clients/rsk/personal-tax-return/src/lib/personalTaxReturn.config.ts
Labels: automerge

#7422 feat(j-s): Expulsion From Home
  apps/judicial-system/backend/migrations/20220513084054-update-case.js
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/courtRecord.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/DefendantForm.tsx
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/case.spec.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#7423 feat(j-s): Document Submitted by Court
  apps/judicial-system/web/messages/Core/courtDocuments.ts
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/components/Header/Header.tsx
  libs/judicial-system/types/src/lib/courtDocument.ts
Labels: automerge

#7436 feat(j-s): Warn users when they select a lawyer that is not in the lawyer registry
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
  apps/judicial-system/web/messages/Core/defenderInfo.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/ConfirmationForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#7437 fix(j-s): Fix Custody Restrictions
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepThree.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThreeForm.tsx
Labels: automerge

#7445 fix(j-s): Fix End of Session Bookings
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
Labels: automerge

#7447 fix(j-s): Resend Info Panel
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/overview.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.css.ts
Labels: automerge

#7464 fix(j-s): Add exclude with only node_modules for tsconfig spec.
  apps/judicial-system/web/tsconfig.spec.json
Labels: automerge

#7429 chore(j-s): Posts Error Events on Signing Failure
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/files/file.service.spec.ts
  apps/application-system/api/src/app/modules/application/files/file.service.ts
  apps/application-system/api/src/environments/environment.interface.ts
  apps/application-system/api/src/environments/environment.ts
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/environments/environment.ts
  libs/dokobit-signing/README.md
  libs/dokobit-signing/src/index.ts
  libs/dokobit-signing/src/lib/signing.config.ts
  libs/dokobit-signing/src/lib/signing.module.ts
  libs/dokobit-signing/src/lib/signing.service.spec.ts
  libs/dokobit-signing/src/lib/signing.service.ts
Labels: automerge

#7460 feat(web): Mannaudstorg header and footer change on service web
  apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/MannaudstorgFooter.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
Labels: automerge, deploy-feature

#7463 fix(web): Use flatten from lodash instead of NestJS
  apps/web/components/Organization/Slice/TimelineSlice/TimelineSlice.tsx
Labels: automerge

#7469 feat(web): Hotfix - mannaudstorg service web header change
  apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/MannaudstorgFooter.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Mannaudstorg/Mannaudstorg.css.ts
Labels: automerge

#7407 feat(j-s): confirm courtDate on continue button press
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepThree.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/hearingArrangements.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangementsForm.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#7470 fix(j-s): Fix Missing Upload Checkmark
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
Labels: automerge

#7444 chore(j-s): Cleanup on the Cases page
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/Logo/Logo.css.ts
  apps/judicial-system/web/src/components/Logo/Logo.spec.tsx
  apps/judicial-system/web/src/components/Logo/Logo.tsx
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemandsForm.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/TableSkeleton.tsx
  libs/judicial-system/formatters/src/lib/formatters.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#7449 refactor(core): Refactor withHealthchecks into infra-next-server
  apps/air-discount-scheme/web/next-modules/withHealthcheckConfig.js
  apps/air-discount-scheme/web/next.config.js
  apps/air-discount-scheme/web/pages/_app.tsx
  apps/air-discount-scheme/web/server.ts
  apps/air-discount-scheme/web/utils/Healthchecks/withHealthchecks.tsx
  apps/auth-admin-web/next-modules/withHealthcheckConfig.js
  apps/auth-admin-web/next.config.js
  apps/auth-admin-web/pages/_app.tsx
  apps/auth-admin-web/server.ts
  apps/financial-aid/web-osk/next-modules/withHealthcheckConfig.js
  apps/financial-aid/web-osk/next.config.js
  apps/financial-aid/web-osk/pages/_app.tsx
  apps/financial-aid/web-osk/server.ts
  apps/financial-aid/web-osk/units/Healthchecks/withHealthchecks.tsx
  apps/financial-aid/web-veita/next-modules/withHealthcheckConfig.js
  apps/financial-aid/web-veita/next.config.js
  apps/financial-aid/web-veita/pages/_app.tsx
  apps/financial-aid/web-veita/server.ts
  apps/financial-aid/web-veita/units/Healthchecks/withHealthchecks.tsx
  apps/judicial-system/web/next-modules/withHealthcheckConfig.js
  apps/judicial-system/web/next.config.js
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/server.ts
  apps/judicial-system/web/units/Healthchecks/withHealthchecks.tsx
  apps/reference-next-app/graphql/client.ts
  apps/reference-next-app/next.config.js
  apps/reference-next-app/pages/_app.tsx
  apps/reference-next-app/server.ts
  apps/skilavottord/web/next-modules/.gitkeep
  apps/skilavottord/web/next-modules/withHealthcheckConfig.js
  apps/skilavottord/web/next.config.js
  apps/skilavottord/web/pages/_app.tsx
  apps/skilavottord/web/server.ts
  apps/skilavottord/web/units/Healthchecks/withHealthchecks.tsx
  apps/web/next-modules/withHealthcheckConfig.js
  apps/web/next.config.js
  apps/web/pages/[slug]/index.ts
  apps/web/server.ts
  apps/web/units/Healthchecks/withHealthchecks.tsx
  libs/infra-next-server/src/lib/bootstrap.ts
  libs/infra-next-server/src/lib/health.ts
  workspace.json
Labels: automerge, deploy-feature

#7467 feat(web): Support Category description added to the service web form
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
Labels: automerge

#7475 feat(web): Mannaudstorg - service web search page now only searches mannaudstorg related content
  apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
Labels: automerge, deploy-feature

#7477 docs(application-system): Readme for orginisations reqeusts
  SUMMARY.md
  apps/application-system/README.md
  handbook/misc/application-system-org-requests.md
Labels: automerge

#7478 fix(j-s): fix court date being confirmed automatically
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangementsForm.tsx
Labels: automerge

#7479 docs(application-system): fixes to readme
  handbook/misc/application-system-org-requests.md
Labels: automerge

#7462 feat(web): Watson chat panel translations read from CMS
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge, deploy-feature

#7472 feat(service-portal): Finance schedule compressed
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTable.tsx
  libs/service-portal/finance-schedule/src/components/FinanceScheduleTable/FinanceScheduleTableRowCompressed.tsx
Labels: automerge

#7446 fix(driving-school/instructor): Minor fixes
  libs/application/templates/driving-instructor-registrations/src/dataProviders/TeachingRightsProvider.ts
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/forms/instructorRegistrations.ts
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
  libs/application/templates/driving-school-confirmation/src/dataProviders/EmployeeProvider.ts
  libs/application/templates/driving-school-confirmation/src/fields/ConfirmationDate/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/SchoolConfirmed/index.tsx
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
  libs/application/templates/driving-school-confirmation/src/lib/messages.ts
Labels: automerge

#7481 fix(parental-leave): fix other parent could not choose personal discount
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#7482 fix(driving-school-confirmation): Screen Description fix
  libs/application/templates/driving-school-confirmation/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/driving-school-confirmation/src/forms/drivingSchoolConfirmation.ts
  libs/application/templates/driving-school-confirmation/src/lib/messages.ts
Labels: automerge

#7484 test(j-s): remove it.only mark for e2e test
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
Labels: automerge

#7485 feat(web): Service web, optional search indexing
  apps/web/components/HeadWithSocialSharing/HeadWithSocialSharing.tsx
  apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
Labels: automerge

#7486 feat(web): Organizations page - CMS can change what organizations are shown
  apps/web/screens/Organizations/Organizations.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organization.model.ts
Labels: automerge

#7466 feat(fa): Status page + file upload page
  apps/financial-aid/backend/src/app/guards/application.guard.ts
  apps/financial-aid/backend/src/app/modules/file/file.controller.ts
  apps/financial-aid/backend/src/app/modules/file/file.service.ts
  apps/financial-aid/backend/src/app/modules/file/models/createFiles.model.ts
  apps/financial-aid/backend/src/app/modules/file/test/fileControllerGuards.spec.ts
  libs/api/domains/municipalities-financial-aid/src/lib/dto/application.input.ts
  libs/api/domains/municipalities-financial-aid/src/lib/dto/createFiles.input.ts
  libs/api/domains/municipalities-financial-aid/src/lib/dto/getSignedUrlForId.input.ts
  libs/api/domains/municipalities-financial-aid/src/lib/dto/index.ts
  libs/api/domains/municipalities-financial-aid/src/lib/dto/updateApplication.input.ts
  libs/api/domains/municipalities-financial-aid/src/lib/models/createFiles.model.ts
  libs/api/domains/municipalities-financial-aid/src/lib/models/index.ts
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.resolver.ts
  libs/api/domains/municipalities-financial-aid/src/lib/municipalitiesFinancialAid.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts
  libs/application/templates/financial-aid/src/dataProviders/VeitaProvider.ts
  libs/application/templates/financial-aid/src/fields/Files/Files.tsx
  libs/application/templates/financial-aid/src/fields/MissingFiles/FileList/FileList.css.ts
  libs/application/templates/financial-aid/src/fields/MissingFiles/FileList/FileList.tsx
  libs/application/templates/financial-aid/src/fields/MissingFiles/MissingFiles.tsx
  libs/application/templates/financial-aid/src/fields/MissingFiles/MissingFilesConfirmation/MissingFilesConfirmation.tsx
  libs/application/templates/financial-aid/src/fields/Status/AidAmount/AidAmount.tsx
  libs/application/templates/financial-aid/src/fields/Status/ApplicantStatus.tsx
  libs/application/templates/financial-aid/src/fields/Status/Estimation/Estimation.tsx
  libs/application/templates/financial-aid/src/fields/Status/Header/Header.tsx
  libs/application/templates/financial-aid/src/fields/Status/MissingFilesCard/MissingFilesCard.tsx
  libs/application/templates/financial-aid/src/fields/Status/MoreActions/MoreActions.tsx
  libs/application/templates/financial-aid/src/fields/Status/RejectionMessage/RejectionMessage.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseAlert/SpouseAlert.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseApproved/SpouseApproved.tsx
  libs/application/templates/financial-aid/src/fields/Status/SpouseStatus.tsx
  libs/application/templates/financial-aid/src/fields/Status/Status.css.ts
  libs/application/templates/financial-aid/src/fields/Status/Timeline/Timeline.css.ts
  libs/application/templates/financial-aid/src/fields/Status/Timeline/Timeline.tsx
  libs/application/templates/financial-aid/src/fields/Status/index.ts
  libs/application/templates/financial-aid/src/fields/index.ts
  libs/application/templates/financial-aid/src/forms/ApplicantSubmitted.ts
  libs/application/templates/financial-aid/src/forms/SpouseSubmitted.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/constants.ts
  libs/application/templates/financial-aid/src/lib/formatters.ts
  libs/application/templates/financial-aid/src/lib/hooks/useApplication.ts
  libs/application/templates/financial-aid/src/lib/hooks/useFileUpload.ts
  libs/application/templates/financial-aid/src/lib/messages/index.ts
  libs/application/templates/financial-aid/src/lib/messages/missingFiles.ts
  libs/application/templates/financial-aid/src/lib/messages/status.ts
  libs/application/templates/financial-aid/src/lib/types.ts
  libs/application/templates/financial-aid/src/lib/utils.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#7453 feat(ads): Admin interface user lookup
  apps/air-discount-scheme/api/src/app/modules/flightLeg/dto/flightLeg.input.ts
  apps/air-discount-scheme/backend/seeders/20211108100835-development.js
  apps/air-discount-scheme/backend/src/app/modules/flight/flight.service.ts
  apps/air-discount-scheme/web/screens/Admin/Admin.tsx
  apps/air-discount-scheme/web/screens/Admin/components/Filters/Filters.tsx
  libs/air-discount-scheme/types/src/lib/flight.ts
Labels: automerge

#7483 feat(web): Askur chat bot on frontpage
  apps/web/components/ChatPanel/index.ts
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Home/Home.tsx
  apps/web/screens/Home/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge, deploy-feature

#7487 fix(service-portal): Update dynamic route handling in service-portal
  apps/service-portal/src/hooks/useNavigation/useNavigation.ts
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  apps/service-portal/src/screens/Modules/Modules.tsx
  apps/service-portal/src/store/actions.ts
  apps/service-portal/src/store/store.ts
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/core/src/screens/DynamicWrapper/DynamicWrapper.tsx
  libs/service-portal/finance-schedule/src/index.ts
  libs/service-portal/finance-schedule/src/lib/service-portal-finance-schedule.spec.tsx
  libs/service-portal/finance-schedule/src/lib/service-portal-finance-schedule.tsx
  libs/service-portal/finance/src/index.ts
  libs/service-portal/finance/src/lib/service-portal-finance.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/queries/getFinanceTapsControl.ts
Labels: automerge, deploy-feature

#7497 fix(personal-representative): Minor fix to openapidoc
  apps/services/personal-representative/src/app/modules/rightTypes/rightTypes.controller.ts
Labels: automerge

#7494 fix(j-s): File Status
  apps/judicial-system/web/messages/Core/caseFiles.ts
  apps/judicial-system/web/messages/Core/caseFilesAccordion.ts
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/OverviewForm.tsx
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#7493 feat(financial-statements-inao): Add ids and some refactoring
  libs/api/domains/financial-statements-inao/src/lib/client/dataverseClient.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.resolver.ts
  libs/api/domains/financial-statements-inao/src/lib/financialStatementsInao.service.ts
  libs/api/domains/financial-statements-inao/src/lib/models/clientType.model.ts
  libs/api/domains/financial-statements-inao/src/lib/models/election.model.ts
Labels: automerge

#7489 feat(general-fishing-license): modal
  .github/CODEOWNERS
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-ship.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-unfulfilled-license.model.ts
  libs/api/domains/fishing-license/src/lib/fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipInformation/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/ShipSelectionAlertModal.css.ts
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/UnfulfilledLicenseReasons.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/index.ts
  libs/application/templates/general-fishing-license/src/graphql/queries.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicense.ts
  libs/application/templates/general-fishing-license/src/lib/messages/shipSelection.ts
  libs/clients/fishing-license/src/clientConfig.json
Labels: automerge

#7498 feat(j-s): Email Error Event
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#7506 fix(j-s): Move viewport meta tag from _document to _app
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/pages/_document.tsx
Labels: automerge

#7473 feat(j-s): modifiy ruling
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20220518114634-update-case.js
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/courtUpload.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web-e2e/cypress.json
  apps/judicial-system/web-e2e/src/fixtures/requestRulingSignatureMutationResponse.json
  apps/judicial-system/web-e2e/src/fixtures/rulingSignatureConfirmationResponse.json
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/modifyRuling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/confirmation.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/courtRecord.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/modifyRuling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/receptionAndAssignment.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/ruling.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepFour.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepThree.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/stepTwo.spec.ts
  apps/judicial-system/web-e2e/src/integration/Shared/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web-e2e/src/support/index.d.ts
  apps/judicial-system/web-e2e/src/support/index.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/ruling.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/ruling.ts
  apps/judicial-system/web/pages/domur/rannsoknarheimild/urskurdur/leidretta/[id].ts
  apps/judicial-system/web/pages/domur/urskurdur/leidretta/[id].ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/PageLayout/utils/index.spec.tsx
  apps/judicial-system/web/src/components/SignedDocument/SignedDocument.css.ts
  apps/judicial-system/web/src/components/SignedDocument/SignedDocument.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/caseGql.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverviewForm.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#7496 feat(service-portal): vehicle additions
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/clients/vehicles/src/lib/vehiclesClient.service.ts
  libs/service-portal/vehicles/src/components/DetailTable/CoOwnerInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/Column.tsx
  libs/service-portal/vehicles/src/components/DetailTable/InspectionInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OperatorInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OwnerInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/OwnersTable.tsx
  libs/service-portal/vehicles/src/components/DetailTable/RegistrationInfoItem.tsx
  libs/service-portal/vehicles/src/components/DetailTable/TechnicalInfoItem.tsx
  libs/service-portal/vehicles/src/queries/getUsersVehicleDetail.ts
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  workspace.json
Labels: automerge

#7508 fix(parental leave): remove personalAllowance(FromSpouse) if the user does not want to use it
  libs/application/templates/parental-leave/src/fields/SpouseUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/fields/personalUseAsMuchAsPossible/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#7480 fix(health-insurance): Remove error object from response
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
Labels: automerge

#7512 fix(health-insurance): remove error object
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
Labels: automerge

#7513 chore(application-system): Replace default error message on dataprovider fail submit
  libs/application/core/src/lib/messages.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#7515 chore(application-system): Replace error in dataprovider
  libs/application/core/src/lib/messages.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#7516 feat(fa): Add project to robin hood codeowner list
  .github/CODEOWNERS
Labels: automerge

#7514 fix(fa): Check for existing application
  libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts
  libs/application/templates/financial-aid/src/fields/MissingFiles/MissingFilesConfirmation/MissingFilesConfirmation.tsx
  libs/application/templates/financial-aid/src/fields/Status/AidAmount/AidAmount.tsx
  libs/application/templates/financial-aid/src/fields/Status/ApplicantStatus.tsx
  libs/application/templates/financial-aid/src/fields/Status/Estimation/Estimation.tsx
  libs/application/templates/financial-aid/src/fields/Status/index.ts
  libs/application/templates/financial-aid/src/forms/PrerequisitesSpouse.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/hooks/useApplication.ts
  libs/application/templates/financial-aid/src/lib/utils.ts
Labels: automerge

#7521 fix(service-portal): Finance schedule grid
  apps/service-portal/src/screens/Modules/Modules.tsx
  libs/service-portal/finance-schedule/src/screens/FinanceSchedule/FinanceSchedule.tsx
Labels: automerge

#7519 chore(service-portal): Remove company feature-flag + deletevalue update
  apps/service-portal/src/hooks/useModules/useModules.ts
  apps/service-portal/src/hooks/useRoutes/useRoutes.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
Labels: automerge
