Repository island-is/island.is, pull requests merged in 2023-01, with the labels that each got.

#9439 refactor(admin-portal): Remove dependency on user profile scope.
  apps/portals/admin/src/app/App.tsx
  apps/portals/admin/src/auth.ts
Labels: automerge

#9458 chore(j-s): Show defenders on closed indictment info card
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#9454 chore(j-s): Fix console warning
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
Labels: automerge

#9462 chore(j-s): Refactor useDep hook
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFour/StepFour.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepThree/StepThree.tsx
  apps/judicial-system/web/src/utils/hooks/useDeb/index.tsx
Labels: automerge

#9414 fix(j-s): LOKE upload fix
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/caseFiles.ts
  apps/judicial-system/web/pages/krafa/rannsoknargogn/[id].ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/rannsoknargogn/[id].ts
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/StepFive/StepFive.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
  apps/judicial-system/web/src/utils/hooks/useS3UploadV2/useS3UploadV2.ts
Labels: automerge

#9463 chore(j-s): Refactoring (renaming)
  apps/judicial-system/web/pages/krafa/domkrofur-og-lagaakvaedi/[id].ts
  apps/judicial-system/web/pages/krafa/greinargerd/[id].ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#9473 fix(delegation-api): Add admin audience
  apps/services/auth/delegation-api/src/environments/environment.ts
Labels: automerge

#9475 fix(delegation-api): Fix audience regression
  apps/services/auth/delegation-api/src/environments/environment.ts
Labels: automerge

#9461 chore(docs): Change link in technical direction documentation
  handbook/technical-overview/technical-direction.md
Labels: automerge

#9472 fix(parental leave): percentage end date issue (#9469)
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/index.ts
Labels: automerge

#9453 chore(j-s): Improve loading experience on cases screen
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/TableSkeleton.tsx
Labels: automerge

#9474 feat(web): Add close button to watson chat panel
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
Labels: automerge

#9479 fix(fa): Updating personal tax allowance
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#9460 chore(j-s): Remove function handleRemoveFromS3
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/deleteCaseFileRolesRules.spec.ts
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
Labels: automerge

#9404 fix(driving-licence): Inconsistent UI state
  apps/system-e2e/global.d.ts
  apps/system-e2e/src/addons.ts
  apps/system-e2e/src/playwright.config.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/tests/application-system/acceptance/driving-licence.spec.ts
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
Labels: automerge

#9488 fix(service-portal): vehicle history type error
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.type.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
Labels: automerge

#9477 feat(eslint): Allow fake national IDs
  eslint-local-rules.js
Labels: automerge

#9464 feat(transport authority applications): Anonymity in the vehicle registry
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/anonymity-in-vehicle-registry/anonymity-in-vehicle-registry.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/anonymity-in-vehicle-registry/anonymity-in-vehicle-registry.service.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/assets/Jobs.tsx
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/dataProviders/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/fields/ConfirmationField/index.tsx
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/fields/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/AnonymityInVehicleRegistryForm.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/AnonymityInVehicleRegistryForm/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/AnonymityInVehicleRegistryForm/informationSection.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/AnonymityInVehicleRegistryForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/AnonymityInVehicleRegistryTemplate.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/application.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/error.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/information.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/tsconfig.json
  libs/clients/transport-authority/vehicle-infolocks/.babelrc
  libs/clients/transport-authority/vehicle-infolocks/.eslintrc.json
  libs/clients/transport-authority/vehicle-infolocks/README.md
  libs/clients/transport-authority/vehicle-infolocks/jest.config.js
  libs/clients/transport-authority/vehicle-infolocks/project.json
  libs/clients/transport-authority/vehicle-infolocks/src/clientConfig.json
  libs/clients/transport-authority/vehicle-infolocks/src/index.ts
  libs/clients/transport-authority/vehicle-infolocks/src/lib/apiConfiguration.ts
  libs/clients/transport-authority/vehicle-infolocks/src/lib/vehicleInfolocksClient.config.ts
  libs/clients/transport-authority/vehicle-infolocks/src/lib/vehicleInfolocksClient.module.ts
  libs/clients/transport-authority/vehicle-infolocks/src/lib/vehicleInfolocksClient.service.ts
  libs/clients/transport-authority/vehicle-infolocks/src/lib/vehicleInfolocksClient.types.ts
  libs/clients/transport-authority/vehicle-infolocks/tsconfig.json
  libs/clients/transport-authority/vehicle-infolocks/tsconfig.lib.json
  libs/clients/transport-authority/vehicle-infolocks/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#9466 feat(transport authority applications): Order vehicle registration certificate
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-registration-certificate/order-vehicle-registration-certificate.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-registration-certificate/order-vehicle-registration-certificate.service.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/assets/Company.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/assets/Jobs.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/ConfirmationField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/MainOwner.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/Payment/PaymentChargeOverview.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/Payment/PaymentPending.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/Payment/PaymentUrlNotFound.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/Approved.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/pickVehicleSubSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/paymentSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/Payment.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/constants.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/application.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/error.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/payment.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/types/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/utils/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/tsconfig.json
  libs/clients/transport-authority/vehicle-printing/.babelrc
  libs/clients/transport-authority/vehicle-printing/.eslintrc.json
  libs/clients/transport-authority/vehicle-printing/README.md
  libs/clients/transport-authority/vehicle-printing/jest.config.js
  libs/clients/transport-authority/vehicle-printing/project.json
  libs/clients/transport-authority/vehicle-printing/src/clientConfig.json
  libs/clients/transport-authority/vehicle-printing/src/index.ts
  libs/clients/transport-authority/vehicle-printing/src/lib/apiConfiguration.ts
  libs/clients/transport-authority/vehicle-printing/src/lib/vehiclePrintingClient.config.ts
  libs/clients/transport-authority/vehicle-printing/src/lib/vehiclePrintingClient.module.ts
  libs/clients/transport-authority/vehicle-printing/src/lib/vehiclePrintingClient.service.ts
  libs/clients/transport-authority/vehicle-printing/tsconfig.json
  libs/clients/transport-authority/vehicle-printing/tsconfig.lib.json
  libs/clients/transport-authority/vehicle-printing/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#9490 fix(parental-leave): don't stop process when send sms got error
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#9492 fix(service-portal): HOTFIX - vehicle history type error (#9488)
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.type.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
Labels: automerge

#9495 fix(financial-aid): Hotfix tax calculation
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#9494 feat(transport-authority): Add missing xroad config for Anonymity application
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#9493 fix(web): Prevent 500 error if slicedropdown is selected and no slices are provided
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
Labels: automerge

#9500 fix(service-portal): finance error string
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
Labels: automerge

#9497 fix(j-s): State error when uploading
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
Labels: automerge

#9382 feat(service-portal): smart solutions refactor
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.types.ts
  libs/clients/smartsolutions/src/lib/utils.ts
Labels: automerge

#9496 fix(driving-license-application): external data id needed
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
Labels: automerge

#9503 fix(transport-authority-transfer-of-vehicle-ownership): Fix the way we get vehicle locks
  libs/api/domains/transport-authority/src/lib/graphql/models/ownerChangeValidation.model.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getCurrentVehicles.model.ts
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
  libs/api/domains/vehicles/src/utils/basicVehicleInformationMapper.ts
  libs/api/domains/vehicles/src/utils/updatelocks.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ValidationErrorMessages/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/applicationCheck.ts
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.types.ts
Labels: automerge

#9470 feat(service-portal): filtered health documents
  libs/api/domains/documents/src/lib/document.service.ts
  libs/api/domains/documents/src/lib/dto/getDocumentListInput.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/graphql/src/hooks/documents/useListDocuments.ts
Labels: automerge, deploy-feature

#9487 fix(j-s): deliver court records to court through right endpoint
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCourtRecordToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#9482 fix(j-s): only send one email per defendant
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendDefenderAssignedNotifications.spec.ts
Labels: automerge

#9483 feat(j-s): Alter travel ban duration
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/messages/Core/caseFiles.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/SigningModal/SigningModal.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#9491 chore(j-s): Court Authentication
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/receptionAndAssignment.spec.ts
  libs/judicial-system/court-client/src/clientConfig.json
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#9485 fix(j-s): Police Case Number
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
Labels: automerge

#9489 chore(j-s): Slack Spamming
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
Labels: automerge

#9509 fix(driving-instructor-registrations): modal tweaks for mobile
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/style.css.ts
Labels: automerge

#9511 fix(transport-authority-transfer-of-vehicle-ownership): Use correct errorNo for vehicle locks
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts
Labels: automerge

#9507 fix(air-discount-scheme): Return legacy gender value for external contacts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.controller.ts
  libs/air-discount-scheme/types/src/lib/user.ts
Labels: automerge

#9476 test(Portals): Tests for filter navigation tree method
  libs/portals/core/src/hooks/useNavigation.ts
  libs/portals/core/src/utils/filterNavigationTree/filterNavigationTree.spec.ts
  libs/portals/core/src/utils/filterNavigationTree/filterNavigationTree.ts
  libs/portals/core/src/utils/filterNavigationTree/test-data.ts
Labels: automerge

#9512 fix(ads): Hotfix ads legacy gender
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.controller.ts
  libs/air-discount-scheme/types/src/lib/user.ts
Labels: automerge

#9430 chore(user-profile): More specific handle error logging for userprofile domain
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
Labels: automerge

#9517 feat(service-portal): assets - add missing translated text
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/utils/createUnits.ts
Labels: automerge

#9516 fix(driving-instructor-registrations): table tweaks for mobile
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/style.css.ts
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
Labels: automerge

#9510 chore(j-s): Heads-up Notifications
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/message-handler/src/app/app.module.ts
  apps/judicial-system/message-handler/src/app/caseDelivery.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/deliverCase.spec.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#9232 fix(operating-license): Fixes
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/types/application.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/utils.ts
  libs/application/templates/operating-license/src/dataProviders/index.ts
  libs/application/templates/operating-license/src/fields/PropertyOverviewRepeater/index.tsx
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/operating-license/src/forms/draft/draft.ts
  libs/application/templates/operating-license/src/forms/draft/fakeDataSection.ts
  libs/application/templates/operating-license/src/forms/draft/index.ts
  libs/application/templates/operating-license/src/forms/draft/sectionApplicationInfo.ts
  libs/application/templates/operating-license/src/forms/draft/sectionOverview.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOpeningHours.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOtherInfo.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionPropertyRepeater.ts
  libs/application/templates/operating-license/src/graphql/index.ts
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/application/templates/operating-license/src/lib/constants.ts
  libs/application/templates/operating-license/src/lib/dataSchema.ts
  libs/application/templates/operating-license/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/operating-license/src/lib/messages.ts
  libs/application/templates/operating-license/src/lib/utils.ts
  libs/application/templates/operating-license/src/types.ts
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#9498 fix(delegations): Auth delegations outgoing query fixes
  apps/portals/admin/src/graphql.ts
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
  libs/portals/shared-modules/delegations/src/hooks/useDomains/useDomains.ts
Labels: automerge

#9521 fix(driving-instructor-registrations): ui tweaks
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
Labels: automerge

#9504 chore(j-s): File upload extension restrictions
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  libs/island-ui/core/types.ts
  package.json
  yarn.lock
Labels: automerge

#9481 refactor(service-portal): Remove delegations feature flags and delete old project
  apps/service-portal/src/lib/masterNavigation.ts
  apps/service-portal/src/lib/modules.ts
  apps/services/auth/delegation-api/src/app/delegations/me-delegations.controller.ts
  apps/services/auth/delegation-api/src/app/domains/domains.controller.ts
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/loaders/apiScope.loader.ts
  libs/api/domains/auth/src/lib/resolvers/apiScope.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/customDelegation.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/delegation.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/domain.resolver.ts
  libs/api/domains/auth/src/lib/services-v1/apiScope.service.ts
  libs/api/domains/auth/src/lib/services-v1/meDelegations.service.ts
  libs/api/domains/auth/src/lib/services-v2/apiScope.service.ts
  libs/api/domains/auth/src/lib/services-v2/meDelegations.service.ts
  libs/api/domains/auth/src/lib/services/apiScope.service.ts
  libs/api/domains/auth/src/lib/services/constants.ts
  libs/api/domains/auth/src/lib/services/meDelegations.service.ts
  libs/api/domains/auth/src/lib/services/types.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/feature-flags/src/lib/features.ts
  libs/portals/shared-modules/delegations/src/module.tsx
  libs/portals/shared-modules/delegations/src/screens/AccessControl.tsx
  libs/service-portal/settings/access-control/.babelrc
  libs/service-portal/settings/access-control/.eslintrc.json
  libs/service-portal/settings/access-control/README.md
  libs/service-portal/settings/access-control/babel-jest.config.json
  libs/service-portal/settings/access-control/jest.config.js
  libs/service-portal/settings/access-control/project.json
  libs/service-portal/settings/access-control/src/components/AccessCard/AccessCard.tsx
  libs/service-portal/settings/access-control/src/components/AccessCard/index.ts
  libs/service-portal/settings/access-control/src/components/AccessItem/AccessItem.css.ts
  libs/service-portal/settings/access-control/src/components/AccessItem/AccessItem.tsx
  libs/service-portal/settings/access-control/src/components/AccessItem/index.ts
  libs/service-portal/settings/access-control/src/components/AccessModal/AccessModal.css.ts
  libs/service-portal/settings/access-control/src/components/AccessModal/AccessModal.tsx
  libs/service-portal/settings/access-control/src/components/AccessModal/index.ts
  libs/service-portal/settings/access-control/src/components/Accesses/Accesses.tsx
  libs/service-portal/settings/access-control/src/components/Accesses/index.ts
  libs/service-portal/settings/access-control/src/components/index.ts
  libs/service-portal/settings/access-control/src/constants.ts
  libs/service-portal/settings/access-control/src/index.ts
  libs/service-portal/settings/access-control/src/lib/navigation.ts
  libs/service-portal/settings/access-control/src/lib/paths.ts
  libs/service-portal/settings/access-control/src/module.ts
  libs/service-portal/settings/access-control/src/screens/Access/Access.css.ts
  libs/service-portal/settings/access-control/src/screens/Access/Access.tsx
  libs/service-portal/settings/access-control/src/screens/Access/index.ts
  libs/service-portal/settings/access-control/src/screens/AccessControl/AccessControl.tsx
  libs/service-portal/settings/access-control/src/screens/AccessControl/index.ts
  libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.css.ts
  libs/service-portal/settings/access-control/src/screens/GrantAccess/GrantAccess.tsx
  libs/service-portal/settings/access-control/src/screens/GrantAccess/index.ts
  libs/service-portal/settings/access-control/src/utils/types.ts
  libs/service-portal/settings/access-control/tsconfig.json
  libs/service-portal/settings/access-control/tsconfig.lib.json
  libs/service-portal/settings/access-control/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#9520 chore(payment-schedule-client): Client to use token exchange
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/payment-schedule/src/lib/payment-schedule.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.module.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/application/templates/public-debt-payment-plan/src/dataProviders/paymentPlanPrerequisites.ts
  libs/clients/payment-schedule/src/index.ts
  libs/clients/payment-schedule/src/lib/apiConfiguration.ts
  libs/clients/payment-schedule/src/lib/apis.ts
  libs/clients/payment-schedule/src/lib/payment-schedule-client.module.ts
  libs/clients/payment-schedule/src/lib/payment-schedule.config.ts
  libs/clients/payment-schedule/src/lib/payment-schedule.ts
  libs/clients/payment-schedule/src/lib/payment-schedule.utils.spec.ts
  libs/clients/payment-schedule/src/lib/payment-schedule.utils.ts
Labels: automerge, deploy-feature

#9519 feat(delegations): Show scope group displayName instead of scope displayName
  apps/services/auth/delegation-api/src/app/domains/domains.controller.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/resources/delegation-resources.service.ts
  libs/portals/shared-modules/delegations/src/components/access/AccessCard.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.graphql
Labels: automerge

#9525 fix(j-s): Police Case Update
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
Labels: automerge

#9530 fix(marriage-condition-application): Prod error due to 404 in hjonavigla
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
Labels: automerge

#9531 fix(marriage-conditions-template): Driving registration and marriage conditions
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/style.css.ts
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
Labels: automerge

#9529 fix(general-fishing-license): Fix incorrect license codes and update service
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-ship.model.ts
  libs/api/domains/fishing-license/src/lib/fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
  libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/UnfulfilledLicenseReasons.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/index.tsx
  libs/application/templates/general-fishing-license/src/graphql/queries.ts
  libs/clients/fishing-license/src/clientConfig.json
  libs/clients/fishing-license/src/lib/fishing-license-service.ts
  libs/clients/fishing-license/src/lib/types/index.ts
Labels: automerge, deploy-feature

#9532 fix(general-fishing-license): Hotfix - Fix incorrect license codes and update service
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-ship.model.ts
  libs/api/domains/fishing-license/src/lib/fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
  libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/UnfulfilledLicenseReasons.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/index.tsx
  libs/application/templates/general-fishing-license/src/graphql/queries.ts
  libs/clients/fishing-license/src/clientConfig.json
  libs/clients/fishing-license/src/lib/types/index.ts
Labels: automerge

#9533 fix(search-indexer): Hotfix - Add circularity fail-safe to error filtering (#9337)
  libs/content-search-toolkit/README.md
  libs/content-search-toolkit/src/services/elastic.service.ts
  libs/content-search-toolkit/src/services/utils/index.ts
  libs/content-search-toolkit/src/services/utils/utils.spec.ts
Labels: automerge

#9536 fix(service-portal): Delegations module was missing in modules
  apps/service-portal/src/lib/modules.ts
Labels: automerge

#9539 fix(marriage-conditions): for testing (#9535)
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
Labels: automerge

#9537 chore(j-s): Ready For Court Notifications
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverRequestToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/notification/models/sendNotification.response.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#9543 fix(ap): Description for ADS admin
  libs/portals/admin/air-discount-scheme/src/lib/messages.ts
  libs/portals/admin/air-discount-scheme/src/lib/navigation.ts
Labels: automerge

#9542 feat(web): Persist news filter tag between language changes
  apps/web/components/Header/Header.tsx
  apps/web/components/LanguageToggler/LanguageToggler.tsx
  apps/web/components/Organization/LatestNewsCardConnectedComponent/LatestNewsCardConnectedComponent.tsx
  apps/web/layouts/main.tsx
  apps/web/screens/Organization/OrganizationNewsList.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/queries/GenericTag.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getGenericTagBySlug.input.ts
Labels: automerge

#9545 chore(pdpp): Remove area code from phone number and CIT-return condtion
  libs/application/data-providers/src/providers/UserProfileProvider.ts
  libs/application/templates/public-debt-payment-plan/src/dataProviders/paymentPlanPrerequisites.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
  libs/clients/payment-schedule/src/lib/payment-schedule-client.module.ts
Labels: automerge

#9438 feat(admin-portal): Static module switcher with dashboard redirect on single item
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.css.ts
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherHeader.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherItems.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherMobile.tsx
  apps/portals/admin/src/screens/Dashboard/Dashboard.tsx
  libs/portals/core/babel-jest.config.json
  libs/portals/core/jest.config.js
  libs/portals/core/src/hooks/useSingleNavigationItem.spec.tsx
  libs/portals/core/src/hooks/useSingleNavigationItem.ts
  libs/portals/core/src/index.ts
  libs/portals/core/test/setup.ts
  libs/portals/core/test/useSingleNavigationItem-test-cases.ts
Labels: automerge

#9399 feat: samradsgat project
  .github/CODEOWNERS
  .gitignore
  SUMMARY.md
  apps/samradsgatt/.eslintrc.json
  apps/samradsgatt/README.md
  apps/samradsgatt/babel-jest.config.json
  apps/samradsgatt/components/Card/Card.tsx
  apps/samradsgatt/components/Filter/Utils/FilterOptions.ts
  apps/samradsgatt/index.d.ts
  apps/samradsgatt/infra/samradsgatt.ts
  apps/samradsgatt/jest.config.js
  apps/samradsgatt/next-env.d.ts
  apps/samradsgatt/next.config.js
  apps/samradsgatt/pages/404.tsx
  apps/samradsgatt/pages/_app.tsx
  apps/samradsgatt/pages/api/helloworld.ts
  apps/samradsgatt/pages/index.tsx
  apps/samradsgatt/pages/test.tsx
  apps/samradsgatt/project.json
  apps/samradsgatt/proxy.config.json
  apps/samradsgatt/public/.gitkeep
  apps/samradsgatt/server.ts
  apps/samradsgatt/specs/index.spec.tsx
  apps/samradsgatt/styles/styles.css
  apps/samradsgatt/tsconfig.json
  apps/samradsgatt/tsconfig.spec.json
  charts/islandis/values.dev.yaml
  infra/src/uber-charts/islandis.ts
  package.json
  workspace.json
  yarn.lock
Labels: deploy-feature

#9546 fix(parental-leave): fix sms text to otherParent
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/assignOtherParentSms.ts
Labels: automerge

#9514 chore(j-s): Refactor upload
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/index.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
Labels: automerge

#9513 feat: remove extra login page
  apps/service-portal/src/components/Greeting/Greeting.tsx
  apps/web/components/Header/Header.tsx
  apps/web/components/Menu/Menu.tsx
  apps/web/components/ServiceWeb/Header/Header.tsx
Labels: automerge, deploy-feature

#9424 feat(auth): Delegation filtering
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-incoming.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-outgoing.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.auth.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.filters.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/test-data.ts
  apps/services/auth/delegation-api/src/app/domains/test/domains.controller.spec.ts
  apps/services/auth/delegation-api/test/types.ts
  apps/services/auth/delegation-api/tsconfig.app.json
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-test-cases.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-types.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters.spec.ts
  apps/services/auth/ids-api/tsconfig.app.json
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-company.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-ward.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.module.ts
  libs/services/auth/testing/src/fixtures/apiScopeGroup.fixture.ts
  libs/services/auth/testing/src/fixtures/client.fixture.ts
  libs/services/auth/testing/src/fixtures/domain.fixture.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/services/auth/testing/src/fixtures/index.ts
  libs/services/auth/testing/src/fixtures/types.ts
  libs/services/auth/testing/src/utils/delegations.ts
Labels: automerge

#9540 chore(service-portal): Remove StateProvider from service portal
  apps/service-portal/src/app/App.tsx
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/components/Layout/footerProps.ts
  apps/service-portal/src/components/MobileMenu/MobileMenu.tsx
  apps/service-portal/src/components/Notifications/NotificationMenu/NotificationCard/NotificationCard.tsx
  apps/service-portal/src/components/Notifications/NotificationMenu/NotificationCard/Notificationcard.css.ts
  apps/service-portal/src/components/Notifications/NotificationMenu/NotificationMenu.css.ts
  apps/service-portal/src/components/Notifications/NotificationMenu/NotificationMenu.tsx
  apps/service-portal/src/components/Notifications/NotificationMenu/mockNotifications.ts
  apps/service-portal/src/components/Notifications/NotificationMenuTrigger/NotificationMenuTrigger.css.ts
  apps/service-portal/src/components/Notifications/NotificationMenuTrigger/NotificationMenuTrigger.tsx
  apps/service-portal/src/components/Notifications/NotificationMenuTrigger/index.ts
  apps/service-portal/src/components/Sidebar/ModuleNavigation.tsx
  apps/service-portal/src/components/Sidebar/NavItem/Chevron.tsx
  apps/service-portal/src/components/Sidebar/NavItem/NavItem.tsx
  apps/service-portal/src/components/Sidebar/Sidebar.tsx
  apps/service-portal/src/store/actions.ts
  apps/service-portal/src/store/mockData.tsx
  apps/service-portal/src/store/stateProvider.tsx
  apps/service-portal/src/store/store.ts
Labels: automerge

#9541 fix(j-s): Queue Connection
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/lib/message.config.ts
  libs/judicial-system/message/src/lib/message.service.ts
  libs/judicial-system/message/src/lib/test/createTestingMessageModule.ts
Labels: automerge

#9550 refactor(portals): Remove widgets from Portal module
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/screens/Dashboard/WidgetError/WidgetError.tsx
  apps/service-portal/src/screens/Dashboard/WidgetLoading/WidgetLoading.css.ts
  apps/service-portal/src/screens/Dashboard/WidgetLoading/WidgetLoading.tsx
  libs/portals/admin/air-discount-scheme/src/module.ts
  libs/portals/core/README.md
  libs/portals/core/src/hooks/useSingleNavigationItem.spec.tsx
  libs/portals/core/src/types/portalCore.ts
  libs/portals/shared-modules/delegations/src/module.tsx
  libs/service-portal/applications/src/module.ts
  libs/service-portal/assets/src/module.ts
  libs/service-portal/core/src/lib/service-portal-core.ts
  libs/service-portal/document-provider/src/module.ts
  libs/service-portal/documents/project.json
  libs/service-portal/documents/src/module.ts
  libs/service-portal/documents/src/widgets/documentList.tsx
  libs/service-portal/documents/src/widgets/index.ts
  libs/service-portal/education-career/src/module.ts
  libs/service-portal/education-degree/src/index.ts
  libs/service-portal/education-license/src/module.ts
  libs/service-portal/education-student-assessment/src/module.ts
  libs/service-portal/education/src/module.ts
  libs/service-portal/eligibility/src/index.ts
  libs/service-portal/endorsements/src/module.ts
  libs/service-portal/finance/src/module.ts
  libs/service-portal/health/src/index.ts
  libs/service-portal/icelandic-names-registry/src/module.ts
  libs/service-portal/information/src/module.ts
  libs/service-portal/licenses/src/module.ts
  libs/service-portal/settings/personal-information/src/module.ts
  libs/service-portal/vehicles/src/module.ts
Labels: automerge

#9538 feat(auth-admin): Add name field to ApiScopeUser
  apps/auth-admin-web/components/Admin/form/ApiScopeUserCreateForm.tsx
  apps/auth-admin-web/components/Admin/lists/ApiScopeUsersList.tsx
  apps/auth-admin-web/entities/dtos/api-scope-user.dto.ts
  apps/auth-admin-web/entities/models/api-scope-user.model.ts
  apps/auth-admin-web/i18n/locales/en.json
  apps/auth-admin-web/pages/admin/api-scope-user/[apiScopeUser].tsx
  apps/auth-admin-web/pages/admin/api-scope-user/index.tsx
  apps/auth-admin-web/pages/admin/index.tsx
  apps/auth-admin-web/styles/_ListLayout.scss
  libs/auth-api-lib/migrations/20230109085417-add-api-scope-user-name-field.js
  libs/auth-api-lib/src/lib/resources/dto/api-scope-user-update.dto.ts
  libs/auth-api-lib/src/lib/resources/dto/api-scope-user.dto.ts
  libs/auth-api-lib/src/lib/resources/models/api-scope-user.model.ts
  libs/auth-api-lib/src/lib/resources/resource-access.service.ts
Labels: automerge

#9528 fix(financial-statement-inao): add missing translation string to cemetery overview
  libs/application/templates/financial-statements-inao/src/fields/CemetryOverview/index.tsx
Labels: automerge

#9554 feat(payment migration): Add migration to alter column type for definition
  apps/application-system/api/migrations/20230109220524-payment-alter-column-definition.js
Labels: automerge

#9515 fix(qa): Fix breaking admin-portal test
  apps/system-e2e/src/addons.ts
  apps/system-e2e/src/playwright.config.ts
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/support/urls.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/tests/admin-portal/smoke/admin-portal.spec.ts
  apps/system-e2e/src/tests/air-discount-scheme/smoke/air-discount-scheme.spec.ts
  apps/system-e2e/src/tests/application-system/acceptance/driving-licence.spec.ts
  apps/system-e2e/src/tests/application-system/acceptance/parental-leave.spec.ts
  apps/system-e2e/src/tests/application-system/smoke/p-sign.spec.ts
  apps/system-e2e/src/tests/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/service-portal/smoke/company-delegation.spec.ts
  apps/system-e2e/src/tests/service-portal/smoke/service-portal.spec.ts
  apps/system-e2e/src/tests/skilavottord/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/web/smoke/homepage.spec.ts
  apps/system-e2e/src/tests/web/smoke/miscellaneous.spec.ts
  apps/system-e2e/src/tests/web/smoke/search.spec.ts
  apps/system-e2e/src/tests/web/smoke/sites-of-institutions.spec.ts
Labels: automerge

#9557 feat(transport authority applications): Transfer of vehicle ownership - Switch vehiclecheck endpoint
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.types.ts
Labels: automerge

#9555 fix(j-s): Queue Connection
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  libs/judicial-system/message/src/lib/message.service.ts
  libs/judicial-system/message/src/lib/test/sendMessageToQueue.spec.ts
  libs/judicial-system/message/src/lib/test/sendMessagesToQueue.spec.ts
Labels: automerge

#9563 fix(ads): More test data on local development
  apps/air-discount-scheme/backend/seeders/20211108100835-development.js
Labels: automerge

#9566 fix(j-s): Other Case Files
  apps/judicial-system/web/src/utils/formHelper.ts
Labels: automerge

#9569 fix(parental-leave): prevent sending sms to non GSM phoneNumber
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#9570 fix(parental leave): sms issues
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#9575 fix(j-s): Remove case files
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
Labels: automerge

#9577 chore(portals): Remove support for array of route paths
  .github/CODEOWNERS
  libs/portals/core/src/components/PortalProvider.tsx
  libs/portals/core/src/screens/Modules.tsx
  libs/portals/core/src/types/portalCore.ts
  libs/portals/core/src/utils/filterNavigationTree/filterNavigationTree.ts
  libs/portals/core/src/utils/plausible.ts
  libs/portals/shared-modules/delegations/src/components/access/AccessForm/AccessForm.tsx
Labels: automerge

#9576 feat(ap): Implement PortalNavigation and tweak ADS admin design
  libs/portals/admin/air-discount-scheme/src/lib/navigation.ts
  libs/portals/admin/air-discount-scheme/src/screens/CreateDiscount/CreateDiscount.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/Overview.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/components/Filters/Filters.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/components/KeyValues/KeyValue.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/components/KeyValues/KeyValues.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/components/Summary/Summary.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/utils.ts
  libs/portals/core/src/components/PortalNavigation/PortalNavigation.tsx
  libs/portals/core/src/index.ts
Labels: automerge

#9574 feat(application-system): Update template name
  apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/templates/reference-template/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTemplate.ts
Labels: automerge

#9581 chore(service-portal): Remove passport feature flag
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
Labels: automerge

#9559 fix(driving-license-application): jurisdiction required
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
Labels: automerge

#9585 chore(service-portal): hotfix - remove feature flag passport
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
Labels: automerge

#9567 feat(auth): Enable filtering delegations with requested scopes
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
Labels: automerge

#9590 fix(contentful-role-permissions): Load all content types, not just the first 100 in Contentful dev tool
  apps/tools/contentful-role-permissions/constants/index.ts
  apps/tools/contentful-role-permissions/utils/index.ts
Labels: automerge

#9593 fix(j-s): Remove case files again
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
Labels: automerge

#9572 fix(parental leave): remove apply option personal allowance single parent
  libs/application/templates/parental-leave/src/fields/OtherParent/index.tsx
  libs/application/templates/parental-leave/src/forms/OtherParentApproval.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: bug

#9580 refactor(portals-admin): Update static module switcher when outside active module
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcher.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.css.ts
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherDesktop.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherHeader.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherMobile.tsx
  apps/portals/admin/src/screens/Dashboard/Dashboard.tsx
  libs/portals/core/src/hooks/useSingleNavigationItem.spec.tsx
  libs/portals/core/src/hooks/useSingleNavigationItem.ts
  libs/portals/core/test/useSingleNavigationItem-test-cases.ts
Labels: automerge

#9594 fix(delegation-api): Stop actor from being able to find delegations to self with otherUser filter.
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.filters.spec.ts
  libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
Labels: automerge

#9573 fix(system-e2e): Fix incorrect targeting in admin-portal
  apps/system-e2e/src/tests/admin-portal/smoke/admin-portal.spec.ts
Labels: automerge

#9562 fix(application-estate): Cleanup types
  libs/application/templates/estate/src/dataProviders/EstateNoticeProvider.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/forms/ResidencePermit/overviewSection.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
Labels: automerge

#8691 feat(service-portal): new disability license client
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/service-portal/src/assets/images/tr.svg
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/license-service/README.md
  libs/api/domains/license-service/src/index.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/disabilityLicenseMapper.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.config.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.module.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/index.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/mocks/src/domains/license-service/factories.ts
  libs/api/mocks/src/domains/license-service/mocks/disabilityMock.ts
  libs/api/mocks/src/domains/license-service/store.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/tr.scope.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/utils/dataMapper.ts
Labels: automerge

#9586 fix(service-portal): Remove unused code
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
Labels: automerge

#9598 feat(transport authority applications): Transfer of vehicle ownership - Small fixes
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/smsGenerators/requestReviewSms.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#9338 feat(inheritance-report): Initial Setup of the Inheritance Report
  .github/CODEOWNERS
  SUMMARY.md
  libs/application/core/src/lib/institutionMapper.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/.babelrc
  libs/application/templates/inheritance-report/.eslintrc.json
  libs/application/templates/inheritance-report/README.md
  libs/application/templates/inheritance-report/babel-jest.config.json
  libs/application/templates/inheritance-report/codegen.yml
  libs/application/templates/inheritance-report/jest.config.js
  libs/application/templates/inheritance-report/project.json
  libs/application/templates/inheritance-report/src/assets/Grieving.tsx
  libs/application/templates/inheritance-report/src/fields/DoneImage/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/fields/styles.css.ts
  libs/application/templates/inheritance-report/src/forms/assets.ts
  libs/application/templates/inheritance-report/src/forms/business.ts
  libs/application/templates/inheritance-report/src/forms/debts.ts
  libs/application/templates/inheritance-report/src/forms/done.ts
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/heirs.ts
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/index.ts
  libs/application/templates/inheritance-report/src/lib/InheritanceReportTemplate.ts
  libs/application/templates/inheritance-report/src/lib/constants.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/currencyStringToNumber.ts
  libs/application/templates/inheritance-report/src/lib/utils/isEstateInfo.ts
  libs/application/templates/inheritance-report/src/types.ts
  libs/application/templates/inheritance-report/src/types/index.ts
  libs/application/templates/inheritance-report/tsconfig.json
  libs/application/templates/inheritance-report/tsconfig.lib.json
  libs/application/templates/inheritance-report/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#9544 chore(j-s): Optimize cases query
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/case/case.resolver.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/cases.interceptor.ts
  apps/judicial-system/api/src/app/modules/caseList/caseList.module.ts
  apps/judicial-system/api/src/app/modules/caseList/caseList.resolver.ts
  apps/judicial-system/api/src/app/modules/caseList/interceptors/caseList.interceptor.ts
  apps/judicial-system/api/src/app/modules/caseList/models/caseList.model.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseListEntry.response.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Shared/cases.spec.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/mutations.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#9609 fix(ap): Hide actor button in user menu.
  apps/portals/admin/src/components/Header/Header.tsx
  libs/shared/components/src/auth/UserMenu/UserDelegations.tsx
  libs/shared/components/src/auth/UserMenu/UserDropdown.tsx
  libs/shared/components/src/auth/UserMenu/UserMenu.tsx
Labels: automerge

#9608 fix(ap): Delegation scope should be 1 level deep.
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#9556 chore(system-e2e): Support for mocking x-road Properties/assets api calls
  apps/api/infra/api.ts
  apps/application-system/form/project.json
  apps/service-portal/infra/service-portal.ts
  apps/service-portal/project.json
  apps/services/user-profile/infra/service-portal-api.ts
  apps/system-e2e/project.json
  apps/system-e2e/src/support/wire-mocks.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/value-files-generators/local-setup.ts
  infra/src/dsl/xroad.ts
  infra/src/uber-charts/islandis.ts
  libs/service-portal/graphql/src/lib/client.ts
  libs/shared/utils/src/lib/createXRoadAPIPath.ts
Labels: automerge

#9599 feat(auth): Add stored procedure for deleting expired grants.
  libs/auth-api-lib/migrations/20230113112021-add_grant_cleanup_proc.js
Labels: automerge

#9613 fix(application-system-worker): Missing environment variables
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, deploy-feature

#9612 fix(system-e2e): number of national IDs for admin mage
  apps/system-e2e/src/support/login.ts
Labels: automerge

#9523 feat(j-s): allow prosecutor to edit indictments before they are recieved
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/overview.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#9568 fix(ads): Display Discount Model in requests instead of empty array
  libs/air-discount-scheme/types/src/lib/discount.ts
  libs/api/domains/air-discount-scheme/src/lib/discount/discount.resolver.spec.ts
  libs/api/domains/air-discount-scheme/src/lib/discount/discount.service.ts
  libs/api/domains/air-discount-scheme/src/lib/models/discount.model.ts
Labels: automerge

#9571 chore(j-s): Move RECEIVE transition from frontend to backend
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#9617 fix(transfer of vehicle ownership): few small fixes
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/application.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/application.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/BuyerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/SellerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/VehicleSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/buyerSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/application.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/conclusion.ts
Labels: automerge

#9616 fix(cleanup feature flag): Remove unused feature flag - No Debt Certificate Delegation
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#9622 feat(pdpp): Map correct texts to prerequisites error modal
  libs/application/data-providers/src/providers/UserProfileProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/paymentPlanPrerequisites.service.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/errorModal.ts
Labels: automerge, deploy-feature

#9565 feat(j-s): heads up notifications for indictments
  apps/judicial-system/backend/migrations/20230106104020-update-institution.js
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/messages/pdfCore.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
Labels: automerge

#9627 fix(parental-leave): personal allowance removed when selected NO
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#9582 fix: Upgraded class-validator
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/findByTagsEndorsementList/findByTagsEndorsementList.spec.ts
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  libs/infra-nest-server/src/lib/testServer.ts
  package.json
  yarn.lock
Labels: security, automerge, high priority

#9561 fix(applications): Fix health insurance application
  libs/application/templates/health-insurance/src/fields/Review/FormerInsurance.tsx
Labels: automerge

#9631 fix(applications): minor QA fixes to data protection complaint
  libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.tsx
  libs/application/templates/data-protection-complaint/src/lib/messages/complaint.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/delimitation.ts
Labels: automerge

#9632 fix(transfer of vehicle ownership): bugs
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OperatorRepeater/OperatorRepeaterItem.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/CoOwnerAndOperatorRepeater/CoOwnerAndOperatorRepeaterItem.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#8851 feat(general-fishing-license): New fishing license types added to application
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-data-restriction.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-license.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-columns.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-options.model.ts
  libs/api/domains/fishing-license/src/lib/fishing-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/AreaWithDateSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/AttachmentsTitleSection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/DateWithConstraintsSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
  libs/application/templates/general-fishing-license/src/fields/FishingLicenseFurtherInfoTitleSection/FishingLicenseFurtherInfoTitleSection.css.ts
  libs/application/templates/general-fishing-license/src/fields/FishingLicenseFurtherInfoTitleSection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/Overview/index.tsx
  libs/application/templates/general-fishing-license/src/fields/RailNetAndRoeNetCalculations/index.tsx
  libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/FishingLicenseAlertMessage/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipInformation/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/ShipSelectionAlertModal.css.ts
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/index.ts
  libs/application/templates/general-fishing-license/src/fields/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/fishingLicenseFurtherInfoSection.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/index.ts
  libs/application/templates/general-fishing-license/src/graphql/queries.ts
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
  libs/application/templates/general-fishing-license/src/lib/messages/application.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicense.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicenseFurtherInformation.ts
  libs/application/templates/general-fishing-license/src/lib/messages/index.ts
  libs/application/templates/general-fishing-license/src/lib/messages/shipSelection.ts
  libs/application/templates/general-fishing-license/src/types/index.ts
  libs/application/templates/general-fishing-license/src/utils/fields.ts
  libs/application/templates/general-fishing-license/src/utils/licenses.ts
  libs/clients/fishing-license/src/lib/types/index.ts
Labels: automerge, deploy-feature

#9604 feat(web): Change header and footer for Directorate of Health
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.tsx
Labels: automerge

#9633 fix(j-s): Receive Case
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
Labels: automerge

#9620 feat(web): Add footer and header to HSU organization pages
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.tsx
Labels: automerge

#9626 feat(transport authority applications): Make subLabel translatable in radio and checkbox components
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/AnonymityInVehicleRegistryForm/informationSection.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/CardTypeSection/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/OrderVehicleLicensePlateForm/InformationSection/plateDeliverySubSection.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
  libs/island-ui/core/src/lib/RadioButton/RadioButton.tsx
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
  libs/shared/form-fields/src/lib/RadioController/RadioController.tsx
Labels: automerge

#9630 chore(system-e2e): Scoping system e2e tests by deployment
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/admin-portal.spec.ts
  apps/system-e2e/src/tests/islandis/air-discount-scheme/smoke/air-discount-scheme.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-licence.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/setup-xroad.mocks.ts
  apps/system-e2e/src/tests/islandis/application-system/smoke/applications.spect.ts
  apps/system-e2e/src/tests/islandis/application-system/smoke/p-sign.spec.ts
  apps/system-e2e/src/tests/islandis/identity-server/smoke/identity-server.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/applications.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/education.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financials.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/miscellaneous.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/payment-plan.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/realestate.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/service-portal.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/settings.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/islandis/skilavottord/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/miscellaneous.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/search.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts
Labels: automerge

#9634 fix(core): Revert forbidUnknownValues
  libs/infra-nest-server/src/lib/bootstrap.ts
  libs/infra-nest-server/src/lib/testServer.ts
  libs/testing/nest/src/lib/testServer.ts
Labels: automerge

#9636 feat(general-fishing-license): New fishing license types added to app…
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-data-restriction.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-license.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-columns.model.ts
  libs/api/domains/fishing-license/src/graphql/models/fishing-license-list-options.model.ts
  libs/api/domains/fishing-license/src/lib/fishing-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/AreaWithDateSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/AttachmentsTitleSection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/DateWithConstraintsSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
  libs/application/templates/general-fishing-license/src/fields/FishingLicenseFurtherInfoTitleSection/FishingLicenseFurtherInfoTitleSection.css.ts
  libs/application/templates/general-fishing-license/src/fields/FishingLicenseFurtherInfoTitleSection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/Overview/index.tsx
  libs/application/templates/general-fishing-license/src/fields/RailNetAndRoeNetCalculations/index.tsx
  libs/application/templates/general-fishing-license/src/fields/ShipSelection/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/FishingLicenseAlertMessage/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipInformation/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/ShipSelectionAlertModal.css.ts
  libs/application/templates/general-fishing-license/src/fields/components/ShipSelectionAlertModal/index.tsx
  libs/application/templates/general-fishing-license/src/fields/components/index.ts
  libs/application/templates/general-fishing-license/src/fields/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/fishingLicenseFurtherInfoSection.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/index.ts
  libs/application/templates/general-fishing-license/src/graphql/queries.ts
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
  libs/application/templates/general-fishing-license/src/lib/messages/application.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicense.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicenseFurtherInformation.ts
  libs/application/templates/general-fishing-license/src/lib/messages/index.ts
  libs/application/templates/general-fishing-license/src/lib/messages/shipSelection.ts
  libs/application/templates/general-fishing-license/src/types/index.ts
  libs/application/templates/general-fishing-license/src/utils/fields.ts
  libs/application/templates/general-fishing-license/src/utils/licenses.ts
  libs/clients/fishing-license/src/lib/types/index.ts
Labels: automerge, high priority

#9635 fix(core): HOTFIX Revert forbidUnknownValues
  libs/infra-nest-server/src/lib/bootstrap.ts
  libs/infra-nest-server/src/lib/testServer.ts
  libs/testing/nest/src/lib/testServer.ts
Labels: automerge, high priority

#9611 chore(public-api): Clean up in public api and auth-api-lib
  apps/services/auth/public-api/src/app/.gitkeep
  apps/services/auth/public-api/src/app/app.module.ts
  apps/services/auth/public-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth/public-api/src/app/modules/delegations/meDelegations.controller.spec.ts
  apps/services/auth/public-api/src/app/modules/delegations/meDelegations.controller.ts
  apps/services/auth/public-api/src/app/modules/resources/resources.module.ts
  apps/services/auth/public-api/src/app/modules/resources/scopes.controller.spec.ts
  apps/services/auth/public-api/src/app/modules/resources/scopes.controller.ts
  apps/services/auth/public-api/test/fixtures/index.ts
  apps/services/auth/public-api/test/fixtures/translation.fixture.ts
  apps/services/auth/public-api/test/setup.ts
  apps/services/auth/public-api/test/utils.ts
  libs/api/domains/auth/src/lib/dto/actorDelegation.input.ts
  libs/api/domains/auth/src/lib/models/delegation.model.ts
  libs/api/domains/auth/src/lib/resolvers/delegationScope.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/mergedDelegation.resolver.ts
  libs/api/domains/auth/src/lib/services/meDelegations.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.service.ts
  libs/auth-api-lib/src/lib/resources/resources.service.ts
  libs/clients/auth/public-api/src/lib/apis.ts
  libs/services/auth/testing/src/fixtures/apiScopeGroup.fixture.ts
Labels: automerge

#9639 fix(j-s): Side panel
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
Labels: automerge

#9638 feat(auth): Create ApiScopeUserClaim models in scope migrations.
  libs/auth-api-lib/seeders/data/helpers/createScope.ts
Labels: automerge

#9640 fix(j-s): Case File Reset
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#9641 feat(web): Change header and footer for Directorate of Health (#9604)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.tsx
Labels: automerge, high priority

#9618 chore(j-s): Clarify hearing arrangements button text
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/defendantForm.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/accusedForm.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.strings.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.strings.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#9646 fix(service-portal): Update passport renewal links
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
Labels: automerge

#9623 fix(core): Fix serve in SPA projects
  apps/application-system/form/project.json
  apps/portals/admin/project.json
  apps/service-portal/project.json
Labels: automerge

#9644 fix(application-system): clone object during configure
  libs/application/templates/reference-template/src/dataProviders/index.ts
  libs/application/templates/reference-template/src/forms/Prerequisites.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/template-api/TemplateApi.ts
Labels: automerge

#9652 fix(pdpp): change reference to identity for overview
  libs/application/templates/public-debt-payment-plan/src/fields/Overview/Overview.tsx
Labels: automerge

#9645 fix(application-system): clone object for configure
  libs/application/templates/reference-template/src/dataProviders/index.ts
  libs/application/templates/reference-template/src/forms/Prerequisites.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/template-api/TemplateApi.ts
Labels: automerge

#9653 fix(transfer of vehicle ownership): bugs
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/messages/applicant.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/StatusStep/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/BuyerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/InsuranceSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/types/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getReviewSteps.ts
Labels: automerge

#9655 fix(transfer of vehicle ownership): hotfix
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/messages/applicant.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/StatusStep/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/BuyerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/InsuranceSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/types/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getReviewSteps.ts
Labels: automerge

#9656 feat(auth): Create ApiScopeUserClaim models in scope migrations. (#9638) HOTFIX
  libs/auth-api-lib/seeders/data/helpers/createScope.ts
Labels: automerge

#9658 feat: ELECTRONIC_DATA_DISCOVERY_INVESTIGATION defender registration
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
Labels: automerge

#9650 fix(j-s): Conditional text for secondary button
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.strings.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.strings.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#9624 chore(application-system): Remove data providers lib
  SUMMARY.md
  libs/application/data-providers/.babelrc
  libs/application/data-providers/.eslintrc.json
  libs/application/data-providers/README.md
  libs/application/data-providers/jest.config.js
  libs/application/data-providers/project.json
  libs/application/data-providers/src/index.ts
  libs/application/data-providers/src/libs/constants.ts
  libs/application/data-providers/src/providers/ExampleFails.ts
  libs/application/data-providers/src/providers/ExampleSucceeds.ts
  libs/application/data-providers/src/providers/FamilyInformationProvider.ts
  libs/application/data-providers/src/providers/HasQualityPhotoProvider.ts
  libs/application/data-providers/src/providers/IdentityProvider.ts
  libs/application/data-providers/src/providers/JuristictionProvider.ts
  libs/application/data-providers/src/providers/NationalRegistryProvider.ts
  libs/application/data-providers/src/providers/PaymentCatalogProvider.ts
  libs/application/data-providers/src/providers/UserProfileProvider.ts
  libs/application/data-providers/tsconfig.json
  libs/application/data-providers/tsconfig.lib.json
  libs/application/data-providers/tsconfig.spec.json
  libs/application/templates/accident-notification/src/dataProviders/index.ts
  libs/application/templates/accident-notification/src/index.ts
  libs/application/templates/data-protection-complaint/src/dataProviders/index.ts
  libs/application/templates/data-protection-complaint/src/index.ts
  libs/application/templates/driving-license-duplicate/src/dataProviders/FeeInfoProvider.ts
  libs/application/templates/driving-license-duplicate/src/dataProviders/QualityPhotoProvider.ts
  libs/application/templates/driving-license-duplicate/src/dataProviders/index.ts
  libs/application/templates/estate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/index.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#9663 fix(marriage-conditions): Missing new religions data provider
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/marriage-conditions/src/dataProviders/NationalRegistryMaritalStatusProvider.ts
  libs/application/templates/marriage-conditions/src/dataProviders/ReligionsProvider.ts
  libs/application/templates/marriage-conditions/src/dataProviders/index.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/constants.ts
  libs/clients/syslumenn/src/lib/syslumennClient.config.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge, high priority

#9671 feat(web): Ship search component for directorate of fisheries organization pages
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/connected/fiskistofa/ShipSearchBoxedInput/ShipSearchBoxedInput.tsx
  apps/web/components/connected/fiskistofa/index.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
Labels: automerge

#9669 infra: Grant graphql api access to air-discount-scheme-backend
  apps/air-discount-scheme/backend/infra/backend.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge
