Repository island-is/island.is, pull requests merged in 2023-03, with the labels that each got.

#10240 fix(j-s): Filter Case
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
Labels: automerge

#10248 fix(infra): Add client cert to applicaiton infra not worker
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#10242 fix(island-ui): location of the buttons
  libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.tsx
Labels: automerge

#10225 feat(island-ui): Change icon prop for Input component
  apps/judicial-system/web/src/components/DateTime/DateTime.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
  libs/island-ui/core/src/lib/DatePicker/types.ts
  libs/island-ui/core/src/lib/Filter/FilterInput/FilterInput.tsx
  libs/island-ui/core/src/lib/Input/Input.tsx
  libs/island-ui/core/src/lib/Input/types.ts
  libs/island-ui/core/src/lib/Menu/Menu.tsx
  libs/portals/admin/document-provider/src/components/Forms/StatisticForm.tsx
  libs/portals/admin/document-provider/src/screens/DocumentProviders/DocumentProvidersSearch.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoingHeader.tsx
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/vehicles/src/screens/Lookup/Lookup.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/VehicleHistory.tsx
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#10258 chore(applications): Submit button disable option to fieldprops
  libs/application/types/src/lib/Form.ts
  libs/application/ui-shell/src/components/FormField.tsx
  libs/application/ui-shell/src/components/FormMultiField.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
Labels: automerge

#10263 feat(ids-admin): Create DB seed for local dev for domain
  libs/auth-api-lib/seeders/local/008-domains_resources.js
Labels: automerge

#10247 feat(services-auth-admin-api): Admin api new tenant endpoint
  apps/services/auth/admin-api/README.md
  apps/services/auth/admin-api/project.json
  apps/services/auth/admin-api/src/app/.gitkeep
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/modules/access/access.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-allowed-scope.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-claim.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-grant-type.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-post-logout-redirect-uri.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-secret.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/clients.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/cors.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/idp-restriction.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/redirect-uri.controller.ts
  apps/services/auth/admin-api/src/app/modules/grant-types/grant-types.controller.ts
  apps/services/auth/admin-api/src/app/modules/idp-provider/idp-provider.controller.ts
  apps/services/auth/admin-api/src/app/modules/personal-representative/personal-representative.controller.ts
  apps/services/auth/admin-api/src/app/modules/resources/resources.controller.ts
  apps/services/auth/admin-api/src/app/modules/translation/translation.controller.ts
  apps/services/auth/admin-api/src/app/modules/users/user-identities.controller.ts
  apps/services/auth/admin-api/src/app/tenants/me-tenants.controller.ts
  apps/services/auth/admin-api/src/app/tenants/tenants.module.ts
  apps/services/auth/admin-api/src/buildOpenApi.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  apps/services/auth/admin-api/src/main.ts
  apps/services/auth/admin-api/src/openApi.ts
  apps/services/auth/admin-api/tsconfig.app.json
  apps/services/auth/admin-api/tsconfig.json
  libs/auth-api-lib/seeders/data/scope-auth-admin-super-user.ts
  libs/auth-api-lib/seeders/data/scope-auth-admin.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/resources/dto/tenant.dto.ts
  libs/auth-api-lib/src/lib/resources/resources.module.ts
  libs/auth-api-lib/src/lib/resources/tenants.service.ts
  libs/auth-api-lib/src/lib/translation/dto/translated-value.dto.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/auth/scopes/src/lib/authAdmin.scope.ts
Labels: automerge

#10261 fix(parental-leave): update read me
  libs/application/templates/parental-leave/README.md
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart-2.png
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart.drawio
Labels: automerge

#10266 feat(financial-statements-inao): Equity can be negative
  libs/application/templates/financial-statements-inao/src/lib/utils/dataSchema.ts
Labels: automerge

#10271 fix(parental-leave): fix employer to employer email
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
Labels: automerge

#10267 fix(operating-license-application): delegation
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/application/templates/operating-license/src/lib/constants.ts
  libs/application/templates/operating-license/src/lib/messages.ts
Labels: automerge

#10274 fix(j-s): Remove modified text and change namespace
  apps/judicial-system/backend/src/app/messages/courtUpload.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
Labels: automerge

#10268 chore(web): Update Heilsuvera livechat license id
  apps/web/components/Organization/Wrapper/config.ts
Labels: automerge

#10214 fix(web): Organization page button link DOM nodes
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  libs/island-ui/core/src/lib/Button/Button.tsx
Labels: automerge

#10250 fix(web): Only move chat bubble up on articles if process entry banner is present
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/screens/Article/Article.tsx
Labels: automerge

#10222 fix(service-portal): service portal - petitions
  .github/CODEOWNERS
  apps/service-portal/src/lib/modules.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/endorsements/README.md
  libs/service-portal/endorsements/src/lib/messages.ts
  libs/service-portal/endorsements/src/lib/paths.ts
  libs/service-portal/endorsements/src/screens/Petitions/Petitions.tsx
  libs/service-portal/endorsements/src/screens/Petitions/index.ts
  libs/service-portal/endorsements/src/screens/PetitionsAdmin/index.ts
  libs/service-portal/endorsements/src/screens/PetitionsTable/PetitionsTable.tsx
  libs/service-portal/endorsements/src/screens/PetitionsTable/index.ts
  libs/service-portal/endorsements/src/screens/ViewPetition/ViewPetition.tsx
  libs/service-portal/endorsements/src/screens/ViewPetition/index.ts
  libs/service-portal/endorsements/src/screens/ViewPetitionAdmin/index.ts
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/petitions/.babelrc
  libs/service-portal/petitions/.eslintrc.json
  libs/service-portal/petitions/README.md
  libs/service-portal/petitions/babel-jest.config.json
  libs/service-portal/petitions/codegen.yml
  libs/service-portal/petitions/jest.config.js
  libs/service-portal/petitions/project.json
  libs/service-portal/petitions/src/index.ts
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/lib/paths.ts
  libs/service-portal/petitions/src/lib/utils.ts
  libs/service-portal/petitions/src/module.tsx
  libs/service-portal/petitions/src/screens/Petitions/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsAdmin/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/styles.css.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/Skeletons/Skeleton.tsx
  libs/service-portal/petitions/src/screens/Skeletons/SkeletonAdmin.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewPetitionAdmin/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/service-portal/petitions/src/screens/hooks.ts
  libs/service-portal/petitions/src/screens/queries.ts
  libs/service-portal/petitions/tsconfig.json
  libs/service-portal/petitions/tsconfig.lib.json
  libs/service-portal/petitions/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#10276 fix(parental-leave): Could delete period until 20 of this month
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#10282 fix(parental-leave): Could delete period until 20 of this month (#10276)
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#10279 feat(financial-statements-inao): Overview total values border top
  libs/application/templates/financial-statements-inao/src/fields/Shared/AssetDebtEquityOverview.tsx
  libs/application/templates/financial-statements-inao/src/fields/Shared/ValueLine.tsx
Labels: automerge

#10284 fix(parental-leave): wording on email to employer
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
Labels: automerge

#10285 fix(license-api): Pick out properties for verify
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
Labels: automerge

#10287 feat(financial-statements-inao): Fix election age limit
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
  libs/clients/financial-statements-inao/src/lib/utils/ageUtil.spec.ts
  libs/clients/financial-statements-inao/src/lib/utils/ageUtil.ts
Labels: automerge

#10280 fix(system-e2e): Disable breaking test
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/financial-statements-inao.spec.ts
Labels: automerge

#10259 feat(j-s): Traffic Violation Substances
  apps/judicial-system/web/src/components/Substances/Substances.css.ts
  apps/judicial-system/web/src/components/Substances/Substances.strings.ts
  apps/judicial-system/web/src/components/Substances/Substances.tsx
  apps/judicial-system/web/src/components/Substances/SubstancesEnum.strings.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#10265 fix(j-s): Incident Description Autofill
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCountSubstanceEnum.strings.ts
Labels: automerge

#10290 feat(consultation-portal): Kam 866 make page mobile friendly and others
  apps/consultation-portal/components/BreadcrumbsWithMobileDivider/BreadcrumbsWithMobileDivider.tsx
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/Card/SimpleCardSkeleton.tsx
  apps/consultation-portal/components/Card/index.ts
  apps/consultation-portal/components/CaseOverview/CaseOverview.css.ts
  apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/components/CaseStatusCard/CaseStatusCard.tsx
  apps/consultation-portal/components/CaseTimeline/CaseTimeline.tsx
  apps/consultation-portal/components/DropdownSort/DropdownSort.tsx
  apps/consultation-portal/components/EyebrowsWithSeperator/EyebrowsWithSeperator.tsx
  apps/consultation-portal/components/Filterbox/Filterbox.tsx
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/components/SearchAndFilter/SearchAndFilter.tsx
  apps/consultation-portal/components/SearchAndSort/SearchAndSort.tsx
  apps/consultation-portal/components/StackedTitleAndDescription/StackedTitleAndDescription.tsx
  apps/consultation-portal/components/SubscriptionBox/SubscriptionBox.tsx
  apps/consultation-portal/components/Tab/TabContent.tsx
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/types/enums.ts
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/helpers/index.ts
  apps/consultation-portal/utils/helpers/sorting.ts
Labels: automerge

#10286 fix(estate): adding representative section
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#10294 fix(parental-leave): title on InReviewSteps shown twice
  libs/application/templates/parental-leave/src/forms/EditsInReview.ts
  libs/application/templates/parental-leave/src/forms/InReviewAdditionalDocumentsRequired.ts
Labels: automerge

#10233 feat(infra): DSL support for redis declarations
  apps/air-discount-scheme/backend/infra/backend.ts
  apps/application-system/api/infra/application-system-api.ts
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/dsl.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/redis.spec.ts
  infra/src/dsl/service-to-environment/pre-process-service.ts
  infra/src/dsl/types/charts.ts
  infra/src/dsl/types/input-types.ts
  infra/src/environments.ts
Labels: automerge

#10197 feat(j-s): Show caseResentExplanation on defender overview screen
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
  apps/judicial-system/web/src/components/CaseResentExplanation/CaseResentExplanation.strings.ts
  apps/judicial-system/web/src/components/CaseResentExplanation/CaseResentExplanation.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
Labels: automerge

#10298 fix(infra): Test EnvironmentConfig requires redisHost
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/egress.spec.ts
  infra/src/dsl/env.spec.ts
  infra/src/dsl/extraAttributes.spec.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/healthcheck.spec.ts
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/initContainer.spec.ts
  infra/src/dsl/postgres.spec.ts
  infra/src/dsl/service-account.spec.ts
  infra/src/dsl/target-port.spec.ts
  infra/src/dsl/toggles.spec.ts
  infra/src/dsl/volumes.spec.ts
  infra/src/dsl/xroad.spec.ts
Labels: automerge, high priority, merge.priority_merge_label

#10264 feat(ids-admin): Tenant loader and back button update
  libs/portals/admin/ids-admin/src/components/Applications/Applications.tsx
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.loader.ts
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/IDSAdmin.tsx
  libs/portals/admin/ids-admin/src/screens/Tenant.tsx
  libs/portals/core/src/components/PortalNavigation/PortalNavigation.tsx
  libs/portals/core/src/utils/router/createModuleRoutes.tsx
  libs/react-spa/shared/src/index.ts
  libs/react-spa/shared/src/lib/replaceParams.ts
Labels: automerge

#10299 feat(consultation-portal): Kam 934 active menu items highlighted
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/components/Menu/Menu.css.ts
  apps/consultation-portal/components/Menu/Menu.tsx
  apps/consultation-portal/components/Modal/MenuModal.tsx
  apps/consultation-portal/components/svg/LogoMobile.tsx
  apps/consultation-portal/components/svg/index.ts
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/um/index.tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/utils/helpers/checkActiveHeaderLink.tsx
  apps/consultation-portal/utils/helpers/index.ts
Labels: automerge

#10304 feat(consultation-portal): KAM-933 basic empty state
  apps/consultation-portal/components/EmptyState/EmptyState.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
Labels: automerge

#10270 chore(sp): Implement api mocks for delegations
  apps/service-portal/src/auth.ts
  libs/api/mocks/src/domains/auth/factories.ts
  libs/api/mocks/src/domains/auth/resolvers.ts
  libs/api/mocks/src/domains/auth/store.ts
  libs/api/mocks/src/domains/identity/factories.ts
  libs/api/mocks/src/domains/identity/resolvers.ts
  libs/api/mocks/src/domains/identity/store.ts
  libs/api/mocks/src/resolvers.ts
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationsFormFooter.css.ts
  libs/shared/mocking/src/utils/factory.spec.ts
  libs/shared/mocking/src/utils/factory.ts
  libs/shared/mocking/src/utils/simpleFactory.ts
  libs/shared/mocking/src/utils/times.spec.ts
  libs/shared/mocking/src/utils/times.ts
  libs/testing/fixtures/project.json
Labels: automerge

#10306 fix(sessions): Removed Test string from datepicker
  libs/service-portal/sessions/src/components/SessionFilter/SessionFilter.tsx
Labels: automerge

#10141 chore(contentful-apps): Add Contentful apps to monorepo
  .github/CODEOWNERS
  apps/contentful-apps/.eslintrc.json
  apps/contentful-apps/README.md
  apps/contentful-apps/components/Layout.tsx
  apps/contentful-apps/components/LocalhostWarning.tsx
  apps/contentful-apps/index.d.ts
  apps/contentful-apps/infra/contentful-apps.ts
  apps/contentful-apps/jest.config.js
  apps/contentful-apps/next-env.d.ts
  apps/contentful-apps/next.config.js
  apps/contentful-apps/pages/_app.tsx
  apps/contentful-apps/pages/fields/admin-only-json-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-checkbox-list-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-dropdown-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-field.tsx
  apps/contentful-apps/pages/fields/admin-only-single-reference-field.tsx
  apps/contentful-apps/pages/fields/article-related-articles-field.tsx
  apps/contentful-apps/pages/fields/article-subarticles-field.tsx
  apps/contentful-apps/pages/fields/content-type-notifications-field.tsx
  apps/contentful-apps/pages/fields/publish-date-field.tsx
  apps/contentful-apps/project.json
  apps/contentful-apps/public/.gitkeep
  apps/contentful-apps/server.ts
  apps/contentful-apps/tsconfig.json
  apps/contentful-apps/tsconfig.spec.json
  charts/islandis/values.dev.yaml
  infra/src/uber-charts/islandis.ts
  package.json
  workspace.json
  yarn.lock
Labels: automerge

#10302 feat: samradsgatt/kam 916 add graph ql queries
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/EybrowsWithSeperator/EybrowsWithSeperator.tsx
  apps/consultation-portal/graphql/getAllCases.ts
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/pages/test.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/getCase.ts
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/getAllCases.ts
  apps/consultation-portal/screens/Test/Home.tsx
  apps/consultation-portal/specs/index.spec.tsx
  apps/consultation-portal/types.tsx
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/dto/case.input.ts
Labels: automerge

#10296 fix(service-portal): Tryggingastofnun name
  libs/api/domains/license-service/src/lib/client/disability-license-client/disabilityLicenseMapper.ts
Labels: automerge

#10277 fix(judicial-administration-client): XROAD paths corrected
  .github/CODEOWNERS
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/judicial-administration/src/lib/judicialAdministration.config.ts
Labels: automerge

#10311 fix(infra): Unable to use CNAME for cluster-config endpoint
  apps/air-discount-scheme/backend/infra/backend.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/environments.ts
Labels: automerge

#10309 fix(j-s): Contentful Key
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
Labels: automerge

#10307 chore(web): Swap Directorate of Immigration Livechat with IBM Watson
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge

#10312 fix(parental-leave): change companyId validation
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#10297 fix(transport authority applications): License plate - allow rearType to be empty, Change co-owner - validation national id
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/PickPlateSize.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/clients/transport-authority/vehicle-plate-ordering/src/lib/vehiclePlateOrderingClient.service.ts
Labels: automerge

#10300 fix(license-service): remove date check for picture
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicense.spec.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
Labels: automerge

#10316 fix(applications): General Fishing License QA
  libs/application/templates/general-fishing-license/src/fields/components/ShipInformation/index.tsx
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/fishingLicenseFurtherInfoSection.ts
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicenseFurtherInformation.ts
  libs/application/templates/general-fishing-license/src/utils/licenses.ts
  libs/clients/fishing-license/src/lib/apiConfiguration.ts
Labels: automerge

#9892 fix(search-indexer): Increase performance of search-indexer
  apps/services/search-indexer/infra/search-indexer-service.ts
  apps/web/components/PageLoader/PageLoader.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/cms/src/lib/search/importers/utils.ts
  libs/content-search-indexer/src/environments/environment.ts
  libs/content-search-indexer/src/lib/indexing.controller.ts
  libs/content-search-indexer/src/lib/indexing.service.ts
  libs/content-search-toolkit/src/services/elastic.service.ts
Labels: automerge

#10229 feat(application-system): Application history
  SUMMARY.md
  apps/application-system/api/migrations/20230202110016-application-history.js
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/dto/application.response.dto.ts
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  apps/application-system/api/src/app/modules/application/e2e/mockFeatureFlagService.ts
  apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
  apps/application-system/form/src/routes/Applications.tsx
  handbook/misc/assets/application-history.jpeg
  handbook/misc/assets/application-pending-action.jpeg
  libs/api/domains/application/src/lib/application.model.ts
  libs/api/domains/application/src/lib/application.resolver.ts
  libs/application/api/history/.eslintrc.json
  libs/application/api/history/README.md
  libs/application/api/history/jest.config.js
  libs/application/api/history/project.json
  libs/application/api/history/src/index.ts
  libs/application/api/history/src/lib/dto/history.dto.ts
  libs/application/api/history/src/lib/history.model.ts
  libs/application/api/history/src/lib/history.module.ts
  libs/application/api/history/src/lib/history.service.ts
  libs/application/api/history/src/lib/historyBuilder.ts
  libs/application/api/history/tsconfig.json
  libs/application/api/history/tsconfig.lib.json
  libs/application/api/history/tsconfig.spec.json
  libs/application/core/README.md
  libs/application/core/src/lib/ApplicationTemplateHelper.spec.ts
  libs/application/core/src/lib/ApplicationTemplateHelper.ts
  libs/application/core/src/lib/messages.ts
  libs/application/graphql/src/lib/fragments/application.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/application/application.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/application/application.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/reference-template/emailGenerators/assignEmail.ts
  libs/application/templates/data-protection-complaint/src/constants/index.ts
  libs/application/templates/data-protection-complaint/src/lib/DataProtectionComplaintTemplate.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/application.ts
  libs/application/templates/reference-template/src/dataProviders/index.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/Application.ts
  libs/application/types/src/lib/StateMachine.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/application-history.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/index.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/feature-flags/src/lib/features.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCardHistory/ActionCardHistory.tsx
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.tsx
  libs/island-ui/core/src/lib/FormStepper/FormStepper.css.ts
  libs/island-ui/core/src/lib/FormStepper/HistorySection.tsx
  libs/island-ui/core/src/lib/FormStepper/HistoryStepper.tsx
  libs/island-ui/core/src/lib/FormStepper/Section.css.ts
  libs/island-ui/core/src/lib/FormStepper/SectionNumber/SectionNumber.css.ts
  libs/island-ui/core/src/lib/FormStepper/SectionNumber/SectionNumber.tsx
  libs/service-portal/graphql/src/lib/fragments/application.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, deploy-feature

#10252 feat(user-notification): Key value arg objects
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/openApi.ts
  charts/islandis/values.staging.yaml
Labels: automerge

#10308 fix(parental-leave): parent with no consent should not see a child info
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts
  libs/application/templates/parental-leave/src/forms/InReview.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#10289 feat(ids-admin): Graphql layer for applications
  libs/api/domains/auth-admin/src/lib/application/application.resolver.ts
  libs/api/domains/auth-admin/src/lib/application/applications-environment.resolver.ts
  libs/api/domains/auth-admin/src/lib/application/applications.service.ts
  libs/api/domains/auth-admin/src/lib/application/dto/applications-payload.ts
  libs/api/domains/auth-admin/src/lib/application/dto/applications.input.ts
  libs/api/domains/auth-admin/src/lib/application/models/application.model.ts
  libs/api/domains/auth-admin/src/lib/application/models/applications-environment.model.ts
  libs/api/domains/auth-admin/src/lib/auth-admin.module.ts
Labels: automerge

#10278 feat(web): Add header for 'gev' organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/GevTheme/index.ts
Labels: automerge

#10319 feat(services-auth-admin-api): Adding tests for tenants endpoint
  apps/services/auth/admin-api/jest.config.js
  apps/services/auth/admin-api/src/app/tenants/test/me-tenants.auth.spec.ts
  apps/services/auth/admin-api/src/app/tenants/test/me-tenants.spec.ts
  apps/services/auth/delegation-api/src/app/clients/clients.controller.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.auth.spec.ts
  apps/services/auth/delegation-api/src/app/domains/test/domains.controller.spec.ts
  apps/services/auth/delegation-api/test/types.ts
  libs/auth-api-lib/src/lib/resources/tenants.service.ts
  libs/testing/nest/src/index.ts
  libs/testing/nest/src/lib/setup.ts
  libs/testing/nest/src/lib/types.ts
Labels: automerge

#10332 chore(deps): Deduplicate deep-equal and color
  package.json
  yarn.lock
Labels: automerge

#10291 feat(api-domains-auth-admin): Multi env admin api with merging
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/auth-admin-web/proxy.config.json
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/app/modules/access/access.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-allowed-scope.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-claim.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-grant-type.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-post-logout-redirect-uri.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/client-secret.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/clients.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/cors.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/idp-restriction.controller.ts
  apps/services/auth/admin-api/src/app/modules/clients/redirect-uri.controller.ts
  apps/services/auth/admin-api/src/app/modules/grant-types/grant-types.controller.ts
  apps/services/auth/admin-api/src/app/modules/idp-provider/idp-provider.controller.ts
  apps/services/auth/admin-api/src/app/modules/personal-representative/personal-representative.controller.ts
  apps/services/auth/admin-api/src/app/modules/resources/resources.controller.ts
  apps/services/auth/admin-api/src/app/modules/translation/translation.controller.ts
  apps/services/auth/admin-api/src/app/modules/users/user-identities.controller.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  apps/services/auth/admin-api/src/main.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/dsl.ts
  infra/src/uber-charts/islandis.ts
  libs/api/domains/auth-admin/src/lib/application/application.resolver.ts
  libs/api/domains/auth-admin/src/lib/application/applications.service.ts
  libs/api/domains/auth-admin/src/lib/application/models/application.model.ts
  libs/api/domains/auth-admin/src/lib/application/models/applications-environment.model.ts
  libs/api/domains/auth-admin/src/lib/auth-admin.module.ts
  libs/api/domains/auth-admin/src/lib/models/environment.ts
  libs/api/domains/auth-admin/src/lib/tenant/models/tenant-environment.model.ts
  libs/api/domains/auth-admin/src/lib/tenant/models/tenant.model.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenant-environment.resolver.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenant.resolver.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.spec.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.ts
  libs/auth-api-lib/src/lib/resources/dto/tenant.dto.ts
  libs/auth-nest-tools/src/lib/auth.module.ts
  libs/clients/auth/admin-api/.eslintrc.json
  libs/clients/auth/admin-api/README.md
  libs/clients/auth/admin-api/jest.config.js
  libs/clients/auth/admin-api/project.json
  libs/clients/auth/admin-api/src/index.ts
  libs/clients/auth/admin-api/src/lib/apis.ts
  libs/clients/auth/admin-api/src/lib/auth-admin-api-client.config.ts
  libs/clients/auth/admin-api/src/lib/auth-admin-api-client.module.ts
  libs/clients/auth/admin-api/tsconfig.json
  libs/clients/auth/admin-api/tsconfig.lib.json
  libs/clients/auth/admin-api/tsconfig.spec.json
  libs/shared/types/src/index.ts
  libs/shared/types/src/lib/environment.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, high priority, merge.priority_merge_label

#10338 fix(applications): hide application data from actioncard
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#10330 fix(system-e2e): Fix broken sessions tests
  apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
  scripts/_run-aws-eks-commands.js
Labels: automerge

#10344 fix(services-auth-admin-api): Add issuer url env variable
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge, merge.priority_merge_label

#10347 fix(services-auth-admin-api): Add issuer url env variable (#10344)
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#10345 fix(application-system): Hotfix hide application data
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#10346 fix(system-e2e): Fix broken sessions tests (#10330)
  apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
  scripts/_run-aws-eks-commands.js
Labels: automerge, merge.priority_merge_label

#10295 feat(j-s): Add police case files to case files screen in indictments
  apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.controller.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/uploadPoliceCaseFile.spec.ts
  apps/judicial-system/web/graphql/sharedGql.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  libs/judicial-system/types/src/lib/policeFile.ts
Labels: automerge

#10315 chore(j-s): Add a no-index meta tag
  apps/judicial-system/web/pages/_app.tsx
Labels: automerge

#10329 chore(j-s): Improves Slack Notifications for Indictments
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
Labels: automerge

#10320 feat: get query for subscriptions
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/pages/test.tsx
  apps/consultation-portal/project.json
  apps/consultation-portal/screens/Case/getCase.graphql.ts
  apps/consultation-portal/screens/Home/getAllCases.graphql.ts
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/screens/Subscriptions/getAllCases.graphql.ts
  apps/consultation-portal/screens/Test/Home.tsx
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#10348 fix(dsl): missing db jobs on identical db names
  apps/services/sessions/infra/sessions.ts
  infra/src/dsl/output-generators/feature-jobs.ts
Labels: automerge, autoupdate

#10355 fix(services-auth-admin-api): Add nginx-ingress-external. (#10350)
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#10354 fix(consultation-portal): fixing layout issues with hero banner
  apps/consultation-portal/components/HeroBanner/HeroBanner.css.ts
  apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
  apps/consultation-portal/components/HeroBanner/HeroTiles.tsx
  apps/consultation-portal/components/StatisticBox/StatisticBox.css.ts
Labels: automerge

#10349 feat(financial-statements-inao): Better error message when financial limit is null
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/IncomeLimitField.tsx
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
Labels: automerge

#10331 feat(consultation-portal): consultation-portal_graphql-for-types
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/getAllTypes.ts
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/helpers/tableRowBackgroundColor.ts
  libs/api/domains/consultation-portal/src/lib/api-domains-consultation-portal.module.ts
  libs/api/domains/consultation-portal/src/lib/models/allTypesResult.model.ts
  libs/api/domains/consultation-portal/src/lib/types/types.resolver.ts
  libs/api/domains/consultation-portal/src/lib/types/types.service.ts
  libs/clients/consultation-portal/src/lib/apiConfiguration.ts
  libs/clients/consultation-portal/src/lib/consultationPortalClient.module.ts
Labels: automerge

#10356 feat: case renamed
  libs/api/domains/consultation-portal/src/lib/documents/documents.resolver.ts
  libs/api/domains/consultation-portal/src/lib/documents/documents.service.ts
Labels: automerge

#10358 fix(service-portal): loftbru not rendering
  libs/service-portal/air-discount/src/module.tsx
  libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx
Labels: automerge

#10339 feat(samradsgatt): Kam 941 api query for getting and filtering items on the frontpage
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/EybrowsWithSeperator/EybrowsWithSeperator.tsx
  apps/consultation-portal/screens/Home/getCases.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/dto/cases.input.ts
Labels: automerge

#10363 fix: case renamed (#10356)
  libs/api/domains/consultation-portal/src/lib/documents/documents.resolver.ts
  libs/api/domains/consultation-portal/src/lib/documents/documents.service.ts
Labels: automerge

#10364 fix(service-portal): loftbru not rendering (#10358)
  libs/service-portal/air-discount/src/module.tsx
  libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx
Labels: automerge

#10369 fix(general-petition): tweaka links
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
Labels: automerge

#10362 feat: samradsgatt/kam 923 api get all reviews for case
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/getAdvices.graphql.ts
  apps/consultation-portal/screens/Home/getAllTypes.graphql.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/dto/case.input.ts
Labels: automerge

#10372 fix(services-auth-admin-api): Undo multi issuer on auth admin api (#10371)
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.ts
Labels: automerge

#10368 chore(search-indexer): Change progress deadline to be 25 minutes
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#10376 fix(parental-leave): Sync VMST period when start is less then date 20…
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#10378 feat(web): Allow faqlists inside stepper subtitles
  apps/web/components/Stepper/utils.ts
  apps/web/screens/queries/Article.ts
Labels: automerge

#10374 chore(ci): auto commit dirty charts
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest.yml
  infra/scripts/ci/git-check-dirty.sh
  scripts/ci/20_check-formatting.sh
  scripts/gitbook.js
Labels: automerge

#10379 fix(driving-school): date format in showing schools
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
  libs/application/templates/driving-school-confirmation/src/graphql/queries.ts
Labels: automerge

#10389 fix(passport): child fix
  libs/application/templates/passport/src/forms/infoSection/childsPersonalInfo.ts
Labels: automerge

#10386 ci(autocommit): autocommit code generated files, gitbook, charts, nx format
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest.yml
  infra/scripts/ci/git-check-dirty.sh
  scripts/ci/20_check-formatting.sh
  scripts/gitbook.js
Labels: automerge

#10394 fix(search-indexer): Revert "fix(search-indexer): Increase performance of search-indexer (#9892)"
  apps/services/search-indexer/infra/search-indexer-service.ts
  apps/web/components/PageLoader/PageLoader.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/cms/src/lib/search/importers/utils.ts
  libs/content-search-indexer/src/environments/environment.ts
  libs/content-search-indexer/src/lib/indexing.controller.ts
  libs/content-search-indexer/src/lib/indexing.service.ts
  libs/content-search-toolkit/src/services/elastic.service.ts
Labels: automerge

#10397 fix(dsl): missing db jobs on identical db names (#10348)
  apps/services/sessions/infra/sessions.ts
  infra/src/dsl/output-generators/feature-jobs.ts
Labels: automerge

#10357 feat(j-s): Different measurement units for 2 substances
  apps/judicial-system/web/src/components/Substances/Substances.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCountSubstanceEnum.strings.ts
Labels: automerge

#10390 fix(driving-license-book-api): Simplify get student
  libs/clients/driving-license-book/src/clientConfig.json
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
  libs/clients/driving-license-book/src/utils/mappers.ts
Labels: automerge

#10399 fix(license-service): fix disability mapping
  libs/api/domains/license-service/src/lib/client/disability-license-client/disabilityLicenseMapper.ts
Labels: automerge

#10403 fix(web): Broken pages on web due to input props change
  apps/web/components/Regulations/RegulationsSearchSection.tsx
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
  apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
  libs/shared/connected/src/lib/LawyersList/LawyersList.tsx
  libs/shared/connected/src/lib/RealEstateAgentsList/RealEstateAgentsList.tsx
Labels: automerge

#10402 fix(web): Fix props for Input component on web causing 500 errors on prod
  apps/web/components/Regulations/RegulationsSearchSection.tsx
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
  apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
  libs/shared/connected/src/lib/LawyersList/LawyersList.tsx
  libs/shared/connected/src/lib/RealEstateAgentsList/RealEstateAgentsList.tsx
Labels: automerge

#10404 fix(service-portal): remove logheimilisforeldri
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
Labels: automerge

#10405 feat(financial-statements-inao): Display digital signing reminder on done screen
  libs/application/templates/financial-statements-inao/src/fields/Done/Success.tsx
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
  libs/application/templates/financial-statements-inao/src/lib/utils/helpers.ts
Labels: automerge

#10411 fix(service-portal): remove logheimilisforeldri (#10404)
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
Labels: automerge

#10400 fix(search-indexer): Revert "fix(search-indexer): Revert "fix(search-indexer): Increase performance of search-indexer (#9892)" (#10394)"
  apps/services/search-indexer/infra/search-indexer-service.ts
  apps/web/components/PageLoader/PageLoader.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/cms/src/lib/search/importers/utils.ts
  libs/content-search-indexer/src/environments/environment.ts
  libs/content-search-indexer/src/lib/indexing.controller.ts
  libs/content-search-indexer/src/lib/indexing.service.ts
  libs/content-search-toolkit/src/services/elastic.service.ts
Labels: automerge

#10325 chore: Add new codecov components
  codecov.yml
Labels: automerge

#10415 fix(auth-admin-api): Use nestjs global prefix instead of ingress rewrite.
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/main.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#10413 feat(consultation-portal): KAM-744
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/EyebrowsWithSeperator/EyebrowsWithSeperator.tsx
  apps/consultation-portal/components/Filter/Filter.tsx
  apps/consultation-portal/components/Filterbox/Filterbox.tsx
  apps/consultation-portal/components/SearchAndFilter/SearchAndFilter.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/getCases.graphql.ts
  apps/consultation-portal/screens/Home/getInitFilterValues.ts
  apps/consultation-portal/types/enums.ts
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#10370 feat(ids-admin): Create Application form
  libs/api/domains/auth-admin/src/lib/application/application.resolver.ts
  libs/api/domains/auth-admin/src/lib/application/applications.service.ts
  libs/api/domains/auth-admin/src/lib/application/dto/createApplication.input.ts
  libs/api/domains/auth-admin/src/lib/application/models/application.model.ts
  libs/api/domains/auth-admin/src/lib/models/applicationType.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenant.resolver.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.ts
  libs/portals/admin/ids-admin/jest.config.js
  libs/portals/admin/ids-admin/src/components/Applications/Applications.tsx
  libs/portals/admin/ids-admin/src/components/Modal/Modal.css.ts
  libs/portals/admin/ids-admin/src/components/Modal/Modal.tsx
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.graphql
  libs/portals/admin/ids-admin/src/components/forms/CreateApplication/CreateApplication.action.spec.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateApplication/CreateApplication.action.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateApplication/CreateApplication.graphql
  libs/portals/admin/ids-admin/src/components/forms/CreateApplication/CreateApplication.tsx
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.graphql
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.loader.ts
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.tsx
  libs/portals/core/src/index.ts
  libs/portals/core/src/utils/router/createModuleRoutes.tsx
  libs/portals/core/src/utils/router/wrappedLoaderFn.ts
  libs/portals/core/src/utils/router/wrappers.ts
  libs/react-spa/shared/jest.config.js
  libs/react-spa/shared/src/lib/validate.ts
  package.json
  yarn.lock
Labels: automerge

#10420 fix(ci): prepare base tag to use new convention
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge, high priority, merge.priority_merge_label

#10426 fix(ci): New docker_tag convention
  .github/workflows/push.yml
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge

#10423 feat(web): Keep state between page change for PowerBi Slices
  apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx
Labels: automerge

#10433 feat(web): Hotfix keep state between pages for powerbi slices
  apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx
Labels: automerge

#10398 fix(general-petitions): UI fixes in service portal
  libs/service-portal/petitions/project.json
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/Petitions/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsAdmin/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewPetitionAdmin/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
Labels: automerge

#10430 feat: minor fix on data structure in case view
  apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/components/StackedTitleAndDescription/StackedTitleAndDescription.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/getCase.graphql.ts
  apps/consultation-portal/types/viewModels.ts
Labels: automerge

#10392 feat(samradsgatt): Add pagination my reviews
  apps/consultation-portal/components/Pagination/Pagination.css.ts
  apps/consultation-portal/components/Pagination/Pagination.tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Home/Home.tsx
Labels: automerge

#10434 fix(parental leave): sync period
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#10442 fix(parental-leave): pruned days
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#10435 feat(consultation-portal): SEO component
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/components/SEO/SEO.tsx
  apps/consultation-portal/pages/tolfraedi.tsx
  apps/consultation-portal/pages/um/index.tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#10445 feat(Atr): Tree slider for carbon emission
  libs/application/templates/alcohol-tax-redemption/src/assets/Tree.tsx
  libs/application/templates/alcohol-tax-redemption/src/fields/Components/SliderWithGraphic/Slider/Slider.css.ts
  libs/application/templates/alcohol-tax-redemption/src/fields/Components/SliderWithGraphic/Slider/Slider.tsx
  libs/application/templates/alcohol-tax-redemption/src/fields/Components/SliderWithGraphic/Slider/utils.ts
  libs/application/templates/alcohol-tax-redemption/src/fields/TreeSlider/TreeSlider.css.ts
  libs/application/templates/alcohol-tax-redemption/src/fields/TreeSlider/TreeSlider.tsx
  libs/application/templates/alcohol-tax-redemption/src/fields/index.ts
  libs/application/templates/alcohol-tax-redemption/src/forms/draft.ts
  libs/application/templates/alcohol-tax-redemption/src/index.ts
  libs/application/templates/alcohol-tax-redemption/src/lib/AlcoholTaxRedemptionTemplate.ts
  libs/application/templates/alcohol-tax-redemption/src/lib/constants.ts
  libs/application/templates/alcohol-tax-redemption/src/lib/messages/draft.ts
Labels: automerge

#10448 fix(auth-admin-web): Fixes in auth-api-lib for auth-admin-web
  apps/auth-admin-web/entities/dtos/identity-resource.dto.ts
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/auth-api-lib/src/lib/resources/dto/identity-resources.dto.ts
  libs/auth-api-lib/src/lib/resources/models/identity-resource.model.ts
  libs/auth-api-lib/src/lib/resources/resources.service.ts
Labels: automerge

#10444 feat(sessions): Add procedure for deleting old sessions.
  apps/services/sessions/migrations/20230310141658-add-session-cleanup-proc.js
Labels: automerge

#10449 fix(services-auth-ids-api): Revert removing of raw: true for clients
  libs/auth-api-lib/src/lib/clients/clients.service.ts
Labels: automerge

#10428 docs: Pósthólf translation fix
  handbook/technical-overview/postholf/README.md
Labels: automerge

#10451 fix(e2e): Hide onboarding in service portal tests
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts
Labels: automerge

#10453 chore(applications): Logo header url change
  apps/application-system/form/src/components/Header/Header.tsx
Labels: automerge

#10321 feat(auth-admin): Get tenant by id
  apps/services/auth/admin-api/src/app/tenants/me-tenants.controller.ts
  apps/services/auth/admin-api/src/app/tenants/test/me-tenants.spec.ts
  libs/auth-api-lib/src/lib/resources/tenants.service.ts
Labels: automerge

#10452 chore(applications): Conclusion screen updates
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/conclusionSection.ts
  libs/application/templates/accident-notification/src/lib/messages/conclusion.ts
  libs/application/templates/alcohol-tax-redemption/src/forms/overview.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintFormInReview.ts
  libs/application/templates/funding-government-projects/src/forms/FundingGovernmentProjectsForm.ts
  libs/application/templates/funding-government-projects/src/forms/FundingGovernmentProjectsFormSubmitted.ts
  libs/application/templates/funding-government-projects/src/lib/messages/submitted.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePaymentForm.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseSubmittedForm.ts
  libs/application/templates/general-fishing-license/src/lib/messages/conclusion.ts
  libs/application/templates/health-insurance/src/forms/ConfirmationScreen.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/health-insurance/src/forms/MissingInfoForm.ts
  libs/application/templates/institution-collaboration/src/forms/application.ts
  libs/application/templates/institution-collaboration/src/forms/approved.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/templates/login-service/src/forms/LoginServiceFormSubmitted.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanSubmittedForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/conclusion.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/Confirmation.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.tsx
  libs/application/ui-forms/src/index.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
  libs/application/ui-forms/src/lib/formConclusionSection/messages.ts
Labels: automerge

#10457 fix(auth-admin-web): Fix get for api resources in auth admin api.
  libs/auth-api-lib/src/lib/resources/resources.service.ts
Labels: automerge

#10458 fix(web): Update input props for Services page
  apps/web/screens/Organization/Services.tsx
Labels: automerge

#10460 fix(web): Hotfix - Update input props for Services page (#10458)
  apps/web/screens/Organization/Services.tsx
Labels: automerge

#10450 chore(deps): Upgrade dd-trace
  package.json
  yarn.lock
Labels: automerge

#10455 fix(services-auth-admin-api): Fixes api path and update methods in admin api.
  apps/auth-admin-web/entities/dtos/identity-resource.dto.ts
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/main.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/auth-api-lib/src/lib/resources/dto/identity-resources.dto.ts
  libs/auth-api-lib/src/lib/resources/models/identity-resource.model.ts
  libs/auth-api-lib/src/lib/resources/resources.service.ts
Labels: automerge

#10333 chore(deps): Upgrade react-datepicker and popper
  libs/island-ui/core/src/index.ts
  libs/island-ui/core/src/lib/DatePicker/DatePicker.css.ts
  libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
  libs/island-ui/core/src/lib/DatePicker/react-datepicker.css.ts
  libs/island-ui/core/src/lib/DatePicker/types.ts
  libs/island-ui/core/src/lib/Input/ErrorMessage.tsx
  libs/island-ui/core/src/lib/Input/Input.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/Finance.css.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/sessions/src/components/SessionFilter/SessionFilter.css.ts
  libs/service-portal/sessions/src/components/SessionFilter/SessionFilter.tsx
  libs/testing/fixtures/src/index.ts
  package.json
  yarn.lock
Labels: automerge

#10326 feat(nest): Add a new nest/core library
  SUMMARY.md
  apps/services/license-api/src/app/modules/license/license.controller.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createNotification.dto.ts
  apps/services/user-profile/src/app/user-profile/dto/userDeviceToken.dto.ts
  libs/nest/core/.eslintrc.json
  libs/nest/core/README.md
  libs/nest/core/jest.config.js
  libs/nest/core/project.json
  libs/nest/core/src/index.ts
  libs/nest/core/src/lib/decorators/nationalId.decorator.ts
  libs/nest/core/src/lib/validators/isNationalId.decorator.ts
  libs/nest/core/tsconfig.json
  libs/nest/core/tsconfig.lib.json
  libs/nest/core/tsconfig.spec.json
  libs/nest/validators/.babelrc
  libs/nest/validators/.eslintrc.json
  libs/nest/validators/README.md
  libs/nest/validators/babel-jest.config.json
  libs/nest/validators/jest.config.js
  libs/nest/validators/project.json
  libs/nest/validators/src/index.ts
  libs/nest/validators/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#10456 feat(consultation-portal): KAM-956 loading dots
  apps/consultation-portal/screens/Home/Home.tsx
Labels: automerge

#10443 feat(samradsgatt): fixing layout issues for um page
  apps/consultation-portal/components/About/MainColumn.tsx
  apps/consultation-portal/components/About/RightSideColumn.tsx
  apps/consultation-portal/pages/um/index.tsx
Labels: automerge

#10463 chore(Application-system): Allow client nationalid claim for production
  apps/application-system/api/src/environments/environment.ts
Labels: automerge

#10440 fix(j-s): Fix upload functionality
  apps/judicial-system/web/src/routes/Court/Indictments/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
Labels: automerge

#9835 fix(estate): Estate application enable upload data
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/types/index.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#10352 feat(auth-ids): Return domain with apiscope and identityresource.
  apps/services/auth/ids-api/src/app/resources/identity-resource.dto.ts
  apps/services/auth/ids-api/src/app/resources/identity-resource.mapper.ts
  apps/services/auth/ids-api/src/app/resources/resources.controller.ts
  libs/auth-api-lib/src/lib/resources/models/api-scope-group.model.ts
  libs/auth-api-lib/src/lib/resources/models/api-scope.model.ts
  libs/auth-api-lib/src/lib/resources/models/domain.model.ts
  libs/auth-api-lib/src/lib/resources/models/identity-resource.model.ts
  libs/auth-api-lib/src/lib/resources/resources.service.ts
Labels: automerge

#10387 feat(auth-nest-tools): Add support for multiple issuers
  apps/github-actions-cache/src/app/auth.ts
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/application/template-api-modules/jest.config.js
  libs/auth-nest-tools/jest.config.js
  libs/auth-nest-tools/src/lib/create-key-provider.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/nest/problem/jest.config.js
  package.json
  yarn.lock
Labels: automerge

#10464 feat(consultation-portal): Kam 924 api get all my reviews query
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Advices/getAllUserAdvices.graphql.ts
  apps/consultation-portal/types/interfaces.ts
  libs/api/domains/consultation-portal/src/lib/api-domains-consultation-portal.module.ts
  libs/api/domains/consultation-portal/src/lib/models/userAdviceResult.model.ts
  libs/api/domains/consultation-portal/src/lib/user/userAdvice.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/userAdvice.services.ts
  libs/clients/consultation-portal/src/lib/apiConfiguration.ts
  libs/clients/consultation-portal/src/lib/consultationPortalClient.module.ts
Labels: automerge

#10474 fix(license-service): existing pkpass fix
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
  libs/clients/smartsolutions/src/lib/graphql/queries/queries.ts
Labels: automerge

#10478 fix(web): Prevent 500 error on article page if there is no category set
  apps/web/screens/Article/Article.tsx
Labels: automerge

#10479 feat(transport authority applications): Update which warnSever we look at for validation
  libs/clients/transport-authority/vehicle-operators/src/lib/vehicleOperatorsClient.service.ts
  libs/clients/transport-authority/vehicle-plate-ordering/src/lib/vehiclePlateOrderingClient.service.ts
Labels: automerge

#10483 fix(license-service): Hotfix - update graphql request for existing pkpass
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
  libs/clients/smartsolutions/src/lib/graphql/queries/queries.ts
Labels: automerge

#10485 feat: add link to download files
  apps/consultation-portal/components/ReviewCard/ReviewCard.css.ts
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/screens/Case/getAdvices.graphql.ts
Labels: automerge

#10471 feat(consultation-portal): KAM-962 Only get cases that are subscribable
  apps/consultation-portal/components/BreadcrumbsWithMobileDivider/index.ts
  apps/consultation-portal/components/SearchAndSort/SearchAndSort.tsx
  apps/consultation-portal/components/Tab/TabContent.tsx
  apps/consultation-portal/components/Table/SubscriptionTable.tsx
  apps/consultation-portal/components/Table/SubscriptionTableItem.tsx
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/screens/Subscriptions/getInitValues.ts
  apps/consultation-portal/screens/Subscriptions/queries.graphql.ts
  apps/consultation-portal/screens/Subscriptions/tabsList.tsx
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/helpers/getInitFilterValues.ts
  apps/consultation-portal/utils/helpers/index.ts
Labels: automerge

#10487 feat(application-system): Fix header scaling
  libs/application/ui-shell/src/components/ErrorShell.tsx
  libs/application/ui-shell/src/components/FormStepper.tsx
  libs/island-ui/core/src/lib/Header/Header.tsx
Labels: automerge

#9750 test(j-s): Implement first playwright test
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/support/urls.ts
  apps/system-e2e/src/tests/islandis/judicial-system/smoke/restriction-case.spec.ts
Labels: automerge

#10490 chore(infra): Change min replicas for various deployments and more cost optimizations
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  apps/consultation-portal/infra/samradsgatt.ts
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/portals/admin/infra/portals-admin.ts
  apps/service-portal/infra/service-portal.ts
  apps/web/infra/web.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#10494 chore(infra): Tune requests CPU to more legitimate averages
  apps/air-discount-scheme/api/infra/api.ts
  apps/air-discount-scheme/backend/infra/backend.ts
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/initContainer.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#10493 fix(consultation-portal): KAM-1005_Change Cases API to reflect changes on Backend
  apps/consultation-portal/components/Pagination/Pagination.tsx
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/test.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/getAllCases.graphql.ts
  apps/consultation-portal/screens/Home/getCases.graphql.ts
  apps/consultation-portal/screens/Subscriptions/getInitValues.ts
  apps/consultation-portal/screens/Subscriptions/queries.graphql.ts
  apps/consultation-portal/screens/Test/Home.tsx
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/dto/cases.input.ts
  libs/api/domains/consultation-portal/src/lib/models/casesAggregateResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#10323 chore(j-s): Make workingCase non-optional in PageLayout component
  apps/judicial-system/web/messages/Core/pageLayout.ts
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/routes/Admin/Admin.strings.ts
  apps/judicial-system/web/src/routes/Admin/ChangeUser/ChangeUser.tsx
  apps/judicial-system/web/src/routes/Admin/NewUser/NewUser.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.css.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.css.ts
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
Labels: automerge

#10384 chore(j-s): Refactor feature functionality
  apps/judicial-system/web/src/components/FeatureProvider/FeatureProvider.tsx
Labels: automerge

#10409 fix(j-s): Refactor indictment counts substances
  apps/judicial-system/web/src/components/Substances/Substances.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substance/Substance.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/Substances.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/Substances.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/Substances.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/SubstancesEnum.strings.ts
Labels: automerge

#10417 chore(j-s): Fix slow UI update on radio buttons on slow networks
  apps/judicial-system/web/src/components/Decision/Decision.tsx
  apps/judicial-system/web/src/components/SelectSubpoenaType/SelectSubpoenaType.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/components/AppealSections/AppealSections.tsx
Labels: automerge
