Repository island-is/island.is, pull requests merged in 2023-02, with the labels that each got.

#9789 feat(web): Reload page on online chat link click
  apps/web/components/ServiceWeb/Footer/Footer.tsx
Labels: automerge

#9695 feat(transport authority order vehicle plate): Add validation
  libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
  libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.module.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-license-plate/order-vehicle-license-plate.service.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/hooks/useLazyVehicleDetails.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/information.ts
  libs/clients/transport-authority/vehicle-plate-ordering/src/clientConfig.json
  libs/clients/transport-authority/vehicle-plate-ordering/src/lib/vehiclePlateOrderingClient.service.ts
  libs/clients/transport-authority/vehicle-plate-ordering/src/lib/vehiclePlateOrderingClient.types.ts
Labels: automerge

#9792 fix(mortgage certificate): ready for production
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
Labels: automerge

#9793 fix(mortgage certificate): ready for production
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
Labels: automerge

#9799 fix(applications): Remove beta message from the application
  libs/application/templates/public-debt-payment-plan/src/fields/FormConclusion/index.tsx
  libs/application/templates/public-debt-payment-plan/src/forms/BetaTestSection.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/betaTest.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/index.ts
Labels: automerge

#9791 feat(web): Add terms and conditions to footer links
  apps/web/components/ServiceWeb/Footer/Footer.tsx
  apps/web/layouts/main.tsx
  libs/island-ui/core/src/lib/Footer/Footer.tsx
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/Facebook.tsx
Labels: automerge

#9763 fix(erfdafjarskyrsla): Efs improvements
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalBusiness/index.tsx
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalDebts/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsOverview/index.tsx
  libs/application/templates/inheritance-report/src/fields/PrintScreen/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/fields/styles.css.ts
  libs/application/templates/inheritance-report/src/forms/assets.ts
  libs/application/templates/inheritance-report/src/forms/business.ts
  libs/application/templates/inheritance-report/src/forms/debts.ts
  libs/application/templates/inheritance-report/src/forms/heirs.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#9803 fix(ui): Datepicker month overlap fix
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
Labels: automerge

#9806 fix(mortgage certificate): delegation fix
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennNotifyError.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennSubmitRequestError.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/types/index.ts
  libs/application/templates/mortgage-certificate/src/dataProviders/index.ts
  libs/application/templates/mortgage-certificate/src/forms/MortgageCertificateForm.ts
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
Labels: automerge

#9807 fix(mortgage certificate): delegation fix
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennNotifyError.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/emailGenerators/syslumennSubmitRequestError.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/types/index.ts
  libs/application/templates/mortgage-certificate/src/dataProviders/index.ts
  libs/application/templates/mortgage-certificate/src/forms/MortgageCertificateForm.ts
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
Labels: automerge

#9800 fix(j-s): Fix bugs where incorrect role is set in guard
  apps/judicial-system/backend/src/app/modules/file/guards/rolesRules.ts
Labels: automerge

#9785 feat(financial-statements-inao): API tests
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.spec.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
  libs/clients/financial-statements-inao/src/lib/mocks/cemeteryClientByNationalId.json
  libs/clients/financial-statements-inao/src/lib/mocks/clientTypes.json
  libs/clients/financial-statements-inao/src/lib/mocks/electionInfo.json
  libs/clients/financial-statements-inao/src/lib/mocks/financialTypes.json
  libs/clients/financial-statements-inao/src/lib/mocks/individualClientByNationalId.json
  libs/clients/financial-statements-inao/src/lib/mocks/politicalPartyClientByNationalId.json
  libs/clients/financial-statements-inao/tsconfig.spec.json
Labels: automerge

#9809 fix(transport authority): delegation fix
  libs/application/templates/no-debt-certificate/src/dataProviders/index.ts
  libs/application/templates/no-debt-certificate/src/forms/NoDebtCertificateForm.ts
  libs/application/templates/no-debt-certificate/src/lib/messages.ts
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/externalDataSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/OrderVehicleLicensePlateForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/dataProviders/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/externalData.ts
Labels: automerge

#9811 feat(transport authority applications): Add internalProcuring to VehiclesDetail
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Labels: automerge

#9754 feat(applications): Create application conclusion form
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/public-debt-payment-plan/src/fields/FormConclusion/index.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/index.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanSubmittedForm.ts
  libs/application/templates/public-debt-payment-plan/src/index.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/conclusion.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AlertMessageFormField/AlertMessageFormField.stories.mdx
  libs/application/ui-fields/src/lib/AlertMessageFormField/AlertMessageFormField.tsx
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.mdx
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.tsx
  libs/application/ui-fields/src/lib/MessageWithLinkButtonFormField/MessageWithLinkButtonFormField.stories.mdx
  libs/application/ui-fields/src/lib/MessageWithLinkButtonFormField/MessageWithLinkButtonFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
  libs/application/ui-forms/src/index.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationMultiField.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationSchema.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/index.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/messages.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/types.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
  libs/application/ui-forms/src/lib/formConclusionSection/messages.ts
Labels: automerge

#9804 fix(applications): Slug error handling
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge

#9810 fix(transport authority): delegation fix
  libs/application/templates/no-debt-certificate/src/dataProviders/index.ts
  libs/application/templates/no-debt-certificate/src/forms/NoDebtCertificateForm.ts
  libs/application/templates/no-debt-certificate/src/lib/messages.ts
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/externalDataSection.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/externalDataSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/OrderVehicleLicensePlateForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/dataProviders/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/externalData.ts
Labels: automerge

#9812 feat(transport authority applications): Add internalProcuring to VehiclesDetail
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Labels: automerge

#9731 feat(auth): Add activity endpoint for saving login history
  SUMMARY.md
  apps/services/sessions/.eslintrc.json
  apps/services/sessions/.sequelizerc
  apps/services/sessions/README.md
  apps/services/sessions/docker-compose.yml
  apps/services/sessions/esbuild.json
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/jest.config.js
  apps/services/sessions/migrations/20230123095340-add-sessions.js
  apps/services/sessions/project.json
  apps/services/sessions/sequelize.config.d.ts
  apps/services/sessions/sequelize.config.js
  apps/services/sessions/src/app/app.module.ts
  apps/services/sessions/src/app/sessions.config.ts
  apps/services/sessions/src/app/sessions/create-session.dto.ts
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions.controller.spec.ts
  apps/services/sessions/src/app/sessions/sessions.controller.ts
  apps/services/sessions/src/app/sessions/sessions.module.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  apps/services/sessions/src/app/worker/sessions-processor.ts
  apps/services/sessions/src/app/worker/worker.module.ts
  apps/services/sessions/src/app/worker/worker.ts
  apps/services/sessions/src/buildOpenApi.ts
  apps/services/sessions/src/environments/environment.ts
  apps/services/sessions/src/environments/index.ts
  apps/services/sessions/src/main.ts
  apps/services/sessions/src/openApi.ts
  apps/services/sessions/src/sequelizeConfig.service.ts
  apps/services/sessions/test/session.fixture.ts
  apps/services/sessions/test/set-env-vars.ts
  apps/services/sessions/test/setup.ts
  apps/services/sessions/tsconfig.app.json
  apps/services/sessions/tsconfig.json
  apps/services/sessions/tsconfig.spec.json
  charts/islandis/values.dev.yaml
  infra/src/uber-charts/islandis.ts
  libs/auth-api-lib/seeders/data/scope-sessions.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/sessions-scope.ts
  libs/nest/swagger/src/lib/documentation.decorator.ts
  workspace.json
Labels: automerge, deploy-feature

#9778 fix(air-discount-scheme): Fix breaking e2e test
  apps/system-e2e/src/tests/islandis/air-discount-scheme/smoke/air-discount-scheme.spec.ts
Labels: automerge

#9769 feat(web): Multiple recipients for form submission on the web
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/Form/Form.tsx
  apps/web/screens/queries/fragments.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/communications/src/index.ts
  libs/api/domains/communications/src/lib/communications.config.ts
  libs/api/domains/communications/src/lib/communications.resolver.ts
  libs/api/domains/communications/src/lib/communications.service.spec.ts
  libs/api/domains/communications/src/lib/communications.service.ts
  libs/cms/src/index.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/form.model.ts
Labels: automerge

#9818 feat(web): Read organization footer image urls from cms
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandkjorstjornFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx
Labels: automerge, deploy-feature

#9823 fix(j-s): Handling Received Cases
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/overview.spec.ts
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#9825 feat(j-s): Indictment Count Fields
  apps/judicial-system/api/src/app/modules/indictment-count/dto/updateIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/migrations/20230202164320-update-indictment-count.js
  apps/judicial-system/backend/src/app/modules/indictment-count/dto/updateIndictmentCount.dto.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
Labels: automerge

#9821 feat(sessions): Add get endpoint for sessions.
  apps/services/sessions/migrations/20230202142207-add-index.js
  apps/services/sessions/src/app/app.module.ts
  apps/services/sessions/src/app/sessions/create-session.dto.ts
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions-query.dto.ts
  apps/services/sessions/src/app/sessions/sessions-result.dto.ts
  apps/services/sessions/src/app/sessions/sessions.controller.spec.ts
  apps/services/sessions/src/app/sessions/sessions.controller.ts
  apps/services/sessions/src/app/sessions/sessions.module.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  apps/services/sessions/test/fixture.factory.ts
  apps/services/sessions/test/session.fixture.ts
  libs/testing/fixtures/src/index.ts
Labels: automerge

#9826 feat(sessions): Configure session url for ids.
  apps/services/auth/ids-api/infra/identity-server.ts
  apps/services/sessions/infra/sessions.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
Labels: automerge

#9832 fix(j-s): Modified Notifications
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#9828 fix(parental leave): additional documents layouts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/InReviewSteps/EditsInReviewSteps.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/ReviewSection/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/forms/InReviewAdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/fileUploadValidationSection.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge

#9794 fix(application-templates): Marriage conditions and passport pruning and email
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/assignOtherSpouseEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport/emailGenerators/assignParentBEmail.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/constants.ts
  libs/application/templates/passport/src/lib/messages.ts
Labels: automerge

#9831 fix(j-s): Defender Link
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CopyLinkForDefenderButton/CopyLinkForDefenderButton.tsx
  libs/judicial-system/auth/src/lib/guards/auth.guard.ts
Labels: automerge

#9847 chore(ci): Troubleshoot Github stickman
  .github/actions/package.json
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge

#9837 feat(sessions): Fix infra configuration.
  .github/CODEOWNERS
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#9844 fix(parental-leave): get bankInfo from UserProfile and fix pre-filled phone numbers
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#9856 fix(sessions): Add missing db migrations assets to project.json.
  apps/services/sessions/project.json
Labels: automerge

#9830 fix(j-s): Fixes for Indictment screen
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/stepHelper.tsx
  apps/judicial-system/web/src/utils/utils.spec.tsx
  package.json
  yarn.lock
Labels: automerge

#9845 fix(j-s): Defender Tooltip
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
Labels: automerge

#9854 feat(service-portal): add expiry date to machine license
  libs/api/domains/license-service/src/lib/client/machine-license-client/__mock_data/expiredMachineLicense.json
  libs/api/domains/license-service/src/lib/client/machine-license-client/__mock_data/validMachineLicense.json
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.spec.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/machineLicenseMapper.ts
  libs/api/domains/license-service/tsconfig.json
Labels: automerge

#9858 fix: fixing password mixup in session service
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: high priority

#9753 feat(new application): Update instructor in driving license book
  .github/CODEOWNERS
  libs/application/core/src/lib/institutionMapper.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-book-update-instructor/driving-license-book-update-instructor.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-book-update-instructor/driving-license-book-update-instructor.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-license-book-update-instructor/.babelrc
  libs/application/templates/driving-license-book-update-instructor/.eslintrc.json
  libs/application/templates/driving-license-book-update-instructor/README.md
  libs/application/templates/driving-license-book-update-instructor/jest.config.js
  libs/application/templates/driving-license-book-update-instructor/project.json
  libs/application/templates/driving-license-book-update-instructor/src/assets/Jobs.tsx
  libs/application/templates/driving-license-book-update-instructor/src/dataProviders/index.ts
  libs/application/templates/driving-license-book-update-instructor/src/fields/Confirmation.tsx
  libs/application/templates/driving-license-book-update-instructor/src/fields/index.ts
  libs/application/templates/driving-license-book-update-instructor/src/forms/Confirmation.ts
  libs/application/templates/driving-license-book-update-instructor/src/forms/DrivingLicenseBookUpdateInstructorForm/index.ts
  libs/application/templates/driving-license-book-update-instructor/src/forms/DrivingLicenseBookUpdateInstructorForm/informationSection.ts
  libs/application/templates/driving-license-book-update-instructor/src/forms/DrivingLicenseBookUpdateInstructorForm/prerequisitesSection.ts
  libs/application/templates/driving-license-book-update-instructor/src/index.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/DrivingLicenseBookUpdateInstructorTemplate.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/constants.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/dataSchema.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/application.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/confirmation.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/error.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/externalData.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/index.ts
  libs/application/templates/driving-license-book-update-instructor/src/lib/messages/information.ts
  libs/application/templates/driving-license-book-update-instructor/src/shared/constants.ts
  libs/application/templates/driving-license-book-update-instructor/src/shared/index.ts
  libs/application/templates/driving-license-book-update-instructor/tsconfig.json
  libs/application/templates/driving-license-book-update-instructor/tsconfig.lib.json
  libs/application/templates/driving-license-book-update-instructor/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/clients/driving-license-book/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.config.ts
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.spec.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#9861 fix(sessions): Add bull module as external in esbuild.json
  apps/services/sessions/esbuild.json
Labels: automerge

#9863 fix: removing keepalive from sessions worker
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#9852 feat(financial-statements-inao): E2E tests
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/financial-statements-inao.spec.ts
  libs/application/templates/financial-statements-inao/src/fields/ElectionsInfoFields/IncomeLimitField.tsx
Labels: automerge

#9815 feat(financial-statement-inao): Change lifecycle
  libs/application/templates/financial-statements-inao/src/lib/financialStatementsInao.ts
Labels: automerge

#9817 feat(transfer vehicle ownership): dont validate age company
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/criminal-record/src/fields/OverviewPaymentCharge/index.tsx
  libs/application/templates/criminal-record/src/lib/messages.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/NationalIdWithName/index.tsx
Labels: automerge

#9864 fix: sessions worker missing startup config
  apps/services/sessions/README.md
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/project.json
  apps/services/sessions/src/app/worker/worker.ts
  apps/services/sessions/src/main.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#9868 fix(marriage-conditions): remove duplicate data provider text
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts
Labels: automerge

#9871 fix(marriage-conditions): remove duplicate data provider text (#9868)
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts
Labels: automerge

#9866 fix(financial-statement-inao): prevent refetching of cemetery donations
  libs/application/templates/financial-statements-inao/src/fields/CemetryOperation/cemetryExpenses.tsx
Labels: automerge

#9732 feat(api): New sessions domain
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/services/sessions/src/app/sessions/sessions-query.dto.ts
  apps/services/sessions/src/app/sessions/sessions-result.dto.ts
  apps/services/sessions/src/app/sessions/sessions.controller.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/api/domains/auth/src/index.ts
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/dto/client.input.ts
  libs/api/domains/auth/src/lib/loaders/client.loader.ts
  libs/api/domains/auth/src/lib/models/client.model.ts
  libs/api/domains/identity/src/index.ts
  libs/api/domains/identity/src/lib/identity.loader.ts
  libs/api/domains/identity/src/lib/identity.module.ts
  libs/api/domains/sessions/.eslintrc.json
  libs/api/domains/sessions/README.md
  libs/api/domains/sessions/jest.config.js
  libs/api/domains/sessions/project.json
  libs/api/domains/sessions/src/index.ts
  libs/api/domains/sessions/src/lib/dto/paginated-session.response.ts
  libs/api/domains/sessions/src/lib/dto/sessions.input.ts
  libs/api/domains/sessions/src/lib/models/session.model.ts
  libs/api/domains/sessions/src/lib/services/sessions.service.ts
  libs/api/domains/sessions/src/lib/sessions-module.ts
  libs/api/domains/sessions/src/lib/sessions.resolver.ts
  libs/api/domains/sessions/tsconfig.json
  libs/api/domains/sessions/tsconfig.lib.json
  libs/api/domains/sessions/tsconfig.spec.json
  libs/clients/identity/src/lib/identityClient.module.ts
  libs/clients/sessions/.eslintrc.json
  libs/clients/sessions/README.md
  libs/clients/sessions/jest.config.js
  libs/clients/sessions/project.json
  libs/clients/sessions/src/index.ts
  libs/clients/sessions/src/lib/api-configuration.ts
  libs/clients/sessions/src/lib/apis.ts
  libs/clients/sessions/src/lib/clients-sessions.module.ts
  libs/clients/sessions/src/lib/sessions-client.config.ts
  libs/clients/sessions/tsconfig.json
  libs/clients/sessions/tsconfig.lib.json
  libs/clients/sessions/tsconfig.spec.json
  libs/nest/pagination/README.md
  libs/nest/pagination/src/index.ts
  libs/nest/pagination/src/lib/dto/pageinfo.dto.ts
  libs/nest/pagination/src/lib/graphql/paginated.response.ts
  libs/nest/pagination/src/lib/graphql/pagination.input.ts
  libs/nest/pagination/src/lib/types/order.ts
  libs/nest/pagination/tsconfig.lib.json
  tsconfig.base.json
  workspace.json
Labels: automerge, merge.priority_merge_label

#9881 fix(parental-leave): Fix rightCodePeriod and rights calculator
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/clients/vmst/src/lib/utils.ts
Labels: automerge

#9883 fix(parental-leave): Fix rightCodePeriod and rights calculator (#9881)
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/clients/vmst/src/lib/utils.ts
Labels: automerge

#9887 fix(parental-leave): gender code wrong
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#9876 feat(j-s): Add vehicle registration number to indictment count
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCountGql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCountGql.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#9843 feat(j-s): Traffic Violation Demands
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useOnceOn/index.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#9879 feat(financial-statement-inao): data collection text for financial info
  libs/application/templates/financial-statements-inao/src/forms/application/application.ts
  libs/application/templates/financial-statements-inao/src/lib/messages.ts
Labels: automerge

#9862 chore(j-s): Revoked Prison Email
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#9867 fix(service-portal): total driving lessons
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
Labels: automerge

#9890 fix(service-portal): remove unused from query
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
Labels: automerge

#9896 fix(parental-leave): right code fix
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#9849 feat(sessions): Add from/to query params. Add param descriptions
  apps/services/sessions/src/app/sessions/sessions-query.dto.ts
  apps/services/sessions/src/app/sessions/sessions.controller.spec.ts
  apps/services/sessions/src/app/sessions/sessions.controller.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  libs/nest/pagination/src/lib/dto/pagination.dto.ts
Labels: automerge

#9891 feat(change-co-owner-of-vehicle): can delete coowner
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.utils.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwnerRepeater/CoOwnerRepeaterItem.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwnerRepeater/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/sections/OwnerSection.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/Approved.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getChargeItemCodes.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getReviewSteps.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/isLastReviewer.ts
Labels: automerge

#9882 chore(applications): Documentation for new fields
  libs/application/core/README.md
Labels: automerge

#9850 feat(web): Add search box for Directorate of Health organization page
  apps/web/screens/Organization/Home/Home.tsx
Labels: automerge, deploy-feature

#9895 feat(applications): Error handling for application system
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  apps/application-system/form/src/routes/Application.tsx
  apps/application-system/form/src/routes/Applications.tsx
  apps/application-system/form/src/routes/AssignApplication.tsx
  libs/application/core/src/lib/messages.ts
  libs/application/ui-shell/src/assets/NotebookIllustration.tsx
  libs/application/ui-shell/src/components/ErrorShell.tsx
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/lib/FormShell.css.ts
  libs/application/ui-shell/src/lib/FormShell.tsx
Labels: automerge

#9893 fix(marriage-conditions): Cannot marry yourself :(
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/ApplicationOverview.tsx
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/index.tsx
  libs/application/templates/marriage-conditions/src/fields/Done/NextSteps.tsx
  libs/application/templates/marriage-conditions/src/fields/Done/index.tsx
  libs/application/templates/marriage-conditions/src/fields/InfoAlert/InfoAlert.tsx
  libs/application/templates/marriage-conditions/src/fields/InfoAlert/index.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/NationalIdWithName.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/PaymentInfo.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
  libs/application/templates/marriage-conditions/src/lib/messages.ts
Labels: automerge

#9898 fix(service-portal): remove unused from query (#9890)
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
Labels: automerge

#9840 chore(applications): Update conclusion screen for all norda applications
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/accident-notification/src/fields/FormConclusion/index.tsx
  libs/application/templates/accident-notification/src/fields/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/conclusionSection.ts
  libs/application/templates/accident-notification/src/lib/messages/conclusion.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ConfirmationScreen/ConfirmationScreen.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.css.ts
  libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/ComplaintConfirmation.tsx
  libs/application/templates/data-protection-complaint/src/fields/ComplaintConfirmation/index.ts
  libs/application/templates/data-protection-complaint/src/fields/index.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintFormInReview.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/confirmation.ts
  libs/application/templates/funding-government-projects/src/fields/Submitted/Submitted.tsx
  libs/application/templates/funding-government-projects/src/fields/index.ts
  libs/application/templates/funding-government-projects/src/forms/FundingGovernmentProjectsForm.ts
  libs/application/templates/funding-government-projects/src/forms/FundingGovernmentProjectsFormSubmitted.ts
  libs/application/templates/funding-government-projects/src/lib/messages/submitted.ts
  libs/application/templates/general-fishing-license/src/fields/Conclusion/index.tsx
  libs/application/templates/general-fishing-license/src/fields/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePaymentForm.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicensePrerequisitesForm/index.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseSubmittedForm.ts
  libs/application/templates/general-fishing-license/src/lib/messages/conclusion.ts
  libs/application/templates/health-insurance/src/fields/ConfirmationScreen/ConfirmationScreen.tsx
  libs/application/templates/health-insurance/src/fields/index.ts
  libs/application/templates/health-insurance/src/forms/ConfirmationScreen.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/health-insurance/src/forms/MissingInfoForm.ts
  libs/application/templates/health-insurance/src/forms/messages.ts
  libs/application/templates/institution-collaboration/src/forms/application.ts
  libs/application/templates/institution-collaboration/src/forms/approved.ts
  libs/application/templates/institution-collaboration/src/lib/messages.ts
  libs/application/templates/login-service/src/fields/Submitted/Submitted.tsx
  libs/application/templates/login-service/src/fields/index.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/templates/login-service/src/forms/LoginServiceFormSubmitted.ts
  libs/application/templates/login-service/src/lib/messages/submitted.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanSubmittedForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/conclusion.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.tsx
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.stories.mdx
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
  libs/application/ui-fields/src/lib/LinkFormField/hooks/useGenerateFileUrl.ts
  libs/application/ui-fields/src/lib/index.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#9906 feat(web): Hotfix - Add search box for Directorate of Health organization page (#9850)
  apps/web/screens/Organization/Home/Home.tsx
Labels: automerge

#9908 fix(applications): Fix service portal url from application system
  libs/application/ui-fields/src/lib/MessageWithLinkButtonFormField/MessageWithLinkButtonFormField.tsx
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
  libs/auth/react/src/lib/auth/AuthProvider.tsx
Labels: automerge

#9900 fix(marriage-conditions): adding error to core messages for marital status
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/types.ts
Labels: automerge

#9904 fix(aod): minor tweaks
  libs/application/templates/announcement-of-death/src/fields/ExistingApplication/LinkExistingApplication.tsx
  libs/application/templates/announcement-of-death/src/forms/draft/sectionOverview.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionWillAndTrade.ts
  libs/application/templates/announcement-of-death/src/lib/announcementOfDeathTemplate.ts
  libs/application/templates/announcement-of-death/src/lib/messages.ts
  libs/application/templates/announcement-of-death/src/lib/utils/index.ts
  libs/application/templates/announcement-of-death/src/utils/index.ts
Labels: automerge

#9907 fix(application-system): Hot fix for SPA router signin redirect
  apps/application-system/form/src/app/App.tsx
  apps/application-system/form/src/components/Router.tsx
  apps/application-system/form/src/lib/messages.tsx
  apps/application-system/form/src/lib/routes.tsx
  libs/auth/react/src/lib/auth/AuthErrorScreen.tsx
  libs/auth/react/src/lib/auth/AuthProvider.tsx
Labels: automerge

#9901 feat(sessions): Add device column to store user agent parsing.
  apps/services/sessions/migrations/20230209230744-add-device.js
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  package.json
  yarn.lock
Labels: automerge

#9913 fix(web): Change Box components to divs for Organization headers
  apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/DigitalIcelandHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/TryggingastofnunHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.tsx
Labels: automerge

#9903 feat(j-s): Indictment Count Laws Broken
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/api/src/app/modules/indictment-count/dto/updateIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/migrations/20230209163537-update-indictment-count.js
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseListEntry.response.ts
  apps/judicial-system/backend/src/app/modules/case/models/signatureConfirmation.response.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/dto/updateIndictmentCount.dto.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCountGql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCountGql.ts
Labels: automerge

#9916 fix(j-s): Fix IndictmentCount create mutation
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/deleteIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql.ts
Labels: automerge

#9808 feat(delegation-api): Add clients controller
  apps/services/auth/delegation-api/src/app/app.module.ts
  apps/services/auth/delegation-api/src/app/clients/client.dto.ts
  apps/services/auth/delegation-api/src/app/clients/clients.controller.spec.ts
  apps/services/auth/delegation-api/src/app/clients/clients.controller.ts
  apps/services/auth/delegation-api/src/app/clients/clients.module.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.filters.spec.ts
  libs/auth-api-lib/src/lib/clients/clients-translation.service.ts
  libs/auth-api-lib/src/lib/clients/clients.module.ts
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/services/auth/testing/src/fixtures/client.fixture.ts
  libs/services/auth/testing/src/fixtures/domain.fixture.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#9784 fix(portals-admin): Fix admin portal system-e2e
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcher.tsx
  apps/portals/admin/src/components/ModuleSwitcher/ModuleSwitcherHeader.tsx
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/admin-portal.spec.ts
Labels: automerge

#9917 feat(api-sessions): Use data loader to load client name and logo
  apps/services/sessions/sequelize.config.js
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/loaders/client.loader.ts
  libs/api/domains/auth/src/lib/models/client.model.ts
  libs/api/domains/auth/src/lib/services/clients.service.ts
  libs/api/domains/auth/src/lib/services/types.ts
  libs/clients/auth/delegation-api/src/lib/apis.ts
Labels: automerge

#9915 fix(web): Skip server side rendering Organization header and footers
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/index.ts
Labels: automerge, deploy-feature

#9918 fix(financial-statement-inao): operating year not persisting
  libs/application/templates/financial-statements-inao/src/forms/application/shared/about/clientInfoSection.ts
  libs/application/templates/financial-statements-inao/src/forms/application/shared/keyNumbers/capitalNumbers.ts
Labels: automerge

#9839 fix(estate): set up for private exchange
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/forms/PrivateExchange/done.ts
  libs/application/templates/estate/src/forms/PrivateExchange/form.ts
  libs/application/templates/estate/src/forms/PrivateExchange/overviewSection.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#9880 feat(sessions): UI for sessions
  apps/service-portal/src/lib/masterNavigation.ts
  libs/api/domains/sessions/src/lib/models/session.model.ts
  libs/portals/shared-modules/delegations/src/lib/navigation.ts
  libs/portals/shared-modules/delegations/src/module.tsx
  libs/service-portal/sessions/codegen.yml
  libs/service-portal/sessions/project.json
  libs/service-portal/sessions/src/components/LogTable/LogTable.css.ts
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/components/PersonIcon/PersonIcon.tsx
  libs/service-portal/sessions/src/lib/messages.ts
  libs/service-portal/sessions/src/lib/navigation.ts
  libs/service-portal/sessions/src/lib/paths.ts
  libs/service-portal/sessions/src/lib/types/sessionTypes.ts
  libs/service-portal/sessions/src/module.ts
  libs/service-portal/sessions/src/screens/Sessions/Sessions.graphql
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
  libs/service-portal/sessions/src/utils/useOnScreen.tsx
  libs/service-portal/sessions/src/utils/utils.ts
  libs/shared/constants/src/lib/date.ts
Labels: automerge

#9787 feat(user-notification): Hnipp templates
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/dto/hnippTemplate.response.ts
  apps/services/user-notification/src/app/modules/notifications/e2e/notifications.spec.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
  apps/services/user-notification/src/app/modules/notifications/types.ts
  apps/services/user-notification/src/buildOpenApi.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-notification/src/main.ts
  apps/services/user-notification/src/messages.ts
  apps/services/user-notification/test/globalSetup.ts
  apps/services/user-notification/test/globalTeardown.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#9683 feat(service-portal-applications): Draft status bar for application list
  apps/application-system/api/migrations/20230901211601-add-draft-states-cols.js
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/dto/application.response.dto.ts
  apps/application-system/api/src/app/modules/application/dto/updateApplication.dto.ts
  apps/application-system/api/src/app/modules/application/tools/application.serializer.ts
  libs/api/domains/application/src/lib/application.model.ts
  libs/api/domains/application/src/lib/dto/draftProgress.input.ts
  libs/api/domains/application/src/lib/dto/updateApplication.input.ts
  libs/application/api/core/src/lib/application/application.model.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/application/core/README.md
  libs/application/graphql/src/lib/fragments/application.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
  libs/application/types/src/lib/Application.ts
  libs/application/types/src/lib/Form.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/application/ui-shell/src/components/FormStepper.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/island-ui/core/src/index.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.css.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/island-ui/core/src/lib/DraftProgressMeter/DraftProgressMeter.css.ts
  libs/island-ui/core/src/lib/DraftProgressMeter/DraftProgressMeter.stories.tsx
  libs/island-ui/core/src/lib/DraftProgressMeter/DraftProgressMeter.tsx
  libs/service-portal/graphql/src/lib/fragments/application.ts
Labels: automerge

#9923 feat(web): Allow organization searchbox to be a connected component
  apps/web/components/Organization/SearchBox/SearchBox.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home/Home.tsx
Labels: automerge

#9922 chore(applications): Multiple errors / alerts for data provider items.
  apps/application-system/api/src/app/modules/application/tools/templateApiActionRunner.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/paymentPlanPrerequisites.service.ts
  libs/application/types/src/lib/DataProviderResult.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
  libs/nest/problem/src/lib/TemplateApiError.ts
  libs/shared/problem/src/problems.ts
Labels: automerge

#9924 fix(marriage-conditions): rm try catch
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
Labels: automerge

#9889 fix(transport authority applications): Update link to minarsidur
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/fields/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/index.ts
  libs/application/templates/transport-authority/anonymity-in-vehicle-registry/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/RejectedConclusion/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/conclusion.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/RejectedConclusion/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/conclusion.ts
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/fields/index.ts
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/fields/index.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/fields/index.ts
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/Confirmation.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/Confirmation.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/confirmation.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/RejectedConclusion/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ReviewConclusion/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/conclusion.ts
Labels: automerge

#9920 feat(j-s): Indictment Count Legal Arguments
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#9930 fix(transport authority applications): Change slug for CoOwner and Operator
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#9925 refactor(service-portal): change link for name hidden
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/utils/constants.ts
Labels: automerge

#9931 fix(transpor-authority): small bugs
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/sections/OwnerSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/sections/OwnerSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Payment/PaymentPendingField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/BuyerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/SellerSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getReviewSteps.ts
Labels: automerge

#9919 feat(services-sessions): Add geoip parsing
  apps/services/sessions/esbuild.json
  apps/services/sessions/migrations/20230212085519-add-iplocation.js
  apps/services/sessions/project.json
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  package.json
  yarn.lock
Labels: automerge

#9940 fix(services-sessions): Fix app serve locally
  apps/services/sessions/project.json
Labels: automerge

#9944 fix(core): Add env variable to dockerfile
  scripts/ci/Dockerfile
Labels: automerge

#9942 fix(sessions): Fix infinite scrolling
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
  package.json
  yarn.lock
Labels: automerge

#9934 feat(web): Hotfix - SAk header and footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.tsx
Labels: automerge, deploy-feature

#9945 fix(parental-leave): Fix specific cases for rightCodePeriod
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
Labels: automerge

#9946 fix(core): Add docker build args
  .github/workflows/push.yml
Labels: automerge

#9937 fix(applications): fishing license application translation string
  libs/application/templates/general-fishing-license/src/lib/messages/fishingLicenseFurtherInformation.ts
Labels: automerge

#9935 feat(web): Add footer and header to SAk organization pages
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/index.ts
Labels: automerge, deploy-feature

#9949 fix(core): Add env. to access variable.
  .github/workflows/push.yml
Labels: automerge, high priority

#9948 fix(ui): Actioncard conditionally render progressbar
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#9943 fix(sessions): Add device field. Move domain to field resolver. Use Intl for date format.
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/loaders/client.loader.ts
  libs/api/domains/auth/src/lib/models/client.model.ts
  libs/api/domains/auth/src/lib/resolvers/client.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/index.ts
  libs/api/domains/sessions/src/lib/models/session.model.ts
  libs/service-portal/sessions/src/components/Client/Client.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/lib/messages.ts
  libs/service-portal/sessions/src/lib/paths.ts
  libs/service-portal/sessions/src/screens/Sessions/Sessions.graphql
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
Labels: automerge

#9951 fix: increase session service resource limits
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#9932 fix(infra): Allow large headers in auth-admin-web
  apps/auth-admin-web/infra/auth-admin-web.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#10063 fix(sessions): Font size for client name
  libs/service-portal/sessions/src/components/Client/Client.tsx
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
  libs/service-portal/sessions/src/utils/useOnScreen.tsx
Labels: automerge

#10064 fix(sessions): Grant islandis namespace.
  apps/api/infra/api.ts
  apps/services/sessions/infra/sessions.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#9933 feat(j-s): Indictment Incident Description
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql.ts
Labels: automerge

#10065 fix(service-portal): Hide air discount when logged in as a company
  libs/service-portal/air-discount/src/module.ts
Labels: automerge

#10067 fix(api-auth): Refactor domain data loader to return null.
  libs/api/domains/auth/src/lib/loaders/domain.loader.ts
  libs/api/domains/auth/src/lib/resolvers/client.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/customDelegation.resolver.ts
Labels: automerge

#10072 fix(applications): Revert draft status bar to original design
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#9921 fix(shared): tweak markdown for lists
  libs/shared/components/src/Markdown/markdownOptions.tsx
Labels: automerge

#10075 fix(applications): Revert draft status bar to original design (#10072)
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#10074 fix(applications): Revert draft status bar to original design
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#10079 fix(session): Info bubble for location
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/lib/messages.ts
Labels: automerge

#10066 fix(aod): UI tweaks
  libs/application/templates/announcement-of-death/src/fields/AnswerPopulator/AnswerPopulator.tsx
  libs/application/templates/announcement-of-death/src/fields/AnswerPopulator/index.tsx
  libs/application/templates/announcement-of-death/src/fields/Done/AnnouncementCompleteImage.tsx
  libs/application/templates/announcement-of-death/src/fields/Done/Completed.tsx
  libs/application/templates/announcement-of-death/src/fields/Done/Delegated.tsx
  libs/application/templates/announcement-of-death/src/fields/Done/index.tsx
  libs/application/templates/announcement-of-death/src/fields/ElectPerson/ElectPerson.tsx
  libs/application/templates/announcement-of-death/src/fields/ElectPerson/index.tsx
  libs/application/templates/announcement-of-death/src/fields/ElectPerson/styles.css.ts
  libs/application/templates/announcement-of-death/src/fields/EstateMemberRepeater/EstateMemberRepeater.tsx
  libs/application/templates/announcement-of-death/src/fields/EstateMemberRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/fields/EstateMemberRepeater/styles.css.ts
  libs/application/templates/announcement-of-death/src/fields/FilesRecipientCard/FilesRecipientCard.tsx
  libs/application/templates/announcement-of-death/src/fields/FilesRecipientCard/index.tsx
  libs/application/templates/announcement-of-death/src/fields/InfoCard/InfoCard.tsx
  libs/application/templates/announcement-of-death/src/fields/InfoCard/index.tsx
  libs/application/templates/announcement-of-death/src/fields/RealEstateAndLandsRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/styles.css.ts
  libs/application/templates/announcement-of-death/src/fields/VehiclesRepeater/VehiclesRepeater.tsx
  libs/application/templates/announcement-of-death/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/fields/VehiclesRepeater/styles.css.ts
  libs/application/templates/announcement-of-death/src/fields/index.ts
  libs/application/templates/announcement-of-death/src/forms/delegated.ts
  libs/application/templates/announcement-of-death/src/forms/done.ts
  libs/application/templates/announcement-of-death/src/forms/draft/draft.ts
  libs/application/templates/announcement-of-death/src/forms/draft/sectionOverview.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionFiles.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionInfo.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionInheritance.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionProperties.ts
  libs/application/templates/announcement-of-death/src/forms/prerequisite/index.ts
  libs/application/templates/announcement-of-death/src/lib/messages.ts
Labels: automerge

#10080 fix(ui): Enable feature flags for ui components
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/island-ui/storybook/config/main.js
Labels: automerge

#10082 fix(estate): tweaking application using proper english :')
  libs/application/templates/estate/src/forms/DivisionOfEstate/done.ts
  libs/application/templates/estate/src/forms/DivisionOfEstate/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/done.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/done.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/externalDataFields/estateMembersFields.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/externalDataFields/propertiesFields.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/done.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/forms/sharedSections/announcerInfo.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#9947 fix(applications): Fix incorrect text on data providers
  libs/application/templates/public-debt-payment-plan/src/forms/PrerequisitesForm.ts
Labels: automerge

#10083 fix(inheritance-report): adding Tax Free Limit to contentful
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/lib/constants.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#10085 fix(web): Add missing hasBorderAbove field to OverviewLinks query
  apps/web/screens/queries/fragments.ts
Labels: automerge

#10076 feat(web): New login button with dropdown
  apps/service-portal/src/auth.ts
  apps/web/components/Header/Header.tsx
  libs/auth/react/src/lib/AuthSettings.ts
  libs/auth/react/src/lib/auth/AuthProvider.tsx
  libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.css.ts
Labels: automerge

#10087 fix(instructor-registration-application): error toast for allow practice driving
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
Labels: automerge

#10090 fix(applications): Fix for draft status bar
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#10073 fix(j-s): Traffic Violation Navigation
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
Labels: automerge

#10094 fix(parental-leave): Dont send email to employer when sending additio…
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#10095 fix(transport-authority): operator fixes
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.utils.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/ValidationErrorMessages/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OldOperators/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OperatorRepeater/OldOperatorItem.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OperatorRepeater/OperatorRepeaterItem.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OperatorRepeater/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/ValidationErrorMessages/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/index.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/mainOperatorSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/operatorSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getChargeItemCodes.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getReviewSteps.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/isLastReviewer.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/isRemovingOperatorOnly.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/updateOldOperatorAnswers.ts
Labels: automerge

#10091 fix(estate): Einkaskipti tweaks
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#10102 fix(parental-leave): get applicant name not all external data
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
Labels: automerge

#10101 fix(service-portal): Hotfix - hide air-discount when logged in as a company in serviceportal
  libs/service-portal/air-discount/src/module.ts
Labels: automerge

#10099 fix(web): Prevent TwoColumnText titles from overflowing
  apps/web/components/Organization/Slice/TwoColumnText/TwoColumnTextSlice.tsx
Labels: automerge

#10104 fix(parental-leave): take out - when sending in bank account to api
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
Labels: automerge

#9786 feat(system-e2e): Add e2e tests for Júní applications
  apps/system-e2e/global.d.ts
  apps/system-e2e/src/addons.ts
  apps/system-e2e/src/support/disablers.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/announcement-of-death.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-assessment-approval.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-instructor-registrations.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-licence.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-school-confirmation.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/marriage-conditions.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/operating-licence.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/passport.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/smoke/p-sign.spec.ts
  libs/application/templates/announcement-of-death/src/lib/messages.ts
  package.json
  yarn.lock
Labels: automerge

#10108 chore(web): SAk Header UI tweaks
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.css.ts
Labels: automerge

#10096 feat(parental leave): multiple employers
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/applicationApprovedByEmployerToEmployer.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/smsGenerators/assignEmployerSms.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/EmployersOverview/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/ConclusionImageScreen.tsx
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Employment.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/OtherParent.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Payments.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/PersonalAllowance.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/SpousePersonalAllowance.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/props.ts
  libs/application/templates/parental-leave/src/fields/SelfEmployed/index.tsx
  libs/application/templates/parental-leave/src/fields/UnEmploymentBenefits/index.tsx
  libs/application/templates/parental-leave/src/fields/components/EmployersTable/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/fileUploadValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLastestEmployerValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
  libs/application/ui-components/src/components/CompanySearchController/CompanySearchController.tsx
Labels: deploy-feature

#10105 feat(transport authority applications): Use shared MessageWithLinkButton component
  libs/application/core/src/lib/messages.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/conclusion.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/conclusion.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Conclusion/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ConclusionMessageWithLinkButtonFormField/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/conclusion.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
  libs/application/ui-forms/src/lib/formConclusionSection/messages.ts
Labels: automerge

#10115 fix(parental-leave): Non-custodial father can not give days (#10107)
  libs/application/templates/parental-leave/src/lib/answerValidationSections/giveRightsValidationSection.ts
Labels: automerge

#9897 chore(web): Remove web project version of sortAlpha function
  apps/web/layouts/main.tsx
  apps/web/screens/Category/Category/Category.tsx
  apps/web/screens/Organizations/Organizations.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/utils/sortAlpha.ts
  libs/portals/core/src/utils/stringHash.ts
  libs/service-portal/graphql/src/hooks/alertBanners/useAlertBanners.ts
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/stringHash.ts
Labels: automerge

#10017 feat(j-s): Indictment Count Auto Laws
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#10100 feat(j-s): Indictment PDF
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/api/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/messages/index.ts
  apps/judicial-system/backend/src/app/messages/pdfIndictment.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/utils/hooks/useOnceOn/index.ts
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
Labels: automerge

#10119 fix(web): Change padding on web form depending on screen size
  apps/web/components/Form/Form.tsx
Labels: automerge

#10121 fix(j-s): Remove dash from National IDs
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
Labels: automerge

#10114 fix(application): Change button size to link field and make icon customizable.
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/confirmation.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
  libs/island-ui/core/src/index.ts
  libs/island-ui/core/src/lib/AlertBanner/AlertBanner.tsx
  libs/island-ui/core/src/lib/IconRC/Icon.tsx
  libs/island-ui/core/src/lib/IconRC/types.ts
  libs/island-ui/core/src/lib/Tooltip/Tooltip.tsx
  libs/island-ui/core/types.ts
Labels: automerge

#10130 fix(user-notification): mapLocale and cache settings
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
Labels: automerge

#10128 fix(document-provider): Fix scope check
  libs/portals/admin/document-provider/src/module.tsx
Labels: automerge

#10132 fix(user-notification): mapLocale and cache settings (#10130)
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
Labels: automerge

#10112 fix(general-petition): General Petition Template, vol.2
  libs/application/templates/general-petition/src/assets/CoatOfArms.tsx
  libs/application/templates/general-petition/src/assets/Logo.tsx
  libs/application/templates/general-petition/src/assets/School.tsx
  libs/application/templates/general-petition/src/constants.ts
  libs/application/templates/general-petition/src/fields/EndorsementApproved/index.tsx
  libs/application/templates/general-petition/src/fields/EndorsementDisclaimer/index.tsx
  libs/application/templates/general-petition/src/fields/ListCreated/index.tsx
  libs/application/templates/general-petition/src/fields/ListSubmitted/index.tsx
  libs/application/templates/general-petition/src/fields/Overview/index.tsx
  libs/application/templates/general-petition/src/fields/SignPetitionView/Skeleton.tsx
  libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
  libs/application/templates/general-petition/src/fields/index.ts
  libs/application/templates/general-petition/src/forms/ApplicationForm.ts
  libs/application/templates/general-petition/src/forms/PetitionApplicationApproved.ts
  libs/application/templates/general-petition/src/forms/done.ts
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/templates/general-petition/src/forms/prerequisites.ts
  libs/application/templates/general-petition/src/forms/signPetitionForm.ts
  libs/application/templates/general-petition/src/index.ts
  libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts
  libs/application/templates/general-petition/src/lib/dataSchema.ts
  libs/application/templates/general-petition/src/lib/generalPetitionTemplate.spec.ts
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/application/templates/general-petition/src/lib/utils.ts
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/endorsements/src/lib/messages.ts
Labels: automerge

#10135 fix(parental-leave): validate employers' ratio and phonNumber
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLastestEmployerValidationSection.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge
