Repository island-is/island.is, pull requests merged in 2023-10, with the labels that each got.

#12273 feat(consultation-portal): Kam 1681 fixes from meeting 29 9 2023
  apps/consultation-portal/components/LogoText/LogoText.tsx
  apps/consultation-portal/screens/About/components/AboutContent/AboutRTF.tsx
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/AdviceForm/components/AgencyText/AgencyText.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusCard/CaseStatusCard.tsx
Labels: automerge

#12274 feat(web): Skip showing logo for vacancies coming from cms with no institution name
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
Labels: automerge

#12277 chore(web): Change housing benefit calculator xroad path for prod
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#12279 feat(web): Hotfix - Log error for hsn form response (#12230)
  libs/api/domains/communications/src/lib/communications.service.ts
Labels: automerge

#12281 chore(web): Hotfix - Change housing benefit calculator xroad path for prod (#12277)
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#12282 fix(application-estate): Desynced types in estate
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
Labels: automerge

#12283 fix(application-estate): Email and phone validation
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/templates/estate/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/estate/src/fields/Cards/index.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
  libs/application/templates/estate/src/forms/Sections/estateAssets.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#12285 fix(j-s): Hide judge and default string for court case number if empty
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
Labels: automerge

#12222 feat(j-s): Send SMS to court assistants when a case is appealed
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.config.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealToCourtOfAppealsNotifications.spec.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#12256 fix(web): Add top padding to "default footer" on web
  apps/web/components/Footer/Footer.tsx
Labels: automerge

#12289 fix(medeigandi-okutaekis): removing console logs
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx
Labels: automerge

#12287 fix(web): HSN web form - Set "Content-Type" header to "application/json"
  libs/api/domains/communications/src/lib/communications.service.ts
Labels: automerge

#12157 fix(driving-license-book-client): reduce empty array → return null
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
Labels: automerge

#12280 fix(j-s): Send case notification e-mail to defender
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendCourtDateNotification.spec.ts
Labels: automerge

#12290 fix(auth-api-lib) Revert "feat(auth-api-lib): Add delegation custom scope rule for @island.is/fishing-license scope. (#12245)"
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#12294 fix(web): Hotfix - Explicitly set HSN form response header (#12287)
  libs/api/domains/communications/src/lib/communications.service.ts
Labels: automerge

#12278 feat(web): Hotfix - Add header for HMS (#12232)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/HmsHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/HmsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/index.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
  libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.css.ts
  libs/island-ui/core/src/lib/AsyncSearch/shared/Input/Input.tsx
  libs/island-ui/core/src/lib/Button/Button.css.ts
  libs/island-ui/core/src/lib/FocusableBox/FocusableBox.css.ts
  libs/island-ui/core/src/lib/context/ColorSchemeContext/ColorSchemeContext.ts
Labels: automerge, deploy-feature

#12302 fix(digital tachograph): Fix shared template api currentLicense when using validCategories param
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
Labels: automerge

#12301 fix(digital tachograph): Fix shared template api currentLicense when using validCategories param
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
Labels: automerge

#12305 fix(consultation-portal): KAM-1748: Fix bg color of subscription table in my subscriptions
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/SubscriptionTable.tsx
Labels: automerge

#12298 feat(web): Remove org logo from default footer
  apps/web/components/Footer/Footer.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#12268 feat(web): Directorate of immigration - service web iteration
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/screens/ServiceWeb/Forms/utils.ts
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#12307 fix(j-s): No LÖKE Files
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
Labels: automerge

#12271 fix(air-discount-scheme): default lifetime of code and added type of code
  .github/CODEOWNERS
  libs/portals/admin/air-discount-scheme/src/screens/CreateDiscount/CreateDiscount.graphql
  libs/portals/admin/air-discount-scheme/src/screens/CreateDiscount/CreateDiscount.tsx
  libs/portals/admin/air-discount-scheme/src/screens/Overview/Overview.loader.ts
Labels: automerge

#12261 chore(git-hooks): Add more protected branches in local push-protector
  .githooks/pre-push
Labels: automerge

#12315 feat(web): Change /starfatorg footer
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
Labels: automerge

#12316 feat(smart-solutions): add local smart graphql source
  libs/clients/smartsolutions/codegen.yml
  libs/clients/smartsolutions/fetchGraphql.yml
  libs/clients/smartsolutions/project.json
  libs/clients/smartsolutions/smartsolutions-api.graphql
Labels: automerge

#12317 fix(service portal): Add can register property to health centers
  libs/api/domains/rights-portal/src/lib/models/healthCenter.model.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.graphql
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
Labels: automerge

#12297 build(infra): improve --max-old-space-size default calculation
  apps/services/sessions/infra/sessions.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/output-generators/map-to-localrun.ts
  infra/src/dsl/postgres.spec.ts
  libs/shared/utils/src/lib/scale-value.ts
Labels: automerge

#10219 feat(passport-annulment): new template for Passport Annulment
  .github/CODEOWNERS
  libs/application/template-api-modules/src/lib/modules/shared/api/index.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/passport/passport.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/passport/passport.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport-annulment/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport-annulment/passport-annulment.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport-annulment/passport-annulment.service.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/passport-annulment/.babelrc
  libs/application/templates/passport-annulment/.eslintrc.json
  libs/application/templates/passport-annulment/README.md
  libs/application/templates/passport-annulment/babel-jest.config.json
  libs/application/templates/passport-annulment/jest.config.ts
  libs/application/templates/passport-annulment/project.json
  libs/application/templates/passport-annulment/src/dataProviders/index.ts
  libs/application/templates/passport-annulment/src/fields/DoneImage/assets/School.tsx
  libs/application/templates/passport-annulment/src/fields/DoneImage/index.tsx
  libs/application/templates/passport-annulment/src/fields/PassportSelection/index.tsx
  libs/application/templates/passport-annulment/src/fields/index.ts
  libs/application/templates/passport-annulment/src/forms/Done.ts
  libs/application/templates/passport-annulment/src/forms/Draft.ts
  libs/application/templates/passport-annulment/src/forms/sections/info.ts
  libs/application/templates/passport-annulment/src/forms/sections/overveiw.ts
  libs/application/templates/passport-annulment/src/index.ts
  libs/application/templates/passport-annulment/src/lib/PassportAnnulmentTemplate.ts
  libs/application/templates/passport-annulment/src/lib/constants.ts
  libs/application/templates/passport-annulment/src/lib/dataSchema.ts
  libs/application/templates/passport-annulment/src/lib/error.ts
  libs/application/templates/passport-annulment/src/lib/messages.ts
  libs/application/templates/passport-annulment/src/lib/utils.ts
  libs/application/templates/passport-annulment/tsconfig.json
  libs/application/templates/passport-annulment/tsconfig.lib.json
  libs/application/templates/passport-annulment/tsconfig.spec.json
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/institutionMapper.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/index.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/passport.ts
  libs/clients/passports/src/clientConfig.yaml
  libs/clients/passports/src/lib/PassportsApiProvider.ts
  libs/clients/passports/src/lib/passportsApi.service.ts
  libs/clients/passports/src/lib/passportsApi.types.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge

#12296 chore(j-s): Enable Appeals
  apps/judicial-system/api/infra/judicial-system-api.ts
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#12322 fix(web): Logo fix
  libs/island-ui/core/src/lib/Logo/Logo.css.ts
  libs/island-ui/core/src/lib/Logo/Logo.tsx
Labels: automerge, deploy-feature

#12321 fix(parental-leave): Other parent could create new application
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children-utils.ts
Labels: automerge

#12295 feat(j-s): Deliver Appeal Ruling To Police
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts
Labels: automerge

#12299 feat(j-s): Defender access changes
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/auth/auth.module.ts
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
  apps/judicial-system/api/src/app/modules/defender/defender.config.ts
  apps/judicial-system/api/src/app/modules/defender/defender.controller.ts
  apps/judicial-system/api/src/app/modules/defender/defender.module.ts
  apps/judicial-system/api/src/app/modules/defender/defender.service.ts
  apps/judicial-system/api/src/app/modules/index.ts
  apps/judicial-system/web/proxy.config.json
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/defender.ts
Labels: automerge

#12312 feat(web): Add new anchor page type
  apps/web/components/Organization/Slice/LifeEventPageListSlice/LifeEventPageListSlice.tsx
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/o/digital-iceland/island-is-community/[slug].ts
  apps/web/pages/s/stafraent-island/island-is-samfelagid/[slug].ts
  apps/web/screens/LifeEvent/LifeEvent.tsx
  apps/web/screens/Organization/Home/Home.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Search/Search.tsx
  apps/web/screens/queries/Search.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/anchorPage.ts
  libs/api/domains/content-search/src/lib/enums/searchableContentTypes.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/lifeEventPage.model.ts
  libs/cms/src/lib/search/importers/lifeEventsPage.service.ts
Labels: automerge, skip-generated-cache

#12332 fix(j-s): Defender config
  apps/judicial-system/api/src/app/modules/defender/defender.config.ts
Labels: automerge

#12325 fix(web): Fix subArticle entry hyperlinking
  apps/contentful-apps/constants/index.ts
  apps/contentful-apps/pages/sidebars/preview-link.tsx
  libs/cms/src/lib/search/importers/utils.spec.ts
  libs/cms/src/lib/search/importers/utils.ts
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
Labels: automerge

#12310 fix(web): Fix color for dark theme scroll header
  libs/island-ui/core/src/lib/AsyncSearch/AsyncSearch.tsx
  libs/island-ui/core/src/lib/Button/Button.css.ts
Labels: automerge

#12326 fix(application-system): Address vague error message in application system
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/core/src/lib/messages.ts
  libs/application/ui-shell/src/components/ErrorShell.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge

#12329 chore(portals-admin): Move the application error boundary higher up in the tree.
  apps/portals/admin/src/app/App.tsx
Labels: automerge

#12341 ci: set stalebot to run at 8 am
  .github/workflows/stale-prs.yml
Labels: automerge

#12339 fix(j-s): Assistant pdf access
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRequestPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/deleteCaseFileRolesRules.spec.ts
Labels: automerge

#12320 feat(license-api): Updates and revoke function for driving licenses
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseMapper.ts
Labels: automerge

#12308 fix(application-system): Changing default values for the fileuploaderformfield
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/messages.ts
  libs/application/ui-fields/src/lib/DescriptionFormField/DescriptionFormField.tsx
  libs/application/ui-fields/src/lib/FileUploadFormField/FileUploadFormField.tsx
Labels: automerge

#12154 feat(auth-admin): Client partial creation warning
  libs/auth-api-lib/seeders/local/011-local-artic.js
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Client/CreateClient/CreateClient.action.ts
Labels: automerge

#12208 feat(auth-delegation): Access control default system
  libs/portals/shared-modules/delegations/src/components/access/AccessForm/AccessForm.tsx
  libs/portals/shared-modules/delegations/src/hooks/useDomains/useDomains.ts
  libs/portals/shared-modules/delegations/src/lib/messages.ts
  libs/portals/shared-modules/delegations/src/screens/AccessControl.tsx
  libs/portals/shared-modules/delegations/src/screens/GrantAccess/GrantAccess.tsx
Labels: automerge

#12331 feat(web): Display all reduction fields in housing benefit calculator
  apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx
  apps/web/screens/queries/HousingBenefitCalculator.ts
Labels: automerge

#12138 chore(driving-license-client): Refactor into only v4/v5
  libs/api/domains/driving-license-book/src/lib/guards/drivingInstructor.guard.ts
  libs/api/domains/driving-license-book/src/lib/guards/drivingInstructorOrEmployee.guard.ts
  libs/api/domains/driving-license/src/lib/__mock-data__/canApplyWithResultFail.json
  libs/api/domains/driving-license/src/lib/__mock-data__/canApplyWithResultSuccess.json
  libs/api/domains/driving-license/src/lib/__mock-data__/drivingAssessment.ts
  libs/api/domains/driving-license/src/lib/__mock-data__/expiredLicense.json
  libs/api/domains/driving-license/src/lib/__mock-data__/finishedSchool.json
  libs/api/domains/driving-license/src/lib/__mock-data__/licenseWithDisqualification.json
  libs/api/domains/driving-license/src/lib/__mock-data__/notFinishedSchool.json
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/api/domains/driving-license/src/lib/__mock-data__/teachers.json
  libs/api/domains/driving-license/src/lib/__mock-data__/validLicense.json
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/guards/drivingInstructor.guard.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/index.ts
  libs/api/domains/driving-license/src/lib/graphql/qualityPhoto.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/qualitySignature.resolver.ts
  libs/api/domains/driving-license/src/lib/util/sortTeachers.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/sortTeachers.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/types.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/digital-tachograph-drivers-card.service.ts
  libs/application/templates/driving-learners-permit/src/forms/form/sectionFakeData.ts
  libs/application/templates/driving-learners-permit/src/lib/constants.ts
  libs/application/templates/driving-license-book-update-instructor/src/forms/DrivingLicenseBookUpdateInstructorForm/informationSection.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionOverview.ts
  libs/application/templates/driving-license/src/fields/HealthRemarks.tsx
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
  libs/clients/driving-license/src/index.ts
  libs/clients/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.spec.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#12286 feat(history-application-system): Using the last history message as the date for the pending action.
  libs/application/ui-components/src/components/ApplicationCard/utils/history.tsx
  libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx
Labels: automerge

#12149 chore(national-registry): Remove fate of child from service
  apps/native/app/src/graphql/queries/list-family-query.ts
  libs/api/domains/national-registry/src/lib/shared/models/child.model.ts
  libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts
  libs/api/domains/national-registry/src/lib/v1/soffia.service.ts
  libs/api/domains/national-registry/src/lib/v1/types/child.type.ts
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/clients/national-registry/v1/src/lib/dto/getViewISLBorninMin.dto.ts
  libs/service-portal/information/src/lib/queries/getNationalChildren.ts
  libs/service-portal/information/src/lib/queries/getNationalRegistryFamily.ts
  libs/service-portal/information/src/screens/Child/Child.graphql
Labels: automerge

#12347 fix(samgongustofa applications): Make sure charge is deleted on payment state (if fulfilled)
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#12346 fix(samgongustofa applications): Make sure charge is deleted on payment state (if fulfilled)
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#12344 feat(service-portal): optimize user info queries
  libs/api/domains/national-registry/src/lib/resolvers/person.resolver.ts
  libs/service-portal/information/src/screens/Child/Child.graphql
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge

#12348 fix(search-indexer): Hotfix - Correctly prune entry hyperlink fields #12345
  libs/cms/src/lib/search/importers/utils.spec.ts
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#11962 feat(service-portal-e2e): Add smoketest for workmachines
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-machines.spec.ts
Labels: automerge

#12351 feat(contentful-apps): Time duration and formatted location contentful apps
  apps/contentful-apps/pages/fields/formatted-location-input-field.tsx
  apps/contentful-apps/pages/fields/time-duration-field.tsx
Labels: automerge

#12352 fix(service-portal): Aids and nutrition tab check.
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
Labels: automerge

#12361 fix(service-portal): hotfix - New inbox document line
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
Labels: automerge

#12362 fix(access-control): Fix access control
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationsEmptyState.tsx
  libs/portals/shared-modules/delegations/src/hooks/useDomains/useDomains.ts
Labels: automerge

#12363 fix(search-indexer): Extract fields rather than deleting for entry-hyperlink nodes
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#12364 fix(search-indexer): Hotfix - Extract fields rather than deleting for entry-hyperlink nodes (#12363)
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge, high priority

#12328 fix(system-test): Correctly notify which project failed
  apps/system-e2e/entrypoint.sh
Labels: automerge

#12330 fix(driving-license): show calculated days
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/models/applicationEligibilityRequirement.model.ts
  libs/api/domains/driving-license/src/lib/util/hasResidenceHistory.ts
  libs/application/templates/driving-learners-permit/src/lib/constants.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/ReviewSection/index.tsx
  libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#12368 fix(history-application-system): Using the last history message as the date for the pending action
  libs/application/ui-components/src/components/ApplicationCard/utils/history.tsx
  libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx
Labels: automerge

#12354 revert(j-s): Deliver Appeal Ruling To Police (#12295)
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts
Labels: automerge

#12360 feat(service-portal): Add bulk archive and fav
  libs/api/domains/documents/src/lib/document.resolver.ts
  libs/api/domains/documents/src/lib/document.service.ts
  libs/api/domains/documents/src/lib/dto/postBulkMailActionInput.ts
  libs/api/domains/documents/src/lib/models/bulkMailAction.model.ts
  libs/clients/documents/src/lib/documentClient.ts
  libs/clients/documents/src/lib/models/BulkMailActionDTO.ts
  libs/service-portal/documents/codegen.yml
  libs/service-portal/documents/project.json
  libs/service-portal/documents/src/components/DocumentLine/AvatarImage.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/FavAndStash/index.tsx
  libs/service-portal/documents/src/screens/Overview/BatchMailAction.graphql
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/messages.ts
Labels: automerge, deploy-feature

#12370 feat(j-s): Deliver Appeal Ruling to Police
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts
Labels: automerge

#12373 feat(transfer of vehicle ownerchange): Add mileage input field
  libs/api/domains/transport-authority/src/lib/graphql/dto/ownerChangeAnswers.input.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/VehicleSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ValidationErrorMessages/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/information.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/overview.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/index.ts
  libs/clients/transport-authority/vehicle-owner-change/src/clientConfig.json
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.service.ts
  libs/clients/transport-authority/vehicle-owner-change/src/lib/vehicleOwnerChangeClient.types.ts
Labels: automerge

#12371 fix(sessions): use jobs for geoip
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/src/deleteme.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/output-generators/map-to-localrun.ts
  infra/src/dsl/utils/scale-value.spec.ts
  infra/src/dsl/utils/scale-value.ts
Labels: automerge, deploy-feature

#12377 chore: remove deleteme from sessions
  apps/services/sessions/src/deleteme.ts
Labels: automerge

#12378 fix(sessions): use jobs for geoip
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/src/deleteme.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/output-generators/map-to-localrun.ts
  infra/src/dsl/utils/scale-value.spec.ts
  infra/src/dsl/utils/scale-value.ts
Labels: automerge

#12380 fix(service-portal): Hide shown document list mobile
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#12369 chore(system-tests): Show which project failed
  apps/system-e2e/entrypoint.sh
  apps/system-e2e/src/notifications/notify.ts
Labels: automerge

#12375 fix(search-indexer): Hotfix - entry hyperlink circularity pruning (#12372)
  libs/cms/src/lib/search/importers/utils.spec.ts
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#12372 fix(search-indexer): Prune entry hyperlink node fields that are not primitive
  libs/cms/src/lib/search/importers/utils.spec.ts
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#12384 fix(estate): fixing phone for representative in overview
  libs/application/templates/estate/src/forms/OverviewSections/representative.ts
Labels: automerge

#12342 feat(ci): Cancel previous jobs
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#12366 fix(j-s): COA ruling fixes
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
Labels: automerge

#11629 feat(eslint): Require default argument in .reduce
  .eslintrc.json
  apps/financial-aid/web-veita/src/components/ApplicationSideNavItems/ApplicationSideNavItems.tsx
  eslint-local-rules.js
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/auth-api-lib/src/lib/delegations/models/delegation.model.ts
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
  libs/service-portal/core/src/utils/addArray.ts
  libs/service-portal/education/src/utils/addArray.ts
Labels: automerge

#12387 fix(web): Add footerConfig to article query
  apps/web/screens/queries/Article.ts
Labels: automerge

#12324 feat(api): add p card client
  apps/api/src/app/app.module.ts
  infra/src/dsl/xroad.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/district-commissioners.scope.ts
  libs/clients/p-card/.eslintrc.json
  libs/clients/p-card/README.md
  libs/clients/p-card/jest.config.ts
  libs/clients/p-card/project.json
  libs/clients/p-card/src/clientConfig.json
  libs/clients/p-card/src/index.ts
  libs/clients/p-card/src/lib/pCard.module.ts
  libs/clients/p-card/src/lib/pCard.service.ts
  libs/clients/p-card/src/lib/pCardApiProvider.ts
  libs/clients/p-card/src/lib/pCardClient.config.ts
  libs/clients/p-card/tsconfig.json
  libs/clients/p-card/tsconfig.lib.json
  libs/clients/p-card/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#12388 fix(license-client): scope fix
  apps/services/license-api/src/app/modules/license/license.types.ts
  apps/services/license-api/src/app/modules/license/scopeMapper.ts
  apps/services/license-api/src/app/modules/license/test/utils.spec.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/auth/scopes/src/lib/license-api.scope.ts
  libs/clients/license-client/src/lib/licenseClient.module.ts
  libs/clients/license-client/src/lib/licenseClient.type.ts
  libs/clients/license-client/src/lib/licenseUpdateClient.module.ts
  libs/clients/license-client/src/lib/providers/passTemplateIdsProvider.ts
Labels: automerge

#12390 chore(license-client): readme update
  libs/clients/license-client/README.md
Labels: automerge

#12383 feat(web): Main name and email fields for forms can now be skipped
  apps/contentful-apps/pages/fields/form-default-namespace-field.tsx
  apps/web/components/Form/Form.tsx
Labels: automerge

#12394 fix(service-portal): Minor file issues regarding document views in inbox
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
Labels: automerge

#12395 fix(service-portal): Hotfix - file viewing for new inbox
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#12392 fix(j-s): Allow prison system user COA result access
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/guards/viewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlRolesRules.spec.ts
Labels: automerge

#12397 fix(system-e2e): Test work license path and name
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-license.spec.ts
Labels: automerge

#12398 fix(web): Add missing whitespace in form message
  apps/web/components/Form/Form.tsx
Labels: automerge

#12391 feat(web): KAM-1780: Footer for rettindagaesla fatlads folks
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
Labels: automerge

#12400 chore: util script for changelogs
  scripts/generate-changelog.sh
Labels: automerge

#12404 chore(service-portal): Use pagination instead of displaying all documents inbox
  libs/service-portal/documents/src/components/DocumentRenderer/PdfDocument.tsx
Labels: automerge

#12405 fix(service-portal): Add fixes that fix e2e tests in service-portal
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
Labels: automerge

#12403 feat(web): rettindagaesla fatlads folks footer
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
Labels: automerge

#12414 fix(transfer-vehicle-ownership): text change in history logs
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/application.ts
Labels: automerge

#12413 fix(transfer-vehicle-ownership): text change in history logs
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/application.ts
Labels: automerge

#12408 fix(Utlendingastofnun): Add missing pageTitle change
  libs/application/core/src/lib/formBuilders.ts
Labels: automerge

#12415 fix(p-card): add district commissioners xroad config
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12376 chore(service-portal): Removal of old feature flags
  libs/api/domains/rights-portal/src/lib/rightsPortal.resolver.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
Labels: automerge

#12382 chore(service-portal): Overview documents
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/PdfDocument.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/DesktopOverview.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/MobileOverview.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/OverviewDisplay.css.ts
  libs/service-portal/documents/src/components/OverviewDisplay/OverviewDocumentDisplay.tsx
  libs/service-portal/documents/src/lib/types.ts
  libs/service-portal/documents/src/screens/Overview/DocumentExtra.graphql
  libs/service-portal/documents/src/screens/Overview/Overview.css.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/downloadDocument.ts
Labels: automerge

#12303 fix(user-profile): Allow 204 response in userprofile service
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/handle204.ts
  libs/clients/middlewares/src/lib/types.ts
Labels: automerge, deploy-feature

#12409 fix(system-e2e): General service portal e2e
  apps/system-e2e/src/tests/islandis/service-portal/smoke/service-portal.spec.ts
Labels: automerge

#12422 fix(consultation-portal): Boð um þátttöku has empty string
  apps/consultation-portal/screens/Case/utils/getStakeholdersList.ts
Labels: automerge

#12401 chore(web): Add eslint rule for import order
  apps/web/.eslintrc.json
Labels: automerge

#12424 fix(helm): Remove latest_master as default image
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/environments.ts
Labels: automerge

#12426 fix(services-sessions): Fix serve buildTarget to fix yarn start for the service.
  apps/services/sessions/project.json
Labels: automerge

#12242 feat(j-s): Generate a zip file
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/api/src/app/modules/file/file.service.ts
  apps/judicial-system/api/src/app/modules/file/limitedAccessFile.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getAllFilesZipGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getAllFilesZipRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.css.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
  package.json
  yarn.lock
Labels: automerge

#12427 feat(web): Add sign language video field to news content type
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
  apps/web/screens/News.tsx
  apps/web/screens/queries/News.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/news.model.ts
Labels: automerge

#12412 feat(web): Add category card variant to accordion slice content type
  apps/web/components/Organization/Slice/AccordionSlice/AccordionSlice.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
Labels: automerge

#12423 feat(web): Display description field on auctions page
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
Labels: automerge

#12411 feat(citizenship): CheckboxformField needed rightContent
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
Labels: automerge

#12439 feat(web): Hotfix - anonymous form submit on web
  apps/contentful-apps/pages/fields/form-default-namespace-field.tsx
  apps/web/components/Form/Form.tsx
Labels: automerge

#12434 chore(auth-api-lib): Add delegation custom scope rule
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#12311 chore(web): Change spacing
  apps/web/components/NewsItems/NewsItems.tsx
  apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home/Home.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#12353 fix(service-portal): Updating occupation licenses
  apps/system-e2e/src/tests/islandis/service-portal/smoke/occupational-licenses.spec.ts
  libs/api/domains/occupational-licenses/src/lib/models/occupationalLicense.model.ts
  libs/api/domains/occupational-licenses/src/lib/models/occupationalLicenseError.model.ts
  libs/api/domains/occupational-licenses/src/lib/models/occupationalLicenseList.model.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
  libs/clients/health-directorate/src/clientConfig.json
  libs/service-portal/occupational-licenses/src/components/LicenceActionCard.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
  libs/service-portal/occupational-licenses/src/lib/messages.ts
  libs/service-portal/occupational-licenses/src/lib/navigation.ts
  libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.graphql
  libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.graphql
  libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.graphql
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge

#12435 fix(parental leave): sync dob
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
Labels: automerge

#12438 fix(parental-leave): Update flow chart
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart-2.png
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart.drawio
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart.png
Labels: automerge

#12420 fix(service-portal): Layout tweaks
  apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
  libs/service-portal/documents/src/components/NoPDF/NoPDF.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/MobileOverview.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/OverviewDocumentDisplay.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/occupational-licenses/src/lib/navigation.ts
Labels: automerge

#12385 fix(j-s): Remove .pdf ending from indictment case files
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createCaseFile.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createCaseFile.spec.ts
Labels: automerge

#12357 feat(j-s): Display message if defender has no active or completed cases
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
Labels: automerge

#12443 fix(national-registry): Update children response for v1
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/v1/soffia.service.ts
Labels: automerge

#12444 fix(national-registry): Hotfix - Update children response for v1
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/v1/soffia.service.ts
Labels: automerge

#12437 fix(j-s): Failing Playwright tests
  apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts
Labels: automerge

#12446 feat(consultation-portal): KAM-1828: Changing hero image
  apps/consultation-portal/components/svg/HeroImage.tsx
  apps/consultation-portal/components/svg/LESchoolMobile.tsx
  apps/consultation-portal/components/svg/Splash.tsx
  apps/consultation-portal/components/svg/index.ts
  apps/consultation-portal/screens/Home/components/HeroBanner/HeroBanner.css.ts
  apps/consultation-portal/screens/Home/components/HeroBanner/HeroBanner.tsx
Labels: automerge

#12449 fix: set default service upstream to true for fully zero downtime deployments
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/types/input-types.ts
Labels: automerge

#12453 Fix: proxies failing due to permissions
  scripts/Dockerfile.proxy
Labels: automerge

#12455 fix(web): Load readspeaker client side
  apps/web/components/Webreader/Webreader.tsx
  apps/web/components/Webreader/index.ts
  apps/web/components/real.ts
Labels: automerge

#12430 fix(license-api): smartsolutions updates
  apps/services/license-api/src/app/modules/license/clients/disabilityLicense/disabilityLicenseClient.service.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseMapper.ts
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseMapper.ts
  apps/services/license-api/src/app/modules/license/dto/revokeLicense.dto.ts
  apps/services/license-api/src/app/modules/license/dto/updateLicense.dto.ts
  apps/services/license-api/src/app/modules/license/license.controller.ts
  apps/services/license-api/src/app/modules/license/license.service.ts
  apps/services/license-api/src/app/modules/license/license.types.ts
  apps/services/license-api/src/app/modules/license/test/license.service.spec.ts
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
  libs/clients/smartsolutions/smartsolutions-api.graphql
  libs/clients/smartsolutions/src/lib/graphql/queries/mutations.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.types.ts
Labels: automerge

#12463 feat(service-portal): Use publishdate ahead of doc date for inbox item
  libs/api/domains/documents/src/lib/models/document.model.ts
  libs/clients/documents/src/lib/models/DocumentInfoDTO.ts
Labels: automerge

#12464 fix(consultation-portal): KAM-1831: removal of useEffect
  apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx
Labels: automerge

#12462 ci: check for release manager approval on pre-release
  .github/actions/check-team-approval.ts
  .github/workflows/pullrequest.yml
Labels: automerge

#12442 ci: increase stale PR cleanup
  .github/workflows/stale-prs.yml
  .prettierignore
Labels: automerge

#12448 fix(consultation-portal): Kam 1826 takes to long to initially load cold start
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/graphql/client.ts
  apps/consultation-portal/hooks/api/index.ts
  apps/consultation-portal/hooks/api/useDeleteCaseSubscription.ts
  apps/consultation-portal/hooks/api/useFetchAdvices.ts
  apps/consultation-portal/hooks/api/useFetchAdvicesById.ts
  apps/consultation-portal/hooks/api/useFetchCaseSubscription.ts
  apps/consultation-portal/hooks/api/useFetchCases.ts
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/hooks/api/useFetchStatistics.ts
  apps/consultation-portal/hooks/api/useFetchSubscriptions.ts
  apps/consultation-portal/hooks/api/usePostAdvice.ts
  apps/consultation-portal/hooks/api/usePostCaseSubscription.ts
  apps/consultation-portal/hooks/api/usePostEmail.ts
  apps/consultation-portal/hooks/api/usePostSubscription.ts
  apps/consultation-portal/next.config.js
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/pages/minaraskriftir/index.tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Home/Home.json
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
Labels: automerge

#12440 chore(j-s): Remove Old Appeal and Feature Hiding
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/subpoena.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Defender/Indictements/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/caseFiles.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/caseFiles.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/TagAppealState/TagAppealState.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Accused/AccusedAppealDatePicker.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Accused/AccusedAppealInfo.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.css.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Prosecutor/ProsecutorAppealDatePicker.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/Prosecutor/ProsecutorAppealInfo.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/types/src/lib/case.ts
  libs/judicial-system/types/src/lib/feature.ts
Labels: automerge

#12456 test: added hmr-benchmark script
  package.json
  scripts/README.md
  scripts/hmr-benchmark.ts
Labels: automerge

#12469 chore(auth-api-lib): Add Custom delegation type to allow for Samráðsgátt.
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#12470 chore(auth-api-lib): Update delegation config
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#12472 fix(service-portal): Add missing organizations in mobile
  libs/service-portal/assets/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
  libs/service-portal/core/src/utils/constants.ts
  libs/service-portal/information/src/screens/UserProfile/UserProfile.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge

#12460 chore(application-estate): Simplify service and standardize upload data
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/createPDF.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/filters.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/processUploadData.ts
Labels: automerge

#12396 fix(auth-admin): Firefox wildcard subdomain support
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.schema.ts
Labels: automerge

#12476 fix(service-portal): Update slow e2e tests
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financials.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/occupational-licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
Labels: automerge

#12477 feat(IDS scopes): replaced scope @skra.is/properties with @hms.is/properties.
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/hms.scope.ts
  libs/auth/scopes/src/lib/nationalRegistry.scope.ts
  libs/clients/assets/src/lib/assets.config.ts
Labels: automerge

#12458 feat(digital tachograph drivers card): update after changes in their api
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/types.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/digital-tachograph-drivers-card.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/types.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/CardTypeSection/index.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/messages/externalData.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/shared/constants.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/transport-authority/digital-tachograph-drivers-card/src/clientConfig.json
  libs/clients/transport-authority/digital-tachograph-drivers-card/src/lib/digitalTachographDriversCardClient.service.ts
  libs/clients/transport-authority/digital-tachograph-drivers-card/src/lib/digitalTachographDriversCardClient.types.ts
Labels: automerge

#12482 fix(application-system): Get status fetchpolicy
  libs/application/ui-components/src/components/PaymentPending/hooks/usePaymentStatus.ts
Labels: automerge

#12481 fix(application-estate): Advocate expansion introduced to estate member
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/processUploadData.ts
Labels: automerge

#12483 fix(service-portal): UI fixes and updates for Documents and General Layout
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.css.ts
  libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.tsx
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/core/src/components/ToolTip/ToolTip.css.ts
  libs/service-portal/core/src/components/ToolTip/ToolTip.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.css.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/PdfDocument.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/OverviewDisplay.css.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#12488 fix(national-registry): Add fate to model
  libs/api/domains/national-registry/src/lib/shared/models/child.model.ts
  libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts
Labels: automerge

#12490 fix(national-registry): Hotfix - Add fate to model (#12488)
  libs/api/domains/national-registry/src/lib/shared/models/child.model.ts
  libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts
Labels: automerge

#12471 feat(app): add Pcard license to wallet
  apps/native/app/src/graphql/queries/get-license.query.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/ui/assets/card/p-card.png
  apps/native/app/src/ui/assets/card/p-card@2x.png
  apps/native/app/src/ui/assets/card/p-card@3x.png
  apps/native/app/src/ui/lib/card/licence-card.tsx
Labels: automerge
