Repository island-is/island.is, pull requests merged in 2023-12, with the labels that each got.

#12949 feat(car-recycling): Add English translations to messages file
  libs/application/templates/car-recycling/src/lib/messages.ts
Labels: automerge

#12945 feat(web): Chart improvements
  apps/web/components/Charts/v2/constants.ts
  apps/web/components/Charts/v2/renderers/AccessibilityTableRenderer.tsx
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.css.ts
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
  apps/web/components/Charts/v2/renderers/ChartRenderer.tsx
  apps/web/components/Charts/v2/utils/chart.tsx
Labels: automerge

#12950 fix(service-portal): LinkResolver Onclick to undefined
  libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
  libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx
Labels: automerge

#12894 feat(j-s): Court of Appeals Valid to Dates
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20231127130936-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#12953 fix(core): Add esbuild.json external to fix glob update regression
  apps/api/esbuild.json
  apps/application-system/api/esbuild.json
  apps/financial-aid/backend/esbuild.json
  apps/judicial-system/backend/esbuild.json
  apps/services/endorsements/api/esbuild.json
  apps/services/user-profile/esbuild.json
Labels: automerge

#12942 feat(application-system): Add more props to formConclusion
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintFormInReview.ts
  libs/application/ui-fields/src/lib/MessageWithLinkButtonFormField/MessageWithLinkButtonFormField.tsx
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#12959 chore(estate): add missing titlevariants
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
Labels: automerge

#12946 chore(j-s): Validate User
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/user/dto/updateUser.input.ts
  apps/judicial-system/backend/src/app/modules/institution/index.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.module.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.service.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/interceptors/user.validator.ts
  apps/judicial-system/backend/src/app/modules/user/user.controller.ts
  apps/judicial-system/backend/src/app/modules/user/user.module.ts
Labels: automerge

#12933 feat(user-profile): Set DataStatus for email and phone on user profile update
  apps/services/user-profile/src/app/v2/dto/user-profile.dto.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
Labels: automerge

#12962 fix(service-portal): No logo when no provider provided
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
Labels: automerge

#12934 feat(web): Reuse organization default header for project pages
  apps/contentful-apps/pages/fields/theme-properties-field.tsx
  apps/web/components/DefaultHeader/DefaultHeader.css.ts
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/DefaultHeader/index.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/index.ts
  apps/web/components/Project/Header/DefaultProjectHeader.tsx
  apps/web/components/real.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
  apps/web/screens/Project/utils.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/Project.tsx
  apps/web/utils/organization.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationTheme.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#12972 fix(service-portal): hotfix - Update intro header slug
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
Labels: automerge

#12769 feat(signature-collection): Portals and api
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  libs/api/domains/signature-collection/.eslintrc.json
  libs/api/domains/signature-collection/README.md
  libs/api/domains/signature-collection/jest.config.ts
  libs/api/domains/signature-collection/project.json
  libs/api/domains/signature-collection/src/index.ts
  libs/api/domains/signature-collection/src/lib/dto/area.input.ts
  libs/api/domains/signature-collection/src/lib/dto/findSignature.input.ts
  libs/api/domains/signature-collection/src/lib/dto/id.input.ts
  libs/api/domains/signature-collection/src/lib/dto/owner.input.ts
  libs/api/domains/signature-collection/src/lib/dto/signatureListNationalIds.input.ts
  libs/api/domains/signature-collection/src/lib/dto/singatureList.input.ts
  libs/api/domains/signature-collection/src/lib/mocks/index.ts
  libs/api/domains/signature-collection/src/lib/models/area.model.ts
  libs/api/domains/signature-collection/src/lib/models/bulk.model.ts
  libs/api/domains/signature-collection/src/lib/models/collection.model.ts
  libs/api/domains/signature-collection/src/lib/models/nationalIdError.model.ts
  libs/api/domains/signature-collection/src/lib/models/owner.model.ts
  libs/api/domains/signature-collection/src/lib/models/signature.model.ts
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/api/domains/signature-collection/src/lib/models/signee.model.ts
  libs/api/domains/signature-collection/src/lib/models/success.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.module.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/api/domains/signature-collection/tsconfig.json
  libs/api/domains/signature-collection/tsconfig.lib.json
  libs/api/domains/signature-collection/tsconfig.spec.json
  libs/application/api/files/src/lib/pdfGenerators/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/utils.ts
  libs/service-portal/signature-collection/src/screens/SignatureLists/index.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/ownerView.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/signeeView.tsx
  libs/service-portal/signature-collection/src/screens/Skeletons/ListsSkeleton.tsx
  libs/service-portal/signature-collection/src/screens/Skeletons/index.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/signees.tsx
  libs/service-portal/signature-collection/src/screens/hooks.ts
  libs/service-portal/signature-collection/src/screens/queries.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: automerge

#12955 feat(estate): add total to estate bankaccounts
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/Sections/estateAssets.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge, deploy-feature

#12976 feat(origo cleanup): Remove unused feature flag
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/lib/DigitalTachographDriversCardTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#12979 fix(consultation-portal): change text
  apps/consultation-portal/screens/EmailVerified/EmailVerified.json
Labels: automerge

#12980 fix(consultation-portal): Hotfix/kam 1919
  apps/consultation-portal/screens/EmailVerified/EmailVerified.json
Labels: automerge

#12911 chore(inheritance-report): add acknowledgment statement on final submit section
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#12974 fix(estate): check if representative is over 18
  libs/application/templates/estate/src/forms/Sections/representative.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#12855 feat(j-s): Ask for help button
  apps/judicial-system/web/pages/api/geoLocation/getCountryCode.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useGeoLocation/useGeoLocation.ts
  apps/judicial-system/web/src/utils/validate.ts
  package.json
  yarn.lock
Labels: automerge

#12986 fix(j-s): CourtDocument loading indicator fix
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
Labels: automerge

#12982 fix(application-driving-license): Fix category mapping
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
Labels: automerge

#12981 feat(fa): Tables can be sorted after column
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/TableHeaders/SortableTableHeader.tsx
  apps/financial-aid/web-veita/src/components/index.ts
  apps/financial-aid/web-veita/src/routes/ApplicationsOverview/applicationsOverview.tsx
  apps/financial-aid/web-veita/src/routes/ApplicationsOverview/applicationsOverviewProcessed.tsx
  apps/financial-aid/web-veita/src/sharedStyles/Table.css.ts
  apps/financial-aid/web-veita/src/utils/navigation.ts
  apps/financial-aid/web-veita/src/utils/sortHelper.ts
  apps/financial-aid/web-veita/src/utils/useSortedApplications.ts
  libs/financial-aid/shared/src/lib/enums.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#12993 fix(application-driving-license): Fix category mapping (#12982)
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
Labels: automerge

#12975 fix(university-gateway): consolidate infra service name
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12990 fix(j-s): Handle court documents with the same name
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#12988 fix(core): Fix codegen
  nx.json
Labels: automerge

#12999 fix: increased application system api worker limits
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority, merge.priority_merge_label

#12985 feat(admin-portal-applications): Display pruned applications
  apps/application-system/api/src/app/modules/application/admin.controller.ts
  apps/application-system/api/src/app/modules/application/dto/applicationAdmin.response.dto.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAdmin.serializer.ts
  libs/api/domains/application/src/lib/application.model.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx
  libs/portals/admin/application-system/src/components/ApplicationsTable/ApplicationsTable.css.ts
  libs/portals/admin/application-system/src/components/ApplicationsTable/ApplicationsTable.tsx
  libs/portals/admin/application-system/src/lib/messages.ts
  libs/portals/admin/application-system/src/queries/overview.graphql
  libs/portals/admin/application-system/src/screens/Overview/Overview.tsx
  libs/portals/admin/application-system/src/types/adminApplication.ts
Labels: automerge

#12996 fix(clients-social-insurance-administration): add TR_XROAD_PATH to infra
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#13000 feat(web): Add header for Vinnueftirlitið organization page
  apps/web/components/DefaultHeader/DefaultHeader.css.ts
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/index.tsx
Labels: automerge

#13003 chore(estate): add text field for asset radio
  libs/application/templates/estate/src/forms/Sections/estateWithoutAssets.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#12923 feat(admin-portal): Signature Collection
  .github/CODEOWNERS
  apps/portals/admin/src/lib/masterNavigation.ts
  apps/portals/admin/src/lib/modules.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/portals/admin/signature-collection/.babelrc
  libs/portals/admin/signature-collection/.eslintrc.json
  libs/portals/admin/signature-collection/README.md
  libs/portals/admin/signature-collection/assets/headerImage.svg
  libs/portals/admin/signature-collection/babel-jest.config.json
  libs/portals/admin/signature-collection/codegen.yml
  libs/portals/admin/signature-collection/jest.config.ts
  libs/portals/admin/signature-collection/project.json
  libs/portals/admin/signature-collection/src/index.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/navigation.ts
  libs/portals/admin/signature-collection/src/lib/paths.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/module.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/AllLists.loader.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/getAllSignatureLists.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/List.loader.ts
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/skeleton.tsx
  libs/portals/admin/signature-collection/src/screens/List/getListSignees.graphql
  libs/portals/admin/signature-collection/src/screens/List/getSignatureList.graphql
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/portals/admin/signature-collection/tsconfig.json
  libs/portals/admin/signature-collection/tsconfig.lib.json
  libs/portals/admin/signature-collection/tsconfig.spec.json
  libs/portals/core/src/components/IntroHeader.tsx
  libs/react/components/src/components/Modal/Modal.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/ownerView.tsx
  tsconfig.base.json
Labels: automerge

#13014 chore(communications): Add useNodemailerApp to communications domain options
  libs/api/domains/communications/src/lib/environments/environment.ts
Labels: automerge

#13016 feat(web): Hotfix - Change what email Grindavík service web form gets sent to depending on categories (#13009)
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#12863 chore(authmodule): removed mentions of audience from AuthModule Readme
  libs/auth-nest-tools/README.md
Labels: automerge

#13011 chore(estate): add advocate contact info
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
Labels: automerge, deploy-feature

#13001 feat(vehicles): Update vehicle auth in vehicle API
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Labels: automerge

#13024 fix(web): Remove image from project page footers using default variant footer
  apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx
Labels: automerge

#12957 fix(estate): allow decimal in faceValue and calculated value
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
  libs/application/templates/estate/src/lib/utils.ts
Labels: automerge, deploy-feature

#13019 feat(estate): add description section
  libs/application/templates/estate/src/forms/Forms.ts
  libs/application/templates/estate/src/forms/Sections/description.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge, deploy-feature

#13038 feat(web): Change config for directorate of immigration chat
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge

#13025 chore(ids-api): Try fix flaky pers. repr. tests.
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts
Labels: automerge

#12997 chore(estate): extra checkbox fields
  libs/application/templates/estate/src/forms/OverviewSections/confirmAction.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge, deploy-feature

#13040 chore(estate): same checkbox style
  libs/application/templates/estate/src/forms/Sections/approveSubmission.ts
Labels: automerge

#13041 chore(estate): show dateOfBirth if no nationalId
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
Labels: automerge

#13020 feat(car-recycling): Adding mileage inputs
  apps/application-system/api/infra/application-system-api.ts
  apps/skilavottord/ws/infra/ws.ts
  apps/skilavottord/ws/src/app/modules/vehicle/dto/createVehicle.input.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/assets/Images/PeopleWalkingNWateringPlantIllustration.tsx
  libs/application/templates/car-recycling/src/fields/Review/review-groups/Vehicles.tsx
  libs/application/templates/car-recycling/src/fields/VehiclesOverview/VehiclesOverview.tsx
  libs/application/templates/car-recycling/src/index.ts
  libs/application/templates/car-recycling/src/lib/carRecyclingUtils.ts
  libs/application/templates/car-recycling/src/lib/dataSchema.ts
  libs/application/templates/car-recycling/src/lib/messages.ts
  libs/application/templates/car-recycling/src/shared/index.ts
  libs/application/templates/car-recycling/src/shared/types.ts
  libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts
Labels: automerge

#13015 fix(signature-collection): SignatureCollections tweaks
  libs/api/domains/signature-collection/src/lib/mocks/index.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/screens/List/List.loader.ts
  libs/portals/admin/signature-collection/src/screens/List/components/actionExtendDeadline.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/actionReviewComplete.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/SignatureLists/ownerView.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/signeeView.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/signees.tsx
Labels: automerge, deploy-feature

#13037 fix(estate): add condition for stock cards in estate without assets
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
Labels: automerge

#13039 chore(estate): seperate text for section title
  libs/application/templates/estate/src/forms/Sections/estateWithoutAssets.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#13042 fix(services-university-gateway): Fix infra service name for worker
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#13035 feat(fa): Adding staff to filter and removing months
  apps/financial-aid/api/src/app/modules/application/dto/filterApplications.input.ts
  apps/financial-aid/api/src/app/modules/application/models/filterApplications.response.ts
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/dto/filterApplications.dto.ts
  apps/financial-aid/backend/src/app/modules/application/models/filterApplications.response.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/pages/teymid.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/FilterPopover/FilterPopover.tsx
  apps/financial-aid/web-veita/src/components/Generator/GenerateName.tsx
  apps/financial-aid/web-veita/src/components/TableBody/TableBody.tsx
  apps/financial-aid/web-veita/src/routes/ApplicationsOverview/applicationsOverviewProcessed.tsx
  apps/financial-aid/web-veita/src/routes/Search/search.tsx
  apps/financial-aid/web-veita/src/utils/useApplicationFilter.ts
  apps/financial-aid/web-veita/src/utils/useFilter.ts
  libs/financial-aid/shared/src/lib/enums.ts
  libs/financial-aid/shared/src/lib/formatters.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#13033 fix(web): Add optional locale prop to FaqList component
  apps/web/components/Organization/Slice/OneColumnText/OneColumnTextSlice.tsx
  apps/web/components/Organization/Slice/TwoColumnText/TwoColumnTextSlice.tsx
  apps/web/utils/richText.tsx
  libs/island-ui/contentful/src/lib/FaqList/FaqList.tsx
Labels: automerge

#13047 feat(web): Add imageObject position to default header
  apps/contentful-apps/pages/fields/theme-properties-field.tsx
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/models/organizationTheme.model.ts
Labels: automerge

#13048 fix(estate): debts section should be hidden when no assets
  libs/application/templates/estate/src/forms/Sections/estateDebts.ts
Labels: automerge

#13026 chore(service-portal/health): Add specific health scopes
  apps/download-service/src/app/modules/health/payment-overview-documents.controller.ts
  apps/service-portal/src/auth.ts
  libs/api/domains/rights-portal/src/lib/aidOrNutrition/aidOrNutrition.resolver.ts
  libs/api/domains/rights-portal/src/lib/dentist/dentist.resolver.ts
  libs/api/domains/rights-portal/src/lib/drug/drug.resolver.ts
  libs/api/domains/rights-portal/src/lib/healthCenter/healthCenter.resolver.ts
  libs/api/domains/rights-portal/src/lib/overview/overview.resolver.ts
  libs/api/domains/rights-portal/src/lib/payment/payment.resolver.ts
  libs/api/domains/rights-portal/src/lib/therapy/therapy.resolver.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/health/src/module.tsx
Labels: automerge

#12904 feat(j-s): COA users can update restriction length
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/web/src/components/DateTime/DateTime.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/RestrictionLength/RestrictionLength.spec.tsx
  apps/judicial-system/web/src/components/RestrictionLength/RestrictionLength.strings.ts
  apps/judicial-system/web/src/components/RestrictionLength/RestrictionLength.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.strings.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.spec.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
Labels: automerge

#13050 fix(service-portal): Update health strings
  libs/service-portal/health/src/lib/messages.ts
Labels: automerge

#13052 fix(university gateway): Fix after HÍ api changes
  libs/clients/university-application/university-of-iceland/src/clientConfig.json
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.service.ts
Labels: automerge

#12843 feat(web): Embedded video disclaimer visual update
  apps/contentful-apps/.eslintrc.json
  apps/contentful-apps/pages/api/get-embedded-video-thumbnail-url.ts
  apps/contentful-apps/pages/fields/embedded-video-thumbnail-image-field.tsx
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
  apps/web/components/SignLanguageButton/SignLanguageButton.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Organization/OrganizationEvents/OrganizationEventArticle.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/Article.ts
  apps/web/screens/queries/News.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/embeddedVideo.model.ts
  libs/island-ui/contentful/src/lib/EmbeddedVideo/EmbeddedVideo.css.ts
  libs/island-ui/contentful/src/lib/EmbeddedVideo/EmbeddedVideo.tsx
  libs/island-ui/contentful/src/lib/SectionWithVideo/SectionWithVideo.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/videoEmbed.ts
  package.json
  yarn.lock
Labels: automerge, high priority

#13046 feat(car-recycling): Rollback port changes
  apps/skilavottord/web/next.config.js
  apps/skilavottord/ws/docker-compose.yml
  apps/skilavottord/ws/src/environments/environment.ts
  apps/skilavottord/ws/src/main.ts
Labels: automerge

#12498 feat(user-notification): Store notifications
  apps/services/user-notification/.sequelizerc
  apps/services/user-notification/docker-compose.yml
  apps/services/user-notification/esbuild.json
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/migrations/20231117091125-create-user-notification-table.js
  apps/services/user-notification/project.json
  apps/services/user-notification/sequelize.config.js
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/dto/notification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/infra.controller.ts
  apps/services/user-notification/src/app/modules/notifications/me-notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notification.model.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
  apps/services/user-notification/src/app/sequelizeConfig.service.ts
  apps/services/user-notification/src/buildOpenApi.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-notification/src/openApi.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/notifications.scope.ts
Labels: automerge

#13055 fix(estate): remove share conversion
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
  libs/application/templates/estate/src/utils/getMarketValueShare.ts
Labels: automerge

#13051 feat(signature-collection): scopes
  libs/auth-api-lib/seeders/data/scope-signature-collection.ts
Labels: automerge

#12966 feat(ip): add intellectual properties api domain
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  libs/api/domains/intellectual-properties/.eslintrc.json
  libs/api/domains/intellectual-properties/README.md
  libs/api/domains/intellectual-properties/jest.config.ts
  libs/api/domains/intellectual-properties/project.json
  libs/api/domains/intellectual-properties/src/index.ts
  libs/api/domains/intellectual-properties/src/lib/dto/designImages.input.ts
  libs/api/domains/intellectual-properties/src/lib/dto/ip.input.ts
  libs/api/domains/intellectual-properties/src/lib/intellectalProperties.module.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.resolver.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/mapper.ts
  libs/api/domains/intellectual-properties/src/lib/models/applicationLifecycle.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/category.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/country.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/design.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/image.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/imageList.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/intellectualProperty.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/media.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/patent.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/person.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/specification.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/trademark.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/utils.ts
  libs/api/domains/intellectual-properties/tsconfig.json
  libs/api/domains/intellectual-properties/tsconfig.lib.json
  libs/api/domains/intellectual-properties/tsconfig.spec.json
  libs/clients/intellectual-properties/src/lib/api.config.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge

#13058 chore(auth-api-lib): Add custom delegation scope rule for two new application scopes
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#12625 feat(service-portal): finance v2
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/finance/src/lib/models/chargeItemSubjectsByYear.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypeDetails.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypePeriodSubject.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypesByYear.model.ts
  libs/clients/finance-v2/src/lib/financeV2.module.ts
  libs/clients/finance-v2/src/lib/financeV2.service.ts
  libs/service-portal/core/src/components/ExpandableTable/Header.tsx
  libs/service-portal/core/src/components/TabNavigation/SubTabItem.tsx
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/core/src/utils/periodFormat.ts
  libs/service-portal/finance/src/components/FinanceIntro/index.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTable.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRow.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRowCompressed.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsContext.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsFilter.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTable.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTableDetail.css.ts
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTableDetail.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTableRow.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTypes.ts
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionSelectedPeriod.tsx
  libs/service-portal/finance/src/components/FinanceTransactionsTable/FinanceTransactionsTable.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/lib/navigation.ts
  libs/service-portal/finance/src/lib/paths.ts
  libs/service-portal/finance/src/module.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactionPeriods/FinanceTransactionPeriods.graphql
  libs/service-portal/finance/src/screens/FinanceTransactionPeriods/FinanceTransactionPeriods.tsx
  libs/service-portal/finance/src/screens/FinanceTransactionPeriods/index.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/finance/src/utils/cropText.ts
  libs/service-portal/finance/src/utils/dataHeaders.ts
  libs/service-portal/finance/src/utils/filesPeriodBreakdown.ts
  libs/service-portal/finance/src/utils/simpleFilter.ts
Labels: automerge

#13059 feat(national-registry-v3): Update swagger
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/resolvers/childCustody.resolver.ts
  libs/api/domains/national-registry/src/lib/resolvers/person.resolver.ts
  libs/api/domains/national-registry/src/lib/shared/mapper.ts
  libs/api/domains/national-registry/src/lib/shared/models/person.model.ts
  libs/api/domains/national-registry/src/lib/shared/models/personBase.model.ts
  libs/api/domains/national-registry/src/lib/shared/types.ts
  libs/api/domains/national-registry/src/lib/v3/broker.service.ts
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/clients/national-registry/v3/project.json
  libs/clients/national-registry/v3/src/clientConfig.json
  libs/clients/national-registry/v3/src/lib/nationalRegistryV3.service.ts
  libs/service-portal/information/src/screens/Child/Child.graphql
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.graphql
Labels: automerge

#13063 fix(service-portal): Update provider for loan section
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  libs/service-portal/finance/src/lib/navigation.ts
Labels: automerge

#13061 fix(social-insurance-administration): updates to sia applications
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
  libs/application/templates/social-insurance-administration/core/project.json
  libs/application/templates/social-insurance-administration/core/src/messages.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/clients/social-insurance-administration/src/clientConfig.yaml
Labels: automerge

#13057 fix(estate): add condition to extra confirm field
  libs/application/templates/estate/src/forms/OverviewSections/confirmAction.ts
Labels: automerge

#12967 feat(service-portal): Add ip pages
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/models/trademark.model.ts
  libs/island-ui/core/src/lib/Swiper/Swiper.css.ts
  libs/island-ui/core/src/lib/Swiper/Swiper.tsx
  libs/service-portal/assets/src/components/Image/Image.css.ts
  libs/service-portal/assets/src/components/Image/Image.tsx
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/lib/navigation.ts
  libs/service-portal/assets/src/lib/paths.ts
  libs/service-portal/assets/src/module.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.tsx
  libs/service-portal/core/src/components/Gallery/Gallery.tsx
  libs/service-portal/core/src/components/Gallery/GalleryModal.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/core/src/utils/constants.ts
  libs/service-portal/core/src/utils/dateUtils.ts
Labels: automerge

#13066 fix(skilavottord-ws): Fix grantNamespace in skilavottord-ws infra
  apps/skilavottord/ws/infra/ws.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13065 fix(application-system-api): Add missing env variable via xroad config in infra
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13067 fix(University gateway): fix readiness
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#13064 feat(contentful-apps): Increase thumbnail image quality for youtube video thumbnails
  apps/contentful-apps/pages/api/get-embedded-video-thumbnail-url.ts
Labels: automerge

#13068 fix: readiness now redirects to liveness
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#13069 feat(web): Add hljodbokasafn islands header
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/index.ts
Labels: automerge

#13053 feat(application-estate): Settlement Entry Requirements
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
  libs/application/templates/estate/src/lib/utils.ts
  libs/clients/syslumenn/project.json
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.config.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#13070 fix(application-system-api): Adding gql path to the service path for the gql base path in infra
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12989 test(j-s): Court custody flow test
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/support/urls.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-court.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
Labels: automerge

#13071 fix(custom scope origo): cleanup
  apps/application-system/form/src/auth.ts
  libs/api/domains/energy-funds/src/lib/graphql/main.resolver.ts
  libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#13075 fix(application-system-api): Adding gql path to the service path for car recycling
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13072 feat(contentful-apps): Organization subpage slug contentful app
  apps/contentful-apps/pages/fields/organization-subpage-slug-field.tsx
Labels: automerge

#13081 fix(j-s): Defendant Step Validation
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#13082 fix(j-s): Court of Appeals Valid to Dates
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.spec.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
Labels: automerge

#13086 fix(energy funds): update codeowners
  .github/CODEOWNERS
Labels: automerge

#13004 chore(j-s): Allow PROSECUTOR_REPRESENTATIVES to create cases
  apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/xrd-api/src/app/app.dto.ts
  apps/judicial-system/xrd-api/src/app/test/create.spec.ts
Labels: automerge

#13088 fix(application-estate): Correct to which application the <18 applies
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
Labels: automerge

#13085 fix(application-estate): Estate entry requirements
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
  libs/application/templates/estate/src/lib/utils.ts
  libs/clients/syslumenn/project.json
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.config.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#13091 fix(application-estate): Young heir validation
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
Labels: automerge

#13074 fix(ads): explicit discount code sometimes needs flightlegs to and from
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
Labels: automerge

#13095 fix(service-portal): Only show subnav items on tabnav when more than 1
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
Labels: automerge

#13096 fix(ads): explicit discount code sometimes needs flightlegs to and from
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
Labels: automerge

#13084 fix(energy funds): use correct custom scope + update codeowners
  .github/CODEOWNERS
  apps/application-system/form/src/auth.ts
  libs/api/domains/energy-funds/src/lib/graphql/main.resolver.ts
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#13097 fix(digital tachograph drivers card): Allow birthplace to be empty
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/dataProviders/index.ts
Labels: automerge

#13098 chore(ads): Remove juni and aranja from codeowners on ads
  .github/CODEOWNERS
Labels: automerge

#13080 feat(web): Adding connected component for Signature Lists
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderComponents.tsx
  libs/shared/connected/src/index.ts
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
  libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts
Labels: automerge

#13087 fix(energy-funds): UserProfile parameter and price update
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/project.json
  libs/application/templates/energy-funds/src/dataProviders/index.ts
  libs/application/templates/energy-funds/src/lib/messages/information.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/user-profile-api.ts
Labels: automerge

#13102 fix(service-portal): Update finance messages
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx
Labels: automerge

#13105 fix(service-portal): Hotfix - Update finance messages
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx
Labels: automerge

#13017 feat(parental-leave): Fixed period
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13099 fix(signature-collection): Admin - add filter by candidate
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
Labels: automerge

#13111 fix(energy-funds): small fix for grant information
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/lib/dataSchema.ts
Labels: automerge

#13112 fix(service-portal): Health path parents
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/information/src/lib/navigation.ts
Labels: automerge

#13113 feat(parental-leave): Fixed period (#13017)
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13115 fix(application-estate): Resolved !== vs === bug and modified test data
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
Labels: automerge

#13116 fix(application-estate): Estate young heir validation bugfix
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
Labels: automerge

#13100 chore(inheritance-report): change money and deposits to textfield
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#13103 chore(inheritance-report): remove icelandic format on asset bankaccount
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
Labels: automerge

#13118 fix(car-recycling): Fix recycling request not being saved
  apps/skilavottord/ws/src/app/modules/recyclingRequest/dto/createRecyclingRequest.input.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
  libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts
Labels: automerge

#13122 fix(car-recycling): Fix recycling request not being saved (#13118)
  apps/skilavottord/ws/src/app/modules/recyclingRequest/dto/createRecyclingRequest.input.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
  libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts
Labels: automerge

#13110 fix(auth-admin): Permissions search
  libs/portals/admin/ids-admin/src/screens/Permissions/Permissions.tsx
Labels: automerge

#13107 fix(j-s): E2E, Verify update requests completion before continuing
  apps/system-e2e/src/support/api-tools.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-court.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
Labels: automerge

#13123 chore(inheritance-report): change inventory input to textarea
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
Labels: automerge

#13128 feat(social-insurance-administration): Move repeated messages to core
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/review-groups/Payment.tsx
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/fields/Review/review-groups/utils.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/AdditionalSupportForTheElderlyForm.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/AdditionalSupportForTheElderlyTemplate.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/additionalSupportForTheElderlyUtils.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/core/src/constants.ts
  libs/application/templates/social-insurance-administration/core/src/messages.ts
  libs/application/templates/social-insurance-administration/core/src/socialInsuranceAdministrationUtils.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Payment.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/answerValidationSections/fileUploadValidationSection.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.spec.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/EmployersRatioMonthly/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Period/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/PaymentInformation.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/utils.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/fileUpload.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/paymentInfo.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/period.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidators.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidators.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#13126 feat(web): Kilometer fee connected component
  apps/web/components/connected/vehicles/KilometerFee.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/utils/richText.tsx
Labels: automerge

#13125 feat(car-recycling): Fix E2E tests
  apps/system-e2e/src/tests/islandis/application-system/acceptance/car-recycling.spec.ts
Labels: automerge

#13134 fix(contentful-apps): Skip generating organization subpage slug from title on initial render
  apps/contentful-apps/pages/fields/organization-subpage-slug-field.tsx
Labels: automerge

#13136 fix(parental-leave): alert message and period length fix
  libs/application/templates/parental-leave/src/fields/UnEmploymentBenefits/index.tsx
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13124 feat(citizenship): updating citizenship application
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/NationalIdWithGivenFamilyName/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Parents/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/DocumentReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/ResidencyReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/StaysAbroadReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
Labels: automerge

#13138 fix(parental-leave): alert message and period length fix (#13136)
  libs/application/templates/parental-leave/src/fields/UnEmploymentBenefits/index.tsx
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13140 fix(consultation-portal): Hotfix kam 1949
  apps/consultation-portal/screens/Advices/Advices.json
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
Labels: automerge

#13139 fix(consultation-portal): KAM-1949: Fix non binary friendly language
  apps/consultation-portal/screens/Advices/Advices.json
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
Labels: automerge

#13108 chore(user-profile): Migration worker
  apps/services/user-profile/infra/service-portal-api.ts
  apps/services/user-profile/migrations/20231105100001-format-phone-numbers.js
  apps/services/user-profile/migrations/20231105100002-create-migration-table.js
  apps/services/user-profile/project.json
  apps/services/user-profile/src/app/worker/test/worker.spec.ts
  apps/services/user-profile/src/app/worker/types.ts
  apps/services/user-profile/src/app/worker/userProfileAdvania.model.ts
  apps/services/user-profile/src/app/worker/worker.module.ts
  apps/services/user-profile/src/app/worker/worker.service.ts
  apps/services/user-profile/src/app/worker/worker.utils.ts
  apps/services/user-profile/src/environments/environment.ts
  apps/services/user-profile/src/main.ts
  apps/services/user-profile/src/worker.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13135 chore(j-s): XRD API Logging
  apps/judicial-system/xrd-api/src/app/app.controller.ts
  apps/judicial-system/xrd-api/src/app/app.interceptor.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
Labels: automerge

#13094 feat(transfer of vehicle ownership): Make mileage required
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/VehicleSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
Labels: automerge

#13141 fix(energy-funds): Adding contentful text
  libs/application/templates/energy-funds/src/forms/Prerequisites/index.ts
  libs/application/templates/energy-funds/src/lib/messages/externalData.ts
Labels: automerge

#13137 chore(inheritance-report): add currency format to total value
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
Labels: automerge

#13073 feat(user-profile): UserProfile Email Notification & gql refactor
  apps/services/user-profile/migrations/20231129145943-email-notification.js
  apps/services/user-profile/src/app/user-profile/userProfile.model.ts
  apps/services/user-profile/src/app/v2/dto/islyklar-upsert.dto.ts
  apps/services/user-profile/src/app/v2/dto/patch-user-profile.dto.ts
  apps/services/user-profile/src/app/v2/dto/user-profile.dto.ts
  apps/services/user-profile/src/app/v2/islykill.service.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  libs/api/domains/user-profile/src/lib/V1/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/V2/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/dto/updateEmailNotificationsInput.ts
  libs/api/domains/user-profile/src/lib/userProfile.model.ts
  libs/api/domains/user-profile/src/lib/userProfile.module.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/clients/user-profile/src/lib/apiConfiguration.ts
  libs/clients/user-profile/src/lib/apis.ts
  libs/clients/user-profile/src/lib/userProfileClient.module.ts
  libs/service-portal/graphql/src/lib/queries/getUserProfile.ts
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Nudge.tsx
Labels: automerge

#13145 fix(service-portal): Health fallback string and table empty
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
Labels: automerge

#13146 chore(ads): removing many flights option
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/dto/params.dto.ts
  libs/api/domains/air-discount-scheme/src/lib/discount-admin/dto/createExplicitDiscountCode.input.ts
  libs/portals/admin/air-discount-scheme/src/screens/CreateDiscount/CreateDiscount.tsx
  libs/portals/admin/air-discount-scheme/src/screens/SuperDiscount/SuperDiscount.tsx
Labels: automerge

#13147 feat(parental-leave): Revert period fix
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13148 feat(parental-leave): Revert period fix (#13147)
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13121 feat(service-portal): Add file download for health tables
  libs/service-portal/core/src/components/DownloadFileButtons/DownloadFileButtons.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/utils/downloadDataFile.ts
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.css.ts
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionSelectedPeriod.tsx
  libs/service-portal/finance/src/utils/filesGeneral.ts
  libs/service-portal/finance/src/utils/filesGjoldSundurlidun.ts
  libs/service-portal/finance/src/utils/filesGreidslustada.ts
  libs/service-portal/finance/src/utils/filesHreyfingar.ts
  libs/service-portal/finance/src/utils/filesPeriodBreakdown.ts
  libs/service-portal/health/src/components/ExpiringTable/ExpiringTable.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/NutritionTable.tsx
  libs/service-portal/health/src/screens/Dentists/BillsTable.tsx
  libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/utils/FileBreakdown/dataHeaders.ts
  libs/service-portal/health/src/utils/FileBreakdown/filesStructure.ts
  libs/service-portal/health/src/utils/FileBreakdown/index.ts
  libs/service-portal/health/src/utils/format.ts
Labels: automerge

#13132 chore(core): package.json dependency/resolution cleanup
  apps/web/components/OpenApiDocumentation/OpenApiDocumentation.tsx
  package.json
  yarn.lock
Labels: automerge

#13153 fix(consultation-portal): fix non binary friendly text
  apps/consultation-portal/screens/Case/Case.json
Labels: automerge

#13154 fix(consultation-portal): fix non binary friendly text
  apps/consultation-portal/screens/Case/Case.json
Labels: automerge

#13149 feat(skilavottord): update fix if new vehicle owner
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
Labels: automerge

#13157 feat(web): Hotfix - Add hljodbokasafn islands header (#13069)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/HljodbokasafnIslandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HljodbokasafnIslandsTheme/index.ts
Labels: automerge

#13158 feat(web): Hotfix - Kilometer fee calculator
  apps/web/components/connected/vehicles/KilometerFee.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/utils/richText.tsx
Labels: automerge

#13151 fix(healtcare license certificate): Small fixes after testing
  libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/index.ts
  libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/personalSection.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/confirmation.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/error.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/information.ts
  libs/application/templates/healthcare-license-certificate/src/utils/getChargeItemCodes.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/ApplicantSection/userInformationSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
Labels: automerge

#13152 feat(web): Replace === with .includes() for administration of occupational safety and health course cards
  apps/web/components/connected/AdministrationOfOccupationalSafetyAndHealthCourses/AdministrationOfOccupationalSafetyAndHealthCourses.tsx
Labels: automerge

#12810 feat(service-portal): Add simple path masking
  libs/api/domains/national-registry/src/lib/shared/models/person.model.ts
  libs/api/domains/national-registry/src/lib/v3/broker.service.ts
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/information/src/screens/Child/Child.graphql
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/simpleEncryption.spec.ts
  libs/shared/utils/src/lib/simpleEncryption.ts
Labels: automerge

#13163 fix(healtcare license certificate): Small fixes after testing
  libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/index.ts
  libs/application/templates/healthcare-license-certificate/src/forms/HealthcareLicenseCertificateForm/personalSection.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/confirmation.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/error.ts
  libs/application/templates/healthcare-license-certificate/src/lib/messages/information.ts
  libs/application/templates/healthcare-license-certificate/src/utils/getChargeItemCodes.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/ownerSubSection.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/forms/DigitalTachographDriversCardForm/ApplicantSection/userInformationSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/sellerSubSection.ts
Labels: automerge

#13156 fix(web): Kilometer fee calculator visual changes
  apps/web/components/connected/vehicles/KilometerFee.tsx
Labels: automerge

#13090 feat(web): Add organizationPage sidebarCards in mobile
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#13120 feat(web): Display manuals on category page
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/screens/Category/Category/Category.tsx
  apps/web/screens/Manual/components/ManualHeader.tsx
  apps/web/screens/queries/Category.tsx
  apps/web/screens/queries/Manual.ts
  apps/web/screens/queries/Search.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getCategoryPages.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/categoryPage.model.ts
  libs/cms/src/lib/models/manual.model.ts
  libs/cms/src/lib/search/importers/manual.service.ts
Labels: automerge

#13104 feat(web): Add "anchor links" to manual chapter items
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/screens/Manual/ManualChapter.tsx
  apps/web/screens/Search/Search.tsx
Labels: automerge

#13119 feat(new UI component): NationalIdWithName
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-components/src/components/NationalIdWithName/NationalIdWithName.tsx
  libs/application/ui-components/src/components/NationalIdWithName/graphql/queries.ts
  libs/application/ui-components/src/index.ts
  libs/application/ui-fields/src/lib/NationalIdWithNameFormField/NationalIdWithNameFormField.stories.mdx
  libs/application/ui-fields/src/lib/NationalIdWithNameFormField/NationalIdWithNameFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
Labels: automerge
