Repository island-is/island.is, pull requests merged in 2023-07, with the labels that each got.

#11640 chore(search-indexer): Add support categories as nested types
  libs/cms/src/lib/environments/environment.ts
Labels: automerge

#11639 fix(application-driving-license-duplicate): Add markdown to description field
  libs/application/templates/driving-license-duplicate/src/lib/messages.ts
Labels: automerge

#11642 fix(regulations): Amending format fix
  libs/clients/regulations-admin/src/lib/RegulationsAdminClientService.ts
  libs/portals/admin/regulations-admin/src/components/EditMeta.tsx
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#11647 fix(web): Fix asset mapping
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#11648 fix(application-system): Template not found now logged as an info
  apps/application-system/api/src/app/modules/application/application.controller.ts
Labels: automerge

#11650 fix(application-system): Change error to info templatenotfound
  apps/application-system/api/src/app/modules/application/application.controller.ts
Labels: automerge

#11644 fix(application-driving-license-duplicate): Improve logging
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
Labels: automerge

#11655 fix(work-machines): add logging
  libs/api/domains/work-machines/src/index.ts
  libs/api/domains/work-machines/src/lib/dto/getDocuments.input.ts
  libs/api/domains/work-machines/src/lib/models/getWorkMachines.ts
  libs/api/domains/work-machines/src/lib/workMachines.module.ts
  libs/api/domains/work-machines/src/lib/workMachines.resolver.ts
  libs/api/domains/work-machines/src/lib/workMachines.service.ts
  libs/api/domains/work-machines/src/lib/workMachines.types.ts
Labels: automerge

#11663 fix(application-driving-license-duplicate): Final touches
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
  libs/application/templates/driving-license-duplicate/src/lib/messages.ts
Labels: automerge

#11653 fix(service-portal): Update my info overveiw paths
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/information/src/module.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge, deploy-feature

#11427 fix(consultation-portal): KAM-1356-tests-failing
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consts.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-unauthenticated.spec.ts
Labels: automerge

#11645 fix(license-service): some fixes
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseMappers.ts
Labels: automerge

#11665 fix(service-portal): Hotfix - Update my info overveiw paths
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/information/src/module.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
Labels: automerge

#11654 fix(clients-rsk-relationships): Update rsk basepath to relationships service
  apps/api/infra/api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#11668 feat(clients-driving-license): Add basic testing scaffold
  libs/clients/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.spec.ts
Labels: automerge

#11618 fix(passport): Adding history logs
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/messages.ts
Labels: automerge

#11669 fix(service-portal): wrong namespace
  libs/service-portal/vehicles/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/vehicles/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
Labels: automerge

#11670 fix(service-portal): Hotfix - wrong namespace
  libs/service-portal/vehicles/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/vehicles/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
Labels: automerge

#11656 feat(web): Add logos to "Opinber Nýsköpun" footer
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx
  apps/web/screens/Project/components/ProjectFooter/themes/OpinberNyskopun/OpinberNyskopunFooter.tsx
Labels: automerge

#11676 chore(web): Allow process entry links to be relative
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#11671 feat(contentful-apps): Add preview link for vacancy content type
  apps/contentful-apps/pages/sidebars/preview-link.tsx
Labels: automerge

#11672 fix(general-petition): adding action card history logs
  libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts
  libs/application/templates/general-petition/src/lib/messages.ts
Labels: automerge

#11673 fix(operating-license): Action card history logs
  libs/application/templates/operating-license/src/fields/Bullets/index.tsx
  libs/application/templates/operating-license/src/fields/Done/Congratulations.tsx
  libs/application/templates/operating-license/src/fields/Done/index.tsx
  libs/application/templates/operating-license/src/fields/PaymentCharge/index.tsx
  libs/application/templates/operating-license/src/fields/index.ts
  libs/application/templates/operating-license/src/forms/Done.ts
  libs/application/templates/operating-license/src/forms/Payment.tsx
  libs/application/templates/operating-license/src/forms/draft/draft.ts
  libs/application/templates/operating-license/src/forms/draft/sectionOverview.ts
  libs/application/templates/operating-license/src/forms/draft/subSectionOpeningHours.ts
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/application/templates/operating-license/src/lib/messages.ts
Labels: automerge

#11664 chore(service-portal): Update e2e tests + add uni tests.
  apps/system-e2e/src/tests/islandis/service-portal/smoke/information.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/university.spec.ts
Labels: automerge

#11680 fix(aod): Aod history logs action cards
  libs/application/templates/announcement-of-death/src/forms/done.ts
  libs/application/templates/announcement-of-death/src/lib/announcementOfDeathTemplate.ts
  libs/application/templates/announcement-of-death/src/lib/constants.ts
  libs/application/templates/announcement-of-death/src/lib/messages.ts
Labels: automerge

#11682 fix(estate): Estate history logs
  libs/application/templates/driving-assessment-approval/src/fields/Congratulations.tsx
  libs/application/templates/driving-assessment-approval/src/fields/StudentLookupField.tsx
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
Labels: automerge

#11684 fix(license-service): add expiration dates
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
Labels: automerge

#11688 chore(application-driving-learners-permit): Add history logs
  libs/application/templates/driving-learners-permit/src/lib/DrivingLearnersPermitTemplate.ts
Labels: automerge

#11687 fix(driving-license): Historylogs
  libs/application/templates/driving-license/src/assets/Company.tsx
  libs/application/templates/driving-license/src/assets/LogreglanLogo.tsx
  libs/application/templates/driving-license/src/assets/index.ts
  libs/application/templates/driving-license/src/fields/HealthDeclaration.tsx
  libs/application/templates/driving-license/src/fields/PaymentPending/PaymentPending.tsx
  libs/application/templates/driving-license/src/fields/PaymentPending/index.tsx
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionOtherCountry.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/p-sign/src/fields/Bullets/index.tsx
  libs/application/templates/p-sign/src/fields/Done/Congratulations.tsx
  libs/application/templates/p-sign/src/fields/Done/WarningSection/index.tsx
  libs/application/templates/p-sign/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/p-sign/src/fields/UploadedPhoto/index.tsx
  libs/application/templates/p-sign/src/fields/index.ts
  libs/application/templates/p-sign/src/forms/application.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionOverview.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
Labels: automerge

#11689 fix(license-service): Hotfix - add expiration for firearm licenses
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/firearmLicenseApiClient.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
Labels: automerge

#11681 fix(clients-rsk-relationships): Update RSK lookup method
  apps/services/auth/delegation-api/infra/delegation-api.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/clients/rsk/relationships/src/lib/RskRelationshipsClient.ts
  libs/clients/rsk/relationships/src/lib/RskRelationshipsClientConfig.ts
  libs/clients/rsk/relationships/src/lib/apiConfiguration.ts
Labels: automerge

#11690 fix(island-ui): Upgrade react-animate-height
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx
  libs/service-portal/core/src/components/ExpandableTable/Row.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/ExpandableLine.tsx
  package.json
  yarn.lock
Labels: automerge

#11652 feat(j-s): xRoad API Citizenship
  apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/xrd-api/src/app/app.dto.ts
Labels: automerge

#11660 fix(j-s): Indictment Description
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#11661 chore(j-s): Court Litigants
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/court-client/src/lib/courtClient.config.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#11667 fix(j-s): Admin User Page Header
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
Labels: automerge

#11691 ci(system-e2e): No tesults?
  scripts/local-e2e.sh
  scripts/utils.sh
Labels: automerge

#11696 feat(web): Hotfix - Add logos to "Opinber Nýsköpun" footer (#11656)
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/components/ProjectFooter/ProjectFooter.tsx
  apps/web/screens/Project/components/ProjectFooter/themes/OpinberNyskopun/OpinberNyskopunFooter.tsx
Labels: automerge

#11693 feat(web): Add relative url mapping so CMS links can point to prod and code makes them relative
  libs/cms/src/lib/models/link.model.ts
  libs/cms/src/lib/models/processEntry.model.ts
  libs/cms/src/lib/models/referenceLink.model.ts
  libs/cms/src/lib/models/utils.ts
Labels: automerge

#11694 fix(contentful-apps): Publish date field should publish entry again to store it's value
  apps/contentful-apps/pages/fields/publish-date-field.tsx
Labels: automerge

#11695 fix(service-portal): Download/copy link for list in mobile
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/styles.css.ts
Labels: automerge

#11637 fix(j-s): Ruling Date
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/api/src/app/modules/caseList/models/caseList.model.ts
  apps/judicial-system/backend/migrations/20230607135600-update-case.js
  apps/judicial-system/backend/migrations/20230629173643-update-case.js
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseListEntry.response.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/RulingDateLabel/RulingDateLabel.strings.ts
  apps/judicial-system/web/src/components/RulingDateLabel/RulingDateLabel.tsx
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/components/Table/DurationDate/DurationDate.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCases.spec.ts
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseFilesOverview/CaseFilesOverview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDocuments/CaseDocuments.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  apps/judicial-system/web/src/utils/mutations.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
  libs/judicial-system/types/src/lib/case.spec.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#11709 fix(consultation-portal): bug fixed and added sort
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocuments.tsx
  apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.tsx
  apps/consultation-portal/utils/helpers/sortLocale.ts
Labels: automerge

#11706 feat(web): Hotfix - News filters
  apps/web/components/NewsList/NewsList.tsx
  apps/web/components/NewsList/NewsListSidebar.tsx
  apps/web/components/NewsList/utils.ts
  apps/web/constants/index.ts
  apps/web/screens/Home/Home.tsx
  apps/web/screens/News.tsx
  apps/web/screens/Organization/OrganizationNewsArticle.tsx
  apps/web/screens/Organization/OrganizationNewsList.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/queries/News.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/dto/getNews.input.ts
  libs/cms/src/lib/dto/getNewsDates.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/latestNewsSlice.model.ts
  libs/cms/src/lib/models/news.model.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
  libs/cms/src/lib/search/importers/news.service.ts
Labels: automerge

#11698 feat(web): Aircraft registry search on public web
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/connected/vehicles/AircraftSearch.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/screens/queries/AircraftSearch.ts
  apps/web/utils/richText.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/aircraft-registry/.eslintrc.json
  libs/api/domains/aircraft-registry/README.md
  libs/api/domains/aircraft-registry/jest.config.js
  libs/api/domains/aircraft-registry/project.json
  libs/api/domains/aircraft-registry/src/index.ts
  libs/api/domains/aircraft-registry/src/lib/aircraftRegistry.module.ts
  libs/api/domains/aircraft-registry/src/lib/aircraftRegistry.resolver.ts
  libs/api/domains/aircraft-registry/src/lib/aircraftRegistry.service.ts
  libs/api/domains/aircraft-registry/src/lib/dto/aircraftsBySearchTerm.input.ts
  libs/api/domains/aircraft-registry/src/lib/dto/aircraftsBySearchTermResponse.ts
  libs/api/domains/aircraft-registry/src/lib/dto/allAircrafts.input.ts
  libs/api/domains/aircraft-registry/src/lib/dto/allAircraftsResponse.ts
  libs/api/domains/aircraft-registry/src/lib/models/aircraft.model.ts
  libs/api/domains/aircraft-registry/tsconfig.json
  libs/api/domains/aircraft-registry/tsconfig.lib.json
  libs/api/domains/aircraft-registry/tsconfig.spec.json
  libs/clients/aircraft-registry/.eslintrc.json
  libs/clients/aircraft-registry/README.md
  libs/clients/aircraft-registry/jest.config.js
  libs/clients/aircraft-registry/project.json
  libs/clients/aircraft-registry/src/clientConfig.json
  libs/clients/aircraft-registry/src/index.ts
  libs/clients/aircraft-registry/src/lib/aircraftRegistryClient.config.ts
  libs/clients/aircraft-registry/src/lib/aircraftRegistryClient.module.ts
  libs/clients/aircraft-registry/src/lib/apiConfig.ts
  libs/clients/aircraft-registry/src/lib/apiProvider.ts
  libs/clients/aircraft-registry/tsconfig.json
  libs/clients/aircraft-registry/tsconfig.lib.json
  libs/clients/aircraft-registry/tsconfig.spec.json
  libs/clients/icelandic-government-institution-vacancies/README.md
  tsconfig.base.json
  workspace.json
Labels: automerge

#11711 ci(system-e2e): Disable broken test
  apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts
Labels: automerge

#11662 chore(devx): Disable schema generation in postinstall
  README.md
  package.json
  scripts/postinstall.js
Labels: automerge

#11725 fix(yarn): Better post-install env variable
  scripts/postinstall.js
Labels: automerge

#11708 feat(web): Driving instructors on public web
  apps/web/components/connected/DrivingInstructorList/DrivingInstructorList.tsx
  apps/web/components/connected/DrivingInstructorList/index.ts
  apps/web/components/connected/index.ts
  apps/web/screens/queries/DrivingInstructors.ts
  apps/web/utils/richText.tsx
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/teacher.model.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#11718 fix(web): Revert web news frontend changes
  apps/web/components/NewsList/NewsList.tsx
  apps/web/components/NewsList/NewsListSidebar.tsx
  apps/web/components/NewsList/utils.ts
  apps/web/screens/News.tsx
  apps/web/screens/Organization/OrganizationNewsArticle.tsx
  apps/web/screens/Organization/OrganizationNewsList.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/queries/News.tsx
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/dto/getNewsDates.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#11719 fix(j-s): Adding text to court record when session arrangements are none present
  apps/judicial-system/web/messages/InvestigationCases/Court/courtRecordForm.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
Labels: automerge

#11726 fix(consultation-portal): KAM-1429-pdf-opens-in-new-window-in-about-page
  apps/consultation-portal/screens/About/components/AboutContent/AboutRTF.tsx
Labels: automerge

#11728 fix(consultation-portal): change scope and fix advice filename rendering
  apps/consultation-portal/lib/environment.ts
  apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.tsx
Labels: automerge

#11717 feat(web): Store search filters in url for published material pages
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
Labels: automerge

#11729 fix(j-s): Court of appeal route navigation updated
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
Labels: automerge

#11733 feat(search-indexer-service): Add env variable for disabling nested resolution of entries from CMS
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/search/contentful.service.ts
Labels: automerge

#11734 revert: schemas in postinstall
  README.md
  package.json
  scripts/postinstall.js
Labels: automerge

#11721 fix(j-s): Adding all defendants to indictment introduction
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
Labels: automerge

#11543 feat(j-s): Adding Löke number selection to front-end
  apps/judicial-system/api/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
Labels: automerge

#11737 feat(search-indexer-service): Add env variable for disabling nested resolution of entries from CMS (#11733)
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/search/contentful.service.ts
Labels: automerge

#11736 fix: increased ids memory limits
  apps/auth-admin-web/infra/auth-admin-web.ts
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#11730 fix(web): Only update order query param if it's state changed on Published Material page
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
Labels: automerge

#11701 feat(j-s): Adding created at to past and active table
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/components/Table/CreatedDate/CreatedDate.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/MobilePastCase.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/components/Table/SortButton/SortButton.tsx
  apps/judicial-system/web/src/components/Table/index.ts
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSortAppealCases.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSortCases.ts
Labels: automerge

#11744 fix(core): Broken metric server response
  apps/services/auth/delegation-api/src/environments/environment.ts
  libs/infra-metrics/src/lib/startMetricServer.ts
Labels: automerge

#11657 fix(j-s): Defender Case Refresh
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
  apps/judicial-system/web/src/components/UserProvider/UserProvider.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  apps/judicial-system/web/src/utils/hooks/useInstitution/index.ts
  apps/judicial-system/web/src/utils/titleForCase/titleForCase.ts
Labels: automerge

#11723 feat(auth-admin): SuperAdmin check for editing permissions
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth-api-lib/src/lib/resources/admin/dto/admin-patch-scope.dto.ts
  libs/portals/admin/ids-admin/src/screens/Permission/EditPermission.tsx
Labels: automerge

#11749 feat(contentful-apps): Refetch parent on sys change for Baby Article url field extension
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
Labels: automerge

#11740 chore: No schema postinstall
  README.md
  scripts/postinstall.js
Labels: automerge

#11746 fix(j-s): disable police case number input field if the police case number is from Löke
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
Labels: automerge

#11745 fix(j-s): Adding indent for introduction in indictment
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
Labels: automerge

#11752 fix(j-s): Making mobile past cases sort in descending
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
Labels: automerge

#11743 feat(j-s): Adding error message when Löke numbers failed to be fetched
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.tsx
Labels: automerge

#11735 fix(island-ui): PhoneInput error state styles
  libs/island-ui/core/src/lib/PhoneInput/PhoneInput.css.ts
Labels: automerge

#11761 chore(infra): Fix deprecated set-output usage
  .github/actions/cache/action.yml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge, deploy-feature

#11748 fix(license-api): re-enable the photo check
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
Labels: automerge

#11760 feat(datadog): CI testing
  .github/actions/unit-test/action.yml
  .github/workflows/pullrequest.yml
  scripts/ci/30_test.sh
Labels: automerge

#11741 fix(Application-system): Complaints-to-althingi-ombudsman validation
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplainedFor.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
Labels: automerge

#11759 fix(application-system): Complaints to althingi ombudsman QA fixes
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complainee.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintDescription.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintInformation.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/preexistingComplaint.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#11754 chore: Move islyklar to EFS
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/types/input-types.ts
  infra/src/dsl/types/output-types.ts
  infra/src/dsl/volumes.spec.ts
Labels: automerge, deploy-feature

#11772 chore(search-indexer): Re-enable nested fetching for search indexer entries
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#11747 feat(j-s): Select all police cases
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.tsx
Labels: automerge

#11780 revert: "chore: Move islyklar to EFS (#11754)"
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/types/input-types.ts
  infra/src/dsl/types/output-types.ts
  infra/src/dsl/volumes.spec.ts
Labels: automerge

#11765 test(system-e2e): Fix broken test
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
Labels: automerge

#11781 feat(web): Hotfix - Organization news filters update
  apps/web/components/NewsList/NewsList.tsx
  apps/web/components/NewsList/NewsListSidebar.tsx
  apps/web/components/NewsList/utils.ts
  apps/web/screens/News.tsx
  apps/web/screens/Organization/OrganizationNewsArticle.tsx
  apps/web/screens/Organization/OrganizationNewsList.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/queries/News.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/dto/getNewsDates.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
Labels: automerge

#11767 docs(system-e2e): More docs
  SUMMARY.md
  apps/system-e2e/README.md
Labels: automerge
