Repository island-is/island.is, pull requests merged in 2023-11, with the labels that each got.

#12567 fix(j-s): Appeal File Dates
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
Labels: automerge

#12586 feat(j-s): Warning for COA if appealed after deadline
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
Labels: automerge

#12580 fix(j-s): Reorder Files
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
Labels: automerge

#12587 fix(estate): Adding relation with applicant
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/estate/src/types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
Labels: automerge

#12590 fix(passport): small bug fix for disability checkbox
  libs/application/templates/passport/src/lib/utils.ts
Labels: automerge

#12585 fix(search-indexer): update docker image
  apps/services/search-indexer/dev-services/README.md
  apps/services/search-indexer/dev-services/elasticsearch/Dockerfile
Labels: automerge

#12592 feat(web): Allow powerbi embed for Embed content type in CMS
  apps/contentful-apps/pages/fields/embed-link-field.tsx
Labels: automerge

#12595 fix(application-driving-license): Plaster for miscalculated phone
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
Labels: automerge

#12598 fix(application-driving-license): Driving license phone external fix
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
Labels: automerge

#12530 feat(j-s): Send notification when COA judges have been assigned
  apps/judicial-system/backend/migrations/20231025140547-update-notification.js
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealJudgesAssignedNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAppealJudgesAssignedNotification.spec.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web/src/components/Modal/Modal.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#12588 chore(j-s): Change background color on files that can't be opened
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfButton.css.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
Labels: automerge

#12599 chore(service-portal): Add tab navigation as button navigation
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/components/TabNavigation/SubTabItem.tsx
  apps/service-portal/src/components/TabNavigation/TabNavigation.css.ts
  apps/service-portal/src/components/TabNavigation/TabNavigation.tsx
Labels: automerge

#12566 chore(j-s): Do not have a default selected option for requestSharedWithDefender
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/defendant.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/defendant.spec.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/RequiredStar/RequiredStar.css.ts
  apps/judicial-system/web/src/components/RequiredStar/RequiredStar.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#12600 chore(j-s): DB Indexes
  apps/judicial-system/backend/migrations/20231031174234-create-indexes.js
Labels: automerge

#12581 feat(web): link card on articles
  apps/web/components/DataLinkCard/DataLinkCard.tsx
  apps/web/components/DataLinkSection/DataLinkSection.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/queries/OpenDataPage.ts
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/linkCard.model.ts
  libs/cms/src/lib/models/linkCardSection.model.ts
  libs/cms/src/lib/models/openDataPage.model.ts
  libs/cms/src/lib/unions/slice.union.ts
  libs/island-ui/contentful/src/lib/LinkCard/LinkCard.tsx
  libs/island-ui/contentful/src/lib/RichTextRC/RichText.tsx
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderComponents.tsx
  libs/island-ui/contentful/src/lib/richTextRendering.tsx
  libs/island-ui/core/src/index.ts
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#12560 feat(j-s): Case header info
  apps/judicial-system/web-e2e/src/integration/Defender/caseOverview.spec.ts
  apps/judicial-system/web/src/components/CaseTitleInfoAndTags/CaseTitleInfoAndTags.strings.ts
  apps/judicial-system/web/src/components/CaseTitleInfoAndTags/CaseTitleInfoAndTags.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
Labels: automerge

#12604 fix(consultation-portal): KAM-1843: some case detail pages fail
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#12606 fix(consultation-portal): Hotfix kam 1843
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#12608 fix(j-s): Notification Permissions
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
Labels: automerge

#12609 fix(parental-leave): Fix type in emails
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/reference-template/emailGenerators/assignEmail.ts
Labels: automerge

#12610 fix(consultation-portal): Kam 1844 filter numbers not always updating
  apps/consultation-portal/hooks/useFrontPageFilters.ts
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Case/CaseMobile.tsx
  apps/consultation-portal/screens/Case/utils/index.ts
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#12611 fix(consultation-portal): Kam 1844 filter numbers not always updating
  apps/consultation-portal/hooks/useFrontPageFilters.ts
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Case/CaseMobile.tsx
  apps/consultation-portal/screens/Case/utils/index.ts
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#12447 feat(license-service): add pcard to license service
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/api/domains/license-service/src/lib/mappers/licenseMapper.module.ts
  libs/api/domains/license-service/src/lib/mappers/pCardMapper.ts
  libs/api/domains/license-service/src/lib/utils/translations.ts
  libs/clients/license-client/src/lib/clients/adr-license-client/adrLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/disability-license-client/services/disabilityLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/driving-license-client/services/drivingLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/firearm-license-client/services/firearmLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/machine-license-client/machineLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/p-card-client/index.ts
  libs/clients/license-client/src/lib/clients/p-card-client/pCardClient.module.ts
  libs/clients/license-client/src/lib/clients/p-card-client/pCardClient.service.ts
  libs/clients/license-client/src/lib/licenseClient.module.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/utils/dataMapper.ts
Labels: automerge, deploy-feature

#12461 fix(passport): Fixing legal residence check
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/fields/PassportSelection/index.tsx
  libs/application/templates/passport/src/lib/messages.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/national-registry-user.ts
Labels: automerge

#12436 fix(island-ui): Hide PDF pagination when not needed
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/PdfDocument.tsx
  libs/service-portal/documents/src/utils/messages.ts
Labels: automerge

#12618 fix: KAM-1847: Subscription option should not show up until verified email
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/screens/Subscriptions/components/EmailBox/EmailBox.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#12621 fix: KAM-1847: Subscription option should not show up until verified …
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/screens/Subscriptions/components/EmailBox/EmailBox.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#12612 fix(parental-leave): StartDate could be 3 months ago
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge, autoupdate

#12622 fix(j-s): Re-add missing COA overview and result info
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
Labels: automerge

#12619 fix(j-s): Contentful String
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts
Labels: automerge

#12631 fix(service-portal): Institution panel update image
  libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.tsx
Labels: automerge

#12623 chore(regulations): Update regulation tools
  package.json
  yarn.lock
Labels: automerge

#12620 chore(j-s): Query Performance
  apps/judicial-system/backend/migrations/20231103121842-create-indexes.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
Labels: automerge

#12601 chore(j-s): Add tail to all sms and emails with a link to RVG
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
Labels: automerge

#12628 fix(web): Plausible tracking for organizations
  apps/web/hooks/usePlausiblePageview.ts
Labels: automerge

#12495 feat(service-portal): add ehic card
  .github/CODEOWNERS
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/mappers/ehicCardMapper.ts
  libs/api/domains/license-service/src/lib/mappers/licenseMapper.module.ts
  libs/api/domains/license-service/src/lib/utils/translations.ts
  libs/api/domains/rights-portal/src/lib/payment/payment.service.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
  libs/clients/icelandic-health-insurance/rights-portal/src/index.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/lib/providers.ts
  libs/clients/license-client/src/index.ts
  libs/clients/license-client/src/lib/clients/ehic-card-client/ehicCardClient.module.ts
  libs/clients/license-client/src/lib/clients/ehic-card-client/ehicCardClient.service.ts
  libs/clients/license-client/src/lib/clients/ehic-card-client/ehicCardClient.type.ts
  libs/clients/license-client/src/lib/clients/ehic-card-client/index.ts
  libs/clients/license-client/src/lib/licenseClient.module.ts
  libs/clients/license-client/src/lib/licenseClient.type.ts
  libs/clients/p-card/src/clientConfig.json
  libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/health/src/components/ExpiringTable/ExpiringTable.tsx
  libs/service-portal/health/src/components/FootNote/FootNote.tsx
  libs/service-portal/health/src/components/FootNote/helper.tsx
  libs/service-portal/health/src/components/TherapiesTabContent/TherapiesTabContent.tsx
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/utils/dataMapper.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/getDocument.ts
Labels: automerge, deploy-feature

#12632 fix(consultation-portal): Kam 1852 fix spelling and wording
  apps/consultation-portal/lib/shared.json
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Case/CaseMobile.tsx
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#12602 fix(j-s): Remove thick border from indictment files list
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.css.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
Labels: automerge

#12638 fix(download-service): Add health insurance path dl service
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12637 ci: run config values job in pre-release, remove unsupported create event
  .github/CODEOWNERS
  .github/workflows/config-values.yaml
  .gitignore
Labels: automerge

#12641 ci: revert codeowners
  .github/CODEOWNERS
Labels: automerge

#12643 fix(consultation-portal): Kam 1853 my subscriptions not showing up
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#12636 fix(web): Plausible custom pageview event for organization domains
  apps/web/hooks/usePlausiblePageview.ts
Labels: automerge

#12647 fix(web): Plausible custom pageview event for organization domains (#…
  apps/web/hooks/usePlausiblePageview.ts
Labels: automerge

#12639 fix(download-service): Hotfix - Add health insurance path dl service
  .github/CODEOWNERS
  .github/actions/dist/check-team-approval.js
  .github/actions/package.json
  .github/workflows/pullrequest.yml
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12649 chore(core): Simplify infra config to add NPM_CONFIG_UPDATE_NOTIFIER=false to turn of npm notice logs
  apps/air-discount-scheme/api/infra/api.ts
  apps/air-discount-scheme/backend/infra/backend.ts
  apps/api/infra/api.ts
  apps/application-system/api/infra/application-system-api.ts
  apps/icelandic-names-registry/backend/infra/icelandic-names-registry-backend.ts
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/services/auth/ids-api/infra/identity-server.ts
  apps/services/documents/infra/documents-service.ts
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/sessions/infra/sessions.ts
  apps/services/user-profile/infra/service-portal-api.ts
  apps/skilavottord/web/infra/web.ts
  apps/skilavottord/ws/infra/ws.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/dsl.ts
  infra/src/environments.ts
Labels: automerge

#12655 fix(consultation-portal): Hotfix kam 1852
  apps/consultation-portal/lib/shared.json
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Case/CaseMobile.tsx
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#12657 fix(consultation-portal): Hotfix kam 1853
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#12624 fix(j-s): Fix flickering alert banner
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
Labels: automerge

#12627 feat(j-s): Update prosecutor demands and requested valid to date when case is resent
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
Labels: automerge

#12635 fix(service-portal): Update sp e2e tests
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/occupational-licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-machines.spec.ts
Labels: automerge

#12653 fix(estate): tweak for rateofexchange calculations
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/Sections/estateAssets.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/utils.ts
Labels: automerge

#12656 feat(web): Add alert banner option to /starfatorg
  apps/web/layouts/main.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
Labels: automerge

#12662 fix(consultation-portal): KAM-1857: fix wording in statuses
  apps/consultation-portal/lib/shared.json
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
  apps/consultation-portal/screens/Case/components/AdviceList/AdviceList.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusText/CaseStatusText.tsx
  apps/consultation-portal/screens/Case/components/index.ts
Labels: automerge

#12665 fix(service-portal): Add back company settings
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/service-portal/information/src/module.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
Labels: automerge

#12668 fix(service-portal): Vehicles display values and unit display
  libs/service-portal/assets/src/screens/Lookup/Lookup.graphql
  libs/service-portal/assets/src/screens/Lookup/Lookup.tsx
Labels: automerge

#12667 fix(consultation-portal): KAM-1860: fix wording
  apps/consultation-portal/screens/Case/Case.json
Labels: automerge

#12664 feat(web): Change email for Sýslumenn service web form submissions
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#12671 fix(service-portal): display correct chargeType in xls/csv export
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
Labels: automerge

#12660 fix(web): Webreader not loading correctly
  apps/web/components/Webreader/Webreader.tsx
  apps/web/components/Webreader/index.ts
Labels: automerge

#12666 feat(web): Hotfix - Add option for alert banner on /starfatorg
  apps/web/layouts/main.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
Labels: automerge

#12669 feat(web): Load organization headers on server
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/GevTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HveTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/MannaudstorgTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RikissaksoknariTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SHHTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/index.ts
Labels: automerge

#12672 fix(service-portal): Hotfix - Vehicles, company settings, finance xsl
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/service-portal/assets/src/screens/Lookup/Lookup.graphql
  libs/service-portal/assets/src/screens/Lookup/Lookup.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/information/src/module.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
Labels: automerge

#12674 fix(consultation-portal): hotfix My subscriptions not showing up
  apps/consultation-portal/hooks/api/useFetchEmail.ts
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#12676 fix(consultation-portal): fix spelling and wording
  apps/consultation-portal/lib/shared.json
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/CaseDesktop.tsx
  apps/consultation-portal/screens/Case/CaseMobile.tsx
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
  apps/consultation-portal/types/interfaces.ts
Labels: automerge

#12678 fix(consultation-portal): KAM-1855: fixed location (#12650)
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
Labels: automerge

#12680 fix(consultation-portal): KAM-1860: fix wording (#12667)
  apps/consultation-portal/screens/Case/Case.json
Labels: automerge

#12679 fix(consultation-portal): KAM-1857: fix wording in statuses (#12662)
  apps/consultation-portal/lib/shared.json
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
  apps/consultation-portal/screens/Case/components/AdviceList/AdviceList.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusBox/CaseStatusBox.tsx
  apps/consultation-portal/screens/Case/components/CaseStatusText/CaseStatusText.tsx
  apps/consultation-portal/screens/Case/components/index.ts
Labels: automerge

#12596 feat(j-s): Expose heightened security option for police system cases
  apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/xrd-api/src/app/app.dto.ts
Labels: automerge

#12675 fix(web): Remove dynamic imports for headers
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/DigitalIcelandTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/GevTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/HveTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/RikissaksoknariTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SHHTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/TryggingastofnunTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/index.ts
Labels: automerge

#12687 test(j-s): Fix e2e test
  apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts
Labels: automerge

#12629 feat(j-s): Enable COA judges to reopen cases
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20231107164417-update-case.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealCompletedNotifications.spec.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/ReopenModal/ReopenModal.strings.ts
  apps/judicial-system/web/src/components/ReopenModal/ReopenModal.tsx
  apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.strings.ts
  apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/components/index.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.strings.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#12693 fix(user-profile): Reverting using formatted phone number in sms verification
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
Labels: automerge

#12694 fix(user-profile): Reverting using formatted phone number in sms verification
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
Labels: automerge

#12695 fix(user-profile): Parse phone number to find match in confirmSMS
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
Labels: automerge

#12696 fix(user-profile): Parse phone number to find match in confirmSMS
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
Labels: automerge

#12691 fix(consultation-portal): KAM-1865: changed launch date
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
Labels: automerge

#12699 fix(web): Add spacing between slice dropdown and first element
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
Labels: automerge

#12697 fix(consultation-portal): KAM-1865: changed launch date (#12691)
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
Labels: automerge

#12685 fix(island-ui): Added progress meter to action card
  libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
  libs/island-ui/core/src/lib/ProgressMeter/ProgressMeter.css.ts
  libs/island-ui/core/src/lib/ProgressMeter/ProgressMeter.tsx
Labels: automerge

#12700 fix(consultation-portal): KAM-1866: Search getting filter value once filters are loaded
  apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/hooks/useFrontPageFilters.ts
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/components/SearchAndFilter/SearchAndFilter.tsx
Labels: automerge

#12702 fix(consultation-portal): KAM-1866: Search getting filter value once …
  apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/hooks/useFrontPageFilters.ts
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/components/SearchAndFilter/SearchAndFilter.tsx
Labels: automerge

#12558 feat(old-age-pension): Check if applicant is eligible
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/dataProviders/index.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
  libs/clients/social-insurance-administration/src/clientConfig.yaml
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.module.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
Labels: automerge

#12614 feat(service-portal): vehicle new service
  libs/api/domains/vehicles/src/dto/getVehiclesForUserInput.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
  libs/api/domains/vehicles/src/utils/basicVehicleInformationMapper.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/Overview/Overview.graphql
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
  libs/service-portal/assets/src/screens/VehicleHistory/TabContent.tsx
  libs/service-portal/assets/src/screens/VehicleHistory/VehicleHistory.graphql
  libs/service-portal/assets/src/screens/VehicleHistory/VehicleHistory.tsx
  libs/service-portal/assets/src/utils/VehicleExcel.graphql
  libs/service-portal/assets/src/utils/downloadVehicleOwnedFile.ts
  libs/service-portal/assets/src/utils/vehicleOwnedMapper.ts
Labels: automerge

#12692 fix(service-portal): health fixes
  apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
  apps/service-portal/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/health/src/components/FootNote/helper.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/Medicine.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineLicence.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Medicine/components/DrugRow/DrugRow.tsx
  libs/service-portal/health/src/screens/Medicine/components/QuantityCounter/QuantityCounter.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
  libs/service-portal/health/src/screens/Payments/Payments.tsx
  libs/service-portal/health/src/screens/Payments/TabPanes/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/TabPanes/PaymentParticipation.tsx
Labels: automerge

#12607 feat(user-profile): System lookup endpoint
  apps/services/user-profile/src/app/v2/test/user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.controller.ts
  apps/services/user-profile/src/app/v2/user-profile.module.ts
  libs/auth/scopes/src/lib/userProfile.scope.ts
Labels: automerge

#12663 fix(air-discount): Fix filters on air discount
  libs/portals/admin/air-discount-scheme/src/screens/Overview/Overview.loader.ts
Labels: automerge

#12704 fix(ehic): DownloadPDF button
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/mappers/ehicCardMapper.ts
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#12651 feat(user-profile): Skip verification
  apps/services/user-profile/project.json
  apps/services/user-profile/src/app/v2/me-user-profile.controller.ts
  apps/services/user-profile/src/app/v2/test/me-create-verification.spec.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  apps/services/user-profile/test/setup.ts
  libs/auth-nest-tools/src/lib/auth.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/testing/fixtures/src/lib/currentUser.ts
Labels: automerge

#12705 fix(utlendingastofnun - citizenship): Add missing infra in application system
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#12690 fix(consultation-portal): KAM-1864: fixing failing tests
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
Labels: automerge

#12708 fix(parental-leave): change descriptions for uploads
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#12709 fix(service portal): health and pdf fixes
  apps/service-portal/src/components/ContentBreadcrumbs/ContentBreadcrumbs.tsx
  apps/service-portal/src/components/TabNavigation/TabNavigation.tsx
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/mappers/ehicCardMapper.ts
  libs/service-portal/health/src/components/FootNote/helper.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/Medicine.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicineLicence.tsx
  libs/service-portal/health/src/screens/Medicine/TabPanes/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Medicine/components/DrugRow/DrugRow.tsx
  libs/service-portal/health/src/screens/Medicine/components/QuantityCounter/QuantityCounter.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
  libs/service-portal/health/src/screens/Payments/Payments.tsx
  libs/service-portal/health/src/screens/Payments/TabPanes/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/TabPanes/PaymentParticipation.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#12707 fix(firearm-license): firearm license log
  apps/services/license-api/src/app/modules/license/license.service.ts
  libs/clients/license-client/src/lib/clients/firearm-license-client/services/firearmLicenseUpdateClient.service.ts
Labels: automerge

#12689 fix(web): Directorate of Immigration chat - authenticate instantly to prevent connection timeout
  apps/web/components/ChatPanel/WatsonChatPanel/directorateOfImmigrationChatUtils.ts
Labels: automerge

#12701 feat(web): Decrease manual page content width and add table of contents to top of manual chapter item accordions
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/screens/Layouts/SidebarLayout.tsx
  apps/web/screens/Manual/ManualChangelog.tsx
  apps/web/screens/Manual/ManualChapter.tsx
  apps/web/screens/Manual/components/ManualWrapper.tsx
  apps/web/screens/queries/Search.tsx
Labels: automerge

#12713 fix(consultation-portal): KAM-1868: Change launch date to 13th of Nov
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
Labels: automerge

#12714 fix(consultation-portal): KAM-1868: Change launch date to 13th of Nov…
  apps/consultation-portal/screens/Case/utils/shouldShowStakeholdersBox.ts
Labels: automerge

#12670 fix(j-s): Change email wording from Gögn to Krafa
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
Labels: automerge

#12716 fix(service-portal): download button
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#12719 fix(service-portal): Hotfix - download button
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#12724 chore(j-s): Hotfix
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#12659 feat(j-s): Log logins to event log
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.controller.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.module.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.service.ts
  libs/judicial-system/types/src/lib/eventLog.ts
Labels: automerge

#12688 chore(j-s): Stop making redundant calls to APIs
  apps/judicial-system/web/src/utils/hooks/useDeb/index.tsx
  apps/judicial-system/web/src/utils/hooks/useLawyers/useLawyers.ts
Labels: automerge

#12729 chore(delegation-api): Increase memory of delgation api
  apps/services/auth/delegation-api/infra/delegation-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#12731 fix(service-portal): adding id to checkbox
  libs/service-portal/assets/src/screens/VehicleHistory/VehicleHistory.tsx
Labels: automerge

#12733 fix(j-s): COA appeal result modified
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.strings.ts
  apps/judicial-system/web/src/components/RulingModifiedModal/RulingModifiedModal.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#12730 chore(delegation-api): Increase delegation api memory
  README.md
  apps/services/auth/delegation-api/infra/delegation-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#12732 fix(service-portal): health routing
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/service-portal/core/src/components/GoBack/GoBack.tsx
  libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx
  libs/service-portal/core/src/components/TabNavigation/SubTabItem.tsx
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.css.ts
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/screens/DynamicWrapper/DynamicWrapper.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/finance/src/utils/downloadFile.ts
  libs/service-portal/finance/src/utils/filesHreyfingar.ts
  libs/service-portal/finance/src/utils/simpleFilter.ts
  libs/service-portal/health/src/components/ExpiringTable/ExpiringExpandedTableRow.tsx
  libs/service-portal/health/src/components/ExpiringTable/ExpiringTable.tsx
  libs/service-portal/health/src/components/FootNote/FootNote.tsx
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
  libs/service-portal/health/src/components/TherapiesTabContent/TherapiesTabContent.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/NutritionTable.tsx
  libs/service-portal/health/src/screens/Dentists/BillsTable.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/Medicine.css.ts
  libs/service-portal/health/src/screens/Medicine/Medicine.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Medicine/constants.ts
  libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/screens/Payments/Payments.css.ts
  libs/service-portal/health/src/screens/Payments/Payments.tsx
  libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
  libs/service-portal/health/src/screens/Therapies/Therapies.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
Labels: automerge

#12738 feat(old-age-pension): Save the application on TR servers
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
  libs/clients/social-insurance-administration/src/clientConfig.yaml
Labels: automerge

#12737 fix(service-portal): cleanup finance
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/finance/src/lib/dto/getFinanceDocumentsList.input.ts
  libs/api/domains/finance/src/lib/models/annualStatusDocument.model.ts
  libs/api/domains/finance/src/lib/models/customerChargeType.model.ts
  libs/api/domains/finance/src/lib/models/customerChargeTypeItem.model.ts
  libs/api/domains/finance/src/lib/models/customerRecords.model.ts
  libs/api/domains/finance/src/lib/models/customerRecordsItem.model.ts
  libs/api/domains/finance/src/lib/models/customerTapsControl.model.ts
  libs/api/domains/finance/src/lib/models/debtStatus.model.ts
  libs/api/domains/finance/src/lib/models/documentsList.model.ts
  libs/api/domains/finance/src/lib/models/financeDocument.model.ts
  libs/api/mocks/src/domains/finance/store.ts
  libs/service-portal/finance/codegen.yml
  libs/service-portal/finance/project.json
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.graphql
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/DropdownExport/DropdownExport.tsx
  libs/service-portal/finance/src/components/FinanceDebtStatus/FinanceDebtStatus.tsx
  libs/service-portal/finance/src/components/FinanceIntro/index.tsx
  libs/service-portal/finance/src/components/FinanceScheduleDetailTable/FinanceScheduleDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTable.graphql
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTable.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRow.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRowCompressed.tsx
  libs/service-portal/finance/src/components/FinanceStatusDetailTable/FinanceStatusDetailTable.tsx
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.graphql
  libs/service-portal/finance/src/components/FinanceStatusTableRow/FinanceStatusTableRow.tsx
  libs/service-portal/finance/src/components/FinanceTransactionsDetail/FinanceTransactionsDetail.tsx
  libs/service-portal/finance/src/components/FinanceTransactionsTable/FinanceTransactionsTable.tsx
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.graphql
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.graphql
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.graphql
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/queries/getCustomerChargeType.ts
  libs/service-portal/graphql/src/lib/queries/getCustomerRecords.ts
Labels: automerge

#12743 fix(portals-admin-icelandic-names-registry): Fix name update mutation
  .github/CODEOWNERS
  libs/portals/admin/icelandic-names-registry/src/components/Editor/Editor.tsx
Labels: automerge

#12681 feat(signature-list-creation): New Application Collection - "Signature List Creation" & "Signature List Signing"
  .github/CODEOWNERS
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/signature-collection/README.md
  libs/application/templates/signature-collection/assets/Illustration.tsx
  libs/application/templates/signature-collection/signature-list-creation/.babelrc
  libs/application/templates/signature-collection/signature-list-creation/.eslintrc.json
  libs/application/templates/signature-collection/signature-list-creation/README.md
  libs/application/templates/signature-collection/signature-list-creation/jest.config.ts
  libs/application/templates/signature-collection/signature-list-creation/project.json
  libs/application/templates/signature-collection/signature-list-creation/src/fields/ListCreated/index.tsx
  libs/application/templates/signature-collection/signature-list-creation/src/fields/ListsInOverview/index.tsx
  libs/application/templates/signature-collection/signature-list-creation/src/fields/index.ts
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Done.ts
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-creation/src/index.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/CreateListTemplate.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/constants.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/dataSchema.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/utils.ts
  libs/application/templates/signature-collection/signature-list-creation/tsconfig.json
  libs/application/templates/signature-collection/signature-list-creation/tsconfig.lib.json
  libs/application/templates/signature-collection/signature-list-creation/tsconfig.spec.json
  libs/application/templates/signature-collection/signature-list-signing/.babelrc
  libs/application/templates/signature-collection/signature-list-signing/.eslintrc.json
  libs/application/templates/signature-collection/signature-list-signing/README.md
  libs/application/templates/signature-collection/signature-list-signing/jest.config.ts
  libs/application/templates/signature-collection/signature-list-signing/project.json
  libs/application/templates/signature-collection/signature-list-signing/src/fields/ListSigned/index.tsx
  libs/application/templates/signature-collection/signature-list-signing/src/fields/index.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Done.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Draft.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-signing/src/index.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/SignListTemplate.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/constants.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/dataSchema.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
  libs/application/templates/signature-collection/signature-list-signing/tsconfig.json
  libs/application/templates/signature-collection/signature-list-signing/tsconfig.lib.json
  libs/application/templates/signature-collection/signature-list-signing/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/institutionMapper.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge

#12745 fix(consultation-portal): Kam 1869 fix problems from qa
  apps/consultation-portal/components/Layout/components/Footer/Footer.tsx
  apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
  apps/consultation-portal/context/IsSsrMobileContext.tsx
  apps/consultation-portal/context/index.ts
  apps/consultation-portal/hooks/useIsMobile.ts
  apps/consultation-portal/hooks/useIsWindowSize.ts
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/screens/Error404/Error404.json
  apps/consultation-portal/screens/Home/Home.tsx
Labels: automerge

#12735 fix(inheritance-report): Inheritance report iteration2
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/forms/sections/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/business.ts
  libs/application/templates/inheritance-report/src/forms/sections/dataCollection.ts
  libs/application/templates/inheritance-report/src/forms/sections/debts.ts
  libs/application/templates/inheritance-report/src/forms/sections/deceased.ts
  libs/application/templates/inheritance-report/src/forms/sections/funeralCost.ts
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/InheritanceReportTemplate.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#12754 fix(service-portal): update link
  libs/service-portal/health/src/lib/messages.ts
Labels: automerge

#12755 fix(service-portal): wrong scope
  libs/service-portal/health/src/module.tsx
Labels: automerge

#12752 fix(estate): checkbox label tweak
  libs/application/templates/estate/src/forms/Overviews.ts
Labels: automerge

#12748 fix(consultation-portal): Kam 1869 fix problems from qa (#12745)
  apps/consultation-portal/components/Layout/components/Footer/Footer.tsx
  apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
  apps/consultation-portal/context/IsSsrMobileContext.tsx
  apps/consultation-portal/context/index.ts
  apps/consultation-portal/hooks/useIsMobile.ts
  apps/consultation-portal/hooks/useIsWindowSize.ts
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/screens/Error404/Error404.json
  apps/consultation-portal/screens/Home/Home.tsx
Labels: automerge

#12756 fix(service-portal): health updates
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/components/Layout/Layout.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/services/license-api/src/app/modules/license/license.service.ts
  libs/clients/license-client/src/lib/clients/firearm-license-client/services/firearmLicenseUpdateClient.service.ts
  libs/portals/admin/air-discount-scheme/src/screens/Overview/Overview.loader.ts
  libs/service-portal/core/src/components/GoBack/GoBack.tsx
  libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx
  libs/service-portal/core/src/components/TabNavigation/SubTabItem.tsx
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.css.ts
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/screens/DynamicWrapper/DynamicWrapper.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/finance/src/utils/downloadFile.ts
  libs/service-portal/finance/src/utils/filesHreyfingar.ts
  libs/service-portal/finance/src/utils/simpleFilter.ts
  libs/service-portal/health/src/components/ExpiringTable/ExpiringExpandedTableRow.tsx
  libs/service-portal/health/src/components/ExpiringTable/ExpiringTable.tsx
  libs/service-portal/health/src/components/FootNote/FootNote.tsx
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
  libs/service-portal/health/src/components/TherapiesTabContent/TherapiesTabContent.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/NutritionTable.tsx
  libs/service-portal/health/src/screens/Dentists/BillsTable.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/Medicine.css.ts
  libs/service-portal/health/src/screens/Medicine/Medicine.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Medicine/components/DrugRow/DrugRow.tsx
  libs/service-portal/health/src/screens/Medicine/constants.ts
  libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/screens/Payments/Payments.css.ts
  libs/service-portal/health/src/screens/Payments/Payments.tsx
  libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
  libs/service-portal/health/src/screens/Therapies/Therapies.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
Labels: automerge

#12593 feat(service-portal): Finance service v2 client
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  libs/api/domains/finance/src/lib/api-domains-finance.module.ts
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/api/domains/finance/src/lib/dto/getChargeItemSubjectsByYear.input.ts
  libs/api/domains/finance/src/lib/dto/getChargeTypePeriodSubject.input.ts
  libs/api/domains/finance/src/lib/dto/getChargeTypesByYear.input.ts
  libs/api/domains/finance/src/lib/dto/getChargeTypesDetailsByYear.input.ts
  libs/api/domains/finance/src/lib/models/assessmentYears.model.ts
  libs/api/domains/finance/src/lib/models/chargeItemSubjectsByYear.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypeDetails.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypePeriodSubject.model.ts
  libs/api/domains/finance/src/lib/models/chargeTypesByYear.model.ts
  libs/clients/finance-v2/.eslintrc.json
  libs/clients/finance-v2/README.md
  libs/clients/finance-v2/jest.config.ts
  libs/clients/finance-v2/project.json
  libs/clients/finance-v2/src/clientConfig.json
  libs/clients/finance-v2/src/index.ts
  libs/clients/finance-v2/src/lib/financeV2.config.ts
  libs/clients/finance-v2/src/lib/financeV2.module.ts
  libs/clients/finance-v2/src/lib/financeV2.provider.ts
  libs/clients/finance-v2/src/lib/financeV2.service.ts
  libs/clients/finance-v2/tsconfig.json
  libs/clients/finance-v2/tsconfig.lib.json
  libs/clients/finance-v2/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#12760 fix(consultation-portal): Kam 1871 font is not loading using fallback font
  apps/consultation-portal/components/AppLayout/AppLayout.tsx
  apps/consultation-portal/components/Layout/components/SEO/SEO.tsx
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/pages/_document.tsx
  apps/consultation-portal/public/android-chrome-192x192.png
  apps/consultation-portal/public/android-chrome-512x512.png
  apps/consultation-portal/public/apple-touch-icon.png
  apps/consultation-portal/public/favicon-16x16.png
  apps/consultation-portal/public/favicon-32x32.png
  apps/consultation-portal/public/favicon.ico
  apps/consultation-portal/public/fonts/ibm-plex/OFL.txt
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-500.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-500.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.woff2
  apps/consultation-portal/public/site.webmanifest
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
  apps/consultation-portal/screens/Home/components/HeroBanner/components/StatisticBox/StatisticBox.tsx
Labels: automerge

#12759 fix(application-driving-license): Add phone field explicitly.
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#12762 fix(service-portal): always show nav in Therapies
  libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
Labels: automerge

#12774 fix(service-portal): Add xroad path for finance v2 client
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#12776 fix(application-driving-license): Add phone field explicitly. (#12759)
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#12777 fix(service-portal): health therapies nav
  libs/service-portal/health/src/screens/Therapies/TherapiesOccupational.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesPhysical.tsx
  libs/service-portal/health/src/screens/Therapies/TherapiesSpeech.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
Labels: automerge

#12775 fix(service-portal): Don't render button element inside anchors
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
  libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
  libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/UrlDocment.tsx
  libs/service-portal/education/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/FormButton.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#12778 fix(consultation-portal): Kam 1871 font is not loading using fallback…
  apps/consultation-portal/components/AppLayout/AppLayout.tsx
  apps/consultation-portal/components/Layout/components/SEO/SEO.tsx
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/pages/_document.tsx
  apps/consultation-portal/public/android-chrome-192x192.png
  apps/consultation-portal/public/android-chrome-512x512.png
  apps/consultation-portal/public/apple-touch-icon.png
  apps/consultation-portal/public/favicon-16x16.png
  apps/consultation-portal/public/favicon-32x32.png
  apps/consultation-portal/public/favicon.ico
  apps/consultation-portal/public/fonts/ibm-plex/OFL.txt
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-300.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-500.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-500.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-600.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-italic.woff2
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.eot
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.svg
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.ttf
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.woff
  apps/consultation-portal/public/fonts/ibm-plex/ibm-plex-sans-v7-latin-regular.woff2
  apps/consultation-portal/public/site.webmanifest
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
  apps/consultation-portal/screens/Home/components/HeroBanner/components/StatisticBox/StatisticBox.tsx
Labels: automerge

#12757 feat(old-age-pension): Make sure additionalDocumentsRequired don't get sent twice to TR when requesting more documents
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#12768 fix(search-indexer): Prune inline embedded entry fields
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#12771 feat(web): Store profession dropdown filter value in query param for master licences
  apps/web/components/connected/syslumenn/TableLists/MasterList/MasterList.tsx
Labels: automerge

#12779 fix(service-portal): avoid double tabbing on button links
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
  libs/service-portal/core/src/components/GoBack/GoBack.tsx
  libs/service-portal/core/src/components/LinkButton/LinkButton.tsx
  libs/service-portal/core/src/screens/NoDataScreen/NoDataScreen.tsx
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/education/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
Labels: automerge

#12744 feat(web): Change default header props
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/DefaultHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/DefaultTheme/DefaultHeader.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/models/organizationTheme.model.ts
Labels: automerge

#12770 fix(island-ui): Update PDF Annotation layer to support links in pdf viewer
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.css.ts
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
Labels: automerge, deploy-feature

#12785 fix(service-portal): tweak heilsa urls
  libs/service-portal/health/src/lib/paths.ts
Labels: automerge

#12782 feat(web): Add chat widget to Grindavík project page
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/WatsonChatPanel/index.ts
  apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
  apps/web/components/ChatPanel/types.ts
  apps/web/screens/Project/components/ProjectChatPanel/ProjectChatPanel.tsx
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
  apps/web/screens/queries/WatsonAssistantChat.ts
Labels: automerge

#12784 fix(service-portal): tweak heilsa urls
  libs/service-portal/health/src/lib/paths.ts
Labels: automerge

#12780 fix(service-portal): Document rsk link handler
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
  libs/service-portal/documents/src/lib/types.ts
  libs/service-portal/documents/src/utils/customUrlHandler.ts
Labels: automerge

#12781 fix(service-portal): Update link styling for Action Bar linkbutton
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.css.ts
Labels: automerge

#12787 feat(web): Add header for Grindavík project page
  apps/web/components/Project/Header/GrindavikProjectHeader.css.ts
  apps/web/components/Project/Header/GrindavikProjectHeader.tsx
  apps/web/components/Project/index.ts
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/components/ProjectHeader/ProjectHeader.tsx
Labels: automerge

#12791 fix(web): Use light theme for grindavik project page header
  apps/web/screens/Project/utils.tsx
Labels: automerge

#12793 fix(transport authority): Add missing extradata to payment state
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#12792 fix(transport authority): Add missing extradata to payment state
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#12795 fix(service-portal): Document handling in inbox. RSK link and annotation layer.
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.css.ts
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
  libs/service-portal/documents/src/lib/types.ts
  libs/service-portal/documents/src/utils/customUrlHandler.ts
Labels: automerge

#12772 fix(service-portal): only fetch the organization we need
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/portals/core/src/types/portalCore.ts
  libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/assets/src/screens/Lookup/Lookup.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
  libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/assets/src/screens/VehicleHistory/VehicleHistory.tsx
  libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/assets/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
  libs/service-portal/core/src/components/FootNote/FootNote.tsx
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/screens/NavigationOverviewScreen/NavigationOverviewScreen.css.ts
  libs/service-portal/core/src/screens/NavigationOverviewScreen/NavigationOverviewScreen.tsx
  libs/service-portal/core/src/utils/constants.ts
  libs/service-portal/education-career/src/screens/EducationCareer/EducationCareer.tsx
  libs/service-portal/education-degree/src/screens/EducationDegree/EducationDegree.tsx
  libs/service-portal/education-license/src/screens/EducationLicense/EducationLicense.tsx
  libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/EducationStudentAssessment.tsx
  libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx
  libs/service-portal/education/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
  libs/service-portal/education/src/screens/EducationGraduation/EducationGraduation.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/lib/navigation.ts
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/graphql/src/hooks/organizations/useOrganization.ts
  libs/service-portal/graphql/src/hooks/organizations/useOrganizations.ts
  libs/service-portal/graphql/src/index.ts
  libs/service-portal/graphql/src/lib/queries/getOrganizations.ts
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
  libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/Company/CompanyInfo.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/service-portal/information/src/screens/UserProfile/UserProfile.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
  libs/service-portal/occupational-licenses/src/lib/messages.ts
  libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
  libs/shared/constants/src/lib/organizationSlug.ts
Labels: automerge

#12734 feat(user-profile): Redirect email and phone changes to IDS flow
  libs/auth/react/src/lib/auth/AuthContext.tsx
  libs/auth/react/src/lib/auth/AuthProvider.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/ReadOnlyWithLinks.css.ts
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/ReadOnlyWithLinks.tsx
  libs/service-portal/information/src/lib/messages.ts
Labels: automerge

#12739 fix(j-s): Hide case resent explanation
  apps/judicial-system/api/src/app/modules/case/interceptors/limitedAccessCase.interceptor.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/limitedAccessCase.transformer.ts
  apps/judicial-system/api/src/app/modules/case/limitedAccessCase.resolver.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#12790 chore(j-s): XRD API Logging
  apps/judicial-system/xrd-api/src/app/app.controller.ts
Labels: automerge

#12789 fix(j-s): Format Reopen Appeal Event
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
Labels: automerge
