Repository island-is/island.is, pull requests merged in 2023-05, with the labels that each got.

#10970 fix(portals-admin-ids-admin): Modal body scroll
  libs/portals/admin/ids-admin/src/components/Modal/Modal.tsx
Labels: automerge

#10976 fix(delegations): iOS scroll bug
  libs/portals/admin/ids-admin/src/components/Modal/Modal.tsx
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.css.ts
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx
Labels: automerge, deploy-feature

#10973 fix(j-s): Fixing spacing in alert banner
  apps/judicial-system/web/src/components/AlertBanner/index.tsx
Labels: automerge

#10959 chore(j-s): Austurland - Court Client
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#10972 feat(j-s): Court of Appeal case files Appeal ruling added
  apps/judicial-system/backend/migrations/20230428104552-update-case-file.js
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#10978 fix(clients-driving-license): Correct mistaken purpose of user id in client
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/v5/index.ts
Labels: automerge

#10982 fix(clients-driving-license): Correct mistaken purpose of userid
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/v5/index.ts
Labels: automerge

#10927 feat(portals-admin-ids-admin): Adding client secrets
  apps/services/auth/admin-api/src/app/v2/clients/clients.module.ts
  apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.module.ts
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.service.ts
  apps/services/auth/admin-api/src/app/v2/secrets/dto/client-secret.dto.ts
  apps/services/auth/admin-api/src/app/v2/secrets/me-client-secrets.controller.ts
  libs/api/domains/auth-admin/src/lib/auth-admin.module.ts
  libs/api/domains/auth-admin/src/lib/client/client-environment.resolver.ts
  libs/api/domains/auth-admin/src/lib/client/client-secret.loader.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/client-secret.input.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-environment.model.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-secret.model.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/clients.module.ts
  libs/clients/auth/admin-api/src/index.ts
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/components/Client/Client.graphql
  libs/portals/admin/ids-admin/src/components/Client/Client.loader.ts
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/Translations.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditApplication.action.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx
  libs/portals/admin/ids-admin/src/shared/context/ClientContext.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#10489 feat(service-portal): Settings options for paper mail requirement
  libs/api/domains/documents/src/lib/document.resolver.ts
  libs/api/domains/documents/src/lib/document.service.ts
  libs/api/domains/documents/src/lib/dto/postRequestPaperInput.ts
  libs/api/domains/documents/src/lib/models/paperMail.model.ts
  libs/clients/documents/src/lib/documentClient.ts
  libs/clients/documents/src/lib/models/PaperMailRes.ts
  libs/clients/documents/src/lib/models/RequestPaperDTO.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/PaperMail.tsx
  libs/service-portal/settings/personal-information/src/lib/messages.ts
Labels: automerge, deploy-feature

#10985 fix(application-system): ApplicationCard scaling
  libs/application/ui-components/src/components/ApplicationCard/ApplicationCard.tsx
Labels: automerge

#10648 fix: Better esbuild node_modules copy logic
  .yarn/patches/@anatine-esbuildnx-npm-0.2.0-b2ba626748.patch
  package.json
  yarn.lock
Labels: automerge

#10991 fix(clients-driving-license): Possible case sensitivity fix to infra
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
Labels: automerge

#10993 fix(application-driving-learners): Update texts
  libs/application/templates/driving-learners-permit/project.json
  libs/application/templates/driving-learners-permit/src/forms/done.ts
  libs/application/templates/driving-learners-permit/src/forms/form/index.ts
  libs/application/templates/driving-learners-permit/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#10989 fix(j-s): Removing double lines in pdf list for prosecutor
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
Labels: automerge

#10986 fix(j-s): Adding toaster when case can not be opened from case list
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
Labels: automerge

#10987 fix(j-s): Adding event types for appeal transition
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
Labels: automerge

#10990 fix(j-s): Fixing choice of words in police case files
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
Labels: automerge

#10994 fix(application-driving-learners-permit): Update texts and infra
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/application/templates/driving-learners-permit/project.json
  libs/application/templates/driving-learners-permit/src/forms/done.ts
  libs/application/templates/driving-learners-permit/src/forms/form/index.ts
  libs/application/templates/driving-learners-permit/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
Labels: automerge

#10988 chore(j-s): Rewrite Filters
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.archiveFilter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseRead.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseWrite.guard.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#10951 feat(service-portal): Consent UI
  .github/CODEOWNERS
  apps/service-portal/src/lib/masterNavigation.ts
  apps/service-portal/src/lib/modules.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/consent/.babelrc
  libs/service-portal/consent/.eslintrc.json
  libs/service-portal/consent/README.md
  libs/service-portal/consent/codegen.yml
  libs/service-portal/consent/jest.config.js
  libs/service-portal/consent/project.json
  libs/service-portal/consent/src/index.ts
  libs/service-portal/consent/src/lib/messages.ts
  libs/service-portal/consent/src/lib/navigation.ts
  libs/service-portal/consent/src/lib/paths.ts
  libs/service-portal/consent/src/module.tsx
  libs/service-portal/consent/src/screens/Consent/Consent.css.ts
  libs/service-portal/consent/src/screens/Consent/Consent.graphql
  libs/service-portal/consent/src/screens/Consent/Consent.tsx
  libs/service-portal/consent/src/screens/Consent/types.ts
  libs/service-portal/consent/tsconfig.json
  libs/service-portal/consent/tsconfig.lib.json
  libs/service-portal/consent/tsconfig.spec.json
  libs/service-portal/core/src/lib/messages.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#10998 fix(consultation-portal): removed links from footer
  apps/consultation-portal/components/Footer/Footer.css.ts
  apps/consultation-portal/components/Footer/Footer.tsx
Labels: automerge

#11001 fix(consultation-portal): endash in date instead of emdash
  apps/consultation-portal/utils/helpers/dateFormatter.ts
Labels: automerge

#10999 fix(consultation-portal): backend download url fix
  apps/consultation-portal/lib/environment.ts
Labels: automerge

#11006 fix(consultation-portal): blowout icon is now add instead of open
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#11003 fix(consultation-portal): fixed breadcrumbs
  apps/consultation-portal/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
  apps/consultation-portal/pages/um/index.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#11002 feat(operating-license): submit debt status ad pdf
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/types/attachments.ts
Labels: automerge

#11012 feat(regulations): Add search option endpoint for regulations
  libs/api/domains/regulations/src/lib/api-domains-regulations.resolver.ts
  libs/clients/regulations/src/lib/regulations.service.ts
  libs/portals/admin/regulations-admin/src/components/impacts/ImpactAmendingSelection.tsx
  libs/portals/admin/regulations-admin/src/utils/dataHooks.ts
Labels: automerge

#11007 fix(j-s): Updating text on indictment when checkbox is marked
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
Labels: automerge

#11009 refactor(j-s): Rename graphql queries and mutations
  apps/judicial-system/web-e2e-regression/src/integration/Court/RestrictionCases/confirmation.spec.ts
  apps/judicial-system/web-e2e-regression/src/integration/Prosecutor/Indictments/processing.spec.ts
  apps/judicial-system/web-e2e-regression/src/integration/Prosecutor/RestrictionCases/hearingArrangements.spec.ts
  apps/judicial-system/web-e2e-regression/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e-regression/src/utils/index.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/Indictments/prosecutorAndDefender.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/ProsecutorSelection/prosecutorSelectionUsersGql.ts
  apps/judicial-system/web/src/components/SigningModal/SigningModal.spec.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
  apps/judicial-system/web/src/components/SigningModal/requestRulingSignatureGql.ts
  apps/judicial-system/web/src/components/UserProvider/UserProvider.spec.tsx
  apps/judicial-system/web/src/components/UserProvider/UserProvider.tsx
  apps/judicial-system/web/src/components/UserProvider/gql.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/courtRecordSignatureConfirmationGql.ts
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/gql.ts
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/createDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/deleteDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/updateDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/gql.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/deleteIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/gql.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/mutations.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
Labels: automerge

#10872 feat(web): Explicit og:image field added to anchor page
  apps/web/screens/LifeEvent/LifeEvent.tsx
  apps/web/screens/queries/LifeEvents.tsx
  libs/cms/src/lib/models/lifeEventPage.model.ts
Labels: automerge

#11013 feat(portals-shared-modules-delegations): Drawer modal
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.css.ts
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessConfirmModal.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessDeleteModal/AccessDeleteModal.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationIncomingModal/DelegationIncomingModal.tsx
  libs/portals/shared-modules/delegations/src/lib/messages.ts
  package.json
  yarn.lock
Labels: automerge

#11010 feat(search-toolkit): Contentful logging
  libs/api/domains/content-search/src/lib/contentSearch.resolver.ts
  libs/cms/src/lib/contentful.repository.ts
Labels: automerge

#10971 fix(estate): updating estate members look
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/externalDataFields/estateMembersFields.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
Labels: automerge

#10877 chore(e2e-application-systems): Acceptance tests for application system
  apps/system-e2e/src/support/application.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/criminal-record.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/data-protection-complaint.spec.ts
  libs/application/templates/data-protection-complaint/src/lib/messages/complaint.ts
  tsconfig.base.json
Labels: automerge

#10923 fix(operating-license-template): add court bankruptcy to submit
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/types/application.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/utils.ts
Labels: automerge

#11022 fix(transfer of vehicle ownership): Handle if buyer is also seller's co-owner
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/hasReviewerApproved.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/hasReviewerApproved.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/hasReviewerApproved.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/index.ts
Labels: automerge

#11025 feat(consulation-portal): add nr of advices
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#11018 fix(estate): Adding screen - Erfðaskrá og Kaupmáli
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#11026 feat(consultation-portal): add case closed card
  apps/consultation-portal/components/CaseStatusCard/CaseStatusCard.tsx
Labels: automerge

#11027 feat(consultation-portal): move advice count to top of case page
  apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#11024 fix(userProfileApi-template-module): Allow mock on dev
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/user-profile-api.ts
Labels: automerge

#11032 fix(estate): adding new screen in Einkaskipti and validation improvement
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#11029 fix(consultation-portal): move documents box card left
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#10967 feat(j-s): Statement Files to Court
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/update.spec.ts
Labels: automerge

#10995 chore(j-s): Throttle Case Files PDF Generation
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
Labels: automerge

#11037 feat(consultation-portal): add dates to timeline
  apps/consultation-portal/components/CaseTimeline/CaseTimeline.tsx
  apps/consultation-portal/utils/helpers/dateFormatter.ts
Labels: automerge

#11034 fix(consultation-portal): Fix wording in hero banner
  apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
  apps/consultation-portal/components/StatisticBox/StatisticBox.tsx
Labels: automerge

#11015 chore(applications): Applicant Information Props
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/applicantInformationSection.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/data-protection-complaint/src/lib/dataSchema.ts
  libs/application/templates/general-fishing-license/src/forms/GeneralFishingLicenseForm/applicantInformationSection.ts
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/health-insurance/src/lib/dataSchema.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/dataSchema.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationMultiField.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationSchema.ts
  libs/application/ui-forms/src/lib/applicantInformationMultiField/types.ts
Labels: automerge

#11038 feat(passport-application): delete charge in 7 days if parentb does not approve
  libs/application/templates/passport/src/lib/PassportTemplate.ts
Labels: automerge

#11041 feat(consultation-portal): blowout on umbodsbox
  apps/consultation-portal/components/Advices/Advices.tsx
  apps/consultation-portal/components/Card/SimpleCardSkeleton.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/components/AdviceCTA.tsx
  apps/consultation-portal/screens/Case/components/Stakeholders.css.ts
  apps/consultation-portal/screens/Case/components/Stakeholders.tsx
Labels: automerge

#9393 feat(service-portal): Add a couple of smoke tests
  .eslintrc.json
  apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financial-payment-application.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financials.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/information.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/miscellaneous.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/service-portal.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-license.spec.ts
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
  libs/service-portal/core/src/components/ExpandableTable/Row.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTable.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRow.tsx
  libs/service-portal/finance/src/components/FinanceScheduleTable/FinanceScheduleTableRowCompressed.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/licenses/src/components/PassportLicense/PassportLicense.tsx
  libs/service-portal/licenses/src/components/SingleLicenseCard/SingleLicenseCard.tsx
  libs/service-portal/vehicles/src/components/VehicleCard.tsx
  libs/service-portal/vehicles/src/lib/messages.ts
  tsconfig.base.json
Labels: automerge

#11011 feat(auth-admin-api): Client create scope endpoint
  SUMMARY.md
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/api/domains/auth-admin/src/lib/auth-admin.module.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-environment.model.ts
  libs/api/domains/auth-admin/src/lib/scope/dto/create-scope.input.ts
  libs/api/domains/auth-admin/src/lib/scope/dto/create-scope.response.ts
  libs/api/domains/auth-admin/src/lib/scope/models/scope-environment.model.ts
  libs/api/domains/auth-admin/src/lib/scope/models/scope.model.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.resolver.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.service.spec.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.service.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/clients.module.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth-api-lib/src/lib/resources/admin/dto/client-create-scope.dto.ts
  libs/auth/shared/.babelrc
  libs/auth/shared/.eslintrc.json
  libs/auth/shared/README.md
  libs/auth/shared/jest.config.js
  libs/auth/shared/package.json
  libs/auth/shared/project.json
  libs/auth/shared/src/index.ts
  libs/auth/shared/src/lib/utils/validateClientId.spec.ts
  libs/auth/shared/src/lib/utils/validateClientId.ts
  libs/auth/shared/tsconfig.json
  libs/auth/shared/tsconfig.lib.json
  libs/auth/shared/tsconfig.spec.json
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.spec.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#11030 feat(web): Update directorate of immigration service web header
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/Utlendingastofnun/Utlendingastofnun.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Utlendingastofnun/Utlendingastofnun.tsx
  apps/web/components/ServiceWeb/config.ts
Labels: automerge

#11036 feat(web): Send to different emails depending on selected category on service web
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#10851 feat(contentful-apps): Display single reference entry card for non-admin users
  apps/contentful-apps/pages/fields/admin-only-single-reference-field.tsx
Labels: automerge

#10878 fix(web): Remove !important css rule from Rikislogmadur header styles
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurHeader.tsx
Labels: automerge

#11020 feat(web): Update Fjarsyslan footer visuals
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsFooter.tsx
Labels: automerge

#11044 fix(passport-application): minor param fix
  libs/application/templates/passport/src/dataProviders/index.ts
Labels: automerge

#11042 fix(delegations & ids-admin): Modal fixes
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/Permissions.tsx
  libs/portals/admin/ids-admin/src/components/Modal/Modal.css.ts
  libs/portals/admin/ids-admin/src/components/Modal/Modal.tsx
  libs/portals/admin/ids-admin/src/components/ShadowBox/ShadowBox.css.ts
  libs/portals/admin/ids-admin/src/components/ShadowBox/ShadowBox.tsx
  libs/portals/admin/ids-admin/src/components/forms/AddPermissions/AddPermissions.tsx
  libs/portals/admin/ids-admin/src/components/forms/AddPermissions/useDynamicShadow.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditApplication.action.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/shared/context/ClientContext.ts
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.css.ts
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessConfirmModal.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessDeleteModal/AccessDeleteModal.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationIncomingModal/DelegationIncomingModal.tsx
  libs/portals/shared-modules/delegations/src/lib/messages.ts
  package.json
  yarn.lock
Labels: automerge

#11046 fix(health-insurance): Fix health insurance prerequisite check
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
  libs/application/templates/health-insurance/src/healthInsuranceUtils.ts
Labels: automerge

#11047 fix(consultation-portal): add 1 day to process ends
  apps/consultation-portal/utils/helpers/dateFormatter.ts
Labels: automerge

#11048 fix(health-inurance): Fix prerequisite check for insurance
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
  libs/application/templates/health-insurance/src/healthInsuranceUtils.ts
Labels: automerge

#11040 chore(j-s): Blocks FMST from Changing Valid to Date
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#11053 fix(consultation-portal): Kam 1175 filter in frontpage mobile defaults to no component
  apps/consultation-portal/components/DebouncedSearch/DebouncedSearch.tsx
  apps/consultation-portal/components/DropdownSort/DropdownSort.tsx
  apps/consultation-portal/components/Filter/Filter.tsx
  apps/consultation-portal/components/Filter/MobileFilter.tsx
  apps/consultation-portal/components/Filterbox/Filterbox.tsx
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/components/Pagination/Pagination.css.ts
  apps/consultation-portal/components/Pagination/Pagination.tsx
  apps/consultation-portal/components/SearchAndFilter/SearchAndFilter.tsx
  apps/consultation-portal/components/SearchAndSort/SearchAndSort.css.ts
  apps/consultation-portal/components/SearchAndSort/SearchAndSort.tsx
  apps/consultation-portal/components/SearchAndSort/SearchAndSortPartialData.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/consts/consts.ts
  apps/consultation-portal/utils/helpers/adviceFilters/getDefaultFilters.ts
  apps/consultation-portal/utils/helpers/adviceFilters/useAdviceFilters.ts
  apps/consultation-portal/utils/helpers/api/usePostSubscription.ts
  apps/consultation-portal/utils/helpers/debounce.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/getDefaultFilters.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/getFilteredItemsOrAll.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/getInitFilterValues.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/getInitialFilters.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/index.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/useFrontPageFilters.ts
  apps/consultation-portal/utils/helpers/index.ts
  apps/consultation-portal/utils/helpers/localStorage/getItem.ts
  apps/consultation-portal/utils/helpers/localStorage/index.ts
  apps/consultation-portal/utils/helpers/localStorage/setItem.ts
  apps/consultation-portal/utils/helpers/subscriptions/initSubscriptions.ts
  apps/consultation-portal/utils/helpers/useDebounce.ts
  apps/consultation-portal/utils/helpers/useFetchCases.ts
  apps/consultation-portal/utils/helpers/useIsMobile.ts
Labels: automerge

#11056 fix(applications): Health insurance 412 response to 500
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
Labels: automerge

#11059 fix(consultation-portal): my subscriptions does not go to login when logged out
  apps/consultation-portal/graphql/errorLink.ts
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/utils/helpers/adviceFilters/useAdviceFilters.ts
  apps/consultation-portal/utils/helpers/useFetchAdvices.ts
Labels: automerge

#11039 refactor(j-s): Appeals Court Access
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseRead.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseWrite.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#11063 chore(qa): Attempting to remove some flakiness in basic web tests
  apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/search.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts
Labels: automerge

#11066 fix(operating-license-application): validation on repeater
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/operating-license/src/lib/dataSchema.ts
Labels: automerge

#11000 feat(web): Track different "domains" in plausible
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
  apps/web/constants/index.ts
  apps/web/hooks/index.ts
  apps/web/hooks/usePlausiblePageview.ts
  apps/web/pages/_document.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/LifeEvent/LifeEvent.tsx
  apps/web/screens/queries/Article.ts
  apps/web/screens/queries/Organization.tsx
  apps/web/screens/queries/PublishedMaterial.ts
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organization.model.ts
Labels: automerge

#11055 feat(island-ui): Add destructive variant to <ActionCard> and center CTA button.
  libs/island-ui/core/src/lib/ActionCard/ActionCard.stories.tsx
  libs/island-ui/core/src/lib/ActionCard/ActionCard.tsx
Labels: automerge

#11049 feat(application-system): Events used as log markers for application history
  apps/application-system/api/migrations/20230504150905-history-add-exit-event.js
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  libs/application/api/history/src/lib/history.model.ts
  libs/application/api/history/src/lib/history.service.ts
  libs/application/api/history/src/lib/historyBuilder.ts
  libs/application/core/README.md
  libs/application/core/src/lib/ApplicationTemplateHelper.ts
  libs/application/core/src/lib/messages.ts
  libs/application/templates/data-protection-complaint/src/lib/DataProtectionComplaintTemplate.ts
  libs/application/templates/reference-template/src/lib/ReferenceApplicationTemplate.ts
  libs/application/types/src/lib/StateMachine.ts
Labels: automerge

#11050 feat(j-s): Court of appeal overview site differentiates case types
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
Labels: automerge

#11070 fix: moved non-secret to env
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge, deploy-feature, high priority, merge.priority_merge_label

#11071 fix(applications): Fix application overview pagination
  libs/application/ui-components/src/components/ApplicationList/ApplicationList.tsx
Labels: automerge

#11077 fix(infra): Fixing parsing of `with-mocks` parameter when feature-generating values file
  infra/src/feature-env.ts
Labels: automerge, high priority, merge.priority_merge_label

#10931 docs: postholf checklist translation
  SUMMARY.md
  handbook/technical-overview/postholf/postholf-00-security-checklist.md
Labels: automerge

#11079 fix(estate): updates in Eignalaus skipti
  libs/application/templates/estate/src/forms/DivisionOfEstate/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/externalDataFields/propertiesFields.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/forms/sharedSections/testamentInfo.ts
Labels: automerge

#10848 fix(system-e2e): XRoad wire-mock works in K8s too
  apps/system-e2e/src/support/wire-mocks.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/setup-xroad.mocks.ts
Labels: automerge

#11074 chore(qa): Attempting to remove some flakiness in basic web tests
  apps/system-e2e/src/tests/islandis/service-portal/smoke/information.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
Labels: automerge

#11082 fix(okutimar): registrations visibility tweak
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
Labels: automerge

#11084 build: fix regression on postgres CREATE EXTENSION, should check IF EXISTS
  infra/scripts/container-scripts/create-db.sh
Labels: automerge, high priority, merge.priority_merge_label

#11045 refactor(j-s): GraphQL refactor
  apps/judicial-system/codegen.yml
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/SigningModal/RulingSignature.graphql
  apps/judicial-system/web/src/components/SigningModal/SigningModal.spec.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
  apps/judicial-system/web/src/components/SigningModal/requestRulingSignatureGql.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/CourtRecordSignature.graphql
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/courtRecordSignatureConfirmationGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  apps/judicial-system/web/src/utils/mutations.ts
Labels: automerge

#11067 fix(j-s): Adding timestamp and category to appeal case files list in court of appeal overview
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#11085 fix(service-portal): Consent UI polish
  libs/service-portal/consent/src/screens/Consent/Consent.tsx
  libs/service-portal/consent/src/screens/Consent/types.ts
Labels: automerge

#11064 fix(consultation-portal): filename cannot be more than 100 characters
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/utils/consts/consts.ts
  apps/consultation-portal/utils/helpers/index.ts
  apps/consultation-portal/utils/helpers/renderDocFileName.ts
  apps/consultation-portal/utils/helpers/usePostAdvice.ts
Labels: automerge

#11075 fix(consultation-portal): safari fix?
  apps/consultation-portal/utils/helpers/useLogin.ts
Labels: automerge

#11091 feat(consultation-portal): additionalDocuments in nestjs
  apps/consultation-portal/graphql/queries.graphql.ts
  libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#11052 feat(j-s): Store Case Files Record in AWS S3
  apps/judicial-system/README.md
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archiveCaseFilesRecord.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archiveCaseFilesRecordGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToCourt.spec.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#11069 fix(j-s): Updating indictment pdf text as requested
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
Labels: automerge

#11051 fix(j-s): Fix Appeal Court Folder
  apps/judicial-system/backend/migrations/20230428151155-update-notification.js
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#11065 feat(j-s): Added appeal info to COA appeal overview screen
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
Labels: automerge

#11094 fix(consultation-portal): subscription refactor
  apps/consultation-portal/components/Card/ChosenSubscriptionCard.tsx
  apps/consultation-portal/components/Card/components/CardGridContainer.tsx
  apps/consultation-portal/components/Card/components/SimpleCardSkeleton.tsx
  apps/consultation-portal/components/Card/index.ts
  apps/consultation-portal/components/ChosenSubscriptions/ChosenSubscriptions.tsx
  apps/consultation-portal/components/SubscriptionChoices/SubscriptionChoices.tsx
  apps/consultation-portal/components/Table/SubscriptionTableItem.tsx
  apps/consultation-portal/types/enums.ts
Labels: automerge

#11089 fix(estate): bugfixing
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#11102 fix: added length constraints to LAST_GOOD_BUILD_DOCKER_TAG while retagging
  scripts/ci/_retag.sh
Labels: automerge

#11097 fix(application-driving-learners-permit): Validation and license fallbacks
  charts/islandis/values.dev.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
Labels: automerge

#11116 fix(driving-learners-permit): License and registrations tweak
  charts/islandis/values.dev.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
Labels: automerge

#11109 fix(estate): marketvalue requirements
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils.ts
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#11110 fix(j-s): Fix legal arguments text
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#11105 fix(j-s): Validate and send updated ruling info to server
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#11090 fix(j-s): Removing unnecessary tool tip
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.strings.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#11111 feat(web): Sjukratryggingar footer update
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/layouts/main.tsx
  apps/web/screens/LifeEvent/LifeEvent.tsx
Labels: automerge

#11114 fix(consultation-portal): remove padding in hero banner
  apps/consultation-portal/components/HeroBanner/HeroBanner.css.ts
  apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
Labels: automerge

#11117 fix(consultation-portal): removed crypto and using UUIDv4
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/utils/helpers/createUUIDString.ts
Labels: automerge

#11083 fix(j-s): Create Court Case
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#11122 fix(Ehic): fix api actions (#11108)
  libs/application/templates/european-health-insurance-card/src/dataProviders/apiActions.enum.ts
  libs/application/templates/european-health-insurance-card/src/dataProviders/index.ts
  libs/application/templates/european-health-insurance-card/src/lib/template.ts
Labels: automerge

#11107 fix(consultation-portal): remove checkboxes in my subs and added link
  apps/consultation-portal/components/Card/ChosenSubscriptionCard.tsx
  apps/consultation-portal/components/ChosenSubscriptions/ChosenSubscriptions.tsx
  apps/consultation-portal/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
  apps/consultation-portal/screens/UserSubscriptions/UserSubscriptions.tsx
Labels: automerge

#11120 fix(estate): Lookup person custom component
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/LookupPerson/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/fields/index.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/sharedSections/announcerInfo.ts
Labels: automerge

#11127 fix(consultation-portal): Fix/samradsgatt/kam 1224 various small fixes from
  apps/consultation-portal/components/CaseEmailBox/CaseEmailBox.tsx
  apps/consultation-portal/components/CaseStatusCard/CaseStatusCard.tsx
  apps/consultation-portal/components/ChosenSubscriptions/ChosenSubscriptions.tsx
  apps/consultation-portal/components/EmailBox/EmailBox.tsx
  apps/consultation-portal/components/SubscriptionChoices/SubscriptionChoices.tsx
  apps/consultation-portal/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/components/RenderDocumentsBox.tsx
  apps/consultation-portal/types/enums.ts
  apps/consultation-portal/utils/dummydata/api/User/SubscriptionsArray.ts
  apps/consultation-portal/utils/dummydata/index.ts
  apps/consultation-portal/utils/helpers/subscriptions/initSubscriptions.ts
Labels: automerge

#11124 fix(j-s): Link resolver becomes text button in alert banner
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/strings.ts
Labels: automerge

#11131 fix(consultation-portal): getSession in _app takes in customContext
  apps/consultation-portal/pages/_app.tsx
Labels: automerge

#11126 feat(search-toolkit): Remove unnecessary property
  apps/web/screens/queries/Search.tsx
Labels: automerge

#11132 fix(consultation-portal): tölfræði is hidden and isMobile hook used in Menu
  apps/consultation-portal/components/Menu/Menu.tsx
  apps/consultation-portal/components/Menu/MenuItems.ts
Labels: automerge

#11119 fix(ids-admin): Permissions table sticky header
  libs/island-ui/core/src/lib/Box/useBoxStyles.css.ts
  libs/island-ui/core/src/lib/Table/Table.css.ts
  libs/island-ui/core/src/lib/Table/Table.tsx
  libs/portals/admin/ids-admin/src/components/Client/Permissions.tsx
Labels: automerge

#10984 feat(web): Resolve powerbi embed props at request time
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.css.ts
  apps/web/components/Organization/Slice/PowerBiSlice/PowerBiSlice.tsx
  apps/web/screens/queries/PowerBi.ts
  apps/web/screens/queries/fragments.ts
  libs/api/domains/powerbi/.babelrc
  libs/api/domains/powerbi/.eslintrc.json
  libs/api/domains/powerbi/README.md
  libs/api/domains/powerbi/jest.config.js
  libs/api/domains/powerbi/project.json
  libs/api/domains/powerbi/src/index.ts
  libs/api/domains/powerbi/src/lib/dto/powerbiEmbedToken.input.ts
  libs/api/domains/powerbi/src/lib/powerbi.module.ts
  libs/api/domains/powerbi/src/lib/powerbi.resolver.ts
  libs/api/domains/powerbi/src/lib/serviceProvider.ts
  libs/api/domains/powerbi/tsconfig.json
  libs/api/domains/powerbi/tsconfig.lib.json
  libs/api/domains/powerbi/tsconfig.spec.json
  libs/cms/src/index.ts
  libs/cms/src/lib/cms.module.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getPowerBiEmbedPropsFromServer.response.ts
  libs/cms/src/lib/models/powerBiSlice.model.ts
  libs/cms/src/lib/powerbi.config.ts
  libs/cms/src/lib/powerbi.service.ts
  workspace.json
Labels: automerge

#11137 feat(consultation-portal): samradsgatt/kam 1225 birtingarreglur a umsognum
  apps/consultation-portal/components/Advices/Advices.tsx
  apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/components/CaseStatusCard/CaseStatusCard.tsx
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/components/AdviceCTA.tsx
  apps/consultation-portal/types/enums.ts
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/helpers/dateFormatter.ts
  libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#11138 fix(consultation-portal): KAM-1230-loggedout-state-layout-in-askriftir
  apps/consultation-portal/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#11140 fix(consultation-portal): fix spacing when no documents
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/components/RenderDocumentsBox.tsx
Labels: automerge

#11143 fix(j-s): Removing year from string in court of appeal ruling screen and allowing staff to see conclusion
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#11144 fix(j-s): Allowing input file upload to upload multiple files
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
Labels: automerge

#11139 chore(auht-api-lib): Add seed script for RSK prokura admin scope and a test web client.
  libs/auth-api-lib/seeders/data/scope-rsk-prokura-admin.ts
Labels: automerge

#11152 fix(auth-api-lib): Fix domain name of rsk scope name
  libs/auth-api-lib/seeders/data/scope-rsk-prokura-admin.ts
Labels: automerge

#11133 feat(admin-api): Api scope PATCH in GQL and rest
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.auth.spec.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/api/domains/auth-admin/src/lib/scope/dto/patch-scope.input.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.resolver.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.service.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth-api-lib/src/lib/resources/admin/dto/admin-patch-scope.dto.ts
  libs/auth-api-lib/src/lib/resources/admin/services/admin-translation.service.ts
  libs/auth-api-lib/src/lib/resources/models/api-scope.model.ts
Labels: automerge

#11141 fix(driving-learners-permit): Remove residence requirement and change disqualification logic
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/fakeEligibility.ts
Labels: automerge

#11155 fix(estate): Estate hiding options for prod
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/lib/constants.ts
Labels: automerge

#11145 feat(j-s): Upload Appeal Ruling to District Court
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
Labels: automerge

#11157 feat(consultation-portal): audit and logging in api layer
  libs/api/domains/consultation-portal/src/lib/caseSubscription/caseSubscription.resolver.ts
  libs/api/domains/consultation-portal/src/lib/caseSubscription/caseSubscription.service.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/documents/documents.resolver.ts
  libs/api/domains/consultation-portal/src/lib/documents/documents.service.ts
  libs/api/domains/consultation-portal/src/lib/statistics/statistics.resolver.ts
  libs/api/domains/consultation-portal/src/lib/statistics/statistics.service.ts
  libs/api/domains/consultation-portal/src/lib/types/types.resolver.ts
  libs/api/domains/consultation-portal/src/lib/types/types.service.ts
  libs/api/domains/consultation-portal/src/lib/user/user.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/user.service.ts
Labels: automerge

#11161 feat(web): Hotfix - Sjukratryggingar footer update (#11111)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/layouts/main.tsx
  apps/web/screens/LifeEvent/LifeEvent.tsx
Labels: automerge

#11118 feat(web): Add og:image field to News content type
  apps/web/screens/News.tsx
  apps/web/screens/queries/News.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/news.model.ts
Labels: automerge

#11123 feat(web): Add footer for GEV organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/GevTheme/index.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarFooter.tsx
Labels: automerge

#11142 fix(consultation-portal): hero banner in mobile is like in figma
  apps/consultation-portal/components/HeroBanner/HeroBanner.tsx
  apps/consultation-portal/components/HeroBanner/components/ArrowLink.tsx
  apps/consultation-portal/components/HeroBanner/components/HeroTiles.css.ts
  apps/consultation-portal/components/HeroBanner/components/HeroTiles.tsx
  apps/consultation-portal/components/HeroBanner/components/IntroText.tsx
  apps/consultation-portal/components/svg/HeroLogoMobile.tsx
  apps/consultation-portal/components/svg/LESchoolMobile.tsx
  apps/consultation-portal/components/svg/index.ts
Labels: automerge

#11146 feat(j-s): Display modal if appeal statement deadline has passed
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
Labels: automerge

#11128 fix(transfer of vehicle ownership): add age validation to data schema
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/license-plate-renewal/project.json
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
Labels: automerge

#11169 fix(system-e2e): Fixing assertion for an institution
  apps/system-e2e/src/tests/islandis/web/smoke/sites-of-institutions.spec.ts
Labels: automerge

#11165 fix(consultation-portal): fixed text in stakeholders
  apps/consultation-portal/screens/Case/components/Stakeholders.tsx
Labels: automerge

#11168 fix(operating-license-application): No name for property
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/operating-license/src/lib/messages.ts
Labels: automerge, high priority

#11162 fix(consultation-portal): fix footer
  apps/consultation-portal/components/Footer/Footer.css.ts
  apps/consultation-portal/components/Footer/Footer.tsx
  apps/consultation-portal/components/Footer/components/FooterColumn.tsx
  apps/consultation-portal/components/Footer/components/FooterDivider.css.ts
  apps/consultation-portal/components/Footer/components/FooterDivider.tsx
Labels: automerge

#11154 feat(auth): Mutation for patching consent.
  apps/service-portal/src/auth.ts
  libs/api/domains/auth/src/lib/dto/updateConsent.input.ts
  libs/api/domains/auth/src/lib/resolvers/consent.resolver.ts
  libs/api/domains/auth/src/lib/services/consent.service.ts
  libs/clients/auth/ids-api/src/clientConfig.yaml
Labels: automerge

#11159 fix(j-s): Updating text sizes in alert banner
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
Labels: automerge

#11173 fix(transfer of vehicle ownership): application not submitted after all review
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/hasReviewerApproved.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/isLastReviewer.ts
Labels: automerge

#11167 fix(j-s): Fix Guards tests typos
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCaseGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extendGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getAllGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordSignatureConfirmationGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCustodyNoticePdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmationGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestCourtRecordSignatureGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignatureGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transitionGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archiveCaseFilesRecordGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPoliceGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCourtRecordToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverProsecutorToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverRequestToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedRulingToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/internalCaseControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRulingPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/defendantControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/deleteGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/internalDefendantControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createPresignedPostGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/deleteCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/fileControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/updateFilesGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/uploadCaseFileToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/archiveCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/internalFileControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createPresignedPostGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/deleteCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/getCaseFileSignedUrlGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/limitedAccessFileControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/defendantControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/deleteGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendCaseNotificationGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/police/test/policeControllerGuards.spec.ts
Labels: automerge

#11158 fix(estate): Estate - adding feature flag per each flow
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/getApplicationFeatureFlags.ts
Labels: automerge

#11147 feat(ids-admin): Client danger zone and rotate secret
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.service.ts
  apps/services/auth/admin-api/src/app/v2/secrets/me-client-secrets.controller.ts
  apps/services/auth/admin-api/src/app/v2/secrets/test/me-client-secrets.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.resolver.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/client.input.ts
  libs/api/domains/auth-admin/src/lib/client/dto/clients.input.ts
  libs/api/domains/auth-admin/src/lib/client/dto/rotate-secret.input.ts
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/components/Client/Client.graphql
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/DangerZone.tsx
  libs/portals/admin/ids-admin/src/components/Client/Permissions.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.graphql
  libs/portals/admin/ids-admin/src/components/forms/AddPermissions/AddPermissions.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/components/forms/RotateSecret/RotateSecret.action.ts
  libs/portals/admin/ids-admin/src/components/forms/RotateSecret/RotateSecret.graphql
  libs/portals/admin/ids-admin/src/components/forms/RotateSecret/RotateSecret.tsx
  libs/portals/admin/ids-admin/src/lib/MockApplications.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/ClientsScreen.tsx
  libs/portals/admin/ids-admin/src/shared/hooks/useCopyToClipboard.ts
Labels: automerge

#11166 fix(j-s): Fix defender transition guards and added tests
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transitionGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transitionRolesRules.spec.ts
Labels: automerge

#11163 feat(j-s): Custody Notice to Police
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/updatePoliceCase.spec.ts
  charts/judicial-system/values.dev.yaml
Labels: automerge

#11176 fix(estate): skip market value validation when fields are disabled
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#11172 fix(consultation-portal): fixes in statusboxes and status name
  apps/consultation-portal/components/CaseTimeline/CaseTimeline.tsx
  apps/consultation-portal/screens/Case/components/AdviceCTA.tsx
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/types/enums.ts
  apps/consultation-portal/utils/helpers/frontPageFilters/getInitFilterValues.ts
  apps/consultation-portal/utils/helpers/getTagVariants.ts
Labels: automerge

#11178 chore(ci): Increase node memory limits
  .github/actions/unit-test/action.yml
Labels: automerge

#11179 feat(consultation-portal): readme files
  SUMMARY.md
  apps/consultation-portal/README.md
  libs/api/domains/consultation-portal/README.md
  libs/clients/consultation-portal/README.md
Labels: automerge

#11150 feat(portals-admin-ids-admin): Permissions list view and create permissions
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/components/Client/ClientsUrl.tsx
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
  libs/portals/admin/ids-admin/src/components/Client/Permissions.tsx
  libs/portals/admin/ids-admin/src/components/Client/Translations.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.css.ts
  libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/components/Layout/Layout.tsx
  libs/portals/admin/ids-admin/src/components/Permission/Permission.tsx
  libs/portals/admin/ids-admin/src/components/PermissionsList/PermissionsList.css.ts
  libs/portals/admin/ids-admin/src/components/PermissionsList/PermissionsList.graphql
  libs/portals/admin/ids-admin/src/components/PermissionsList/PermissionsList.loader.ts
  libs/portals/admin/ids-admin/src/components/PermissionsList/PermissionsList.tsx
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreatePermission/CreatePermission.action.ts
  libs/portals/admin/ids-admin/src/components/forms/CreatePermission/CreatePermission.graphql
  libs/portals/admin/ids-admin/src/components/forms/CreatePermission/CreatePermission.tsx
  libs/portals/admin/ids-admin/src/index.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/ClientsScreen.tsx
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.tsx
  libs/portals/admin/ids-admin/src/shared/components/ContentCard/ContentCard.css.ts
  libs/portals/admin/ids-admin/src/shared/components/ContentCard/ContentCard.tsx
  libs/portals/admin/ids-admin/src/shared/components/IdsAdminCard/IdsAdminCard.css.ts
  libs/portals/admin/ids-admin/src/shared/components/IdsAdminCard/IdsAdminCard.tsx
  libs/portals/admin/ids-admin/src/shared/hooks/useLooseSearch.tsx
  libs/portals/admin/ids-admin/src/shared/utils/forms.ts
  libs/portals/core/src/components/PortalNavigation/PortalNavigation.tsx
Labels: automerge
