Repository island-is/island.is, pull requests merged in 2023-04, with the labels that each got.

#10573 fix(pdpp): Remove feature flag for allowed delegations
  libs/application/templates/public-debt-payment-plan/src/lib/PublicDebtPaymentPlanTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#10716 chore(infra): Adjust resources for api
  apps/api/infra/api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#10712 feat(auth-admin): Form validation for edit client
  apps/web/components/Menu/Menu.tsx
  libs/island-ui/core/src/lib/Button/Button.tsx
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/ClientsUrl.tsx
  libs/portals/admin/ids-admin/src/components/Client/ContentCard.tsx
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
  libs/portals/admin/ids-admin/src/components/Client/Translations.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditApplication.action.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx
  libs/portals/admin/ids-admin/src/shared/hooks/useFormatErrorMessage.ts
  libs/react-spa/shared/src/lib/validate.ts
Labels: automerge

#10729 feat(institution-collaboration): Update service list
  libs/application/template-api-modules/src/lib/modules/templates/institution-collaboration/emailGenerators/applicationOverviewTemplate.ts
  libs/application/templates/institution-collaboration/src/fields/Constraints/ConstraintController.tsx
  libs/application/templates/institution-collaboration/src/fields/Constraints/Constraints.tsx
  libs/application/templates/institution-collaboration/src/fields/ReviewScreen/ReviewScreen.tsx
  libs/application/templates/institution-collaboration/src/forms/application.ts
  libs/application/templates/institution-collaboration/src/lib/messages.ts
Labels: automerge

#10586 feat(clients-driving-license): Introduce api version 5
  libs/clients/driving-license/project.json
  libs/clients/driving-license/src/lib/apiConfiguration.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.config.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/v5/clientConfig.json
  libs/clients/driving-license/src/v5/index.ts
Labels: automerge

#10592 fix(estate): further bugfixing of the estate applications
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/templates/announcement-of-death/src/fields/EstateMemberRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionInfo.ts
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/heirs.ts
Labels: automerge

#10501 feat(search-toolkit): Backlog features
  apps/web/components/Organization/SearchBox/SearchBox.tsx
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx
  apps/web/screens/queries/Search.tsx
  libs/api/domains/content-search/src/lib/contentSearch.resolver.ts
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge

#9848 feat(service-portal): student graduation info
  .github/CODEOWNERS
  SUMMARY.md
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/download-service/infra/download-service.ts
  apps/download-service/src/app/app.module.ts
  apps/download-service/src/app/modules/education-documents/dto/getEducationGraduationDocument.ts
  apps/download-service/src/app/modules/education-documents/education-document.controller.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/university-of-iceland/.babelrc
  libs/api/domains/university-of-iceland/.eslintrc.json
  libs/api/domains/university-of-iceland/README.md
  libs/api/domains/university-of-iceland/jest.config.js
  libs/api/domains/university-of-iceland/project.json
  libs/api/domains/university-of-iceland/src/index.ts
  libs/api/domains/university-of-iceland/src/lib/dto/universityOfIcelandStudentInfo.input.ts
  libs/api/domains/university-of-iceland/src/lib/models/universityOfIcelandStudentInfo.model.ts
  libs/api/domains/university-of-iceland/src/lib/universityOfIceland.module.ts
  libs/api/domains/university-of-iceland/src/lib/universityOfIceland.resolver.ts
  libs/api/domains/university-of-iceland/tsconfig.json
  libs/api/domains/university-of-iceland/tsconfig.lib.json
  libs/api/domains/university-of-iceland/tsconfig.spec.json
  libs/clients/university-of-iceland/.babelrc
  libs/clients/university-of-iceland/.eslintrc.json
  libs/clients/university-of-iceland/README.md
  libs/clients/university-of-iceland/jest.config.js
  libs/clients/university-of-iceland/project.json
  libs/clients/university-of-iceland/src/clientConfig.yaml
  libs/clients/university-of-iceland/src/index.ts
  libs/clients/university-of-iceland/src/lib/universityOfIcelandClient.config.ts
  libs/clients/university-of-iceland/src/lib/universityOfIcelandClient.module.ts
  libs/clients/university-of-iceland/src/lib/universityOfIcelandClient.provider.ts
  libs/clients/university-of-iceland/src/lib/universityOfIcelandClient.service.ts
  libs/clients/university-of-iceland/tsconfig.json
  libs/clients/university-of-iceland/tsconfig.lib.json
  libs/clients/university-of-iceland/tsconfig.spec.json
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/paths.ts
  libs/service-portal/education/src/lib/navigation.ts
  libs/service-portal/education/src/lib/paths.ts
  libs/service-portal/education/src/module.tsx
  libs/service-portal/education/src/screens/EducationGraduation/EducationGraduation.tsx
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
  libs/service-portal/education/src/screens/EducationOverview/EducationOverview.tsx
  tsconfig.base.json
  workspace.json
Labels: automerge, deploy-feature

#10732 fix(service-portal): Update vehicle links
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/utils/constants.ts
Labels: automerge, high priority

#10725 fix(auth-admin): Remove filter dropdown for tenants and cleints
  libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
Labels: automerge

#10736 fix(portals-admin-ids-admin): All text in english
  libs/portals/admin/ids-admin/src/lib/messages.ts
Labels: automerge

#10734 fix(auth-admin): Various bug fixes for auth-admin
  apps/portals/admin/src/auth.ts
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/create-client.input.ts
  libs/api/domains/auth-admin/src/lib/models/client-type.enum.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-create-client.dto.ts
  libs/auth-api-lib/src/lib/types.ts
  libs/clients/auth/admin-api/src/index.ts
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/ApplicationsScreen.tsx
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.tsx
Labels: automerge

#10739 feat(web): Re-index pages into ElasticSearch when nested content changes
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
  libs/cms/src/lib/environments/environment.ts
Labels: automerge

#10730 feat(consultation-portal): loading bar
  apps/consultation-portal/components/PageLoader/PageLoader.tsx
  apps/consultation-portal/pages/_app.tsx
Labels: automerge

#10741 fix(consultation-portal): table has fixed width
  apps/consultation-portal/components/Table/SubscriptionTable.css.ts
  apps/consultation-portal/components/Table/SubscriptionTable.tsx
  apps/consultation-portal/components/Table/SubscriptionTableItem.css.ts
  apps/consultation-portal/components/Table/SubscriptionTableItem.tsx
Labels: automerge

#10745 fix: disabled mountebank for this release
  infra/src/dsl/egress.spec.ts
  infra/src/dsl/kubernetes-runtime.ts
  infra/src/dsl/value-files-generators/helm.spec.ts
Labels: automerge, high priority, merge.priority_merge_label

#10744 fix(portals-admin-ids-admin): Hotfixes few bugs, all text in english and remove filter dropdown
  apps/portals/admin/src/auth.ts
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/create-client.input.ts
  libs/api/domains/auth-admin/src/lib/models/client-type.enum.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-create-client.dto.ts
  libs/auth-api-lib/src/lib/types.ts
  libs/clients/auth/admin-api/src/index.ts
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/ApplicationsScreen.tsx
  libs/portals/admin/ids-admin/src/screens/Tenant/Tenant.tsx
Labels: automerge

#10688 feat(j-s): Transition handles case appeal state transition
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/case/limitedAccessCase.resolver.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230327222607-update-case.js
  apps/judicial-system/backend/migrations/20230328095056-update-notification.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web-e2e/src/fixtures/transitionCaseMutationResponse.json
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/transitionCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/transitionLimitedAccessCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#10719 feat(j-s): Add statement screen
  apps/judicial-system/web/pages/greinargerd/[id].ts
  apps/judicial-system/web/pages/verjandi/greinargerd/[id].ts
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.strings.ts
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
Labels: automerge

#10742 feat(auth-admin): Added advanced settings
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
  libs/portals/admin/ids-admin/src/components/Client/Translations.tsx
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditApplication.action.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
Labels: automerge

#10752 fix(license-service): reduce logging
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
Labels: automerge

#10757 fix(license-service): Hotfix: reduce log spam
  libs/api/domains/license-service/src/lib/client/adr-license-client/genericAdrLicense.service.ts
  libs/api/domains/license-service/src/lib/client/disability-license-client/genericDisabilityLicense.service.ts
  libs/api/domains/license-service/src/lib/client/firearm-license-client/genericFirearmLicense.service.ts
  libs/api/domains/license-service/src/lib/client/machine-license-client/genericMachineLicense.service.ts
Labels: automerge

#10758 feat(web): Syslumenn / Fix links and filters
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
Labels: automerge

#10760 fix(web): Main menu graphql errors due to missing content in CMS
  libs/cms/src/lib/models/menuLinkWithChildren.model.ts
Labels: automerge

#9838 feat(web): Syslumenn / Alcohol and temporary event licences
  apps/web/components/connected/index.ts
  apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/AlcoholLicencesList.tsx
  apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/queries.ts
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/TemporaryEventLicencesList.tsx
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/queries.ts
  apps/web/components/connected/syslumenn/index.ts
  apps/web/components/connected/syslumenn/utils/csvExport.ts
  apps/web/components/connected/syslumenn/utils/index.ts
  apps/web/components/connected/syslumenn/utils/search.ts
  apps/web/components/connected/syslumenn/utils/valueParsers.ts
  apps/web/utils/richText.tsx
  libs/api/domains/syslumenn/src/lib/models/alcoholLicence.ts
  libs/api/domains/syslumenn/src/lib/models/temporaryEventLicence.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/syslumenn/src/lib/__mock-data__/responses.ts
  libs/clients/syslumenn/src/lib/syslumenn.spec.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
  libs/shared/connected/src/utils/localization.ts
Labels: automerge, deploy-feature

#10761 fix: slight tuning to the cpu request values to reduce scaling pressu…
  apps/judicial-system/web/infra/judicial-system-web.ts
  apps/services/license-api/infra/license-api.ts
  apps/services/sessions/infra/sessions.ts
  apps/services/user-notification/infra/user-notification.ts
  apps/skilavottord/web/infra/web.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#10720 fix(consultation-portal): Kam 1067 change authentication to next auth
  apps/consultation-portal/components/AppLayout/AppLayout.tsx
  apps/consultation-portal/components/AuthProvier/AuthProvider.tsx
  apps/consultation-portal/components/Card/SubscriptionActionBox.tsx
  apps/consultation-portal/components/EmailBox/EmailBox.tsx
  apps/consultation-portal/components/Menu/Menu.tsx
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/context/UserContext.tsx
  apps/consultation-portal/context/index.ts
  apps/consultation-portal/graphql/authLink.ts
  apps/consultation-portal/graphql/client.ts
  apps/consultation-portal/graphql/httpLink.ts
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/graphql/withApollo.tsx
  apps/consultation-portal/lib/environment.ts
  apps/consultation-portal/lib/idsConfig.ts
  apps/consultation-portal/next.config.js
  apps/consultation-portal/pages/_app.tsx
  apps/consultation-portal/pages/api/auth/[...nextauth].ts
  apps/consultation-portal/pages/api/auth/check.ts
  apps/consultation-portal/pages/api/auth/login.ts
  apps/consultation-portal/pages/api/auth/logout.ts
  apps/consultation-portal/pages/askriftir/index.tsx
  apps/consultation-portal/pages/auth/login.tsx
  apps/consultation-portal/pages/index.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Advices/getAllUserAdvices.graphql.ts
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/getAdvices.graphql.ts
  apps/consultation-portal/screens/Case/getCase.graphql.ts
  apps/consultation-portal/screens/Home/Home.tsx
  apps/consultation-portal/screens/Home/getAllTypes.graphql.ts
  apps/consultation-portal/screens/Home/getCases.graphql.ts
  apps/consultation-portal/screens/Home/getStatistics.graphql.ts
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/screens/Subscriptions/queries.graphql.ts
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/authentication/isAuthenticated.ts
  apps/consultation-portal/utils/helpers/index.ts
  apps/consultation-portal/utils/helpers/useFetchCases.ts
  apps/consultation-portal/utils/helpers/useLogOut.ts
  apps/consultation-portal/utils/helpers/useLogin.ts
  apps/consultation-portal/utils/helpers/useUser.ts
  libs/api/domains/consultation-portal/src/lib/api-domains-consultation-portal.module.ts
  libs/api/domains/consultation-portal/src/lib/auth-tools/auth.middleware.ts
  libs/api/domains/consultation-portal/src/lib/auth-tools/current-authorization.ts
  libs/api/domains/consultation-portal/src/lib/auth-tools/getRequest.ts
  libs/api/domains/consultation-portal/src/lib/authentication/authentication.resolver.ts
  libs/api/domains/consultation-portal/src/lib/authentication/authentication.service.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/user/user.service.ts
  libs/api/domains/consultation-portal/src/lib/user/userAdvice.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/userEmail.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/userEmail.services.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/consultationPortal.scope.ts
Labels: automerge

#10743 feat(auth-admin): Added copy button to basic info
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/lib/messages.ts
Labels: automerge

#10763 feat(consultation-portal): Kam 1056 add confirm subscription button
  apps/consultation-portal/components/Card/ChosenSubscriptionCard.tsx
  apps/consultation-portal/components/Card/SubscriptionActionCard.tsx
  apps/consultation-portal/components/EmailBox/EmailBox.tsx
  libs/api/domains/consultation-portal/src/lib/api-domains-consultation-portal.module.ts
  libs/api/domains/consultation-portal/src/lib/caseSubscription/caseSubscription.resolver.ts
  libs/api/domains/consultation-portal/src/lib/caseSubscription/caseSubscription.service.ts
  libs/api/domains/consultation-portal/src/lib/models/postCaseSubscriptionsCommand.model.ts
  libs/api/domains/consultation-portal/src/lib/models/userSubscriptionResult.model.ts
  libs/api/domains/consultation-portal/src/lib/models/userSubscriptionsAggregate.model.ts
  libs/api/domains/consultation-portal/src/lib/user/user.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/userEmail.resolver.ts
  libs/clients/consultation-portal/src/clientConfig.json
  libs/clients/consultation-portal/src/lib/apiConfiguration.ts
Labels: automerge

#10765 feat(sessions): Allow different formatted National IDs in the filter.
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
Labels: automerge

#10767 feat(ids-admin): Don't show the back button on the tenant list.
  libs/portals/admin/ids-admin/src/screens/IDSAdmin.tsx
Labels: automerge

#10768 chore(contentful-apps): Use environment variables instead of runtime config for Contentful Apps
  apps/contentful-apps/components/MideindTranslationSidebar/api/index.tsx
  apps/contentful-apps/next.config.js
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
Labels: automerge

#10770 feat(ids-admin): Tenant list grid width
  libs/portals/admin/ids-admin/src/components/TenantsList/TenantsList.tsx
Labels: automerge

#10771 feat(sessions): Changes to display country but not region
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/countries.ts
Labels: automerge

#10769 fix(consultation-portal): KAM-1073 fix breadcrumbs in subscriptions
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  libs/api/domains/consultation-portal/src/lib/user/user.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/user.service.ts
Labels: automerge

#10775 fix(consultation-portal): fixed types not found
  libs/api/domains/consultation-portal/src/lib/models/userCaseSubscriptionResult.model.ts
  libs/api/domains/consultation-portal/src/lib/models/userSubscriptionResult.model.ts
Labels: automerge

#10764 fix(j-s): Only display alert banner if case appeal has been postponed
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/AppealAlertBanner/AppealAlertBanner.spec.tsx
  apps/judicial-system/web/src/components/AppealAlertBanner/AppealAlertBanner.strings.ts
  apps/judicial-system/web/src/components/AppealAlertBanner/AppealAlertBanner.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#10766 feat(j-s): Add a isStatementDeadlineExpired field to our API
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#10777 fix(consultation-portal): empty state on case documents
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#10731 feat(j-s): Court of appeal overview screen
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/pages/landsrettur/yfirlit/[id].ts
  apps/judicial-system/web/src/components/Conclusion/Conclusion.strings.ts
  apps/judicial-system/web/src/components/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfButton.css.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.spec.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#10783 feat(consultation-portal): Minimum char in input
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
Labels: automerge

#10779 feat(j-s): Display appeal deadline alert banner for judge
  apps/judicial-system/web/src/components/AppealAlertBanner/AppealAlertBanner.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#10778 feat(consultation-portal): Loggedout state á villtu senda umsögn
  apps/consultation-portal/components/Menu/Menu.tsx
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#10789 fix(transfer of vehicle ownership): Handle if buyerCoOwnerAndOperator is empty
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ValidationErrorMessages/index.tsx
Labels: automerge

#10784 feat(island-ui): Hide spin buttons and add inputmode
  libs/island-ui/core/src/lib/Input/Input.css.ts
  libs/island-ui/core/src/lib/Input/Input.stories.tsx
  libs/island-ui/core/src/lib/Input/types.ts
Labels: automerge

#10790 fix(sessions): Hotfix sessions to format nationalId in search input and only store country code based on location for session.
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/screens/Sessions/Sessions.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/countries.ts
Labels: automerge

#10791 fix(consultation-portal): unauthorized gql error does not redirect to 500
  apps/consultation-portal/pages/umsagnir/index.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
Labels: automerge

#10792 feat(ids-admin): Human readable seconds
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
  libs/portals/admin/ids-admin/src/components/Client/ReadableSeconds.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
Labels: automerge

#10795 chore(j-s): Court of appeal FormStepper title
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
Labels: automerge

#10708 feat(island-ui): Larger tooltip option
  libs/island-ui/core/src/lib/Tooltip/Tooltip.css.ts
  libs/island-ui/core/src/lib/Tooltip/Tooltip.tsx
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
Labels: automerge

#10340 infra(air-discount-scheme-web,api): Fixing reference to domain names
  apps/api/infra/api.ts
  apps/services/search-indexer/infra/search-indexer-service.ts
Labels: automerge

#10798 feat: change api to devland.is
  apps/api/infra/api.ts
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/screens/Case/Case.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/consultation-portal/src/lib/consultationPortalClient.config.ts
Labels: automerge

#10799 feat: add general subscription to all cases
  apps/consultation-portal/components/Card/ChosenSubscriptionCard.tsx
  apps/consultation-portal/components/Table/SubscriptionTable.tsx
  apps/consultation-portal/components/Table/SubscriptionTableAllItems.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/utils/dummydata/api/User/SubscriptionsArray.ts
Labels: automerge

#10801 fix(accident-notification): Parse phone number before submitting document
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
Labels: automerge

#10802 feat(island-ui): ToggleSwitch color changes
  libs/island-ui/core/src/lib/ToggleSwitch/ToggleSwitch.css.ts
  libs/island-ui/core/src/lib/ToggleSwitch/ToggleSwitch.stories.mdx
Labels: automerge

#10780 fix(consultation-portal): changed consultationPortal.scope
  libs/auth/scopes/src/lib/consultationPortal.scope.ts
Labels: automerge

#10808 fix(application-admin-portal): Adjustments to the ui
  apps/application-system/api/src/app/modules/application/utils/application.ts
  libs/application/ui-components/src/components/ApplicationCard/ApplicationCard.tsx
  libs/application/ui-components/src/components/ApplicationCard/components/ApplicationCardProgress.tsx
  libs/application/ui-components/src/components/ApplicationCard/utils/history.tsx
  libs/portals/admin/application-system/src/components/ApplicationDetails/ApplicationDetails.tsx
  libs/portals/admin/application-system/src/components/ApplicationsTable/ApplicationsTable.tsx
  libs/portals/admin/application-system/src/components/Filters/Filters.tsx
  libs/portals/admin/application-system/src/lib/messages.ts
  libs/portals/admin/application-system/src/screens/Overview/Overview.tsx
Labels: automerge

#10806 fix(transport authority): Fix validation when removing co-owner/operator without filling in all required fields
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.utils.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwnerRepeater/CoOwnerRepeaterItem.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwnerRepeater/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getApproveAnswers.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getChargeItemCodes.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getReviewSteps.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getReviewerInfo.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/isLastReviewer.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/OperatorRepeater/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/mainOperatorSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/CoOwnerAndOperatorRepeater/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/CoOwnersSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/sections/OperatorSection.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ReviewCoOwnerAndOperatorRepeater/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/ReviewMainOperator/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/mainOperatorSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
Labels: automerge

#10811 feat(web): Hotfix - Syslumenn list pages
  apps/web/components/connected/index.ts
  apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/AlcoholLicencesList.tsx
  apps/web/components/connected/syslumenn/CardLists/AlcoholLicencesList/queries.ts
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/TemporaryEventLicencesList.tsx
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/queries.ts
  apps/web/components/connected/syslumenn/TableLists/BrokersList/BrokersList.tsx
  apps/web/components/connected/syslumenn/TableLists/BrokersList/queries.ts
  apps/web/components/connected/syslumenn/index.ts
  apps/web/components/connected/syslumenn/utils/csvExport.ts
  apps/web/components/connected/syslumenn/utils/index.ts
  apps/web/components/connected/syslumenn/utils/search.ts
  apps/web/components/connected/syslumenn/utils/valueParsers.ts
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
  apps/web/utils/richText.tsx
  libs/api/domains/syslumenn/src/lib/models/alcoholLicence.ts
  libs/api/domains/syslumenn/src/lib/models/broker.ts
  libs/api/domains/syslumenn/src/lib/models/temporaryEventLicence.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/__mock-data__/requestHandlers.ts
  libs/clients/syslumenn/src/lib/__mock-data__/responses.ts
  libs/clients/syslumenn/src/lib/syslumenn.spec.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/shared/connected/src/utils/localization.ts
Labels: automerge

#10813 feat: subscribe button, clean selection button and add toast
  apps/consultation-portal/components/IconLink/IconLink.css.ts
  apps/consultation-portal/components/IconLink/IconLink.tsx
  apps/consultation-portal/components/Layout/Layout.tsx
  apps/consultation-portal/components/Table/SubscriptionTableItem.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.tsx
Labels: automerge

#10812 fix(service-portal): missing secret
  apps/services/license-api/infra/license-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#10776 fix: upgraded prod application system api callback url
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#10816 fix: upgraded prod application system api callback url (#10776)
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#10819 fix(transfer of vehicle ownership): Handle if buyerCoOwnerAndOperator is empty
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
Labels: automerge

#10817 fix(estate): id in forms for guns
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
Labels: automerge

#10820 fix(transfer of vehicle ownership): Handle if buyerCoOwnerAndOperator is empty
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
Labels: automerge

#10809 feat(j-s): AlertBanner clone
  apps/judicial-system/web/src/components/AlertBanner/index.tsx
  libs/island-ui/core/src/index.ts
Labels: automerge

#10827 feat(consultation-portal): Authentication consultation portal
  libs/api/domains/consultation-portal/src/lib/caseSubscription/caseSubscription.resolver.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/user.resolver.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/auth/scopes/src/lib/consultationPortal.scope.ts
  libs/auth/scopes/src/lib/stjornarradid.scope.ts
  libs/clients/consultation-portal/src/lib/apiConfiguration.ts
  libs/clients/consultation-portal/src/lib/consultationPortalClient.config.ts
Labels: automerge

#10814 feat(auth-admin): Auth admin client patch
  apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.resolver.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/patch-client.input.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-claim.model.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-environment.model.ts
  libs/api/domains/auth-admin/src/lib/models/refreshTokenExpiration.enum.ts
  libs/api/domains/auth-admin/src/lib/models/translated-value.model.ts
  libs/auth-api-lib/seeders/local/009-languages.js
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client-claim.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/translation/dto/translated-value.dto.ts
  libs/auth-api-lib/src/lib/translation/translation.service.ts
  libs/auth-api-lib/src/lib/types.ts
  libs/clients/auth/admin-api/src/index.ts
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/components/Client/Client.graphql
  libs/portals/admin/ids-admin/src/components/Client/Client.tsx
  libs/portals/admin/ids-admin/src/components/Client/ClientsUrl.tsx
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/components/Client/Lifetime.tsx
  libs/portals/admin/ids-admin/src/components/Client/Translations.tsx
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditApplication.action.ts
  libs/portals/admin/ids-admin/src/components/forms/EditApplication/EditClient.graphql
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#10815 fix(j-s): Fix duplicate contentful string
  apps/judicial-system/web/messages/Core/sections.ts
Labels: automerge

#10826 fix(inheritance-report): adding guns
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/index.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/assets.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#10803 feat(phone-input): Scaling and improvements
  libs/application/ui-forms/src/lib/applicantInformationMultiField/applicantInformationMultiField.ts
  libs/application/ui-shell/src/components/FormMultiField.tsx
  libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/Components/index.tsx
  libs/island-ui/core/src/lib/PhoneInput/CountryCodeSelect/CountryCodeSelect.css.ts
  libs/island-ui/core/src/lib/PhoneInput/PhoneInput.css.ts
  libs/island-ui/core/src/lib/PhoneInput/PhoneInput.tsx
Labels: automerge

#10644 feat(auth-admin): Add subcollection for client secrets.
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/v2/clients/clients.module.ts
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.module.ts
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.service.ts
  apps/services/auth/admin-api/src/app/v2/secrets/dto/client-secret.dto.ts
  apps/services/auth/admin-api/src/app/v2/secrets/me-client-secrets.controller.ts
  apps/services/auth/admin-api/src/app/v2/secrets/test/me-client-secrets.auth.spec.ts
  apps/services/auth/admin-api/src/app/v2/secrets/test/me-client-secrets.spec.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/auth-api-lib/migrations/20230322150959-add-uuid-ossp-extension.js
  libs/auth-api-lib/migrations/20230322151344-client-secret-add-columns.js
  libs/auth-api-lib/src/lib/clients/models/client-secret.model.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#10829 fix(web): Increase limit for fetching supportqnas in category to 1000
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge

#10786 fix(general-petitions): minor improvements
  apps/system-e2e/src/tests/islandis/undirskriftarlistar/smoke/undirskriftarlistar.spec.ts
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/application/templates/general-petition/src/forms/done.ts
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/styles.css.ts
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
Labels: automerge

#10834 feat(service-portal): use timeout parameters
  apps/api/infra/api.ts
  apps/services/license-api/infra/license-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/license-service/src/lib/client/driving-license-client/drivingLicenseService.api.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.config.ts
  libs/clients/adr-and-machine-license/src/lib/adr-and-machine-license.config.ts
  libs/clients/disability-license/src/lib/disabilityLicenseClient.config.ts
  libs/clients/disability-license/src/lib/disabilityLicenseClient.provider.ts
  libs/clients/firearm-license/src/lib/firearmApiProvider.ts
  libs/clients/firearm-license/src/lib/firearmLicenseClient.config.ts
Labels: automerge, deploy-feature

#10839 chore(infra): Fixing K8s access to mountebank
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#10835 feat(j-s): Appeal Counter Party Email
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/deliver.dto.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPoliceGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCourtRecordToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCourtRecordToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverProsecutorToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverProsecutorToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverRequestToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverRequestToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedRulingToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedRulingToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/deliverDefendantToCourt.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/deliverDefendantToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/internalDefendantControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/dto/deliver.dto.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/internalFile.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/sendInternalNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/internalNotificationControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefendantsNotUpdatedAtCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendCourtDateNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/user/guards/test/userExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/user/guards/user.decorator.ts
  apps/judicial-system/backend/src/app/modules/user/guards/userExists.guard.ts
  apps/judicial-system/backend/src/app/modules/user/index.ts
  apps/judicial-system/message-handler/src/app/internalDelivery.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/message/src/lib/test/random.ts
  libs/judicial-system/message/src/lib/test/sendMessagesToQueue.spec.ts
Labels: automerge

#10845 feat(island-ui): Icons larger and centered.
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.tsx
Labels: automerge

#10842 feat(institution national ids): Save institution national ids in shared file
  libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-company-card/digital-tachograph-company-card.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-drivers-card/digital-tachograph-drivers-card.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/digital-tachograph-workshop-card/digital-tachograph-workshop-card.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/license-plate-renewal/license-plate-renewal.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-license-plate/order-vehicle-license-plate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-registration-certificate/order-vehicle-registration-certificate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/criminal-record/src/dataProviders/index.ts
  libs/application/templates/mortgage-certificate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/dataProviders/index.ts
  libs/application/templates/transport-authority/digital-tachograph-company-card/src/dataProviders/index.ts
  libs/application/templates/transport-authority/digital-tachograph-drivers-card/src/dataProviders/index.ts
  libs/application/templates/transport-authority/digital-tachograph-workshop-card/src/dataProviders/index.ts
  libs/application/templates/transport-authority/license-plate-renewal/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/dataProviders/index.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/dataProviders/index.ts
  libs/application/types/src/index.ts
  libs/application/types/src/lib/InstitutionNationalIds.ts
Labels: automerge

#10836 fix(consultation-portal): changing post advice in api and fe
  apps/consultation-portal/components/Advices/Advices.tsx
  apps/consultation-portal/components/Card/SimpleCardSkeleton.tsx
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/utils/helpers/index.ts
  apps/consultation-portal/utils/helpers/useFetchAdvicesById.ts
  apps/consultation-portal/utils/helpers/usePostAdvice.ts
  libs/api/domains/consultation-portal/src/lib/api-domains-consultation-portal.module.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
Labels: automerge

#10785 feat(portals-admin): Fix clients loading state and button loading state
  libs/island-ui/core/src/lib/AsyncSearch/shared/Label/Label.tsx
  libs/portals/admin/ids-admin/src/components/Clients/Clients.loader.ts
  libs/portals/admin/ids-admin/src/components/forms/CreateClient/CreateClient.tsx
  libs/react-spa/shared/src/hooks/useIsSubmitting.tsx
  libs/react-spa/shared/src/index.ts
Labels: automerge

#10847 feat: samradsgatt/kam 1055 change or delete email
  apps/consultation-portal/components/EmailBox/EmailBox.tsx
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/utils/helpers/api/useFetchEmail.ts
  libs/api/domains/consultation-portal/src/lib/user/user.resolver.ts
  libs/api/domains/consultation-portal/src/lib/user/user.service.ts
Labels: automerge

#10853 feat(financial-statements-inao): Update timeout to 30 seconds
  libs/clients/financial-statements-inao/src/lib/financialStatementsInaoClient.service.ts
Labels: automerge

#10856 fix(operating-license): Data consistency and bugfixes
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/operating-license/src/lib/dataSchema.ts
  libs/application/templates/operating-license/src/lib/error.ts
Labels: automerge

#10854 fix(consultation-portal): Post advice doesn't accept higher than 0.03mb file
  apps/consultation-portal/components/WriteReviewCard/WriteReviewCard.tsx
  apps/consultation-portal/graphql/client.ts
  apps/consultation-portal/graphql/errorLink.ts
  apps/consultation-portal/graphql/retryLink.ts
  apps/consultation-portal/screens/Advices/Advices.tsx
Labels: automerge

#10859 feat(clients-driving-license): Updated client config
  libs/clients/driving-license/src/v5/clientConfig.json
Labels: automerge

#10821 feat(contentful-apps): Move public env variables into constants
  apps/contentful-apps/components/MideindTranslationSidebar/MideindTranslationSidebar.tsx
  apps/contentful-apps/components/MideindTranslationSidebar/api/index.tsx
  apps/contentful-apps/constants/index.ts
  apps/contentful-apps/infra/contentful-apps.ts
  apps/contentful-apps/next.config.js
  apps/contentful-apps/pages/fields/content-type-notifications-field.tsx
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
  charts/islandis/values.dev.yaml
Labels: automerge

#10863 fix(applications): General Fishing License bugfix
  libs/application/templates/general-fishing-license/src/fields/FishingLicense/index.tsx
Labels: automerge

#10838 feat(passports-client): add delivery address api
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/forms/overviewSection/childsOverview.ts
  libs/application/templates/passport/src/forms/overviewSection/personalOverview.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/constants.ts
  libs/clients/passports/src/clientConfig.yaml
  libs/clients/passports/src/lib/PassportsApiProvider.ts
  libs/clients/passports/src/lib/passportsApi.service.ts
  libs/clients/passports/src/lib/passportsApi.types.ts
Labels: automerge

#10864 fix(applications): GFL, Strandveiðileyfi has two chargecodes
  libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
  libs/application/templates/general-fishing-license/src/fields/Overview/index.tsx
Labels: automerge

#10861 feat(island-ui): Color variants on AccordionCard
  libs/island-ui/core/src/lib/Accordion/Accordion.stories.mdx
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.css.ts
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx
Labels: automerge

#10714 feat(web): IBM Watson Chatbot - Zendesk authentication
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/ChatPanel/WatsonChatPanel/index.ts
  apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/graphql/client.ts
  apps/web/screens/queries/WatsonAssistantChat.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/watson-assistant-chat/.babelrc
  libs/api/domains/watson-assistant-chat/.eslintrc.json
  libs/api/domains/watson-assistant-chat/README.md
  libs/api/domains/watson-assistant-chat/jest.config.js
  libs/api/domains/watson-assistant-chat/project.json
  libs/api/domains/watson-assistant-chat/src/index.ts
  libs/api/domains/watson-assistant-chat/src/lib/dto/watsonAssistantChatIdentityToken.input.ts
  libs/api/domains/watson-assistant-chat/src/lib/models/watsonAssistantChatIdentityTokenResponse.ts
  libs/api/domains/watson-assistant-chat/src/lib/serviceProvider.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.config.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.module.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.resolver.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.service.ts
  libs/api/domains/watson-assistant-chat/tsconfig.json
  libs/api/domains/watson-assistant-chat/tsconfig.lib.json
  libs/api/domains/watson-assistant-chat/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#10850 feat(j-s): Appeal Files to Court
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
Labels: automerge

#10875 fix(web): Correctly populate organization subpage collection links
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/screens/queries/Search.tsx
Labels: automerge

#10857 chore(j-s): Invalid Prosecutor
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
Labels: automerge

#10876 chore(Application-system): Adding datatestid for application system e2e tests.
  libs/application/ui-components/src/components/ApplicationCard/ApplicationCard.tsx
Labels: automerge

#10860 chore(j-s): Unhide Indictments
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/types/src/lib/feature.ts
Labels: automerge

#10896 feat(ids-admin): Collapsable ContentCard
  libs/portals/admin/ids-admin/src/components/Client/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/components/Client/Delegation.tsx
  libs/portals/admin/ids-admin/src/shared/components/ConditionalWrapper.tsx
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.css.ts
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx
Labels: automerge

#10890 feat(auth): Add consents to auth domain with mocked data.
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/dto/consentsPaginated.response.ts
  libs/api/domains/auth/src/lib/models/consent.model.ts
  libs/api/domains/auth/src/lib/models/consentScope.model.ts
  libs/api/domains/auth/src/lib/models/consentScopeGroup.model.ts
  libs/api/domains/auth/src/lib/models/consentScopeTreeNode.model.ts
  libs/api/domains/auth/src/lib/models/index.ts
  libs/api/domains/auth/src/lib/models/scopePermissions.model.ts
  libs/api/domains/auth/src/lib/resolvers/consent.resolver.ts
  libs/api/domains/auth/src/lib/resolvers/index.ts
  libs/api/domains/auth/src/lib/resolvers/scopePermissions.resolver.ts
  libs/api/domains/auth/src/lib/services/consent.service.ts
  libs/api/domains/auth/src/lib/services/scopePermissions.service.ts
Labels: automerge

#10897 feat(license-api): add missing ids server url env
  apps/services/license-api/infra/license-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#10893 fix(consultation-portal): changing nextauth_url and identity_server_issuer_domain in infra
  apps/consultation-portal/infra/samradsgatt.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#10888 chore(service-portal): Update translation loading for modules
  apps/service-portal/src/lib/modules.ts
  apps/service-portal/src/lib/routes.tsx
  apps/service-portal/src/screens/Dashboard/DashboardLoader.ts
  apps/service-portal/src/screens/Dashboard/module.tsx
  libs/service-portal/licenses/src/module.tsx
  libs/service-portal/licenses/src/screens/Translation.loader.ts
  libs/service-portal/vehicles/src/module.tsx
  libs/service-portal/vehicles/src/screens/Translation.loader.ts
Labels: automerge

#10892 fix(operating-license): Clear up confusion on VAT input
  libs/application/templates/operating-license/src/lib/dataSchema.ts
  libs/application/templates/operating-license/src/lib/messages.ts
Labels: automerge

#10894 feat(license-api): add audit namespace
  apps/services/license-api/src/app/modules/license/license.controller.ts
Labels: automerge

#10891 fix(application-system): Allow undefined values in readyforproduction in template
  apps/application-system/api/src/app/modules/application/e2e/application.spec.ts
  apps/application-system/api/src/app/modules/application/e2e/applicationTemplateValidation.spec.ts
  apps/application-system/api/src/app/modules/application/tools/applicationTemplateValidation.service.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/criminal-record/src/lib/CriminalRecordTemplate.ts
  libs/application/templates/data-protection-complaint/src/lib/DataProtectionComplaintTemplate.ts
  libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
  libs/application/templates/driving-assessment-approval/src/lib/DrivingAssessmentApprovalTemplate.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/family-matters/children-residence-change/src/lib/ChildrenResidenceChangeTemplate.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/funding-government-projects/src/lib/FundingGovernmentProjectsTemplate.ts
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
  libs/application/templates/institution-collaboration/src/lib/template.ts
  libs/application/templates/login-service/src/lib/LoginServiceTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/mortgage-certificate/src/lib/mortgageCertificateTemplate.ts
  libs/application/templates/no-debt-certificate/src/lib/noDebtCertificateTemplate.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#10870 ci: improve retagging, trigger docker-build on label
  scripts/ci/_retag.sh
  scripts/ci/retag-unaffected.sh
Labels: automerge

#10855 feat(j-s): Court appeal received notifications
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230418110017-update-notification.js
  apps/judicial-system/backend/migrations/20230418173949-update-case.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealReceivedByCourtNotifications.spec.ts
  apps/judicial-system/backend/test/setup.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web-e2e/src/fixtures/transitionCaseMutationResponse.json
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/limitedAccessTransitionCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/transitionCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.spec.ts
  libs/judicial-system/types/src/lib/case.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#10898 fix(j-s): Format appeal alert banner date
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
Labels: automerge

#10900 feat(consultation-portal): expandable list for stakeholders
  apps/consultation-portal/components/Advices/Advices.tsx
  apps/consultation-portal/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/pages/mal/[slug].tsx
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/types.tsx
  apps/consultation-portal/types/interfaces.ts
  apps/consultation-portal/types/viewModels.ts
Labels: automerge

#10899 chore(web): Remove Directorate of Immigration watson chat user name and email prompt
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/Organization/Wrapper/config.ts
Labels: automerge

#10905 feat: add email verified page
  apps/consultation-portal/pages/user/[slug].tsx
Labels: automerge

#10907 fix(consultation-portal): changing next auth url
  apps/consultation-portal/infra/samradsgatt.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#10909 feat(consultation-portal): Base path to _app
  apps/consultation-portal/pages/_app.tsx
Labels: automerge

#10910 chore(system-e2e): moving judicial-system tests to e separate location to be run independently
  apps/system-e2e/src/tests/judicial-system/smoke/restriction-case.spec.ts
Labels: automerge

#10911 fix(consultation-portal): Update environment.ts
  apps/consultation-portal/lib/environment.ts
Labels: automerge

#10727 feat(driving-learners-permit): Application initialized.
  .github/CODEOWNERS
  libs/api/domains/driving-license-book/src/drivinLicenceBook.type.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/disqualification.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/studentCanGetPracticePermit.input.ts
  libs/api/domains/driving-license/src/lib/graphql/models/studentCanGetPracticePermit.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-learners-permit/.babelrc
  libs/application/templates/driving-learners-permit/.eslintrc.json
  libs/application/templates/driving-learners-permit/babel-jest.config.json
  libs/application/templates/driving-learners-permit/codegen.yml
  libs/application/templates/driving-learners-permit/jest.config.js
  libs/application/templates/driving-learners-permit/project.json
  libs/application/templates/driving-learners-permit/src/dataProviders/index.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/ReviewSection/ReviewSection.css.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/ReviewSection/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-learners-permit/src/fields/LookupStudent/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/index.ts
  libs/application/templates/driving-learners-permit/src/forms/done.ts
  libs/application/templates/driving-learners-permit/src/forms/form/index.ts
  libs/application/templates/driving-learners-permit/src/forms/form/sectionFakeData.ts
  libs/application/templates/driving-learners-permit/src/graphql/index.ts
  libs/application/templates/driving-learners-permit/src/index.ts
  libs/application/templates/driving-learners-permit/src/lib/DrivingLearnersPermitTemplate.ts
  libs/application/templates/driving-learners-permit/src/lib/constants.ts
  libs/application/templates/driving-learners-permit/src/lib/dataSchema.ts
  libs/application/templates/driving-learners-permit/src/lib/messages.ts
  libs/application/templates/driving-learners-permit/src/lib/utils/formUtils.ts
  libs/application/templates/driving-learners-permit/src/lib/utils/index.ts
  libs/application/templates/driving-learners-permit/src/shared/constants.ts
  libs/application/templates/driving-learners-permit/src/shared/index.ts
  libs/application/templates/driving-learners-permit/src/shared/utils.ts
  libs/application/templates/driving-learners-permit/tsconfig.json
  libs/application/templates/driving-learners-permit/tsconfig.lib.json
  libs/application/templates/driving-learners-permit/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/institutionMapper.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge, high priority, merge.priority_merge_label

#10831 fix(inheritance-report): estate data inconsistencies for general purpose repeater
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
Labels: automerge

#10917 fix(consultation-portal): fixed environment file
  apps/consultation-portal/lib/environment.ts
Labels: automerge

#10919 fix: disabled mountebank for this release (#10745)
  infra/src/dsl/egress.spec.ts
  infra/src/dsl/kubernetes-runtime.ts
  infra/src/dsl/value-files-generators/helm.spec.ts
Labels: automerge, high priority

#10916 feat(driving-learners-permit): Application initialized. (#10727)
  .github/CODEOWNERS
  libs/api/domains/driving-license-book/src/drivinLicenceBook.type.ts
  libs/api/domains/driving-license-book/src/drivingLicenseBook.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/disqualification.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/studentCanGetPracticePermit.input.ts
  libs/api/domains/driving-license/src/lib/graphql/models/studentCanGetPracticePermit.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/driving-learners-permit/.babelrc
  libs/application/templates/driving-learners-permit/.eslintrc.json
  libs/application/templates/driving-learners-permit/babel-jest.config.json
  libs/application/templates/driving-learners-permit/codegen.yml
  libs/application/templates/driving-learners-permit/jest.config.js
  libs/application/templates/driving-learners-permit/project.json
  libs/application/templates/driving-learners-permit/src/dataProviders/index.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/ReviewSection/ReviewSection.css.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/ReviewSection/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-learners-permit/src/fields/LookupStudent/index.tsx
  libs/application/templates/driving-learners-permit/src/fields/index.ts
  libs/application/templates/driving-learners-permit/src/forms/done.ts
  libs/application/templates/driving-learners-permit/src/forms/form/index.ts
  libs/application/templates/driving-learners-permit/src/forms/form/sectionFakeData.ts
  libs/application/templates/driving-learners-permit/src/graphql/index.ts
  libs/application/templates/driving-learners-permit/src/index.ts
  libs/application/templates/driving-learners-permit/src/lib/DrivingLearnersPermitTemplate.ts
  libs/application/templates/driving-learners-permit/src/lib/constants.ts
  libs/application/templates/driving-learners-permit/src/lib/dataSchema.ts
  libs/application/templates/driving-learners-permit/src/lib/messages.ts
  libs/application/templates/driving-learners-permit/src/lib/utils/formUtils.ts
  libs/application/templates/driving-learners-permit/src/lib/utils/index.ts
  libs/application/templates/driving-learners-permit/src/shared/constants.ts
  libs/application/templates/driving-learners-permit/src/shared/index.ts
  libs/application/templates/driving-learners-permit/src/shared/utils.ts
  libs/application/templates/driving-learners-permit/tsconfig.json
  libs/application/templates/driving-learners-permit/tsconfig.lib.json
  libs/application/templates/driving-learners-permit/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/institutionMapper.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
  workspace.json
Labels: automerge

#10918 feat(admin-api): Get admin scopes endpoint
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/scopes.module.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.auth.spec.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth-api-lib/src/lib/resources/admin/dto/admin-scope.dto.ts
  libs/auth-api-lib/src/lib/resources/resources.module.ts
Labels: automerge

#10865 fix(estate): newest change requests in estate
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/GunsRepeater/index.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/fields/VehiclesRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstate/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/fields/HeirsOverview/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#10921 docs: Pósthólf skjalaveita cleanup
  handbook/technical-overview/postholf/postholf-03-interface-skjalaveita.md
  handbook/technical-overview/postholf/postholf-05-interfaces.md
Labels: automerge

#10920 fix(driving-learners-permit): Bugfixes
  libs/application/templates/driving-learners-permit/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-learners-permit/src/fields/LookupStudent/index.tsx
  libs/application/templates/driving-learners-permit/src/lib/DrivingLearnersPermitTemplate.ts
  libs/application/templates/driving-learners-permit/src/lib/dataSchema.ts
Labels: automerge

#10915 feat(island-ui): Color variants for dialog buttons
  libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.stories.tsx
  libs/island-ui/core/src/lib/DialogPrompt/DialogPrompt.tsx
Labels: automerge

#10922 feat(license-api): drivers license pkpass v2
  apps/services/license-api/infra/license-api.ts
  apps/services/license-api/src/app/modules/license/clients/disabilityLicense/index.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.config.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.module.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.type.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/index.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/pkpass/pkpass.client.ts
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/pkpass/pkpass.type.ts
  apps/services/license-api/src/app/modules/license/clients/firearmLicense/index.ts
  apps/services/license-api/src/app/modules/license/license.module.ts
  apps/services/license-api/src/app/modules/license/license.service.ts
  apps/services/license-api/src/app/modules/license/license.types.ts
  apps/services/license-api/src/app/modules/license/test/license.service.spec.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#10934 fix(license-api): fix config module loads
  apps/services/license-api/src/app/app.module.ts
  libs/clients/firearm-license/src/index.ts
  libs/clients/firearm-license/src/lib/openFirearmLicenseClient.config.ts
Labels: automerge

#10940 fix(consultation-portal): fix logout link
  apps/consultation-portal/lib/idsConfig.ts
Labels: automerge

#10941 feat(consultation-portal): backend download url
  apps/consultation-portal/components/ReviewCard/ReviewCard.tsx
  apps/consultation-portal/lib/environment.ts
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#10936 feat(admin-api): Add scopes option to update client
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/clients/clients.module.ts
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/services/auth/testing/src/fixtures/client.fixture.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#10945 fix(license-api): Hotfix - config module load
  apps/services/license-api/src/app/app.module.ts
  libs/clients/firearm-license/src/index.ts
  libs/clients/firearm-license/src/lib/openFirearmLicenseClient.config.ts
Labels: automerge

#10943 fix(service-portal): Update input padding on small inputs
  libs/service-portal/settings/personal-information/src/components/Forms/ProfileForm/components/Inputs/ProfileForms.css.ts
Labels: automerge

#10946 fix(consultation-portal): Kam 1134 fix authentication on dev
  apps/consultation-portal/next.config.js
Labels: automerge

#10949 fix(aod): dataschema tweak for pickRole
  libs/application/templates/announcement-of-death/src/lib/dataSchema.ts
Labels: automerge

#10950 feat(web): Added SliceDropdown content type
  apps/web/components/Organization/Slice/Render/SliceDropdown.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/sliceDropdown.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#10935 fix(service-portal): Modal sticky footer
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.css.ts
  libs/portals/shared-modules/delegations/src/components/access/AccessConfirmModal.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessDeleteModal/AccessDeleteModal.tsx
Labels: automerge

#10930 feat(j-s): Court of Appeal case screen
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230419130313-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/pages/landsrettur/kaera/[id].ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCaseGql.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#10948 feat: add request id
  apps/services/license-api/src/app/modules/license/dto/verifyLicense.dto.ts
  apps/services/license-api/src/app/modules/license/license.service.ts
Labels: automerge

#10846 feat(j-s): Case list for court of appeal
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/caseList/caseList.resolver.ts
  apps/judicial-system/api/src/app/modules/caseList/dto/caseList.input.ts
  apps/judicial-system/api/src/app/modules/caseList/interceptors/caseList.interceptor.ts
  apps/judicial-system/api/src/app/modules/caseList/models/caseList.model.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filters.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseListEntry.response.ts
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/pages/landsrettur/krofur.ts
  apps/judicial-system/web/src/components/BigTextSmallText/BigTextSmallText.tsx
  apps/judicial-system/web/src/components/SharedPageLayout/SharedPageLayout.css.ts
  apps/judicial-system/web/src/components/SharedPageLayout/SharedPageLayout.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/createCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/createCourtCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/extendCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/limitedAccessTransitionCaseGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  apps/judicial-system/web/src/utils/hooks/useCase/requestCourtRecordSignatureGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/sendNotificationGql.ts
  apps/judicial-system/web/src/utils/hooks/useCase/transitionCaseGql.ts
  apps/judicial-system/web/src/utils/mutations.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#10960 fix(j-s): Force update appeal judges
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
Labels: automerge

#10957 fix(j-s): Side panel for court of appeal
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#10953 feat(j-s): Court of Appeal ruling screen
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230427112248-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/pages/landsrettur/urskurdur/[id].ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#10962 fix: resource tweeks across multiple apps
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/delegation-api/infra/delegation-api.ts
  apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
  apps/services/auth/personal-representative/infra/personal-representative.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#10963 fix(parental-leave): expected date for foster car and adoption
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
Labels: automerge

#10961 fix(portals-core): Fix navigation tree
  libs/portals/core/src/components/PortalNavigation/PortalNavigation.tsx
Labels: automerge

#10965 fix(portals-shared-modules-delegations): Modal body scroll
  libs/portals/shared-modules/delegations/src/components/Modal/Modal.tsx
Labels: automerge

#10964 fix(auth-admin): Fix isDirty reset
  libs/portals/admin/ids-admin/src/shared/components/ContentCard.tsx
Labels: automerge

#10966 fix(j-s): Add rulingDate to CaseList Query
  apps/judicial-system/web/src/utils/mutations.ts
Labels: automerge

#10969 fix(passport-application): sort delivery addresses
  libs/application/template-api-modules/src/lib/modules/templates/passport/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
Labels: automerge
