Repository island-is/island.is, pull requests merged in 2023-06, with the labels that each got.

#11314 fix(consultation-portal): Kam 1332 documents and additional documents can now be also links
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocuments.tsx
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocumentsSkeleton.css.ts
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocumentsSkeleton.tsx
  apps/consultation-portal/screens/Case/utils/index.ts
  apps/consultation-portal/screens/Case/utils/isDocumentLink.ts
  apps/consultation-portal/types/interfaces.ts
  libs/api/domains/consultation-portal/src/lib/models/documentInfoResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#11322 feat(web): Hotfix - Add header and footer for HSA organization (#11309)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/index.ts
Labels: automerge

#11324 fix(j-s): Appeal in Court
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
Labels: automerge

#11238 feat(admin-portal-petition): Admin portal module for "Undirskriftalistar"
  .github/CODEOWNERS
  apps/portals/admin/src/auth.ts
  apps/portals/admin/src/lib/masterNavigation.ts
  apps/portals/admin/src/lib/modules.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/services/endorsements/api/src/environments/environment.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/portals/admin/petition/.babelrc
  libs/portals/admin/petition/.eslintrc.json
  libs/portals/admin/petition/README.md
  libs/portals/admin/petition/babel-jest.config.json
  libs/portals/admin/petition/codegen.yml
  libs/portals/admin/petition/jest.config.js
  libs/portals/admin/petition/project.json
  libs/portals/admin/petition/src/components/ExportList/downloadCSV.ts
  libs/portals/admin/petition/src/components/ExportList/index.tsx
  libs/portals/admin/petition/src/components/ExportList/styles.css.ts
  libs/portals/admin/petition/src/components/ListActions/LockList/index.tsx
  libs/portals/admin/petition/src/components/ListActions/LockList/lockList.graphql
  libs/portals/admin/petition/src/components/ListActions/UnlockList/index.tsx
  libs/portals/admin/petition/src/components/ListActions/UnlockList/unlockList.graphql
  libs/portals/admin/petition/src/components/ListActions/UpdateList/UpdateList.action.ts
  libs/portals/admin/petition/src/components/ListActions/UpdateList/updateList.graphql
  libs/portals/admin/petition/src/components/ListSignersTable/index.tsx
  libs/portals/admin/petition/src/components/ListSkeleton/index.tsx
  libs/portals/admin/petition/src/index.ts
  libs/portals/admin/petition/src/lib/messages.ts
  libs/portals/admin/petition/src/lib/navigation.ts
  libs/portals/admin/petition/src/lib/paths.ts
  libs/portals/admin/petition/src/lib/utils/types.ts
  libs/portals/admin/petition/src/lib/utils/utils.ts
  libs/portals/admin/petition/src/module.tsx
  libs/portals/admin/petition/src/screens/Overview/Overview.loader.ts
  libs/portals/admin/petition/src/screens/Overview/getAllEndorsementsLists.graphql
  libs/portals/admin/petition/src/screens/Overview/index.tsx
  libs/portals/admin/petition/src/screens/PetitionList/PetitionList.loader.ts
  libs/portals/admin/petition/src/screens/PetitionList/getEndorsements.graphql
  libs/portals/admin/petition/src/screens/PetitionList/getSinglePetitionList.graphql
  libs/portals/admin/petition/src/screens/PetitionList/index.tsx
  libs/portals/admin/petition/tsconfig.json
  libs/portals/admin/petition/tsconfig.lib.json
  libs/portals/admin/petition/tsconfig.spec.json
  libs/service-portal/petitions/src/lib/paths.ts
  libs/service-portal/petitions/src/module.tsx
  libs/service-portal/petitions/src/screens/PetitionsAdmin/index.tsx
  libs/service-portal/petitions/src/screens/ViewPetitionAdmin/index.tsx
  tsconfig.base.json
  workspace.json
Labels: automerge

#11315 fix(web): a couple of minor tweaks for petitions
  apps/web/screens/PetitionView/PetitionSkeleton.tsx
  apps/web/screens/PetitionView/PetitionView.tsx
  apps/web/screens/PetitionView/queries.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
Labels: automerge

#11319 fix(transfer of vehicle ownership): application not submitted after all review
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/hasReviewerApproved.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/isLastReviewer.ts
Labels: automerge

#11327 fix(consultation-portal): Kam 1335 make changes in api and fe to reflect on changes in backend
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/Case.tsx
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Case/components/AdviceList/AdviceList.tsx
  apps/consultation-portal/types/interfaces.ts
  libs/api/domains/consultation-portal/src/lib/cases/cases.service.ts
  libs/api/domains/consultation-portal/src/lib/dto/postAdvice.input.ts
  libs/api/domains/consultation-portal/src/lib/dto/postCaseSubscriptionType.input.ts
  libs/api/domains/consultation-portal/src/lib/models/adviceResult.model.ts
  libs/api/domains/consultation-portal/src/lib/models/postCaseAdviceCommand.model.ts
  libs/api/domains/consultation-portal/src/lib/models/postCaseSubscriptionCommand.model.ts
  libs/api/domains/consultation-portal/src/lib/models/postUserSubscriptionsCommand.model.ts
  libs/api/domains/consultation-portal/src/lib/user/user.service.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#11271 feat(auth-admin): Default environment to highest available
  libs/api/domains/auth-admin/src/lib/client/clients.resolver.ts
  libs/portals/admin/ids-admin/src/hooks/useEnvironment.ts
Labels: automerge

#11333 chore(assets): Increase real estate assets timeout
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/assets/src/lib/assets.config.ts
Labels: automerge

#11241 chore(service-portal): Remove feature-flags
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/vehicles/src/module.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
Labels: automerge

#11334 chore(assets): Increase real estate assets timeout (hotfix)
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/assets/src/lib/assets.config.ts
Labels: automerge

#11312 feat(application-system): Update create charge flow
  apps/application-system/api/src/app/modules/application/charge/application-charge.service.ts
  apps/application-system/api/src/app/modules/application/e2e/payment/payment.service.spec.ts
  libs/application/api/payment/src/lib/payment.service.ts
  libs/application/api/payment/src/lib/types/paymentStatus.ts
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/payment/payment.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/clients/charge-fjs-v2/project.json
  libs/clients/charge-fjs-v2/src/clientConfig.json
  libs/clients/charge-fjs-v2/src/index.ts
  libs/clients/charge-fjs-v2/src/lib/chargeFjsV2Client.service.ts
  libs/clients/charge-fjs-v2/src/lib/chargeFjsV2Client.utils.ts
Labels: automerge

#11331 feat(j-s): Defender Cases Query
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getAllRolesRules.spec.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#11343 chore(application-system): Revise documentation
  libs/application/core/README.md
Labels: automerge

#11339 fix(j-s): Enables Case Correction After Appeal
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
Labels: automerge

#11330 fix(j-s): Adding step more specific step validation to court of appeal
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
Labels: automerge

#11335 fix(j-s): Adding a is restriction case check in court of appeal table
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
Labels: automerge

#11336 fix(web): Add org page to query for org subpage in search
  apps/web/screens/queries/Search.tsx
Labels: automerge

#11304 fix(application-operating-license): Case sensitive input
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#11348 fix(service-portal): Hotfix - fix message id (#11289)
  libs/service-portal/health/src/lib/navigation.ts
Labels: automerge

#11272 feat(ids-admin): Add permission dropdown
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/portals/admin/ids-admin/src/components/forms/AddPermissions/AddPermissions.tsx
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Client/components/AddPermissions/AddPermissions.css.ts
  libs/portals/admin/ids-admin/src/screens/Client/components/AddPermissions/AddPermissions.graphql
  libs/portals/admin/ids-admin/src/screens/Client/components/AddPermissions/AddPermissions.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Permissions.tsx
Labels: automerge

#11302 fix(island-ui): dropdown menu iconType
  libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
Labels: automerge

#11340 fix(consultation-portal): KAM-1135-add-backend-url-in-prod-environment
  apps/consultation-portal/lib/environment.ts
Labels: automerge

#11329 fix(consultation-portal): Fix/text in email bx
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/CaseEmailBox/CaseEmailActionBox.tsx
  apps/consultation-portal/screens/Case/components/CaseEmailBox/CaseEmailBox.tsx
Labels: automerge

#11346 feat(contentful-apps): Add custom contentful preview link app
  apps/contentful-apps/components/MideindTranslationSidebar/fieldUtils/index.tsx
  apps/contentful-apps/constants/index.ts
  apps/contentful-apps/pages/fields/article-subarticles-field.tsx
  apps/contentful-apps/pages/fields/content-type-notifications-field.tsx
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
  apps/contentful-apps/pages/sidebars/preview-link.tsx
Labels: automerge

#11354 feat(consultation-portal): Kam 1255 set up analytics in plausible if needed
  apps/consultation-portal/components/AppLayout/AppLayout.tsx
  apps/consultation-portal/pages/_document.tsx
Labels: automerge

#11355 fix(consultation-portal): change prod path
  apps/api/infra/api.ts
  charts/islandis/values.prod.yaml
Labels: automerge

#11357 chore(infra): Increase memory for judicial-system
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#11318 fix(j-s): Adding appeal state in all case list tables
  apps/judicial-system/web/src/components/TagAppealRuling/TagAppealRuling.tsx
  apps/judicial-system/web/src/components/TagAppealState/TagAppealState.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
Labels: automerge

#11360 chore(contentful-apps): Change subArticle preview link
  apps/contentful-apps/pages/sidebars/preview-link.tsx
Labels: automerge

#11361 chore(web): University studies header visual changes
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
Labels: automerge

#11352 fix(service-portal): Pdf petitions
  libs/application/templates/general-petition/src/fields/ListCreated/index.tsx
  libs/application/templates/general-petition/src/forms/done.ts
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/lib/utils.ts
  libs/service-portal/petitions/src/screens/Petitions/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/assets/island.png
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/assets/thjodskra.png
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/styles.css.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/service-portal/petitions/src/screens/hooks.ts
  package.json
  yarn.lock
Labels: automerge

#11363 chore(system-e2e): Service-portal inbox test stabilization
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
Labels: automerge

#11364 feat(web): Hotfix - university studies header
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/index.ts
Labels: automerge

#10974 feat(web): Icelandic Government Instutition Vacancies
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/FilterTag/FilterTag.css.ts
  apps/web/components/FilterTag/FilterTag.tsx
  apps/web/components/FilterTag/index.ts
  apps/web/components/real.ts
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/starfatorg/[id].ts
  apps/web/pages/starfatorg/index.ts
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.css.ts
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/index.ts
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/Organization/PublishedMaterial/utils.ts
  apps/web/screens/queries/IcelandicGovernmentInstitutionVacancies.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/icelandic-government-institution-vacancies/.eslintrc.json
  libs/api/domains/icelandic-government-institution-vacancies/README.md
  libs/api/domains/icelandic-government-institution-vacancies/jest.config.js
  libs/api/domains/icelandic-government-institution-vacancies/project.json
  libs/api/domains/icelandic-government-institution-vacancies/src/index.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacancies.input.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacanciesResponse.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacancyById.input.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacancyByIdResponse.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.module.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/models/icelandicGovernmentInstitutionVacancy.model.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
  libs/api/domains/icelandic-government-institution-vacancies/tsconfig.json
  libs/api/domains/icelandic-government-institution-vacancies/tsconfig.lib.json
  libs/api/domains/icelandic-government-institution-vacancies/tsconfig.spec.json
  libs/clients/icelandic-government-institution-vacancies/.eslintrc.json
  libs/clients/icelandic-government-institution-vacancies/README.md
  libs/clients/icelandic-government-institution-vacancies/jest.config.js
  libs/clients/icelandic-government-institution-vacancies/project.json
  libs/clients/icelandic-government-institution-vacancies/src/clientConfig.yaml
  libs/clients/icelandic-government-institution-vacancies/src/index.ts
  libs/clients/icelandic-government-institution-vacancies/src/lib/apiConfig.ts
  libs/clients/icelandic-government-institution-vacancies/src/lib/apiProvider.ts
  libs/clients/icelandic-government-institution-vacancies/src/lib/icelandicGovernmentInstitutionVacanciesClient.config.ts
  libs/clients/icelandic-government-institution-vacancies/src/lib/icelandicGovernmentInstitutionVacanciesClient.module.ts
  libs/clients/icelandic-government-institution-vacancies/tsconfig.json
  libs/clients/icelandic-government-institution-vacancies/tsconfig.lib.json
  libs/clients/icelandic-government-institution-vacancies/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: automerge

#11370 chore(web): Add namespace feature flag for vacancies list page
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
Labels: automerge, high priority

#11366 fix(consultation-portal): Kam 1347 text changes from haraldur
  apps/consultation-portal/components/ActionCard/ActionCard.tsx
  apps/consultation-portal/screens/Case/Case.json
  apps/consultation-portal/screens/Case/components/BlowoutList/BlowoutList.tsx
  apps/consultation-portal/screens/Home/components/Filter/components/Filterbox.tsx
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
  apps/consultation-portal/screens/Subscriptions/components/EmailBox/EmailBox.tsx
Labels: automerge

#11323 feat(ids-admin): Ids admin permission sync and refactor
  libs/portals/admin/ids-admin/src/components/ContentCard.tsx
  libs/portals/admin/ids-admin/src/components/DropdownSync/DropdownSync.tsx
  libs/portals/admin/ids-admin/src/components/EnvironmentHeader/EnvironmentHeader.tsx
  libs/portals/admin/ids-admin/src/components/FormCard.tsx
  libs/portals/admin/ids-admin/src/context/EnvironmentContext.tsx
  libs/portals/admin/ids-admin/src/hooks/useEnvironmentQuery.ts
  libs/portals/admin/ids-admin/src/hooks/useEnvironmentState.ts
  libs/portals/admin/ids-admin/src/hooks/useIntent.ts
  libs/portals/admin/ids-admin/src/hooks/useMultiEnvSupport.tsx
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/Client/ClientContext.tsx
  libs/portals/admin/ids-admin/src/screens/Client/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.action.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.schema.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.tsx
  libs/portals/admin/ids-admin/src/screens/Client/PublishClient/PublishClient.action.ts
  libs/portals/admin/ids-admin/src/screens/Client/PublishClient/PublishClient.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/ClientsUrl.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Delegation.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Lifetime.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Permissions.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Translations.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/EditPermission.action.ts
  libs/portals/admin/ids-admin/src/screens/Permission/EditPermission.schema.ts
  libs/portals/admin/ids-admin/src/screens/Permission/EditPermission.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/PermissionContext.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionAccessControl.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionBasicInfo.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionContent.tsx
  libs/portals/admin/ids-admin/src/types/dynamicEnvironmentResult.ts
  libs/portals/admin/ids-admin/src/utils/checkEnvironmentsSync.ts
  libs/portals/admin/ids-admin/src/utils/forms.ts
  libs/portals/admin/ids-admin/src/utils/getIntent.ts
  libs/portals/admin/ids-admin/src/utils/schemas.ts
  libs/portals/core/src/index.ts
  libs/portals/core/src/types/RouterActionResponse.ts
  libs/react-spa/shared/src/lib/validate.ts
Labels: automerge

#11270 feat(auth-admin): Require unique clientId on create
  apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
  libs/api/domains/auth-admin/src/lib/client/clients.resolver.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/client.input.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Client/Client.loader.ts
  libs/portals/admin/ids-admin/src/screens/Client/CreateClient/CreateClient.action.ts
  libs/portals/admin/ids-admin/src/screens/Client/CreateClient/CreateClient.graphql
  libs/portals/admin/ids-admin/src/screens/Client/CreateClient/CreateClient.tsx
Labels: automerge

#11367 fix(j-s): Fixing check in table and past cases sorting and alert banner date
  apps/judicial-system/web-e2e/src/fixtures/transitionCaseMutationResponse.json
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
Labels: automerge

#11372 fix(transfer of vehicle ownership): error if more than one co-owner
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11373 fix(transfer of vehicle ownership): error if more than one co-owner
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11342 fix(j-s): Updating placeholder for case number
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.strings.ts
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
Labels: automerge

#11380 fix(transfer of vehicle ownership): add console log when approving
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11371 fix(api): Use showdown instead of turndown for html to markdown conversion
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
  package.json
  yarn.lock
Labels: automerge, high priority, merge.priority_merge_label

#11383 fix(ehic): Api changes, fixing web accordingly
  libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
  libs/application/templates/european-health-insurance-card/src/fields/CompletedScreen/CompletedScreen.tsx
  libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardForm.tsx
  libs/application/templates/european-health-insurance-card/src/forms/NoApplicants.tsx
  libs/application/templates/european-health-insurance-card/src/lib/helpers/applicantHelper.ts
  libs/application/templates/european-health-insurance-card/src/lib/types/index.ts
  libs/clients/ehic-client-v1/src/openapi.json
Labels: automerge

#11387 fix(transfer of vehicle ownership): revert add console log when approving
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11374 fix(estate): Latest updates
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/attachments.ts
  libs/application/templates/estate/src/fields/Cards/index.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/forms/sharedSections/testamentInfo.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#11353 fix(j-s): Defender Access
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseDefender.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/limitedAccessCaseReceived.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/requestSharedWithDefender.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/caseDefenderGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessCaseReceivedGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/requestSharedWithDefenderGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.strings.ts
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseFilesOverview/CaseFilesOverview.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseFilesOverview/CaseFilesOverview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CopyLinkForDefenderButton/CopyLinkForDefenderButton.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/index.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
Labels: automerge

#11390 fix(transfer-of-vechicle-ownership): negative number validation
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
Labels: automerge

#11392 fix(transfer-of-vechile-ownership): negative number validation
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
Labels: automerge

#11399 fix(web-api): Add jsdom package to api
  apps/api/esbuild.json
Labels: deploy-feature

#11400 fix(parental-leave): Added employers obj to employerAppr write access
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#11401 fix(j-s): Feature hiding tag appeal state for now
  apps/judicial-system/web/src/components/TagAppealState/TagAppealState.tsx
Labels: automerge

#11388 fix(transfer of vehicle ownership): revert add console log when approving
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11369 feat(j-s): Defender Case List
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealCompletedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealReceivedByCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealStatementNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealToCourtOfAppealsNotifications.spec.ts
  apps/judicial-system/web-e2e/src/integration/Defender/Indictements/overview.spec.ts
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/pages/verjandi/krafa/[id].ts
  apps/judicial-system/web/pages/verjandi/krofur.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/components/Table/CourtCaseNumber/CourtCaseNumber.css.ts
  apps/judicial-system/web/src/components/Table/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/components/Table/DefendantInfo/DefendantInfo.css.ts
  apps/judicial-system/web/src/components/Table/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.spec.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/DefenderCasesTable.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/useFilterCases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/useSortCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PastCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/utils.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/utils.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#11406 fix(j-s): Adding no-cache to appealed cases query
  apps/judicial-system/web/src/routes/CourtOfAppeal/Cases/Cases.tsx
Labels: automerge

#11300 fix(web): Update OpenApi Schema for Directorate of Fisheries calculator endpoints
  libs/clients/fiskistofa/src/clientConfig.json
  libs/clients/fiskistofa/src/lib/types.ts
  libs/clients/fiskistofa/src/lib/utils.ts
Labels: automerge

#11376 fix(j-s): Updating strings on defender screen and allowing defenders for indictment cases to see all files
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Defender/Defender.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Defender/Defender.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
Labels: automerge

#11379 test(system-e2e): Ids admin e2e tests
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/admin-portal.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-application.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-applications.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-permission.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-permissions.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenants.spec.ts
  apps/system-e2e/src/utils/pageHelpers.ts
  libs/island-ui/core/src/lib/Button/Button.tsx
  libs/island-ui/core/src/lib/Table/Table.tsx
  libs/portals/admin/ids-admin/src/components/FormCard.tsx
  libs/portals/admin/ids-admin/src/components/IdsAdminCard/IdsAdminCard.tsx
  libs/portals/admin/ids-admin/src/index.ts
  libs/portals/admin/ids-admin/src/module.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/AdvancedSettings.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/BasicInfo.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/Permissions.tsx
  libs/portals/admin/ids-admin/src/screens/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/screens/Permissions/Permissions.tsx
  libs/portals/admin/ids-admin/src/screens/Tenants/Tenants.tsx
Labels: automerge

#11410 Feat/old age pension periods
  SUMMARY.md
  libs/application/templates/old-age-pension/src/fields/Period/index.tsx
  libs/application/templates/old-age-pension/src/fields/Period/period.css.ts
  libs/application/templates/old-age-pension/src/fields/index.ts
  libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/old-age-pension/src/lib/answerValidators.ts
  libs/application/templates/old-age-pension/src/lib/constants.ts
  libs/application/templates/old-age-pension/src/lib/dataSchema.ts
  libs/application/templates/old-age-pension/src/lib/messages.ts
  libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
  libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#11391 test(system-e2e): Service portal consents e2e test
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control-consents.spec.ts
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx
  libs/service-portal/consent/src/screens/Consent/Consent.tsx
Labels: automerge

#11413 fix(ehic): Null pointer fix, unique nationalId array
  libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
  libs/application/templates/european-health-insurance-card/src/fields/CompletedScreen/CompletedScreen.tsx
Labels: automerge

#11407 feat(j-s): When assigning new user using national registry for finding name
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
Labels: automerge

#11409 fix(consultation-portal): Move BACKEND_DL_URL to infra
  apps/consultation-portal/infra/samradsgatt.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#11417 add validators for periods
  libs/application/templates/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/old-age-pension/src/lib/answerValidators.spec.ts
  libs/application/templates/old-age-pension/src/lib/answerValidators.ts
  libs/application/templates/old-age-pension/src/lib/constants.ts
  libs/application/templates/old-age-pension/src/lib/messages.ts
  libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#11411 fix(estate): Final touches on "Seta í óskiptu búi"
  libs/application/templates/estate/src/fields/Cards/index.tsx
  libs/application/templates/estate/src/fields/NotFilledOut/index.tsx
  libs/application/templates/estate/src/fields/index.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
Labels: automerge

#11412 feat(smart-solutions): improve smart logging
  libs/clients/smartsolutions/src/lib/smartSolutions.api.ts
Labels: automerge

#11414 chore(j-s): Defender Notifications
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#11403 fix(j-s): File Open Errors
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.spec.tsx
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/PdfButton/PdfButton.css.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
Labels: automerge

#11422 chore(web): Change width of University studies header for larger screens
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
Labels: automerge

#11382 fix(tests): Fix timeouts in CI tests
  .github/workflows/pullrequest.yml
  scripts/ci/_chunk.js
  scripts/ci/_nx-affected-targets.sh
Labels: automerge

#11385 fix(general-petition): Adding users phone and email to the form
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/createEndorsementList/createEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/interceptors/endorsementList.interceptor.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/interceptors/endorsementList.mask.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/interceptors/endorsementLists.interceptor.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-petition/general-petition.service.ts
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts
  libs/application/templates/general-petition/src/lib/dataSchema.ts
  libs/application/templates/general-petition/src/lib/messages.ts
Labels: automerge

#11415 feat(application-estate): Generate PDF of form data to send to DC
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#11421 feat(passport): Iterating national registry template api module and addressing passport application edge cases
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
  libs/application/templates/alcohol-tax-redemption/src/lib/AlcoholTaxRedemptionTemplate.ts
  libs/application/templates/alcohol-tax-redemption/src/lib/messages/prerequisites.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/fields/PaymentCharge/index.tsx
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
  libs/application/templates/passport/src/lib/error.ts
  libs/application/templates/passport/src/lib/utils.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/national-registry-user.ts
  libs/clients/passports/src/lib/passportsApi.service.ts
Labels: automerge, high priority

#11420 fix(j-s): Display loading table for defender cases
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/DefenderCasesTable.tsx
Labels: automerge

#11425 fix(estate): Seta í óskiptu búi final tweak
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#11429 fix(admin-portal): Petitions texts
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/portals/admin/petition/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
Labels: automerge

#11428 fix(general-petition): Copy link toast
  libs/application/core/src/lib/messages.ts
  libs/application/templates/general-petition/src/fields/ListCreated/index.tsx
  libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/application/ui-components/src/components/CopyLink/CopyLink.tsx
Labels: automerge

#11431 fix(service-portal): Pdf download fix
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
  libs/application/templates/general-petition/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
Labels: automerge

#11288 feat(endorsement-system): SystemE2E-tests
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/endorsements.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/endorsement-list.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/endorsements.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts
Labels: automerge

#11435 chore(service-portal): Skip outbound link track childview
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
Labels: automerge

#11436 fix(service-portal): Add air discount description
  libs/service-portal/air-discount/src/lib/navigation.ts
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge, high priority, merge.priority_merge_label

#11441 fix(consultation-portal): FocusableBox component as button
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Subscriptions/components/CardGridContainer/CardGridContainer.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionCard/SubscriptionCard.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/components/SubscriptionTableItem/SubscriptionTableItem.tsx
Labels: automerge

#11438 chore(service-portal): university data display
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
Labels: automerge

#11434 fix(service-portal): Petitions final spin
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/portals/admin/petition/src/lib/messages.ts
  libs/service-portal/petitions/src/lib/messages.ts
  libs/service-portal/petitions/src/screens/Petitions/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
Labels: automerge

#11446 fix(passport-template): passport use payment from paymentApi
  libs/application/templates/passport/src/fields/PaymentCharge/index.tsx
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/lib/utils.ts
Labels: automerge

#11448 fix(driving-learners-permit): Hook up error messages to descriptors
  libs/application/templates/driving-learners-permit/src/fields/LookupStudent/index.tsx
Labels: automerge

#11450 fix(national-registry): national registry requested that we get age from date of birth
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
Labels: automerge

#11445 feat(web): Fix starfatorg pagination
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
Labels: automerge, deploy-feature

#11444 feat(web): Fix haskolanam header scaling
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
Labels: automerge, deploy-feature

#11424 test(system-e2e): Disable/fix broken tests
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-unauthenticated.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/licenses.spec.ts
Labels: automerge

#11457 feat(web): Hotfix - University studies header scaling
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
Labels: automerge

#11451 fix(service-portal): sp petition pdf change
  apps/service-portal/src/assets/images/island.png
  apps/service-portal/src/assets/images/thjodskra.png
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
Labels: automerge, deploy-feature

#11454 fix(access-control): Fix formatMessage syntax so extract-strings works.
  libs/portals/shared-modules/delegations/src/screens/AccessControl.tsx
Labels: automerge

#11426 feat(ids-api): Add endpoint for sending sms.
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/ids-api/src/app/app.module.ts
  apps/services/auth/ids-api/src/app/notifications/dto/sms-message.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.controller.spec.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.controller.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.module.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.service.ts
  apps/services/auth/ids-api/src/environments/environment.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#11453 feat(summer-of-perf): Connection pooling for website requests
  apps/web/graphql/client.ts
  apps/web/next.config.js
  libs/clients/middlewares/README.md
  libs/clients/middlewares/src/lib/createEnhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/createEnhancedFetch.ts
  libs/clients/middlewares/src/lib/e2e/enhancedFetch.spec.ts
  libs/clients/middlewares/src/lib/withAgent.ts
  libs/cms/src/lib/contentful.repository.ts
  libs/nest/feature-flags/src/lib/feature-flag.client.ts
  libs/shared/constants/src/index.ts
  libs/shared/constants/src/lib/agent.ts
Labels: automerge

#11459 test(system-e2e): Fix delegation test failure
  apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts
Labels: automerge

#11470 fix(consultation-portal): wrong url in staging in infra
  apps/consultation-portal/infra/samradsgatt.ts
  charts/islandis/values.staging.yaml
Labels: automerge

#11472 feat(web): Hotfix - Add new background for tengjum rikid event slice
  apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx
Labels: automerge

#11467 fix(service-portal): Update inbox e2e test fix
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.tsx
Labels: automerge

#11468 feat(web): Add new background for tengjum rikid event slice
  apps/web/components/Organization/Slice/EventSlice/EventSlice.tsx
Labels: automerge

#11452 feat(service-desk): Create Service-desk module
  apps/portals/admin/src/auth.ts
  apps/portals/admin/src/lib/masterNavigation.ts
  apps/portals/admin/src/lib/modules.ts
  libs/auth-api-lib/seeders/data/scope-service-desk.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/portals/admin/service-desk/.babelrc
  libs/portals/admin/service-desk/.eslintrc.json
  libs/portals/admin/service-desk/README.md
  libs/portals/admin/service-desk/jest.config.js
  libs/portals/admin/service-desk/project.json
  libs/portals/admin/service-desk/src/index.ts
  libs/portals/admin/service-desk/src/lib/messages.ts
  libs/portals/admin/service-desk/src/lib/navigation.ts
  libs/portals/admin/service-desk/src/lib/paths.ts
  libs/portals/admin/service-desk/src/module.tsx
  libs/portals/admin/service-desk/src/screens/service-desk.tsx
  libs/portals/admin/service-desk/tsconfig.json
  libs/portals/admin/service-desk/tsconfig.lib.json
  libs/portals/admin/service-desk/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: automerge

#11473 fix(consultation-portal): hotfix change staging url next-auth
  apps/consultation-portal/infra/samradsgatt.ts
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#11471 fix(island-ui): add is translation + radio field fix
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/shared/utils/src/lib/countries.ts
Labels: automerge

#11476 fix(old-age-pension): unitest and format
  libs/application/templates/old-age-pension/jest.config.js
  libs/application/templates/old-age-pension/src/dataProviders/index.ts
  libs/application/templates/old-age-pension/src/fields/ResidenceHistory/index.tsx
  libs/application/templates/old-age-pension/src/fields/Review/index.tsx
  libs/application/templates/old-age-pension/src/fields/Review/review-groups/props.ts
  libs/application/templates/old-age-pension/src/hooks/useApplicationAnswers.ts
  libs/application/templates/old-age-pension/src/hooks/useStatefulAnswers.ts
  libs/application/templates/old-age-pension/src/index.ts
  libs/application/templates/old-age-pension/src/lib/answerValidators.spec.ts
  libs/application/templates/old-age-pension/src/lib/constants.ts
  libs/application/templates/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
  libs/application/templates/old-age-pension/tsconfig.json
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#11442 feat(portals): Add custom pageview props for entities
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/portals/core/src/screens/ModuleRoute.tsx
  libs/portals/core/src/utils/plausible.ts
  libs/service-portal/core/src/hooks/usePlausibleDetailPageview/usePlausibleDetailPageview.ts
Labels: automerge

#11377 fix(j-s): Change "seen by" to "opened by" defender
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230607135600-update-case.js
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getById.spec.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/overview.spec.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/overview.ts
  apps/judicial-system/web/messages/InvestigationCases/Prosecutor/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/overview.ts
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#11419 feat(j-s): Activate Defendant Court Updates
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/deliverDefendantToCourt.spec.ts
  charts/judicial-system/values.prod.yaml
Labels: automerge

#11461 fix(j-s): Use unique defenders for ruling notifications
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#11478 fix(j-s): Filter Active and Completed case tables at the same time
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/FilterCheckboxes.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/components/FilterCheckboxes.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/hooks/useFilterCases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/hooks/useSortCases.tsx
Labels: automerge

#11479 fix(service-portal): Don't translate the names in service-portal
  apps/service-portal/src/components/Greeting/Greeting.tsx
  libs/island-ui/core/src/lib/Text/Text.tsx
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/components/FamilyMemberCard/FamilyMemberCard.tsx
  libs/service-portal/information/src/screens/Company/CompanyInfo.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/licenses/src/components/PassportLicense/PassportLicense.tsx
  libs/service-portal/licenses/src/components/SingleLicenseCard/SingleLicenseCard.tsx
  libs/service-portal/licenses/src/screens/PassportDetail/PassportDetail.tsx
  libs/shared/components/src/auth/UserMenu/UserButton.tsx
  libs/shared/components/src/auth/UserMenu/UserDropdown.tsx
Labels: automerge

#11341 fix(j-s): Adding heading to defender overview site
  apps/judicial-system/web/messages/Core/defenderCaseOverview.ts
  apps/judicial-system/web/messages/Core/signedVerdictOverview.ts
  apps/judicial-system/web/src/components/OverviewHeader/OverviewHeader.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.strings.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/titleForCase/titleForCase.spec.ts
  apps/judicial-system/web/src/utils/titleForCase/titleForCase.strings.ts
  apps/judicial-system/web/src/utils/titleForCase/titleForCase.ts
Labels: automerge

#11408 fix(j-s): Updating subject on email to the prisons
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
Labels: automerge

#11477 fix(web): Vacancies list screen page number reset on filter
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
Labels: automerge

#11475 feat(ids-api): Disable delegations caching on dev and staging.
  apps/services/auth/ids-api/infra/identity-server.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#11458 fix(j-s): Fixing side panel on investigation cases
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#11482 fix(consultation-portal): Update api.ts
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#11492 fix(consultation-portal): Update consultationPortalClient.config.ts
  libs/clients/consultation-portal/src/lib/consultationPortalClient.config.ts
Labels: automerge, high priority

#11455 feat(summer-of-perf): Upgrade ioredis
  .yarn/patches/cache-manager-ioredis-yet-npm-1.1.0-da7d1a9865.patch
  .yarnrc.yml
  apps/air-discount-scheme/backend/src/app/modules/cache/cache.module.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/e2e/discount.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/flight.controller.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/test/e2e/flight.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/flight/test/unit/flight.controller.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/nationalRegistry/nationalRegistry.service.ts
  apps/air-discount-scheme/backend/src/app/modules/user/test/unit/user.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
  apps/air-discount-scheme/backend/types/global.d.ts
  apps/air-discount-scheme/web/i18n/withLocale.tsx
  apps/financial-aid/web-osk/src/components/AppProvider/AppProvider.tsx
  apps/reference-next-app/pages/_app.tsx
  apps/services/auth/admin-api/jest.config.js
  apps/services/auth/delegation-api/jest.config.js
  apps/services/auth/ids-api/jest.config.js
  apps/services/auth/personal-representative-public/jest.config.js
  apps/services/auth/personal-representative/jest.config.js
  apps/services/auth/public-api/jest.config.js
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.module.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/buildOpenApi.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/pkpass.client.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/application/templates/accident-notification/src/hooks/useLazyQuery.ts
  libs/application/templates/parental-leave/src/hooks/useLazyQuery.ts
  libs/application/templates/public-debt-payment-plan/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/hooks/useLazyQuery.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/hooks/useLazyQuery.ts
  libs/cache/src/index.ts
  libs/cache/src/lib/cache.module.ts
  libs/cache/src/lib/cache.ts
  libs/clients/middlewares/README.md
  libs/clients/middlewares/src/lib/withAutoAuth.spec.ts
  libs/clients/middlewares/src/lib/withAutoAuth.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/national-registry/v2/src/lib/apiConfiguration.ts
  libs/clients/national-registry/v2/src/lib/cache.ts
  libs/clients/rsk/company-registry/src/lib/apiConfiguration.ts
  libs/clients/rsk/procuring/src/lib/RskProcuringClient.ts
  libs/clients/rsk/procuring/src/lib/RskProcuringClientModule.ts
  libs/clients/rsk/procuring/src/lib/apiConfiguration.ts
  libs/clients/user-profile/src/lib/apiConfiguration.ts
  libs/financial-aid/shared/src/lib/useAsyncLazyQuery.ts
  libs/localization/src/lib/useLocalizedQuery.ts
  libs/localization/src/lib/withLocale.tsx
  libs/testing/nest/src/lib/hooks/useDatabase.ts
  package.json
  yarn.lock
Labels: automerge

#11489 fix(j-s): Appeal Statement Notifications
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#11500 fix(consultation-portal): Advices hotfix
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.css.ts
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Case/components/AdviceForm/AdviceForm.tsx
Labels: automerge

#11474 fix: Caching of hashed webpack assets
  scripts/dockerfile-assets/nginx/default.conf.template
Labels: automerge

#11488 fix(j-s): Feature hide appeal to court of appeals email
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#11506 feat(contentful-apps): Bypass cache for preview links
  apps/contentful-apps/pages/sidebars/preview-link.tsx
Labels: automerge

#11486 fix(ehic): check array length
  libs/application/template-api-modules/src/lib/modules/templates/european-health-insurance-card/european-health-insurance-card.service.ts
Labels: automerge

#11368 feat(web): Add header and footer for NTÍ organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts
Labels: automerge

#11502 fix(consultation-portal): KAM-1359-related-cases-sometimes-fails
  apps/consultation-portal/screens/Case/Case.tsx
Labels: automerge

#11505 fix(consultation-portal): text should have breaks
  apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
Labels: automerge

#11463 fix(estate): Estate refactor
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/templates/estate/src/fields/DoneImage/assets/Grieving.tsx
  libs/application/templates/estate/src/fields/DoneImage/index.tsx
  libs/application/templates/estate/src/forms/DivisionOfEstate/done.ts
  libs/application/templates/estate/src/forms/DivisionOfEstate/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/done.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/form.ts
  libs/application/templates/estate/src/forms/DivisionOfEstateByHeirs/overviewSection.ts
  libs/application/templates/estate/src/forms/Done.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/done.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/externalDataFields/propertiesFields.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/form.ts
  libs/application/templates/estate/src/forms/EstateWithoutAssets/overviewSection.ts
  libs/application/templates/estate/src/forms/Forms.ts
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
  libs/application/templates/estate/src/forms/OverviewSections/attachments.ts
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
  libs/application/templates/estate/src/forms/OverviewSections/confirmAction.ts
  libs/application/templates/estate/src/forms/OverviewSections/representative.ts
  libs/application/templates/estate/src/forms/Overviews.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/done.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/form.ts
  libs/application/templates/estate/src/forms/PermitToPostponeEstateDivision/overviewSection.ts
  libs/application/templates/estate/src/forms/Prerequisites.ts
  libs/application/templates/estate/src/forms/Sections/announcerInfo.ts
  libs/application/templates/estate/src/forms/Sections/approveSubmission.ts
  libs/application/templates/estate/src/forms/Sections/attachments.ts
  libs/application/templates/estate/src/forms/Sections/dataCollection.ts
  libs/application/templates/estate/src/forms/Sections/deceasedInfoFields.ts
  libs/application/templates/estate/src/forms/Sections/estateAssets.ts
  libs/application/templates/estate/src/forms/Sections/estateDebts.ts
  libs/application/templates/estate/src/forms/Sections/estateMembers.ts
  libs/application/templates/estate/src/forms/Sections/estateWithoutAssets.ts
  libs/application/templates/estate/src/forms/Sections/representative.ts
  libs/application/templates/estate/src/forms/Sections/spouseOfTheDeceased.ts
  libs/application/templates/estate/src/forms/Sections/testamentInfo.ts
  libs/application/templates/estate/src/forms/sharedSections/testamentInfo.ts
  libs/application/templates/estate/src/lib/EstateTemplate.ts
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge, deploy-feature

#11510 feat(web): Hotfix - Add header and footer for NTÍ organization (#11368)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/index.ts
Labels: automerge

#11509 feat(ids-api): Add decorators.
  apps/services/auth/ids-api/src/app/notifications/dto/sms-message.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.controller.spec.ts
Labels: automerge

#11517 feat(web): Hotfix - Adjust NTÍ header title height
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
Labels: automerge

#11514 fix(estate): cleanup
  libs/application/templates/estate/src/forms/Sections/spouseOfTheDeceased.ts
Labels: automerge

#11515 feat(web): Adjust NTÍ header title height
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
Labels: automerge

#11487 fix(ids-admin): Fixing two bugs in permissions
  libs/portals/admin/ids-admin/src/components/FormCard/FormCard.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/AddPermissions/AddPermissions.tsx
Labels: automerge

#11484 test(system-e2e): Fix broken tests
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/endorsements.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts
Labels: automerge

#11496 fix(j-s): updating signing button
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDocuments/CaseDocuments.tsx
Labels: automerge

#11513 fix(consultation-portal): text is weird if it is too long
  apps/consultation-portal/screens/Subscriptions/components/CardGridContainer/CardGridContainer.tsx
  apps/consultation-portal/screens/Subscriptions/components/ChosenSubscriptions/ChosenSubscriptions.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionCard/SubscriptionCard.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/SubscriptionTable.css.ts
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/components/SubscriptionTableHeader/SubscriptionTableHeader.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/components/SubscriptionTableItem/SubscriptionTableItem.css.ts
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/components/SubscriptionTableItem/SubscriptionTableItem.tsx
Labels: automerge

#11519 fix(consultation-portal): documents in box now also limited
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.css.ts
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Case/components/BlowoutList/BlowoutList.tsx
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocuments.tsx
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocumentsSkeleton.css.ts
  apps/consultation-portal/screens/Case/components/CaseDocuments/CaseDocumentsSkeleton.tsx
  apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.css.ts
  apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.tsx
  apps/consultation-portal/screens/Case/components/index.ts
  apps/consultation-portal/screens/Case/utils/renderDocFileName.ts
  apps/consultation-portal/utils/consts/consts.ts
Labels: automerge

#10678 feat(j-s): Update Court Case with Defendants
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extend.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/delete.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/update.spec.ts
Labels: automerge

#11522 fix(ehic): Add expiry date, exclude old card when applying for pdf if applying for new card
  libs/application/templates/european-health-insurance-card/src/forms/EuropeanHealthInsuranceCardForm.tsx
  libs/application/templates/european-health-insurance-card/src/forms/NoApplicants.tsx
  libs/application/templates/european-health-insurance-card/src/lib/helpers/applicantHelper.ts
  libs/application/templates/european-health-insurance-card/src/lib/messages.ts
Labels: automerge

#11528 test(system-e2e): Permit out-of-band auth & fixed tests
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/endorsements.spec.ts
Labels: automerge

#11532 revert(endorsement-system): NationalRegV2 update and municipali...
  apps/services/endorsements/api/src/app/app.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/createEndorsement.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/seed.js
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/findAllEndorsement/seed.js
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/endorsement.interceptor.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/endorsement.mask.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/paginatedEndorsement.interceptor.ts
  apps/services/endorsements/api/src/app/modules/endorsement/models/endorsementMetadata.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/web/screens/PetitionView/queries.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsementMetadata.model.ts
Labels: automerge

#11516 chore(dsl): Disable grantNamespaces for staging
  charts/identity-server/values.staging.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/types/output-types.ts
Labels: automerge

#11534 chore(j-s): Vestfirðir
  apps/judicial-system/backend/migrations/20230619193259-update-institution.js
  apps/judicial-system/backend/test/e2e.spec.ts
Labels: automerge

#11521 feat(j-s): Get police case info
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/police/dto/policeCaseInfo.input.ts
  apps/judicial-system/api/src/app/modules/police/index.ts
  apps/judicial-system/api/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/api/src/app/modules/police/police.resolver.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.controller.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/getPoliceCaseInfo.spec.ts
  apps/judicial-system/web/src/routes/Prosecutor/graphql/PoliceCaseInfo.graphql
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
Labels: automerge

#11523 feat(j-s): Court Email
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/migrations/20230616180244-update-institution.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.config.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealReceivedByCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealToCourtOfAppealsNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#11536 feat(endorsement-system): NationalRegV2 update take 2
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/src/app/app.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/createEndorsement.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/createEndorsement/seed.js
  apps/services/endorsements/api/src/app/modules/endorsement/e2e/findAllEndorsement/seed.js
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/endorsement.interceptor.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/endorsement.mask.ts
  apps/services/endorsements/api/src/app/modules/endorsement/interceptors/paginatedEndorsement.interceptor.ts
  apps/services/endorsements/api/src/app/modules/endorsement/models/endorsementMetadata.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/web/screens/PetitionView/queries.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/endorsement-system/src/lib/models/endorsementMetadata.model.ts
Labels: automerge

#11542 feat(license-service): fix driving license categories
  libs/api/domains/license-service/src/lib/client/driving-license-client/genericDrivingLicense.service.ts
  libs/api/domains/license-service/src/lib/client/driving-license-client/pkpass.client.ts
  libs/api/domains/license-service/src/lib/client/old-driving-license-client/oldGenericDrivingLicense.service.ts
  libs/api/domains/license-service/src/lib/client/old-driving-license-client/oldPkpass.client.ts
Labels: automerge
