Repository island-is/island.is, pull requests merged in 2023-08, with the labels that each got.

#11786 fix(parental-leave): give employers more rights to read application d…
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#11788 fix(contentful-apps): Adjust subarticles field height depending on item count
  apps/contentful-apps/pages/fields/article-subarticles-field.tsx
Labels: automerge

#11783 chore(search-indexer): Allow fetching entries that link to nested entries again
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#11674 refactor(j-s): GraphQL
  apps/judicial-system/api/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/web/src/components/SigningModal/RulingSignature.graphql
  apps/judicial-system/web/src/components/SigningModal/SigningModal.spec.tsx
  apps/judicial-system/web/src/components/SigningModal/SigningModal.tsx
  apps/judicial-system/web/src/components/SigningModal/getRulingSignatureConfirmation.graphql
  apps/judicial-system/web/src/components/SigningModal/requestRulingSignature.graphql
  apps/judicial-system/web/src/components/UserProvider/UserProvider.spec.tsx
  apps/judicial-system/web/src/components/UserProvider/UserProvider.tsx
  apps/judicial-system/web/src/components/UserProvider/getCurrentUser.graphql
  apps/judicial-system/web/src/components/UserProvider/gql.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/getPoliceCaseInfo.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/getIndictmentPoliceCaseFiles.graphql
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/getPoliceCaseFiles.graphql
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/index.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDocuments/CaseDocuments.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/CourtRecordSignature.graphql
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/getCourtRecordSignatureConfirmation.graphql
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/requestCourtRecordSignature.graphql
  apps/judicial-system/web/src/utils/hooks/useFileList/getSigendUrl.graphql
  apps/judicial-system/web/src/utils/hooks/useFileList/gql.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/limitedAccessGetigendUrl.graphql
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCount.graphql
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/createIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/deleteIndictmentCount.graphql
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/deleteIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/createFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/createPresignedPost.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/deleteFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/gql.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessCreateFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessCreatePresignedPost.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessDeleteFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/uploadPoliceCaseFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  apps/judicial-system/web/src/utils/mocks.ts
Labels: automerge

#11797 Fix/transfer vehicle ownership race condition
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11773 fix: datadog injection error
  .yarn/patches/dd-trace-npm-3.29.1-4e4e5d3a0c.patch
  apps/api/src/app/graphql.middleware.spec.ts
  libs/testing/containers/src/lib/testing-containers.ts
  package.json
  yarn.lock
Labels: automerge

#11575 feat(Application-system): Custom delegation support.
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/app/modules/application/application.controller.ts
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/e2e/applicationAccess.spec.ts
  apps/application-system/api/src/app/modules/application/guards/delegation.guard.ts
  apps/application-system/api/src/app/modules/application/tools/applicationAccess.service.ts
  apps/services/auth/public-api/project.json
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.ts
  libs/api/domains/application/src/lib/application.service.ts
  libs/api/domains/application/src/lib/dto/applicationApplications.input.ts
  libs/application/templates/general-fishing-license/src/lib/GeneralFishingLicenseTemplate.ts
  libs/application/types/src/lib/ApplicationTemplate.ts
  libs/auth-api-lib/src/lib/delegations/delegation-dto.mapper.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/delegations/dto/merged-delegation.dto.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation.model.ts
  libs/clients/auth/public-api/project.json
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/graphql/src/hooks/applications/useApplications.ts
Labels: automerge

#11776 fix(service-desk): Fix spelling in path
  libs/portals/admin/service-desk/src/lib/paths.ts
Labels: automerge

#11775 fix(consultation-portal): changed scope in apiScope
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#11692 chore(no-debt-certificate): e2e test for no debt certificate delegation
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/no-debt-certificate.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
Labels: automerge

#11806 chore: upgrade dd-trace
  package.json
  yarn.lock
Labels: automerge

#11713 feat(web): Plate availability search on public web
  apps/web/components/connected/vehicles/PlateAvailableSearch.css.ts
  apps/web/components/connected/vehicles/PlateAvailableSearch.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/screens/queries/PublicVehicleSearch.ts
  apps/web/utils/richText.tsx
  libs/api/domains/transport-authority/src/lib/graphql/dto/index.ts
  libs/api/domains/transport-authority/src/lib/graphql/dto/plateAvailability.input.ts
  libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
  libs/api/domains/transport-authority/src/lib/graphql/models/index.ts
  libs/api/domains/transport-authority/src/lib/graphql/models/plateAvailability.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/clients/transport-authority/vehicle-plate-renewal/src/lib/apiConfiguration.ts
  libs/clients/transport-authority/vehicle-plate-renewal/src/lib/vehiclePlateRenewalClient.service.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
Labels: automerge

#11774 feat(web): Aircraft registry public search
  .github/CODEOWNERS
  apps/web/components/connected/vehicles/AircraftSearch.tsx
  apps/web/screens/queries/AircraftSearch.ts
  charts/islandis/values.prod.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/aircraft-registry/src/lib/aircraftRegistry.resolver.ts
  libs/api/domains/aircraft-registry/src/lib/aircraftRegistry.service.ts
  libs/api/domains/aircraft-registry/src/lib/dto/allAircrafts.input.ts
  libs/clients/aircraft-registry/src/clientConfig.json
  libs/island-ui/core/src/lib/Pagination/Pagination.tsx
Labels: automerge

#11814 fix: do not use yarn set version
  scripts/ci/Dockerfile
Labels: automerge

#11815 console.log for development
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
Labels: automerge

#11816 chore(search-indexer-service): Temporarily disable nested entry fetching on dev
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#11818 fix(transfer vehicle ownership): submit and approve race condition
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getApproveAnswers.ts
Labels: automerge

#11821 fix(consultation-portal): KAM-1482-fix-login-click-back-and-logout
  apps/consultation-portal/hooks/useLogin.ts
  apps/consultation-portal/pages/_app.tsx
Labels: automerge

#11825 fix(contentful-apps): Subarticle url field validation
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
Labels: automerge

#11826 fix(core): Add @nestjs/axios in esbuild.json externalDependencies.
  apps/judicial-system/api/esbuild.json
  apps/judicial-system/backend/esbuild.json
  apps/services/user-notification/esbuild.json
Labels: automerge

#11778 chore(web): Remove unused project page field from query
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#11813 fix(search-indexer): Use id instead of slug as unique value for article categories
  libs/cms/src/lib/search/importers/articleCategory.service.ts
Labels: automerge

#11820 chore(web): Cache Vacancies api call for 10 minutes
  apps/web/utils/safelyExtractPathnameFromUrl.ts
  libs/api/domains/aircraft-registry/.eslintrc.json
  libs/api/domains/aircraft-registry/src/lib/models/aircraft.model.ts
  libs/api/domains/electronic-registration-statistics/.eslintrc.json
  libs/api/domains/electronic-registration-statistics/src/lib/models/brokenDownRegistrationStatistic.ts
  libs/api/domains/fiskistofa/.eslintrc.json
  libs/api/domains/fiskistofa/src/lib/dto/updateShipQuotaStatusForTimePeriod.input.ts
  libs/api/domains/fiskistofa/src/lib/dto/updateShipStatusForCalendarYear.input.ts
  libs/api/domains/fiskistofa/src/lib/dto/updateShipStatusForTimePeriod.input.ts
  libs/api/domains/fiskistofa/src/lib/models/quotaStatus.ts
  libs/api/domains/fiskistofa/src/lib/models/quotaType.ts
  libs/api/domains/fiskistofa/src/lib/models/shipBasicInfo.ts
  libs/api/domains/fiskistofa/src/lib/models/shipStatusInformation.ts
  libs/api/domains/fiskistofa/src/lib/models/singleShip.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacanciesResponse.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/dto/icelandicGovernmentInstitutionVacancyByIdResponse.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/models/icelandicGovernmentInstitutionVacancy.model.ts
  libs/api/domains/syslumenn/.eslintrc.json
  libs/api/domains/syslumenn/src/lib/models/paginatedOperatingLicenses.ts
Labels: automerge

#11827 fix(admin-portal): petitions wrong message
  libs/portals/admin/petition/src/screens/PetitionList/index.tsx
Labels: automerge

#11828 feat(license-api): add drivers license check
  apps/services/license-api/src/app/modules/license/clients/drivingLicense/drivingLicenseApiClient.service.ts
Labels: automerge

#11791 fix(j-s): Fix Delete Issue
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
Labels: automerge

#11801 feat(web): Add sign language button option to web
  apps/web/components/SignLanguageButton/SignLanguageButton.css.ts
  apps/web/components/SignLanguageButton/SignLanguageButton.tsx
  apps/web/components/real.ts
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/queries/Article.ts
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/article.model.ts
  libs/cms/src/lib/models/organizationSubpage.model.ts
  libs/cms/src/lib/models/subArticle.model.ts
  libs/island-ui/contentful/src/index.ts
  libs/island-ui/contentful/src/lib/EmbeddedVideo/EmbeddedVideo.tsx
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/SignLanguage.tsx
Labels: automerge

#11831 fix(service-portal): Fixes login error in portals on localhost
  libs/auth/react/src/lib/auth/AuthProvider.tsx
  libs/island-ui/storybook/config/main.js
  libs/react-spa/shared/src/hooks/useEffectOnce.ts
  libs/react-spa/shared/src/index.ts
Labels: automerge

#11834 fix(j-s): Court Date Email
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#11833 fix(web): Allow bypassing cache for web
  apps/web/graphql/client.ts
  apps/web/graphql/options.ts
  apps/web/graphql/withApollo.tsx
Labels: automerge

#11835 feat(web): Update NTÍ header image link
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
Labels: automerge

#11837 fix(cms): Include query params in relative url mapping
  libs/cms/src/lib/models/utils.ts
Labels: automerge

#11839 fix(web): useEffect returned values are causing errors on route change
  apps/web/components/IcelandicNamesSearcher/IcelandicNamesSearcher.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/hooks/useContentfulId.ts
  apps/web/hooks/usePlausible.ts
  apps/web/hooks/useViewport.ts
  apps/web/screens/AboutPage/Sidebar.tsx
  apps/web/screens/Adgerdir/components/AdgerdirArticles/AdgerdirArticles.tsx
  apps/web/screens/Adgerdir/components/CardsSlider/CardsSlider.tsx
  apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
  apps/web/screens/Organizations/Organizations.tsx
  apps/web/screens/Search/Search.tsx
Labels: automerge

#11836 fix(application-system): Delegations screen stuck in loading state
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge, deploy-feature

#11829 fix(web): Hydration error due to mismatch between server and client DOM
  apps/web/components/MobileAppBanner/MobileAppBanner.tsx
  libs/island-ui/core/src/lib/IconRC/Icon.tsx
Labels: automerge

#11841 fix(search-indexer): Update docker files for local development
  apps/services/search-indexer/dev-services/docker-compose.yml
  apps/services/search-indexer/dev-services/elasticsearch/Dockerfile
Labels: automerge

#11843 fix(application-dir): Exams passed filter
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
Labels: automerge

#11847 fix(application-dir): Exams filter
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
Labels: automerge

#11845 feat(auth-admin): Fixed text for custom claims
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Client/components/AdvancedSettings.tsx
Labels: automerge

#11849 feat(service-portal): vehicles UI changes
  libs/api/domains/vehicles/src/models/getVehicleDetail.model.ts
  libs/api/domains/vehicles/src/utils/basicVehicleInformationMapper.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/utils/amountFormat.ts
  libs/service-portal/core/src/utils/numberFormat.ts
  libs/service-portal/vehicles/src/lib/messages.ts
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
  libs/service-portal/vehicles/src/screens/Overview/Overview.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/utils/createUnits.ts
  libs/service-portal/vehicles/src/utils/displayWithUnit.ts
Labels: automerge

#11817 feat(search-indexer): Remove fields object from sync response to reduce memory usage
  libs/cms/src/lib/search/contentful.service.ts
Labels: automerge

#11755 feat(web): Óskalisti þjóðarinnar POC
  apps/web/pages/oskalisti-thjodarinnar/index.tsx
Labels: automerge, deploy-feature

#11855 chore(service-portal): Remove unused feature flags
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/air-discount/src/module.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/education/src/module.tsx
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
Labels: automerge

#11792 feat(j-s): Defender Email
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#11846 fix(j-s): Repaint happening on input
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/DefendantInfo/DefendantInfo.tsx
Labels: automerge

#11863 chore(search-indexer): Change env variable on dev
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#11864 fix(admin-portal): petitions loader limit
  libs/portals/admin/petition/src/screens/PetitionList/PetitionList.loader.ts
Labels: automerge

#11793 fix(j-s): Case Files
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/overview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/InvestigationCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Court/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Prosecutor/RestrictionCases/signedVerdictOverview.spec.ts
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
Labels: automerge

#11866 fix(application-p-sign): Translation namespace for dataprovider string
  libs/application/templates/p-sign/src/lib/messages.ts
Labels: automerge

#11705 chore(application-passport): Logging
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
Labels: automerge

#11854 feat(auth-admin): Allow empty custom claims
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
Labels: automerge

#11666 fix(island-ui): Remove redundant translate=yes
  libs/island-ui/core/src/lib/Text/Text.tsx
Labels: automerge

#11871 fix(admin-portal): Limit wrong query
  libs/portals/admin/petition/src/screens/PetitionList/PetitionList.loader.ts
Labels: automerge

#11870 fix(web): Vacancies added in CMS not showing up on overview page
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/search/importers/news.service.ts
Labels: automerge

#11875 fix(application-p-sign): Fix duplicate message id
  libs/application/templates/p-sign/src/lib/messages.ts
Labels: automerge

#11876 fix(admin-portal): Petition pdf stylingtweak
  libs/portals/admin/petition/src/components/ExportList/MyPdfDocument/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
Labels: automerge

#11874 fix(web): Published material page prop refetching loop
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
Labels: automerge

#11880 fix(admin-portal): Petititons csv export fix
  libs/portals/admin/petition/src/components/ExportList/downloadCSV.ts
  libs/portals/admin/petition/src/components/ExportList/index.tsx
  libs/portals/admin/petition/src/components/ListSignersTable/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
Labels: automerge

#11867 fix(j-s): Update case facts and legal arguments when case is resent
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
Labels: automerge

#11886 fix(web): Hotfix - Vacancies added in CMS not showing up on overview page (#11870)
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
Labels: automerge

#11881 feat(web): Add header for "geislavarnir-rikisins"
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/IcelandicRadiationSafetyAuthorityHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/IcelandicRadiationSafetyAuthorityHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/index.ts
Labels: automerge

#11799 feat(web): Section with video
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/sectionWithVideo.model.ts
  libs/cms/src/lib/unions/slice.union.ts
  libs/island-ui/contentful/src/lib/RichTextRC/RichText.tsx
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderComponents.tsx
  libs/island-ui/contentful/src/lib/SectionWithVideo/SectionWithVideo.tsx
  libs/island-ui/contentful/src/lib/richTextRendering.tsx
Labels: automerge

#11872 feat(service-portal): add icons
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/Expand.tsx
  libs/island-ui/core/src/lib/IconRC/icons/ExpandOutline.tsx
  libs/island-ui/core/src/lib/IconRC/icons/Pause.tsx
  libs/island-ui/core/src/lib/IconRC/icons/PauseCircle.tsx
  libs/island-ui/core/src/lib/IconRC/icons/PauseCircleOutline.tsx
  libs/island-ui/core/src/lib/IconRC/icons/PauseOutline.tsx
  libs/island-ui/core/src/lib/IconRC/icons/VolumeHigh.tsx
  libs/island-ui/core/src/lib/IconRC/icons/VolumeHighOutline.tsx
  libs/island-ui/core/src/lib/IconRC/icons/VolumeMute.tsx
  libs/island-ui/core/src/lib/IconRC/icons/VolumeMuteOutline.tsx
Labels: automerge

#11884 fix(application-dlp): Add logging
  libs/application/template-api-modules/src/lib/modules/templates/driving-learners-permit/driving-learners-permit.service.ts
Labels: automerge

#11784 chore: allow extending .envrc with .envrc.private
  .envrc
  .gitignore
Labels: automerge, high priority

#11877 fix(j-s): Notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealCompletedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealReceivedByCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealStatementNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealToCourtOfAppealsNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
Labels: automerge

#11890 fix(j-s): Specific subject for "ready for court" notifications in investigation cases
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#11893 fix(j-s): Reopen Case
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
Labels: automerge

#11894 fix(service-portal): Update locale date for vehicle screens
  libs/service-portal/vehicles/src/components/DetailTable/OwnersTable.tsx
  libs/service-portal/vehicles/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/HistoryTableData.tsx
  libs/service-portal/vehicles/src/screens/VehicleHistory/TabContent.tsx
  libs/service-portal/vehicles/src/utils/constants.ts
  libs/service-portal/vehicles/src/utils/createUnits.ts
  libs/service-portal/vehicles/src/utils/downloadVehicleOwnedFile.ts
  libs/service-portal/vehicles/src/utils/vehicleOwnedMapper.ts
Labels: automerge

#11899 fix(service-portal): Update finance loading in service portal
  libs/service-portal/finance/src/module.tsx
  libs/service-portal/finance/src/screens/FinanceRoutes.loader.ts
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: automerge

#11897 feat(web): Add default footer for organizations
  apps/web/components/Footer/Footer.css.ts
  apps/web/components/Footer/Footer.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/real.ts
Labels: automerge

#11896 chore(application-templates): Logging and small fixes
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/example-payment-actions/examplePaymentActions.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/public-debt-payment-plan/public-debt-payment-plan.service.ts
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/example-payment/src/lib/examplePaymentTemplate.ts
  libs/application/templates/operating-license/src/dataProviders/index.ts
  libs/application/templates/operating-license/src/lib/constants.ts
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/lib/constants.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/payment-catalog.ts
Labels: automerge

#11907 fix(core): Remove handbook from codeowners
  .github/CODEOWNERS
Labels: automerge

#11895 fix(j-s): Stop requiring session bookings
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#11905 feat(web): Add default footer for organizations (#11897)
  apps/web/components/Footer/Footer.css.ts
  apps/web/components/Footer/Footer.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/real.ts
Labels: automerge, high priority

#11910 fix(j-s): Sanitize filename before uploading to court
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  libs/judicial-system/formatters/src/lib/formatters.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#11902 chore(j-s): Hearing arrangements error message
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#11901 fix(j-s): Revoked investigation case sms text
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#11892 feat(local-e2e): Minor fixes
  apps/system-e2e/entrypoint.sh
  scripts/local-e2e.sh
Labels: automerge

#11906 fix(general-petition): Removing unused feature flags
  libs/application/templates/driving-instructor-registrations/src/lib/InstructorRegistrationsTemplate.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/application/templates/driving-school-confirmation/src/lib/DrivingSchoolConfirmationTemplate.ts
  libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/operating-license/src/lib/OperatingLicenseTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#11909 fix(ADS): Removing router from getinitialprops
  apps/air-discount-scheme/web/pages/_app.tsx
Labels: automerge, deploy-feature, high priority

#11857 feat(clients-driving-license-book): Student overview update
  libs/api/domains/driving-license-book/src/index.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenceBook.type.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenseBook.module.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenseBook.resolver.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenseBook.service.ts
  libs/api/domains/driving-license-book/src/lib/dto/createDrivingSchoolTestResult.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/createPracticalDrivingLesson.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/deletePracticalDrivingLesson.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/getPracticalDrivingLessons.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/student.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/students.input.ts
  libs/api/domains/driving-license-book/src/lib/dto/updatePracticalDrivingLesson.input.ts
  libs/api/domains/driving-license-book/src/lib/guards/drivingInstructor.guard.ts
  libs/api/domains/driving-license-book/src/lib/guards/drivingInstructorOrEmployee.guard.ts
  libs/api/domains/driving-license-book/src/lib/guards/drivingSchoolEmployee.guard.ts
  libs/api/domains/driving-license-book/src/lib/interceptors/studentId.interceptor.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingBookLesson.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingBookStudentOverview.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingLicenseBook.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingLicenseBookSchoolType.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingLicenseBookStudent.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingLicenseTestResult.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingSchool.response.ts
  libs/api/domains/driving-license-book/src/lib/models/drivingSchoolExam.response.ts
  libs/api/domains/driving-license-book/src/lib/models/practicalDrivingLesson.response.ts
  libs/api/domains/driving-license-book/src/lib/models/studentsTeacherNationalId.response.ts
  libs/api/domains/driving-license-book/src/lib/models/success.response.ts
  libs/api/domains/driving-license-book/src/lib/utils/drivingLicenseBookMapper.ts
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/graphql/queries.ts
  libs/clients/driving-license-book/src/clientConfig.json
  libs/clients/driving-license-book/src/lib/drivingLicenseBookType.types.ts
  libs/clients/driving-license-book/src/utils/mappers.ts
Labels: automerge

#11887 chore(j-s): Auto Regression Test
  apps/system-e2e/src/tests/judicial-system/custody-prosecutor.spec.ts
Labels: automerge

#11914 fix(application-driving-learners-permit): Correct charge
  libs/application/templates/driving-license-duplicate/src/fields/PaymentCharge/index.tsx
Labels: automerge

#11908 feat(ci): Add DD test integration to `main`
  .github/workflows/push.yml
  scripts/ci/30_test.sh
Labels: automerge

#11918 fix(ADS): Removing router from getinitialprops (#11909)
  apps/air-discount-scheme/web/pages/_app.tsx
Labels: automerge

#11920 feat(ci): Add DD test integration to `main` (#11908)
  .github/workflows/push.yml
  scripts/ci/30_test.sh
Labels: automerge

#11878 fix(transport authority): Get newest answers when submitting approval
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/Overview/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/Overview/index.tsx
Labels: automerge

#11911 feat(delegations): Fixed whitespace on confirm modal
  libs/portals/shared-modules/delegations/src/components/access/AccessConfirmModal.tsx
Labels: automerge

#11922 fix(service-portal): Update first reg date in get veichle search model
  libs/api/domains/vehicles/src/models/getVehicleSearch.model.ts
Labels: automerge

#11917 feat(web): Match institutions via reference identifier for vacancies
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.css.ts
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/models/icelandicGovernmentInstitutionVacancy.model.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/dto/getOrganizations.input.ts
  libs/cms/src/lib/models/organization.model.ts
Labels: automerge

#11925 fix(consultation-portal): KAM-1548-failed-test
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
Labels: automerge

#11929 feat(web): Hotfix - Match institutions via reference identifier for vacancies (#11917)
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.css.ts
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/models/icelandicGovernmentInstitutionVacancy.model.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/dto/getOrganizations.input.ts
  libs/cms/src/lib/models/organization.model.ts
Labels: automerge

#11930 chore(web): Hide frontpage news tag on latest news card
  apps/web/components/NewsItems/NewsItems.tsx
  apps/web/screens/queries/fragments.ts
Labels: automerge

#11931 chore(application-driving-license-duplicate): Update charge code
  libs/application/templates/driving-license-duplicate/src/fields/PaymentCharge/index.tsx
Labels: automerge

#11932 fix(island-ui): Adding lock opened icon
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/LockOpened.tsx
  libs/island-ui/core/src/lib/IconRC/icons/LockOpenedOutline.tsx
  libs/portals/admin/petition/src/screens/PetitionList/index.tsx
Labels: automerge

#11935 fix(island-ui): Adding aria-label for the span button
  libs/island-ui/core/src/lib/Button/Button.tsx
Labels: automerge

#11842 feat(j-s): Use new ids
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/modules/auth/auth.config.ts
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/auth/auth.module.ts
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
  apps/judicial-system/api/src/app/modules/index.ts
  apps/judicial-system/api/src/environments/environment.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#11912 chore(j-s): Use GraphQL generated Gender type
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.spec.tsx
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInput.tsx
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/components/Table/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Defender/SelectDefender.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.spec.ts
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
  apps/judicial-system/web/src/utils/hooks/useNationalRegistry/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#11939 fix(service-portal-e2e): Udpate ownership link in vehicle test
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
Labels: automerge

#11949 fix(application-dlp): Charge codes
  libs/application/templates/driving-license-duplicate/src/fields/PaymentCharge/index.tsx
Labels: automerge

#11951 fix(web): Convert numeric "stofnunNr" field to string for vacancy institutions
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
Labels: automerge

#11952 fix(web): Hotfix - Convert numeric "stofnunNr" field to string for vacancy institutions (#11951)
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/utils.ts
Labels: automerge

#11950 fix(j-s): Token verification and refactor
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
Labels: automerge

#11954 fix(web): Vacancy institution logo matching
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
Labels: automerge

#11868 feat(nest-audit): Add log to console options in audit module
  apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/secrets/me-client-secrets.controller.ts
  libs/nest/audit/README.md
  libs/nest/audit/src/lib/audit.service.spec.ts
  libs/nest/audit/src/lib/audit.service.ts
  libs/nest/audit/src/lib/audit.types.ts
Labels: automerge

#11956 chore(core): Fix broken links in root README
  README.md
Labels: automerge

#11953 fix(consultation-portal): Kam 1570 endless reload when logged in on prod
  apps/consultation-portal/.babelrc
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/Eyebrows/Eyebrows.tsx
  apps/consultation-portal/next.config.js
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Case/components/DocFileName/DocFileName.tsx
  apps/consultation-portal/screens/Error404/Error404.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/components/SubscriptionTableItem/SubscriptionTableItem.tsx
Labels: automerge

#11961 fix(service-portal): Hotfix - add included types to licenses query
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
Labels: automerge

#11960 fix(island-ui): Fix react datepicker media query quote mark.
  libs/island-ui/core/src/lib/DatePicker/react-datepicker.css.ts
Labels: automerge

#11947 chore(j-s): Don't allow clicking on current step of form stepper
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#11955 feat(service-portal): refactor rights portal api domain
  libs/api/domains/rights-portal/src/index.ts
  libs/api/domains/rights-portal/src/lib/models/aidsOrNutrition.model.ts
  libs/api/domains/rights-portal/src/lib/models/healthCenter.model.ts
  libs/api/domains/rights-portal/src/lib/models/therapies.model.ts
  libs/api/domains/rights-portal/src/lib/models/userDentist.model.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.module.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.resolver.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.types.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
  libs/clients/icelandic-health-insurance/rights-portal/src/index.ts
  libs/service-portal/health/src/components/TherapiesTabContent/TherapiesTabContent.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.graphql
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.graphql
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/Therapies/Therapies.graphql
  libs/service-portal/health/src/screens/Therapies/Therapies.tsx
Labels: automerge

#11923 feat(j-s): Show laws broken in indictment overviews
  apps/judicial-system/web/messages/Core/lawsBrokenAccordion.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsLawsBrokenAccordionItem/IndictmentsLawsBrokenAccordionItem.tsx
  apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
Labels: automerge

#11941 chore(j-s): Run Smoke Test in Pipeline
  apps/system-e2e/src/tests/judicial-system/smoke/custody-prosecutor.spec.ts
Labels: automerge

#11963 feat(j-s): Date field from LÖKE
  apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
  apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/getIndictmentPoliceCaseFiles.graphql
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/getPoliceCaseFiles.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  libs/judicial-system/types/src/lib/policeFile.ts
Labels: automerge

#11921 feat(j-s): RP initiated logout
  apps/judicial-system/api/src/app/modules/auth/auth.config.ts
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/web/graphql/errorLink.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/services/api.spec.ts
  apps/judicial-system/web/src/services/api.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#11971 fix(service-portal): formatting
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
Labels: automerge

#11975 fix(j-s): Add required fields to appealed cases CaseList query
  apps/judicial-system/web/src/utils/mutations.ts
Labels: automerge

#11972 fix(web): Change styling for NTí header
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
Labels: automerge

#11968 chore(j-s): Use generated caseLegalProvisions type in frontend
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/messages/Core/laws.ts
  apps/judicial-system/web/src/components/AccordionItems/PoliceRequestAccordionItem/PoliceRequestAccordionItem.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/laws.ts
Labels: automerge

#11969 chore(application-system-api): Remove xroad-proxy as explicit dependency in dev target
  apps/application-system/api/project.json
Labels: automerge

#11978 fix(web): Hotfix - load institution title if logo is missing (#11967)
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
Labels: automerge

#11974 fix(crc): Add missing overview
  libs/application/templates/family-matters/children-residence-change/src/fields/index.ts
Labels: automerge

#11976 chore(j-s): Use generated CaseCustodyRestrictions type
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/messages/Core/restrictions.ts
  apps/judicial-system/web/src/components/RestrictionTags/RestrictionTags.spec.tsx
  apps/judicial-system/web/src/components/RestrictionTags/RestrictionTags.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/restrictions.spec.tsx
  apps/judicial-system/web/src/utils/restrictions.ts
  apps/judicial-system/web/src/utils/stepHelper.ts
Labels: automerge

#11986 fix(application-system): Hot reload error screen
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
Labels: automerge

#11983 chore(j-s): GraphQL schema for Defendant operations
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/createDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/createDefendantt.graphql
  apps/judicial-system/web/src/utils/hooks/useDefendants/deleteDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/deleteDefendantt.graphql
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/updateDefendantGql.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/updateDefendantt.graphql
Labels: automerge, skip-nx-cache, skip-nodejs-cache

#11982 feat(web): Make SectionWithVideo title optional
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/SectionWithVideo/SectionWithVideo.tsx
  apps/web/components/SectionWithVideo/index.ts
  apps/web/components/real.ts
  apps/web/screens/LifeEvent/LifeEvent.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/sectionWithVideo.model.ts
  libs/island-ui/contentful/src/index.ts
Labels: automerge

#11998 fix(parental-leave): change max upload file size to 2MB
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#12002 fix(parental-leave): Parent could create new application for new baby
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts
Labels: automerge
