Repository island-is/island.is, pull requests merged in 2023-09, with the labels that each got.

#11993 fix(j-s): Form footer mobile styles
  apps/judicial-system/web/src/components/FormFooter/FormFooter.css.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/InfoBox/InfoBox.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
Labels: automerge

#11811 feat(ehic): Add history
  libs/application/templates/european-health-insurance-card/src/lib/template.ts
Labels: automerge

#11990 fix(general-fishing-license): Allow selecting ships when there are more than 6
  libs/application/templates/general-fishing-license/src/lib/dataSchema.ts
Labels: automerge

#12007 feat(web): Add new field to Form model
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/form.model.ts
Labels: automerge

#12008 fix(application-dsc): Update query type and filter driving schools
  libs/application/templates/driving-school-confirmation/src/fields/StudentInfo/index.tsx
  libs/application/templates/driving-school-confirmation/src/graphql/queries.ts
  libs/application/templates/driving-school-confirmation/src/types.ts
Labels: automerge

#12009 feat(application-system): buildExternalDataProvider markdown support for description field
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#12013 fix(clients-rsk-relationships): Add aranja as codeowners for relationships integration.
  .github/CODEOWNERS
Labels: automerge

#12011 feat(clients-middlewares): Create helper function to add header value to cache key for withCache
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/rsk/relationships/src/lib/RskRelationshipsClientConfig.ts
  libs/clients/rsk/relationships/src/lib/apiConfiguration.ts
Labels: automerge

#11992 fix(application-complaints-to-althingi-ombudsman): Minor QA feedback
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/attachments.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/overview.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/shared/constants.ts
Labels: automerge

#11987 chore(j-s): Use generated CaseAppealDecision type
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
Labels: automerge

#11966 feat(j-s): Indictment LÖKE File Chapters
  apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/migrations/20230831074825-gudjon,update-case-file.js
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/dto/updateFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/web/graphql/index.ts
  apps/judicial-system/web/pages/_app.tsx
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.spec.tsx
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/getIndictmentPoliceCaseFiles.graphql
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  apps/judicial-system/web/src/utils/hooks/useS3Upload/createFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  libs/judicial-system/types/src/lib/file.ts
  libs/judicial-system/types/src/lib/policeFile.ts
Labels: automerge

#12012 fix(j-s): Indictment Defendants
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
Labels: automerge

#12006 chore(j-s): Remove Stream Buffer Dependency
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  apps/judicial-system/backend/test/setup.ts
Labels: automerge

#12018 fix(j-s): Remove lands wights logo for defenders
  apps/judicial-system/web/src/components/Logo/Logo.tsx
Labels: automerge

#12022 fix(j-s): Use column case type for defender table
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
Labels: automerge

#12023 fix: typo
  .github/workflows/pullrequest.yml
Labels: automerge

#12003 refactor(j-s): Graphql schema hooks for prosecutor selection and upda…
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/api/src/app/modules/file/models/updateFiles.response.ts
  apps/judicial-system/api/src/app/modules/user/user.model.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/UpdateFiles.gql.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/updateFiles.graphql
  apps/judicial-system/web/src/components/ProsecutorSelection/ProsecutorSelection.tsx
  apps/judicial-system/web/src/components/ProsecutorSelection/prosecutorSelectionUsers.graphql
  apps/judicial-system/web/src/components/ProsecutorSelection/prosecutorSelectionUsersGql.ts
Labels: automerge

#11946 feat(auth-admin): Domain contact info
  apps/auth-admin-web/components/Admin/form/DomainCreateForm.tsx
  apps/auth-admin-web/entities/dtos/domain.dto.ts
  apps/auth-admin-web/i18n/locales/en.json
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.spec.ts
  libs/auth-api-lib/migrations/20230823212530-domain-add-contact-email.js
  libs/auth-api-lib/seeders/local/010-contact-email-domain.js
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/resources/dto/domain.dto.ts
  libs/auth-api-lib/src/lib/resources/dto/tenant.dto.ts
  libs/auth-api-lib/src/lib/resources/models/domain.model.ts
  libs/auth-api-lib/src/lib/resources/tenants.service.ts
Labels: automerge

#11985 chore(service-portal): outbound link clicks
  apps/service-portal/src/index.src.html
  libs/plausible/src/lib/servicePortalEvents.ts
  libs/service-portal/core/src/components/LinkResolver/LinkResolver.tsx
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/health/src/components/LinkButton/LinkButton.tsx
Labels: automerge, deploy-feature

#11915 chore(j-s): Test Performance
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/modules/institution/test/createTestingInstitutionModule.ts
  apps/judicial-system/backend/src/app/modules/institution/test/getAll.spec.ts
  apps/judicial-system/backend/src/app/modules/institution/test/institutionControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/dto/createUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/test/create.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/createTestingUserModule.ts
  apps/judicial-system/backend/src/app/modules/user/test/getAll.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getAllGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getById.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getByNationalId.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getByNationalIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/update.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/updateRolesRules.spec.ts
  apps/judicial-system/backend/test/e2e.spec.ts
  apps/judicial-system/backend/test/globalSetup.ts
  apps/judicial-system/backend/test/globalTeardown.ts
Labels: automerge

#12042 fix(application-system): Hotfix - Accept excel in file upload
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
Labels: automerge

#12032 fix(j-s): Polise File Chapter
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
Labels: automerge

#12030 fix(parental-leave): Remove pre-fill employerID and fix unbenefits qu…
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#12020 fix(parental-leave): stop checking past period from VMST whether it i…
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
Labels: automerge

#12034 fix(j-s): Footer info box width
  apps/judicial-system/web/src/components/FormFooter/FormFooter.css.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
Labels: automerge

#12035 feat(j-s): Judge foreperson
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
Labels: automerge

#12016 fix(parental-leave): Drop periods in the past and not in VMST
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#12033 fix(j-s): Alphabetize judge list in appeal case results
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/sortHelper.spec.ts
  apps/judicial-system/web/src/utils/sortHelper.ts
Labels: automerge

#12031 fix(j-s): Remove logo from defender form stepper
  apps/judicial-system/web/src/components/Logo/Logo.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
Labels: automerge

#12040 fix(application-system): Hotfix - Accept excel in file upload
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
Labels: automerge

#12044 fix(service-portal): national registry fixes
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/resolvers/person.resolver.ts
  libs/api/domains/national-registry/src/lib/v1/soffia.service.ts
  libs/service-portal/graphql/src/lib/client.ts
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.graphql
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.graphql
Labels: automerge

#12001 chore(githook): Make helm chart hook less aggressive
  .githooks/pre-commit
  .gitignore
Labels: automerge

#12050 fix(clients-rsk-relationships): Removing admin scope from fallback value
  libs/clients/rsk/relationships/src/lib/RskRelationshipsClientConfig.ts
Labels: automerge

#12055 fix(service-portal): occupational license feature flag
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.module.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge, high priority

#12028 feat(web): Form content type namespace added
  apps/web/components/Form/Form.tsx
Labels: automerge

#11991 chore(application-system): Remove stream-buffer usage
  libs/application/api/files/src/lib/pdfGenerators/residenceChange.ts
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/pdfGenerators/templates/residenceChange.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfGenerator.ts
  libs/application/templates/family-matters/children-residence-change/src/fields/index.ts
Labels: automerge

#12058 fix(service-portal): Hotfix - occupational license feature flag
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.module.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#11938 chore(j-s): Court Types
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/backend/migrations/20230822160212-update-institution.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/web-e2e/src/fixtures/institutionsQueryResponse.json
  apps/judicial-system/web-e2e/src/fixtures/judgeUser.json
  apps/judicial-system/web-e2e/src/fixtures/updateCaseMutationResponse.json
  apps/judicial-system/web-e2e/src/utils/index.ts
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/AppealSection/AppealSection.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useInstitution/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/mocks.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/case.spec.ts
  libs/judicial-system/types/src/lib/institution.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#11981 chore(core): Update prettier to 2.6.2
  apps/financial-aid/web-osk/src/utils/hooks/useUpdateApplication.ts
  package.json
  yarn.lock
Labels: automerge

#12004 feat(web): Update Directorate of immigration footer visuals
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.css.ts
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.tsx
Labels: automerge

#12067 fix(service-portal): add xroad config to education
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#12068 feat(consultation-portal): Changed from logo to text
  apps/consultation-portal/components/Layout/components/Footer/Footer.tsx
  apps/consultation-portal/components/LogoText/LogoText.json
  apps/consultation-portal/components/LogoText/LogoText.tsx
  apps/consultation-portal/components/index.ts
  apps/consultation-portal/components/svg/Splash.tsx
  apps/consultation-portal/screens/Home/components/HeroBanner/HeroBanner.tsx
Labels: automerge

#12070 fix(service-portal): Hotfix - education xroad config
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#12074 fix(j-s): Police File Id
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
Labels: automerge

#12075 fix(petitions): dateTil with a max
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/templates/general-petition/src/lib/GeneralPetitionTemplate.ts
Labels: automerge

#12076 fix(service-portal): user information child
  libs/service-portal/information/src/screens/Child/Child.tsx
Labels: automerge

#12079 fix(service-portal): hotfix - user information child (#12076)
  libs/service-portal/information/src/screens/Child/Child.tsx
Labels: automerge

#12052 feat(auth-admin): Sort permissions
  libs/api/domains/auth-admin/src/lib/scope/scope.service.ts
Labels: automerge

#12071 chore: make nx format trigger workflow
  .github/workflows/config-values.yaml
  .github/workflows/pullrequest.yml
  infra/scripts/ci/git-check-dirty.sh
Labels: automerge

#12073 fix(service-portal): Adding scope, fixing messages
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/occupational-licenses/src/lib/messages.ts
  libs/service-portal/occupational-licenses/src/lib/navigation.ts
  libs/service-portal/occupational-licenses/src/module.tsx
Labels: automerge

#12053 fix(j-s): Use same error message for all LÖKE case file errors
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
Labels: automerge

#12084 fix(service-portal): Adding scope, fixing messages (#12073)
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/lib/navigation/masterNavigation.ts
  libs/service-portal/occupational-licenses/src/lib/messages.ts
  libs/service-portal/occupational-licenses/src/lib/navigation.ts
  libs/service-portal/occupational-licenses/src/module.tsx
Labels: automerge

#12085 fix(web): Trim .json from pathname extraction function
  apps/web/utils/safelyExtractPathnameFromUrl.ts
Labels: automerge

#12086 fix(web): Hotfix - Trim .json from pathname extraction function (#12085)
  apps/web/utils/safelyExtractPathnameFromUrl.ts
Labels: automerge

#12083 feat(citizenship): checkbox-ui-update
  libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
Labels: automerge

#12087 fix(helm): Use right repository locations
  infra/helm/Chart.yaml
Labels: automerge

#10122 fix(user-profile): Update how to get locale of current logged in user.
  apps/services/user-profile/src/app/user-profile/dto/actorLocale.ts
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  libs/api/domains/user-profile/README.md
  libs/api/domains/user-profile/src/lib/models/userProfileLocale.model.ts
  libs/api/domains/user-profile/src/lib/models/userProfileStatus.model.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
  libs/shared/components/src/auth/UserMenu/userProfile.graphql.ts
Labels: automerge

#12041 chore(island-ui): Added text-align styles to Text component
  apps/judicial-system/web/src/components/Conclusion/AppealConclusion.tsx
  apps/judicial-system/web/src/components/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  libs/island-ui/core/src/lib/Text/Text.css.ts
  libs/island-ui/core/src/lib/Text/Text.tsx
Labels: automerge

#12082 fix(parental leave): few errors
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#12043 fix(auth-admin): Out of sync check
  libs/auth-api-lib/src/lib/resources/admin/services/admin-translation.service.ts
Labels: automerge

#12081 build(nx): cache-generatedevindexhtml
  apps/application-system/form/project.json
  apps/portals/admin/project.json
  apps/service-portal/project.json
  nx.json
Labels: automerge

#11980 feat(útlendingastofnun umsóknir): Form external data provider - add page title
  libs/application/types/src/lib/Form.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#12096 fix(service-portal): hotfix - HTML display on complete in document inbox
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
Labels: automerge

#12049 chore(j-s): Prosecutor Representative
  apps/judicial-system/backend/migrations/20230822160212-update-institution.js
  apps/judicial-system/backend/migrations/20230905135627-update-user.js
  apps/judicial-system/backend/seeders/seed_user.js
  apps/judicial-system/backend/src/app/guards/index.ts
  apps/judicial-system/backend/src/app/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getAllRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getByIdRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getIndictmentPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transitionRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/deleteRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createCaseFileRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createPresignedPostRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/deleteCaseFileRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/updateFilesRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/indictmentCount.controller.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/deleteRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/getAllCaseNotificationsRolesRules.spec.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#12060 fix(j-s): Court date event for investigation cases
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
Labels: automerge

#12097 feat(web): Add livechat config for transport authority
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#12077 feat(transport authority applications): Add custom delegation
  apps/application-system/form/src/auth.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/license-plate-renewal/src/lib/LicensePlateRenewalTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#12091 chore(j-s): Rename Staff Role
  apps/judicial-system/backend/migrations/20230905160659-update-user.js
  apps/judicial-system/backend/seeders/seed_user.js
  apps/judicial-system/backend/src/app/guards/index.ts
  apps/judicial-system/backend/src/app/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getAllRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getByIdRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCustodyNoticePdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingPdfRolesRules.spec.ts
  apps/judicial-system/web-e2e/src/fixtures/prisonSystemStaffUser.json
  apps/judicial-system/web-e2e/src/integration/Staff/InvestigationCase/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/integration/Staff/RestrictionCase/signedVerdictOverview.spec.ts
  apps/judicial-system/web-e2e/src/support/commands.ts
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/AllCases.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDocuments/CaseDocuments.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.spec.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#12103 fix(j-s): Court Record Signature Failure
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordSignatureConfirmation.spec.ts
Labels: automerge

#12104 feat(web): Kam 1600 rettindagaesla banner i header
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
Labels: automerge

#11940 feat(web): Housing benefit calculator
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx
  apps/web/components/connected/HousingBenefitCalculator/index.ts
  apps/web/components/connected/index.ts
  apps/web/screens/queries/HousingBenefitCalculator.ts
  apps/web/utils/richText.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/housing-benefit-calculator/.eslintrc.json
  libs/api/domains/housing-benefit-calculator/README.md
  libs/api/domains/housing-benefit-calculator/jest.config.ts
  libs/api/domains/housing-benefit-calculator/project.json
  libs/api/domains/housing-benefit-calculator/src/index.ts
  libs/api/domains/housing-benefit-calculator/src/lib/dto/calculation.input.ts
  libs/api/domains/housing-benefit-calculator/src/lib/housing-benefit-calculator.module.ts
  libs/api/domains/housing-benefit-calculator/src/lib/housing-benefit-calculator.resolver.ts
  libs/api/domains/housing-benefit-calculator/src/lib/models/calculation.model.ts
  libs/api/domains/housing-benefit-calculator/tsconfig.json
  libs/api/domains/housing-benefit-calculator/tsconfig.lib.json
  libs/api/domains/housing-benefit-calculator/tsconfig.spec.json
  libs/clients/housing-benefit-calculator/.eslintrc.json
  libs/clients/housing-benefit-calculator/README.md
  libs/clients/housing-benefit-calculator/jest.config.ts
  libs/clients/housing-benefit-calculator/project.json
  libs/clients/housing-benefit-calculator/src/clientConfig.json
  libs/clients/housing-benefit-calculator/src/index.ts
  libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.config.ts
  libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.module.ts
  libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.provider.ts
  libs/clients/housing-benefit-calculator/src/lib/housing-benefit-calculator.service.ts
  libs/clients/housing-benefit-calculator/tsconfig.json
  libs/clients/housing-benefit-calculator/tsconfig.lib.json
  libs/clients/housing-benefit-calculator/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#12072 feat(consultation-portal): changed logo on sites other than frontpage
  apps/consultation-portal/components/Layout/components/Footer/Footer.tsx
  apps/consultation-portal/components/Layout/components/Menu/Menu.tsx
  apps/consultation-portal/components/Layout/components/Menu/components/MenuModal/MenuModal.tsx
  apps/consultation-portal/components/LogoText/LogoText.tsx
  apps/consultation-portal/components/svg/HeroLogo.tsx
  apps/consultation-portal/components/svg/HeroLogoMobile.tsx
  apps/consultation-portal/components/svg/Logo.tsx
  apps/consultation-portal/components/svg/LogoMobile.tsx
  apps/consultation-portal/components/svg/SGLogo.tsx
  apps/consultation-portal/components/svg/index.ts
Labels: automerge

#12092 chore(j-s): Police V2 API Flag
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/modules/police/police.config.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#12078 feat(transport authority applications): Add custom delegation
  apps/application-system/form/src/auth.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/license-plate-renewal/src/lib/LicensePlateRenewalTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/OrderVehicleLicensePlateTemplate.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/OrderVehicleRegistrationCertificateTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#12105 fix(j-s): Indictment Subtypes
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.strings.ts
Labels: automerge

#12102 feat(j-s): Update Extended Police Case
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseOriginalAncestor.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/test/caseOriginalAncestorInterceptor.spec.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/police/test/createTestingPoliceModule.ts
Labels: automerge

#12089 feat(web): Directorate of immigration footer link changes
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunFooter.css.ts
Labels: automerge

#12107 feat(parental-leave): Revamp application history
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#12061 feat(auth-admin): Permission name availability check
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Permission/CreatePermission/CreatePermission.graphql
  libs/portals/admin/ids-admin/src/screens/Permission/CreatePermission/CreatePermission.tsx
Labels: automerge

#12115 fix(ehic): Set prereuisities to EphemeralStateLifeCycle
  libs/application/templates/european-health-insurance-card/src/lib/template.ts
Labels: automerge

#12056 fix(j-s): Put time label and placeholder into Contentful
  apps/judicial-system/web/src/components/DateTime/DateTime.spec.tsx
  apps/judicial-system/web/src/components/DateTime/DateTime.strings.ts
  apps/judicial-system/web/src/components/DateTime/DateTime.tsx
Labels: automerge

#12090 chore(j-s): Activate Norðurland Vestra
  apps/judicial-system/backend/migrations/20230908135754-update-institution.js
Labels: automerge

#12114 feat(auth-admin): Allow colon in permission ID
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth/shared/src/index.ts
  libs/auth/shared/src/lib/utils/validateClientId.spec.ts
  libs/auth/shared/src/lib/utils/validateIdMockData.ts
  libs/auth/shared/src/lib/utils/validatePermissionId.spec.ts
  libs/auth/shared/src/lib/utils/validatePermissionId.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Permission/CreatePermission/CreatePermission.action.ts
Labels: automerge

#12118 fix(service-portal): Occupational license fix download service and date format
  apps/download-service/src/app/modules/occupational-licenses/education-license.controller.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
  libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge

#12119 fix(service-portal): hotfix - dl-service occupation license
  apps/download-service/src/app/modules/occupational-licenses/education-license.controller.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.resolver.ts
  libs/service-portal/occupational-licenses/src/screens/EducationalDetail/EducationalDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/HealthDirectorateDetail/HealthDirectorateDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge

#12117 fix(auth-delegation): Fix "valid until" translation
  libs/portals/shared-modules/delegations/src/components/access/AccessDate/AccessDate.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessItem/AccessItem.tsx
  libs/portals/shared-modules/delegations/src/components/access/AccessList/AccessListHeader.tsx
  libs/portals/shared-modules/delegations/src/components/access/access.utils.ts
  libs/portals/shared-modules/delegations/src/lib/messages.ts
Labels: automerge

#11996 fix(service-portal): Optimize our SPA bundles size
  libs/api/mocks/src/index.ts
Labels: automerge

#12120 feat(search-indexer): Use feature flag instead of env variable for turning nested entry resolving on or off
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#11994 fix(ids-api): Fix flaky test in ids-api
  apps/services/auth/ids-api/src/app/user-profile/user-profile.controller.spec.ts
  apps/services/auth/ids-api/test/setup.ts
  libs/services/auth/testing/src/fixtures/apiScope.fixture.ts
  libs/testing/fixtures/src/index.ts
  libs/testing/fixtures/src/utils/createUniqueWords.ts
  libs/testing/nest/src/lib/testServer.ts
Labels: automerge

#12116 chore(web): Remove old feature flags from web
  apps/web/README.md
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/hooks/index.ts
  apps/web/hooks/useFeatureFlag.ts
  apps/web/screens/Project/Project.tsx
  apps/web/utils/featureFlag/featureFlag.spec.ts
  apps/web/utils/featureFlag/featureFlag.ts
  apps/web/utils/featureFlag/index.ts
Labels: automerge

#12111 feat(web): Add option for displaying feature articles on service web
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getServiceWebPage.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/serviceWebPage.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/importers/serviceWebPage.service.ts
Labels: automerge

#12093 chore(core): Fix warning from jest
  .yarn/patches/jest-config-npm-29.7.0-97d8544d74.patch
  apps/application-system/api/src/app.ts
  apps/application-system/api/src/main.ts
  apps/native/app/package.json
  apps/services/search-indexer/src/migrate/migrateKibana.ts
  apps/services/sessions/src/main.ts
  apps/services/user-notification/src/environments/environment.ts
  libs/infra-nest-server/src/index.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
  libs/infra-nest-server/src/lib/processJob.ts
  package.json
  scripts/build-graphql-schema.ts
  yarn.lock
Labels: automerge

#12099 perf(feature-flags): remove dynamic cc lib loading for factory
  libs/feature-flags/src/index.ts
  libs/feature-flags/src/lib/configcat.ts
  libs/feature-flags/src/lib/constants.ts
  libs/feature-flags/src/lib/factory.ts
  libs/feature-flags/src/lib/feature-flags-missing-sdk-key.spec.ts
  libs/feature-flags/src/lib/feature-flags.spec.ts
  libs/feature-flags/src/lib/feature-flags.ts
  libs/feature-flags/src/lib/server-side.ts
  libs/feature-flags/src/lib/types.ts
  libs/nest/feature-flags/src/lib/feature-flag.client.ts
  libs/react/feature-flags/src/lib/context.tsx
Labels: automerge, high priority

#12124 chore(search-indexer): Export configcat sdk key to init-containers
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#12101 feat(web): Render table slice
  apps/web/utils/richText.tsx
Labels: automerge

#12128 fix(chore): Fix db-proxy scripts after yargs update
  scripts/_run-aws-eks-commands.js
Labels: automerge

#12127 fix: import configcat-node typo
  libs/nest/feature-flags/src/lib/feature-flag.client.ts
Labels: automerge

#12121 fix(parental-leave): id contentful
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#12129 fix(service-portal): Remove fate from child ui
  libs/service-portal/information/src/screens/Child/Child.tsx
Labels: automerge

#12131 fix(auth-admin): Fix replica issue when creating client
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
Labels: automerge

#12132 fix(service-portal): fate UI hotfix
  libs/service-portal/information/src/screens/Child/Child.tsx
Labels: automerge

#12126 feat(web): Add config for Icelandic Health Insurance chatbot
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
Labels: automerge

#12130 fix(search-indexer-service): Increase memory limit for search-indexer
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#12134 chore(system-e2e): Disable retries in CI
  apps/system-e2e/src/playwright.config.ts
Labels: automerge

#12005 feat(service-portal): Transfer health center and dentist
  libs/api/domains/rights-portal/src/lib/dto/RegisterDentist.input.ts
  libs/api/domains/rights-portal/src/lib/dto/getDentists.input.ts
  libs/api/domains/rights-portal/src/lib/models/address.model.ts
  libs/api/domains/rights-portal/src/lib/models/aidsOrNutrition.model.ts
  libs/api/domains/rights-portal/src/lib/models/bill.model.ts
  libs/api/domains/rights-portal/src/lib/models/dentist.model.ts
  libs/api/domains/rights-portal/src/lib/models/healthCenter.model.ts
  libs/api/domains/rights-portal/src/lib/models/healthCenterResponse.model.ts
  libs/api/domains/rights-portal/src/lib/models/registerDentistResponse.ts
  libs/api/domains/rights-portal/src/lib/models/therapies.model.ts
  libs/api/domains/rights-portal/src/lib/models/userDentist.model.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.resolver.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/core/src/components/UserInfoLine/UserInfoLine.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.css.ts
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
  libs/service-portal/health/src/components/RegisterModal/index.ts
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.graphql
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.css.ts
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.graphql
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.tsx
  libs/service-portal/health/src/screens/Dentists/BillsTable.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.graphql
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.graphql
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/HealthCenter/HistoryTable.tsx
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.graphql
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthRegistration.css.ts
  libs/service-portal/health/src/screens/Therapies/Therapies.graphql
  libs/service-portal/health/src/screens/Therapies/Therapies.tsx
  libs/service-portal/health/src/utils/format.ts
Labels: automerge, deploy-feature

#12137 chore(system-e2e): Better failure message in Slack
  apps/system-e2e/src/notifications/notify.ts
Labels: automerge

#12143 fix(search-indexer): Imports failing due to missing deleted entry ids
  libs/cms/src/lib/search/contentful.service.ts
Labels: automerge

#12139 chore(service-portal): Add url resolving to docline inbox sp
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
Labels: automerge

#12145 feat(web): Project page secondary sidebar option
  apps/web/components/Project/Header/DefaultProjectHeader.css.ts
  apps/web/screens/Project/utils.tsx
  apps/web/screens/queries/Project.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#12148 fix(service-portal): Only show driving school exam with status 2
  libs/service-portal/vehicles/src/screens/DrivingLessonsBook/DrivingLessonsBook.tsx
Labels: automerge

#12150 fix(j-s): Use compare locale IS for alphabetized sorting
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/utils/hooks/useSort/useSortAppealCases.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSortCases.ts
Labels: automerge

#12153 fix(service-portal): Add back tooltip split name
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.graphql
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
Labels: automerge, deploy-feature

#12125 feat(j-s): Default Crime Scene
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/LokeNumberList/LokeNumberList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/getPoliceCaseInfo.graphql
Labels: automerge

#12123 feat(web): Add Embed content type to CMS
  apps/web/components/Organization/Slice/EmbedSlice/EmbedSlice.css.ts
  apps/web/components/Organization/Slice/EmbedSlice/EmbedSlice.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/embed.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge, high priority

#12151 fix(service-portal): Update marital and cohabitation display in service-portal
  libs/api/domains/national-registry/src/lib/shared/models/spouse.model.ts
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/clients/national-registry/v3/src/clientConfig.json
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/Spouse/Spouse.graphql
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
Labels: automerge, deploy-feature

#11995 feat(útlendingastofnun umsóknir): Changes to National Registry service for new applications
  libs/api/domains/identity/src/lib/models/identity.model.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
  libs/application/types/src/lib/template-api/shared-api/models/index.ts
  libs/application/types/src/lib/template-api/shared-api/models/national-registry/custody-information.ts
  libs/application/types/src/lib/template-api/shared-api/models/national-registry/individual.ts
  libs/application/types/src/lib/template-api/shared-api/models/national-registry/maritalTitle.ts
  libs/application/types/src/lib/template-api/shared-api/models/national-registry/parents.ts
  libs/clients/identity/src/lib/identityClient.service.ts
  libs/clients/identity/src/lib/types/identity.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
  libs/clients/national-registry/v2/src/lib/types/cohabitation.dto.ts
Labels: automerge

#12141 feat(web): Add nofollow on vacancy details page
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacancyDetails.tsx
  apps/web/screens/Search/Search.tsx
Labels: automerge, high priority

#12106 feat(j-s): Add new option for defender access to cases
  apps/judicial-system/api/src/app/modules/case/dto/createCase.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20230907135116-update-case.js
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/guards/limitedAccessAccordingToCaseState.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/limitedAccessCaseReceived.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/requestSharedWithDefender.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessAccordingToCaseStateGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessCaseReceivedGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/requestSharedWithDefenderGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCaseFilesRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getIndictmentPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getRequestPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/web-e2e-regression/src/utils/index.ts
  apps/judicial-system/web/messages/Core/caseResubmitModal.ts
  apps/judicial-system/web/src/components/CaseResubmitModal/CaseResubmitModal.spec.tsx
  apps/judicial-system/web/src/components/CaseResubmitModal/CaseResubmitModal.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.strings.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/FormProvider/caseGql.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCaseGql.ts
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/types/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/mutations.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#12062 fix(j-s): Form stepper fixes
  apps/judicial-system/web/src/components/PageLayout/utils/index.spec.tsx
  apps/judicial-system/web/src/components/PageLayout/utils/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#11970 fix(application-system): Reusable AlertMessageField
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/accident-notification/src/fields/FieldAlertMessage/index.tsx
  libs/application/templates/accident-notification/src/fields/index.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/whoIsTheNotificationForSection.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintInformation/FieldAlertMessage.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/data-protection-complaint/src/fields/FieldAlertMessage.tsx
  libs/application/templates/data-protection-complaint/src/fields/index.ts
  libs/application/templates/data-protection-complaint/src/forms/ComplaintForm.ts
  libs/application/templates/health-insurance/src/fields/FormerCountryErrorMessage/FormerCountryErrorMessage.tsx
  libs/application/templates/health-insurance/src/fields/index.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/login-service/src/fields/IsatInvalid/IsatInvalid.tsx
  libs/application/templates/login-service/src/fields/index.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/parental-leave/src/fields/AlertMessage/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/AlertWarningLostPlate.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/index.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/forms/OrderVehicleLicensePlateForm/InformationSection/plateDeliverySubSection.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AlertMessageFormField/AlertMessageFormField.stories.mdx
  libs/application/ui-fields/src/lib/AlertMessageFormField/AlertMessageFormField.tsx
Labels: automerge

#12165 ci: ignore schemas cache on label
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge, skip-generated-cache

#12163 fix(transport authority custom delegation): Add missing scope to endpoints that are used
  libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Labels: automerge

#12164 fix(transport authority custom delegation): Add missing scope to endpoints that are used
  libs/api/domains/transport-authority/src/lib/graphql/main.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
Labels: automerge

#12168 fix(web): Use correct slug when querying service web slices
  apps/web/screens/ServiceWeb/Home/Home.tsx
Labels: automerge

#12140 fix: Juristiction → Jurisdiction
  libs/api/domains/driving-license/src/lib/__mock-data__/jurisdictions.json
  libs/api/domains/driving-license/src/lib/__mock-data__/requestHandlers.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/api/domains/driving-license/src/lib/graphql/main.resolver.ts
  libs/api/domains/driving-license/src/lib/graphql/models/index.ts
  libs/api/domains/driving-license/src/lib/graphql/models/jurisdiction.model.ts
  libs/api/domains/driving-license/src/lib/util/constants.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/drivingLicenseSubmittedEmail.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDelivery.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionOverview.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/driving-license.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#12171 fix(user-profile): Handling for no user found
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
Labels: automerge

#12175 fix(user-profile): hotfix no user found
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
Labels: automerge

#12158 feat(web): Transport authority ship search on public web
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/connected/vehicles/PublicShipSearch.tsx
  apps/web/components/connected/vehicles/PublicVehicleSearch.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/screens/queries/PublicShipSearch.ts
  apps/web/utils/richText.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/ship-registry/.eslintrc.json
  libs/api/domains/ship-registry/README.md
  libs/api/domains/ship-registry/jest.config.ts
  libs/api/domains/ship-registry/project.json
  libs/api/domains/ship-registry/src/index.ts
  libs/api/domains/ship-registry/src/lib/dto/ship-search.input.ts
  libs/api/domains/ship-registry/src/lib/models/ship-search.model.ts
  libs/api/domains/ship-registry/src/lib/ship-registry.module.ts
  libs/api/domains/ship-registry/src/lib/ship-registry.resolver.ts
  libs/api/domains/ship-registry/tsconfig.json
  libs/api/domains/ship-registry/tsconfig.lib.json
  libs/api/domains/ship-registry/tsconfig.spec.json
  libs/clients/ship-registry/.eslintrc.json
  libs/clients/ship-registry/README.md
  libs/clients/ship-registry/jest.config.ts
  libs/clients/ship-registry/project.json
  libs/clients/ship-registry/src/clientConfig.json
  libs/clients/ship-registry/src/index.ts
  libs/clients/ship-registry/src/lib/ship-registry.config.ts
  libs/clients/ship-registry/src/lib/ship-registry.module.ts
  libs/clients/ship-registry/src/lib/ship-registry.provider.ts
  libs/clients/ship-registry/src/lib/ship-registry.service.ts
  libs/clients/ship-registry/tsconfig.json
  libs/clients/ship-registry/tsconfig.lib.json
  libs/clients/ship-registry/tsconfig.spec.json
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  tsconfig.base.json
Labels: automerge

#12177 feat(web): Hotfix - Add livechat config for transport authority (#12097)
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#12179 fix(estate): changing phone and email of estate members to be required
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#12144 feat(j-s): Add tooltip next to button to notify COA
  apps/judicial-system/web/messages/Core/titles.ts
  apps/judicial-system/web/messages/InvestigationCases/Court/overview.ts
  apps/judicial-system/web/messages/RestrictionCases/Court/overview.ts
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.strings.ts
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/strings.ts
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/useAppealAlertBanner.css.ts
Labels: automerge

#12181 feat(web): Hotfix - Transport authority ship search on public web (#12158)
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/connected/vehicles/PublicShipSearch.tsx
  apps/web/components/connected/vehicles/PublicVehicleSearch.tsx
  apps/web/components/connected/vehicles/index.ts
  apps/web/screens/queries/PublicShipSearch.ts
  apps/web/utils/richText.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/ship-registry/.eslintrc.json
  libs/api/domains/ship-registry/README.md
  libs/api/domains/ship-registry/jest.config.ts
  libs/api/domains/ship-registry/project.json
  libs/api/domains/ship-registry/src/index.ts
  libs/api/domains/ship-registry/src/lib/dto/ship-search.input.ts
  libs/api/domains/ship-registry/src/lib/models/ship-search.model.ts
  libs/api/domains/ship-registry/src/lib/ship-registry.module.ts
  libs/api/domains/ship-registry/src/lib/ship-registry.resolver.ts
  libs/api/domains/ship-registry/tsconfig.json
  libs/api/domains/ship-registry/tsconfig.lib.json
  libs/api/domains/ship-registry/tsconfig.spec.json
  libs/clients/ship-registry/.eslintrc.json
  libs/clients/ship-registry/README.md
  libs/clients/ship-registry/jest.config.ts
  libs/clients/ship-registry/project.json
  libs/clients/ship-registry/src/clientConfig.json
  libs/clients/ship-registry/src/index.ts
  libs/clients/ship-registry/src/lib/ship-registry.config.ts
  libs/clients/ship-registry/src/lib/ship-registry.module.ts
  libs/clients/ship-registry/src/lib/ship-registry.provider.ts
  libs/clients/ship-registry/src/lib/ship-registry.service.ts
  libs/clients/ship-registry/tsconfig.json
  libs/clients/ship-registry/tsconfig.lib.json
  libs/clients/ship-registry/tsconfig.spec.json
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  tsconfig.base.json
Labels: automerge

#12187 fix(application-passport): Passport domicile requirement amendment
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
Labels: automerge

#12188 fix(application-passport): Hotfix/r242 passport domicile fix
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
Labels: automerge

#12189 fix(application-passport): Passport domicile requirement amendment
  libs/application/templates/passport/src/dataProviders/index.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/passport/src/lib/PassportTemplate.ts
Labels: automerge

#12183 fix(medeigandi-okutaekis): loading state fix
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx
Labels: automerge

#12182 feat(j-s): Case Conclustion to Court
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseConclusionToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseConclusionToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.config.ts
  apps/judicial-system/backend/src/app/modules/court/court.module.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createTestingCourtModule.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.module.ts
  apps/judicial-system/backend/src/app/modules/file/file.module.ts
  apps/judicial-system/backend/src/app/modules/index.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#12191 fix(service-portal): Aids and nutrition missing data fix
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.types.ts
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx
Labels: automerge

#12192 fix(consultation-portal): KAM-1637-setja-malefnasvid-undir-askriftum-i-stafrofsrod
  apps/consultation-portal/screens/Subscriptions/components/ChosenSubscriptions/ChosenSubscriptions.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/SubscriptionTable.tsx
  apps/consultation-portal/utils/helpers/sorting.ts
Labels: automerge

#12180 fix(medeigandi-okutaekis): Loading state fix
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/CoOwner/index.tsx
Labels: automerge

#12195 fix(service-portal): Aids and nutrition service not returning data
  libs/api/domains/rights-portal/src/lib/rightsPortal.service.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.types.ts
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsTable.tsx
Labels: automerge

#12190 fix(passport): full expiration date and no intro
  libs/application/templates/passport/src/fields/PassportSelection/index.tsx
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/overviewSection/personalOverview.ts
  libs/application/templates/passport/src/lib/messages.ts
Labels: automerge

#12194 fix(national-registry-v3): Update spouse model marital status text
  libs/api/domains/national-registry/src/lib/shared/models/spouse.model.ts
Labels: automerge

#12173 feat(contentful-apps): Embed Link Field Contentful App
  apps/contentful-apps/pages/fields/content-type-notifications-field.tsx
  apps/contentful-apps/pages/fields/embed-link-field.tsx
Labels: automerge

#12202 fix(domains): Updating spouse model marital status text
  libs/api/domains/national-registry/src/lib/shared/models/spouse.model.ts
Labels: automerge

#12204 fix(domains): Force new commit to release branch.
  libs/service-portal/occupational-licenses/README.md
Labels: automerge

#12206 fix(domains): New empty commit to fix spinnaker
  libs/service-portal/occupational-licenses/src/components/LicenceActionCard.tsx
Labels: automerge

#12198 feat(web): Display aircraft registration number in table
  apps/web/components/connected/vehicles/AircraftSearch.tsx
Labels: automerge

#12017 feat(app): vehicle mileage
  apps/native/app/README.md
  apps/native/app/android/app/build.gradle
  apps/native/app/android/fastlane/Fastfile
  apps/native/app/android/fastlane/README.md
  apps/native/app/babel.config.js
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
  apps/native/app/ios/IslandApp/Info.plist
  apps/native/app/ios/Podfile.lock
  apps/native/app/ios/fastlane/Fastfile
  apps/native/app/ios/fastlane/README.md
  apps/native/app/metro.config.js
  apps/native/app/package.json
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/graphql/queries/get-users-vehicles-detail.ts
  apps/native/app/src/graphql/queries/update-islykill-settings.mutation.ts
  apps/native/app/src/hooks/create-navigation-option-hooks.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/react-native.d.ts
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/finance/finance.tsx
  apps/native/app/src/screens/home/applications-module.tsx
  apps/native/app/src/screens/license-scanner/license-scanner.tsx
  apps/native/app/src/screens/license-scanner/scan-results/license-scan-result.tsx
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/screens/settings/edit-email.tsx
  apps/native/app/src/screens/settings/edit-phone.tsx
  apps/native/app/src/screens/vehicles/vehicles-detail.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
  apps/native/app/src/ui/lib/card/vehicle-card.tsx
  apps/native/app/src/utils/applications-utils.ts
  apps/native/app/tsconfig.json
Labels: automerge

#12162 fix(auth-admin): Fix flaky client creation
  apps/services/auth/admin-api/src/app/v2/secrets/client-secrets.service.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/clients-translation.service.ts
  libs/auth-api-lib/src/lib/resources/resource-translation.service.ts
  libs/auth-api-lib/src/lib/translation/translation.service.spec.ts
  libs/auth-api-lib/src/lib/translation/translation.service.ts
Labels: automerge
