Repository island-is/island.is, pull requests merged in 2024-06, with the labels that each got.

#14805 feat(web): UV radiation chart data
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/statistics/src/lib/statistics.module.ts
  libs/clients/statistics/src/lib/statistics.service.ts
  libs/clients/statistics/src/lib/statistics.utils.ts
  libs/clients/statistics/src/lib/types.ts
  libs/clients/ultraviolet-radiation/.eslintrc.json
  libs/clients/ultraviolet-radiation/README.md
  libs/clients/ultraviolet-radiation/jest.config.ts
  libs/clients/ultraviolet-radiation/project.json
  libs/clients/ultraviolet-radiation/src/clientConfig.json
  libs/clients/ultraviolet-radiation/src/index.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.config.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.module.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.provider.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.service.ts
  libs/clients/ultraviolet-radiation/tsconfig.json
  libs/clients/ultraviolet-radiation/tsconfig.lib.json
  libs/clients/ultraviolet-radiation/tsconfig.spec.json
  libs/shared/constants/src/lib/organizationSlug.ts
  libs/shared/types/src/lib/api-cms-domain.ts
  tsconfig.base.json
Labels: automerge

#14988 fix(university-careers): add lhi to uni
  apps/api/src/app/app.module.ts
  apps/download-service/src/app/app.module.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/university-careers/src/lib/universityCareers.service.ts
  libs/api/domains/university-careers/src/lib/universityCareers.types.ts
  libs/clients/university-careers/project.json
  libs/clients/university-careers/src/index.ts
  libs/clients/university-careers/src/lib/clients/iceland-university-of-the-arts/clientConfig.yaml
  libs/clients/university-careers/src/lib/clients/iceland-university-of-the-arts/icelandUniversityOfTheArtsCareerClient.config.ts
  libs/clients/university-careers/src/lib/clients/iceland-university-of-the-arts/icelandUniversityOfTheArtsCareerClient.provider.ts
  libs/clients/university-careers/src/lib/clients/iceland-university-of-the-arts/index.ts
  libs/clients/university-careers/src/lib/clients/index.ts
  libs/clients/university-careers/src/lib/dto/universityDto.ts
  libs/clients/university-careers/src/lib/universityCareers.module.ts
  libs/clients/university-careers/src/lib/universityCareers.service.ts
  libs/clients/university-careers/src/lib/universityCareers.types.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/education/src/utils/mapUniversitySlug.ts
  libs/shared/constants/src/lib/organizationSlug.ts
Labels: automerge

#15031 fix(cms): Logo loader performance fix
  libs/api/domains/auth/src/lib/resolvers/domain.resolver.ts
  libs/api/domains/notifications/src/lib/notificationsList.resolver.ts
  libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
  libs/cms/src/index.ts
  libs/cms/src/lib/cms.module.ts
  libs/cms/src/lib/loaders/organizationLogo.loader.ts
  libs/cms/src/lib/loaders/organizationLogoByNationalId.loader.ts
  libs/cms/src/lib/loaders/organizationLogoByReferenceId.loader.ts
  libs/cms/src/lib/loaders/organizationLogoByTitle.loader.ts
  libs/cms/src/lib/utils/types.ts
Labels: automerge

#14812 fix(social-insurance-administration): add scopes
  .github/CODEOWNERS
  libs/api/domains/social-insurance/src/lib/dtos/paymentPlan.input.ts
  libs/api/domains/social-insurance/src/lib/models/payments.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.resolver.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/auth-api-lib/seeders/data/add-social-insurance-api-scopes-to-clients-api.ts
  libs/clients/social-insurance-administration/src/clientConfig.json
  libs/clients/social-insurance-administration/src/lib/apiConfiguration.ts
  libs/clients/social-insurance-administration/src/lib/apiProvider.ts
  libs/clients/social-insurance-administration/src/lib/apis.ts
  libs/clients/social-insurance-administration/src/lib/configFactory.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.config.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.module.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.type.ts
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.graphql
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.tsx
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.graphql
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge

#15002 feat(fa): Adding application event and allow to update
  apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts
  apps/financial-aid/backend/migrations/20240529131132-application_event-add-to-event_type.js
  apps/financial-aid/backend/src/app/modules/application/application.controller.ts
  apps/financial-aid/backend/src/app/modules/application/dto/updateApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/test/update.spec.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/ApplicationHeader/ApplicationHeader.tsx
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/AppliedMonthModal/AppliedMonthModal.tsx
  apps/financial-aid/web-veita/src/components/CommentSection/CommentSection.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  apps/financial-aid/web-veita/src/utils/navigation.ts
  apps/financial-aid/web-veita/src/utils/useApplicationEvent.ts
  apps/financial-aid/web-veita/src/utils/useApplicationState.ts
  libs/financial-aid/shared/src/lib/enums.ts
  libs/financial-aid/shared/src/lib/formatters.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#15049 fix(j-s): Routing
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#14768 feat(service-desk): WebApiCrypto encryption
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/portals/admin/service-desk/src/screens/User/User.loader.ts
  libs/portals/admin/service-desk/src/screens/Users/Users.action.ts
  libs/portals/admin/service-desk/src/screens/Users/Users.tsx
  libs/service-portal/information/src/screens/BioChild/BioChild.tsx
  libs/service-portal/information/src/screens/ChildCustody/ChildCustody.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/shared/utils/src/lib/simpleEncryption.spec.ts
  libs/shared/utils/src/lib/simpleEncryption.ts
Labels: automerge

#15053 chore(service-portal): No scope notifications
  apps/service-portal/src/components/DocumentsEmpty/DocumentsEmpty.css.ts
  apps/service-portal/src/components/DocumentsEmpty/DocumentsEmpty.tsx
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  apps/service-portal/src/components/Notifications/NotificationButton.tsx
  apps/service-portal/src/components/Notifications/Notifications.css.ts
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
Labels: automerge

#15046 fix(fa): Making children aid field required if it is shown
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
Labels: automerge

#15055 chore: Exclude githubActionsCache on feature deployments
  infra/src/uber-charts/islandis.ts
Labels: automerge

#14803 feat(home-support-application): Add application-system translation namespace
  libs/application/templates/home-support/src/lib/HomeSupportTemplate.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#15047 fix(licenses): Chunk error
  libs/service-portal/licenses/src/components/QRCodeModal/PkPass.tsx
  libs/service-portal/licenses/src/screens/LicenseDetail/LicenseDetail.tsx
Labels: automerge

#15063 fix(inheritance-report): dataschema deceased was married
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
Labels: automerge

#15052 fix(j-s): MD5 Indictment File Hash
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
Labels: automerge

#15056 feat(university-application): file uploads added to service
  apps/services/university-gateway/src/app/modules/application/dto/createApplicationDto.ts
  apps/services/university-gateway/src/app/modules/application/universityApplication.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/application/templates/university/src/components/SummaryBlock.tsx
  libs/application/templates/university/src/fields/EducationDetails/DetailsRepeaterItem.tsx
  libs/application/templates/university/src/fields/Review/ProgramReview.tsx
  libs/application/templates/university/src/forms/UniversityForm/FormerEducation/index.ts
  libs/clients/university-application/university-of-iceland/src/clientConfig.yaml
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.service.ts
  libs/university-gateway/src/lib/model/application.ts
Labels: automerge

#15054 fix(licenses): parallel
  libs/api/domains/license-service/src/lib/licenseService.service.ts
Labels: automerge

#15064 fix(application-hid): HOTFIX Health insurance declaration fixes
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.utils.ts
  libs/application/templates/health-insurance-declaration/src/forms/HealthInsuranceDeclarationForm.ts
  libs/application/templates/health-insurance-declaration/src/forms/Prerequisites.ts
  libs/application/templates/health-insurance-declaration/src/forms/Submitted.ts
  libs/application/templates/health-insurance-declaration/src/index.ts
  libs/application/templates/health-insurance-declaration/src/lib/HealthInsuranceDeclarationTemplate.ts
  libs/application/templates/health-insurance-declaration/src/lib/dataSchema.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/errors.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/index.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/prerequisites.ts
  libs/application/templates/health-insurance-declaration/src/types/index.ts
  libs/application/templates/health-insurance-declaration/src/utils/data.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/health-insurance-api.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
Labels: automerge

#15069 fix(service-portal-work-machines): Add action type
  libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
Labels: automerge

#15061 feat(documents-v2): Mark all as read option
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/markAllMailAsRead.model.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
Labels: automerge

#15072 fix(district-commissioners-licenses): HOTFIX - update client
  libs/clients/district-commissioners-licenses/project.json
  libs/clients/district-commissioners-licenses/src/clientConfig.json
  libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.config.ts
  libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.module.ts
  libs/clients/district-commissioners-licenses/src/lib/districtCommissionersLicenses.service.ts
Labels: automerge

#15074 fix(documents-v2): Mark all as read name
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
Labels: automerge

#15075 chore(estate): Include autonomous answer in formdata
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/createPDF.ts
Labels: automerge

#15060 feat(delegations): Verifu usage of ASDT instead of PRSP
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/delegations/dto/delegation.dto.ts
Labels: automerge

#15067 fix(web): Fix percentage rounding in pie charts
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
  apps/web/components/Charts/v2/utils/format.ts
Labels: automerge

#15083 fix(application-system): Data provider bug hotfix
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#15082 fix(application-system): Data provider bug hotfix
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#15038 feat(admins-portal): applications statistics for portals admin
  apps/application-system/api/src/app/modules/application/admin.controller.ts
  apps/application-system/api/src/app/modules/application/dto/applicationAdmin.response.dto.ts
  libs/api/domains/application/src/lib/application-admin/application-admin.resolvers.ts
  libs/api/domains/application/src/lib/application-admin/dto/applications-applications-admin-input.ts
  libs/api/domains/application/src/lib/application.model.ts
  libs/api/domains/application/src/lib/application.service.ts
  libs/application/api/core/src/lib/application/application.model.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/portals/admin/application-system/src/components/StatisticsForm/StatisticsForm.tsx
  libs/portals/admin/application-system/src/components/StatisticsTable/StatisticsTable.tsx
  libs/portals/admin/application-system/src/lib/messages.ts
  libs/portals/admin/application-system/src/lib/navigation.ts
  libs/portals/admin/application-system/src/lib/paths.ts
  libs/portals/admin/application-system/src/module.tsx
  libs/portals/admin/application-system/src/queries/overview.graphql
  libs/portals/admin/application-system/src/screens/Overview/Overview.tsx
  libs/portals/admin/application-system/src/screens/Root/Root.tsx
  libs/portals/admin/application-system/src/screens/Statistics/Statistics.tsx
Labels: automerge, deploy-feature

#14892 feat(application-system): add total file size limit
  libs/application/core/src/lib/constants.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-components/src/utilities/FileUploadController/index.tsx
  libs/application/ui-components/src/utilities/FileUploadController/utils.ts
Labels: automerge

#15078 feat(web): Chart number box - Add configuration so we can determine within the CMS if the value should be rounded or not
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/chartNumberBox.model.ts
Labels: automerge

#15085 feat:(endorsement-list): Adding pagination
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge, autoupdate

#15059 fix(j-s): Completed Case States in Defender Case Lists
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/routes/Defender/Cases/defenderCases.graphql
  apps/judicial-system/web/src/routes/Shared/Cases/prisonCases.graphql
Labels: automerge

#15070 fix(j-s): Defender Case File Access
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/limitedAccessFile.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createPresignedPostGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/deleteCaseFileGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/limitedAccessFileControllerGuards.spec.ts
Labels: automerge

#15080 fix(ids-api): Removing VER applications delegation config
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#15081 feat(ids-api): remove delegation config for ver applications
  libs/auth-api-lib/src/lib/delegations/DelegationConfig.ts
Labels: automerge

#15077 fix(j-s): Indictment Post Processing
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
Labels: automerge

#15048 fix(fa): Renaming applied from applied to appliedDate
  apps/financial-aid/api/src/app/modules/application/dto/updateApplication.input.ts
  apps/financial-aid/api/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/migrations/20240531145432-update-application-applied_date.js
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/dto/updateApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/getCurrentApplication.spec.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsTable.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/utils/navigation.ts
  apps/financial-aid/web-veita/src/utils/useApplicationState.ts
  libs/financial-aid/shared/src/lib/enums.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
  libs/financial-aid/shared/src/lib/utils.ts
Labels: automerge

#15079 feat(ids-api): index delegations when IDS gets delegations
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
  apps/services/auth/ids-api/src/app/delegations/delegations.module.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-scopes.spec.ts
Labels: automerge

#15084 feat(web): Organization page - prefilter search results
  apps/web/components/FilterTag/FilterTag.tsx
  apps/web/components/Header/Header.tsx
  apps/web/components/Menu/Menu.tsx
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/layouts/main.tsx
  apps/web/screens/Search/Search.tsx
  apps/web/utils/organization.ts
Labels: automerge

#15087 feat(web): Ultraviolet Radiation chart - Add endpoint that shows past year measurements
  libs/clients/statistics/src/lib/statistics.service.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.service.ts
Labels: automerge

#15108 feat(ui-fields): Add spacing to CheckboxFormField
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
Labels: automerge

#15114 fix(service-portal): Update get for documents hotfix
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/documents.input.ts
  libs/service-portal/documents/src/hooks/useDocumentList.ts
Labels: automerge

#15065 fix(AOSH): Radiofield validation fix and changesupervisor phone validation fix
  libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/pickMachineSubSection.ts
  libs/application/templates/aosh/change-machine-supervisor/src/lib/dataSchema.ts
  libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/pickMachineSubSection.ts
  libs/application/templates/aosh/request-for-inspection/src/forms/RequestMachineForInspectionForm/InformationSection/pickMachineSubSection.ts
  libs/application/templates/aosh/street-registration/src/forms/StreetRegistrationForm/InformationSection/pickMachineSubSection.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/InformationSection/pickMachineSubSection.ts
Labels: automerge

#15076 feat(application-system): Custom text for next button in applications
  apps/application-system/form/src/routes/Application.tsx
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Form.ts
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
Labels: automerge

#15120 fix(hs): Throw error on submit
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
Labels: automerge

#15097 fix(inheritance-report): EFS fixes 4.06
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsOverview/index.tsx
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/forms/sections/applicationTypeSelection.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/heirs.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/inheritanceExecutor.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/overview.ts
  libs/application/templates/inheritance-report/src/lib/InheritanceReportTemplate.ts
  libs/application/templates/inheritance-report/src/lib/constants.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
Labels: automerge, deploy-feature

#15112 fix(service-portal): Update get for documents
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/documents.input.ts
  libs/service-portal/documents/src/hooks/useDocumentList.ts
Labels: automerge

#14847 fix(application-driving-license): Fix logging
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
Labels: automerge

#15092 feat(university-gateway): Improved error handling for enum mapping
  apps/services/university-gateway/migrations/20240528142532-add-Person-FieldType.js
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/agriculturalUniversityOfIcelandClient.service.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.service.ts
  libs/clients/university-application/holar-university/src/lib/holarUniversityClient.service.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/icelandUniversityOfTheArtsClient.service.ts
  libs/clients/university-application/reykjavik-university/src/lib/reykjavikUniversityClient.service.ts
  libs/clients/university-application/university-of-akureyri/src/lib/universityOfAkureyriClient.service.ts
  libs/clients/university-application/university-of-iceland/src/clientConfig.yaml
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.service.ts
  libs/clients/university-application/university-of-iceland/src/lib/utils/mapUglaCourses.ts
  libs/clients/university-application/university-of-iceland/src/lib/utils/mapUglaPrograms.ts
  libs/university-gateway/src/lib/types/fieldType.ts
  libs/university-gateway/src/lib/utils/enum.ts
Labels: automerge

#15093 feat(web): Default footer no longer is full width but instead the same width as the content section
  apps/web/components/Footer/Footer.tsx
  apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.tsx
  apps/web/components/Organization/Slice/LatestNewsSlice/LatestNewsSlice.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home/Home.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySubPage.tsx
Labels: automerge

#15118 feat(web): Hide contact banner for "Tryggingastofnun" service web pages
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
Labels: automerge

#15119 fix(hs): Throw on error for submit
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
Labels: automerge

#15121 fix(web): Kilometer fee result - remove suffix
  apps/web/components/connected/vehicles/KilometerFee.tsx
Labels: automerge

#15106 fix(user-notifications): Fix Hnipp name tag padding
  libs/email-service/src/tools/design/styles.hbs
Labels: automerge

#15110 feat(application-ir): Add debttypes and distribute to otherDebts according to DC enumeration
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/fakeData.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#15123 chore(j-s): Robot Case File Email
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#15124 fix(j-s): Defender national id
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalId.spec.ts
  libs/judicial-system/types/src/lib/defender.ts
Labels: automerge

#15127 fix(service-portal): Sanitize html from document providers
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.css.ts
  libs/service-portal/documents/src/components/DocumentRenderer/HTMLDocument.tsx
Labels: automerge

#15115 fix(fa): fixing spouse personal tax calculation
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#15130 fix(ojoi): Fixing bugs found in demo
  apps/web/screens/queries/OfficialJournalOfIceland.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.input.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.response.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/single.input.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.resolver.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.service.ts
  libs/application/templates/official-journal-of-iceland/src/components/htmlEditor/HTMLEditor.css.ts
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Regular.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Signatures.css.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.css.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/AdvertModal.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Publishing.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Summary.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/clients/official-journal-of-iceland/public/src/clientConfig.json
  libs/clients/official-journal-of-iceland/public/src/lib/officialJournalOfIcelandClient.service.ts
Labels: automerge

#15132 fix(inheritance-report): EFS fixes 6/06
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/deceased.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#15133 fix(university-gateway): Removing calls to update application status
  apps/services/university-gateway/src/app/worker/worker.service.ts
Labels: automerge

#15086 fix(delegation-index): primary key violation
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#15024 chore: upgrade node version to 20.14.0
  package.json
Labels: automerge, deploy-feature, test everything

#15138 fix(ids-api): mock delegation indexing in controller tests
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-types.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-scopes.spec.ts
  apps/services/auth/ids-api/test/setup.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#15099 chore(j-s): Criminal record update visible in in indictments case lists
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.strings.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#15136 fix(j-s): Digital mailbox swagger
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.controller.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/case.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/defenders/defender.controller.ts
Labels: automerge

#15139 chore(ids-api): Config infra for national registry service on staging.
  charts/identity-server/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15144 feat(web): Hotfix - Project page - Fetch 5 levels of data depth (#15142)
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge

#15142 feat(web): Project page - Fetch 5 levels of data depth
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge

#14906 chore(ids-api): Add passkey to allowed acr for island.is/web client.
  libs/auth-api-lib/seeders/20240523102129-configure-acr-for-clients.js
Labels: automerge

#15134 fix(web): Add max width to default footer component instead of using GridContainer
  apps/web/components/Footer/Footer.css.ts
  apps/web/components/Footer/Footer.tsx
Labels: automerge

#15104 feat(j-s): Update subpoena compensation claim decision
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240603112011-update-defendant.js
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.controller.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/dto/subpoena.dto.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/case.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalCase.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/defenders/defender.controller.ts
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
Labels: automerge

#15141 feat(fa): Changing filter tables from using created to appliedDate
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/ApplicationsTable/ApplicationsFilterTable.tsx
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/utils/navigation.ts
Labels: automerge

#15143 fix(fa): Removing tax from children aid
  apps/financial-aid/web-veita/src/components/ModalTypes/AcceptModal.tsx
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: automerge

#15145 fix(inheritance-report): fixes EFS 7.06
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsOverview/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/heirs.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/inheritance.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/overview.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#15151 fix(application-system): Remove unnecessary logging for validation errors
  apps/application-system/api/src/app/modules/application/tools/applicationTemplateValidation.service.ts
Labels: automerge

#15147 feat(web): Charts - Allow y axis ticks to be set manually in the cms
  apps/web/components/Charts/v2/types/index.ts
  apps/web/components/Charts/v2/utils/chart.tsx
Labels: automerge

#15128 chore(ids-api): Handle missing data in national registry v3 client.
  libs/clients/national-registry/v3/src/lib/nationalRegistryV3.service.ts
Labels: automerge

#15155 chore(ids-api): Add client id for national registry v3 on prod.
  charts/identity-server/values.prod.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15025 chore(documents): logging for documents v2 single doc
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
Labels: automerge

#15111 feat(core): Make <FormStepper /> use new FormStepperV2
  libs/application/ui-shell/src/components/FormStepper.tsx
  libs/application/ui-shell/src/hooks/useIsMobile.ts
  libs/application/ui-shell/src/hooks/useIsWindowSize.ts
  libs/application/ui-shell/src/lib/FormShell.spec.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/application/utils/src/index.ts
  libs/application/utils/src/lib/excludesFalse.ts
Labels: automerge

#15135 chore(application-system): remove padding for component that shouldn't render
  libs/application/templates/passport-annulment/src/forms/Draft.ts
  libs/application/templates/passport-annulment/src/forms/sections/overview.ts
  libs/application/templates/reference-template/src/forms/ExampleForm.ts
  libs/application/ui-shell/src/components/FormMultiField.tsx
Labels: automerge

#15159 fix(admin-portal): remove unused translations for delegation types
  libs/portals/admin/ids-admin/src/lib/messages.ts
Labels: automerge

#15105 feat(j-s): Prosecutor Asks for Cancellation
  apps/judicial-system/backend/migrations/20240531113155-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/defenceUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/districtCourtUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/prosecutionUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extend.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.spec.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#15140 feat(j-s): Actor title in indictment confirmation
  apps/judicial-system/backend/src/app/formatters/coatOfArms.ts
  apps/judicial-system/backend/src/app/formatters/confirmedIndictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
Labels: automerge

#15170 fix(service-portal): remove network only requests for docv2 list
  libs/service-portal/documents/src/hooks/useDocumentList.ts
Labels: automerge

#14950 fix(service-portal): Health UI tweaks
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
  libs/service-portal/health/src/components/TherapiesTabContent/TherapiesTabContent.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.tsx
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
Labels: automerge

#14952 fix(driving-license): BE License updates
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/EligibilitySummary.tsx
  libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/HealthDeclaration.tsx
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15163 feat(web): Add caching to uv radiation fetch calls
  libs/clients/ultraviolet-radiation/src/clientConfig.json
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.config.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.module.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.provider.ts
  libs/clients/ultraviolet-radiation/src/lib/ultraviolet-radiation.service.ts
Labels: automerge

#15171 feat(core): hide upload button in some cases
  libs/application/ui-components/src/utilities/FileUploadController/index.tsx
  libs/application/ui-fields/src/lib/FileUploadFormField/FileUploadFormField.tsx
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
Labels: automerge

#15161 fix(inheritance-report): EFS touch ups
  libs/application/templates/inheritance-report/src/components/NumberInput/index.tsx
  libs/application/templates/inheritance-report/src/fields/BusinessAssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsOverview/index.tsx
  libs/application/templates/inheritance-report/src/fields/LookupPerson/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/fields/SpouseEstateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/forms/done.ts
  libs/application/templates/inheritance-report/src/forms/sections/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/overview.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#15088 feat(license-service): less contentful
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.resolver.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/api/domains/license-service/tsconfig.lib.json
Labels: automerge

#14791 chore(user-profile): Remove migration worker and make user profile strict
  apps/services/auth/ids-api/src/app/user-profile/user-profile.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-profile/infra/service-portal-api.ts
  apps/services/user-profile/migrations/20240513221742-remove-migration-table.js
  apps/services/user-profile/project.json
  apps/services/user-profile/src/app/user-profile/dto/confirmEmailDto.ts
  apps/services/user-profile/src/app/user-profile/dto/confirmSmsDto.ts
  apps/services/user-profile/src/app/user-profile/emailVerification.model.ts
  apps/services/user-profile/src/app/user-profile/pipes/userProfileByNationalId.pipe.ts
  apps/services/user-profile/src/app/user-profile/smsVerification.model.ts
  apps/services/user-profile/src/app/user-profile/userDeviceTokens.model.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/userProfile.service.ts
  apps/services/user-profile/src/app/user-profile/userToken.controller.ts
  apps/services/user-profile/src/app/utils/format-phone-number.ts
  apps/services/user-profile/src/app/v2/dto/actor-profile.dto.ts
  apps/services/user-profile/src/app/v2/dto/islyklar-upsert.dto.ts
  apps/services/user-profile/src/app/v2/dto/post-nudge.dto.ts
  apps/services/user-profile/src/app/v2/dto/user-profile.dto.ts
  apps/services/user-profile/src/app/v2/user-profile.module.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  apps/services/user-profile/src/app/worker/test/worker.spec.ts
  apps/services/user-profile/src/app/worker/types.ts
  apps/services/user-profile/src/app/worker/userProfileAdvania.model.ts
  apps/services/user-profile/src/app/worker/worker.module.ts
  apps/services/user-profile/src/app/worker/worker.service.ts
  apps/services/user-profile/src/app/worker/worker.utils.ts
  apps/services/user-profile/src/config.ts
  apps/services/user-profile/src/environments/environment.ts
  apps/services/user-profile/src/main.ts
  apps/services/user-profile/src/worker.ts
  apps/services/user-profile/tsconfig.json
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/api/domains/user-profile/src/lib/userProfile.model.ts
Labels: automerge

#15149 feat(j-s): Actor title in indictment confirmation pt2
  apps/judicial-system/backend/src/app/formatters/PDFKitCoatOfArms.ts
  apps/judicial-system/backend/src/app/formatters/confirmedIndictmentPdf.ts
Labels: automerge

#14609 feat(driving-instructor-registrations): Add tabs for B and BE license
  libs/api/domains/driving-license-book/src/index.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenceBook.type.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenseBook.resolver.ts
  libs/api/domains/driving-license-book/src/lib/drivingLicenseBook.service.ts
  libs/api/domains/driving-license-book/src/lib/dto/student.input.ts
  libs/api/domains/driving-license-book/src/lib/utils/drivingLicenseBookMapper.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/forms/instructorRegistrations.ts
  libs/application/templates/driving-instructor-registrations/src/graphql/queries.ts
  libs/application/templates/driving-instructor-registrations/src/lib/InstructorRegistrationsTemplate.ts
  libs/application/templates/driving-instructor-registrations/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
  libs/application/templates/driving-instructor-registrations/src/types/enums.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/driving-license.ts
  libs/clients/driving-license-book/src/clientConfig.json
  libs/clients/driving-license-book/src/lib/drivingLicenseBookClient.service.ts
  libs/clients/driving-license-book/src/lib/drivingLicenseBookType.types.ts
  libs/clients/driving-license-book/src/utils/mappers.ts
Labels: automerge

#15177 fix(ojoi): Datepicker default date
  libs/application/templates/official-journal-of-iceland/src/fields/Publishing.tsx
Labels: automerge

#15178 fix(application-system): formstepper formatMessage
  libs/application/ui-shell/src/components/FormStepper.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
Labels: automerge

#15172 feat(j-s): Robot mail for received indictments
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentInfoToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentInfoToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.controller.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/lib/eventLog.ts
Labels: automerge

#15179 fix(auth-api-lib): add TR scopes for application system
  libs/auth-api-lib/seeders/data/add-social-insurance-api-scopes-to-clients-application-system.ts
Labels: automerge

#15148 fix:(endorsement): Update date validation
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/templates/general-petition/src/lib/dataSchema.ts
  libs/application/templates/general-petition/src/lib/generalPetitionUtils.ts
  libs/application/templates/general-petition/src/lib/messages.ts
Labels: automerge, autoupdate

#15184 fix(auth-api-lib): Add TR scopes for application system
  libs/auth-api-lib/seeders/data/add-social-insurance-api-scopes-to-clients-application-system.ts
Labels: automerge

#15183 fix(driving-license): fix eligibility check for driving-license
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
Labels: automerge

#15186 fix(application-system): formstepper empty state
  libs/application/ui-shell/src/components/FormStepper.tsx
Labels: automerge

#15185 fix(application-system): empty title for formStepper
  libs/application/ui-shell/src/components/FormStepper.tsx
Labels: automerge

#15154 feat(j-s): Complete Cancellation
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/Table/CourtDate/CourtDate.tsx
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/components/Table/index.ts
  apps/judicial-system/web/src/routes/Court/components/CasesInProgressTable/CasesInProgressTable.strings.ts
  apps/judicial-system/web/src/routes/Court/components/CasesInProgressTable/CasesInProgressTable.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumberInput.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Court/components/index.ts
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  apps/judicial-system/web/src/utils/testHelpers.tsx
Labels: automerge

#14583 chore: macos support for generate-changelog.sh
  scripts/generate-changelog.sh
Labels: automerge

#15194 fix(documents-v2): Add download URL to detail document v2
  libs/api/domains/documents/src/lib/documentV2.service.ts
Labels: automerge

#15195 feat(web): Generic List - Visual Changes
  apps/web/components/GenericList/GenericList.tsx
  apps/web/screens/GenericList/GenericListItem.tsx
Labels: automerge

#15165 feat(native-app): update skeleton loader for notifications
  apps/native/app/src/screens/notifications/notifications.tsx
  apps/native/app/src/ui/lib/card/notification-card.tsx
  apps/native/app/src/ui/lib/skeleton/list-item-skeleton.tsx
Labels: automerge

#15187 fix(libs+sessions): Add 202 response code handling to document decorator.
  libs/nest/swagger/src/lib/documentation.decorator.ts
Labels: automerge

#15198 feat(j-s): Add subpoenaType to Defendant table
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240611213639-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  apps/judicial-system/web/src/utils/hooks/useDefendants/createDefendant.graphql
  apps/judicial-system/web/src/utils/hooks/useDefendants/deleteDefendant.graphql
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/updateDefendant.graphql
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/defendant.ts
Labels: automerge

#15202 feat(web): Social Insurance Administration - header title color change
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#15152 feat(ui-core): isMulti option for Select
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/island-ui/core/src/lib/Select/Components/index.tsx
  libs/island-ui/core/src/lib/Select/Select.css.ts
  libs/island-ui/core/src/lib/Select/Select.stories.tsx
  libs/island-ui/core/src/lib/Select/Select.tsx
  libs/shared/form-fields/src/lib/SelectController/SelectController.tsx
Labels: automerge

#15188 fix(general-petition): max date in application
  libs/application/templates/general-petition/src/forms/form.ts
  libs/application/types/src/lib/Fields.ts
Labels: automerge, autoupdate

#15192 feat(application-system): stricter conditions on warnings
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection/accidentDetailSubSection.ts
Labels: automerge

#15203 chore(app): Upgrade app-auth library and bump app version
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
  apps/native/app/ios/Podfile.lock
  apps/native/app/package.json
  yarn.lock
Labels: automerge

#15193 feat: remove Ísland.is from display text
  libs/auth-api-lib/seeders/data/scope-application-system-admin.ts
  libs/portals/admin/application-system/src/lib/messages.ts
Labels: automerge

#15189 fix(auth-api-lib): stop updating refreshTokenExpiration when it's not in the payload
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
Labels: automerge

#15210 fix(driving-license-instructor): set dataprovider behind feature flag
  libs/application/templates/driving-instructor-registrations/src/forms/instructorRegistrations.ts
Labels: automerge

#15209 fix(driving-license-instructor): set dataprovider behind feature flag
  libs/application/templates/driving-instructor-registrations/src/forms/instructorRegistrations.ts
Labels: automerge, high priority

#14798 fix(native-app): Fix token refresh to logout
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/stores/environment-store.ts
Labels: automerge

#15211 fix(web): Remove autoAuth for PensionCalculatorApi due to 500 error when calculating pension
  libs/clients/social-insurance-administration/src/lib/apiProvider.ts
  libs/clients/social-insurance-administration/src/lib/configFactory.ts
Labels: automerge

#15212 fix(web): Hotfix - Remove autoAuth for PensionCalculatorApi due to 500 error when calculating pension #15211
  libs/clients/social-insurance-administration/src/lib/apiProvider.ts
  libs/clients/social-insurance-administration/src/lib/configFactory.ts
Labels: automerge

#15201 feat(j-s): Subpoena PDF
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/messages/index.ts
  apps/judicial-system/backend/src/app/messages/pdfSubpoena.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/web/src/types/index.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#15206 fix(j-s): Only display indictment appeal expiration on certain pages
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#15150 feat(native-app): Use new document endpoints for inbox
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/graphql/fragments/document.fragment.graphql
  apps/native/app/src/graphql/queries/inbox.graphql
  apps/native/app/src/lib/post-mail-action.ts
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/ui/lib/detail/header.tsx
  apps/native/app/src/ui/lib/list/list-item.tsx
Labels: automerge

#15103 ci: cache refactor
  .github/actions/get-cache/action.yml
  .github/actions/unit-test/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/ci/_common.mjs
  scripts/ci/cache/__config.mjs
  scripts/ci/cache/_common.mjs
  scripts/ci/cache/_const.mjs
  scripts/ci/cache/_get_hashes_utils.mjs
  scripts/ci/cache/_key_storage.mjs
  scripts/ci/cache/_restore_cache.mjs
  scripts/ci/cache/_save_cache.mjs
  scripts/ci/cache/_utils.mjs
  scripts/ci/cache/cache-action.mjs
  scripts/ci/cache/generate-files.sh
  scripts/ci/cache/package.json
  scripts/ci/cache/yarn.lock
  scripts/ci/get-node-modules-hash.mjs
Labels: automerge, deploy-feature, test everything

#15215 feat(web): Hotfix - Social Insurance Administration - header title color change (#15202)
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#15216 fix: increase time between retries
  scripts/ci/cache/_utils.mjs
Labels: automerge

#15217 ci: key generated files cache
  scripts/ci/cache/__config.mjs
  scripts/ci/cache/_utils.mjs
Labels: automerge

#15219 fix(service-portal): Update notification icon styling
  apps/service-portal/src/components/Notifications/NotificationLine.tsx
  apps/service-portal/src/components/Notifications/Notifications.css.ts
  libs/service-portal/core/src/components/ActionCard/ActionCard.css.ts
  libs/service-portal/documents/src/components/DocumentLine/AvatarImage.tsx
Labels: automerge

#15220 fix(citizenship): reverting fixes temporarily
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/InformationSection/FormerIcelanderSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/InformationSection/MaritalStatusSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/InformationSection/ParentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/supportingDocuments.ts
Labels: automerge

#15222 fix(application-system): Multi select in storybook
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.stories.mdx
Labels: automerge

#15224 chore(ids-api): Use national registry v3 dev service from staging.
  charts/identity-server/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15096 chore(application-system): Refactor env config
  apps/api/src/app/app.module.ts
  apps/api/src/app/environments/environment.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/environments/environment.ts
  libs/api/domains/criminal-record/src/lib/criminalRecord.module.ts
  libs/api/domains/criminal-record/src/lib/criminalRecord.spec.ts
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.module.ts
  libs/api/domains/health-insurance/src/lib/api-domains-health-insurance.spec.ts
  libs/api/domains/health-insurance/src/lib/healthInsurance.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/operating-license/operatingLicense.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.module.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/clients/althingi-ombudsman/src/lib/apiConfiguration.ts
  libs/clients/criminal-record/src/index.ts
  libs/clients/criminal-record/src/lib/apiConfiguration.ts
  libs/clients/criminal-record/src/lib/criminalRecordApi.config.ts
  libs/clients/criminal-record/src/lib/criminalRecordApi.module.ts
  libs/clients/data-protection-complaint/src/index.ts
  libs/clients/data-protection-complaint/src/lib/apiConfiguration.ts
  libs/clients/data-protection-complaint/src/lib/apis.ts
  libs/clients/data-protection-complaint/src/lib/config/config.ts
  libs/clients/data-protection-complaint/src/lib/data-protection-complaint-client.config.ts
  libs/clients/data-protection-complaint/src/lib/data-protection-complaint.module.ts
  libs/clients/icelandic-health-insurance/health-insurance/src/index.ts
  libs/clients/icelandic-health-insurance/health-insurance/src/lib/apiConfiguration.ts
  libs/clients/icelandic-health-insurance/health-insurance/src/lib/apis.ts
  libs/clients/icelandic-health-insurance/health-insurance/src/lib/clients-health-insurance-v2.config.ts
  libs/clients/icelandic-health-insurance/health-insurance/src/lib/clients-health-insurance-v2.module.ts
  libs/clients/vmst/src/index.ts
  libs/clients/vmst/src/lib/apiConfiguration.ts
  libs/clients/vmst/src/lib/apis.ts
  libs/clients/vmst/src/lib/vmst.config.ts
  libs/clients/vmst/src/lib/vmst.module.ts
Labels: automerge, deploy-feature

#15125 chore(clients-signature-collection): add tests
  libs/clients/signature-collection/jest.config.ts
  libs/clients/signature-collection/project.json
  libs/clients/signature-collection/src/lib/signature-collection.service.spec.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/clients/signature-collection/tsconfig.json
Labels: automerge

#15226 fix(native-app): no flicker on inbox screen for android
  apps/native/app/src/screens/inbox/inbox.tsx
Labels: automerge

#15228 chore(ids-api): Use national registry v3 dev service from staging. (#…
  charts/identity-server/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15153 feat(services-auth-api): Implement passkey registration and authentication
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/ids-api/src/app/app.module.ts
  apps/services/auth/ids-api/src/app/passkeys/dto/authenticationOptions.dto.ts
  apps/services/auth/ids-api/src/app/passkeys/passkeys.controller.ts
  apps/services/auth/ids-api/src/app/passkeys/passkeys.module.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  apps/services/auth/public-api/src/app/app.module.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/authenticationOptions.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/authenticationResponse.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/handleChallenge.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/registrationOptions.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/registrationResponse.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/dto/validateRegistration.dto.ts
  apps/services/auth/public-api/src/app/modules/passkeys/passkeys.controller.ts
  apps/services/auth/public-api/src/app/modules/passkeys/passkeys.module.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/api/domains/auth/src/lib/auth.module.ts
  libs/api/domains/auth/src/lib/dto/authenticationObject.input.ts
  libs/api/domains/auth/src/lib/dto/registrationObject.input.ts
  libs/api/domains/auth/src/lib/models/authenticationOptions.model.ts
  libs/api/domains/auth/src/lib/models/registrationOptions.model.ts
  libs/api/domains/auth/src/lib/models/verifyRegistration.model.ts
  libs/api/domains/auth/src/lib/resolvers/passkey.resolver.ts
  libs/api/domains/auth/src/lib/services/passkey.service.ts
  libs/auth-api-lib/migrations/20240422100000-create-passkeys.js
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/passkeys-core/models/passkey.model.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.cache.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.config.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.module.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.service.spec.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.service.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.utils.ts
  libs/clients/auth/public-api/src/lib/apis.ts
  libs/feature-flags/src/lib/features.ts
  package.json
  yarn.lock
Labels: automerge

#15231 fix(web): Language toggle not working for organization news
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
Labels: automerge

#15223 fix(parental-leave): Fix parental leave errors
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#15232 fix(web): Hotfix - Language toggle not working for organization news #15231
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
Labels: automerge

#15234 fix(native-app): offline banner now works correctly
  apps/native/app/src/components/offline/offline-banner.tsx
  apps/native/app/src/hoc/offline-hoc.tsx
  apps/native/app/src/screens/app-lock/app-lock.tsx
  apps/native/app/src/stores/auth-store.ts
Labels: automerge

#15235 fix(native-app): show personal info from cache if present
  apps/native/app/src/screens/more/personal-info.tsx
Labels: automerge

#15221 feat(web): Remove front page news
  apps/web/screens/Home/Home.tsx
Labels: automerge, deploy-feature

#15237 fix(driving-license): Hotfix - BE license fixes
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
Labels: automerge

#15245 fix(services-auth-public-api): Fix how max age days is set in passkey config
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.config.ts
Labels: automerge

#15218 fix(j-s): Only display cases with certain ruling decisions as up for review
  apps/judicial-system/web/src/routes/PublicProsecutor/Cases/PublicProsecutorCases.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#15249 fix(j-s): Cases Filtering
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
Labels: automerge

#15246 fix(native-app): offline mode more fixes
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/utils/app-lock.ts
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
Labels: automerge
