Repository island-is/island.is, pull requests merged in 2024-04, with the labels that each got.

#14296 fix(j-s): Appeal Ruling Validation
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge, ai-review

#14290 fix(j-s): Case ruling autofill
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
Labels: automerge, ai-review

#14198 chore(core): Cleanup unused fork of contentful extension
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalId.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getById.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentDeniedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAppealFilesUpdatedNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAppealJudgesAssignedNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendDefenderAssignedNotifications.spec.ts
  jest.resolver.js
  libs/shared/webpack/nrwl-config.js
  package.json
  yarn.lock
Labels: automerge, deploy-feature

#14329 fix(contentful-apps): Link group app - Make sure that nothing renders until load is complete
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
Labels: automerge

#14330 fix(web): Organization subpage links are missing bottom padding
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#14331 fix(web): News - embedded video goes above floated image
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
Labels: automerge

#14323 chore(island-ui): Input styling
  libs/island-ui/core/src/lib/Input/Input.mixins.ts
Labels: automerge

#14344 fix(contentful-apps): Hotfix - Link group app - Make sure that nothing renders until load is complete (#14329)
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
Labels: automerge

#14345 fix(web): Hotfix - News - embedded video goes above floated image (#14331)
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
Labels: automerge

#14346 fix(application-ctao): Remove complainee from payload and other minor fixes
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/complaints-to-althingi-ombudsman.utils.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/FieldTitle/FieldTitle.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/Prerequisites.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/ComplaintsToAlthingiOmbudsmanTemplate.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complainedFor.ts
Labels: automerge

#14354 chore(service-portal): Vehicles latest mileage registration
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
Labels: automerge

#14356 fix(service-portal): wrong license type
  libs/service-portal/licenses/src/utils/dataMapper.tsx
Labels: automerge

#14357 fix(service-portal): hotfix - mileage and type
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
  libs/service-portal/licenses/src/utils/dataMapper.tsx
Labels: automerge

#14341 feat(parental-leave): Add comment page
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/clients/vmst/src/clientConfig.yaml
Labels: automerge

#14351 feat(intellectual-properties): add locale support
  libs/api/domains/intellectual-properties/src/lib/dto/ip.input.ts
  libs/api/domains/intellectual-properties/src/lib/dto/ipCollection.input.ts
  libs/api/domains/intellectual-properties/src/lib/intellectalProperties.module.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.resolver.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/mapper.ts
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.tsx
Labels: automerge

#14308 feat(services-user-notification): send email to user delegations
  apps/services/auth/delegation-api/src/app/delegations/delegation-index.controller.ts
  apps/services/auth/delegation-api/src/app/delegations/delegations.controller.ts
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notification.model.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/helpers.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/test/globalSetup.ts
  apps/services/user-notification/test/globalTeardown.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/auth-api-lib/seeders/data/add-delegation-index-scope-to-notification-service.ts
  libs/auth-api-lib/seeders/data/helpers/addScopesToClient.ts
  libs/auth-api-lib/seeders/data/helpers/index.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/clients/auth/delegation-api/src/lib/api-configuration.ts
  libs/clients/auth/delegation-api/src/lib/apis.ts
  libs/clients/auth/delegation-api/src/lib/auth-delegation-api-client.config.ts
  libs/feature-flags/src/lib/features.ts
  libs/message-queue/src/lib/nest/queue.service.ts
Labels: automerge, ai-review

#14362 fix(parental-leave): Refactor residence grant
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#14347 feat(auth-api-lib): add findOrCreateSubjectId for delegations
  libs/auth-api-lib/src/lib/user-identities/user-identities.service.spec.ts
  libs/auth-api-lib/src/lib/user-identities/user-identities.service.ts
Labels: automerge

#14361 fix(readme): Add link to Getting Started on devland + yarn infra step
  README.md
Labels: automerge

#14336 fix(native-app): Bump Android version and build number
  apps/native/app/android/app/build.gradle
  apps/native/app/package.json
Labels: automerge

#14364 feat(web): Hotfix -Pension Calculator - Remove "has lived abroad" question for disability assessment type of pensions #14363
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14363 feat(web): Pension Calculator - Remove "has lived abroad" question for disability assessment type of pensions
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14358 chore(web): Service web - Add default placeholder text for search in other than icelandic locales
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
Labels: automerge

#14353 feat(user-notification): Hnipp email UI changes
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  libs/email-service/src/tools/design/styles.hbs
  libs/email-service/src/tools/design/subtitle.hbs
  libs/email-service/src/tools/design/tag.hbs
  libs/email-service/src/types/index.ts
Labels: automerge, ai-review

#14377 fix(web): Fix redirect functionality by also redirecting if there is not a CustomNextError thrown
  apps/web/pages/_error.tsx
  apps/web/utils/fetch404RedirectUrl.ts
  apps/web/utils/getServerSidePropsWrapper.ts
Labels: automerge

#14382 fix(sgs): Fixing default value for rearplate because of dataschema validation problem
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/PickPlateSize.tsx
Labels: automerge

#14383 fix(sgs): Fixing default value for rearplate because of dataschema validation problem
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/PickPlateSize.tsx
Labels: automerge

#14386 fix(signature-collection): area id error handling
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
Labels: automerge

#14378 feat(native-app): Add info alert to ehic cards
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
Labels: automerge

#14369 chore(j-s): Rewrite Message Handling
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/delete.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/deliverDefendantToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/file/internalFile.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAppealFilesUpdatedNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAppealJudgesAssignedNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendCourtDateNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendHeadsUpNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/index.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#14348 feat(j-s): Allow appeal when appeal decision in court is "not applicable"
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#14384 fix(service-user-notification): add missing env variables
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14387 fix(web): Hotfix - Fix redirect functionality by also redirecting if there is not a CustomNextError thrown (#14377)
  apps/web/pages/_error.tsx
  apps/web/utils/fetch404RedirectUrl.ts
  apps/web/utils/getServerSidePropsWrapper.ts
Labels: automerge

#14349 fix(estate): change done status to completed
  libs/application/templates/estate/src/lib/EstateTemplate.ts
Labels: automerge, deploy-feature

#14390 feat(web): Hotfix - Service web contact form disclaimer #14388
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/serviceWebPage.model.ts
Labels: automerge

#14385 feat(native-app): update hunting license logo and background
  apps/native/app/src/ui/assets/card/ust-logo.png
  apps/native/app/src/ui/assets/card/ust-logo@2x.png
  apps/native/app/src/ui/assets/card/ust-logo@3x.png
  apps/native/app/src/ui/assets/card/ust.png
  apps/native/app/src/ui/assets/card/ust@2x.png
  apps/native/app/src/ui/assets/card/ust@3x.png
  apps/native/app/src/ui/assets/card/veidikort.png
  apps/native/app/src/ui/assets/card/veidikort@2x.png
  apps/native/app/src/ui/assets/card/veidikort@3x.png
  apps/native/app/src/ui/lib/card/licence-card.tsx
  apps/native/app/src/ui/lib/scan-result-card/scan-result-card.tsx
Labels: automerge

#14372 fix(social-insurance-administration): Additional documents required error
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/AdditionalSupportForTheElderlyTemplate.spec.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/AdditionalSupportForTheElderlyTemplate.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/additionalSupportForTheElderlyUtils.ts
  libs/application/templates/social-insurance-administration/core/src/assets/Logo.tsx
  libs/application/templates/social-insurance-administration/core/src/lib/socialInsuranceAdministrationUtils.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.spec.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.spec.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.spec.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/pensionSupplementUtils.ts
Labels: automerge

#14394 fix(signature-collections): openlists and area error fixes
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
  libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts
Labels: automerge

#14393 feat(web): Pension Calculator - Offset start month by one
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14265 fix(passport-annulment): Application tweaks
  libs/application/templates/passport-annulment/src/fields/PassportSelection/index.tsx
  libs/application/templates/passport-annulment/src/forms/Done.ts
  libs/application/templates/passport-annulment/src/forms/sections/info.ts
  libs/application/templates/passport-annulment/src/forms/sections/overveiw.ts
  libs/application/templates/passport-annulment/src/lib/PassportAnnulmentTemplate.ts
  libs/application/templates/passport-annulment/src/lib/constants.ts
  libs/application/templates/passport-annulment/src/lib/dataSchema.ts
  libs/application/templates/passport-annulment/src/lib/error.ts
  libs/application/templates/passport-annulment/src/lib/messages.ts
Labels: automerge

#14334 chore(scripts): Add `--dist` option to `clean.sh` and minor cleanup in `scripts/*`
  scripts/ci/20_check-formatting.sh
  scripts/ci/30_test.sh
  scripts/ci/40_e2e.sh
  scripts/ci/90_docker-express.sh
  scripts/ci/ci.sh
  scripts/clean.sh
Labels: automerge

#14208 chore(j-s): Table refactoring
  apps/judicial-system/web/src/components/ContextMenu/ContextMenu.strings.ts
  apps/judicial-system/web/src/components/ContextMenu/ContextMenu.tsx
  apps/judicial-system/web/src/components/ReactTable/Table.css.ts
  apps/judicial-system/web/src/components/ReactTable/Table.tsx
  apps/judicial-system/web/src/components/Table/Table.strings.ts
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
Labels: automerge

#14395 fix(native-app): more screen, fix Loftbrú out of view on small screens and not scrollable in view
  apps/native/app/src/screens/more/more.tsx
Labels: automerge

#14389 feat(j-s): Robot Email Changes
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/migrations/20240405115305-create-sequence.js
  apps/judicial-system/backend/src/app/modules/court/court.config.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#14404 fix(unviersity-gateway): removing one state in application
  libs/application/templates/university/src/lib/UniversityTemplate.ts
Labels: automerge

#14322 fix(native-app): Fix typecheck in native app
  apps/native/app/package.json
  apps/native/app/src/graphql/use-fragment.ts
  apps/native/app/src/lib/show-picker.ts
  apps/native/app/src/react-native.d.ts
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
  apps/native/app/src/ui/lib/card/finance-status-card.tsx
  apps/native/app/src/utils/lifecycle/setup-dev-menu.ts
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
  apps/native/app/src/utils/lifecycle/setup-globals.ts
  apps/native/app/tsconfig.json
Labels: automerge

#14400 feat(web): Finetune search results when typing "Tryggingastofnun" keywords
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge

#14401 feat(j-s): Appeal Received Date
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverAppealReceivedDateToCourtOfAppeals.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverAppealReceivedDateToCourtOfAppealsGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#14406 feat(web): Hotfix - Finetune search results when typing "Tryggingastofnun" keywords (#14400)
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge

#14408 feat(web): Hotfix - Social Insurance Administration - Service web header #14402
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.css.ts
  apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.tsx
Labels: automerge

#14402 feat(web): Social Insurance Administration - Service web header
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.css.ts
  apps/web/components/ServiceWeb/Background/Variations/SocialInsuranceAdministration/SocialInsuranceAdministration.tsx
Labels: automerge

#14381 fix(ip): better name handling
  libs/api/domains/intellectual-properties/src/lib/dto/ip.input.ts
  libs/api/domains/intellectual-properties/src/lib/dto/ipCollection.input.ts
  libs/api/domains/intellectual-properties/src/lib/intellectalProperties.module.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.resolver.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/mapper.ts
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.tsx
Labels: automerge

#14375 fix(contentful-apps): Content import app - Read from select what tab to open from an excel file
  apps/contentful-apps/components/content-import/FileInput.tsx
Labels: automerge

#14407 feat(web): Hotfix - Pension Calculator - Offset start month by one (#14393)
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14396 fix(passport-annulment): further improvements
  libs/application/templates/passport-annulment/src/forms/sections/info.ts
  libs/application/templates/passport-annulment/src/forms/sections/overveiw.ts
  libs/application/templates/passport-annulment/src/lib/PassportAnnulmentTemplate.ts
  libs/application/templates/passport-annulment/src/lib/dataSchema.ts
  libs/application/templates/passport-annulment/src/lib/messages.ts
Labels: automerge

#14411 chore(gbh): Extend inReview lifetime
  libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts
Labels: automerge

#14409 chore(gbh): Extend inreview lifetime
  libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts
Labels: automerge

#14399 chore(native-app): update android build readme
  apps/native/app/README.md
  apps/native/app/patches/expo-modules-core+1.1.1.patch
  apps/native/app/patches/react-native+0.71.1.patch
Labels: automerge

#14412 chore: prepare for upgrading to kubernetes 1.26
  infra/helm/libs/api-template/templates/hpa.yaml
Labels: automerge

#14410 feat(j-s): Court Robot Email
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverAssignedRolesToCourtOfAppeals.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverAssignedRolesToCourtOfAppealsGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverReceivedDateToCourtOfAppeals.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverReceivedDateToCourtOfAppealsGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  libs/judicial-system/message/src/index.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#14355 feat(ir): cohabitation and separate asset share check
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/components/DeceasedShare/index.tsx
  libs/application/templates/inheritance-report/src/components/DoubleColumnRow/index.tsx
  libs/application/templates/inheritance-report/src/components/ShareInput/index.tsx
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalDebts/index.tsx
  libs/application/templates/inheritance-report/src/fields/DeceasedShareField/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/OtherAssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/fields/styles.css.ts
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/business.ts
  libs/application/templates/inheritance-report/src/forms/sections/debts.ts
  libs/application/templates/inheritance-report/src/forms/sections/deceased.ts
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/constants.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#14415 feat(api): xroad configuration for offical journal service
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/dmr/src/lib/dmrClient.config.ts
  libs/clients/dmr/src/lib/dmrClient.provider.ts
Labels: automerge

#14418 fix(native-app): Fix license barcode expire time
  apps/native/app/src/graphql/queries/licenses.graphql
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  libs/api/domains/license-service/src/lib/dto/CreateBarcodeResult.dto.ts
  libs/services/license/src/lib/barcode.service.ts
Labels: automerge

#14405 feat(j-s): Judge can return an indictment to prosecutor
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240408113716-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.css.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Court/Indictments/ReturnIndictmentCaseModal/ReturnIndictmentCaseModal.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/ReturnIndictmentCaseModal/ReturnIndictmentCaseModal.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#14422 fix(license-service): Fix license barcode expire time
  libs/api/domains/license-service/src/lib/dto/CreateBarcodeResult.dto.ts
  libs/services/license/src/lib/barcode.service.ts
Labels: automerge

#14425 chore(application-system): add xroad def to infra
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14419 feat(web): University studies header - Style using media queries
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesHeader.tsx
Labels: automerge

#14427 fix(api): adding ojoi xroad config to application system api
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14433 fix: Adding new login (keeping old for backwards compatability)
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/support/session.ts
Labels: automerge

#14432 feat(ojoi): Adding institution to submitted application
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Publishing.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/OJOIApplication.ts
Labels: automerge

#14434 fix(native-app): fix barcode loading state
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
Labels: automerge

#14360 fix(parental-leave): Edit or add periods error
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge, ai-review

#14437 chore(application-system): add to service
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14421 build(native-app): Preparing app for version 1.2.6
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#14435 fix(parental-leave): Move Additional documents and Comment to new section
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#14443 build(native-app): Update app build number
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#14444 fix(native-app): Fix license ehic info alert
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
Labels: automerge

#14431 feat(delegation-api): add incoming delegations lookup to delegation index
  .github/CODEOWNERS
  apps/services/auth/delegation-api/src/app/delegations/delegations.controller.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller-test-types.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller.test-cases.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#14420 feat(web): University studies - Redirect /s and /en/o routes
  apps/web/pages/en/o/university-studies/[...subpage].ts
  apps/web/pages/en/o/university-studies/index.ts
  apps/web/pages/s/haskolanam/[...subpage].ts
  apps/web/pages/s/haskolanam/index.ts
Labels: automerge

#14445 build(native-app): Update build number to 143
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#14352 chore: remove postinstall script
  apps/system-e2e/README.md
  package.json
  scripts/infra-cmds.js
Labels: automerge

#14373 chore(core): Refactoring `withCache` to automatically detect known header key patterns
  libs/clients/middlewares/README.md
  libs/clients/middlewares/src/index.ts
  libs/clients/middlewares/src/lib/withCache/withCache.spec.ts
  libs/clients/middlewares/src/lib/withCache/withCache.ts
  libs/clients/rsk/relationships/src/lib/apiConfiguration.ts
  libs/clients/user-profile/src/lib/apiConfiguration.ts
Labels: automerge

#14439 feat(web): Hotfix - add associated domains
  apps/native/app/ios/IslandApp/IslandApp.entitlements
  apps/web/public/.well-known/apple-app-site-association
  apps/web/public/.well-known/assetlinks.json
Labels: automerge

#14376 feat(delegation-index): Add subject id to delegation index records
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index-test-cases.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index.service.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-outgoing.spec.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  libs/auth-api-lib/migrations/20240327103605-add-subject-id-to-delegation-index.js
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/delegations/dto/delegation-index.dto.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation-index.model.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/services/auth/testing/src/fixtures/types.ts
Labels: automerge

#14438 feat(web): Add associated domains
  apps/native/app/ios/IslandApp/IslandApp.entitlements
  apps/web/public/.well-known/apple-app-site-association
  apps/web/public/.well-known/assetlinks.json
Labels: automerge

#14429 chore(search-indexer): By default skip resolving nested entries locally
  apps/services/search-indexer/README.md
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/content-search-indexer/src/environments/environment.ts
  libs/content-search-indexer/src/lib/cache-invalidation.service.ts
Labels: automerge

#14453 fix(general-petitions): signedlist listid
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
Labels: automerge

#14454 fix(general-petitions): Hotfix/petitions fix listid
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
Labels: automerge

#14428 feat(estate): allow member without contact member
  libs/application/template-api-modules/src/lib/modules/templates/estate/consts.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/types/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/estate/src/types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
Labels: automerge, deploy-feature

#14457 fix(general-petitions): Hotfix/petitions no polling
  apps/web/screens/PetitionView/PetitionView.tsx
  apps/web/screens/PetitionView/queries.ts
  libs/service-portal/petitions/src/screens/hooks.ts
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#14458 ci: set DD_GIT_COMMIT_SHA env in docker images for source code tracing
  .github/workflows/push.yml
  scripts/ci/Dockerfile
Labels: automerge

#14455 feat(ojoi): Adding submitted state to the application
  libs/application/templates/official-journal-of-iceland/src/fields/Submitted.tsx
  libs/application/templates/official-journal-of-iceland/src/forms/Submitted.ts
  libs/application/templates/official-journal-of-iceland/src/lib/OJOIApplication.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/complete.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/submitted.tsx
  libs/application/templates/official-journal-of-iceland/src/screens/SubmittedScreen.tsx
  libs/application/templates/official-journal-of-iceland/src/screens/index.ts
Labels: automerge

#14464 chore(web): Pension Calculator - Read currency input max length from config
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14463 fix(j-s): Add scheduled info card component for defenders
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
Labels: automerge

#14468 fix(user-profile-worker): Set nextNudge to null when nudgeLastAsked has no value and remove islykill cert as dependency
  apps/services/user-profile/infra/service-portal-api.ts
  apps/services/user-profile/src/app/worker/worker.service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#14451 feat(university-gateway): Adding a sitemap so google can index programmes properly
  apps/web/pages/en/university-studies/sitemap.xml.tsx
  apps/web/pages/haskolanam/sitemap.xml.tsx
  apps/web/screens/UniversitySearch/Sitemap.tsx
  apps/web/screens/queries/UniversityGateway.ts
Labels: automerge

#14473 fix(university-gateway): Renaming query to fix duplicate query name issue holding up pipelines
  apps/web/screens/queries/UniversityGateway.ts
Labels: automerge

#14469 feat(web): Add rich text field in featured article content type for intro text
  apps/web/components/Organization/Slice/FeaturedArticles/FeaturedArticlesSlice.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/featuredArticles.model.ts
Labels: automerge

#14474 fix(external-contracts-tests): added missing tsconfig.spec.json
  apps/external-contracts-tests/tsconfig.spec.json
Labels: automerge

#14092 fix(parental-leave): Refactor state machine and update documentation
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/README.md
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart.drawio
  libs/application/templates/parental-leave/assets/parental-leave-flow-chart.png
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#14479 fix(fa): Revert Adding swagger ui to esbuild
  apps/financial-aid/open-api/esbuild.json
Labels: automerge

#14288 feat(service-portal): Housing benefits frontend + api
  apps/api/src/app/app.module.ts
  apps/service-portal/src/auth.ts
  libs/api/domains/housing-benefits/.eslintrc.json
  libs/api/domains/housing-benefits/README.md
  libs/api/domains/housing-benefits/jest.config.ts
  libs/api/domains/housing-benefits/project.json
  libs/api/domains/housing-benefits/src/index.ts
  libs/api/domains/housing-benefits/src/lib/dto/getHmsLoansPaymenthistory.input.ts
  libs/api/domains/housing-benefits/src/lib/housing-benefits.module.ts
  libs/api/domains/housing-benefits/src/lib/housing-benefits.resolver.ts
  libs/api/domains/housing-benefits/src/lib/models/housingBenefit.model.ts
  libs/api/domains/housing-benefits/tsconfig.json
  libs/api/domains/housing-benefits/tsconfig.lib.json
  libs/api/domains/housing-benefits/tsconfig.spec.json
  libs/clients/hms-housing-benefits/src/clientConfig.json
  libs/clients/hms-housing-benefits/src/index.ts
  libs/clients/hms-housing-benefits/src/lib/hms-housing-benefits.module.ts
  libs/clients/hms-housing-benefits/src/lib/hms-housing-benefits.service.ts
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/core/src/hooks/useDynamicRoutes/paths.ts
  libs/service-portal/core/src/hooks/useDynamicRoutes/useDynamicRoutes.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/utils/dateUtils.ts
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefits.css.ts
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFooter.tsx
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsTable.tsx
  libs/service-portal/finance/src/financeRedirects.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/lib/navigation.ts
  libs/service-portal/finance/src/lib/paths.ts
  libs/service-portal/finance/src/module.tsx
  libs/service-portal/finance/src/screens/HousingBenefits/HousingBenefits.graphql
  libs/service-portal/finance/src/screens/HousingBenefits/HousingBenefits.tsx
  libs/service-portal/finance/src/screens/HousingBenefits/index.ts
  libs/service-portal/finance/src/utils/dataHeaders.ts
  libs/service-portal/finance/src/utils/filesHousingBenefits.ts
  libs/service-portal/finance/src/utils/generateMonthArray.ts
  tsconfig.base.json
Labels: automerge

#14476 feat(web): Pension Calculator - Print screen view for results
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
Labels: automerge

#14481 fix(general-petitions): Hotfix/petitions tagged signedlists
  libs/api/domains/endorsement-system/src/lib/dto/endorsementPagination.input.ts
  libs/service-portal/petitions/src/screens/hooks.ts
Labels: automerge

#14462 feat(e2e): more test for health registrations
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/health.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
  libs/service-portal/health/src/utils/FileBreakdown/filesStructure.ts
  tsconfig.base.json
Labels: automerge

#14486 fix(general-petitions): Hotfix/general petitions nolimit tags
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#14465 feat(j-s): Return a formatted address for place of crime
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/getPoliceCaseInfo.spec.ts
Labels: automerge

#14480 fix(fa): Adding swagger ui to esbuild
  apps/financial-aid/open-api/esbuild.json
Labels: automerge

#14471 feat(parental-leave): Add file upload for changing employer
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Attachments.tsx
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge

#14489 fix(petitions): small revert - web - limit 1000
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge, high priority

#14475 feat(j-s): Case Files to Court of Appeals
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/aws-s3/awsS3.config.ts
  apps/judicial-system/backend/src/app/modules/aws-s3/awsS3.service.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.config.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/file.module.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/internalFile.controller.ts
  apps/judicial-system/backend/src/app/modules/file/limitedAccessFile.controller.ts
  apps/judicial-system/backend/src/app/modules/file/test/createTestingFileModule.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/createCaseFile.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrl.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/uploadCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtOfAppeals.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtOfAppealsGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createCaseFile.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/getCaseFileSignedUrl.spec.ts
  apps/judicial-system/backend/src/app/modules/index.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#14477 feat(j-s): Correction Flag to Court Robot
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCaseGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extend.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extendGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getAllGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getByIdGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCourtRecordPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseConclusionToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/test/random.ts
Labels: automerge

#14467 feat(web): Livechat for Administration of Occupational Safety and Health
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  package.json
  yarn.lock
Labels: automerge

#14283 feat(system-e2e): Move system-e2e to NX
  .gitignore
  .vscode/extensions.json
  apps/system-e2e/.babelrc
  apps/system-e2e/.eslintrc.json
  apps/system-e2e/.gitignore
  apps/system-e2e/README.md
  apps/system-e2e/build.sh
  apps/system-e2e/e2e/example.spec.ts
  apps/system-e2e/entrypoint.sh
  apps/system-e2e/package.json
  apps/system-e2e/playwright.config.ts
  apps/system-e2e/project.json
  apps/system-e2e/src/playwright.config.ts
  apps/system-e2e/src/support/urls.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/support/wire-mocks.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-application.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-permission.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/car-recycling.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/criminal-record.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/data-protection-complaint.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-school-confirmation.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/no-debt-certificate.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/operating-licence.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/setup-xroad.mocks.ts
  apps/system-e2e/src/tests/islandis/application-system/smoke/p-sign.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-unauthenticated.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/assets.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control-consents.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/auth-utils.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/auth.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financial-payment-application.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financials.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/information.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/occupational-licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/service-portal.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/university.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-license.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-machines.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/search.spec.ts
  apps/system-e2e/tsconfig.json
  nx.json
  package.json
  scripts/local-e2e.sh
  yarn.lock
Labels: automerge

#14482 feat(ojoi): Added comment screen to application
  libs/application/templates/official-journal-of-iceland/src/components/comments/AddComment.tsx
  libs/application/templates/official-journal-of-iceland/src/components/comments/Comment.tsx
  libs/application/templates/official-journal-of-iceland/src/components/comments/CommentList.tsx
  libs/application/templates/official-journal-of-iceland/src/components/comments/Comments.css.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Comments.tsx
  libs/application/templates/official-journal-of-iceland/src/forms/DraftRetry.ts
  libs/application/templates/official-journal-of-iceland/src/lib/OJOIApplication.ts
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/comments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/general.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/application/templates/official-journal-of-iceland/src/screens/CommentsScreen.tsx
  libs/application/templates/official-journal-of-iceland/src/screens/index.ts
Labels: automerge

#14493 feat(e2e): add tests and refactor structure
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/assets.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/healthInsurance.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/socialInsurance.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/social-insurance.spec.ts
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge

#14483 fix(j-s): Stepper indictment sections for defender
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#14500 revert: "feat(system-e2e): Move system-e2e to NX (#14283)"
  .gitignore
  .vscode/extensions.json
  apps/system-e2e/.babelrc
  apps/system-e2e/.eslintrc.json
  apps/system-e2e/.gitignore
  apps/system-e2e/README.md
  apps/system-e2e/build.sh
  apps/system-e2e/e2e/example.spec.ts
  apps/system-e2e/entrypoint.sh
  apps/system-e2e/package.json
  apps/system-e2e/playwright.config.ts
  apps/system-e2e/project.json
  apps/system-e2e/src/playwright.config.ts
  apps/system-e2e/src/support/urls.ts
  apps/system-e2e/src/support/utils.ts
  apps/system-e2e/src/support/wire-mocks.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-application.spec.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/tenant-permission.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/car-recycling.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/criminal-record.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/data-protection-complaint.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/driving-school-confirmation.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/no-debt-certificate.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/operating-licence.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/setup-xroad.mocks.ts
  apps/system-e2e/src/tests/islandis/application-system/smoke/p-sign.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-authenticated.spec.ts
  apps/system-e2e/src/tests/islandis/consultation-portal/smoke/consultation-portal-unauthenticated.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/assets.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control-consents.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/auth-utils.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/auth.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/company-delegation.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financial-payment-application.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/financials.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/inbox.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/information.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/occupational-licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/service-portal.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/sessions.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/university.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/vehicles.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-license.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/work-machines.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/homepage.spec.ts
  apps/system-e2e/src/tests/islandis/web/smoke/search.spec.ts
  apps/system-e2e/tsconfig.json
  nx.json
  package.json
  scripts/local-e2e.sh
  yarn.lock
Labels: automerge

#14499 chore(web): Remove chat from "HMS" and "Tryggingastofnun" articles
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#14310 feat(user-profile): Migration Date verification
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-profile/src/app/app.module.ts
  apps/services/user-profile/src/app/types/ClientType.ts
  apps/services/user-profile/src/app/user-profile/verification.service.ts
  apps/services/user-profile/src/app/v2/dto/user-profile.dto.ts
  apps/services/user-profile/src/app/v2/me-user-profile.controller.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/test/user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.controller.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  apps/services/user-profile/src/app/worker/worker.module.ts
  apps/services/user-profile/src/app/worker/worker.service.ts
  apps/services/user-profile/src/config.ts
  apps/services/user-profile/src/environments/environment.ts
Labels: automerge, ai-review

#14501 fix(web): Secondary menu appearing on mobile when it shouldn't
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#14446 feat(j-s): Return indictment messages
  apps/judicial-system/backend/migrations/20240409124300-update-notification.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentReturnedNotifications.spec.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#14459 feat(user-profile): implement actor profiles in user profile service
  apps/services/user-profile/migrations/20240408162626-create-actor-profile.js
  apps/services/user-profile/src/app/app.module.ts
  apps/services/user-profile/src/app/v2/dto/actor-profile.dto.ts
  apps/services/user-profile/src/app/v2/me-user-profile.controller.ts
  apps/services/user-profile/src/app/v2/models/actor-profile.model.ts
  apps/services/user-profile/src/app/v2/test/me-user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/test/user-profile.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.controller.ts
  apps/services/user-profile/src/app/v2/user-profile.module.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  apps/services/user-profile/test/fixture-factory.ts
Labels: automerge

#14496 fix(sgs): km registration fix
  libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.module.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/clients/vehicles/project.json
  libs/clients/vehicles/src/clientConfig.json
Labels: automerge

#14488 feat(web): Form - Fetch translations on the client
  apps/web/components/Form/Form.tsx
  apps/web/screens/AnchorPage/AnchorPage.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/LifeEventPage/LifeEventPage.tsx
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/UniversitySearch/UniversitySubPage.tsx
  apps/web/utils/richText.tsx
Labels: automerge

#14511 feat(web): Organization page - show that frontpage link is active if present
  apps/web/screens/Organization/Home/Home.tsx
Labels: automerge

#14503 fix(estate): modify property number in needed before looking up
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
Labels: automerge

#14502 fix(sgs): km registration bug fix/change
  libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.module.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/error.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/error.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/clients/vehicles/project.json
  libs/clients/vehicles/src/clientConfig.json
Labels: automerge

#14514 fix(aosh): Adding extra data to eigendaskipti tækis
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/getExtraData.ts
Labels: automerge

#14515 fix(aosh): Adding extra data to eigendaskipti tækis
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/getExtraData.ts
Labels: automerge

#14507 feat(j-s): Robot Log
  apps/judicial-system/backend/migrations/20240416110933-create-robot-log.js
  apps/judicial-system/backend/src/app/modules/court/court.module.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/models/robotLog.model.ts
  apps/judicial-system/backend/src/app/modules/court/test/createTestingCourtModule.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourtOfAppeals.spec.ts
Labels: automerge

#14522 fix(web): Asset title appearing as item in table of contents
  apps/web/utils/navigation.ts
Labels: automerge

#14509 feat(user-notifications): fetch actor profile when sending emails to delegation holders
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
Labels: automerge

#14506 fix(consultation-portal): KAM-2369: Add html heading tags
  apps/consultation-portal/components/Card/Card.tsx
  apps/consultation-portal/components/Error/Error404/Error404.tsx
  apps/consultation-portal/components/LogoText/LogoText.tsx
  apps/consultation-portal/screens/About/components/AboutContent/AboutContent.css.ts
  apps/consultation-portal/screens/About/components/AboutContent/AboutContent.tsx
  apps/consultation-portal/screens/About/components/AboutContent/AboutRTF.tsx
  apps/consultation-portal/screens/About/components/TableOfContents/TableOfContents.css.ts
  apps/consultation-portal/screens/About/components/TableOfContents/TableOfContents.tsx
  apps/consultation-portal/screens/Advices/Advices.tsx
  apps/consultation-portal/screens/Case/components/AdviceCard/AdviceCard.tsx
  apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/screens/Case/components/CaseTimeline/CaseTimeline.tsx
  apps/consultation-portal/screens/Case/components/RenderAdvices/RenderAdvices.tsx
  apps/consultation-portal/screens/Case/components/Stacked/Stacked.tsx
  apps/consultation-portal/screens/Home/components/Filter/components/Filterbox.tsx
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#14529 feat(web): Hotfix - Livechat for Administration of Occupational Safety and Health (#14467)
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/ArticleChatPanel.tsx
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  package.json
  yarn.lock
Labels: automerge

#14530 chore: grant application-system namespace
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14513 fix(consultation-portal): KAM-2371: Pagination tab virkni virkaði ekki
  apps/consultation-portal/components/Pagination/Pagination.tsx
Labels: automerge

#14461 feat(user-notifications): use 3rd party login in emails to delegation holders
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/src/config.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-notification/test/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14536 chore(housing-benefits): update codeowners
  .github/CODEOWNERS
Labels: automerge

#14524 chore(service-portal): Housing benefits additions
  libs/api/domains/housing-benefits/src/lib/models/housingBenefit.model.ts
  libs/clients/hms-housing-benefits/src/index.ts
  libs/clients/hms-housing-benefits/src/lib/enums.ts
  libs/clients/hms-housing-benefits/src/lib/hms-housing-benefits.service.ts
  libs/service-portal/core/src/utils/constants.ts
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefits.css.ts
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsTable.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/utils/dataHeaders.ts
  libs/service-portal/finance/src/utils/generateMonthArray.ts
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTableRow.tsx
  libs/service-portal/social-insurance-maintenance/src/lib/constants.ts
Labels: automerge

#14535 fix(web): KAM-2391: Fix layout shift in RettindagaeslaFatladsFolks
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/RettindagaeslaFatladsFolksHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RettindagaeslaFatladsFolksTheme/index.ts
Labels: automerge

#14532 feat(api): Sort children by descending age
  libs/api/domains/national-registry/src/lib/v3/broker.service.ts
Labels: automerge

#14528 fix(user-profile): infra config
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-profile/infra/service-portal-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14538 fix(sgs): Fixing km registration for radio field and adjust km reg field size
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleRadioField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
Labels: automerge

#14533 fix(api): Feature flag to disable national registry v1
  libs/api/domains/national-registry/src/lib/nationalRegistry.module.ts
  libs/api/domains/national-registry/src/lib/nationalRegistry.service.ts
  libs/api/domains/national-registry/src/lib/resolvers/child.resolver.ts
  libs/api/domains/national-registry/src/lib/resolvers/correction.resolver.ts
  libs/api/domains/national-registry/src/lib/resolvers/familyMember.resolver.ts
  libs/api/domains/national-registry/src/lib/resolvers/person.resolver.ts
  libs/api/domains/national-registry/src/lib/resolvers/user.resolver.ts
  libs/api/domains/national-registry/src/lib/shared/models/address.model.ts
  libs/api/domains/national-registry/src/lib/shared/models/banMarking.model.ts
  libs/api/domains/national-registry/src/lib/v1/types/user.type.ts
  libs/api/domains/national-registry/src/lib/v3/broker.service.ts
  libs/api/domains/national-registry/src/lib/v3/mapper.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#14543 fix(infra): Adding missing configs for vehicle-mileage xroad
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14544 fix(infra): Adding missing configs for vehicle-mileage xroad
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14545 fix(app): Update placeholder and length values in EditConfirmScreen
  apps/native/app/src/screens/settings/edit-confirm.tsx
Labels: automerge

#14547 feat(ojoi): Give assignees read and write permissions
  libs/application/templates/official-journal-of-iceland/src/lib/OJOIApplication.ts
Labels: automerge

#14548 fix(documents): Change logger from error to info
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
Labels: automerge
