Repository island-is/island.is, pull requests merged in 2024-03, with the labels that each got.

#13965 feat(gbh-application): Grindavik buyout additions
  apps/application-system/api/src/app/modules/application/tools/templateApiActionRunner.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/assets/Logo.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersOverview/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersRepeater/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/index.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/Approved.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/InReview.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/Prerequisites.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/Rejected.ts
  libs/application/templates/grindavik-housing-buyout/src/index.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/inReview.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/index.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/notEligible.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/prerequisites.ts
  libs/application/templates/grindavik-housing-buyout/src/utils/sections.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/StaticTableFormField/StaticTableFormField.tsx
Labels: automerge

#13967 feat(university-gateway): Add RU xroad
  apps/services/university-gateway/infra/university-gateway.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/agriculturalUniversityOfIcelandClient.config.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.config.ts
  libs/clients/university-application/holar-university/src/lib/holarUniversityClient.config.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/icelandUniversityOfTheArtsClient.config.ts
  libs/clients/university-application/reykjavik-university/src/clientConfig.json
  libs/clients/university-application/reykjavik-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/reykjavik-university/src/lib/reykjavikUniversityClient.config.ts
  libs/clients/university-application/university-of-akureyri/src/lib/universityOfAkureyriClient.config.ts
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.config.ts
Labels: automerge

#13790 feat(j-s): Update indictment introduction when name, national id or address change
  apps/judicial-system/web/pages/api/geoLocation/getCountryCode.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyer/getLawyer.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyers/getLawyers.ts
  apps/judicial-system/web/pages/api/nationalRegistry/getBusinessesByNationalId/index.ts
  apps/judicial-system/web/pages/api/nationalRegistry/getPersonByNationalId/index.ts
  apps/judicial-system/web/src/components/CaseResubmitModal/CaseResubmitModal.tsx
  apps/judicial-system/web/src/components/Table/DurationDate/DurationDate.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/WithdrawnAppealCase/WithdrawnAppealCase.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/CaseDocuments/CaseDocuments.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/restrictions.ts
Labels: automerge

#13976 fix(university-gateway): University day frontend changes
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/en/university-studies/info/[subSlug]/index.tsx
  apps/web/pages/haskolanam/upplysingar/[subSlug]/index.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/UniversitySearch/UniversitySubPage.tsx
Labels: automerge

#13963 fix(skilavottord): Disable my-cars page
  apps/skilavottord/web/screens/Overview/Overview.tsx
  apps/skilavottord/web/screens/RecycleCar/RecycleCar.tsx
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.spec.ts
  libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts
Labels: automerge

#13966 feat(delegation api): update delegation index when custom or personal representative delegations are updated
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-incoming.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegation-index.spec.ts
  apps/services/auth/personal-representative/src/app/app.module.ts
  apps/services/auth/personal-representative/src/app/modules/personalRepresentatives/personalRepresentatives.controller.ts
  apps/services/auth/personal-representative/src/app/modules/personalRepresentatives/personalRepresentatives.module.ts
  apps/services/auth/personal-representative/src/openApi.ts
  libs/auth-api-lib/migrations/20240229145515-add-primary-key-to-delegation-index.js
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation-index.model.ts
  libs/auth-api-lib/src/lib/personal-representative/services/personalRepresentative.service.ts
Labels: automerge

#13980 fix: hash files
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/_hash-generated-files.sh
Labels: automerge

#13985 fix: hash files (#13980)
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/_hash-generated-files.sh
Labels: automerge, high priority

#13974 feat(driving-licence-and-residence-history): Fix leap year logic
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/residence-history/src/lib/computeCountryResidence.spec.ts
Labels: automerge, high priority

#13939 feat(j-s): Flag for users who can confirm appeals
  apps/judicial-system/api/src/app/modules/user/dto/createUser.input.ts
  apps/judicial-system/api/src/app/modules/user/dto/updateUser.input.ts
  apps/judicial-system/api/src/app/modules/user/models/user.model.ts
  apps/judicial-system/backend/migrations/20240227123542-update-case.js
  apps/judicial-system/backend/src/app/modules/user/dto/createUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/interceptors/user.interceptor.ts
  apps/judicial-system/backend/src/app/modules/user/test/create.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getByNationalId.spec.ts
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/ProsecutorSelection/prosecutorSelectionUsers.graphql
  apps/judicial-system/web/src/components/UserProvider/currentUser.graphql
  apps/judicial-system/web/src/routes/Admin/ChangeUser/ChangeUser.tsx
  apps/judicial-system/web/src/routes/Admin/ChangeUser/user.graphql
  apps/judicial-system/web/src/routes/Admin/NewUser/NewUser.tsx
  apps/judicial-system/web/src/routes/Admin/NewUser/createUser.graphql
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  apps/judicial-system/web/src/routes/Admin/Users/users.graphql
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/SelectCourtOfficials/selectCourtOfficialsUsers.graphql
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/appealCaseUsers.graphql
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
  apps/judicial-system/web/src/routes/Shared/Cases/prisonCases.graphql
  apps/judicial-system/web/src/utils/hooks/useCase/limitedAccessUpdateCase.graphql
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  apps/judicial-system/web/src/utils/hooks/useSections/useSections.spec.tsx
  apps/judicial-system/web/src/utils/mocks.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#13989 feat(university-gateway): re-trigger codegen
  libs/clients/university-application/reykjavik-university/src/clientConfig.json
Labels: automerge

#13990 feat(university-gateway): re-trigger codegen
  libs/clients/university-application/reykjavik-university/src/clientConfig.json
Labels: automerge, skip-generated-cache

#13964 fix(web): Prune json fields from EmailSignup when mapping searchable content into Elasticsearch
  libs/cms/src/lib/search/importers/utils.ts
Labels: automerge

#13981 feat(web): Chatbot custom message for "Purchase of residential property in Grindavík" article
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#13982 chore(web): District commissioner chat bot should appear for all districts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#13971 feat(web): UI updates for Grindavík property purchase calculator
  apps/web/components/connected/GrindavikResidentialPropertyPurchaseCalculator/GrindavikResidentialPropertyPurchaseCalculator.css.ts
  apps/web/components/connected/GrindavikResidentialPropertyPurchaseCalculator/GrindavikResidentialPropertyPurchaseCalculator.tsx
Labels: automerge

#13994 feat(web): Pension Calculator - Fix translation strings and change UI according to new design
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
  apps/web/screens/queries/PensionCalculator.ts
  libs/api/domains/social-insurance/src/lib/models/pensionCalculation.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge

#13995 fix(signature-collections): sort candidates
  .github/CODEOWNERS
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
  libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts
Labels: automerge

#13993 fix(parental-leave): change text on external data page
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/employerValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
Labels: automerge

#13959 fix(EnergyFunds): Added FindVehicleFormField to EnergyFunds application
  libs/api/domains/energy-funds/src/lib/energyFunds.service.ts
  libs/api/domains/energy-funds/src/lib/graphql/main.resolver.ts
  libs/api/domains/energy-funds/src/lib/graphql/models/getVehicleWithGrant.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/types.ts
  libs/application/templates/energy-funds/src/fields/SelectVehicle/index.tsx
  libs/application/templates/energy-funds/src/graphql/queries.ts
  libs/application/templates/energy-funds/src/hooks/useLazyVehicleQuery.ts
  libs/application/templates/energy-funds/src/lib/messages/error.ts
  libs/application/templates/energy-funds/src/lib/messages/information.ts
  libs/application/templates/energy-funds/src/shared/types.ts
  libs/application/templates/energy-funds/src/utils/getSelectedVehicle.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.util.ts
Labels: automerge

#13996 feat(ghb): Updates, new screen and tweaks
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
Labels: automerge

#13969 chore: make new dmr apps comply with xroad standards
  apps/judicial-system/digital-mailbox-api/infra/judicial-system-xrd-robot-api.ts
  apps/judicial-system/robot-api/infra/judicial-system-xrd-robot-api.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/uber-charts/judicial-system.ts
Labels: automerge, deploy-feature

#13987 feat(delegation-api): add custom delegation scope field to delegation index
  apps/services/auth/delegation-api/src/app/login-restrictions/me-login-restrictions.controller.auth.spec.ts
  apps/services/auth/delegation-api/src/app/login-restrictions/me-login-restrictions.controller.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegation-index.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-types.ts
  apps/services/auth/ids-api/src/app/login-restrictions/login-restrictions.controller.spec.ts
  apps/services/auth/personal-representative/src/app/modules/personalRepresentatives/e2e/personalRepresentatives.spec.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation-index.model.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#13962 feat(web): Chart improvements
  apps/web/components/Charts/v2/constants.ts
  apps/web/components/Charts/v2/hooks/data.ts
  apps/web/components/Charts/v2/renderers/ChartComponentRenderer.tsx
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
  apps/web/components/Charts/v2/renderers/ChartRenderer.tsx
  apps/web/components/Charts/v2/renderers/LegendRenderer.tsx
  apps/web/components/Charts/v2/types/index.ts
  apps/web/components/Charts/v2/utils/chart.tsx
  apps/web/screens/queries/Statistics.ts
  apps/web/screens/queries/fragments.ts
  libs/api/domains/statistics/src/lib/models/statistics-query.model.ts
  libs/clients/statistics/src/lib/statistics.utils.spec.ts
  libs/clients/statistics/src/lib/statistics.utils.ts
  libs/clients/statistics/src/lib/types.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/chart.model.ts
Labels: automerge

#13686 feat(service-portal): update navigation
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  libs/clients/assets/src/lib/PropertiesApiProvider.ts
  libs/clients/hms-loans/src/lib/hmsLoans.provider.ts
  libs/portals/core/src/types/portalCore.ts
  libs/service-portal/core/src/components/TabNavigation/SubTabItem.tsx
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.css.ts
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/utils/constants.ts
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/components/FinanceIntro/index.tsx
  libs/service-portal/finance/src/lib/navigation.ts
  libs/service-portal/finance/src/screens/FinanceBills/FinanceBills.tsx
  libs/service-portal/finance/src/screens/FinanceEmployeeClaims/FinanceEmployeeClaims.tsx
  libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx
  libs/service-portal/finance/src/screens/FinanceLocalTax/LocalTax.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactionPeriods/FinanceTransactionPeriods.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/shared/constants/src/lib/organizationSlug.ts
Labels: automerge, deploy-feature

#13978 feat(parental-leave): Refactor employers
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  apps/system-e2e/src/tests/islandis/application-system/acceptance/setup-xroad.mocks.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Employers.tsx
  libs/application/templates/parental-leave/src/fields/EmployersOverview/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Employment.tsx
  libs/application/templates/parental-leave/src/fields/components/EmployersTable/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLastestEmployerValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
Labels: automerge

#13999 feat(web): Move 404 redirect logic to getServerSidePropsWrapper function
  apps/web/pages/_error.tsx
  apps/web/utils/getServerSidePropsWrapper.ts
  apps/web/utils/safelyExtractPathnameFromUrl.ts
Labels: automerge

#14002 fix(j-s): Add required canConfirmAppeal field to defender user
  apps/judicial-system/api/src/app/modules/auth/auth.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/findDefenderByNationalId.spec.ts
Labels: automerge

#14003 feat(web): Add projectsubpage to project sidebarlinks
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/linkGroup.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/web.ts
Labels: automerge

#14006 fix(delegation-api): use master when indexing delegations
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/personal-representative/services/personalRepresentative.service.ts
Labels: automerge

#14011 fix(personal-representative-api): Add missing infra variables for the personal representative api.
  apps/services/auth/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge, high priority

#14010 fix(personal-representative-api): Add missing infra variables for the personal representative api.
  apps/services/auth/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge, high priority

#14004 feat(web): Pension Calculator - Change date defaults
  apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
Labels: automerge

#14009 feat(web): Grindavík property purchase calculator - Autofocus appended loan input fields
  apps/web/components/connected/GrindavikResidentialPropertyPurchaseCalculator/GrindavikResidentialPropertyPurchaseCalculator.tsx
Labels: automerge

#13883 fix(admin-portal): Fix environment changing on save
  libs/portals/admin/ids-admin/src/screens/Client/ClientContext.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/PermissionContext.tsx
Labels: automerge

#14007 fix(order-vehicle-registration-certificate): fixing error when choosing car
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/forms/OrderVehicleRegistrationCertificateForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/utils/getSelectedVehicle.ts
Labels: automerge

#14012 feat(web): Pension Calculator - Change default values and tweak visuals
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#13944 feat: resync app
  apps/native/app/.eslintrc.json
  apps/native/app/README.md
  apps/native/app/ios/Podfile.lock
  apps/native/app/package.json
  apps/native/app/src/config.ts
  apps/native/app/src/stores/environment-store.ts
Labels: automerge

#14017 fix(delegation-index): stop using master db when indexing all delegations
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#14001 feat(j-s): Update indictment count crime scene info
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#13895 feat(auth-admin): Single session client
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/api/domains/auth-admin/src/lib/client/dto/patch-client.input.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-environment.model.ts
  libs/auth-api-lib/migrations/20240223121645-single-session.js
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/clients/models/client.model.ts
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/screens/Client/Client.graphql
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.graphql
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.schema.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/AdvancedSettings.tsx
  libs/services/auth/testing/src/fixtures/client.fixture.ts
Labels: automerge

#13803 fix(application-estate): List completed applications
  libs/application/templates/estate/src/lib/EstateTemplate.ts
Labels: automerge

#14013 feat(inheritance-report): add property or estate repeater
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/BusinessAssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/forms/sections/business.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#14020 feat(scripts): Improved run-proxies
  scripts/run-proxies.sh
Labels: automerge

#14024 fix(university-gateway): Accessibility on header
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/UniversitySearch/UniversitySubPage.tsx
Labels: automerge

#14027 fix(aosh): Making fateOfMachine field required
  libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/deregisterSubSection.ts
Labels: automerge

#14028 fix(aosh): making fateOfMachine as required field
  libs/application/templates/aosh/deregister-machine/src/forms/DeregisterMachineForm/InformationSection/deregisterSubSection.ts
Labels: automerge

#13977 fix(system-e2e): Fix tests to handle new login system
  apps/system-e2e/src/support/login.ts
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/access-control.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/smoke/auth.spec.ts
Labels: automerge

#14030 fix(application-estate): Share-parsing function for icelandic commas
  libs/clients/syslumenn/src/lib/syslumennClient.utils.spec.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#14031 fix(gbh): use auth middleware
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
Labels: automerge

#14032 chore(university-gateway): Cache graphql calls
  libs/api/domains/university-gateway/src/lib/graphql/main.resolver.ts
  libs/api/domains/university-gateway/src/lib/graphql/models/program.model.ts
  libs/api/domains/university-gateway/src/lib/graphql/models/programFilter.model.ts
  libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
  libs/nest/pagination/src/lib/graphql/paginated.response.ts
Labels: automerge

#14019 fix(parental-leave): Add option to exit residenceGrantApplication
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrantNoBirthDate.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#14034 fix(ids-admin-portal): Be able to save refresh token absolute lifetime without setting expiration
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.schema.ts
Labels: automerge

#14022 fix(university-gateway): Client side fetching programs
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/screens/UniversitySearch/AboutPage.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/UniversitySearch/UniversitySubPage.tsx
Labels: automerge

#14038 fix(inheritance-report): change placement of remove button in mobile
  libs/application/templates/inheritance-report/src/fields/styles.css.ts
Labels: automerge

#14037 fix(fa): Adding more details to swagger documentation and updating path
  apps/financial-aid/open-api/src/app/app.controller.ts
  apps/financial-aid/open-api/src/app/backendModels/amount.model.ts
  apps/financial-aid/open-api/src/app/backendModels/application.model.ts
  apps/financial-aid/open-api/src/app/backendModels/deductionFactors.model.ts
  apps/financial-aid/open-api/src/app/backendModels/directTaxPayment.model.ts
  apps/financial-aid/open-api/src/app/backendModels/file.model.ts
  apps/financial-aid/open-api/src/app/backendModels/index.ts
  apps/financial-aid/open-api/src/app/backendModels/staff.model.ts
  apps/financial-aid/open-api/src/app/models/application.model.ts
  apps/financial-aid/open-api/src/main.ts
Labels: automerge

#14042 fix(ghb): Remove statement checkbox and add loan providers check
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/utils/loan.ts
Labels: automerge

#14040 fix(application-estate): Share-parsing function for icelandic commas …
  libs/clients/syslumenn/src/lib/syslumennClient.utils.spec.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#14036 feat(ghb): Use auth middleware
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
Labels: automerge

#14043 fix(ghb): Add loan provider checkbox and remove other one
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/utils/loan.ts
Labels: automerge

#14026 fix(island-ui): Pagination in mobile
  libs/island-ui/core/src/lib/Pagination/Pagination.css.ts
  libs/island-ui/core/src/lib/Pagination/Pagination.tsx
Labels: automerge

#14023 fix: show 404 instead of 500 erorr when regulation is not found
  apps/web/screens/Regulations/RegulationPage.tsx
  libs/clients/regulations/src/lib/regulations.service.ts
  libs/clients/regulations/src/lib/regulations.spec.ts
Labels: automerge

#14050 feat(ghb): Preferred delivery date, non-specified loan providers and preemptive-rights
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/approved.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/rejected.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
Labels: automerge

#14048 fix(inheritance-report): allow option for no title in cards
  libs/application/templates/inheritance-report/src/fields/Cards/index.tsx
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
Labels: automerge

#14053 fix(regulations): Hotfix - Show 404 instead of 500 error
  apps/web/screens/Regulations/RegulationPage.tsx
  libs/clients/regulations/src/lib/regulations.service.ts
  libs/clients/regulations/src/lib/regulations.spec.ts
Labels: automerge

#14045 fix(energy-funds): Fixing timeout bug where it was trying to prefetch all vehicles and n…
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
Labels: automerge

#14052 feat(ghb): Preferred delivery date, non-specified loan providers and preemptive-rights
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/approved.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/rejected.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
Labels: automerge, high priority

#14059 feat(ghb): bankinfo and move preemptive rights
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersOverview/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersRepeater/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/sections/applicant.ts
  libs/application/templates/grindavik-housing-buyout/src/sections/index.ts
Labels: automerge

#14060 feat(ghb): bankinfo and move preemptive rights
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersOverview/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersRepeater/index.tsx
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/dataSchema.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/errors.ts
  libs/application/templates/grindavik-housing-buyout/src/sections/applicant.ts
  libs/application/templates/grindavik-housing-buyout/src/sections/index.ts
Labels: automerge

#14055 chore(university-gateway): Hotfix - Cache graphql calls (#14032)
  libs/api/domains/university-gateway/src/lib/graphql/main.resolver.ts
  libs/api/domains/university-gateway/src/lib/graphql/models/program.model.ts
  libs/api/domains/university-gateway/src/lib/graphql/models/programFilter.model.ts
  libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
  libs/nest/pagination/src/lib/graphql/paginated.response.ts
Labels: automerge

#14051 fix(skilavottord): Fix slow queries in skilavottord
  apps/skilavottord/web/i18n/locales/en.json
  apps/skilavottord/web/i18n/locales/is.json
  apps/skilavottord/ws/migrations/20240307280301-add-indexes.js
Labels: automerge

#14041 chore(j-s): Don't encrypt laws broken
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
Labels: automerge

#14062 fix(passport): parentB error fix
  libs/application/templates/passport/src/lib/utils.ts
Labels: automerge

#14064 fix(ghb): Missing translations
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/GrindavikHousingBuyoutTemplate.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/constants/index.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#14067 fix(passport): parentB error fix (#14062)
  libs/application/templates/passport/src/lib/utils.ts
Labels: automerge

#13997 fix(skilavottord): Check if registered owner is the current user on de-registration
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.module.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.module.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.module.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.services.ts
Labels: automerge

#14033 feat(j-s): Confirm indictment modal
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#14057 feat(parental-leave): Refactor EditsRequireAction and DraftRequireAction
  libs/application/templates/parental-leave/src/fields/DraftRequiresAction/index.tsx
  libs/application/templates/parental-leave/src/fields/EditsRequireAction/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/DraftRequiresAction.ts
  libs/application/templates/parental-leave/src/forms/EditsRequireAction.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#14061 fix(parental-leave): remove unused hooks
  libs/application/templates/parental-leave/src/hooks/useLazyParentalLeavePeriodEndDate.ts
  libs/application/templates/parental-leave/src/hooks/useLazyParentalLeavePeriodLength.ts
  libs/application/templates/parental-leave/src/hooks/useLazyQuery.ts
Labels: automerge

#14070 feat(web): Add support category email for district commissioner form on service web (#14068)
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#13998 chore(identity-server): added migration script for application admin scope
  libs/auth-api-lib/migrations/20240227133212-migrate-application-admin-scope.js
Labels: automerge

#14065 fix(skilavottord): Fix slow queries in skilavottord and check current owner
  apps/skilavottord/web/i18n/locales/en.json
  apps/skilavottord/web/i18n/locales/is.json
  apps/skilavottord/ws/migrations/20240307280301-add-indexes.js
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.module.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwner.module.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.module.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.services.ts
Labels: automerge

#14068 feat(web): Add support category email for district commissioner form on service web
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#14069 fix(applications): KeyValueField regression
  libs/application/ui-fields/src/lib/KeyValueFormField/KeyValueFormField.tsx
Labels: automerge

#14071 feat(university-gateway): Changing search behaviour for a more fair result
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/utils/useUniversitySearch.tsx
Labels: automerge

#14078 fix(skilavottord): Rollback owner check
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#14082 fix(skilavottord): Rollback owner check (#14078)
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#14081 fix(user-notifications): In memory cache fix
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
Labels: automerge

#14087 fix(auth-api-lib): Fix syntax error
  libs/auth-api-lib/migrations/20240227133212-migrate-application-admin-scope.js
Labels: automerge

#14079 feat(web): Pension Calculator - client side input validation
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14088 feat(university-gateway): change search results, make more fair
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/utils/useUniversitySearch.tsx
Labels: automerge

#14085 fix(energy-funds): submit object wrong and adding 2 field in findVehicleFormField
  libs/api/domains/energy-funds/src/lib/energyFunds.service.ts
  libs/api/domains/energy-funds/src/lib/graphql/models/getVehicleWithGrant.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/graphql/queries.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#14086 fix(energy-funds): submit object wrong and adding 2 field in findVehicleFormField
  libs/api/domains/energy-funds/src/lib/energyFunds.service.ts
  libs/api/domains/energy-funds/src/lib/graphql/models/getVehicleWithGrant.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/graphql/queries.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#14090 fix(j-s): Duplicate contentful strings
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#14091 chore(auth-api-lib):migrate application admin scope
  libs/auth-api-lib/migrations/20240227133212-migrate-application-admin-scope.js
Labels: automerge

#14095 fix(j-s): Prosecutor section update
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSection.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/ProsecutorSection/ProsecutorSectionHeightenedSecurity.tsx
Labels: automerge

#14035 feat(j-s): Deny indictment modal
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240306133836-update-case.js
  apps/judicial-system/backend/migrations/20240307104300-update-notification.js
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentDeniedNotifications.spec.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/DenyIndictmentCaseModal/DenyIndictmentCaseModal.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/DenyIndictmentCaseModal/DenyIndictmentCaseModal.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/lib/case.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#14098 fix(aosh): Adding plate number to title, fixing undefined error for newDate in e…
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
  libs/application/templates/energy-funds/src/lib/messages/application.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#14099 fix(aosh): Adding plate number to title, fixing undefined error for newDate
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
  libs/application/templates/energy-funds/src/lib/messages/application.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#14103 feat(react-spa-shared): make third party default small
  libs/react-spa/shared/src/components/problems/Problem.tsx
Labels: automerge

#13763 feat(service-portal): Implement standard error/empty states in ui
  libs/api/domains/university-of-iceland/src/lib/universityOfIceland.resolver.ts
  libs/api/domains/work-machines/src/lib/workMachines.resolver.ts
  libs/service-portal/air-discount/src/screens/AirDiscountOverview/AirDiscountOverview.tsx
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/assets/src/components/DetailHeader/index.tsx
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/AssetsOverview/AssetsOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/patentVariations/EP.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/patentVariations/IS.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.tsx
  libs/service-portal/assets/src/screens/Lookup/Lookup.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.graphql
  libs/service-portal/assets/src/screens/RealEstateAssetDetail/RealEstateAssetDetail.tsx
  libs/service-portal/assets/src/screens/VehicleHistory/TabContent.tsx
  libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/assets/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/screens/DynamicWrapper/DynamicWrapper.tsx
  libs/service-portal/education-career/src/screens/EducationCareer/components/CareerCards/CareerCards.tsx
  libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx
  libs/service-portal/education/src/screens/EducationGraduation/EducationGraduation.tsx
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
  libs/service-portal/education/src/screens/SecondarySchoolCareer/SecondarySchoolCareer.tsx
  libs/service-portal/education/src/screens/SecondarySchoolGraduationDetail/SecondarySchoolGraduationDetail.tsx
  libs/service-portal/education/src/screens/SecondarySchoolGraduationOverview/SecondarySchoolGraduationOverview.tsx
  libs/service-portal/education/src/screens/SecondarySchoolGraduationSingle/SecondarySchoolGraduationSingle.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx
  libs/service-portal/finance/src/screens/FinanceSchedule/FinanceSchedule.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/health/src/screens/AidsAndNutrition/AidsAndNutrition.tsx
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.tsx
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/HealthCenter/HealthCenter.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/screens/Therapies/wrapper/TherapiesWrapper.tsx
  libs/service-portal/information/src/components/ChildView/ChildView.css.ts
  libs/service-portal/information/src/components/ChildView/ChildView.tsx
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/Child/Child.tsx
  libs/service-portal/information/src/screens/Company/CompanyInfo.tsx
  libs/service-portal/information/src/screens/Spouse/Spouse.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.graphql
  libs/service-portal/information/src/screens/UserInfoOverview/UserInfoOverview.tsx
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge

#14102 fix(skilavottord): Remove timers
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#14105 fix(skilavottord): Clean up readme
  apps/skilavottord/README.md
Labels: automerge

#14056 chore(inheritance-report): change how percentage input works
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/components/NumberInput/index.tsx
  libs/application/templates/inheritance-report/src/components/ShareInput/index.tsx
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/SpouseEstateShare/index.tsx
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.spec.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#14108 chore(regulations): Minor UI fixes. Update Editor package.
  libs/portals/admin/regulations-admin/src/components/impacts/EditChange.tsx
  libs/portals/admin/regulations-admin/src/components/impacts/ImpactAmendingSelection.tsx
  package.json
  yarn.lock
Labels: automerge

#14110 fix(ghb): Add description to preemption screen
  libs/application/templates/grindavik-housing-buyout/src/forms/GrindavikHousingBuyoutForm.ts
  libs/application/templates/grindavik-housing-buyout/src/lib/messages/application.ts
Labels: automerge

#14114 fix(web): Add failsafe for when mapping project pages
  libs/cms/src/lib/models/linkGroup.model.ts
  libs/cms/src/lib/models/projectPage.model.ts
Labels: automerge

#14104 fix(j-s): Display appeal publish request on Result screen in appeal cases
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.strings.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
Labels: automerge

#14112 fix(island-ui): large checkbox input left
  libs/island-ui/core/src/lib/Checkbox/Checkbox.css.ts
  libs/island-ui/core/src/lib/Checkbox/Checkbox.tsx
Labels: automerge

#14121 fix(j-s): Fix trim error
  apps/judicial-system/web/src/utils/formHelper.ts
Labels: automerge

#14125 fix(application-system): Fix submit callback bug
  libs/application/ui-shell/src/components/Screen.tsx
Labels: automerge

#14123 chore(web): Pension Calculator - change visuals after feedback from social insurance administration
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#14106 feat(parental-leave): Update review
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Employers.tsx
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Attachments.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Employment.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/OtherParent.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Payments.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/PersonalAllowance.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/SpousePersonalAllowance.tsx
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
Labels: automerge

#14054 fix(ojoi-application): Fixing bugs from testing
  .github/CODEOWNERS
  libs/api/domains/ministry-of-justice/src/lib/ministryOfJustice.resolver.ts
  libs/api/domains/ministry-of-justice/src/lib/ministryOfJustice.service.ts
  libs/api/domains/ministry-of-justice/src/lib/models/advert.input.ts
  libs/application/template-api-modules/src/lib/modules/templates/official-journal-of-iceland/official-journal-of-iceland.service.ts
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Committee.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Regular.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Publishing.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Signatures.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/clients/dmr/src/clientConfig.json
  libs/clients/dmr/src/lib/dmrClient.service.ts
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
  libs/island-ui/core/src/lib/DatePicker/types.ts
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
  libs/shared/form-fields/src/lib/DatePickerController/DatePickerController.tsx
Labels: automerge

#14118 fix(parental-leave): Remove PaymentSchedule
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/InformationScreen.tsx
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/PaymentSchedule.css.ts
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/PaymentsTable.tsx
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/SalaryScreen.tsx
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/estimatedPaymentsQuery.ts
  libs/application/templates/parental-leave/src/fields/PaymentSchedule/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
Labels: automerge

#14117 fix(service-portal): update payment plan
  libs/api/domains/social-insurance/src/lib/dtos/paymentPlan.input.ts
  libs/api/domains/social-insurance/src/lib/models/payment.model.ts
  libs/api/domains/social-insurance/src/lib/models/paymentGroup.model.ts
  libs/api/domains/social-insurance/src/lib/models/paymentGroupType.model.ts
  libs/api/domains/social-insurance/src/lib/models/paymentMonth.model.ts
  libs/api/domains/social-insurance/src/lib/models/paymentPlan.model.ts
  libs/api/domains/social-insurance/src/lib/models/payments.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.resolver.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/clients/social-insurance-administration/src/clientConfig.json
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
  libs/service-portal/core/src/components/EmptyTable/EmptyTable.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/core/src/utils/generateYears.ts
  libs/service-portal/social-insurance-maintenance/codegen.yml
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.graphql
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.tsx
  libs/service-portal/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTableRow.tsx
  libs/service-portal/social-insurance-maintenance/src/components/index.ts
  libs/service-portal/social-insurance-maintenance/src/lib/messages.ts
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.graphql
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge, deploy-feature

#14129 fix(grindavik-housing-buyout): Duplicate submissions
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#14132 fix(application-ctao): Translation strings
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/InformationToComplainer/InformationToComplainer.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/ComplaintsToAlthingiOmbudsmanTemplate.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/application.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/informationToComplainer.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#14084 chore(logging): Delete and log more
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#14080 chore(infra): Tag conformance
  libs/api/domains/auth-admin/project.json
  libs/api/domains/watson-assistant-chat/project.json
  libs/clients/aircraft-registry/project.json
  libs/clients/auth/admin-api/project.json
  libs/clients/auth/ids-api/project.json
  libs/clients/health-directorate/project.json
  libs/clients/housing-benefit-calculator/project.json
  libs/clients/icelandic-government-institution-vacancies/project.json
  libs/clients/sessions/project.json
  libs/clients/ship-registry/project.json
  libs/clients/signature-collection/project.json
  libs/clients/statistics/project.json
  libs/service-portal/restrictions/project.json
  libs/university-gateway/project.json
  scripts/check-tags.ts
Labels: automerge

#14135 feat(university-gateway): Frontend accessibility, styling, locale and other smaller changes
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.css.ts
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/queries/UniversityGateway.ts
  apps/web/utils/useUniversitySearch.tsx
  libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
  libs/application/templates/university/src/graphql/queries.ts
  libs/cms/src/index.ts
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.module.ts
  libs/cms/src/lib/loaders/organizationLinkEnByKey.loader.ts
Labels: automerge

#14142 fix(service-portal): Home w car animation
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  apps/service-portal/src/utils/Icons/idMapper.tsx
Labels: automerge

#14073 fix(old-age-pension): start date is next month after birthday
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#14089 fix(parental-leave): No dynamic record, only const
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#14151 fix(gbh): Extra residence check
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
  libs/clients/national-registry/v2/src/index.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
  libs/clients/national-registry/v2/src/lib/types/address.dto.ts
  libs/clients/national-registry/v2/src/lib/types/birthplace.dto.ts
  libs/clients/national-registry/v2/src/lib/types/citizenship.dto.ts
  libs/clients/national-registry/v2/src/lib/types/cohabitation.dto.ts
  libs/clients/national-registry/v2/src/lib/types/family.dto.ts
  libs/clients/national-registry/v2/src/lib/types/individual.dto.ts
  libs/clients/national-registry/v2/src/lib/types/religion.dto.ts
  libs/clients/national-registry/v2/src/lib/types/residence-history-entry.dto.ts
Labels: automerge

#14140 fix(parental-leave): remove url from emails
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignEmployerEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/emailGenerators/assignOtherParentEmail.ts
Labels: automerge

#14127 fix(web): Pension Calculator - Change default yearOfBirth to 1952 or more
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge

#14146 chore(web): Add translation defaults to Pension Calculator
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#14149 feat(gbh): Extra residence check
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/grindavik-housing-buyout/grindavik-housing-buyout.utils.ts
  libs/clients/national-registry/v2/src/index.ts
  libs/clients/national-registry/v2/src/lib/nationalRegistryClient.service.ts
  libs/clients/national-registry/v2/src/lib/types/address.dto.ts
  libs/clients/national-registry/v2/src/lib/types/birthplace.dto.ts
  libs/clients/national-registry/v2/src/lib/types/citizenship.dto.ts
  libs/clients/national-registry/v2/src/lib/types/cohabitation.dto.ts
  libs/clients/national-registry/v2/src/lib/types/family.dto.ts
  libs/clients/national-registry/v2/src/lib/types/individual.dto.ts
  libs/clients/national-registry/v2/src/lib/types/religion.dto.ts
  libs/clients/national-registry/v2/src/lib/types/residence-history-entry.dto.ts
Labels: automerge

#14152 fix(driving-license): fix for dl in other country
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
Labels: automerge

#14159 chore: fix spinnaker github 404 issue
  infra/cache-bust
Labels: automerge

#14018 chore(translation-extension): Remove translation-extension references and project files
  .github/CODEOWNERS
  .gitignore
  apps/contentful-apps/README.md
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/helm/Chart.yaml
  infra/src/uber-charts/islandis.ts
  libs/contentful-extensions/README.md
  libs/contentful-extensions/translation/.babelrc
  libs/contentful-extensions/translation/.eslintrc.json
  libs/contentful-extensions/translation/README.md
  libs/contentful-extensions/translation/infra/contentful-translation-extension.ts
  libs/contentful-extensions/translation/jest.config.ts
  libs/contentful-extensions/translation/project.json
  libs/contentful-extensions/translation/src/assets/bold.png
  libs/contentful-extensions/translation/src/assets/insert_link.png
  libs/contentful-extensions/translation/src/assets/italic.png
  libs/contentful-extensions/translation/src/assets/list_bulleted.png
  libs/contentful-extensions/translation/src/assets/list_numbered.png
  libs/contentful-extensions/translation/src/assets/looks_four.png
  libs/contentful-extensions/translation/src/assets/looks_three.png
  libs/contentful-extensions/translation/src/assets/looks_two.png
  libs/contentful-extensions/translation/src/assets/underlined.png
  libs/contentful-extensions/translation/src/components/BlockButton.tsx
  libs/contentful-extensions/translation/src/components/Button.tsx
  libs/contentful-extensions/translation/src/components/Element.tsx
  libs/contentful-extensions/translation/src/components/Label.tsx
  libs/contentful-extensions/translation/src/components/Leaf.tsx
  libs/contentful-extensions/translation/src/components/LinkButton.tsx
  libs/contentful-extensions/translation/src/components/MarkButton.tsx
  libs/contentful-extensions/translation/src/components/MarkdownEditor.tsx
  libs/contentful-extensions/translation/src/components/Toolbar.tsx
  libs/contentful-extensions/translation/src/index.css
  libs/contentful-extensions/translation/src/index.html
  libs/contentful-extensions/translation/src/index.tsx
  libs/contentful-extensions/translation/src/plugins/withHtml.ts
  libs/contentful-extensions/translation/src/plugins/withShortcuts.ts
  libs/contentful-extensions/translation/src/types/types.d.ts
  libs/contentful-extensions/translation/src/utils/constants.ts
  libs/contentful-extensions/translation/src/utils/deserialize.spec.ts
  libs/contentful-extensions/translation/src/utils/deserialize.ts
  libs/contentful-extensions/translation/src/utils/markdown.fixture.ts
  libs/contentful-extensions/translation/src/utils/serialize.spec.ts
  libs/contentful-extensions/translation/src/utils/serialize.ts
  libs/contentful-extensions/translation/src/utils/slate.fixture.ts
  libs/contentful-extensions/translation/tsconfig.json
  libs/contentful-extensions/translation/tsconfig.spec.json
  scripts/ci/30_test.sh
Labels: automerge

#14154 fix(service-portal): Display single document by path
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/lib/paths.ts
  libs/service-portal/documents/src/module.tsx
  libs/service-portal/documents/src/screens/Documents.loader.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#14162 fix(ojoi): query schema and inputs
  libs/api/domains/ministry-of-justice/src/lib/models/advert.input.ts
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
Labels: automerge

#14148 fix(university-gateway): Increasing cache to 20 minutes (worker runs every hour)
  libs/api/domains/university-gateway/src/lib/cacheControl.ts
  libs/api/domains/university-gateway/src/lib/graphql/main.resolver.ts
  libs/api/domains/university-gateway/src/lib/graphql/university.resolver.ts
Labels: automerge

#14161 feat(university-gateway): Parsing raw html to our design system
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/queries/UniversityGateway.ts
  libs/api/domains/university-gateway/src/lib/graphql/models/program.model.ts
  libs/api/domains/university-gateway/src/lib/universityGateway.service.ts
  libs/api/domains/university-gateway/src/lib/utils.ts
Labels: automerge

#12833 feat(api): new hunting license client
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/service-portal/src/assets/images/umhverfisstofnun.svg
  apps/services/license-api/infra/license-api.ts
  apps/services/license-api/src/app/app.module.ts
  apps/services/license-api/src/app/modules/license/license.types.ts
  apps/services/license-api/src/app/modules/license/scopeMapper.ts
  apps/services/license-api/src/app/modules/license/utils/mapLicenseId.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/license-service/src/lib/licenseService.constants.ts
  libs/api/domains/license-service/src/lib/mappers/huntingLicenseMapper.ts
  libs/api/domains/license-service/src/lib/mappers/licenseMapper.module.ts
  libs/api/domains/license-service/src/lib/providers/licenseMapper.provider.ts
  libs/auth-api-lib/seeders/data/client-licenses-ust.ts
  libs/auth/scopes/src/lib/license-api.scope.ts
  libs/clients/hunting-license/.eslintrc.json
  libs/clients/hunting-license/README.md
  libs/clients/hunting-license/jest.config.ts
  libs/clients/hunting-license/project.json
  libs/clients/hunting-license/src/clientConfig.json
  libs/clients/hunting-license/src/index.ts
  libs/clients/hunting-license/src/lib/huntingLicenseClient.config.ts
  libs/clients/hunting-license/src/lib/huntingLicenseClient.module.ts
  libs/clients/hunting-license/src/lib/huntingLicenseClient.provider.ts
  libs/clients/hunting-license/src/lib/huntingLicenseClient.service.ts
  libs/clients/hunting-license/src/lib/huntingLicenseClient.types.ts
  libs/clients/hunting-license/tsconfig.json
  libs/clients/hunting-license/tsconfig.lib.json
  libs/clients/hunting-license/tsconfig.spec.json
  libs/clients/license-client/src/index.ts
  libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClient.config.ts
  libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClient.module.ts
  libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/hunting-license-client/huntingLicenseClientMapper.ts
  libs/clients/license-client/src/lib/clients/hunting-license-client/index.ts
  libs/clients/license-client/src/lib/licenseClient.module.ts
  libs/clients/license-client/src/lib/licenseClient.type.ts
  libs/clients/license-client/src/lib/providers/passTemplateIdsProvider.ts
  libs/service-portal/licenses/src/lib/messages.ts
  libs/service-portal/licenses/src/lib/paths.ts
  libs/service-portal/licenses/src/screens/LicensesOverview/index.tsx
  libs/service-portal/licenses/src/utils/dataMapper.tsx
  tsconfig.base.json
Labels: automerge, deploy-feature

#14126 fix(ip): scopes
  apps/service-portal/src/auth.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.resolver.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/assets/src/module.tsx
Labels: automerge

#14119 feat(user-profile): State query param for user-profile
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
Labels: automerge

#14120 fix(signature-collections): web recap
  .github/CODEOWNERS
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
Labels: automerge

#14150 feat(services-license): Add license type restriction to barcode
  apps/services/license-api/infra/license-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/license-service/src/lib/licenseService.resolver.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
Labels: automerge

#14147 fix(j-s): Case Files Record Encoding
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverCaseFilesRecordToPolice.spec.ts
Labels: automerge

#14168 chore(service-portal): add health directorate statuses
  libs/api/domains/occupational-licenses/src/lib/models/occupationalLicense.model.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
  libs/service-portal/occupational-licenses/src/components/LicenceActionCard.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
  libs/service-portal/occupational-licenses/src/lib/messages.ts
Labels: automerge

#13657 chore(ci): Better caching failure handling
  .github/actions/cache/action.yml
  .github/actions/unit-test/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#14165 feat(j-s): Required Files
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#14172 fix(ctao): Add missing conclusion translations
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanSubmitted.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/confirmation.ts
Labels: automerge

#14174 chore(document-provider): Update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#14144 feat(delegation-api): delegation index lookup
  apps/services/auth/delegation-api/src/app/delegations/delegation-index.controller.ts
  apps/services/auth/delegation-api/src/app/delegations/delegations.controller.ts
  apps/services/auth/delegation-api/src/app/delegations/delegations.module.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index-test-cases.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index.controller.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegations-index-types.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller-test-types.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller.test-cases.ts
  libs/auth-api-lib/seeders/data/scope-delegation-index.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/delegations/dto/delegation-index.dto.ts
  libs/auth-api-lib/src/lib/delegations/utils/delegations.ts
  libs/auth-api-lib/src/lib/personal-representative/services/personalRepresentativeRightType.service.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/auth/scopes/src/lib/auth.scope.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/services/auth/testing/src/fixtures/types.ts
Labels: automerge

#14141 feat(j-s): New law in laws broken
  apps/judicial-system/backend/migrations/20240314142256-update-case.js
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/web/messages/Core/laws.ts
  apps/judicial-system/web/src/components/SectionHeading/SectionHeading.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/utils/laws.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge, skip-nx-cache, skip-nodejs-cache, skip-generated-cache

#13877 feat(documents-v2): New documents client
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/download-service/src/app/app.module.ts
  libs/api/domains/documents/src/index.ts
  libs/api/domains/documents/src/lib/document.module.ts
  libs/api/domains/documents/src/lib/document.types.ts
  libs/api/domains/documents/src/lib/documentBuilder.ts
  libs/api/domains/documents/src/lib/documentV1.resolver.ts
  libs/api/domains/documents/src/lib/documentV1.service.ts
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v1/actionMail.model.ts
  libs/api/domains/documents/src/lib/models/v1/bulkMailAction.model.ts
  libs/api/domains/documents/src/lib/models/v1/document.model.ts
  libs/api/domains/documents/src/lib/models/v1/documentCategory.model.ts
  libs/api/domains/documents/src/lib/models/v1/documentDetails.model.ts
  libs/api/domains/documents/src/lib/models/v1/documentPage.model.ts
  libs/api/domains/documents/src/lib/models/v1/documentSender.model.ts
  libs/api/domains/documents/src/lib/models/v1/documentType.model.ts
  libs/api/domains/documents/src/lib/models/v1/paperMail.model.ts
  libs/api/domains/documents/src/lib/models/v2/base.model.ts
  libs/api/domains/documents/src/lib/models/v2/bulkMailAction.input.ts
  libs/api/domains/documents/src/lib/models/v2/category.model.ts
  libs/api/domains/documents/src/lib/models/v2/document.input.ts
  libs/api/domains/documents/src/lib/models/v2/document.model.ts
  libs/api/domains/documents/src/lib/models/v2/documentContent.model.ts
  libs/api/domains/documents/src/lib/models/v2/documents.input.ts
  libs/api/domains/documents/src/lib/models/v2/mailAction.model..ts
  libs/api/domains/documents/src/lib/models/v2/paperMailPreferences.model.ts
  libs/api/domains/documents/src/lib/models/v2/postMailAction.model.ts
  libs/api/domains/documents/src/lib/models/v2/sender.model.ts
  libs/api/domains/documents/src/lib/models/v2/type.model.ts
  libs/api/domains/documents/src/lib/types/documents.config.ts
  libs/api/domains/documents/src/lib/types/index.ts
  libs/clients/documents-v2/.eslintrc.json
  libs/clients/documents-v2/README.md
  libs/clients/documents-v2/jest.config.ts
  libs/clients/documents-v2/project.json
  libs/clients/documents-v2/src/clientConfig.json
  libs/clients/documents-v2/src/index.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.config.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.module.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.provider.ts
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
  libs/clients/documents-v2/src/lib/dto/documentInfo.dto.ts
  libs/clients/documents-v2/src/lib/dto/documentList.dto.ts
  libs/clients/documents-v2/src/lib/dto/listDocuments.input.ts
  libs/clients/documents-v2/src/lib/dto/mailAction.dto.ts
  libs/clients/documents-v2/tsconfig.json
  libs/clients/documents-v2/tsconfig.lib.json
  libs/clients/documents-v2/tsconfig.spec.json
  libs/clients/documents/src/index.ts
  libs/clients/documents/src/lib/document.connection.ts
  libs/clients/documents/src/lib/document.module.ts
  libs/clients/documents/src/lib/documentClient.config.ts
  libs/clients/documents/src/lib/documentClient.ts
  libs/clients/documents/src/lib/documents.module.ts
  libs/service-portal/documents/src/screens/Overview/Overview.graphql
  tsconfig.base.json
Labels: automerge
