Repository island-is/island.is, pull requests merged in 2024-09, with the labels that each got.

#15823 feat(web): Generic list items - Cards set to full width on all screen sizes
  apps/web/components/GenericList/GenericList.tsx
Labels: automerge

#15829 fix(application-estate): Email and phone prefill
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/fakeData.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#15813 fix(application-ir): Skip disabled estates in calculations
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
Labels: automerge

#15534 feat(mms): Add enhancedFetch-using grade client
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/education.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
  libs/api/domains/education/src/index.ts
  libs/api/domains/education/src/lib/education.utils.ts
  libs/api/domains/education/src/lib/educationMapper.ts
  libs/api/domains/education/src/lib/educationV2.module.ts
  libs/api/domains/education/src/lib/educationV2.service.ts
  libs/api/domains/education/src/lib/graphql/grades.resolver.ts
  libs/api/domains/education/src/lib/models/competence.model.ts
  libs/api/domains/education/src/lib/models/course.model.ts
  libs/api/domains/education/src/lib/models/familyCareer.model.ts
  libs/api/domains/education/src/lib/models/grade.model.ts
  libs/api/domains/education/src/lib/models/gradeCategory.model.ts
  libs/api/domains/education/src/lib/models/gradeCategoryText.model.ts
  libs/api/domains/education/src/lib/models/gradeCategoryWeighted.model.ts
  libs/api/domains/education/src/lib/models/gradeDetail.model.ts
  libs/api/domains/education/src/lib/models/gradeLevelExamResults.model.ts
  libs/api/domains/education/src/lib/models/studentCareer.model.ts
  libs/clients/mms/grade/.eslintrc.json
  libs/clients/mms/grade/README.md
  libs/clients/mms/grade/jest.config.ts
  libs/clients/mms/grade/project.json
  libs/clients/mms/grade/src/clientConfig.json
  libs/clients/mms/grade/src/index.ts
  libs/clients/mms/grade/src/lib/dto/course.dto.ts
  libs/clients/mms/grade/src/lib/dto/courseGradeHistory.dto.ts
  libs/clients/mms/grade/src/lib/dto/familyAssessments.dto.ts
  libs/clients/mms/grade/src/lib/dto/gradeResult.dto.ts
  libs/clients/mms/grade/src/lib/dto/studentGradeLevelAssessment.dto.ts
  libs/clients/mms/grade/src/lib/gradeClient.config.ts
  libs/clients/mms/grade/src/lib/gradeClient.module.ts
  libs/clients/mms/grade/src/lib/gradeClient.provider.ts
  libs/clients/mms/grade/src/lib/gradeClient.service.ts
  libs/clients/mms/grade/tsconfig.json
  libs/clients/mms/grade/tsconfig.lib.json
  libs/clients/mms/grade/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#15465 feat(smart-solutions-v2): add client
  .github/CODEOWNERS
  libs/clients/smart-solutions-v2/.eslintrc.json
  libs/clients/smart-solutions-v2/README.md
  libs/clients/smart-solutions-v2/codegen.yml
  libs/clients/smart-solutions-v2/fetchSchema.yml
  libs/clients/smart-solutions-v2/jest.config.ts
  libs/clients/smart-solutions-v2/project.json
  libs/clients/smart-solutions-v2/smartsolutions-api.graphql
  libs/clients/smart-solutions-v2/src/index.ts
  libs/clients/smart-solutions-v2/src/lib/gqlClientFactory.ts
  libs/clients/smart-solutions-v2/src/lib/gqlFetch.ts
  libs/clients/smart-solutions-v2/src/lib/smartSolutions.config.ts
  libs/clients/smart-solutions-v2/src/lib/smartSolutions.graphql
  libs/clients/smart-solutions-v2/src/lib/smartSolutions.module-definition.ts
  libs/clients/smart-solutions-v2/src/lib/smartSolutions.module.ts
  libs/clients/smart-solutions-v2/src/lib/smartSolutions.service.ts
  libs/clients/smart-solutions-v2/src/lib/types/config.type.ts
  libs/clients/smart-solutions-v2/src/lib/types/graphqlFetchResponses.type.ts
  libs/clients/smart-solutions-v2/src/lib/types/responses.type.ts
  libs/clients/smart-solutions-v2/src/lib/types/result.type.ts
  libs/clients/smart-solutions-v2/tsconfig.json
  libs/clients/smart-solutions-v2/tsconfig.lib.json
  libs/clients/smart-solutions-v2/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#15840 fix(auth-admin-api): Use master node when finding newly created scope
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
Labels: automerge

#15817 feat(j-s): Show courtRecord files in indictments to everyone once uploaded
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.spec.tsx
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.spec.tsx
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
Labels: automerge

#15821 fix(j-s): Defender File Display
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
Labels: automerge

#15845 fix(j-s): Appeal Case Judges
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
Labels: automerge

#15839 fix(services-user-notification): Fix no email registered and error when getting company name
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/test/environment.ts
Labels: automerge

#15848 fix(cms): getOrganizations endpoint - Lower include depth to 4
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge

#15851 fix(cms): getOrganizations endpoint - Lower include depth to 4
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge, high priority

#15847 feat(income-plan): add year
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
  libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
Labels: automerge, deploy-feature

#15855 fix(inheritance-report): overview confirmations
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#15726 fix(api): This fixes colour logging by Nest.js health check
  .github/CODEOWNERS
  libs/infra-nest-server/src/lib/infra/health/health.logger.ts
  libs/infra-nest-server/src/lib/infra/health/health.module.ts
Labels: automerge

#15856 fix(aod): tweak firearm stringify
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts
Labels: automerge

#15859 infra(services-user-notification): Adding missing infra for company registry
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#15863 fix(application-aod): Fix expander for firearm data to sysl (#15862)
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts
Labels: automerge

#15831 fix(j-s): Undefined Slack Events
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#15861 feat(j-s): Disable Next Button While Editing
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.spec.tsx
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.strings.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/EditableCaseFile/EditableCaseFile.strings.ts
  apps/judicial-system/web/src/components/EditableCaseFile/EditableCaseFile.tsx
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.strings.ts
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/routes/Shared/AddFiles/AddFiles.tsx
Labels: automerge

#15864 fix(signature-collection): cleanup constituencies
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/modals/LookupPerson/index.tsx
Labels: automerge

#15865 fix(citizenship): error with given and family names on prod
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/PersonalSection/UserInformationSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/CitizenshipTemplate.ts
Labels: automerge

#15868 fix(search-indexer): Latest Generic List Items - Prevent infinite loop when mapping organization subpage reference
  libs/cms/src/lib/models/latestGenericListItems.model.ts
Labels: automerge, high priority

#15869 chore(native-app): bump version to 1.4.1
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#15850 fix(j-s): Disable ServiceRequirement rather then hiding it when sent to public prosecutor
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
Labels: automerge

#15874 feat(native-app): fix rendering of regular font in iOS
  apps/native/app/android/app/src/main/assets/fonts/IBMPlexSans.ttf
  apps/native/app/assets/fonts/IBMPlexSans.ttf
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
Labels: automerge

#15828 fix(native-app): always reset passkey preferences on logout
  apps/native/app/src/stores/auth-store.ts
Labels: automerge

#15873 fix(driving-license): disabled BE for 65 and older
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
Labels: automerge

#15866 fix(j-s): Additional Documents
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#15877 fix: fjs staging xrd paths
  apps/application-system/api/infra/application-system-api.ts
  charts/identity-server/values.staging.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15879 fix: fjs staging xrd paths (#15877)
  apps/application-system/api/infra/application-system-api.ts
  charts/identity-server/values.staging.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15818 feat(health-insurance-declaration): Make it possible to select only child for health insurance declaration
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.utils.ts
  libs/application/templates/health-insurance-declaration/src/forms/HealthInsuranceDeclarationForm.ts
  libs/application/templates/health-insurance-declaration/src/lib/dataSchema.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/application.ts
  libs/application/templates/health-insurance-declaration/src/utils/data.ts
Labels: automerge

#15841 chore(mocking): Relocate and update mocking readme as well as accident-notification mock data
  libs/application/templates/README.md
  libs/application/templates/accident-notification/mockData/accident-notification.json
  libs/application/templates/health-insurance-declaration/mockData/health-insurance-declaration.json
  mocks/README.md
Labels: automerge

#15860 feat(j-s): Add "acknowledged" to case and subpoena
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/case.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
Labels: automerge

#15881 fix(driving-license): digital license, no pickup
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionDigitalLicenseInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15886 chore(j-s): Add institution addresses to db
  apps/judicial-system/backend/migrations/20240904100012-update-institution.js
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
Labels: automerge

#15891 fix(universtity-gateway): fixing modeOfDelivery error
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/application/templates/university/src/shared/types.ts
Labels: automerge

#15882 fix(driving-license): digital license, no pickup (#15881)
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionDigitalLicenseInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15884 fix(regulations-admin): Increase body limit on regulations backend
  apps/services/regulations-admin-backend/src/main.ts
Labels: automerge

#15904 fix(citizenship): name error fix
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/PersonalSection/UserInformationSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/CitizenshipTemplate.ts
Labels: automerge

#15844 chore(j-s): Prison users access to appeal case files
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/guards/limitedAccessCaseExists.guard.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseFile.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/completedAppealAccessed.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/file.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#15903 fix(inheritance-report): make sure total assets get into answers
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/SetTotalAssets/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
Labels: automerge

#15905 fix(inheritance-report): calculate realEstate withOUT share
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
Labels: automerge

#15896 fix(island-ui): Filter Dialog - Scroll doesn't work on iOS
  libs/island-ui/core/src/lib/Filter/Filter.tsx
  libs/island-ui/core/src/lib/Filter/usePreventBodyScroll.ts
Labels: automerge, deploy-feature

#15890 fix(native-app): update inbox filter headers
  apps/native/app/src/ui/lib/accordion/accordion-item.tsx
  apps/native/app/src/ui/lib/checkbox/checkbox.tsx
Labels: automerge

#15893 feat(native-app): use unseen count for notifications as badge for app
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/stores/notifications-store.ts
Labels: automerge

#15819 feat(web): Parental leave calculator
  apps/web/components/Organization/MarkdownText/MarkdownText.tsx
  apps/web/components/connected/ParentalLeaveCalculator/ParentalLeaveCalculator.css.ts
  apps/web/components/connected/ParentalLeaveCalculator/ParentalLeaveCalculator.tsx
  apps/web/components/connected/ParentalLeaveCalculator/translations.strings.ts
  apps/web/components/real.ts
  apps/web/utils/currency.ts
  apps/web/utils/richText.tsx
Labels: automerge

#15836 feat(service-portal): Fix up modal
  libs/service-portal/core/src/components/Modal/Modal.css.ts
  libs/service-portal/core/src/components/Modal/Modal.tsx
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.css.ts
  libs/service-portal/health/src/components/RegisterModal/RegisterModal.tsx
  libs/service-portal/health/src/components/RegisterModal/index.ts
  libs/service-portal/health/src/screens/DentistRegistration/DentistRegistration.tsx
  libs/service-portal/health/src/screens/HealthCenterRegistration/HealthCenterRegistration.tsx
Labels: automerge

#15898 fix(native-app): add missing error messages for updating profile information
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/settings/edit-bank-info.tsx
  apps/native/app/src/screens/settings/edit-confirm.tsx
  apps/native/app/src/screens/settings/edit-email.tsx
Labels: automerge

#15852 chore(j-s): Allow public prosecutor user to open case files
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getIndictmentPdfRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/viewCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/guards/viewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlRolesRules.spec.ts
Labels: automerge

#15871 feat(j-s): Confirmed subpoena stamp
  apps/judicial-system/backend/src/app/formatters/confirmedIndictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/limitedAccessFileController/createPresignedPostGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.spec.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#15913 fix(native-app): final fix for ios font
  apps/native/app/android/link-assets-manifest.json
  apps/native/app/ios/IslandApp/Info.plist
  apps/native/app/ios/link-assets-manifest.json
  apps/native/app/src/ui/lib/list/list-item.tsx
Labels: automerge

#15912 infra(services-auth-delegation-api): Grant user-notification-worker access to delegation-api
  apps/services/auth/delegation-api/infra/delegation-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15915 feat(web): Search screen - Stop overriding previous filters
  apps/web/screens/Search/Search.tsx
Labels: automerge

#15888 feat(native-app): app should use locale on user profile
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/stores/preferences-store.ts
Labels: automerge

#15916 fix(social-insurance-maintenance): wrong field used
  libs/api/domains/social-insurance/src/lib/models/income/category.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.graphql
  libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.tsx
Labels: automerge

#15857 feat(regulations-admin): Add affected regulation formatting
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#15897 fix(multiple): remove phone from error logs
  libs/application/template-api-modules/src/lib/modules/templates/aosh/change-machine-supervisor/change-machine-supervisor.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/transfer-of-machine-ownership.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
Labels: automerge

#15895 fix(accident notification): Set final review to completed status
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
Labels: automerge

#15728 fix(service-portal): Health Directorate - Fixes
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/organ-donation.model.ts
  libs/api/domains/health-directorate/src/lib/models/vaccinations.model.ts
  libs/clients/health-directorate/src/index.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.config.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.provider.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.service.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.config.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.service.ts
  libs/service-portal/core/src/index.ts
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/OrganDonation/OrganDonation.graphql
  libs/service-portal/health/src/screens/OrganDonation/OrganDonation.tsx
  libs/service-portal/health/src/screens/OrganDonationRegistration/Limitations.tsx
  libs/service-portal/health/src/screens/OrganDonationRegistration/Loader.tsx
  libs/service-portal/health/src/screens/OrganDonationRegistration/RegistrationForm.tsx
  libs/service-portal/health/src/screens/Vaccinations/Vaccinations.graphql
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsGeneral.tsx
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsOther.tsx
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsDetailTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/wrapper/VaccinationsWrapper.tsx
  libs/service-portal/health/src/utils/tagSelector.ts
Labels: automerge

#15910 fix(j-s): Cancelled Unassigned Indictment
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
Labels: automerge

#15902 feat(native-app): add app widgets to home screen
  apps/native/app/src/assets/icons/options.png
  apps/native/app/src/assets/icons/options@2x.png
  apps/native/app/src/assets/icons/options@3x.png
  apps/native/app/src/assets/illustrations/le-company-s2x.png
  apps/native/app/src/assets/illustrations/le-jobs-s2.png
  apps/native/app/src/assets/illustrations/le-jobs-s2@2x.png
  apps/native/app/src/assets/illustrations/le-jobs-s2@3x.png
  apps/native/app/src/assets/illustrations/le-moving-s4.png
  apps/native/app/src/assets/illustrations/le-moving-s4@2x.png
  apps/native/app/src/assets/illustrations/le-moving-s4@3x.png
  apps/native/app/src/assets/illustrations/le-retirement-s3-large.png
  apps/native/app/src/assets/illustrations/le-retirement-s3-large@2x.png
  apps/native/app/src/assets/illustrations/le-retirement-s3-large@3x.png
  apps/native/app/src/assets/illustrations/le-retirement-s3.png
  apps/native/app/src/assets/illustrations/le-retirement-s3@2x.png
  apps/native/app/src/assets/illustrations/le-retirement-s3@3x.png
  apps/native/app/src/assets/illustrations/moving.png
  apps/native/app/src/assets/illustrations/moving@2x.png
  apps/native/app/src/assets/illustrations/moving@3x.png
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/home/air-discount-module.tsx
  apps/native/app/src/screens/home/applications-module.tsx
  apps/native/app/src/screens/home/hello-module.tsx
  apps/native/app/src/screens/home/home-options.tsx
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/home/inbox-module.tsx
  apps/native/app/src/screens/home/licenses-module.tsx
  apps/native/app/src/screens/home/onboarding-module.tsx
  apps/native/app/src/screens/home/vehicles-module.tsx
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/screens/vehicles/vehicles-detail.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
  apps/native/app/src/screens/wallet/components/wallet-item.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/stores/notifications-store.ts
  apps/native/app/src/stores/preferences-store.ts
  apps/native/app/src/ui/index.ts
  apps/native/app/src/ui/lib/card/air-discount-card.tsx
  apps/native/app/src/ui/lib/card/license-card.tsx
  apps/native/app/src/ui/lib/card/vehicle-card.tsx
  apps/native/app/src/ui/lib/empty-state/empty-card.tsx
  apps/native/app/src/ui/lib/skeleton/general-card-skeleton.tsx
  apps/native/app/src/ui/lib/tableview/tableview-cell.tsx
  apps/native/app/src/utils/component-registry.ts
  apps/native/app/src/utils/get-main-root.ts
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
  apps/native/app/src/utils/lifecycle/setup-routes.ts
  apps/native/app/src/utils/test-ids.ts
Labels: automerge

#15919 feat: Configure universal links for the test app HOTFIX
  .github/CODEOWNERS
  apps/web/public/.well-known/apple-app-site-association
Labels: automerge

#15906 fix(j-s): Indictment Appeal
  apps/judicial-system/api/src/app/modules/case-list/interceptors/caseList.interceptor.ts
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/prisonAdminUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/prisonStaffUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/prisonSystemUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/file/guards/viewCaseFile.guard.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/indictmentCase.spec.ts
  libs/judicial-system/types/src/lib/indictmentCase.ts
Labels: automerge

#12291 fix(driving-license): driving license application for 65+
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/QualityPhoto/QualityPhoto.tsx
  libs/application/templates/driving-license/src/fields/QualityPhoto/hooks/useQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
Labels: automerge

#15917 fix(application-plc): Incorrect assumption for dataprovider
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
Labels: automerge

#15926 fix(chore): missing env for application system
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#15924 fix:(application-plc) partial submission cleanup
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge

#15920 fix(announcement-of-death): remove sms and email notifications
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/emailGenerators/assets/logo.jpg
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/emailGenerators/firearmApplicantNotification.ts
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/smsGenerators/requestReviewSms.ts
Labels: automerge

#15928 fix(j-s): Edit Count
  apps/judicial-system/web/src/components/EditableCaseFile/EditableCaseFile.tsx
Labels: automerge

#15931 chore(clients-signature-collection): Update client
  libs/clients/signature-collection/src/clientConfig.json
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge

#15938 fix(driving-license): adding back JurisdictionApi check
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15936 fix(application-system): Removing EES requirement for healthcare license certificate
  libs/application/templates/healthcare-license-certificate/src/lib/HealthcareLicenseCertificateTemplate.ts
Labels: automerge

#15937 fix(application-system): Removing EES requirement for healthcare license certificate
  libs/application/templates/healthcare-license-certificate/src/lib/HealthcareLicenseCertificateTemplate.ts
Labels: automerge

#15935 fix(j-s): Allow prison system users to see rulings
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseFile.interceptor.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
Labels: automerge

#15940 fix(driving-license): hotfix/jurisdictionid back in dl
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15941 chore(web): Parental Leave Calculator - Reverse year order
  apps/web/components/connected/ParentalLeaveCalculator/ParentalLeaveCalculator.tsx
Labels: automerge

#15944 chore: Rightsizing some services
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/portals/admin/infra/portals-admin.ts
  apps/services/user-profile/infra/service-portal-api.ts
  apps/skilavottord/web/infra/skilavottord-web.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#15760 chore: update PDF package
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
  package.json
  yarn.lock
Labels: automerge

#15837 feat(ids-api): Add legal representative delegation type and return in delegation list.
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-test-cases.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-types.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters.spec.ts
  apps/services/auth/ids-api/test/setup.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  libs/api/domains/auth/src/lib/models/delegation.model.ts
  libs/auth-api-lib/seeders/20240829140032-add-delegation-type-legal-representative.js
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/delegations/constants/names.ts
  libs/auth-api-lib/src/lib/delegations/delegation-dto.mapper.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.service.ts
  libs/auth-api-lib/src/lib/delegations/dto/delegation-index.dto.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation-index.model.ts
  libs/auth-api-lib/src/lib/delegations/utils/delegations.ts
  libs/feature-flags/src/lib/features.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/shared/types/src/lib/delegation.ts
Labels: automerge

#15951 fix(web): Pension calculator toggled off
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#15927 feat(signature-collection): Sign parliamentary list hooked up
  libs/api/domains/signature-collection/src/lib/models/candidate.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.service.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/dataSchema.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/signListTemplate.ts
  libs/clients/signature-collection/src/index.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.spec.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
Labels: automerge

#15954 fix(auth-nest-tools): Client claims prefix is defaulted to `client_` with single underscore
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
Labels: automerge

#15867 feat(auth-admin): Delegation admin module
  apps/portals/admin/src/auth.ts
  apps/portals/admin/src/lib/masterNavigation.ts
  apps/portals/admin/src/lib/modules.ts
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.controller.ts
  apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.module.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/api/domains/auth-admin/src/lib/auth-admin.module.ts
  libs/api/domains/auth-admin/src/lib/delegationAdmin/delegation-admin.resolver.ts
  libs/api/domains/auth-admin/src/lib/delegationAdmin/delegation-admin.service.ts
  libs/api/domains/auth-admin/src/lib/delegationAdmin/models/delegation.model.ts
  libs/api/domains/auth-admin/src/lib/delegationProvider/delegation-provider.resolver.ts
  libs/api/domains/auth/src/index.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/delegations/dto/delegation-admin-custom.dto.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/auth/scopes/src/lib/auth.scope.ts
  libs/clients/auth/admin-api/src/index.ts
  libs/clients/auth/admin-api/src/lib/apis.ts
  libs/clients/auth/admin-api/src/lib/auth-admin-api-client.config.ts
  libs/clients/auth/delegation-api/src/index.ts
  libs/portals/admin/delegation-admin/.babelrc
  libs/portals/admin/delegation-admin/.eslintrc.json
  libs/portals/admin/delegation-admin/README.md
  libs/portals/admin/delegation-admin/codegen.yml
  libs/portals/admin/delegation-admin/jest.config.ts
  libs/portals/admin/delegation-admin/project.json
  libs/portals/admin/delegation-admin/src/components/DelegationList.tsx
  libs/portals/admin/delegation-admin/src/index.ts
  libs/portals/admin/delegation-admin/src/lib/messages.ts
  libs/portals/admin/delegation-admin/src/lib/navigation.ts
  libs/portals/admin/delegation-admin/src/lib/paths.ts
  libs/portals/admin/delegation-admin/src/module.tsx
  libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.graphql
  libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.loader.ts
  libs/portals/admin/delegation-admin/src/screens/DelegationAdminDetails/DelegationAdmin.tsx
  libs/portals/admin/delegation-admin/src/screens/Root.action.ts
  libs/portals/admin/delegation-admin/src/screens/Root.tsx
  libs/portals/admin/delegation-admin/tsconfig.json
  libs/portals/admin/delegation-admin/tsconfig.lib.json
  libs/portals/admin/delegation-admin/tsconfig.spec.json
  libs/portals/shared-modules/delegations/src/components/access/AccessCard.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationsIncoming.tsx
  libs/portals/shared-modules/delegations/src/index.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  tsconfig.base.json
Labels: automerge

#15947 feat(web): Team List - Display email, phone and tags for team members
  apps/web/components/Organization/Slice/TeamListSlice/TeamListSlice.tsx
  apps/web/screens/queries/TeamList.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/teamMember.model.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.css.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx
Labels: automerge

#15950 fix(social-insurance-maintenance): HOTFIX - wrong field used
  libs/api/domains/social-insurance/src/lib/models/income/category.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.graphql
  libs/service-portal/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.tsx
Labels: automerge

#15878 feat(Skilavottord): Handle number plates and information about pre-deregistered vehicles
  apps/skilavottord/web/components/CarDetailsBox/CarDetailsBox.tsx
  apps/skilavottord/web/components/CarDetailsBox2/CarDetailsBox2.tsx
  apps/skilavottord/web/components/CarDetailsBox2/index.ts
  apps/skilavottord/web/components/InlineError/InlineError.tsx
  apps/skilavottord/web/components/index.ts
  apps/skilavottord/web/i18n/locales/en.json
  apps/skilavottord/web/i18n/locales/is.json
  apps/skilavottord/web/i18n/locales/translation.d.ts
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/utils/consts.ts
  apps/skilavottord/ws/migrations/20201008200611-vehicle_owner.js
  apps/skilavottord/ws/migrations/20201008210611-vehicle.js
  apps/skilavottord/ws/migrations/20201008210711-recycling-partners.js
  apps/skilavottord/ws/migrations/20201008220611-recycling_request.js
  apps/skilavottord/ws/migrations/20201008230611-gdpr.js
  apps/skilavottord/ws/migrations/20211207210715-access-control.js
  apps/skilavottord/ws/migrations/20220318210711-addcolumn-recycling-partners.js
  apps/skilavottord/ws/migrations/20220318210715-addcolumn-access-control.js
  apps/skilavottord/ws/migrations/20220318210715-alow-null-recycling-partners.js
  apps/skilavottord/ws/migrations/20231113210715-addcolumn-mileage.js
  apps/skilavottord/ws/migrations/20240307280301-add-indexes.js
  apps/skilavottord/ws/migrations/202409083210715-addcolumns-numberplate-info.js
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.model.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.module.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.resolver.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/test/samgongustofa.service.spec.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/transport/index.ts
  apps/skilavottord/ws/src/app/modules/samgongustofa/transport/transport.service.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.model.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicle.service.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.module.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.services.ts
  apps/skilavottord/ws/src/app/utils/const.ts
  apps/skilavottord/ws/src/app/utils/index.ts
  apps/skilavottord/ws/src/app/utils/skilavottordUtils.ts
Labels: automerge

#15946 fix(driving-license): 65 renewal updates
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15963 feat: Configure universal links for the test app
  .github/CODEOWNERS
  apps/web/public/.well-known/apple-app-site-association
Labels: automerge

#15966 chore(app-sys): Convert conventional functions to arrow functions
  apps/application-system/api/src/app/modules/application/utils/delegationUtils.ts
  apps/application-system/api/src/app/modules/application/utils/tokenUtils.ts
  apps/application-system/form/src/utils/index.ts
  libs/application/api/files/src/lib/files.module.ts
  libs/application/api/files/src/lib/pdfGenerators/residenceChange.ts
  libs/application/api/payment/src/lib/types/Charge.ts
  libs/application/core/README.md
  libs/application/core/src/lib/conditionUtils.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/formBuilders.ts
  libs/application/core/src/lib/formUtils.ts
  libs/application/core/src/validation/validators.ts
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/pdfGenerators/templates/residenceChange.ts
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/pdfGenerators/templates/complaint.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/pdfGenerator.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/pdfGenerators/templates/complaintPdf.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/bucket/bucket.service.ts
  libs/application/template-loader/src/index.ts
  libs/application/templates/family-matters/children-residence-change-v2/src/forms/ContractRejected.ts
  libs/application/templates/reference-template/src/fields/ExampleCountryField.tsx
  libs/application/types/src/lib/StateMachine.ts
  libs/application/types/src/lib/application-types.ts
  libs/application/ui-components/src/utilities/FileUploadController/index.tsx
  libs/application/ui-components/src/utilities/handleServerError.ts
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
  libs/application/ui-shell/src/components/FormRepeater.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
  libs/application/ui-shell/src/hooks/useDocumentTitle.ts
  libs/application/ui-shell/src/hooks/useIsWindowSize.ts
  libs/application/ui-shell/src/lib/ApplicationForm.tsx
  libs/application/ui-shell/src/reducer/ApplicationFormReducer.ts
  libs/application/ui-shell/src/reducer/reducerUtils.ts
  libs/application/ui-shell/src/utils.ts
  libs/application/utils/src/lib/builders/paymentStateBuilder.ts
Labels: automerge

#15968 fix(services-auth-admin-api): Fix delegation settings
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
Labels: automerge

#15959 feat(web): Add default header for syslumenn organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennDefaultHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennDefaultHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/index.ts
Labels: automerge

#15971 fix(service-portal): Applications sorting fix
  .github/CODEOWNERS
  libs/service-portal/applications/src/shared/utils/index.ts
Labels: automerge

#15921 feat(j-s): Confirmed court records
  apps/judicial-system/backend/src/app/formatters/confirmedPdf.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
Labels: automerge

#15922 fix(j-s): Don't show UI updates underneath a modal
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#15965 feat(web): Team List - Move frontend logic to the backend
  apps/web/components/Organization/Slice/TeamListSlice/TeamListSlice.tsx
  apps/web/screens/queries/TeamList.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/teamList.model.ts
  libs/cms/src/lib/models/teamMember.model.ts
  libs/cms/src/lib/search/importers/teamList.service.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx
Labels: automerge

#15973 feat(web): Add default header for fiskistofa organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaDefaultHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaDefaultHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
Labels: automerge

#15978 fix(ui-fields): Change button colour, icon and add space
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
Labels: automerge

#15988 fix(auth-admin-api): Add missing xroad config to auth admin api
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15989 ci: fix upload-artifact breaking changes
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#15981 feat(web): Parental leave calculator - Calculation formula updated
  apps/web/components/connected/ParentalLeaveCalculator/ParentalLeaveCalculator.tsx
  apps/web/components/connected/ParentalLeaveCalculator/utils.ts
Labels: automerge

#15983 feat(web): Generic List - UX improvements
  apps/web/components/GenericList/GenericList.css.ts
  apps/web/components/GenericList/GenericList.tsx
  apps/web/components/Organization/Slice/TeamListSlice/TeamListSlice.tsx
Labels: automerge

#15991 fix(auth-admin-api): Add missing env
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15979 fix(samrit): digital license
  libs/application/templates/announcement-of-death/src/lib/messages.ts
  libs/application/templates/driving-license-duplicate/src/forms/application.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDigitalLicenseInfo.ts
  libs/application/templates/driving-license-duplicate/src/lib/messages.ts
Labels: automerge

#15974 fix(efs): Set up for separate feature flag
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/lib/InheritanceReportTemplate.ts
  libs/application/templates/inheritance-report/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#15945 feat(application-plc): Procuration
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/createCollectionTemplate.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge

#15953 feat(income-plan): Incorrect monthly income when changing between montly and yearly income
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
Labels: automerge

#15982 feat(income-plan): Don't allow negative numbers or 0 in income plan
  libs/application/templates/social-insurance-administration/income-plan/src/lib/dataSchema.ts
Labels: automerge

#15987 fix(income-plan): Hide IKR when foreign income
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
  libs/application/templates/social-insurance-administration/income-plan/src/lib/constants.ts
Labels: automerge

#15990 fix(user-profile): Check if nationalId+deviceToken pair exists and only create if not.
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/userProfile.service.ts
Labels: automerge

#15997 fix(cms): Latest Generic List Items - Mark seeMorePage field as nullable
  libs/cms/src/lib/models/latestGenericListItems.model.ts
Labels: automerge

#16000 fix(ids-admin|user-profile): Apply 15968 and 15990 to current release
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  apps/services/user-profile/src/app/user-profile/e2e/userProfile.spec.ts
  apps/services/user-profile/src/app/user-profile/userProfile.controller.ts
  apps/services/user-profile/src/app/user-profile/userProfile.service.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
Labels: automerge

#15998 feat(income-plan): Only allow one income plan in draft
  libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
Labels: automerge

#16001 feat(income-plan): Add disabled to TableRepeaterItem
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterItem.tsx
Labels: automerge

#15999 feat(income-plan): Update updateValueObj in incomeType
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterItem.tsx
Labels: automerge

#15994 chore(j-s): Hide the resend indictment button
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
Labels: automerge

#15995 chore(regulations-admin): Update national registry for regulations
  apps/services/regulations-admin-backend/infra/regulations-admin-backend.ts
  apps/services/regulations-admin-backend/src/app/app.module.ts
  apps/services/regulations-admin-backend/src/app/modules/draft_regulation/draft_regulation.module.ts
  apps/services/regulations-admin-backend/src/app/modules/draft_regulation/draft_regulation.service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#16002 chore(j-s): Left align table values
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.tsx
Labels: automerge

#16006 feat(contentful-apps): Team member filter tags field
  apps/contentful-apps/pages/fields/team-member-filter-tags-field.tsx
Labels: automerge

#16008 feat(contentful-apps): Generic Tag Group - Display in cms what tags belong to group
  apps/contentful-apps/components/lists/GenericListEditor/GenericListEditor.tsx
  apps/contentful-apps/pages/fields/generic-tag-group-items-field.tsx
Labels: automerge

#16012 feat(eb): Add default header for sjukratryggingar organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarDefaultHeader.css.ts
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/SjukratryggingarDefaultHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SjukratryggingarTheme/index.ts
Labels: automerge

#16015 feat(web): Add default header for sak organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.css.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#15961 feat(native-app): Implement universal links
  apps/native/app/android/app/src/prod/AndroidManifest.xml
  apps/native/app/ios/IslandApp/IslandApp.entitlements
  apps/native/app/package.json
  apps/native/app/src/hooks/use-deep-link-handling.ts
  apps/native/app/src/index.tsx
  apps/native/app/src/lib/deep-linking.ts
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/notifications/notifications.tsx
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
  apps/native/app/src/utils/lifecycle/setup-notifications.ts
  yarn.lock
Labels: automerge

#15962 feat(user-notifications): Send notificationId in push notifications
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
Labels: automerge, high priority

#16007 fix(regulations-admin): Update styling. Update presigned query.
  apps/web/components/Regulations/RegulationTexts.types.ts
  libs/api/domains/regulations/src/lib/api-domains-regulations.resolver.ts
  libs/api/domains/regulations/src/lib/dto/createPresignedPost.input.ts
  libs/portals/admin/regulations-admin/src/components/TaskList.tsx
  libs/portals/admin/regulations-admin/src/components/impacts/ImpactListItem.tsx
  libs/portals/admin/regulations-admin/src/utils/dataHooks.ts
Labels: automerge, high priority

#15932 feat(auth-admin): Delegation reference id
  libs/auth-api-lib/migrations/20240910092516-delegation-reference-id.js
  libs/auth-api-lib/src/lib/delegations/dto/delegation.dto.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation.model.ts
Labels: automerge

#16009 fix(native-app): fix android crash due to borderRadius set to string value
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/ui/lib/skeleton/general-card-skeleton.tsx
Labels: automerge

#16003 fix(native-app): optional chaining for content.value and data.[0].mileage
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
Labels: automerge

#16023 feat(web): Add default header for landlaeknir organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.css.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge, high priority

#16016 fix(auth-admin-api): Fix delegation type reset when adding new type
  libs/auth-api-lib/src/lib/clients/clients.service.ts
Labels: automerge, high priority

#16019 feat(service-portal): Signee view for parliamentary signature collection
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Done.ts
  libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
Labels: automerge, high priority

#16020 fix(service-portal): Health Spacing
  libs/service-portal/health/src/screens/OrganDonation/OrganDonation.tsx
Labels: automerge, high priority

#16022 feat(web): Add default header for natturuhamfaratryggingar islands
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge, high priority

#16025 fix(occupational-licenses): Remove date of birth for health directorate licenses
  libs/api/domains/occupational-licenses-v2/src/lib/occupationalLicensesV2.service.ts
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesDetail/OccupationalLicensesDetail.tsx
Labels: automerge, high priority

#16026 fix(application-plc): Stop double candidacies in dataprovider
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/errors.ts
Labels: automerge, high priority

#15970 fix(native-app): fix vehicle details screen transition
  apps/native/app/src/utils/lifecycle/setup-routes.ts
Labels: automerge

#15918 feat(j-s): Subpoena delivery and endpoint for updates
  apps/judicial-system/backend/migrations/20240827132504-create-subpoena.js
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/index.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/police/models/createSubpoena.response.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/deliver.dto.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/updateSubpoena.dto.ts
  apps/judicial-system/backend/src/app/modules/subpoena/guards/subpoena.decorator.ts
  apps/judicial-system/backend/src/app/modules/subpoena/guards/subpoenaExists.guard.ts
  apps/judicial-system/backend/src/app/modules/subpoena/internalSubpoena.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/deliver.response.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/subpoena.model.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.module.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/xrd-api/src/app/app.controller.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/dto/subpoena.dto.ts
  apps/judicial-system/xrd-api/src/app/models/subpoena.response.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#16010 feat(j-s): Civil Demands
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240909194458-rename-explanatory-comment.js
  apps/judicial-system/backend/src/app/formatters/indictmentPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfIndictment.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.module.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/case.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseFile.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseOriginalAncestor.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/completedAppealAccessed.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/limitedAccessCaseFile.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseString.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/index.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.service.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/caseString.ts
Labels: automerge

#15993 fix(register-new-machine): small fixes
  libs/application/template-api-modules/src/lib/modules/templates/aosh/register-new-machine/register-new-machine.service.ts
  libs/application/templates/aosh/register-new-machine/src/fields/AboutMachine/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/ChangeAnswers/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/LicensePlates/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/MachineType/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/Overview/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/index.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/InformationSection/ImporterInformation.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/InformationSection/OperatorInformation.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/InformationSection/OwnerInformation.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/InformationSection/index.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/MachineSection/MachineBasicInformation.ts
  libs/application/templates/aosh/register-new-machine/src/forms/RegisterMachineForm/MachineSection/MachineLicensePlate.ts
  libs/application/templates/aosh/register-new-machine/src/lib/dataSchema.ts
  libs/application/templates/aosh/register-new-machine/src/lib/messages/information.ts
  libs/application/templates/aosh/register-new-machine/src/lib/messages/overview.ts
  libs/application/templates/aosh/register-new-machine/src/utils/canMaybeRegisterToTraffic.ts
  libs/application/templates/aosh/register-new-machine/src/utils/canRegisterToTraffic.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getTechnicalInformation.ts
  libs/application/templates/aosh/register-new-machine/src/utils/isOwnerOtherThanImporter.ts
  libs/clients/work-machines/src/clientConfig.json
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/postalCodes.ts
Labels: automerge

#16011 fix(j-s): Merge Email
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#16024 fix(j-s): Defender Case Info
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#16004 feat(j-s): Add civil claim file upload
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#16031 feat(web): Latest Generic List Items content type - Don't allow clicking on cards if there isn't a 'see more page'
  apps/web/components/GenericList/LatestGenericListItems/LatestGenericListItems.tsx
Labels: automerge

#16032 fix(ojoi): Signature HTML and comments
  libs/api/domains/official-journal-of-iceland-application/src/models/getComments.input.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getComments.response.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/postComment.input.ts
  libs/application/templates/official-journal-of-iceland/src/components/comments/AddComment.tsx
  libs/application/templates/official-journal-of-iceland/src/components/comments/Comment.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Chairman.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/CommitteeMember.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Institution.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/RegularMember.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Comments.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Signatures.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useComments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/comments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/clients/official-journal-of-iceland/application/src/clientConfig.json
  libs/clients/official-journal-of-iceland/application/src/lib/ojoiApplicationClient.service.ts
Labels: automerge

#16033 feat(web): Pension Calculator - Tax calculation translation
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#16030 fix(service-portal): parliamentary refactor signee view
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/modals/DeletePerson/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/modals/LookupPerson/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
  libs/service-portal/signature-collection/src/screens/Presidential/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Presidential/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/screens/Presidential/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/skeletons.tsx
Labels: automerge

#16035 feat(web): Add default header for HSN organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#16037 fix(web): Pension Calculator - Remove space in translation string keys
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#16028 feat(web): Add default header for HMS organization
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#16047 fix: add back in feature flag check for passkeys on logout
  apps/native/app/src/stores/auth-store.ts
Labels: automerge
