Repository island-is/island.is, pull requests merged in 2024-12, with the labels that each got.

#17034 fix: Update FormSystemClient.config.ts
  libs/clients/form-system/src/lib/FormSystemClient.config.ts
Labels: automerge

#17043 feat(j-s): Connect case files to defendant or civil claimants
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/file/dto/createCivilClaimantFile.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/createDefendantFile.input.ts
  apps/judicial-system/api/src/app/modules/file/file.resolver.ts
  apps/judicial-system/api/src/app/modules/file/limitedAccessFile.resolver.ts
  apps/judicial-system/backend/migrations/20241122091513-update-case-file.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/createCivilClaimantCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/createDefendantCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessWriteCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessWriteCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/limitedAccessFile.controller.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/SendToPrisonAdmin/SendToPrisonAdmin.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/createCivilClaimantFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/createDefendantFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessCreateCivilClaimantFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessCreateDefendantFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/limitedAccessCreateFile.graphql
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
Labels: automerge

#17099 fix(services-bff): Fix ingress for portals
  apps/api/infra/api.ts
  apps/services/bff/infra/admin-portal.infra.ts
  apps/services/bff/infra/my-pages-portal.infra.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/api/values.dev.yaml
  charts/services/api/values.prod.yaml
  charts/services/api/values.staging.yaml
  charts/services/services-bff-portals-admin/values.dev.yaml
  charts/services/services-bff-portals-admin/values.prod.yaml
  charts/services/services-bff-portals-admin/values.staging.yaml
  charts/services/services-bff-portals-my-pages/values.dev.yaml
  charts/services/services-bff-portals-my-pages/values.prod.yaml
  charts/services/services-bff-portals-my-pages/values.staging.yaml
Labels: automerge, high priority

#17096 feat(web): Organization pages - Show parent subpage even though standalone theme is not set
  apps/web/pages/s/[...slugs]/index.tsx
Labels: automerge

#17086 fix(contentful-apps): Fix chart component manual data key value on page load
  apps/contentful-apps/pages/fields/chart-component-source-data-key-field.tsx
Labels: automerge

#17097 fix(j-s): Prison admin indictment notifications
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
Labels: automerge

#17105 fix: add missing ns grant to api for bff
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/api/values.dev.yaml
  charts/services/api/values.prod.yaml
  charts/services/api/values.staging.yaml
Labels: automerge, high priority

#17103 chore(j-s): Robot Court Name
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#17100 feat(web): Level 2 navigation for parent subpages should be visible despite theme
  apps/web/pages/s/[...slugs]/index.tsx
Labels: automerge

#17107 feat(auth-admin): Allow non super admin to change Legal Representative Delegation type
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionDelegations.tsx
Labels: automerge

#17085 feat(web): Organization page with "standalone" theme - Level 2 sitemap
  apps/web/pages/s/[...slugs]/index.tsx
  apps/web/screens/Organization/Standalone/Level2Sitemap.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getOrganizationPageStandaloneSitemap.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPageStandaloneSitemap.model.ts
  libs/cms/src/lib/models/organizationParentSubpage.model.ts
Labels: automerge

#17095 feat(web): Add search input to organization standalone theme mobile frontpage
  apps/web/layouts/organization/standalone/components/Header.tsx
  apps/web/layouts/organization/standalone/standalone.tsx
Labels: automerge

#17072 fix(user-notifications): Run worker after bootstrap
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/src/main.ts
Labels: automerge

#16855 fix(license-service): check app version
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/api/domains/license-service/src/lib/mappers/firearmLicenseMapper.ts
  libs/api/domains/license-service/src/lib/resolvers/licenseCollection.resolver.ts
  libs/api/domains/license-service/src/lib/resolvers/userLicense.resolver.ts
  libs/api/domains/license-service/src/lib/utils/appCompatibilityMode.ts
Labels: automerge, deploy-feature

#17029 feat(application-system): Add notifications support to pruning
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.module.ts
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
  apps/application-system/api/src/app/modules/application/lifecycle/test/application-lifecycle-notification.spec.ts
  apps/application-system/api/src/app/modules/application/lifecycle/test/application-lifecycle-unit.spec.ts
  libs/application/api/core/src/lib/application/application.service.ts
  libs/application/core/src/lib/constants.ts
  libs/application/template-api-modules/src/lib/index.ts
  libs/application/templates/README.md
  libs/application/types/src/lib/ApplicationLifecycle.ts
  libs/application/types/src/lib/StateMachine.ts
  libs/clients/user-notification/src/index.ts
  libs/clients/user-notification/src/lib/eagerApiConfiguration.ts
  libs/clients/user-notification/src/lib/userNotificationEagerClient.module.ts
Labels: automerge

#17108 fix(application-system): Fix s3 uri errors in heath insureance application
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts
Labels: automerge

#17065 fix(application-system-form): Checkbox ordering and look consolidation
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/application/ui-shell/src/components/FormMultiField.tsx
  libs/island-ui/core/src/lib/Checkbox/Checkbox.css.ts
Labels: automerge

#17111 fix(application-system): Fix s3 uri errors in heath insureance applic…
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts
Labels: automerge

#17113 fix(Consultation-portal): KAM-2800 user cannot deregister from "all" cases
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionTable/SubscriptionTable.tsx
Labels: automerge

#17054 chore(infra): Move `ARG` declaration for clarity
  scripts/ci/Dockerfile
Labels: automerge, deploy-feature, test everything

#17101 feat(app-sys): national-id-with-name fetch form more endpoints
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-components/src/components/NationalIdWithName/NationalIdWithName.tsx
  libs/application/ui-components/src/components/NationalIdWithName/graphql/queries.ts
  libs/application/ui-fields/src/lib/NationalIdWithNameFormField/NationalIdWithNameFormField.tsx
Labels: automerge

#17120 chore(web): switch line and text around
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
Labels: automerge

#17121 fix(web): order filter
  apps/web/screens/Grants/SearchResults/SearchResultsFilter.tsx
Labels: automerge

#17122 feat(cms): Be able to query organization by national id
  libs/cms/src/lib/cms.contentful.service.ts
Labels: automerge

#17106 fix(citizenship): error indexing child
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/ChildrenPassportReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/DocumentReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectChildren/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenPassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/utils/childrenInfo.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/utils/selectedIndividual.ts
Labels: automerge

#17126 fix(citizenship): error indexing children
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/ChildrenPassportReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Review/DocumentReview.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectChildren/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenPassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/utils/childrenInfo.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/utils/selectedIndividual.ts
Labels: automerge

#17116 fix(web): In case no organization page is found we still want to potentially render a frontpage
  apps/web/pages/s/[...slugs]/index.tsx
Labels: automerge

#17123 feat(web): Add namespace for 'samgongustofa' web chat config
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#17128 feat(web): Latest generic list items - Item count is now editable in the CMS
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/latestGenericListItems.model.ts
Labels: automerge

#17132 fix(infra): `run-local-env` bugfixes
  infra/src/cli/cli.ts
  infra/src/dsl/value-files-generators/local-setup.ts
Labels: automerge

#17135 chore(web): Stop printing web reader
  apps/web/components/Webreader/Webreader.tsx
Labels: automerge

#17133 chore(consultation-portal): Move to ts, and use `API_URL`
  apps/consultation-portal/infra/samradsgatt.ts
  apps/consultation-portal/proxy.config.json
  apps/consultation-portal/proxy.config.ts
  apps/consultation-portal/server.ts
Labels: automerge

#17136 feat(web): WHODAS Calculator - Add text to top of component
  apps/web/components/connected/WHODAS/Calculator.strings.ts
  apps/web/components/connected/WHODAS/Calculator.tsx
Labels: automerge

#17087 feat(old-age-pension): Show conclusion page based on income plan status
  libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/dataProviders/index.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Conclusion/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/index.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#17139 feat(web): WHODAS calculator - Change how we calculate score
  apps/web/components/connected/WHODAS/Calculator.css.ts
  apps/web/components/connected/WHODAS/Calculator.strings.ts
  apps/web/components/connected/WHODAS/Calculator.tsx
Labels: automerge

#17140 chore(application-system-api-worker): Add missing user notification url
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/application-system-api-worker/values.dev.yaml
  charts/services/application-system-api-worker/values.prod.yaml
  charts/services/application-system-api-worker/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#17026 feat(ids-admin): General Mandate delegation for companies
  apps/services/auth/admin-api/project.json
  apps/services/auth/delegation-api/project.json
  apps/services/auth/ids-api/project.json
  apps/services/auth/ids-api/src/app/delegations/test/delegations.controller.spec.ts
  apps/services/auth/ids-api/test/stubs/genericStubs.ts
  libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
Labels: automerge

#16993 feat(auth-admin): Admin notifications
  apps/services/user-notification/src/app/modules/notifications/me-notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/app/modules/notifications/tests/notifications.service.spec.ts
  libs/api/domains/notifications/src/lib/notifications.model.ts
  libs/api/domains/notifications/src/lib/notifications.module.ts
  libs/api/domains/notifications/src/lib/notificationsAdmin.resolver.ts
  libs/api/domains/notifications/src/lib/notificationsAdmin.service.ts
  libs/api/domains/notifications/src/utils/helpers.ts
  libs/nest/pagination/src/lib/paginate.ts
  libs/portals/admin/service-desk/src/lib/messages.ts
  libs/portals/admin/service-desk/src/screens/User/User.graphql
  libs/portals/admin/service-desk/src/screens/User/User.tsx
  libs/portals/admin/service-desk/src/screens/Users/Users.action.ts
Labels: automerge

#17152 feat(j-s): Upload Additional Files to Court
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
Labels: automerge

#17079 feat(j-s): Show indictment decision type to public prosecutor users
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesAwaitingReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesForReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#17149 fix(j-s): Fix Empty National Id
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectDefender.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
Labels: automerge

#17112 fix(j-s): Display confirmation modal before completing case
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
Labels: automerge

#17150 feat(j-s): Upload Confirmed Court Record to Court
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#17144 feat(web): Organization parent subpage - Use organization layout in case theme is not set to 'standalone'
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/pages/s/[...slugs]/index.tsx
  apps/web/screens/Organization/ParentSubpage.tsx
  apps/web/screens/Organization/Standalone/ParentSubpage.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#17154 chore(ids-api): Try fix flaky tests
  apps/services/auth/ids-api/src/app/delegations/delegations-personal-representative.controller.spec.ts
Labels: automerge

#17088 feat(delegation-api): Use national registry v3 for name service
  apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.spec.ts
  libs/auth-api-lib/src/lib/delegations/names.service.ts
Labels: automerge

#17155 fix(native-app): change border radius circle to be full
  apps/native/app/src/ui/utils/theme.ts
Labels: automerge

#17158 fix(j-s): Fix subpoena pdf
  apps/judicial-system/api/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.controller.ts
Labels: automerge

#17157 fix(documents): Sort by publication v1 and v2 by default
  libs/api/domains/documents/src/lib/dto/getDocumentListInput.ts
  libs/api/domains/documents/src/lib/models/v2/documents.input.ts
  libs/clients/documents-v2/src/lib/dto/listDocuments.input.ts
  libs/clients/documents/src/lib/documentClient.ts
  libs/clients/documents/src/lib/models/DocumentInput.ts
Labels: automerge

#17159 fix(inheritance-report): adding funeral service cost
  libs/application/templates/inheritance-report/src/fields/FuneralCost/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewDebts/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#17137 chore(inao-pp): refactor out custom components and enhance validation
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-political-party/financial-statement-political-party.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-political-party/mappers/mapValuesToPartyTypes.ts
  libs/application/templates/inao/financial-statement-political-party/src/components/AssetDebtEquityOverview.tsx
  libs/application/templates/inao/financial-statement-political-party/src/components/Total.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/ElectionEquities/ElectionEquities.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/ElectionStatement/ElectionStatement.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/KeyNumbersCapital/KeyNumbersCapital.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/Overview/Overview.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/PartyOperatingIncome/PartyExpenses.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/PartyOperatingIncome/PartyIncome.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/PartyOperatingIncome/PartyOperatingIncome.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/PartyOverview/PartyOverview.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/Success/Success.tsx
  libs/application/templates/inao/financial-statement-political-party/src/fields/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/conclusionSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/financialStatementSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/capitalNumbersSubsection.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/capitalNumbersSubsection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/equitiesAndLiabilitiesSubsection.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/equitiesAndLiabilitiesSubsection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/operatingCostSubsection.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/operatingCostSubsection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/overviewSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/keyNumbersSection/overviewSection/overviewMultiField.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/applicationForm/overviewSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/done/conclusionSection/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/done/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/lib/dataSchema.ts
  libs/application/templates/inao/financial-statement-political-party/src/lib/messages.ts
  libs/application/templates/inao/financial-statement-political-party/src/utils/constants.ts
  libs/application/templates/inao/financial-statement-political-party/src/utils/helpers.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/DisplayFormField/DisplayFormField.tsx
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#17156 fix(domains-education): Update education inna resolver
  libs/api/domains/education/src/lib/graphql/inna.resolver.ts
Labels: automerge

#17163 feat(web): WHODAS calculator - Remove total score in breakdown and update texts
  apps/web/components/connected/WHODAS/Calculator.css.ts
  apps/web/components/connected/WHODAS/Calculator.strings.ts
  apps/web/components/connected/WHODAS/Calculator.tsx
Labels: automerge

#17167 fix: add missing datadog ns grant to ids web
  apps/services/auth/ids-api/infra/identity-server.ts
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/services/identity-server/values.dev.yaml
  charts/services/identity-server/values.prod.yaml
  charts/services/identity-server/values.staging.yaml
  charts/services/services-auth-ids-api-cleanup/values.dev.yaml
  charts/services/services-auth-ids-api-cleanup/values.prod.yaml
  charts/services/services-auth-ids-api-cleanup/values.staging.yaml
  charts/services/services-auth-ids-api/values.dev.yaml
  charts/services/services-auth-ids-api/values.prod.yaml
  charts/services/services-auth-ids-api/values.staging.yaml
Labels: automerge

#17075 feat(j-s): Show district court abbreviation on mobile
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
Labels: automerge

#17124 fix(ojoi): Input validation and bugfixes
  apps/web/components/OfficialJournalOfIceland/OJOIAdvertCard.tsx
  apps/web/screens/OfficialJournalOfIceland/OJOISearch.tsx
  apps/web/screens/OfficialJournalOfIceland/hooks/useAdverts.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.input.ts
  libs/application/templates/official-journal-of-iceland/src/components/additions/Additions.tsx
  libs/application/templates/official-journal-of-iceland/src/components/input/OJOIInputController.tsx
  libs/application/templates/official-journal-of-iceland/src/components/input/OJOISelectController.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Institution.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Member.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Attachments.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Publishing.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/attachments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/island-ui/core/src/lib/Header/Header.css.ts
  libs/island-ui/core/src/lib/Header/Header.tsx
  libs/island-ui/core/src/lib/Hyphen/Hyphen.tsx
  libs/shared/form-fields/src/lib/SelectController/SelectController.tsx
Labels: automerge

#16877 feat(native-app): use national registry person endpoint (V3)
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/graphql/queries/national-registry.graphql
  apps/native/app/src/screens/family/family-details.tsx
  apps/native/app/src/screens/family/family-overview.tsx
  apps/native/app/src/screens/more/personal-info.tsx
  apps/native/app/src/ui/lib/avatar/avatar.tsx
Labels: automerge

#17164 fix(ids-api): Use name field instead of fullname.
  apps/services/auth/ids-api/src/app/user-profile/user-profile.service.ts
Labels: automerge

#17176 fix(services-bff): Disable PAR until ids resolves error
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/services-bff-portals-admin/values.dev.yaml
  charts/services/services-bff-portals-admin/values.prod.yaml
  charts/services/services-bff-portals-admin/values.staging.yaml
  charts/services/services-bff-portals-my-pages/values.dev.yaml
  charts/services/services-bff-portals-my-pages/values.prod.yaml
  charts/services/services-bff-portals-my-pages/values.staging.yaml
  infra/src/dsl/bff.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/portal-env.spec.ts
Labels: automerge

#17143 feat(contentful-apps): Add organization parent subpage to link group link field
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/linkGroup.model.ts
Labels: automerge

#17177 fix(inheritance-report): adding service to mappers
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/heirs.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#17118 fix(service-portal): Fixes for third-party paths to old login
  apps/native/app/src/lib/passkeys/helpers.ts
  apps/portals/admin/project.json
  apps/portals/my-pages/project.json
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/src/config.ts
  apps/services/user-notification/test/environment.ts
  apps/web/components/Header/LoginButton.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/user-notification-worker/values.dev.yaml
  charts/services/user-notification-worker/values.prod.yaml
  charts/services/user-notification-worker/values.staging.yaml
  charts/services/user-notification/values.dev.yaml
  charts/services/user-notification/values.prod.yaml
  charts/services/user-notification/values.staging.yaml
  libs/react-spa/bff/src/lib/BffProvider.tsx
Labels: automerge

#17185 fix(web): Set DropdownMenu styles to use minWidth
  apps/web/components/Header/LoginButton.css.ts
  apps/web/components/Header/LoginButton.tsx
  libs/island-ui/core/src/lib/DropdownMenu/DropdownMenu.css.ts
Labels: automerge

#17129 feat(j-s): Add indictment count subtypes to IndictmentCount
  apps/judicial-system/api/infra/judicial-system-api.ts
  apps/judicial-system/api/src/app/modules/indictment-count/dto/updateIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/migrations/20241204124025-update-indictment-count.js
  apps/judicial-system/backend/src/app/modules/indictment-count/dto/updateIndictmentCount.dto.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncement.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/updateIndictmentCount.graphql
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  charts/services/judicial-system-api/values.prod.yaml
  charts/services/judicial-system-api/values.staging.yaml
  libs/judicial-system/types/src/lib/feature.ts
Labels: automerge

#17052 feat(j-s): Only registered judge can complete indictment case with ruling
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseTransition.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseTransitionRules.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/caseTransitionGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transitionGuards.spec.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
Labels: automerge

#17182 fix(inheritance-report): deceased share texts
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/deceased.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#17186 fix(application-system-api-worker): Get template error catch
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
Labels: automerge

#17110 feat(j-s): Add modal when revoking send to prison admin
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.strings.ts
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/SendToPrisonAdmin/SendToPrisonAdmin.strings.ts
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
Labels: automerge

#17161 chore(inao-cem): Refactor out custom components
  libs/application/templates/inao/financial-statement-cemetery/README.md
  libs/application/templates/inao/financial-statement-cemetery/src/dataProviders/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryEquities/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryIncomeLimit/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOperation/CemeteryExpenses.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOperation/CemeteryIncome.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOperation/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/BottomBar.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/KeyNumbers/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/KeyNumbersCapital/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/OperatingYear/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/OperatingYear/styles.css.ts
  libs/application/templates/inao/financial-statement-cemetery/src/fields/PowerOfAttorney/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/Success/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/capitalNumberSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/equityAndLiabilitySubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/opperatingCostSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/clientInfoSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/conclusionSection/conclusionSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/overviewSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/overviewSection/oveviewMultiField.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/done/conclusionSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/done/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/notAllowed/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/notAllowed/notAllowedSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/prerequisites/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/prerequisites/prerequsitesSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/lib/dataSchema.ts
  libs/application/templates/inao/financial-statement-cemetery/src/lib/financialStatementCemeteryTemplate.ts
  libs/application/templates/inao/financial-statement-cemetery/src/lib/messages.ts
  libs/application/templates/inao/financial-statement-cemetery/src/types/types.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/constants.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/helpers.ts
  libs/application/templates/inao/financial-statement-cemetery/tsconfig.json
  libs/application/templates/inao/financial-statement-cemetery/tsconfig.lib.json
  libs/application/templates/inao/financial-statement-individual-election/src/dataProviders/index.ts
  libs/application/templates/inao/financial-statement-individual-election/src/forms/prerequisites/prerequisitesSection.ts
  libs/application/templates/inao/financial-statement-individual-election/src/lib/financial-statement-individual-election.ts
  libs/application/templates/inao/financial-statement-political-party/README.md
  libs/application/templates/inao/financial-statement-political-party/src/dataProviders/index.ts
  libs/application/templates/inao/financial-statement-political-party/src/forms/prerequsites/prerequsitesSection.ts
  libs/application/templates/inao/financial-statement-political-party/src/lib/financialStatementPoliticalPartyTemplate.ts
Labels: automerge

#17115 fix(web): Fix query for generic and team member lists
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/search/importers/genericListItem.service.ts
  libs/cms/src/lib/search/importers/teamList.service.ts
Labels: automerge

#17138 fix(my-pages): small tweaks for vaccinations
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/portals/my-pages/core/src/components/SortableTable/SortableTable.tsx
  libs/portals/my-pages/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/portals/my-pages/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
  libs/portals/my-pages/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
Labels: automerge

#17000 chore: Helm template support for ArgoCD
  infra/helm/libs/api-template/templates/deployment.yaml
  infra/helm/libs/api-template/templates/hpa.yaml
  infra/helm/libs/api-template/templates/ingress.yaml
  infra/helm/libs/api-template/templates/namespaces.yaml
  infra/helm/libs/api-template/templates/pdb.yaml
  infra/helm/libs/api-template/templates/secrets.yaml
  infra/helm/libs/api-template/templates/service.yaml
  infra/helm/libs/cronjob-template/templates/cronjob.yaml
Labels: automerge

#17172 feat: Add codeOwner to logging context
  libs/infra-tracing/src/lib/code-owner.spec.ts
  libs/infra-tracing/src/lib/code-owner.ts
  libs/logging/src/lib/context.spec.ts
  libs/logging/src/lib/context.ts
  libs/nest/core/src/lib/code-owner/code-owner.interceptor.spec.ts
  libs/nest/core/src/lib/code-owner/code-owner.interceptor.ts
Labels: automerge

#17183 feat(web): WHODAS calculator - Allow users to go to previous step using browser back
  apps/web/components/connected/WHODAS/Calculator.tsx
  package.json
  yarn.lock
Labels: automerge

#17181 fix(social-insurance-maintenance): Disable payment plan with FF
  libs/feature-flags/src/lib/features.ts
  libs/portals/my-pages/social-insurance-maintenance/src/lib/messages.ts
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/IncomePlan.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.tsx
Labels: automerge

#17151 fix(core): S3 copy object with foreign characters
  libs/nest/aws/src/lib/s3.service.ts
Labels: automerge, deploy-feature

#17174 feat(j-s): Notifications to prosecutors office in completed indictments
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.module.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.service.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/indictmentCaseNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/notificationDispatch.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.config.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/app/modules/notification/notificationDispatch.service.ts
  apps/judicial-system/backend/src/app/modules/notification/services/indictmentCaseNotification/indictmentCaseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/services/indictmentCaseNotification/indictmentCaseNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/eventNotificationDispatch/eventNotificationDispatch.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/indictmentCaseNotification/sendIndictmentVerdictInfoNotification.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentsWaitingForConfirmationNotifications.spec.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  charts/services/judicial-system-backend/values.dev.yaml
  charts/services/judicial-system-backend/values.prod.yaml
  charts/services/judicial-system-backend/values.staging.yaml
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#17102 fix(auth-react): Remove auth-react library in favour of bff
  libs/auth/react/.babelrc
  libs/auth/react/.eslintrc.json
  libs/auth/react/README.md
  libs/auth/react/babel-jest.config.json
  libs/auth/react/jest.config.ts
  libs/auth/react/project.json
  libs/auth/react/src/index.ts
  libs/auth/react/src/lib/AuthSettings.spec.ts
  libs/auth/react/src/lib/AuthSettings.ts
  libs/auth/react/src/lib/auth/Auth.css.ts
  libs/auth/react/src/lib/auth/Auth.state.ts
  libs/auth/react/src/lib/auth/AuthContext.tsx
  libs/auth/react/src/lib/auth/AuthErrorScreen.tsx
  libs/auth/react/src/lib/auth/AuthProvider.mocked.spec.tsx
  libs/auth/react/src/lib/auth/AuthProvider.spec.tsx
  libs/auth/react/src/lib/auth/AuthProvider.tsx
  libs/auth/react/src/lib/auth/CheckIdpSession.tsx
  libs/auth/react/src/lib/auth/MockedAuthProvider.spec.tsx
  libs/auth/react/src/lib/auth/MockedAuthProvider.tsx
  libs/auth/react/src/lib/authLink.ts
  libs/auth/react/src/lib/createMockUser.ts
  libs/auth/react/src/lib/getAccessToken.spec.ts
  libs/auth/react/src/lib/getAccessToken.ts
  libs/auth/react/src/lib/userManager.ts
  libs/auth/react/src/lib/utils/tinyMemoize.spec.ts
  libs/auth/react/src/lib/utils/tinyMemoize.ts
  libs/auth/react/src/lib/utils/toStringScope.spec.ts
  libs/auth/react/src/lib/utils/toStringScope.ts
  libs/auth/react/test/setup.ts
  libs/auth/react/tsconfig.json
  libs/auth/react/tsconfig.lib.json
  libs/auth/react/tsconfig.spec.json
  libs/island-ui/storybook/config/main.ts
  tsconfig.base.json
Labels: automerge

#17193 fix(ads): Update code for explicit and manual use
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
Labels: automerge

#17178 docs(service-bff): Bff trouble shooting guide
  apps/services/bff/README.md
  apps/services/bff/TROUBLESHOOT_GUIDE.md
Labels: automerge

#17207 fix(ads-my-pages): vaccine, ads explicit - hotfix
  apps/air-discount-scheme/backend/src/app/modules/discount/discount.service.ts
  apps/air-discount-scheme/backend/src/app/modules/discount/test/unit/discount.service.spec.ts
  apps/air-discount-scheme/backend/src/app/modules/user/user.service.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/portals/my-pages/core/src/components/SortableTable/SortableTable.tsx
  libs/portals/my-pages/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/portals/my-pages/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
  libs/portals/my-pages/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
Labels: automerge

#17213 refactor(services-bff): Update failed login attempt data retrieval
  apps/services/bff/src/app/modules/auth/auth.service.ts
Labels: automerge

#17212 fix(react-spa-bff): Enhance broadcaster with subpath handling
  libs/react-spa/bff/src/lib/BffPoller.tsx
  libs/react-spa/bff/src/lib/BffProvider.tsx
  libs/react-spa/bff/src/lib/bff.hooks.ts
Labels: automerge

#17189 feat(web): add support links to grants
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
  apps/web/screens/queries/Grants.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/grant.model.ts
Labels: automerge

#17184 chore(j-s): Add more info to new indictment robot emails
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentInfoToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/court/test/createCourtCase.spec.ts
Labels: automerge

#17200 feat(j-s): Tooltip with info about service not being required
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
Labels: automerge

#17127 feat(web): updated grant status logic
  apps/web/pages/en/grants-plaza/grant/[id].ts
  apps/web/pages/en/grants-plaza/grants/index.ts
  apps/web/pages/en/grants-plaza/index.ts
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
  apps/web/screens/Grants/Home/GrantsHome.tsx
  apps/web/screens/Grants/SearchResults/SearchResultsContent.tsx
  apps/web/screens/Grants/messages.ts
  apps/web/screens/Grants/utils.ts
  apps/web/screens/queries/Grants.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/grant.model.ts
  libs/cms/src/lib/search/importers/grants.service.ts
Labels: automerge

#17195 chore(inao-cem): Refactor custom components and fetch tax data
  .github/CODEOWNERS
  libs/application/templates/inao/financial-statement-cemetery/src/dataProviders/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryIncomeLimit/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/AboutOverview.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/CapitalNumbersOverview.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/FetchDataBasedOnSelectedYear/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/PowerOfAttorney/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryCaretakerSection/caretakerMultiField.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryCaretakerSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryFinancialStatementSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/capitalNumberSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/equityAndLiabilitySubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/opperatingCostSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/clientInfoSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/hooks/useTotals.ts
  libs/application/templates/inao/financial-statement-cemetery/src/lib/dataSchema.ts
  libs/application/templates/inao/financial-statement-cemetery/src/types/types.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/constants.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/currency.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/helpers.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/overviewUtils.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/sums.ts
Labels: automerge

#17171 feat(j-s): Add court name abbr. to prison cases table
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/prisonCases.graphql
Labels: automerge

#17162 fix(application-system): Possible to go back to hidden screens
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/components/ScreenFooter.tsx
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/application/ui-shell/src/reducer/reducerUtils.ts
Labels: automerge

#17218 fix(j-s): Police case number in robot e-mail
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#17199 feat(user-notification): Firebase Credentials Setup for Local Development
  infra/src/cli/render-secrets.ts
Labels: automerge

#17221 feat(native-app): Update passkey information link
  apps/native/app/ios/Podfile.lock
  apps/native/app/src/screens/passkey/passkey.tsx
Labels: automerge

#17202 feat(web): Service web contact form - Add custom fields for 'Vinnueftirlitið'
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/components/ServiceWeb/Forms/StandardForm/types.ts
  apps/web/screens/ServiceWeb/Forms/utils.ts
Labels: automerge

#17194 feat(user-notification): Change action button text
  apps/services/user-notification/src/assets/images/en-button-open.png
  apps/services/user-notification/src/assets/images/is-button-open.png
Labels: automerge

#17222 fix(services-bff): Bff fixes
  apps/services/bff/src/app/modules/auth/auth.service.ts
  libs/react-spa/bff/src/lib/BffPoller.tsx
  libs/react-spa/bff/src/lib/BffProvider.tsx
  libs/react-spa/bff/src/lib/bff.hooks.ts
Labels: automerge

#17201 feat(ids-api): Enable getting fake users in v3 client. Configure for ids-api envs.
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/ids-api/src/app/app.module.ts
  apps/services/auth/ids-api/src/app/user-profile/user-profile.service.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/services/services-auth-ids-api/values.dev.yaml
  charts/services/services-auth-ids-api/values.prod.yaml
  charts/services/services-auth-ids-api/values.staging.yaml
  libs/auth-api-lib/src/lib/delegations/alive-status.service.ts
  libs/clients/national-registry/v3/src/lib/nationalRegistryV3.service.ts
Labels: automerge

#17210 feat(app-sys): changes to app sys that were bundled with financial aid update
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/types/src/lib/Form.ts
  libs/application/ui-fields/src/lib/AccordionFormField/AccordionFormField.tsx
  libs/application/ui-fields/src/lib/BankAccountFormField/BankAccountFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/application/ui-shell/src/utils.ts
Labels: automerge

#17227 chore: allow staging to scale down more
  charts/identity-server/values.staging.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.staging.yaml
  charts/services/air-discount-scheme-api/values.staging.yaml
  charts/services/air-discount-scheme-backend/values.staging.yaml
  charts/services/air-discount-scheme-web/values.staging.yaml
  charts/services/api/values.staging.yaml
  charts/services/application-system-api/values.staging.yaml
  charts/services/auth-admin-web/values.staging.yaml
  charts/services/consultation-portal/values.staging.yaml
  charts/services/judicial-system-api/values.staging.yaml
  charts/services/judicial-system-backend/values.staging.yaml
  charts/services/judicial-system-scheduler/values.staging.yaml
  charts/services/license-api/values.staging.yaml
  charts/services/portals-admin/values.staging.yaml
  charts/services/search-indexer-service/values.staging.yaml
  charts/services/service-portal-api/values.staging.yaml
  charts/services/service-portal/values.staging.yaml
  charts/services/services-auth-admin-api/values.staging.yaml
  charts/services/services-auth-delegation-api/values.staging.yaml
  charts/services/services-auth-ids-api/values.staging.yaml
  charts/services/services-auth-personal-representative-public/values.staging.yaml
  charts/services/services-auth-personal-representative/values.staging.yaml
  charts/services/services-auth-public-api/values.staging.yaml
  charts/services/services-bff-portals-admin/values.staging.yaml
  charts/services/services-bff-portals-my-pages/values.staging.yaml
  charts/services/services-sessions/values.staging.yaml
  charts/services/services-university-gateway/values.staging.yaml
  charts/services/skilavottord-web/values.staging.yaml
  charts/services/user-notification-worker/values.staging.yaml
  charts/services/web/values.staging.yaml
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#17229 chore: allow staging to scale down more (#17227)
  charts/identity-server/values.staging.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.staging.yaml
  charts/services/air-discount-scheme-api/values.staging.yaml
  charts/services/air-discount-scheme-backend/values.staging.yaml
  charts/services/air-discount-scheme-web/values.staging.yaml
  charts/services/api/values.staging.yaml
  charts/services/application-system-api/values.staging.yaml
  charts/services/auth-admin-web/values.staging.yaml
  charts/services/consultation-portal/values.staging.yaml
  charts/services/judicial-system-api/values.staging.yaml
  charts/services/judicial-system-backend/values.staging.yaml
  charts/services/judicial-system-scheduler/values.staging.yaml
  charts/services/license-api/values.staging.yaml
  charts/services/portals-admin/values.staging.yaml
  charts/services/search-indexer-service/values.staging.yaml
  charts/services/service-portal-api/values.staging.yaml
  charts/services/service-portal/values.staging.yaml
  charts/services/services-auth-admin-api/values.staging.yaml
  charts/services/services-auth-delegation-api/values.staging.yaml
  charts/services/services-auth-ids-api/values.staging.yaml
  charts/services/services-auth-personal-representative-public/values.staging.yaml
  charts/services/services-auth-personal-representative/values.staging.yaml
  charts/services/services-auth-public-api/values.staging.yaml
  charts/services/services-bff-portals-admin/values.staging.yaml
  charts/services/services-bff-portals-my-pages/values.staging.yaml
  charts/services/services-sessions/values.staging.yaml
  charts/services/services-university-gateway/values.staging.yaml
  charts/services/skilavottord-web/values.staging.yaml
  charts/services/user-notification-worker/values.staging.yaml
  charts/services/web/values.staging.yaml
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/hpa.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#17223 feat(web): Auto open livechat if query param present
  apps/web/components/ChatPanel/LiveChatIncChatPanel/LiveChatIncChatPanel.tsx
Labels: automerge

#16852 fix(skilavottord): Fix error message being shown if vehicle is not found for registration
  apps/skilavottord/web/graphql/errorLink.ts
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Overview/Overview.tsx
  apps/skilavottord/web/utils/roleUtils.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#17196 chore(j-s): Send signed court record to police for investigation cases
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedCourtRecordToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverSignedCourtRecordToPoliceGuards.spec.ts
  apps/judicial-system/web/messages/Core/errors.ts
  libs/judicial-system/message/src/lib/message.service.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#17148 chore(j-s): Show send to prison admin file
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.strings.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#17117 feat(web): Pension Calculator - "After September 1 2025" year option
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
  libs/api/domains/social-insurance/src/lib/dtos/pensionCalculation.input.ts
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge, deploy-feature

#17191 feat(web): add button label
  apps/web/screens/Grants/Grant/Grant.tsx
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
  apps/web/screens/Grants/messages.ts
  apps/web/screens/queries/Grants.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/grant.model.ts
  libs/cms/src/lib/search/importers/grants.service.ts
Labels: automerge

#17169 feat(j-s): Notifications sent when court officials are assigned
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/notification/services/caseNotification/caseNotification.service.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#17245 feat(web): Hotfix - Pension Calculator, "After September 1 2025" year option #17117
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
  libs/api/domains/social-insurance/src/lib/dtos/pensionCalculation.input.ts
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge

#17244 fix(inao-cem): remove custom components that cause problems
  libs/application/templates/inao/financial-statement-cemetery/src/dataProviders/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryIncomeLimit/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/AboutOverview.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/CapitalNumbersOverview.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/CemeteryOverview/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/FetchDataBasedOnSelectedYear/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/PowerOfAttorney/index.tsx
  libs/application/templates/inao/financial-statement-cemetery/src/fields/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryCaretakerSection/caretakerMultiField.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryCaretakerSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryFinancialStatementSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/capitalNumberSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/equityAndLiabilitySubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/cemeteryKeyNumbersSection/opperatingCostSubSection.ts
  libs/application/templates/inao/financial-statement-cemetery/src/forms/applicationForm/clientInfoSection/index.ts
  libs/application/templates/inao/financial-statement-cemetery/src/hooks/useTotals.ts
  libs/application/templates/inao/financial-statement-cemetery/src/lib/dataSchema.ts
  libs/application/templates/inao/financial-statement-cemetery/src/types/types.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/constants.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/currency.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/helpers.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/overviewUtils.ts
  libs/application/templates/inao/financial-statement-cemetery/src/utils/sums.ts
  libs/clients/financial-statements-inao/src/lib/financialStatementsInao.config.ts
Labels: automerge

#17251 feat(web): Pension Calculator - Display icon to left of title for 2025 preview
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorTitle.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: automerge

#17253 fix(services-bff): Add missing exp check on the user endpoint
  apps/services/bff/src/app/modules/user/user.controller.spec.ts
  apps/services/bff/src/app/modules/user/user.service.ts
Labels: automerge

#17257 feat(income-plan): remove edit functionality
  libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.spec.ts
  libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
  libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
Labels: automerge

#17205 fix(social-insurance-maintenance): add warning
  libs/portals/my-pages/social-insurance-maintenance/src/lib/messages.ts
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlanDetail/IncomePlanDetail.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge, deploy-feature

#17198 feat(j-s): Add punishment type to indictment overview
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/defendant/defendant.module.ts
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/limitedAccessDefendant.resolver.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20241211095654-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/defendant.module.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/defendant/limitedAccessDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/createTestingDefendantModule.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/limitedAccessDefendantController/updateDefendant.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/limitedAccessDefendantController/updateDefendantRolesRules.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/limitedAccessUpdateDefendant.graphql
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/defendant.ts
Labels: automerge

#17258 fix(new-primary-school): mock users dev
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.service.ts
Labels: automerge, deploy-feature

#17263 feat(app-sys): add tab title option
  libs/application/types/src/lib/Form.ts
  libs/application/ui-shell/src/hooks/useApplicationTitle.ts
Labels: automerge

#17261 fix(my-pages): Remove health doc button
  apps/download-service/src/app/app.module.ts
  apps/download-service/src/app/modules/health/payment-overview-documents.controller.ts
  libs/portals/my-pages/health/src/screens/Payments/PaymentOverview.tsx
Labels: automerge

#17266 feat(web): Hotfix - Global search alias for 'Vinnumálastofnun' (#17204)
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge

#17264 fix(j-s): Render sent to prison admin files for FMST
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#17217 chore(application-system): Improving form field styling consistency
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/CompanySearchFormField/CompanySearchFormField.tsx
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/DisplayFormField/DisplayFormField.tsx
  libs/application/ui-fields/src/lib/DividerFormField/DividerFormField.tsx
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.tsx
  libs/application/ui-fields/src/lib/FileUploadFormField/FileUploadFormField.tsx
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/KeyValueFormField/KeyValueFormField.tsx
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
  libs/application/ui-fields/src/lib/PaymentChargeOverviewFormField/PaymentChargeOverviewFormField.tsx
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/application/ui-fields/src/lib/RedirectToServicePortalFormField/RedirectToServicePortalFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/application/ui-fields/src/lib/SliderFormField/SliderFormField.tsx
  libs/application/ui-fields/src/lib/SubmitFormField/SubmitFormField.tsx
  libs/application/ui-fields/src/lib/TextFormField/TextFormField.tsx
  libs/application/ui-fields/src/lib/VehicleRadioFormField/VehicleRadioFormField.tsx
Labels: automerge

#17268 fix(my-pages): Remove health doc button hotfi
  apps/download-service/src/app/app.module.ts
  apps/download-service/src/app/modules/health/payment-overview-documents.controller.ts
  libs/portals/my-pages/health/src/screens/Payments/PaymentOverview.tsx
Labels: automerge

#17208 feat(web): new header for Rannis org page
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
Labels: automerge

#17269 fix(new-primary-school): Use guardian role instead of parent
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
Labels: automerge

#17271 fix(web): Boost chat panel - use pushUp prop
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
Labels: automerge

#17209 feat(j-s): Set court session type to arraignment when subpoena created
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
Labels: automerge

#17272 fix(web): Hotfix - Boost chat panel, use pushUp prop #17271
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
Labels: automerge

#17270 feat(web): RSS feed for events and generic list items
  apps/web/pages/api/rss/index.ts
  apps/web/screens/queries/Events.ts
  libs/cms/src/lib/models/event.model.ts
Labels: automerge, deploy-feature

#17256 fix(application-system): Fix radio and description field spacing
  libs/application/ui-fields/src/lib/DescriptionFormField/DescriptionFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/shared/form-fields/src/lib/RadioController/RadioController.tsx
Labels: automerge

#17259 feat(native-app): add english translations for organ donation in app
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
  apps/native/app/src/messages/en.ts
Labels: automerge

#17234 fix: search indexer service scaling on staging
  charts/islandis/values.staging.yaml
  charts/services/search-indexer-service/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
Labels: automerge

#17249 feat(user-profile): Remove user-profile V1 from api layer
  libs/api/domains/user-profile/src/lib/V1/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/V2/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/dto/confirmEmailVerificationInput.ts
  libs/api/domains/user-profile/src/lib/dto/confirmSmsVerificationInput.ts
  libs/api/domains/user-profile/src/lib/userProfile.module.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/portals/my-pages/graphql/src/hooks/profile/useResendEmailVerification.ts
  libs/portals/my-pages/graphql/src/index.ts
  libs/portals/my-pages/graphql/src/lib/mutations/resendEmailVerification.ts
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
Labels: automerge

#17203 feat(my-pages): Mileage charts for vehicles
  libs/feature-flags/src/lib/features.ts
  libs/portals/my-pages/assets/src/lib/messages.ts
  libs/portals/my-pages/assets/src/lib/navigation.ts
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageSubData.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageTable.tsx
  libs/portals/my-pages/assets/src/screens/VehicleMileage/VehicleMileage.tsx
  libs/portals/my-pages/assets/src/utils/displayWithUnit.ts
  libs/portals/my-pages/core/src/components/Charts/SimpleBarChart/SimpleBarChart.tsx
  libs/portals/my-pages/core/src/components/Charts/SimpleBarChart/styles.css.ts
  libs/portals/my-pages/core/src/components/Charts/charts.css.ts
  libs/portals/my-pages/core/src/components/Charts/index.ts
  libs/portals/my-pages/core/src/components/Charts/sharedChartComponents.tsx
  libs/portals/my-pages/core/src/components/EmptyTable/EmptyTable.tsx
  libs/portals/my-pages/core/src/index.ts
  libs/portals/my-pages/core/src/lib/messages.ts
Labels: automerge, deploy-feature

#17283 feat(web): Organization pages, boolean in CMS that'll hide pages from search engines
  apps/contentful-apps/pages/fields/admin-only-boolean-field.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/search/importers/organizationPage.service.ts
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
Labels: automerge

#17278 fix(web): Overview Links, stop using Image component
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
Labels: automerge, deploy-feature

#17289 fix(my-pages-assets): chart fixes
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageSubData.tsx
  libs/portals/my-pages/core/src/components/Charts/SimpleBarChart/SimpleBarChart.tsx
  libs/portals/my-pages/core/src/components/Charts/sharedChartComponents.tsx
Labels: automerge

#17293 fix(application-system): Fix post-cleanup codegen
  libs/application/templates/accident-notification/src/utils/miscUtils.ts
Labels: automerge, high priority

#17282 fix(web): RSS feed - Lowercase t in "contentType" query param
  apps/web/pages/api/rss/index.ts
Labels: automerge

#17228 feat(my-pages): add back "other" for organ donation registration
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/organ-donation.model.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/clientConfig.json
  libs/portals/my-pages/health/src/lib/messages.ts
  libs/portals/my-pages/health/src/module.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/OrganDonation.css.ts
  libs/portals/my-pages/health/src/screens/OrganDonation/OrganDonation.graphql
  libs/portals/my-pages/health/src/screens/OrganDonation/OrganDonation.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/components/Limitations.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/components/Loader.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/components/NoAccess.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/components/RegistrationForm.tsx
  libs/portals/my-pages/health/src/screens/OrganDonation/helpers/textMapper.ts
  libs/portals/my-pages/health/src/screens/OrganDonationRegistration/Limitations.tsx
  libs/portals/my-pages/health/src/screens/OrganDonationRegistration/OrganDonationRegistration.css.ts
Labels: automerge

#17294 feat(web): Hotfix - Organization pages, boolean in CMS that'll hide pages from search engines (#17283)
  apps/contentful-apps/pages/fields/admin-only-boolean-field.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/cms/src/lib/search/importers/organizationPage.service.ts
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
Labels: automerge

#17232 feat(j-s): Allow defenders to filter cases by court date
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
Labels: automerge

#17275 feat(ojoi): Advert main types
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.input.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.model.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.response.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.resolver.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.service.ts
  libs/application/templates/official-journal-of-iceland/src/components/htmlEditor/HTMLEditor.tsx
  libs/application/templates/official-journal-of-iceland/src/components/input/OJOISelectController.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/AdvertModal.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useTypes.ts
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/advert.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/application/templates/official-journal-of-iceland/src/screens/InvolvedPartyScreen.tsx
  libs/clients/official-journal-of-iceland/public/src/clientConfig.json
  libs/clients/official-journal-of-iceland/public/src/lib/officialJournalOfIcelandClient.service.ts
Labels: automerge

#17279 feat(j-s): Add received date and new table state tag for indictment prison cases
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/case.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/defendantIndictmentAccessed.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getById.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendantEventLog.model.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/Tags/utils.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
  apps/judicial-system/web/src/routes/Shared/Cases/prisonCases.graphql
  libs/judicial-system/types/src/lib/eventLog.ts
Labels: automerge

#17297 fix(web): RSS feed - Event dates should show single digit for date if it can
  apps/web/pages/api/rss/index.ts
Labels: automerge

#17299 chore(j-s): remove the option to set a reviewer when a decision has been taken
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#17292 feat(web): Article Institution Panel - Read eyebrow text from org namespace
  apps/web/screens/Article/Article.tsx
Labels: automerge

#17295 fix(inheritance-report): Fixes for go live
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/inheritanceExecutor.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17306 fix(inheritance-report): Hotfix for efs golive
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/forms/prerequisites.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/debtsAndFuneralCost.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/inheritanceExecutor.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17214 feat(web): Grant - Mobile view and sidemenu refactor
  apps/web/screens/Grants/Grant/Grant.css.ts
  apps/web/screens/Grants/Grant/Grant.tsx
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/DetailPanel.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/ExtraPanel.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/GrantSidebar.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/PanelLine.tsx
  apps/web/screens/Grants/messages.ts
  apps/web/screens/Grants/utils.ts
  libs/island-ui/core/src/lib/Breadcrumbs/Breadcrumbs.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/DetailedInfoCard.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/InfoCard.css.ts
Labels: automerge

#17304 fix(auth-delegations): Fix missing domains for legal representative delegations
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/utils/filterByScopeCustomScopeRule.ts
  libs/auth-api-lib/src/lib/resources/delegation-resources.service.ts
  libs/auth-api-lib/src/lib/resources/resources.module.ts
Labels: automerge

#17305 fix(application-system): Fix checkbox half width and third width layout
  libs/application/templates/reference-template/src/forms/exampleForm/tablesAndRepeatersSection/fieldsRepeaterSubsection.ts
  libs/application/ui-fields/src/lib/FieldsRepeaterFormField/FieldsRepeaterItem.tsx
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterItem.tsx
Labels: automerge
