Repository island-is/island.is, pull requests merged in 2024-10, with the labels that each got.

#16210 fix(bulk-vehicle-mileage): Fixes
  libs/api/domains/vehicles/src/lib/models/v3/mileageDetails.model.ts
  libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.graphql
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageFileDownloader.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageSaveButton.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageTable.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/mocks/propsDummy.ts
  libs/service-portal/assets/src/screens/VehicleBulkMileage/types.ts
  libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileageUpload/VehicleBulkMileageUpload.tsx
  libs/service-portal/assets/src/utils/parseCsvToMileage.ts
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#16212 fix(delegations): Fix delete for GeneralMandate delegations
  libs/portals/shared-modules/delegations/src/components/access/AccessDeleteModal/AccessDeleteModal.tsx
Labels: automerge

#16216 fix(download-service): Update usage of accesstoken in jwt strategy and download service controllers
  apps/download-service/src/app/modules/documents/document.controller.ts
  apps/download-service/src/app/modules/documents/dto/getDocument.dto.ts
  apps/download-service/src/app/modules/education-documents/dto/getEducationGraduationDocument.ts
  apps/download-service/src/app/modules/education-documents/education-document.controller.ts
  apps/download-service/src/app/modules/finance-documents/document.controller.ts
  apps/download-service/src/app/modules/finance-documents/dto/getFinanceDocument.dto.ts
  apps/download-service/src/app/modules/health/dto/getHealthPaymentDocument.dto.ts
  apps/download-service/src/app/modules/health/payment-overview-documents.controller.ts
  apps/download-service/src/app/modules/occupational-licenses/occupational-license.controller.ts
  apps/download-service/src/app/modules/regulation-documents/dto/getRegulationDraftDocument.dto.ts
  apps/download-service/src/app/modules/regulation-documents/regulation-documents.controller.ts
  apps/download-service/src/app/modules/vehicles-documents/dto/getVehicleHistoryDocument.dto.ts
  apps/download-service/src/app/modules/vehicles-documents/vehicle-document.controller.ts
  apps/download-service/src/app/modules/work-machines-documents/dto/getWorkMachineCollectionDocument.dto.ts
  apps/download-service/src/app/modules/work-machines-documents/work-machines-documents.controller.ts
  libs/api/domains/finance/src/lib/api-domains-finance.resolver.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
Labels: automerge

#16227 fix(j-s): Fix e2e test
  apps/system-e2e/src/tests/judicial-system/regression/custody-tests.spec.ts
Labels: automerge

#16111 chore(application-system): template-api-modules unit test improvements
  apps/application-system/api/src/app/modules/application/utils/applicationUtils.spec.ts
  apps/application-system/api/src/app/modules/application/utils/delegationUtils.spec.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-cemetery/mappers/mapValuesToUserType.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-individual-election/mappers/helpers.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-individual-election/mappers/helpers.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-individual-election/mappers/mapValuesToUserTypes.spec.ts
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection/workMachineSubSection.ts
  libs/application/templates/accident-notification/src/index.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/workMachine.ts
  libs/application/templates/accident-notification/src/utils/hasMissingDocuments.spec.ts
  libs/application/templates/accident-notification/src/utils/hasReceivedConfirmation.spec.ts
  libs/application/templates/accident-notification/src/utils/index.spec.ts
  libs/application/templates/accident-notification/src/utils/index.ts
  libs/application/templates/accident-notification/src/utils/isFatalAccident.spec.ts
  libs/application/templates/accident-notification/src/utils/isHealthInsured.spec.ts
  libs/application/templates/accident-notification/src/utils/isReportingBehalfOfSelf.spec.ts
  libs/application/templates/accident-notification/src/utils/isRepresentativeOfCompanyOrInstitue.spec.ts
  libs/application/templates/accident-notification/src/utils/isRepresentativeOfCompanyOrInstitute.spec.ts
  libs/application/templates/accident-notification/src/utils/isRepresentativeOfCompanyOrInstitute.ts
Labels: automerge

#16230 feat(signature-collection): Admin area summary report endpoint
  libs/api/domains/signature-collection/src/lib/dto/areaSummaryReport.input.ts
  libs/api/domains/signature-collection/src/lib/models/areaSummaryReport.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/types/areaSummaryReport.dto.ts
Labels: automerge

#16221 fix(web): Districts slice - text wrap and style changes
  apps/web/components/Organization/Slice/Districts/DistrictsSlice.css.ts
  apps/web/components/Organization/Slice/Districts/DistrictsSlice.tsx
Labels: automerge

#16220 fix(skilavottord): Handle null value in model year
  apps/skilavottord/web/utils/dateUtils.ts
  apps/skilavottord/ws/src/app/modules/vehicle/dto/createVehicle.input.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/shared/types.ts
  libs/clients/car-recycling/src/lib/carRecyclingClient.service.ts
Labels: automerge

#16127 feat(contentful-apps): Team member - Editor app
  apps/contentful-apps/components/editors/ContentfulField.tsx
  apps/contentful-apps/components/editors/TeamMemberEditor/TeamMemberEditor.tsx
  apps/contentful-apps/components/editors/TeamMemberEditor/TeamMemberFilterTagsField.tsx
  apps/contentful-apps/components/editors/lists/GenericListEditor/GenericListEditor.tsx
  apps/contentful-apps/components/editors/lists/GenericListItemEditor/GenericListItemEditor.tsx
  apps/contentful-apps/components/editors/utils.ts
  apps/contentful-apps/pages/editors/generic-list-editor.ts
  apps/contentful-apps/pages/editors/generic-list-item-editor.ts
  apps/contentful-apps/pages/editors/team-member-editor.ts
  libs/cms/src/lib/models/teamMember.model.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx
Labels: automerge

#16164 feat(native-app): add upgrade wall to app
  apps/native/app/ios/IslandApp.xcodeproj/project.pbxproj
  apps/native/app/ios/Podfile.lock
  apps/native/app/package.json
  apps/native/app/src/assets/illustrations/digital-services-m1-dots.png
  apps/native/app/src/assets/illustrations/digital-services-m1-dots@2x.png
  apps/native/app/src/assets/illustrations/digital-services-m1-dots@3x.png
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/passkey/passkey.tsx
  apps/native/app/src/screens/update-app/update-app.tsx
  apps/native/app/src/stores/preferences-store.ts
  apps/native/app/src/ui/lib/navigation-bar-sheet/navigation-bar-sheet.tsx
  apps/native/app/src/utils/component-registry.ts
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-routes.ts
  apps/native/app/src/utils/minimum-app-version.ts
  apps/native/app/src/utils/user-agent.ts
  yarn.lock
Labels: automerge

#16239 fix(citizenship): adding validation to file uploads
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/OtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/error.ts
Labels: automerge

#16236 feat(contentful-apps): Miðeind translation sidebar - confirmation modal
  apps/contentful-apps/components/MideindTranslationSidebar/MideindTranslationSidebar.tsx
Labels: automerge

#16181 feat(new-primary-school): Uncheck disabled language checkbox
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/languageSubSection.ts
Labels: automerge, autoupdate

#16245 docs(infra): Create documentation, focusing on developers' usage
  infra/README.md
  infra/src/cli/cli.ts
Labels: automerge

#16235 feat(j-s): Store Subpoena PDF and HASH
  apps/judicial-system/backend/migrations/20241002084126-update-subpoena.js
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/guards/subpoenaExists.guard.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/subpoena.model.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
Labels: automerge

#16233 fix(skilavottord): PlateCount is not always provided
  apps/skilavottord/web/components/CarDetailsBox2/CarDetailsBox2.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
Labels: automerge

#16232 feat(signature-collection): Signature lookup for admin
  libs/api/domains/signature-collection/src/lib/dto/signatureLookup.input.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
Labels: automerge

#16251 fix(citizenship): wrong path error fix
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
Labels: automerge

#16223 fix(services-endorsement-system): Disable caching
  libs/api/domains/endorsement-system/src/lib/dto/paginatedEndorsement.response.ts
  libs/api/domains/endorsement-system/src/lib/dto/paginatedEndorsementList.response.ts
  libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsement.model.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsementList.model.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsementListOpen.model.ts
Labels: automerge

#16253 fix(assets): bulk mileage fixes
  libs/api/domains/vehicles/src/lib/resolvers/mileage.resolver.ts
  libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
  libs/clients/vehicles-mileage/src/clientConfig.json
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
  libs/service-portal/core/src/components/NestedTable/NestedFullTable.tsx
Labels: automerge, deploy-feature

#16237 fix(portals-admin): signature collections pdf summary
  libs/portals/admin/petition/src/components/ExportList/index.tsx
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/removeCandidate.graphql
  libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/removeList.graphql
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/areaSummary.graphql
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/logo.png
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/index.tsx
Labels: automerge

#16250 feat(signature-collection): Admin lock signature list endpoint
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
Labels: automerge

#16254 fix(citizenship): longer timeout
  libs/clients/directorate-of-immigration/src/lib/apiConfiguration.ts
Labels: automerge

#16228 fix(j-s): Fix persistent error message
  apps/judicial-system/web/src/components/Inputs/InputNationalId.tsx
Labels: automerge

#16258 chore(ci): Update configure-aws-credentials version to `v4`
  .github/workflows/config-values.yaml
  .github/workflows/push.yml
Labels: automerge

#16262 fix(citizenship): upload files required and timeout release
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/OtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/error.ts
  libs/clients/directorate-of-immigration/src/lib/apiConfiguration.ts
Labels: automerge

#16194 chore(driving-license): add delivery price if pickup = post selected
  libs/application/templates/driving-license/src/fields/HealthDeclaration.tsx
  libs/application/templates/driving-license/src/forms/draft/subSectionDelivery.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
Labels: automerge

#16211 fix(portals-admin): signees filters
  libs/portals/admin/signature-collection/assets/electionsCommittee.svg
  libs/portals/admin/signature-collection/assets/nationalRegistry.svg
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/module.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/List/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/index.tsx
  libs/portals/admin/signature-collection/src/screens-presidential/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens-presidential/List/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/completeReview/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/extendDeadline/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/listInfoAlert/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/signees/filterSignees/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/signees/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/signees/sortSignees/index.tsx
Labels: automerge

#16261 fix(service-portal): subpoena fixes
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/confirmActions.input.ts
  libs/api/domains/documents/src/lib/models/v2/confirmActions.model.ts
  libs/service-portal/core/src/components/ConfirmationModal/ConfirmationModal.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV3.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.graphql
Labels: automerge

#16260 chore(signature-collection): Swap out old endpoints for new ones
  libs/clients/signature-collection/src/clientConfig.json
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.spec.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge

#16209 feat(j-s): Update subpoena dto and send multiple files
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/dto/subpoena.dto.ts
Labels: automerge

#16268 fix(portals-admin): signature collection overview search
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens-parliamentary/findSignature.graphql
  libs/portals/admin/signature-collection/src/screens-parliamentary/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/compareLists/skeleton.tsx
Labels: automerge

#16273 fix(island-ui): Update url for pdf worker
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
Labels: automerge

#16266 chore(web): Add pdf worker file to web assets
  .prettierignore
  apps/web/public/assets/pdf.worker.min.mjs
Labels: automerge

#16271 fix(citizenship): fixing file upload
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
Labels: automerge

#16275 fix(service-portal): fix defender info and alert
  libs/api/domains/law-and-order/src/lib/law-and-order.service.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV3.tsx
  libs/service-portal/law-and-order/src/screens/Subpoena/Subpoena.tsx
Labels: automerge

#16277 chore(web): Add pdf worker file to web assets - hotfix
  .prettierignore
  apps/web/public/assets/pdf.worker.min.mjs
Labels: automerge

#16241 chore(scripts): Formatting
  apps/financial-aid/api/scripts/run-xroad-proxy.sh
  apps/services/search-indexer/bin/generate-es-config.sh
  infra/scripts/build-docker-container.sh
  infra/scripts/ci/diff-chart-values-all-charts.sh
  infra/scripts/ci/diff-chart-values.sh
  infra/scripts/ci/git-check-dirty.sh
  infra/scripts/ci/test-unit.sh
  infra/scripts/container-scripts/destroy-dbs.sh
  infra/scripts/format-yaml.sh
  infra/scripts/helm-diff.sh
  scripts/ci/00_prepare-base-tags.sh
  scripts/ci/10_prepare-docker-deps.sh
  scripts/ci/10_prepare-host-deps.sh
  scripts/ci/20_check-formatting.sh
  scripts/ci/30_test.sh
  scripts/ci/50_upload-coverage.sh
  scripts/ci/90_docker-express.sh
  scripts/ci/90_docker-jest.sh
  scripts/ci/90_docker-next.sh
  scripts/ci/90_docker-playwright.sh
  scripts/ci/90_docker-static.sh
  scripts/ci/_common.sh
  scripts/ci/_nx-affected-targets.sh
  scripts/ci/cache/generate-files.sh
  scripts/ci/ci.sh
  scripts/ci/docker-login-ecr.sh
  scripts/ci/generate-build-chunks.sh
  scripts/ci/generate-chunks.sh
  scripts/ci/list-unaffected.sh
  scripts/ci/retag-unaffected.sh
  scripts/ci/run-affected-in-parallel.sh
  scripts/ci/run-in-parallel-native.sh
  scripts/ci/run-in-parallel.sh
  scripts/create-secret.sh
  scripts/dockerfile-assets/bash/extract-environment.sh
  scripts/stop-test-proxies.sh
Labels: automerge, deploy-feature, test everything

#16276 fix(web): Syslumenn remove link to fasteignaskra
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
Labels: automerge

#16272 feat(passport-application): Þjóðskrá as fixed deliveryaddress
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
  libs/application/templates/passport/src/forms/Draft.ts
  libs/application/templates/passport/src/forms/overviewSection/childsOverview.ts
  libs/application/templates/passport/src/forms/overviewSection/personalOverview.ts
  libs/application/templates/passport/src/lib/dataSchema.ts
  libs/application/templates/passport/src/lib/messages.ts
Labels: automerge

#16280 fix(island-ui): pdf viewer worker url
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
Labels: automerge

#16240 feat(web): Add campaign monitor email signup service
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/Organization/Slice/EmailSignup/EmailSignup.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/email-signup/src/index.ts
  libs/api/domains/email-signup/src/lib/emailSignup.config.ts
  libs/api/domains/email-signup/src/lib/emailSignup.module.ts
  libs/api/domains/email-signup/src/lib/emailSignup.resolver.spec.ts
  libs/api/domains/email-signup/src/lib/emailSignup.service.ts
  libs/api/domains/email-signup/src/lib/serviceProvider.ts
  libs/api/domains/email-signup/src/lib/services/campaignMonitor/campaignMonitor.config.ts
  libs/api/domains/email-signup/src/lib/services/campaignMonitor/campaignMonitor.service.ts
  libs/api/domains/email-signup/src/lib/services/zenter/zenter.service.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/emailSignup.model.ts
Labels: automerge

#16274 fix(island-ui): Update url for pdf worker - hotfix
  libs/island-ui/core/src/lib/PdfViewer/PdfViewer.tsx
Labels: automerge

#16171 fix(j-s): Civil claimant view for courts
  apps/judicial-system/backend/src/app/modules/defendant/civilClaimant.controller.ts
  apps/judicial-system/web/pages/domur/akaera/malflytjendur/[id].ts
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectCivilClaimantAdvocate.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectDefender.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Defender/Defender.strings.ts
Labels: automerge

#16096 feat(new-primary-school): Data implementation and remove not used pages
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/api/domains/education/src/lib/graphql/frigg.resolver.ts
  libs/api/domains/education/src/lib/graphql/frigg/organization.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
  libs/application/templates/new-primary-school/src/assets/Logo.tsx
  libs/application/templates/new-primary-school/src/dataProviders/index.ts
  libs/application/templates/new-primary-school/src/fields/FriggOptionsAsyncSelectField/index.tsx
  libs/application/templates/new-primary-school/src/fields/RelativesTableRepeater/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/AllergiesAndIntolerances.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Child.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Photography.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/ReasonForApplication.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Relatives.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/School.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Support.tsx
  libs/application/templates/new-primary-school/src/fields/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/childInfoSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/childrenSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/parentsSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/relativesSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/allergiesAndIntolerancesSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/useOfFootageSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/overviewSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/newSchoolSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/childrenSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/externalDataSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/index.ts
  libs/application/templates/new-primary-school/src/graphql/queries.ts
  libs/application/templates/new-primary-school/src/hooks/useFriggOptions.ts
  libs/application/templates/new-primary-school/src/index.ts
  libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
  libs/application/templates/new-primary-school/src/lib/constants.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.spec.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
  libs/application/templates/new-primary-school/src/types.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/ActionCardListFormField/ActionCardListFormField.tsx
  libs/clients/mms/frigg/README.md
  libs/clients/mms/frigg/project.json
  libs/clients/mms/frigg/src/clientConfig.json
  libs/clients/mms/frigg/src/lib/apiProvider.ts
  libs/clients/mms/frigg/src/lib/friggClient.config.ts
  libs/clients/mms/frigg/src/lib/friggClient.service.ts
Labels: automerge

#16177 feat(j-s): Display service status
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/defendant/index.ts
  apps/judicial-system/api/src/app/modules/defendant/models/subpoena.model.ts
  apps/judicial-system/api/src/app/modules/police/dto/subpoenaStatus.input.ts
  apps/judicial-system/api/src/app/modules/police/index.ts
  apps/judicial-system/api/src/app/modules/police/models/subpoenaStatus.model.ts
  apps/judicial-system/api/src/app/modules/police/police.resolver.ts
  apps/judicial-system/backend/migrations/20240925130059-update-subpoena.js
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getIndictmentPdfGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/police/police.controller.ts
  apps/judicial-system/backend/src/app/modules/police/police.module.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/createTestingPoliceModule.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/updateSubpoena.dto.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/subpoena.model.ts
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncement.strings.ts
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncement.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useSubpoena/getSubpoenaStatus.graphql
  apps/judicial-system/web/src/utils/hooks/useSubpoena/index.ts
  apps/judicial-system/xrd-api/src/app/app.service.ts
  apps/judicial-system/xrd-api/src/app/dto/subpoena.dto.ts
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/defendant.ts
Labels: automerge

#16282 fix(search-indexer): Reduce "missing parameter: index" error logs
  libs/content-search-indexer/src/lib/indexing.service.ts
Labels: automerge

#16224 feat(service-portal-health): Add extra doctor info to med cert
  libs/service-portal/health/src/components/ExtraDoctors/index.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
Labels: automerge

#16279 fix(portals-admin): locklist
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/completeReview/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/completeReview/lockList/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/completeReview/lockList/lockList.graphql
Labels: automerge

#16285 feat(service-portal): feature flag resolver for documents
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/api/domains/documents/src/lib/document.module.ts
  libs/api/domains/documents/src/lib/documentV2.resolver.ts
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/documentContent.model.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV3.tsx
  libs/service-portal/documents/src/components/OverviewDisplay/DesktopOverviewV3.tsx
  libs/service-portal/documents/src/hooks/useDocumentListV3.ts
  libs/service-portal/documents/src/screens/Overview/OverviewV3.tsx
Labels: automerge

#16295 fix(vehicles-bulk-mileage): Fixes after testing review
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.tsx
  libs/service-portal/core/src/components/TableGrid/TableGrid.tsx
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#16287 feat(tests): New @island/testing/e2e library
  libs/testing/e2e/.eslintrc.json
  libs/testing/e2e/README.md
  libs/testing/e2e/jest.config.ts
  libs/testing/e2e/project.json
  libs/testing/e2e/src/index.ts
  libs/testing/e2e/src/lib/libs/testing/e2e.spec.ts
  libs/testing/e2e/src/lib/libs/testing/e2e.ts
  libs/testing/e2e/tsconfig.json
  libs/testing/e2e/tsconfig.lib.json
  libs/testing/e2e/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#15901 feat(parental-leave): ApplicationRights
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/constants.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/lib/directorateOfLabour.utils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
  libs/clients/vmst/src/clientConfig.yaml
  libs/clients/vmst/src/lib/utils.ts
Labels: automerge

#16296 feat(passport-application): Updated readme
  libs/application/templates/passport/README.md
Labels: automerge

#16293 fix(regulations-admin): No diff no addition in appendix
  libs/portals/admin/regulations-admin/src/components/impacts/EditChange.tsx
Labels: automerge

#16298 fix(web): Global alert banner - Handle null case
  apps/web/layouts/main.tsx
Labels: automerge

#16299 fix(web): Change custom syslumenn pages config for header
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
  apps/web/screens/Organization/Syslumenn/Homestay.tsx
  apps/web/screens/Organization/Syslumenn/OperatingLicenses.tsx
Labels: automerge

#16301 fix(j-s): Digital mailbox API
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/case.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalCase.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/defendant.ts
Labels: automerge

#16300 fix(signature-collection): Fix list reviewed toggle
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
Labels: automerge

#16242 chore(scripts): Stricter shell script checking
  .github/workflows/pullrequest.yml
  infra/scripts/helm-diff.sh
  scripts/ci/00_prepare-base-tags.sh
  scripts/ci/50_upload-coverage.sh
  scripts/ci/_docker.sh
  scripts/ci/_podman.sh
  scripts/ci/generate-build-chunks.sh
  scripts/ci/list-unaffected.sh
  scripts/local-e2e.sh
  scripts/stop-test-proxies.sh
Labels: automerge

#16302 chore(new-primary-school): Update messages namespace
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#16292 feat(driving-license): check if 65+ renewal is possible
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/v5/clientConfig.json
Labels: automerge

#16306 feat(service-portal): default defender and has chosen fields for subpoena
  libs/api/domains/law-and-order/src/lib/helpers/mappers.ts
  libs/api/domains/law-and-order/src/lib/law-and-order.service.ts
  libs/api/domains/law-and-order/src/models/subpoena.model.ts
  libs/clients/judicial-system-sp/src/clientConfig.json
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/law-and-order/src/components/DefenderChoices/DefenderChoices.tsx
  libs/service-portal/law-and-order/src/screens/Subpoena/Subpoena.graphql
  libs/service-portal/law-and-order/src/screens/Subpoena/Subpoena.tsx
Labels: automerge

#16307 feat(driving-license): check if 65+ renewal is possible (#16292)
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/extractReasons.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/v5/clientConfig.json
Labels: automerge

#16257 feat(auth-admin): Webhook for general mandate delegation
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.controller.ts
  apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.auth.spec.ts
  apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.spec.ts
  apps/services/auth/admin-api/src/environments/environment.ts
  apps/services/auth/admin-api/src/main.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/constants/zendesk.ts
  libs/auth-api-lib/src/lib/delegations/dto/zendesk-webhook-input.dto.ts
  libs/auth-nest-tools/src/index.ts
  libs/auth-nest-tools/src/lib/rawBodyRequest.type.ts
  libs/auth-nest-tools/src/lib/zendeskAuth.guard.ts
  libs/infra-nest-server/src/index.ts
  libs/infra-nest-server/src/lib/bootstrap.ts
  libs/infra-nest-server/src/lib/includeRawBodyMiddleware.ts
  libs/infra-nest-server/src/lib/types.ts
  libs/portals/admin/delegation-admin/src/constants/errors.ts
  libs/portals/admin/delegation-admin/src/lib/messages.ts
  libs/shared/utils/src/lib/errorCodes.ts
  libs/testing/nest/src/lib/setup.ts
  libs/testing/nest/src/lib/testServer.ts
Labels: automerge

#16309 feat: Send codemagic build errors to slack, bump app version
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
  codemagic.yaml
Labels: automerge

#16297 feat(j-s): Block create subpoena on staging and production
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/modules/police/police.config.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#16308 fix: pre-release
  .github/workflows/push.yml
Labels: automerge

#16315 fix(service-portal): remove asFrame check from document line
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV3.tsx
Labels: automerge

#16238 fix(native-app): support dynamic formats of hello image graphic
  apps/native/app/src/screens/home/hello-module.tsx
Labels: automerge

#16184 feat(endorsement-system): Export pdf template look
  apps/services/endorsements/api/README.md
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/services/endorsements/api/src/assets/ibm-plex-sans-v7-latin-600.ttf
  apps/services/endorsements/api/src/assets/ibm-plex-sans-v7-latin-regular.ttf
  apps/services/endorsements/api/src/assets/island.png
  apps/services/endorsements/api/src/assets/thjodskra.png
Labels: automerge

#16325 fix(regulations-admin): Effective publish date warning addition
  libs/portals/admin/regulations-admin/src/components/EditMeta.tsx
  libs/portals/admin/regulations-admin/src/components/impacts/EditChange.tsx
  libs/portals/admin/regulations-admin/src/lib/messages.ts
  libs/portals/admin/regulations-admin/src/utils/index.ts
Labels: automerge

#16331 fix(admin-statistics): Stop old templateIds causing failures
  apps/application-system/api/src/app/modules/application/tools/applicationAdmin.serializer.ts
Labels: automerge

#15420 feat(accident-notification): connect new api for accident-notification
  apps/application-system/api/src/app/app.module.ts
  libs/api/domains/application/src/lib/application.service.ts
  libs/api/domains/health-insurance/src/lib/accident-notification.service.ts
  libs/api/domains/health-insurance/src/lib/graphql/accident-notification.resolver.ts
  libs/api/domains/health-insurance/src/lib/healthInsurance.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification-v2.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/attachments/attachment.utils.ts
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/applicationStatusUtils.ts
  libs/application/templates/accident-notification/src/fields/ApplicationStatus/index.tsx
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/InReviewForm/index.ts
  libs/application/templates/accident-notification/src/index.ts
  libs/application/templates/accident-notification/src/lib/AccidentNotificationTemplate.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/types/index.ts
  libs/application/ui-shell/src/lib/FormShell.tsx
  libs/clients/icelandic-health-insurance/rights-portal/src/clientConfig.json
  libs/clients/icelandic-health-insurance/rights-portal/src/index.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/lib/providers.ts
Labels: automerge, deploy-feature

#16334 fix(marriage-conditions): mock payment
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
Labels: automerge

#16336 fix(endorsement-system): Revert Endorsement count column index logi…
  apps/services/endorsements/api/migrations/20240904000001-endorsement-count.js
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementList.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
Labels: automerge, high priority

#16341 fix(endorsement-system): Revert Endorsement count column index logi… …
  apps/services/endorsements/api/migrations/20240904000001-endorsement-count.js
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementList.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
Labels: automerge, high priority

#16328 feat(register-new-machine): translation
  libs/api/domains/work-machines/src/lib/models/category.ts
  libs/api/domains/work-machines/src/lib/models/subCategory.ts
  libs/api/domains/work-machines/src/lib/models/techInfoItem.ts
  libs/api/domains/work-machines/src/lib/workMachines.resolver.ts
  libs/api/domains/work-machines/src/lib/workMachines.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/aosh/register-new-machine/register-new-machine.service.ts
  libs/application/templates/aosh/register-new-machine/src/fields/AboutMachine/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/MachineType/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/Overview/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/ListItemField.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/formFieldMapper.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/index.tsx
  libs/application/templates/aosh/register-new-machine/src/graphql/queries.ts
  libs/application/templates/aosh/register-new-machine/src/hooks/useLazyMachineCategory.ts
  libs/application/templates/aosh/register-new-machine/src/lib/dataSchema.ts
  libs/application/templates/aosh/register-new-machine/src/shared/types.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getAboutMachineAnswers.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getBasicMachineInformation.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getTechnicalInformation.ts
  libs/application/templates/aosh/register-new-machine/src/utils/index.ts
  libs/clients/work-machines/src/clientConfig.json
  libs/clients/work-machines/src/lib/workMachines.service.ts
Labels: automerge

#16332 fix(j-s): Default service status fix
  apps/judicial-system/api/src/app/modules/police/models/subpoenaStatus.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/updateSubpoena.dto.ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/domkrofur-og-lagagrundvollur/[id].ts
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncement.strings.ts
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncement.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#16347 fix:(auth-admin): Adds nationalId to IdentityCard for createdBy in DelegationViewModal
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx
Labels: automerge

#16342 feat(register-new-machine): hotfix translating
  libs/api/domains/work-machines/src/lib/models/category.ts
  libs/api/domains/work-machines/src/lib/models/subCategory.ts
  libs/api/domains/work-machines/src/lib/models/techInfoItem.ts
  libs/api/domains/work-machines/src/lib/workMachines.resolver.ts
  libs/api/domains/work-machines/src/lib/workMachines.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/aosh/register-new-machine/register-new-machine.service.ts
  libs/application/templates/aosh/register-new-machine/src/fields/AboutMachine/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/MachineType/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/Overview/index.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/ListItemField.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/formFieldMapper.tsx
  libs/application/templates/aosh/register-new-machine/src/fields/TechnicalInfo/index.tsx
  libs/application/templates/aosh/register-new-machine/src/graphql/queries.ts
  libs/application/templates/aosh/register-new-machine/src/hooks/useLazyMachineCategory.ts
  libs/application/templates/aosh/register-new-machine/src/lib/dataSchema.ts
  libs/application/templates/aosh/register-new-machine/src/shared/types.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getAboutMachineAnswers.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getBasicMachineInformation.ts
  libs/application/templates/aosh/register-new-machine/src/utils/getTechnicalInformation.ts
  libs/application/templates/aosh/register-new-machine/src/utils/index.ts
  libs/clients/work-machines/src/clientConfig.json
  libs/clients/work-machines/src/lib/workMachines.service.ts
Labels: automerge

#16349 fix(fsc-application): fix typo in translation key
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#16340 fix(marriage-conditions): touchups
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/index.tsx
  libs/application/templates/marriage-conditions/src/fields/InfoAlert/index.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/marriage-conditions/src/fields/index.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
Labels: automerge

#16345 fix(application-system): Screen validation bug
  libs/application/core/src/validation/validators.spec.ts
  libs/application/core/src/validation/validators.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
  libs/application/ui-shell/src/validation/resolver.ts
Labels: automerge, deploy-feature

#16350 fix(driving-license): mock payment
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
Labels: automerge

#16355 fix(web): Load image with 800px width when embedded in rich text
  apps/web/utils/richText.tsx
Labels: automerge

#16316 chore(j-s): Robot emails
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
Labels: automerge

#16286 fix(j-s): Indictment Cleanup
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
Labels: automerge

#16312 fix(j-s): Show verdict appeal date for defenders
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
Labels: automerge

#16311 fix(j-s): Move subpoena pdf above added documents
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
Labels: automerge

#16356 fix(regulations-admin): Actor to draft
  apps/services/regulations-admin-backend/src/app/modules/draft_regulation/draft_regulation.service.ts
  libs/portals/admin/regulations-admin/src/components/SaveDeleteButtons.tsx
Labels: automerge

#16360 fix(web): Use || instead of ?? for JSON.parse fallback
  apps/web/components/Organization/OrganizationIslandFooter/OrganizationIslandFooter.tsx
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/FiskistofaHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/FjarsyslaRikisinsTheme/FjarsyslaRikisinsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/GevTheme/GevHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunAusturlandsTheme/HeilbrigdisstofnunAusturlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunNordurlandsTheme/HeilbrigdisstofnunNordurlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HeilbrigdisstofnunSudurlandsTheme/HeilbrigdisstofnunSudurlandsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HmsTheme/HmsHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/HveTheme/HveHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicNaturalDisasterInsuranceTheme/IcelandicNaturalDisasterInsuranceHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/IcelandicRadiationSafetyAuthority/IcelandicRadiationSafetyAuthorityHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/LandkjorstjornTheme/LandskjorstjornHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/LandlaeknirTheme/LandlaeknirHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RikislogmadurTheme/RikislogmadurHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/RikissaksoknariTheme/RikissaksoknariHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SAkTheme/SAkHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SHHTheme/ShhHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/TransportAuthorityTheme/TransportAuthorityHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/UtlendingastofnunTheme/UtlendingastofnunHeader.tsx
  apps/web/components/Organization/Wrapper/Themes/VinnueftirlitidTheme/VinnueftirlitidHeader.tsx
  apps/web/components/Project/Header/DirectorateOfHealthDashboardHeader.tsx
  apps/web/components/Project/Header/FiskistofaDashboardHeader.tsx
  apps/web/components/SignLanguageButton/SignLanguageButton.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/Category/Categories/Categories.tsx
  apps/web/screens/Home/Home.tsx
  apps/web/screens/Organization/PublishedMaterial/PublishedMaterial.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
Labels: automerge

#16358 fix(shared-utils): Fix addressing in getConfigValue
  libs/application/template-api-modules/src/lib/modules/shared/shared.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.spec.ts
Labels: automerge

#16353 feat(j-s): Send correct indictment pdf with subpoena
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.module.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/createTestingSubpoenaModule.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/internalSubpoenaController/deliverSubpoenaToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/limitedAccessSubpoenaController/getSubpoenaPdf.spec.ts
Labels: automerge

#16368 fix(register-new-machine): setvalue
  libs/application/templates/aosh/register-new-machine/src/fields/MachineType/index.tsx
Labels: automerge

#16264 chore(j-s): Notifications to advocates in civil claims cases
  apps/judicial-system/backend/migrations/20241003213354-update-notification.js
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAdvocateAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAdvocateAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendCourtDateNotification.spec.ts
  apps/judicial-system/web/src/components/Inputs/InputAdvocate.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectCivilClaimantAdvocate.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/advocate.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#16213 feat(native-app): Subpoena functionality in inbox in app
  apps/native/app/src/assets/icons/download.png
  apps/native/app/src/assets/icons/download@2x.png
  apps/native/app/src/assets/icons/download@3x.png
  apps/native/app/src/assets/icons/external-open.png
  apps/native/app/src/assets/icons/external-open@2x.png
  apps/native/app/src/assets/icons/external-open@3x.png
  apps/native/app/src/graphql/fragments/document.fragment.graphql
  apps/native/app/src/graphql/queries/inbox.graphql
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/document-detail/utils/get-buttons-for-actions.tsx
  apps/native/app/src/screens/document-detail/utils/share-file.tsx
  apps/native/app/src/screens/finance/finance.tsx
  apps/native/app/src/screens/home/inbox-module.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/ui/assets/alert/danger.png
  apps/native/app/src/ui/assets/alert/danger@2x.png
  apps/native/app/src/ui/assets/alert/danger@3x.png
  apps/native/app/src/ui/assets/card/danger.png
  apps/native/app/src/ui/assets/card/danger@2x.png
  apps/native/app/src/ui/assets/card/danger@3x.png
  apps/native/app/src/ui/lib/alert/alert.tsx
  apps/native/app/src/ui/lib/card/inbox-card.tsx
  apps/native/app/src/ui/lib/detail/header.tsx
  apps/native/app/src/ui/lib/label/label.tsx
  apps/native/app/src/ui/lib/link/link.tsx
  apps/native/app/src/ui/lib/list/list-item.tsx
Labels: automerge

#16354 chore(native-app): bump version to 1.4.5
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#16371 feat(web): Allow article to appear multiple times on Category page
  apps/web/screens/Category/Category/utils.ts
Labels: automerge

#16363 chore(change-vehicle-operator): removed vehicle description field
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/information.ts
Labels: automerge

#16333 feat(native-app): add health overview
  apps/native/app/src/assets/icons/health.png
  apps/native/app/src/assets/icons/health@2x.png
  apps/native/app/src/assets/icons/health@3x.png
  apps/native/app/src/config.ts
  apps/native/app/src/graphql/queries/health.graphql
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/health/health-overview.tsx
  apps/native/app/src/screens/home/home-options.tsx
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/screens/wallet-passport/wallet-passport.tsx
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/ui/index.ts
  apps/native/app/src/ui/lib/alert/alert.tsx
  apps/native/app/src/ui/lib/button/button.tsx
  apps/native/app/src/ui/lib/card/more-card.tsx
  apps/native/app/src/ui/lib/heading/heading.tsx
  apps/native/app/src/ui/lib/input/input-row.tsx
  apps/native/app/src/ui/lib/input/input.tsx
  apps/native/app/src/utils/component-registry.ts
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-routes.ts
Labels: automerge

#16373 feat(web): Pension calculator - "Breyta forsendum" button visual changes
  apps/web/components/LanguageToggler/LanguageToggler.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
Labels: automerge

#16381 fix(native-app): fix import
  apps/native/app/src/screens/health/health-overview.tsx
Labels: automerge

#16372 feat(application-system): Remove phone input feature flag
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/estate/src/forms/Sections/announcerInfo.ts
  libs/application/templates/estate/src/forms/Sections/representative.ts
  libs/application/templates/inheritance-report/src/forms/sections/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/applicant.ts
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/inheritanceExecutor.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/presidential-list-creation/src/forms/Draft.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
Labels: automerge

#16382 fix(service-portal): company route signature collections
  apps/portals/my-pages/src/lib/masterNavigation.ts
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/signature-collection/src/index.ts
  libs/service-portal/signature-collection/src/lib/navigation.ts
  libs/service-portal/signature-collection/src/lib/paths.ts
  libs/service-portal/signature-collection/src/module.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
Labels: automerge

#16379 feat(health-insurance): zod for health insurance
  libs/application/templates/health-insurance/project.json
  libs/application/templates/health-insurance/src/assets/Logo.tsx
  libs/application/templates/health-insurance/src/assets/ManOnBenchIllustration.tsx
  libs/application/templates/health-insurance/src/fields/AgentComment/AgentComment.tsx
  libs/application/templates/health-insurance/src/fields/ChildrenInfoMessage/ChildrenInfoMessage.css.ts
  libs/application/templates/health-insurance/src/fields/ChildrenInfoMessage/ChildrenInfoMessage.tsx
  libs/application/templates/health-insurance/src/fields/CitizenshipField/CitizenshipField.tsx
  libs/application/templates/health-insurance/src/fields/ConfirmCheckbox/ConfirmCheckbox.tsx
  libs/application/templates/health-insurance/src/fields/HiddenDateField/HiddenDateField.tsx
  libs/application/templates/health-insurance/src/fields/MissingInfoRemarks/MissingInfoRemarks.tsx
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/PrerequisiteSummary.tsx
  libs/application/templates/health-insurance/src/fields/PrerequisiteSummary/SummaryItem.tsx
  libs/application/templates/health-insurance/src/fields/Review/ContactInfo.tsx
  libs/application/templates/health-insurance/src/fields/Review/FormerInsurance.tsx
  libs/application/templates/health-insurance/src/fields/Review/ReviewAdditionalInfo.tsx
  libs/application/templates/health-insurance/src/fields/Review/ReviewMissingInfo.tsx
  libs/application/templates/health-insurance/src/fields/Review/StatusAndChildren.tsx
  libs/application/templates/health-insurance/src/fields/Review/index.tsx
  libs/application/templates/health-insurance/src/fields/TextWithTooltip/TextWithTooltip.tsx
  libs/application/templates/health-insurance/src/fields/index.ts
  libs/application/templates/health-insurance/src/forms/ConfirmationScreen.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/aplicantInformationSection.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/confirmSection.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/formerInsuranceSection.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/index.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/statusAndChildrenSection.ts
  libs/application/templates/health-insurance/src/forms/MissingInfoForm.ts
  libs/application/templates/health-insurance/src/forms/PrerequisitesForm.ts
  libs/application/templates/health-insurance/src/forms/ReviewApplication.ts
  libs/application/templates/health-insurance/src/healthInsuranceUtils.ts
  libs/application/templates/health-insurance/src/index.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.spec.ts
  libs/application/templates/health-insurance/src/lib/HealthInsuranceTemplate.ts
  libs/application/templates/health-insurance/src/lib/answerValidators.spec.ts
  libs/application/templates/health-insurance/src/lib/answerValidators.ts
  libs/application/templates/health-insurance/src/lib/dataSchema.ts
  libs/application/templates/health-insurance/src/lib/messages/countries.ts
  libs/application/templates/health-insurance/src/lib/messages/messages.ts
  libs/application/templates/health-insurance/src/shared/index.ts
  libs/application/templates/health-insurance/src/utils/EFTA.ts
  libs/application/templates/health-insurance/src/utils/EU.ts
  libs/application/templates/health-insurance/src/utils/constants.ts
  libs/application/templates/health-insurance/src/utils/countries.ts
  libs/application/templates/health-insurance/src/utils/getFormerCountryAndCitizenship.ts
  libs/application/templates/health-insurance/src/utils/options.ts
  libs/application/templates/health-insurance/src/utils/types.ts
Labels: automerge

#16383 fix(service-portal): sp list submitted
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/shared-components/completeReview/lockList/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
Labels: automerge

#16384 fix(portals-admin): adding report date
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/index.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/navigation.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
Labels: automerge

#16335 feat(auth-admin): Delegation-admin webhook auditlog
  apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.controller.ts
  apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.auth.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/delegation-index.controller.ts
  libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#16388 fix(ojoi): Bug fixes and add adverts to web project.
  apps/web/components/OfficialJournalOfIceland/OJOIAdvertCard.tsx
  apps/web/components/OfficialJournalOfIceland/OJOIAdvertCards.tsx
  apps/web/components/OfficialJournalOfIceland/OJOISearchListView.tsx
  apps/web/components/OfficialJournalOfIceland/index.ts
  apps/web/screens/OfficialJournalOfIceland/OJOIHome.tsx
  apps/web/screens/OfficialJournalOfIceland/messages.ts
  libs/application/templates/official-journal-of-iceland/src/components/signatures/Chairman.tsx
  libs/application/templates/official-journal-of-iceland/src/components/signatures/RegularMember.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/attachments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/publishing.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
Labels: automerge

#16321 feat(service-portal): detailed audit logs for law and order
  libs/api/domains/law-and-order/src/lib/law-and-order.resolver.ts
Labels: automerge

#16398 fix(service-portal): Change download for pdf docs inbox
  apps/download-service/src/app/modules/documents/document.controller.ts
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBarV2.tsx
  libs/service-portal/documents/src/utils/downloadDocumentV2.ts
Labels: automerge

#16357 feat(native-app): add useLocale hook
  apps/native/app/src/hooks/use-locale.ts
  apps/native/app/src/screens/applications/applications-completed.tsx
  apps/native/app/src/screens/applications/applications-in-progress.tsx
  apps/native/app/src/screens/applications/applications-incomplete.tsx
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/document-detail/document-detail.tsx
Labels: automerge

#16394 fix(id-card): email for parent B fix
  libs/application/template-api-modules/src/lib/modules/templates/id-card/emailGenerators/assignParentBEmail.ts
  libs/application/templates/id-card/src/forms/Rejected.ts
Labels: automerge

#16344 chore(config): Add shellcheck config file
  .shellcheckrc
Labels: automerge

#16407 fix(signature-collection): Tweaks for parliamentary collection
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
Labels: automerge

#16400 fix(service-portal): Delete and view delegation in service portal form me list
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
Labels: automerge

#16348 feat(web): Generic list - External url field
  apps/web/components/GenericList/GenericList.tsx
  apps/web/screens/queries/GenericList.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/genericListItem.model.ts
Labels: automerge

#16410 feat(search-indexer): Move mapping logic to separate class
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/cms/src/lib/search/mapping.service.ts
Labels: automerge

#16411 fix(signature-collection): Fix paper signatures for candidacy
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-shared.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
Labels: automerge

#16399 chore(infra): Fix run-local-env services argument
  infra/src/cli/cli.ts
Labels: automerge

#16305 chore(j-s): Fixes to ServiceRequirement NOT_REQUIRED
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/subpoena/limitedAccessSubpoena.controller.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.css.ts
  apps/judicial-system/web/src/components/SectionHeading/SectionHeading.tsx
Labels: automerge

#16412 feat(contentful-apps): Allow two project subpages to have same slug
  apps/contentful-apps/pages/fields/project-subpage-slug-field.tsx
Labels: automerge

#16404 chore(personal-representative): Remove `demo-alb` ingress
  apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
  apps/services/auth/personal-representative/infra/personal-representative.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#16409 fix(signature-collections): ongoing updates
  libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
Labels: automerge

#16416 feat(contentful-apps): Hotfix - Allow two project subpages to have same slug (#16412)
  apps/contentful-apps/pages/fields/project-subpage-slug-field.tsx
Labels: automerge

#16393 feat(j-s): Separate requested defender info from actual assigned defender
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20241011090000-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/updateSubpoena.dto.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalCase.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalDefendant.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.tsx
  apps/judicial-system/xrd-api/src/app/app.service.ts
Labels: automerge

#16405 chore(infra): Types for ingress and more
  infra/src/dsl/dsl.ts
  infra/src/dsl/ingress.spec.ts
  infra/src/dsl/types/charts.ts
  infra/src/dsl/types/input-types.ts
Labels: automerge

#16414 fix(auth-admin): Hotfix: Auditlog for webhook and minor UI fixes
  apps/services/auth/admin-api/src/app/v2/delegations/delegation-admin.controller.ts
  apps/services/auth/admin-api/src/app/v2/delegations/test/delegation-admin.auth.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/delegation-index.controller.ts
  libs/auth-api-lib/src/lib/delegations/admin/delegation-admin-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationViewModal.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
Labels: automerge

#16415 fix(signature-collection): A litany of fixes
  apps/service-portal/src/lib/masterNavigation.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/clients/signature-collection/src/lib/signature-collection-shared.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens-parliamentary/DownloadReports/MyPdfDocument/index.tsx
  libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/identityAndCanSignLookup.graphql
  libs/portals/admin/signature-collection/src/screens-parliamentary/List/paperSignees/index.tsx
  libs/portals/admin/signature-collection/src/shared-components/completeReview/lockList/index.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/signature-collection/src/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/navigation.ts
  libs/service-portal/signature-collection/src/lib/paths.ts
  libs/service-portal/signature-collection/src/module.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
Labels: automerge

#16418 feat(web): Directorate of immigration chat changes
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/WatsonChatPanel/utils.ts
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge

#16417 feat(consultation-portal): RSS feed implementation for subscriptions
  apps/consultation-portal/components/svg/RSSFeedIcon.tsx
  apps/consultation-portal/components/svg/index.ts
  apps/consultation-portal/pages/api/rss.ts
  apps/consultation-portal/screens/Subscriptions/Subscriptions.json
  apps/consultation-portal/screens/Subscriptions/components/SubscriptionsSkeleton/SubscriptionsSkeleton.tsx
Labels: automerge

#16424 fix(template-plc): Slug fix
  libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx
Labels: automerge

#16374 feat(endorsement-system): Endorsement count column index rewamp
  apps/services/endorsements/api/migrations/20240904000001-endorsement-count.js
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementList.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
Labels: automerge

#16426 fix(template-plc): Slug fix (#16424)
  libs/application/templates/signature-collection/parliamentary-list-creation/src/fields/CopyLink/index.tsx
Labels: automerge

#16423 fix(signature-collections): fixes 16.10
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/skeletons.tsx
Labels: automerge

#16419 fix(citizenship): aws upload fix and select children fix
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/Prerequisites/index.ts
  libs/clients/directorate-of-immigration/src/clientConfig.json
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.service.ts
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.types.ts
Labels: automerge

#16422 fix(j-s): Filter Case Files by Police Case Number
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFile/CaseFile.tsx
Labels: automerge

#16408 fix(service-portal): Improve error handling when user tries to grant self access as actor
  libs/portals/shared-modules/delegations/src/lib/messages.ts
  libs/portals/shared-modules/delegations/src/screens/GrantAccess/GrantAccess.tsx
Labels: automerge

#16413 chore(j-s): Make a gendered version of the subpoena pdf
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfCore.ts
  apps/judicial-system/backend/src/app/messages/pdfSubpoena.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#16425 fix(signature-colletion): remove candidate if all lists removed
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/errors.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge, high priority

#16427 fix(signature-colletion): allow manager on paper upload
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
Labels: automerge, high priority

#16428 fix(signature-collection): sc fixes 16.10
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
Labels: automerge, high priority

#16430 fix(application-plc): Various fixes 16.10
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/errors.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/application/types/src/lib/Fields.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/skeletons.tsx
Labels: automerge, high priority

#16429 fix(application-plc): Detect user delegation type
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/createCollectionTemplate.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
Labels: automerge

#16431 feat(signature-collection): user not found handling
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.service.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
Labels: automerge

#16432 fix(signature-collection): refetch is owner 16.10
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
Labels: automerge

#16437 fix(signature-collection): remove tooltip
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
Labels: automerge

#16436 fix(application-plc): Fixes 16.10 batch 2
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-creation/parliamentary-list-creation.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/parliamentary-list-signing/parliamentary-list-signing.service.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/createCollectionTemplate.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SignedList/index.tsx
  libs/service-portal/signature-collection/src/screens/shared/SigneeView/index.tsx
Labels: automerge

#16439 fix(signature-collection): remove tooltip (#16437)
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/ViewList/Signees/PaperSignees.tsx
  libs/service-portal/signature-collection/src/screens/Parliamentary/OwnerView/index.tsx
Labels: automerge
