Repository island-is/island.is, pull requests merged in 2024-05, with the labels that each got.

#14662 fix(web): Disable SSR for Directorate of Fisheries footer
  apps/web/components/Organization/Wrapper/Themes/FiskistofaTheme/index.ts
Labels: automerge

#14648 chore(j-s): Get arraignmentDate for defenders
  apps/judicial-system/web/src/components/ContextMenu/ContextMenu.tsx
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/defenderCases.graphql
Labels: automerge

#14654 chore(ids-api): Minor change to have the cleanup worker deployed.
  apps/services/auth/ids-api/src/app/cleanup/cleanup-worker.ts
Labels: automerge

#14663 feat(web): Pension Calculator - Set latest calculator date as default selection
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
Labels: automerge

#14655 feat(j-s): Postponed Indefinitely Explanation
  apps/judicial-system/web/src/components/InfoCard/InfoCard.strings.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardCaseScheduled.strings.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardCaseScheduled.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardCaseScheduledIndictment.strings.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardCaseScheduledIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#14661 fix(user-notifications): Grant islandis namespace. User InfraModule health/check.
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/infra.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/tests/me-notifications.controller.spec.ts
  apps/services/user-notification/src/main.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14653 fix(j-s): Track Execution Time for Get All Police Case Files
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
Labels: automerge

#14659 feat(j-s): Redistribution front end
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
Labels: automerge

#14660 feat(web): Manual changelog - render newlines
  apps/web/screens/Manual/ManualChangelog.tsx
Labels: automerge

#14665 feat(contentful-entry-tagger): Deploy entry tagger to prod
  charts/islandis/values.prod.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#14670 chore(j-s): New user roles for public prosecutor roles
  apps/judicial-system/backend/migrations/20240501130036-update-user.js
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#14671 fix(general-petition): Email validation
  libs/application/templates/general-petition/src/lib/dataSchema.ts
Labels: automerge

#14672 feat(contentful-apps): Add timeout in fetch page above check in link group link field
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
Labels: automerge

#14667 fix(aosh): Adding the skip payment for when it applies for machines
  libs/api/domains/work-machines/src/lib/models/machineDetails.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/InformationSection/machineSubSection.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/index.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/dataSchema.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/shared/types.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/getSelectedMachine.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/index.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/utils/isPaymentRequired.ts
  libs/clients/work-machines/src/lib/workMachines.service.ts
  libs/clients/work-machines/src/lib/workMachines.types.ts
Labels: automerge

#14679 fix(general-petition): Fixing bug when email is undefined
  libs/application/templates/general-petition/src/forms/form.ts
Labels: automerge, autoupdate

#14676 fix(citizenship): updates to UTL externalData call and marriageStatus
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/types/index.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/dataProviders/index.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/ResidenceCountries/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/StaysAbroad/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/Prerequisites/index.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/CitizenshipTemplate.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/error.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/shared/constants.ts
  libs/clients/directorate-of-immigration/src/clientConfig.json
  libs/clients/directorate-of-immigration/src/lib/apiConfiguration.ts
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.service.ts
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.types.ts
Labels: automerge

#14678 feat(j-s): Court Date Notification
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseCompleted.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseNotCompleted.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseReceived.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseType.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/requestSharedWithDefender.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseOriginalAncestor.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/models/dateLog.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/explanatoryComment.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealJudgesAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
Labels: automerge

#14684 chore(j-s): Arrow functions everywhere
  apps/judicial-system/backend/src/app/formatters/caseFilesRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/rulingPdf.ts
  libs/judicial-system/message/src/lib/test/random.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#14674 fix(inheritance-report): remove uppercase style
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/fields/styles.css.ts
Labels: automerge

#14683 chore(ids-api): Fix schedule in infra.
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#14664 refactor(user-notification): Refactor user notification to use the config object in services. Set emailFromAddress in config.
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/src/config.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-notification/test/environment.ts
  apps/services/user-notification/test/globalSetup.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14680 fix(j-s): Fix side stepper in appealed cases
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#14637 fix(Inheritance-report): Property asset number validation
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
Labels: automerge

#14687 fix(regulations): Bugfixes and minor adjustments reg admin
  libs/portals/admin/regulations-admin/src/components/ConfirmModal/ConfirmModal.tsx
  libs/portals/admin/regulations-admin/src/components/EditBasics.tsx
  libs/portals/admin/regulations-admin/src/components/EditMeta.tsx
  libs/portals/admin/regulations-admin/src/components/impacts/ReferenceText.tsx
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#14690 fix(j-s): Get All Cases
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
Labels: automerge

#14668 chore(j-s): Add blueboxes around courtEndTimes
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
Labels: automerge

#14682 fix(j-s): Fix unique key error category card
  apps/judicial-system/web/src/components/Table/PastCasesTable/MobilePastCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
Labels: automerge

#14692 feat(university-gateway): Adjusting search, changing header image, adjust slices to allow one slice above the search bar
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/utils/useUniversitySearch.tsx
Labels: automerge

#14694 fix(contentful-apps): Dynamically import component instead of entire page
  apps/contentful-apps/components/lists/GenericListEditor/GenericListEditor.tsx
  apps/contentful-apps/components/lists/GenericListItemEditor/GenericListItemEditor.tsx
  apps/contentful-apps/pages/editors/generic-list-editor.ts
  apps/contentful-apps/pages/editors/generic-list-item-editor.ts
Labels: automerge

#14697 fix(general-petition): Display closed list
  apps/services/endorsements/api/src/app/modules/endorsementList/e2e/findOneEndorsementList/findOneEndorsementList.spec.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/web/screens/PetitionView/PetitionView.tsx
Labels: automerge

#14699 fix(j-s): Fix CF string
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
Labels: automerge

#14698 feat(web): Add shortTitle field to organizationSubpage and projectSubpage models
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/linkGroup.model.ts
  libs/cms/src/lib/models/organizationSubpage.model.ts
  libs/cms/src/lib/models/projectSubpage.model.ts
Labels: automerge

#14691 fix(j-s): Postponed Indictments
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/defenderCases.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
Labels: automerge

#14708 fix(university-gateway): adding condition for program updates
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
Labels: automerge

#14702 chore(auth-api): Add health insurance scope to application system client
  libs/auth-api-lib/seeders/data/add-health-insurance-scope-to-application-system-client.ts
Labels: automerge

#14693 fix(parental-leave): Fix employer doc type when multiple changes
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#14709 fix(university-gateway): adding back specilization
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
Labels: automerge

#14707 fix(service-portal): Documents logging and ui fixes.
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
  libs/api/domains/documents/src/lib/documentV2.service.ts
  libs/api/domains/documents/src/lib/models/v2/bulkMailAction.input.ts
  libs/api/domains/documents/src/lib/models/v2/document.model.ts
  libs/api/domains/documents/src/lib/models/v2/documents.input.ts
  libs/api/domains/documents/src/lib/models/v2/sender.model.ts
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilterV2.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV2.tsx
  libs/service-portal/documents/src/screens/Overview/index.tsx
Labels: automerge

#14706 fix(j-s): Robot Appeal Ruling Date
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseArchive.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/dateLog.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/explanatoryComment.model.ts
  apps/judicial-system/backend/src/app/modules/court/models/robotLog.model.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/event-log/models/eventLog.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/models/notification.model.ts
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
Labels: automerge

#14673 chore(j-s): Use Table component for prison cases
  apps/judicial-system/web/src/routes/Court/components/CasesAwaitingAssignmentTable/CasesAwaitingAssignmentTable.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CasesAwaitingConfirmationTable/CasesAwaitingConfirmationTable.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesForReview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
Labels: automerge, ai-review

#14644 feat(j-s): Service requirement
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240424141509-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/web/pages/akaera/yfirlit/[id].ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/SectionHeading/SectionHeading.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#14619 fix(parental-leave): Don't send private pension and union info when NO
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
Labels: automerge

#14686 feat(user-notification): Mark all as read
  apps/services/user-notification/src/app/modules/notifications/me-notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/app/modules/notifications/tests/me-notifications.controller.spec.ts
Labels: automerge

#14720 fix(service-portal-health): payment row handles own data
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/screens/Payments/PaymentTableRow.tsx
Labels: automerge

#14641 feat(native-app): Native app cache persistence
  apps/native/app/ios/Podfile.lock
  apps/native/app/package.json
  apps/native/app/src/assets/icons/cloud-offline-outline.png
  apps/native/app/src/assets/icons/cloud-offline-outline@2x.png
  apps/native/app/src/assets/icons/cloud-offline-outline@3x.png
  apps/native/app/src/components/nav-loading-spinner/loading-icon.tsx
  apps/native/app/src/components/offline/offline-icon.tsx
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/hooks/use-connectivity-indicator.ts
  apps/native/app/src/hooks/use-offline-update-navigation.ts
  apps/native/app/src/index.tsx
  apps/native/app/src/lib/post-mail-action.ts
  apps/native/app/src/screens/air-discount/air-discount.tsx
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/assets/assets-detail.tsx
  apps/native/app/src/screens/assets/assets-overview.tsx
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/family/family-overview.tsx
  apps/native/app/src/screens/finance/finance.tsx
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/inbox/inbox-filter.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/screens/license-scanner/license-scan-detail.tsx
  apps/native/app/src/screens/license-scanner/license-scanner.tsx
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/screens/more/personal-info.tsx
  apps/native/app/src/screens/settings/edit-email.tsx
  apps/native/app/src/screens/settings/edit-phone.tsx
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/screens/settings/utils/profile-queries.ts
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/screens/vehicles/vehicles-detail.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/screens/wallet-passport/wallet-passport.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/stores/mkkv.ts
  apps/native/app/src/stores/notifications-store.ts
  apps/native/app/src/stores/organizations-store.ts
  apps/native/app/src/types/apollo3-cache-persist.d.ts
  apps/native/app/src/types/react-native.d.ts
  apps/native/app/src/types/styled-components.d.ts
  apps/native/app/src/ui/lib/navigation-bar-sheet/navigation-bar-sheet.tsx
  apps/native/app/src/utils/component-registry.ts
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-dev-menu.ts
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
  apps/native/app/src/utils/register-component.tsx
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-utils.ts
  package.json
  yarn.lock
Labels: automerge

#14712 feat(j-s): Assign reviewer to indictment
  apps/judicial-system/api/src/app/modules/case-list/interceptors/caseList.interceptor.ts
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240503141513-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/updateRolesRules.spec.ts
  apps/judicial-system/web/pages/rikissaksoknari/akaera/yfirlit/[id].ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesForReview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: automerge

#14727 chore(app): Increase codemagic clone depth
  codemagic.yaml
Labels: automerge

#14719 chore(regulations): Update package
  package.json
  yarn.lock
Labels: automerge

#14724 fix(car-recycling): Add custom to allowedDelegations
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
Labels: automerge

#14723 refactor(gql-auth-admin): Refactor auth-admin GQL domain.
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/models/client.model.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.service.spec.ts
  libs/api/domains/auth-admin/src/lib/scope/scope.service.ts
  libs/api/domains/auth-admin/src/lib/shared/services/multi-environment.service.ts
  libs/api/domains/auth-admin/src/lib/tenant/models/tenant-environment.model.ts
  libs/api/domains/auth-admin/src/lib/tenant/models/tenant.model.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenant-environment.resolver.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.spec.ts
  libs/api/domains/auth-admin/src/lib/tenant/tenants.service.ts
  libs/api/domains/auth-admin/test/utils.ts
  libs/api/domains/auth-admin/tsconfig.spec.json
  libs/clients/auth/admin-api/src/index.ts
  libs/clients/middlewares/src/index.ts
Labels: automerge

#14689 feat(j-s): New decision type in S-cases -- Complete
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240502224235-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/components/CourtArrangements/CourtArrangements.tsx
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#14728 feat(j-s): InfoCard displays indictment reviewer
  apps/judicial-system/web/src/components/InfoCard/InfoCard.css.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
Labels: automerge

#14737 fix(parental-leave): Remove pension fund and validation
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.utils.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#14734 feat(fa): Adding ChildrenCustodyInformationApi to financial-aid form
  libs/application/templates/financial-aid/src/dataProviders/index.ts
  libs/application/templates/financial-aid/src/forms/Prerequisites.ts
  libs/application/templates/financial-aid/src/lib/FinancialAidTemplate.ts
  libs/application/templates/financial-aid/src/lib/messages/externalData.ts
  libs/application/templates/financial-aid/src/lib/types.ts
Labels: automerge

#14735 fix(driving-license): Tweaking done screen depending on application type
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#14739 fix(download-service): Add missing env DistrictCommissionersLicenses
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14740 chore: fix db secret for cleanup
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#14738 fix(car-recycling): Add custom delegation
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
Labels: automerge

#14744 fix(p-card): fix path name typo
  libs/clients/p-card/src/lib/pCardClient.config.ts
Labels: automerge

#14747 fix(ids-api): Add env var to worker to avoid error.
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#14745 chore: upgrade sequelize
  package.json
  yarn.lock
Labels: automerge, test everything

#14725 chore(xroad): update xroad path for MMS DEV
  apps/api/src/app/environments/environment.ts
  charts/islandis/values.dev.yaml
  infra/src/dsl/xroad.ts
  libs/clients/inna/src/lib/inna.config.ts
  libs/clients/mms/project.json
  libs/clients/mms/src/lib/mms.config.ts
Labels: automerge

#14582 feat(service-portal): implement notification settings screen
  apps/service-portal/src/assets/images/company.svg
  apps/system-e2e/src/tests/islandis/service-portal/smoke/notification-settings.spec.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/graphql/src/hooks/profile/useUpdateOrCreateUserProfile.ts
  libs/service-portal/information/src/components/NotificationSettings/ActorProfilesNotificationSettings.css.tsx
  libs/service-portal/information/src/components/NotificationSettings/ActorProfilesNotificationSettings.tsx
  libs/service-portal/information/src/components/NotificationSettings/UserProfileNotificationSettings.tsx
  libs/service-portal/information/src/components/NotificationSettings/cards/ActorProfileSettingsCard.tsx
  libs/service-portal/information/src/components/NotificationSettings/cards/NotificationSettingsCard.tsx
  libs/service-portal/information/src/components/NotificationSettings/cards/SettingsCard/SettingsCard.css.ts
  libs/service-portal/information/src/components/NotificationSettings/cards/SettingsCard/SettingsCard.tsx
  libs/service-portal/information/src/components/NotificationSettings/graphql/ActorProfiles.graphql
  libs/service-portal/information/src/components/NotificationSettings/graphql/UserProfile.graphql
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/information/src/module.tsx
  libs/service-portal/information/src/screens/UserNotifications/UserNotifications.tsx
Labels: automerge

#14754 chore(ids-api): Hotfix ids api cleanup worker infra
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#14756 fix(j-s): Relese fixes
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/web/pages/akaera/yfirlit/[id].ts
  apps/judicial-system/web/pages/domur/akaera/yfirlit/[id].ts
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
Labels: automerge

#14755 fix(api): Missing xroad from infra
  apps/api/infra/api.ts
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#14749 fix(web): Stop hardcoding footer link in district commissioner footer
  apps/web/components/Organization/Wrapper/Themes/SyslumennTheme/SyslumennFooter.tsx
Labels: automerge

#14758 fix(j-s): Contentful String
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
Labels: automerge

#14751 feat(j-s): Splits Case Transitions by Type
  apps/judicial-system/api/src/app/modules/case/interceptors/limitedAccessCase.transformer.ts
  apps/judicial-system/backend/migrations/20240508164452-update-case.js
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.archiveFilter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/appealsCourtUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/defenceUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/districtCourtUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/publicProsecutionUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseCompleted.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/caseNotCompleted.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/requestSharedWithDefenderGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/viewCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/writeCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/guards/viewCaseFile.guard.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardCaseScheduled.tsx
  apps/judicial-system/web/src/components/PageLayout/utils/index.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Cases/PublicProsecutorCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#14705 fix(Inheritance-report): fixing phone number error msg and format value
  libs/application/templates/inheritance-report/src/fields/HeirsAndPartitionRepeater/index.tsx
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
Labels: automerge, autoupdate

#14764 chore(j-s): Use Table component for appealed cases
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#14752 feat(admin-api): Add allowedAcr to clients.
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/auth-api-lib/migrations/20240502142738-add-allowed-acr-to-clients.js
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/clients/models/client.model.ts
  libs/auth-api-lib/src/lib/types.ts
Labels: automerge

#14762 feat(j-s): Reviewer completes indictment review
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20240508231112-update-case.js
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/ReviewDecision/ReviewDecision.css.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/ReviewDecision/ReviewDecision.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/ReviewDecision/ReviewDecision.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#14717 feat(fa): Adding children to back-end to Veita
  apps/financial-aid/api/src/app/modules/application/dto/createApplicationChildren.input.ts
  apps/financial-aid/api/src/app/modules/application/models/application.model.ts
  apps/financial-aid/api/src/app/modules/application/models/children.model.ts
  apps/financial-aid/backend/migrations/20240507110052-create-application_children.js
  apps/financial-aid/backend/src/app/app.module.ts
  apps/financial-aid/backend/src/app/modules/application/application.module.ts
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/backend/src/app/modules/application/dto/createApplication.dto.ts
  apps/financial-aid/backend/src/app/modules/application/dto/createApplicationChildren.dto.ts
  apps/financial-aid/backend/src/app/modules/application/dto/index.ts
  apps/financial-aid/backend/src/app/modules/application/models/application.model.ts
  apps/financial-aid/backend/src/app/modules/application/test/create.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/createEvent.spec.ts
  apps/financial-aid/backend/src/app/modules/application/test/createTestingApplicationModule.ts
  apps/financial-aid/backend/src/app/modules/children/children.module.ts
  apps/financial-aid/backend/src/app/modules/children/children.service.ts
  apps/financial-aid/backend/src/app/modules/children/index.ts
  apps/financial-aid/backend/src/app/modules/children/models/children.model.ts
  apps/financial-aid/backend/src/app/modules/children/models/index.ts
  apps/financial-aid/backend/src/app/modules/index.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  libs/api/domains/municipalities-financial-aid/src/lib/models/application.model.ts
  libs/api/domains/municipalities-financial-aid/src/lib/models/applicationChildren.model.ts
  libs/api/domains/municipalities-financial-aid/src/lib/models/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#14736 fix(j-s): Set correct active step in received indictments
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/useSections.spec.tsx
Labels: automerge

#14771 fix(web): Pension calculator, add one to month offset so it matches the frontend
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge

#14773 fix(contentful-apps): Hotfix - Add retry logic to link group field app (#14753)
  apps/contentful-apps/pages/fields/link-group-link-field.tsx
Labels: automerge

#14772 fix(web): Hotfix - Pension calculator, add one to month offset so it matches the frontend #14771
  libs/api/domains/social-insurance/src/lib/utils.ts
Labels: automerge

#14746 fix(service-portal-health): refactor health overview
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/healthInsurance.mock.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceConfirmation.model.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceConfirmation.response.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceError.model.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceOverview.model.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceOverview.response.ts
  libs/api/domains/rights-portal/src/lib/overview/models/insuranceStatus.model.ts
  libs/api/domains/rights-portal/src/lib/overview/overview.resolver.ts
  libs/api/domains/rights-portal/src/lib/overview/overview.service.ts
  libs/api/domains/rights-portal/src/lib/overview/overview.types.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/core/src/utils/dateUtils.ts
  libs/service-portal/health/codegen.yml
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.graphql
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
Labels: automerge

#14759 fix(island-ui): refactor Select stories
  libs/island-ui/core/src/Welcome.stories.mdx
  libs/island-ui/core/src/lib/Select/Select.stories.tsx
  libs/island-ui/core/src/lib/Select/Select.types.ts
Labels: automerge

#14695 feat(j-s): Indictment summary page
  apps/judicial-system/web/messages/Core/sections.ts
  apps/judicial-system/web/pages/domur/akaera/samantekt/[id].tsx
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#14767 chore(j-s): API Type Directives
  apps/judicial-system/api/src/app/modules/case-list/dto/caseList.input.ts
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/api/src/app/modules/case/dto/case.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/createCase.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/createCourtCase.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/extendCase.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/requestSignature.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/sendNotification.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/signatureConfirmation.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/transitionCase.input.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/api/src/app/modules/case/models/eventLog.model.ts
  apps/judicial-system/api/src/app/modules/case/models/notification.model.ts
  apps/judicial-system/api/src/app/modules/case/models/requestSignature.response.ts
  apps/judicial-system/api/src/app/modules/case/models/signatureConfirmation.response.ts
  apps/judicial-system/api/src/app/modules/defendant/dto/createDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/dto/deleteDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/createPresignedPost.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/deleteFile.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/getSignedUrl.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/updateFiles.input.ts
  apps/judicial-system/api/src/app/modules/file/dto/uploadFileToCourt.input.ts
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/api/src/app/modules/file/models/presignedPost.model.ts
  apps/judicial-system/api/src/app/modules/file/models/signedUrl.model.ts
  apps/judicial-system/api/src/app/modules/indictment-count/dto/createIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/dto/deleteIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/dto/updateIndictmentCount.input.ts
  apps/judicial-system/api/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/api/src/app/modules/institution/institution.model.ts
  apps/judicial-system/api/src/app/modules/police/dto/policeCaseFiles.input.ts
  apps/judicial-system/api/src/app/modules/police/dto/policeCaseInfo.input.ts
  apps/judicial-system/api/src/app/modules/police/dto/uploadPoliceCaseFile.input.ts
  apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/api/src/app/modules/police/models/uploadPoliceCaseFile.response.ts
  apps/judicial-system/api/src/app/modules/user/dto/createUser.input.ts
  apps/judicial-system/api/src/app/modules/user/dto/updateUser.input.ts
  apps/judicial-system/api/src/app/modules/user/dto/user.input.ts
  apps/judicial-system/api/src/app/modules/user/dto/users.input.ts
  apps/judicial-system/api/src/app/modules/user/models/user.model.ts
Labels: automerge

#14527 feat(driving-license): application for BE license
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/messages.ts
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/HealthDeclaration.tsx
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionOtherCountry.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.spec.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
  libs/application/templates/driving-license/src/shared/constants.ts
  libs/application/templates/driving-license/src/shared/index.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#14781 feat(driving-license): BE License
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/emailGenerators/messages.ts
  libs/application/templates/driving-license/src/dataProviders/index.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/fakeEligibility.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/HealthDeclaration.tsx
  libs/application/templates/driving-license/src/forms/draft/draft.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionOtherCountry.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionPhone.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionSummary.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionExternalData.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionFakeData.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.spec.ts
  libs/application/templates/driving-license/src/lib/utils/formUtils.ts
  libs/application/templates/driving-license/src/shared/constants.ts
  libs/application/templates/driving-license/src/shared/index.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#14710 feat(e2e): Occupational licenses test
  apps/system-e2e/src/support/wire-mocks.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/occupationalLicenses.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/socialInsurance.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/occupational-licenses.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
Labels: automerge

#14776 fix(housing-benefits): Update housing benefits filter
  libs/api/domains/housing-benefits/src/lib/dto/getHmsLoansPaymenthistory.input.ts
  libs/clients/hms-housing-benefits/src/clientConfig.json
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsTable.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/screens/HousingBenefits/HousingBenefits.tsx
  libs/service-portal/finance/src/screens/HousingBenefits/useHousingBenefitsFilters.ts
Labels: automerge, deploy-feature

#14777 fix(native-app): don't show photo for driving license unless feature flag is on
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
Labels: automerge

#14787 fix(housing-benefits): hotfix - Update housing benefits filter (#14776)
  libs/api/domains/housing-benefits/src/lib/dto/getHmsLoansPaymenthistory.input.ts
  libs/clients/hms-housing-benefits/src/clientConfig.json
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
  libs/service-portal/finance/src/components/HousingBenefitsPayments/HousingBenefitsTable.tsx
  libs/service-portal/finance/src/lib/messages.ts
  libs/service-portal/finance/src/screens/HousingBenefits/HousingBenefits.tsx
  libs/service-portal/finance/src/screens/HousingBenefits/useHousingBenefitsFilters.ts
Labels: automerge

#14785 fix(application-driving-license): Driving license requirements
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/lib/messages.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#14765 fix(application-ir): Don't show error on asset add
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
Labels: automerge

#14748 feat(application-system): New application - Health Insurance declaration
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/attachments/providers/applicationAttachmentProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/attachments/provider.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/consts/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/health-insurance-declaration/.babelrc
  libs/application/templates/health-insurance-declaration/.eslintrc.json
  libs/application/templates/health-insurance-declaration/README.md
  libs/application/templates/health-insurance-declaration/jest.config.ts
  libs/application/templates/health-insurance-declaration/project.json
  libs/application/templates/health-insurance-declaration/src/assets/Logo.tsx
  libs/application/templates/health-insurance-declaration/src/fields/applicantList.tsx
  libs/application/templates/health-insurance-declaration/src/fields/index.ts
  libs/application/templates/health-insurance-declaration/src/forms/HealthInsuranceDeclarationForm.ts
  libs/application/templates/health-insurance-declaration/src/forms/Prerequisites.ts
  libs/application/templates/health-insurance-declaration/src/forms/Submitted.ts
  libs/application/templates/health-insurance-declaration/src/index.ts
  libs/application/templates/health-insurance-declaration/src/lib/HealthInsuranceDeclarationTemplate.tsx
  libs/application/templates/health-insurance-declaration/src/lib/constants/index.ts
  libs/application/templates/health-insurance-declaration/src/lib/dataSchema.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/application.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/conclution.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/errors.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/index.ts
  libs/application/templates/health-insurance-declaration/src/lib/messages/prerequsites.ts
  libs/application/templates/health-insurance-declaration/src/shared/constants.ts
  libs/application/templates/health-insurance-declaration/src/types/index.ts
  libs/application/templates/health-insurance-declaration/src/utils/data.ts
  libs/application/templates/health-insurance-declaration/src/utils/index.ts
  libs/application/templates/health-insurance-declaration/tsconfig.json
  libs/application/templates/health-insurance-declaration/tsconfig.lib.json
  libs/application/templates/health-insurance-declaration/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/InstitutionMapper.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/health-insurance-api.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/index.ts
  libs/clients/icelandic-health-insurance/rights-portal/src/lib/providers.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge

#14790 fix(delegation-api): Grant service-portal namespace to make request to delegation api.
  apps/services/auth/delegation-api/infra/delegation-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#14778 feat(j-s): Table for reviewed cases
  apps/judicial-system/api/src/app/modules/case-list/models/caseList.model.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/caseList.interceptor.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Cases/PublicProsecutorCases.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
Labels: automerge

#14788 feat(university-gateway): Plausible analytics for Haskolanam + Minor fixes
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.css.ts
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  libs/plausible/src/lib/webEvents.ts
Labels: automerge

#14797 feat(university-gateway): Plausible analytics for Haskolanam + Minor fixes
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.css.ts
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  libs/plausible/src/lib/webEvents.ts
Labels: automerge

#14766 feat(web): Custom subpages
  apps/contentful-apps/pages/fields/custom-page-parent-field.tsx
  apps/contentful-apps/pages/fields/custom-page-unique-identifier-field.tsx
  apps/web/screens/queries/CustomPage.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getCustomPage.input.ts
  libs/cms/src/lib/dto/getCustomSubpage.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/importers/customPage.service.ts
  libs/shared/types/src/lib/api-cms-domain.ts
Labels: automerge

#14786 feat(service-portal): Mark all notifications as read
  libs/api/domains/notifications/src/lib/notifications.model.ts
  libs/api/domains/notifications/src/lib/notifications.resolver.ts
  libs/api/domains/notifications/src/lib/notifications.service.ts
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/screens/Notifications/Notifications.graphql
  libs/service-portal/information/src/screens/Notifications/Notifications.tsx
Labels: automerge

#14801 fix(service-portal): ActionCard img height
  libs/service-portal/core/src/components/ActionCard/ActionCard.css.ts
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
Labels: automerge

#14750 fix(Application-ctao): Minor typo fix in pdf
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/attachments/providers/applicationAttachmentProvider.ts
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/pdfGenerators/templates/complaint.ts
Labels: automerge

#14792 feat(j-s): Add defender to sendModifiedNotifications
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
Labels: automerge

#14795 feat(fa): Showing children information in Veita
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
  apps/financial-aid/web-veita/src/utils/applicationHelper.ts
Labels: automerge

#14559 feat(annoucement-of-death): Firearms
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/announcement-of-death.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/emailGenerators/assets/logo.jpg
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/emailGenerators/firearmApplicantNotification.ts
  libs/application/template-api-modules/src/lib/modules/templates/announcement-of-death/smsGenerators/requestReviewSms.ts
  libs/application/templates/announcement-of-death/src/fields/FirearmApplicant/index.tsx
  libs/application/templates/announcement-of-death/src/fields/index.ts
  libs/application/templates/announcement-of-death/src/forms/done.ts
  libs/application/templates/announcement-of-death/src/forms/draft/draft.ts
  libs/application/templates/announcement-of-death/src/forms/draft/sectionOverview.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionFirearms.ts
  libs/application/templates/announcement-of-death/src/forms/overviewSections.ts
  libs/application/templates/announcement-of-death/src/index.ts
  libs/application/templates/announcement-of-death/src/lib/dataSchema.ts
  libs/application/templates/announcement-of-death/src/lib/messages.ts
  libs/application/templates/announcement-of-death/src/types.ts
Labels: automerge, autoupdate

#14804 chore(application-driving-license): Test phone number formatting
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/utils/healthDeclarationMapper.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/utils/index.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/utils/index.ts
Labels: automerge

#14813 chore(CODEOWNERS): remove soffia from codeowners
  .github/CODEOWNERS
Labels: automerge

#14814 fix(regulations-admin): Modal visible by default. Bugfixing.
  libs/portals/admin/regulations-admin/src/components/ConfirmModal/ConfirmModal.tsx
  libs/portals/admin/regulations-admin/src/components/EditBasics.tsx
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#14820 chore(web): Connect test version of android app to island.is domain [HOTFIX]
  apps/web/public/.well-known/assetlinks.json
Labels: automerge

#14793 fix(island-ui): refactor Input stories
  libs/island-ui/core/src/lib/Input/Input.css.ts
  libs/island-ui/core/src/lib/Input/Input.mixins.ts
  libs/island-ui/core/src/lib/Input/Input.stories.tsx
  libs/island-ui/core/src/lib/Select/Select.css.ts
Labels: automerge

#14823 fix(regulations-admin): Only display modal on amending regs
  libs/portals/admin/regulations-admin/src/components/EditBasics.tsx
Labels: automerge

#14822 chore(license-api): Update logger levels
  apps/services/license-api/src/app/modules/license/license.service.ts
  apps/services/license-api/src/app/modules/license/test/license.controller.spec.ts
  apps/services/license-api/src/app/modules/license/test/license.service.spec.ts
Labels: automerge

#14779 fix(service-portal): Fix company onboarding in service portal
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  libs/api/domains/user-profile/src/lib/V2/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/userProfile.model.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/service-portal/graphql/src/lib/queries/getUserProfile.ts
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/ProfileForm.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/ContactNotVerified.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Phone.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/ProfileForms.css.ts
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/confirmNudge.graphql
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/types/form.ts
  libs/service-portal/information/src/components/PersonalInformation/UserOnboarding/UserOnboarding.graphql
  libs/service-portal/information/src/components/PersonalInformation/UserOnboarding/UserOnboarding.tsx
  libs/service-portal/information/src/components/PersonalInformation/UserOnboardingModal/UserOnboardingModal.tsx
  libs/service-portal/information/src/lib/messages.ts
  libs/service-portal/information/src/utils/showUserOnboardingModal.ts
Labels: automerge

#14825 fix(user-notification): lib default port
  libs/clients/user-notification/src/lib/userNotificationClient.config.ts
Labels: automerge

#14817 fix(native-app): Fix cache and network and loading state on finance screen
  apps/native/app/src/screens/finance/finance.tsx
Labels: automerge

#14818 fix(native-app): Fixes not to show loading on details screens when offline
  apps/native/app/src/screens/assets/assets-detail.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/screens/vehicles/vehicles-detail.tsx
Labels: automerge

#14829 chore(web): Add handle_all_urls to assetlinks [HOTFIX]
  apps/web/public/.well-known/assetlinks.json
Labels: automerge

#14826 fix(service-portal): Dashboard padding
  apps/service-portal/src/components/Layout/FullWidthLayout.tsx
Labels: automerge

#14809 fix(university-gateway): Fixing localization error and adding shortened id to programs to make them unique + changing filters event
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  libs/plausible/src/lib/webEvents.ts
Labels: automerge

#14808 fix(university-gateway): Fixing localization error and adding shortened id to programs to make them unique + changing filters event
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  libs/plausible/src/lib/webEvents.ts
Labels: automerge

#14831 fix(island-ui): Error state in Input component
  libs/island-ui/core/src/lib/Input/Input.mixins.ts
Labels: automerge

#14827 fix(island-ui): refactor Button stories
  libs/island-ui/core/src/lib/Button/Button.stories.tsx
  libs/island-ui/core/src/lib/Button/Button.tsx
Labels: automerge

#14837 fix(documents-v2): Add filetype fallback
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
Labels: automerge

#14436 fix(parental-leave): Refactor Sync - VMST
  libs/api/domains/directorate-of-labour/src/lib/directorate-of-labour.resolver.ts
  libs/api/domains/directorate-of-labour/src/models/applicationInformationPeriod.model.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Periods.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/Panel.tsx
  libs/application/templates/parental-leave/src/fields/components/Timeline/Timeline.tsx
  libs/application/templates/parental-leave/src/forms/EditsRequireAction.ts
  libs/application/templates/parental-leave/src/graphql/queries.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLatestPeriodValidationSection.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/templates/parental-leave/src/types.ts
  libs/clients/vmst/src/clientConfig.yaml
Labels: automerge

#14835 fix(j-s): Use prosecutor instead of prosecutorPerson
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
Labels: automerge

#14841 feat(new-primary-school): Implement relatives page
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Relatives.tsx
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm.ts
  libs/application/templates/new-primary-school/src/lib/constants.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
  libs/application/templates/new-primary-school/src/types.ts
Labels: automerge

#14821 fix: remove steps and add fields to others
  libs/application/templates/accident-notification/src/fields/FormOverview/index.tsx
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/whoIsTheNotificationForSection.ts
  libs/application/templates/accident-notification/src/lib/dataSchema.ts
  libs/application/templates/accident-notification/src/lib/messages/accidentDetails.ts
  libs/application/templates/accident-notification/src/lib/messages/application.ts
  libs/application/templates/accident-notification/src/lib/messages/injuredPersonInformation.ts
  libs/application/templates/accident-notification/src/utils/isSportAccidentAndEmployee.spec.ts
  libs/application/templates/accident-notification/src/utils/isSportAccidentAndEmployee.ts
Labels: automerge

#14846 chore(skilavottord): Improve logging
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/services/icelandicTransportAuthority.services.ts
Labels: automerge

#14844 fix(j-s): Modified notifications for defenders
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealCompletedNotifications.spec.ts
Labels: automerge

#14850 feat(web): Remove contact banner for tryggingastofnun in service web
  apps/web/screens/ServiceWeb/Home/Home.tsx
Labels: automerge

#14815 fix(parental-leave): Employer approval set before application approved
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#14849 chore(clients): Fix NX cache for university-careers
  libs/clients/university-careers/project.json
Labels: automerge

#14836 fix(inheritance-report): Assets validation
  libs/application/templates/inheritance-report/src/fields/AssetsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
Labels: automerge

#14830 feat(web): Manuals - Removal of back link
  apps/web/screens/Manual/components/ManualWrapper.tsx
Labels: automerge

#14856 fix(j-s): Confentful Fix
  apps/judicial-system/backend/src/app/messages/notifications.ts
Labels: automerge

#14770 feat(auth-api-lib): use delegation types in admin api
  apps/auth-admin-web/entities/dtos/base/client-base.dto.ts
  apps/auth-admin-web/entities/models/client.model.ts
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/api/domains/auth-admin/src/lib/client/clients.service.ts
  libs/api/domains/auth-admin/src/lib/client/dto/create-client.input.ts
  libs/api/domains/auth-admin/src/lib/client/dto/patch-client.input.ts
  libs/api/domains/auth-admin/src/lib/client/models/client-environment.model.ts
  libs/auth-api-lib/src/index.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-create-client.dto.ts
  libs/auth-api-lib/src/lib/clients/admin/dto/admin-patch-client.dto.ts
  libs/auth-api-lib/src/lib/clients/clients.module.ts
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/auth-api-lib/src/lib/clients/dto/base/client-base.dto.ts
  libs/auth-api-lib/src/lib/clients/models/client.model.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation-type.model.ts
  libs/portals/admin/ids-admin/src/screens/Client/Client.graphql
  libs/services/auth/testing/src/fixtures/client.fixture.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/services/auth/testing/src/fixtures/types.ts
Labels: automerge

#14857 fix(j-s): Contentful Namespace
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.strings.ts
Labels: automerge

#14800 fix(j-s): LÖKE Info
  apps/judicial-system/backend/src/app/modules/police/police.controller.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
Labels: automerge

#14799 chore(j-s): Guard Cleanup and Validations
  apps/judicial-system/backend/src/app/modules/case/dto/createCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/dto/internalCreateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/dto/transitionCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/archive.response.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseArchive.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/dateLog.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/deliver.response.ts
  apps/judicial-system/backend/src/app/modules/case/models/explanatoryComment.model.ts
  apps/judicial-system/backend/src/app/modules/case/models/signatureConfirmation.response.ts
  apps/judicial-system/backend/src/app/modules/court/models/robotLog.model.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/createDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/delete.response.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/deliver.response.ts
  apps/judicial-system/backend/src/app/modules/event-log/dto/createEventLog.dto.ts
  apps/judicial-system/backend/src/app/modules/event-log/models/eventLog.model.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createPresignedPost.dto.ts
  apps/judicial-system/backend/src/app/modules/file/dto/updateFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/models/deleteFile.response.ts
  apps/judicial-system/backend/src/app/modules/file/models/deliver.response.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/presignedPost.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/signedUrl.model.ts
  apps/judicial-system/backend/src/app/modules/file/models/uploadFileToCourt.response.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/dto/updateIndictmentCount.dto.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/delete.response.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/models/indictmentCount.model.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.model.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/sendNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/models/deliver.response.ts
  apps/judicial-system/backend/src/app/modules/notification/models/notification.model.ts
  apps/judicial-system/backend/src/app/modules/notification/models/sendNotification.response.ts
  apps/judicial-system/backend/src/app/modules/police/dto/uploadPoliceCaseFile.dto.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseInfo.model.ts
  apps/judicial-system/backend/src/app/modules/police/models/uploadPoliceCaseFile.response.ts
  apps/judicial-system/backend/src/app/modules/user/dto/createUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
Labels: automerge

#14802 fix(j-s): Filtering of public prosecution cases
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
Labels: automerge

#14828 feat(native-app): Problem and No data UX related component
  apps/native/app/src/hooks/use-translate.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/ui/lib/problem/problem-template.tsx
  apps/native/app/src/ui/lib/problem/problem.tsx
Labels: automerge

#14855 fix(j-s): Dokobit Polling Interval
  libs/dokobit-signing/src/lib/signing.config.ts
  libs/dokobit-signing/src/lib/signing.service.spec.ts
  libs/dokobit-signing/src/lib/signing.service.ts
Labels: automerge

#14861 fix(regulations-admin): Update article detection for amending articles and more
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
  libs/portals/admin/regulations-admin/src/utils/getDeletionOrAddition.ts
  libs/portals/admin/regulations-admin/src/utils/groupByArticleTitle.ts
Labels: automerge

#14848 feat(j-s): Public defender staff overview after review
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240514111505-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/defendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/updateRolesRules.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.css.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.css.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.css.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#14872 chore(web): Connect test version of android app to island.is domain
  apps/web/public/.well-known/assetlinks.json
Labels: automerge

#14870 chore: default timeout on nodes
  apps/api/src/app/graphql-options.factory.ts
  libs/cache/src/lib/cache.ts
Labels: deploy-feature

#14789 feat(native-app): Notifications V2
  apps/native/app/package.json
  apps/native/app/src/config.ts
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/graphql/fragments/notification.fragment.graphql
  apps/native/app/src/graphql/queries/notifications.graphql
  apps/native/app/src/index.tsx
  apps/native/app/src/lib/deep-linking.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/home/notifications-module.tsx
  apps/native/app/src/screens/home/vehicles-module.tsx
  apps/native/app/src/screens/notification-detail/notification-detail.tsx
  apps/native/app/src/screens/notifications/notifications.tsx
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/stores/mkkv.ts
  apps/native/app/src/stores/mmkv.ts
  apps/native/app/src/stores/notifications-store.ts
  apps/native/app/src/ui/lib/card/notification-card.tsx
  apps/native/app/src/ui/utils/theme.ts
  apps/native/app/src/utils/component-registry.ts
  apps/native/app/src/utils/create-skeleton-arr.ts
  apps/native/app/src/utils/get-main-root.ts
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-dev-menu.ts
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
  apps/native/app/src/utils/lifecycle/setup-notifications.ts
  apps/native/app/src/utils/lifecycle/setup-routes.ts
  libs/api/domains/notifications/src/lib/notifications.service.ts
  yarn.lock
Labels: automerge

#14875 fix: redis timeout
  apps/api/src/app/graphql-options.factory.ts
  apps/web/public/.well-known/assetlinks.json
  libs/cache/src/lib/cache.ts
Labels: automerge, high priority

#14824 fix(parental-leave): use dob instead of estimated dob sometimes
  libs/application/templates/parental-leave/src/fields/FirstPeriodStart/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsRepeater/index.tsx
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLatestPeriodValidationSection.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#14863 feat(native-app): Add optional scopes
  apps/native/app/src/stores/auth-store.ts
Labels: automerge

#14869 feat(fa): Adding muni settings to summary form
  libs/application/templates/financial-aid/src/fields/Summary/ChildrenInfo.tsx
  libs/application/templates/financial-aid/src/fields/Summary/SummaryForm.tsx
  libs/application/templates/financial-aid/src/lib/messages/summaryForm.ts
Labels: automerge

#14884 fix: Release increase timeout
  libs/cache/src/lib/cache.ts
Labels: automerge

#14885 fix: increase timeout
  libs/cache/src/lib/cache.ts
Labels: automerge
