Repository island-is/island.is, pull requests merged in 2024-11, with the labels that each got.

#16693 revert: "fix: added missing grant to auth ids api for user notification (#16680)"
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge, high priority

#16671 feat(j-s): Send service update emails to prosecutors
  apps/judicial-system/backend/src/app/modules/notification/subpoenaNotification.service.ts
  apps/judicial-system/web/pages/beinir/[id].ts
  apps/judicial-system/web/src/routes/Shared/RouteHandler/RouteHandler.css.ts
  apps/judicial-system/web/src/routes/Shared/RouteHandler/RouteHandler.tsx
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#16643 fix(j-s): Handling of wrong appeal info
  apps/judicial-system/api/src/app/modules/case-list/interceptors/caseList.interceptor.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.spec.ts
  apps/judicial-system/api/src/app/modules/case/interceptors/case.transformer.ts
Labels: automerge

#16686 fix(portals-admin): allow delete list & double tag
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens-parliamentary/Constituency/index.tsx
Labels: automerge

#16695 revert: "revert: "fix: added missing grant to auth ids api for user notification (#16680)" (#16693)"
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#16691 feat(application-system): Make required a dynamic field
  libs/application/core/src/lib/fieldBuilders.spec.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/CompanySearchFormField/CompanySearchFormField.tsx
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/NationalIdWithNameFormField/NationalIdWithNameFormField.tsx
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/application/ui-fields/src/lib/TextFormField/TextFormField.tsx
Labels: automerge

#16697 fix: Add namespace grants for services that need it, but don't have it
  apps/api/infra/api.ts
  apps/auth-admin-web/infra/auth-admin-web.ts
  apps/portals/admin/infra/portals-admin.ts
  apps/services/auth/ids-api/infra/identity-server.ts
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#16700 fix(service-portal): Hot fixes for bff regression
  apps/portals/my-pages/project.json
  libs/react-spa/bff/src/lib/BffProvider.tsx
  libs/react-spa/bff/src/lib/bff.hooks.ts
  libs/shared/components/src/auth/UserMenu/UserProfileLocale.tsx
Labels: automerge

#16692 fix(feature-flags): Remove unused feature flags from Origo
  libs/application/templates/aosh/change-machine-supervisor/src/lib/ChangeMachineSupervisorTemplate.ts
  libs/application/templates/aosh/deregister-machine/src/lib/DeregisterMachineTemplate.ts
  libs/application/templates/aosh/register-new-machine/src/lib/RegisterNewMachineTemplate.ts
  libs/application/templates/aosh/request-for-inspection/src/lib/RequestForInspectionTemplate.ts
  libs/application/templates/aosh/street-registration/src/lib/StreetRegistrationTemplate.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/CitizenshipTemplate.ts
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
  libs/application/templates/healthcare-license-certificate/src/lib/HealthcareLicenseCertificateTemplate.ts
  libs/application/templates/healthcare-work-permit/src/lib/HealthcareWorkPermitTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#16690 fix(haskolagatt): Remove obsolete program course enum
  apps/services/university-gateway/migrations/20241101095509-drop-course-enum.js
Labels: automerge

#16652 fix(transport-authority): Get correct requiresMileageRegistration value
  libs/api/domains/energy-funds/src/lib/energyFunds.service.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/forms/ChangeCoOwnerOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/forms/ChangeOperatorOfVehicleForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/InformationSection/vehicleSubSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/forms/TransferOfVehicleOwnershipForm/prerequisitesSection.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/dataSchema.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
  libs/clients/transport-authority/vehicle-codetables/src/lib/vehicleCodetablesClient.service.ts
Labels: automerge

#16657 fix(fa): direct payments making code more readable
  libs/application/template-api-modules/src/lib/modules/templates/financial-aid/financial-aid.service.ts
Labels: automerge

#16248 feat(portals-admin): Include relevant learn more links to the docs
  libs/portals/admin/ids-admin/src/lib/messages.ts
  libs/portals/admin/ids-admin/src/lib/navigation.ts
  libs/portals/admin/ids-admin/src/lib/paths.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.tsx
  libs/portals/admin/ids-admin/src/screens/Clients/Clients.tsx
  libs/portals/admin/ids-admin/src/screens/Permissions/Permissions.tsx
  libs/portals/core/src/components/PortalNavigation/PortalNavigation.tsx
Labels: automerge

#16653 feat(contentful-apps): Sitemap tree field
  apps/contentful-apps/components/sitemap/AddNodeButton.tsx
  apps/contentful-apps/components/sitemap/EditMenu.tsx
  apps/contentful-apps/components/sitemap/SitemapNode.css.ts
  apps/contentful-apps/components/sitemap/SitemapNode.tsx
  apps/contentful-apps/components/sitemap/SitemapNodeContent.tsx
  apps/contentful-apps/components/sitemap/SitemapTreeField.css.ts
  apps/contentful-apps/components/sitemap/SitemapTreeField.tsx
  apps/contentful-apps/components/sitemap/SitemapTreeFieldDialog.css.ts
  apps/contentful-apps/components/sitemap/SitemapTreeFieldDialog.tsx
  apps/contentful-apps/components/sitemap/entryContext.ts
  apps/contentful-apps/components/sitemap/utils.ts
  apps/contentful-apps/pages/fields/sitemap-tree-field.tsx
Labels: automerge

#16701 feat(web): List search - make content searchable
  libs/cms/src/lib/search/importers/genericListItem.service.ts
  libs/cms/src/lib/search/importers/teamList.service.ts
Labels: automerge

#16676 fix(auth-admin): Removed Legal guardian minor delegation type from access control
  libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationsIncoming.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
Labels: automerge

#16702 feat(web): Article keywords
  apps/web/components/HeadWithSocialSharing/HeadWithSocialSharing.tsx
  apps/web/screens/Article/Article.tsx
  apps/web/screens/queries/Article.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/article.model.ts
  libs/cms/src/lib/search/importers/article.service.ts
  libs/content-search-toolkit/src/queries/search.ts
Labels: automerge, skip-nx-cache

#16294 chore(api): Increase json body limit size in api
  apps/api/src/main.ts
Labels: automerge

#16698 feat(ojoi): PDF generation
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.resolver.ts
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.service.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getPdf.response.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/usePdf.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/error.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/preview.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/clients/official-journal-of-iceland/application/src/clientConfig.json
  libs/clients/official-journal-of-iceland/application/src/lib/ojoiApplicationClient.service.ts
Labels: automerge

#16688 fix(social-insurance-administration): Read permission for applicants with rejected applications
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/lib/AdditionalSupportForTheElderlyTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.ts
Labels: automerge

#16710 fix(auth-api-lib): Migration bff admin portal back_channel_logout_uri
  libs/auth-api-lib/migrations/20241104143212-add_back_channel_logout_uri_to_client_bff-stjornbord.js
Labels: automerge

#16711 fix(citizenship): fixing givenName and familyName missing
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/NationalIdWithGivenFamilyName/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/Parents/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectedChildrenExtra/SelectedRepeaterItem.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.service.ts
Labels: automerge

#16660 refactor(j-s): Transition Side Effects
  apps/judicial-system/backend/migrations/20241101152701-correct-appealed-cases.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.spec.ts
  apps/judicial-system/backend/src/app/modules/case/state/case.state.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/transition.spec.ts
Labels: automerge

#16713 fix(accident-notification): dates coming to sjukra
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification-v2.utils.ts
  libs/application/templates/accident-notification/src/forms/AccidentNotificationForm/aboutTheAccidentSection/locationSubSection.ts
Labels: automerge

#16718 fix(my-pages): health - sjukratryggingar - double click on certification button
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
Labels: automerge

#16719 fix(services-bff): Fix bff proxy download service aws cognito
  apps/services/bff/infra/admin-portal.infra.ts
  charts/islandis/values.dev.yaml
Labels: automerge

#16724 chore(ids-api): Remove unused code.
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
  libs/auth-api-lib/src/lib/delegations/delegations.service.ts
Labels: automerge

#16728 fix(download-service): Grant namespace to bff admin portal
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#16320 feat(cms): Most common page types are now directly fetched from cms
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/content-search-indexer/src/lib/cache-invalidation.service.ts
  libs/content-search-indexer/src/lib/indexing.module.ts
  libs/content-search-indexer/src/lib/indexing.service.ts
Labels: automerge

#16717 feat(web): Do not index org subpages that are 'standalone'
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
Labels: automerge

#16729 fix(j-s): Indictment Name
  apps/judicial-system/backend/src/app/messages/courtUpload.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentToCourt.spec.ts
Labels: automerge

#16721 feat(deleagtion-api): Create seed for general mandate delegations
  libs/auth-api-lib/seeders/20241105120627-add-general-mandate-delegations.js
Labels: automerge

#16734 fix(services-bff): Fix proxy headers
  apps/services/bff/src/app/modules/proxy/proxy.service.ts
Labels: automerge

#16733 fix(services-bff): Proxy service headers fix
  apps/services/bff/src/app/modules/proxy/proxy.service.ts
Labels: automerge

#16705 chore(ci): Set correct `GIT_*` on all images
  .github/workflows/push.yml
  scripts/ci/Dockerfile
Labels: automerge, deploy-feature

#16725 fix(id-card, citizenship): adding readme
  libs/application/templates/directorate-of-immigration/citizenship/README.md
  libs/application/templates/id-card/README.md
Labels: automerge

#16739 fix(register-new-machine): readme
  libs/application/templates/aosh/register-new-machine/README.md
Labels: automerge

#16726 fix(haskolagatt): Small fixes in application
  libs/application/templates/university/src/fields/EducationDetails/DetailsRepeaterItem.tsx
  libs/application/templates/university/src/fields/HiddenTextInput/index.tsx
  libs/application/templates/university/src/fields/HiddenValidation/index.tsx
  libs/application/templates/university/src/fields/Overview/index.tsx
  libs/application/templates/university/src/fields/ProgramSelection/index.tsx
  libs/application/templates/university/src/fields/Review/OtherDocumentsReview.tsx
  libs/application/templates/university/src/fields/Review/SchoolCareerReview.tsx
  libs/application/templates/university/src/fields/Review/index.tsx
  libs/application/templates/university/src/fields/index.ts
  libs/application/templates/university/src/forms/UniversityForm/FormerEducation/EducationDetails/Exemption.ts
  libs/application/templates/university/src/forms/UniversityForm/FormerEducation/EducationDetails/NotFinishedEducation.ts
  libs/application/templates/university/src/forms/UniversityForm/FormerEducation/EducationDetails/ThirdLevelEducation.ts
  libs/application/templates/university/src/forms/UniversityForm/FormerEducation/EducationDetails/degreeLevelOptions.ts
  libs/application/templates/university/src/forms/UniversityForm/InformationSection/ModeOfDeliverySubSection.ts
  libs/application/templates/university/src/forms/UniversityForm/InformationSection/ProgramSubSection.ts
  libs/application/templates/university/src/forms/UniversityForm/InformationSection/UserInformationSubSection.ts
  libs/application/templates/university/src/lib/constants.ts
  libs/application/templates/university/src/lib/dataSchema.ts
  libs/application/templates/university/src/lib/messages/information.ts
  libs/application/templates/university/src/lib/messages/review.ts
  libs/application/templates/university/src/shared/types.ts
  libs/application/templates/university/src/utils/formatDate.ts
  libs/application/templates/university/src/utils/getCountryName.ts
  libs/application/templates/university/src/utils/getDegreeLevelLabel.ts
  libs/application/templates/university/src/utils/index.ts
Labels: automerge

#16742 fix(j-s): Migration
  apps/judicial-system/backend/migrations/20241101152701-correct-appealed-cases.js
Labels: automerge

#16679 fix(licenses): pkpass status on machine license
  libs/clients/license-client/src/lib/clients/machine-license-client/machineLicenseClient.service.ts
  libs/clients/license-client/src/lib/clients/machine-license-client/machineLicenseClient.spec.ts
  libs/clients/license-client/src/lib/clients/machine-license-client/machineLicenseMapper.ts
Labels: automerge, deploy-feature

#16727 feat(service-portal): create new intro wrapper component
  libs/service-portal/core/src/components/FootNote/FootNote.tsx
  libs/service-portal/core/src/components/IntroHeader/IntroHeader.tsx
  libs/service-portal/core/src/components/IntroWrapper/IntroWrapper.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/education/src/screens/EducationGraduation/EducationGraduation.tsx
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesDetail/OccupationalLicensesDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge, deploy-feature

#16749 fix(api): Revert endpoint change regarding Service web
  libs/cms/src/lib/cms.resolver.ts
Labels: automerge

#16753 fix(services-bff): Fix prod infra config
  charts/islandis/values.prod.yaml
  infra/src/dsl/bff.ts
Labels: automerge

#16568 feat(auth-admin): system national ids lookup
  apps/application-system/api/src/app/app.module.ts
  libs/clients/identity/src/lib/identityClient.module.ts
  libs/clients/identity/src/lib/identityClient.service.ts
Labels: automerge

#16627 feat(auth-admin): only update/delete delegation index of the types that are being indexed.
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index-test-cases.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index.service.spec.ts
  libs/auth-api-lib/src/lib/delegations/delegations-index.service.ts
Labels: automerge

#16322 feat(zendesk): Refactor Zendesk to use config module
  apps/api/src/app/app.module.ts
  apps/services/auth/admin-api/src/app/app.module.ts
  apps/services/auth/admin-api/test/environment.jest.ts
  apps/services/auth/delegation-api/src/app/app.module.ts
  apps/services/auth/ids-api/src/app/app.module.ts
  apps/services/auth/personal-representative/src/app/app.module.ts
  apps/services/auth/public-api/src/app/app.module.ts
  libs/api/domains/communications/jest.config.ts
  libs/api/domains/communications/src/lib/communications.module.ts
  libs/api/domains/communications/src/lib/communications.service.spec.ts
  libs/api/domains/communications/src/lib/environments/environment.ts
  libs/api/domains/communications/test/environment.jest.ts
  libs/auth-api-lib/src/lib/delegations/delegations.module.ts
  libs/auth-api-lib/src/lib/environments/environment.ts
  libs/auth-api-lib/src/lib/environments/index.ts
  libs/clients/zendesk/src/index.ts
  libs/clients/zendesk/src/lib/zendesk.config.ts
  libs/clients/zendesk/src/lib/zendesk.module.ts
  libs/clients/zendesk/src/lib/zendesk.service.spec.ts
  libs/clients/zendesk/src/lib/zendesk.service.ts
Labels: automerge

#16736 fix(auth-admin): Use display name for api scope groups
  libs/portals/shared-modules/delegations/src/components/access/AccessList/AccessList.tsx
Labels: automerge

#16476 feat(ids-api): Default scopes for clients
  libs/auth-api-lib/migrations/20241018150418-add-default-scopes-to-client-allowed-scope-table.js
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
Labels: automerge

#16644 feat(application-system): Add locale to arguments passed to options functions for select, radio and checkbox fields
  libs/application/core/src/lib/fieldBuilders.spec.ts
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/core/src/lib/formUtils.ts
  libs/application/templates/announcement-of-death/src/fields/ExistingApplication/LinkExistingApplication.tsx
  libs/application/templates/announcement-of-death/src/fields/FilesRecipientCard/index.tsx
  libs/application/templates/data-protection-complaint/src/fields/CommissionFieldRepeater/CommissionFieldRepeater.tsx
  libs/application/templates/data-protection-complaint/src/fields/FieldLabel.tsx
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/Review/index.tsx
  libs/application/templates/driving-license/src/fields/LinkExistingApplication.tsx
  libs/application/templates/funding-government-projects/src/fields/FieldTitle/FieldTitle.tsx
  libs/application/templates/grindavik-housing-buyout/src/fields/AdditionalOwnersOverview/index.tsx
  libs/application/templates/health-insurance/src/fields/TextWithTooltip/TextWithTooltip.tsx
  libs/application/templates/institution-collaboration/src/fields/SecondaryContact/SecondaryContact.tsx
  libs/application/templates/operating-license/src/fields/PropertyOverviewRepeater/index.tsx
  libs/application/templates/operating-license/src/fields/PropertyRepeater/index.tsx
  libs/application/templates/parental-leave/src/fields/Rights/RequestMultipleBirthsDaysBoxChart.tsx
  libs/application/templates/reference-template/src/forms/ExampleForm.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/types/src/lib/Form.ts
  libs/application/ui-fields/src/lib/AccordionFormField/AccordionFormField.tsx
  libs/application/ui-fields/src/lib/AlertMessageFormField/AlertMessageFormField.tsx
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/BankAccountFormField/BankAccountFormField.tsx
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/CompanySearchFormField/CompanySearchFormField.tsx
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/DescriptionFormField/DescriptionFormField.tsx
  libs/application/ui-fields/src/lib/DividerFormField/DividerFormField.tsx
  libs/application/ui-fields/src/lib/ExpandableDescriptionFormField/ExpandableDescriptionFormField.tsx
  libs/application/ui-fields/src/lib/ImageFormField/ImageFormField.tsx
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/application/ui-fields/src/lib/StaticTableFormField/StaticTableFormField.tsx
  libs/application/ui-fields/src/lib/SubmitFormField/SubmitFormField.tsx
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
  libs/application/ui-fields/src/lib/TextFormField/TextFormField.tsx
  libs/application/ui-shell/src/components/FormStepper.tsx
  libs/application/ui-shell/src/components/Screen.tsx
  libs/application/ui-shell/src/hooks/useApplicationTitle.spec.ts
  libs/application/ui-shell/src/hooks/useApplicationTitle.ts
Labels: automerge

#16708 chore(application-system): Translate country list in phone prefix dropdown
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
  libs/island-ui/core/src/lib/PhoneInput/PhoneInput.tsx
  libs/island-ui/core/src/lib/PhoneInput/countryCodes.ts
  libs/shared/form-fields/src/lib/PhoneInputController/PhoneInputController.tsx
Labels: automerge

#16752 fix(samgongustofa): Disable "Continue" button when selecting vehicle with error (and user has over 20 vehicles)
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/index.tsx
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#16754 fix: disable global-auth on download-service (#16738)
  apps/download-service/infra/download-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#16751 fix(web): Pension calculator results - Only fetch preview if selected year is the most recent one
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
Labels: automerge

#16761 fix(services-bff): Move params from ids par requests body to header
  apps/services/bff/src/app/modules/ids/ids.service.ts
Labels: automerge

#16645 chore(j-s): Update subpoena status from digital-mailbox
  apps/judicial-system/backend/src/app/modules/police/internalPolice.controller.ts
  apps/judicial-system/backend/src/app/modules/police/police.module.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.service.ts
Labels: automerge

#16687 feat(j-s): Send defenders a notification once assigned to indictment case
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/caseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/defendantNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/defendantNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/defendantNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/defendantNotification/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAdvocateAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/notificationController/sendAdvocateAssignedNotifications.spec.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/Advocates.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectCivilClaimantAdvocate.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectDefender.tsx
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#16760 fix(j-s): Extension Tag
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/routes/Court/components/CasesInProgressTable/CasesInProgressTable.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
Labels: automerge

#16769 fix(web): Hotfix - pension calculator result preview only for current year (#16751)
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
Labels: automerge

#16732 fix(j-s): LÖKE File Upload
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverAppealToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentCaseToPolice.spec.ts
Labels: automerge

#16771 fix(services-bff): Bff secret log leak fix
  apps/services/bff/src/app/modules/ids/ids.service.ts
Labels: automerge

#16772 fix(services-bff): Remove log
  apps/services/bff/src/app/modules/auth/auth.service.ts
Labels: automerge

#16770 fix(application-system-api): Add missing national registry v3 xroad client config
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#16747 chore(j-s): Slack event when subpoena is serviced
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/limitedAccessSubpoena.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/subpoena.model.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.module.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/createTestingSubpoenaModule.ts
Labels: automerge

#16756 fix(parental-leave): Correct endDate for month slider
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#16777 fix(health-insurance): Fixing zod schema
  libs/application/templates/health-insurance/src/lib/dataSchema.ts
Labels: automerge

#16779 fix(parental-leave): Correct endDate for month slider
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#16755 chore(j-s): Fix DatePicker rendering issue
  apps/auth-admin-web/specs/index.spec.tsx
  package.json
  yarn.lock
Labels: automerge

#16782 fix(application-system-api): add secret from aws parameter store for national registry client v3
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#16682 chore(application-system): More refactoring old s3 stuff
  apps/application-system/api/src/app/modules/application/template-api.service.ts
  libs/api/domains/education/src/lib/education.module.ts
  libs/api/domains/education/src/lib/education.service.ts
  libs/api/domains/education/src/lib/education.spec.ts
  libs/api/domains/education/src/lib/s3.service.ts
  libs/api/domains/file-upload/src/lib/file-upload.resolver.ts
  libs/application/template-api-modules/src/lib/modules/shared/services/attachment-s3.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/attachments/attachment-s3.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/data-protection-complaint/data-protection-complaint.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/general-fishing-license/general-fishing-license.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/bucket/bucket.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance/health-insurance.utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/file-storage/src/lib/file-storage.module.ts
  libs/file-storage/src/lib/file-storage.service.spec.ts
  libs/file-storage/src/lib/file-storage.service.ts
  libs/nest/aws/src/lib/s3.service.spec.ts
  libs/nest/aws/src/lib/s3.service.ts
  package.json
  yarn.lock
Labels: automerge

#16778 fix(health-insurance): Fixing zod schema
  libs/application/templates/health-insurance/src/lib/dataSchema.ts
Labels: automerge

#16783 fix(zendesk-service): Add missing Zendesk config values
  apps/services/auth/delegation-api/infra/delegation-api.ts
  apps/services/auth/personal-representative/infra/personal-representative.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#16784 feat(transfer-of-machine-ownership): aosh ondelete
  libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/emailGenerators/applicationDeleteEmail.ts
  libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/transfer-of-machine-ownership.service.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/dataProviders/index.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/forms/TransferOfMachineOwnershipForm/prerequisitesSection.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/aosh/transfer-of-machine-ownership/src/shared/constants.ts
  libs/clients/work-machines/src/clientConfig.json
  libs/clients/work-machines/src/lib/workMachines.service.ts
Labels: automerge

#16722 feat(j-s): Send subpoena intro text to service portal
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfSubpoena.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.service.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalCase.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
  libs/judicial-system/consts/src/index.ts
  libs/judicial-system/consts/src/lib/messages.ts
Labels: automerge

#16787 fix(air-discount-scheme-backend): Added myflug to cooperation field
  apps/air-discount-scheme/backend/src/app/modules/flight/dto/body.dto.ts
Labels: automerge

#16788 fix(air-discount-scheme-backend): Added myflug to cooperation field (…
  apps/air-discount-scheme/backend/src/app/modules/flight/dto/body.dto.ts
Labels: automerge

#16567 fix(my-pages): health vaccination tags & locale
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/enums.ts
  libs/api/domains/health-directorate/src/lib/models/vaccinations.model.ts
  libs/api/domains/health-directorate/src/lib/utils/mappers.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.service.ts
  libs/service-portal/health/src/screens/Vaccinations/Vaccinations.graphql
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
  libs/service-portal/health/src/screens/Vaccinations/dataStructure.ts
  libs/service-portal/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsTable.tsx
  libs/service-portal/health/src/utils/tagSelector.ts
Labels: automerge, deploy-feature

#16789 fix(j-s): Display verdict view date for defenders
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#16757 feat(native-app): Add medicine section
  apps/native/app/src/graphql/queries/health.graphql
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/health/health-overview.tsx
  apps/native/app/src/ui/lib/input/input.tsx
Labels: automerge

#16794 fix(web): Stop displaying short title for organization vacancies
  libs/api/domains/icelandic-government-institution-vacancies/src/lib/icelandic-government-institution-vacancies.resolver.ts
Labels: automerge

#16741 fix(shared): Markdown links always open in a new tab
  libs/shared/components/src/Markdown/Markdown.tsx
  libs/shared/components/src/Markdown/markdownOptions.tsx
Labels: automerge

#16791 fix(parental-leave): Change maximumStartDate calculation
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
Labels: automerge

#16762 feat(ojoi-web): Categories page
  apps/web/components/OfficialJournalOfIceland/OJOIUtils.ts
  apps/web/screens/OfficialJournalOfIceland/OJOICategories.tsx
  apps/web/screens/OfficialJournalOfIceland/OJOIHome.tsx
  apps/web/screens/OfficialJournalOfIceland/messages.ts
  apps/web/screens/queries/OfficialJournalOfIceland.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.model.ts
  libs/clients/official-journal-of-iceland/public/src/clientConfig.json
  libs/island-ui/core/src/lib/CategoryCard/CategoryCard.tsx
Labels: automerge

#16800 chore: Make QA codeowners of testing/e2e lib
  .github/CODEOWNERS
Labels: automerge

#16799 fix(aosh): changing pdf
  libs/application/templates/aosh/work-accident-notification/src/assets/vinnueftirlitid.tsx
  libs/application/templates/aosh/work-accident-notification/src/fields/PdfOverview/pdfDocument.tsx
Labels: automerge

#16806 fix(parental-leave): Change maxStartDate calculation
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
Labels: automerge

#16811 fix(my-pages): health - sjukratryggingar - double click on certificat…
  libs/service-portal/health/src/screens/HealthOverview/HealthOverview.tsx
Labels: automerge

#16810 fix(financial-statement-political-party): Submit application fix
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-political-party/financial-statement-political-party.service.ts
  libs/application/templates/inao/financial-statement-political-party/src/fields/Overview/Overview.tsx
Labels: automerge

#16809 feat(bulk-mileage): HOTFIX - update errors (#16720)
  libs/api/domains/vehicles/project.json
  libs/api/domains/vehicles/src/lib/dto/getBulkVehicleMileageRequestOverview.input.ts
  libs/api/domains/vehicles/src/lib/messages.ts
  libs/api/domains/vehicles/src/lib/models/v3/bulkMileage/bulkMileageRegistrationRequestError.model.ts
  libs/api/domains/vehicles/src/lib/resolvers/bulkMileage.resolver.ts
  libs/api/domains/vehicles/src/lib/services/bulkMileage.service.ts
  libs/api/domains/vehicles/src/lib/services/errorCodes.ts
  libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
  libs/api/domains/vehicles/src/lib/vehicles.module.ts
  libs/clients/vehicles-mileage/src/clientConfig.json
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.graphql
  libs/service-portal/assets/src/screens/VehicleBulkMileageJobDetail/VehicleBulkMileageJobDetail.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileageJobOverview/VehicleBulkMileageJobOverview.tsx
  libs/service-portal/assets/src/screens/VehicleBulkMileageUpload/VehicleBulkMileageUpload.tsx
  libs/service-portal/assets/src/utils/parseFileToMileage.ts
Labels: automerge

#16684 feat(auth-admin): Use birtNafn instead of fulltNafn
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/mocks.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  libs/clients/national-registry/v3/src/clientConfig.json
  libs/clients/national-registry/v3/src/lib/nationalRegistryV3.service.ts
Labels: automerge

#16797 feat(ojoi-application): Adding addtions as html
  libs/application/templates/official-journal-of-iceland/src/components/additions/Additions.tsx
  libs/application/templates/official-journal-of-iceland/src/components/htmlEditor/HTMLEditor.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Attachments.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/constants.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/attachments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
  libs/application/templates/official-journal-of-iceland/src/screens/RequirementsScreen.tsx
Labels: automerge

#16775 feat(native-app): update vehicleList endpoint to V2
  apps/native/app/src/graphql/fragments/vehicle.fragment.graphql
  apps/native/app/src/graphql/queries/vehicles.graphql
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/home/vehicles-module.tsx
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
Labels: automerge

#16815 feat(web): Stepper - Add "Links" below answers in the history
  apps/web/components/Stepper/Stepper/Stepper.css.ts
  apps/web/components/Stepper/Stepper/Stepper.tsx
  apps/web/components/Stepper/utils.ts
Labels: automerge

#16730 fix: inao pp submit application
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-political-party/financial-statement-political-party.service.ts
  libs/application/templates/inao/financial-statement-political-party/src/fields/Overview/Overview.tsx
Labels: automerge, deploy-feature, high priority

#16812 fix(ojoi-web): Setting max categories to display
  apps/web/screens/OfficialJournalOfIceland/OJOIHome.tsx
Labels: automerge

#16817 fix(web): Update endpoint for IBM Watson to now send feedback to Cloudant
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.config.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.service.ts
  package.json
  yarn.lock
Labels: automerge

#16807 chore(native-app): bump app version to 1.4.7
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#16694 feat(tests): Add functions and documentation to testing/e2e
  .gitignore
  libs/testing/e2e/README.md
  libs/testing/e2e/src/index.ts
  libs/testing/e2e/src/lib/config/playwright-config.ts
  libs/testing/e2e/src/lib/libs/testing/e2e.spec.ts
  libs/testing/e2e/src/lib/libs/testing/e2e.ts
  libs/testing/e2e/src/lib/support/addons.ts
  libs/testing/e2e/src/lib/support/api-tools.ts
  libs/testing/e2e/src/lib/support/application.ts
  libs/testing/e2e/src/lib/support/disablers.ts
  libs/testing/e2e/src/lib/support/email-account.ts
  libs/testing/e2e/src/lib/support/i18n.ts
  libs/testing/e2e/src/lib/support/login.ts
  libs/testing/e2e/src/lib/support/session.ts
  libs/testing/e2e/src/lib/support/urls.ts
  libs/testing/e2e/src/lib/support/utils.ts
  libs/testing/e2e/src/lib/utils/locator-helpers.ts
  libs/testing/e2e/src/lib/utils/pageHelpers.ts
  package.json
  yarn.lock
Labels: automerge

#16744 fix(native-app): Multiple license fixes
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/vehicles/vehicles-detail.tsx
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/ui/lib/card/license-card.tsx
  apps/native/app/src/ui/lib/field/field-card.tsx
  apps/native/app/src/ui/lib/field/field.tsx
Labels: automerge

#16823 feat(native-app): Revert "feat: update vehicleList endpoint to V2"
  apps/native/app/src/graphql/fragments/vehicle.fragment.graphql
  apps/native/app/src/graphql/queries/vehicles.graphql
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/home/vehicles-module.tsx
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
Labels: automerge

#16731 feat(j-s): Service announcement for defenders
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
  libs/island-ui/core/src/lib/AlertMessage/AlertMessage.tsx
  libs/island-ui/core/src/lib/Box/Box.tsx
  libs/island-ui/core/src/lib/Box/useBoxStyles.css.ts
  libs/island-ui/core/src/lib/Box/useBoxStyles.ts
Labels: automerge, high priority

#16803 ci(dependabot): improve schedules
  .github/dependabot.yml
Labels: automerge

#16743 feat(ui-core): mobile error should also have border
  libs/island-ui/core/src/lib/ProblemTemplate/ProblemTemplate.css.ts
Labels: automerge

#16793 feat(web): Organization page - top level navigation links
  apps/contentful-apps/components/sitemap/utils.ts
  apps/web/screens/queries/Organization.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/organizationPage.model.ts
  libs/shared/types/src/lib/api-cms-domain.ts
Labels: automerge

#16837 chore(ci): Quote dependabot times
  .github/dependabot.yml
Labels: automerge, high priority

#16841 ci: remove dependabot versioning-strategy
  .github/dependabot.yml
Labels: automerge, high priority

#16822 fix(regulations-admin): Format ministry name
  apps/download-service/src/app/modules/regulation-documents/regulation-documents.controller.ts
Labels: automerge

#16814 fix(parental-leave): If startDate is the 31st then the endDate should be 1 day later
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#16836 fix(contentful-apps): Add missing variable in check for pie chart type
  apps/contentful-apps/pages/fields/chart-component-source-data-key-field.tsx
Labels: automerge

#16847 fix(parental-leave): If startDate is the 31st then the endDate should be 1 day later (#16814)
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.spec.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#16854 fix(services-bff): Fix refresh token condition
  apps/services/bff/src/app/modules/user/user.service.ts
Labels: automerge

#16827 chore: Making sure buildx image exists in our repo before pulling
  .github/workflows/push.yml
Labels: automerge

#16840 fix(j-s): Fix ServiceAnnouncement component for defenders
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#16851 fix(services-bff): Fix refresh token condition
  apps/services/bff/src/app/modules/user/user.service.ts
Labels: automerge

#16835 feat(endorsement-system): Improved error logs
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/services/endorsements/api/src/environments/environment.ts
Labels: automerge

#16829 chore(e2e): Add dev-services to `run-local-env`
  infra/src/dsl/value-files-generators/local-setup.ts
Labels: automerge

#16833 feat(ids-admin): Remove seed script that inserts delegation
  libs/auth-api-lib/seeders/20241105120627-add-general-mandate-delegations.js
Labels: automerge

#16820 fix(ids-api): Zendesk config
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/services/services-auth-ids-api/values.dev.yaml
  charts/services/services-auth-ids-api/values.prod.yaml
  charts/services/services-auth-ids-api/values.staging.yaml
Labels: automerge

#16821 chore(application-system): Add logging to notification service and make it awaitable
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/children-residence-change.service.ts
  libs/application/template-api-modules/src/lib/notification/notifications.module.ts
  libs/application/template-api-modules/src/lib/notification/notifications.service.ts
Labels: automerge

#16712 fix(auth-admin): Move sleep logic from messgeHandler to worker service
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  libs/message-queue/src/lib/nest/types.ts
  libs/message-queue/src/lib/nest/utils.spec.ts
  libs/message-queue/src/lib/nest/utils.ts
  libs/message-queue/src/lib/nest/worker.service.ts
Labels: automerge

#16642 feat(auth-admin): Delete email and phone from user profile
  apps/services/user-profile/src/app/v2/user-profile.controller.ts
  apps/services/user-profile/src/app/v2/user-profile.service.ts
  libs/api/domains/user-profile/src/lib/V1/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/V2/userProfile.service.ts
  libs/api/domains/user-profile/src/lib/adminUserProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/dto/updateUserProfileInput.ts
  libs/api/domains/user-profile/src/lib/userProfile.resolver.ts
  libs/api/domains/user-profile/src/lib/userProfile.service.ts
  libs/portals/admin/service-desk/src/lib/messages.ts
  libs/portals/admin/service-desk/src/screens/Companies/Companies.tsx
  libs/portals/admin/service-desk/src/screens/Procurers/Procurers.tsx
  libs/portals/admin/service-desk/src/screens/User/User.graphql
  libs/portals/admin/service-desk/src/screens/User/User.tsx
  libs/portals/admin/service-desk/src/screens/Users/Users.tsx
Labels: automerge

#16763 fix(auth-admin): Hide client secret native clients
  apps/services/auth/admin-api/src/app/v2/clients/me-clients.controller.ts
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.tsx
  libs/portals/admin/ids-admin/src/screens/Client/components/BasicInfo.tsx
Labels: automerge

#16850 fix(service-portal): petitions - export list
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/styles.css.ts
  libs/portals/my-pages/petitions/src/screens/queries.ts
Labels: automerge

#16856 chore(tests): E2E lib comments and cleanup
  libs/testing/e2e/src/index.ts
  libs/testing/e2e/src/lib/config/playwright-config.ts
  libs/testing/e2e/src/lib/helpers/api-tools.ts
  libs/testing/e2e/src/lib/helpers/locator-helpers.ts
  libs/testing/e2e/src/lib/helpers/utils.ts
  libs/testing/e2e/src/lib/modules/application.ts
  libs/testing/e2e/src/lib/modules/disablers.ts
  libs/testing/e2e/src/lib/modules/i18n.ts
  libs/testing/e2e/src/lib/modules/urls.ts
  libs/testing/e2e/src/lib/session/email-account.ts
  libs/testing/e2e/src/lib/session/login.ts
  libs/testing/e2e/src/lib/session/session.ts
  libs/testing/e2e/src/lib/support/addons.ts
  libs/testing/e2e/src/lib/support/api-tools.ts
  libs/testing/e2e/src/lib/support/application.ts
  libs/testing/e2e/src/lib/support/disablers.ts
  libs/testing/e2e/src/lib/support/i18n.ts
  libs/testing/e2e/src/lib/support/login.ts
  libs/testing/e2e/src/lib/support/session.ts
  libs/testing/e2e/src/lib/support/utils.ts
  libs/testing/e2e/src/lib/utils/locator-helpers.ts
  libs/testing/e2e/src/lib/utils/pageHelpers.ts
Labels: automerge

#16623 feat: support phone in table repeater
  libs/application/templates/reference-template/src/forms/ExampleForm.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterItem.tsx
Labels: automerge

#16861 chore(application-system): Stop populating club info which duplicates employer info
  libs/api/domains/health-insurance/src/lib/accident-notification.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/accident-notification/accident-notification-v2.utils.ts
Labels: automerge

#16786 fix(j-s): Merge Case Access
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/mergedCaseExists.guard.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/caseExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/caseHasExistedGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/guards/test/limitedAccessCaseExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/extend.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/transition.spec.ts
  apps/judicial-system/backend/src/app/modules/file/file.controller.ts
  apps/judicial-system/backend/src/app/modules/file/guards/limitedAccessViewCaseFile.guard.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/getCaseFileSignedUrlRolesRules.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/caseString.ts
  libs/judicial-system/types/src/lib/dateLog.ts
  libs/judicial-system/types/src/lib/eventLog.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#16759 chore(j-s): Display case info in header
  apps/judicial-system/web/src/components/CaseTitleInfoAndTags/CaseTitleInfoAndTags.tsx
  apps/judicial-system/web/src/components/OverviewHeader/OverviewHeader.tsx
  apps/judicial-system/web/src/components/PageTitle/PageTitle.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Confirmation/Confirmation.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/WithdrawnAppealCase/WithdrawnAppealCase.tsx
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AddFiles/AddFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealCaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/Login/Login.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
Labels: automerge

#16808 chore(j-s): Logging more info for system status
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/xrd-api/src/app/app.controller.ts
Labels: automerge

#16865 fix(api): add ff to resolver
  libs/api/domains/health-directorate/src/lib/health-directorate.module.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#16839 chore(deps): Update `@aws-sdk` client libraries
  infra/package.json
  infra/yarn.lock
  package.json
  yarn.lock
Labels: automerge

#16874 fix(api): add correct scope
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
Labels: automerge

#16859 fix(regulations-admin): Update text amending
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#16884 revert: Update `@aws-sdk` client libraries (#16839)"
  infra/package.json
  infra/yarn.lock
  package.json
  yarn.lock
Labels: deploy-feature

#16792 chore(application-system): Increase cpu and mem limit and request to avoid crashloops
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/application-system-api/values.dev.yaml
  charts/services/application-system-api/values.prod.yaml
  charts/services/application-system-api/values.staging.yaml
Labels: automerge

#16878 feat(native-app): disable tracking of user interactions in app
  apps/native/app/src/utils/lifecycle/setup-globals.ts
Labels: automerge

#16862 feat(native-app): log confirm actions of subpoena to backend
  apps/native/app/src/graphql/queries/inbox.graphql
  apps/native/app/src/screens/document-detail/document-detail.tsx
Labels: automerge

#16894 chore(clients-cms): Define code owners for cms client
  .github/CODEOWNERS
Labels: automerge

#16895 fix(contentful-apps): Add missing variable in check for pie chart type
  apps/contentful-apps/pages/fields/chart-component-source-data-key-field.tsx
Labels: automerge

#16893 chore(application-system): Set initialDelay to 20 seconds
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/application-system-api/values.dev.yaml
  charts/services/application-system-api/values.prod.yaml
  charts/services/application-system-api/values.staging.yaml
Labels: automerge

#16866 fix(portals-admin): petition - export list
  libs/portals/admin/petition/src/components/ExportList/MyPdfDocument/index.tsx
  libs/portals/admin/petition/src/components/ExportList/MyPdfDocument/island.png
  libs/portals/admin/petition/src/components/ExportList/MyPdfDocument/thjodskra.png
  libs/portals/admin/petition/src/components/ExportList/downloadCSV.ts
  libs/portals/admin/petition/src/components/ExportList/exportList.graphql
  libs/portals/admin/petition/src/components/ExportList/index.tsx
  libs/portals/admin/petition/src/components/ExportList/styles.css.ts
  libs/portals/admin/petition/src/components/ListSignersTable/index.tsx
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/portals/my-pages/petitions/src/screens/PetitionsTable/index.tsx
Labels: automerge

#16892 fix(j-s): Service Status Event
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
Labels: automerge

#16873 fix(my-pages): my pages & app fix for health
  libs/api/domains/health-directorate/src/lib/health-directorate.module.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/enums.ts
  libs/api/domains/health-directorate/src/lib/models/vaccinations.model.ts
  libs/api/domains/health-directorate/src/lib/utils/mappers.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.service.ts
  libs/feature-flags/src/lib/features.ts
  libs/service-portal/health/src/screens/Vaccinations/Vaccinations.graphql
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsWrapper.tsx
  libs/service-portal/health/src/screens/Vaccinations/dataStructure.ts
  libs/service-portal/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsTable.tsx
  libs/service-portal/health/src/utils/tagSelector.ts
Labels: automerge

#16867 chore(auth-apis): Add api mocks to tests.
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-incoming.spec.ts
  apps/services/auth/public-api/test/mocks/companyRegistryClientService.mock.ts
  apps/services/auth/public-api/test/mocks/index.ts
  apps/services/auth/public-api/test/setup.ts
Labels: automerge

#16801 feat(j-s): Defender Updated Notification
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/createCourtCase.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/archive.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/defendantNationalIdExists.guard.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/test/defendantNationalIdExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/defendantController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/deliverDefendantToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/updateDefendant.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/internalDefendantController/updateDefendantGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/defendantNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/defendantNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/subpoenaNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/subpoenaNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/subpoena/dto/updateSubpoena.dto.ts
  apps/judicial-system/backend/src/app/modules/subpoena/internalSubpoena.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.module.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/createTestingSubpoenaModule.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#16896 feat(my-pages): add info and deadline text
  libs/api/domains/law-and-order/src/lib/law-and-order.service.ts
  libs/api/domains/law-and-order/src/models/subpoena.model.ts
  libs/clients/judicial-system-sp/src/clientConfig.json
  libs/portals/my-pages/law-and-order/src/screens/Subpoena/Subpoena.graphql
  libs/portals/my-pages/law-and-order/src/screens/Subpoena/Subpoena.tsx
Labels: automerge

#16647 feat(driving-license): start on advanced driving-license
  libs/application/templates/driving-license-duplicate/src/fields/Alert.tsx
  libs/application/templates/driving-license/src/fields/AdvancedLicenseSelection/AdvancedLicenseSelection.tsx
  libs/application/templates/driving-license/src/fields/AdvancedLicenseSelection/index.tsx
  libs/application/templates/driving-license/src/fields/index.ts
  libs/application/templates/driving-license/src/forms/prerequisites/getForm.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionAdvancedLicenseSelection.ts
  libs/application/templates/driving-license/src/forms/prerequisites/sectionApplicationFor.ts
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/dataSchema.ts
  libs/application/templates/driving-license/src/lib/drivingLicenseTemplate.ts
  libs/application/templates/driving-license/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#16750 chore(j-s): Civil claimant spokesperson assigned notifications
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/index.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/defendant/civilClaimant.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/civilClaimaint.decorator.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/civilClaimantExists.guard.ts
  apps/judicial-system/backend/src/app/modules/defendant/guards/test/civilClaimantExistsGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/index.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/createGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/delete.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/deleteGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/deleteRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/update.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/updateGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/civilClaimantController/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/createTestingDefendantModule.ts
  apps/judicial-system/backend/src/app/modules/notification/caseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/civilClaimantNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/civilClaimantNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/civilClaimantNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/civilClaimantNotification/sendSpokespersonAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAdvocateAssignedNotifications.spec.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#16401 feat(native-app): add organ donation to app
  apps/native/app/src/graphql/queries/health.graphql
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/health/health-overview.tsx
Labels: automerge

#16505 feat(grants): Grants plaza UI
  .github/CODEOWNERS
  apps/web/components/Grant/HeaderWithImage/HeaderWithImage.css.ts
  apps/web/components/Grant/HeaderWithImage/HeaderWithImage.tsx
  apps/web/components/Grant/HeaderWithImage/index.ts
  apps/web/components/Grant/SearchSection/SearchSection.css.ts
  apps/web/components/Grant/SearchSection/SearchSection.tsx
  apps/web/components/Grant/SearchSection/index.tsx
  apps/web/components/Grant/Wrapper/GrantWrapper.tsx
  apps/web/components/Grant/index.ts
  apps/web/components/PlazaCard/PlazaCard.css.ts
  apps/web/components/PlazaCard/PlazaCard.tsx
  apps/web/components/SearchSection/SearchSection.tsx
  apps/web/components/real.ts
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/styrkjatorg/index.ts
  apps/web/pages/styrkjatorg/leit/index.ts
  apps/web/pages/styrkjatorg/styrkur/[id].ts
  apps/web/public/assets/sofa.svg
  apps/web/screens/Grants/Grant/Grant.tsx
  apps/web/screens/Grants/Grant/GrantSidebar.tsx
  apps/web/screens/Grants/Home/GrantsHome.tsx
  apps/web/screens/Grants/SearchResults/SearchResults.tsx
  apps/web/screens/Grants/SearchResults/SearchResultsContent.tsx
  apps/web/screens/Grants/SearchResults/SearchResultsFilter.tsx
  apps/web/screens/Grants/messages.ts
  apps/web/screens/queries/GenericTag.ts
  apps/web/screens/queries/Grants.ts
  apps/web/screens/queries/index.tsx
  libs/cms/src/lib/cms.contentful.service.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getGenericTagsInTagGroups.input.ts
  libs/cms/src/lib/dto/getGrants.input.ts
  libs/cms/src/lib/dto/getSingleGrant.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/fund.model.ts
  libs/cms/src/lib/models/grant.model.ts
  libs/cms/src/lib/models/grantList.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/importers/grants.service.ts
  libs/cms/src/lib/search/mapping.service.ts
  libs/shared/types/src/lib/api-cms-domain.ts
Labels: automerge, deploy-feature

#16883 fix(application-system-api): Copy object on upload fix
  libs/nest/aws/src/lib/s3.service.ts
Labels: automerge, high priority
