Repository island-is/island.is, pull requests merged in 2024-01, with the labels that each got.

#13230 fix(fa): Wording for error message when fetching payments
  apps/financial-aid/web-veita/src/components/Profile/ApplicationProfile.tsx
Labels: automerge

#13238 fix(skilavottord): mileage-to-samgongustofu (#13216)
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.resolver.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#13225 fix(fa): Adding employee kt to wise endpoint
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
Labels: automerge

#13235 feat(web): Transport authority service web contact form
  apps/web/screens/ServiceWeb/Forms/utils.ts
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#13236 fix(web): Service web suggested search not displaying results
  apps/web/components/ServiceWeb/SearchInput/SearchInput.tsx
Labels: automerge

#13202 feat(contentful-apps): Content import app
  apps/contentful-apps/components/content-import/ContentTypeSelect.tsx
  apps/contentful-apps/components/content-import/FileDataTable.tsx
  apps/contentful-apps/components/content-import/FileInput.tsx
  apps/contentful-apps/components/content-import/PrimitiveFieldMapping.tsx
  apps/contentful-apps/components/content-import/ReferenceFieldMapping.tsx
  apps/contentful-apps/components/content-import/TagSelect.tsx
  apps/contentful-apps/components/content-import/index.ts
  apps/contentful-apps/components/content-import/utils.ts
  apps/contentful-apps/constants/index.ts
  apps/contentful-apps/hooks/useContentTypeData.ts
  apps/contentful-apps/next.config.js
  apps/contentful-apps/pages/screens/content-import-screen.tsx
  apps/contentful-apps/utils/index.ts
Labels: automerge

#13246 fix(fa): Unit test for new tax numbers and old pension
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
Labels: automerge, merge.priority_merge_label

#13239 fix(parental-leave): Fixed error in provideChildren when adoption
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts
Labels: automerge

#13176 fix(intellectual-properties): Fix ip pages
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/mapper.ts
  libs/api/domains/intellectual-properties/src/lib/models/category.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/classification.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/design.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/imageList.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/media.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/patent.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/pct.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/person.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/priority.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/trademark.model.ts
  libs/api/domains/intellectual-properties/src/lib/models/utils.ts
  libs/api/domains/intellectual-properties/src/lib/tests/mapper.test.ts
  libs/api/domains/intellectual-properties/src/lib/tests/util.test.ts
  libs/api/domains/intellectual-properties/src/lib/utils.ts
  libs/clients/intellectual-properties/src/clientConfig.json
  libs/service-portal/assets/src/components/Image/Image.tsx
  libs/service-portal/assets/src/components/Timeline/Timeline.tsx
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/lib/navigation.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesDesignDetail/IntellectualPropertiesDesignDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesTrademarkDetail/IntellectualPropertiesTrademarkDetail.tsx
  libs/service-portal/assets/src/utils/makeArrayEven.ts
  libs/service-portal/assets/src/utils/timelineMapper.ts
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#13219 feat(license-client): Move passport to license client
  libs/api/domains/license-service/src/lib/graphql/genericLicense.model.ts
  libs/api/domains/license-service/src/lib/graphql/main.resolver.ts
  libs/api/domains/license-service/src/lib/licenceService.type.ts
  libs/api/domains/license-service/src/lib/licenseService.module.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/api/domains/license-service/src/lib/mappers/passportMapper.ts
  libs/clients/license-client/src/lib/clients/passport-client/index.ts
  libs/clients/license-client/src/lib/clients/passport-client/passportsClient.module.ts
  libs/clients/license-client/src/lib/clients/passport-client/passportsClient.service.ts
  libs/clients/license-client/src/lib/licenseClient.type.ts
  libs/clients/national-registry/v3/src/lib/nationalRegistryV3.service.ts
  libs/clients/passports/src/index.ts
Labels: automerge

#12728 chore(ids-api): Add nx targets for ids development.
  apps/services/auth/ids-api/project.json
  apps/services/auth/ids-api/src/environments/environment.ts
  apps/services/user-profile/src/environments/environment.ts
Labels: automerge

#13252 fix(j-s): Side stepper bug
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#13247 fix(web): Add failsafe for when service web organization footer is empty
  apps/web/components/ServiceWeb/DynamicFooter/DynamicFooter.tsx
Labels: automerge

#13262 fix(parental-leave): Fixed error in provideChildren when adoption
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/children/children.service.ts
Labels: automerge

#13251 fix(service-portal): Sp updates signaturecollection
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/SignatureLists/index.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/signeeView.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/paperUpload.tsx
  libs/service-portal/signature-collection/src/screens/ViewList/signees.tsx
  libs/service-portal/signature-collection/src/screens/hooks.ts
  libs/service-portal/signature-collection/src/screens/mutations.ts
Labels: automerge

#13253 feat(ids-api): Adding a collection endpoint for login restrictions.
  apps/services/auth/ids-api/src/app/login-restrictions/login-restrictions.controller.spec.ts
  apps/services/auth/ids-api/src/app/login-restrictions/login-restrictions.controller.ts
Labels: automerge

#13206 fix(auth-admin): Publish super admin fields
  apps/services/auth/admin-api/src/app/v2/clients/test/me-clients.spec.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
Labels: automerge

#13106 fix(signature-collection): scope service portal
  apps/service-portal/src/auth.ts
  libs/auth/scopes/src/lib/api.scope.ts
Labels: automerge

#13223 feat(fa): Allowing employees to change rejection and data needed text
  apps/financial-aid/backend/src/app/modules/application/application.service.ts
  apps/financial-aid/web-veita/src/components/InputModal/InputModal.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/EmailFormatInputModal.tsx
  apps/financial-aid/web-veita/src/components/ModalTypes/ModalTypes.css.ts
  apps/financial-aid/web-veita/src/components/ProfileUnit/Unit.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
  libs/financial-aid/shared/src/lib/formatters.ts
Labels: automerge

#13257 fix(service-portal): Update period export to export all details
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsFilter.tsx
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTypes.ts
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionSelectedPeriod.tsx
  libs/service-portal/finance/src/utils/filesPeriodBreakdown.ts
Labels: automerge

#13258 chore: Add workmachines to application-system-api
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13203 fix(social-insurance-administration): Moved shared sia messages to core
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
  libs/application/templates/social-insurance-administration/core/project.json
  libs/application/templates/social-insurance-administration/core/src/index.ts
  libs/application/templates/social-insurance-administration/core/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/core/src/lib/socialInsuranceAdministrationUtils.spec.ts
  libs/application/templates/social-insurance-administration/core/src/lib/socialInsuranceAdministrationUtils.ts
  libs/application/templates/social-insurance-administration/core/src/messages.ts
  libs/application/templates/social-insurance-administration/core/src/types.ts
  libs/application/templates/social-insurance-administration/household-supplement/README.md
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Payment.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.spec.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/answerValidationSections/fileUploadValidationSection.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.spec.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/README.md
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/EmployersOverview/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/EmployersRatioMonthly/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/PaymentInformation.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/fileUpload.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/period.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidators.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidators.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.spec.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#13260 fix(application-ctoa): Minor bugs in overview screen and strings
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintInformation.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complainedFor.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complainee.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintDescription.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/complaintInformation.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/dataProvider.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/preexistingComplaint.ts
Labels: automerge

#13256 fix(skilavottord): Add back IdsUserGuard
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
Labels: automerge

#13143 fix(application-system-worker): Fix error logging
  apps/application-system/api/src/app/modules/application/application.module.ts
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.service.ts
  apps/application-system/form/src/routes/Applications.tsx
  libs/application/api/files/src/lib/files.module.ts
Labels: automerge, deploy-feature, stale

#13259 feat(web): Redirect /en/o/icelandic-health-insurance to /en/o/iceland-health
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/config.ts
  apps/web/components/ServiceWeb/types.ts
  apps/web/next.config.js
  apps/web/screens/ServiceWeb/Forms/utils.ts
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
  libs/api/domains/content-search/src/lib/contentSearch.resolver.ts
  libs/cms/src/lib/cms.resolver.ts
Labels: automerge

#13213 fix(estate): properly validate estatemembers
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/fields/LookupPerson/index.tsx
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/estate/src/types.ts
Labels: automerge, deploy-feature

#13248 fix(energy-fund): Extra validation on submit
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
Labels: automerge

#13250 fix(university-gateway): Update contentful name
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
Labels: automerge

#13266 fix(energy-fund): adding import code
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleCheckboxField.tsx
  libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleSelectField.tsx
  libs/application/templates/energy-funds/src/lib/dataSchema.ts
Labels: automerge

#13268 fix(energy-fund): adding import code
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleCheckboxField.tsx
  libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleSelectField.tsx
  libs/application/templates/energy-funds/src/lib/dataSchema.ts
Labels: automerge

#13255 fix(car-recycling): Move create owner to send application
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
  libs/application/templates/car-recycling/src/shared/constants.ts
Labels: automerge

#13267 fix(skilavottord): Add back IdsUserGuard (#13256)
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
Labels: automerge

#13261 fix(sgs): Changed CategoryCard to ActionCard in sgs forms
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/license-plate-renewal/src/fields/PlateField/PlateSelectField.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/VehicleSelectField.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/VehicleSelectField.tsx
Labels: automerge

#13269 fix(estate): properly validate estatemembers (#13213)
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
  libs/application/templates/estate/src/fields/LookupPerson/index.tsx
  libs/application/templates/estate/src/lib/constants.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/estate/src/types.ts
Labels: automerge

#13244 fix(skilavottord): Move mileage field to deregister page and remove dead code
  apps/skilavottord/web/pages/deregister-vehicle-km/[id].tsx
  apps/skilavottord/web/pages/deregister-vehicle-km/index.ts
  apps/skilavottord/web/pages/deregister-vehicle-km/select.tsx
  apps/skilavottord/web/pages/en/deregister-vehicle-km/[id].tsx
  apps/skilavottord/web/pages/en/deregister-vehicle-km/index.ts
  apps/skilavottord/web/pages/en/deregister-vehicle-km/select.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Confirm/ConfirmKM.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/index.ts
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/index.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Select.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/index.tsx
  apps/skilavottord/web/screens/index.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwnerAppSys.resolver.ts
Labels: automerge

#13270 chore(web): Add default translations to service web search
  apps/web/components/ServiceWeb/Header/Header.tsx
  apps/web/components/ServiceWeb/SearchSection/SearchSection.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
Labels: automerge

#13263 fix(j-s): Redirect Unauthenticated User
  apps/judicial-system/web-e2e/src/integration/Prosecutor/Indictments/defendant.spec.ts
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
Labels: automerge

#13272 fix(skilavottord): Move mileage field to deregister page and remove test code (#13244)
  apps/skilavottord/web/pages/deregister-vehicle-km/[id].tsx
  apps/skilavottord/web/pages/deregister-vehicle-km/index.ts
  apps/skilavottord/web/pages/deregister-vehicle-km/select.tsx
  apps/skilavottord/web/pages/en/deregister-vehicle-km/[id].tsx
  apps/skilavottord/web/pages/en/deregister-vehicle-km/index.ts
  apps/skilavottord/web/pages/en/deregister-vehicle-km/select.tsx
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Confirm/ConfirmKM.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/Overview.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/CarsTable.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/components/CarsTable/index.ts
  apps/skilavottord/web/screens/DeregisterVehicleKm/Overview/index.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/Select.tsx
  apps/skilavottord/web/screens/DeregisterVehicleKm/index.tsx
  apps/skilavottord/web/screens/index.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwnerAppSys.resolver.ts
Labels: automerge

#13198 fix(signature-colleciton): Sign list tweaks
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Draft.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
  libs/application/ui-shell/src/components/FormExternalDataProvider.tsx
Labels: automerge

#13275 fix(signature-collection): text tweaks
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
Labels: automerge

#13277 fix(vehicles): User is only editing if origincode comes from island.is
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Labels: automerge

#13280 fix(service-portal): hotfix - Vehicle mileage editing mode
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
Labels: automerge

#13144 feat(j-s): Request appeal ruling not to be made public
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20231219145053-update-case.js
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/RequestAppealRulingNotToBePublishedCheckbox/RequestAppealRulingNotToBePublishedCheckbox.strings.ts
  apps/judicial-system/web/src/components/RequestAppealRulingNotToBePublishedCheckbox/RequestAppealRulingNotToBePublishedCheckbox.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.spec.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/components/CaseOverviewHeader/CaseOverviewHeader.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealCaseFiles.spec.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealCaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.spec.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.strings.ts
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  apps/judicial-system/web/src/utils/mocks.ts
  apps/judicial-system/web/src/utils/testHelpers.tsx
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#13276 feat(singature-collection): max reached check
  libs/api/domains/signature-collection/src/lib/models/area.model.ts
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/clients/signature-collection/src/lib/types/area.dto.ts
  libs/clients/signature-collection/src/lib/types/bulkUpload.dto.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
  libs/clients/signature-collection/src/lib/types/signature.dto.ts
Labels: automerge

#13278 feat(social-insurance-administration): Add file upload shared props to constants in sia core
  libs/application/templates/social-insurance-administration/core/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
Labels: automerge

#13282 fix(j-s): Unauthenticated Redirect
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
Labels: automerge

#13285 chore(web): Remove grindavik chat
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Project/components/ProjectChatPanel/config.ts
Labels: automerge

#13271 fix(contentful-apps): Prevent subarticle entry from being saved during initial render
  apps/contentful-apps/pages/fields/subarticle-url-field.tsx
Labels: automerge

#13288 fix(service-portal): read date today
  libs/service-portal/assets/src/utils/readDate.ts
Labels: automerge

#13289 fix(service-portal): Hotfix - Read date validation mileage input
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
  libs/service-portal/assets/src/utils/readDate.ts
Labels: automerge

#13291 fix(university-gateway): page renaming for routing issues
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/haskolanam-temp/[id]/index.tsx
  apps/web/pages/haskolanam-temp/index.tsx
  apps/web/pages/haskolanam-temp/leit.tsx
  apps/web/pages/haskolanam-temp/samanburdur.tsx
Labels: automerge

#13294 fix(skilavottord): Fix idsUserGuard for dev and improve loggers
  apps/skilavottord/web/screens/DeregisterVehicle/Confirm/Confirm.tsx
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequestAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicle/vehicleAppSys.resolver.ts
  apps/skilavottord/ws/src/app/modules/vehicleOwner/vehicleOwnerAppSys.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
Labels: automerge

#13293 test(j-s): Fix missing file change
  apps/system-e2e/src/support/api-tools.ts
Labels: automerge

#13299 fix(signature-collection): build fix
  libs/portals/admin/signature-collection/src/screens/AllLists/getAllSignatureLists.graphql
  libs/portals/admin/signature-collection/src/screens/List/getSignatureList.graphql
Labels: automerge, high priority

#13303 fix(web): Add Hyphen component around vacancy card title
  apps/web/screens/IcelandicGovernmentInstitutionVacancies/IcelandicGovernmentInstitutionVacanciesList.tsx
Labels: automerge

#13273 feat(service-portal): Add vehicle list v3
  libs/api/domains/vehicles/src/dto/getVehiclesForUserInput.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/assets/src/components/VehicleCard.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.graphql
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
Labels: automerge

#13302 test(j-s): Use pdf buffer for appeal files
  apps/system-e2e/src/tests/judicial-system/smoke/TestAppeal.pdf
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#13306 feature(energy-fund): Contentful update
  libs/application/templates/energy-funds/src/lib/dataSchema.ts
  libs/application/templates/energy-funds/src/lib/messages/error.ts
Labels: automerge

#13307 feat(energy-fund): Contentful update release
  libs/application/templates/energy-funds/src/lib/dataSchema.ts
  libs/application/templates/energy-funds/src/lib/messages/error.ts
Labels: automerge

#13301 chore(j-s): Log Levels
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealFilesUpdatedNotifications.spec.ts
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#13304 fix(estate): hide contact info for under 18
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
Labels: automerge

#13308 feat(inheritance-report): add cards component to overviews
  libs/application/templates/inheritance-report/src/fields/Cards/index.tsx
  libs/application/templates/inheritance-report/src/fields/NotFilledOut/index.tsx
  libs/application/templates/inheritance-report/src/fields/index.ts
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/forms/sections/business.ts
  libs/application/templates/inheritance-report/src/forms/sections/debts.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13311 feat(service-portal): Add vehicle list v3 (hotfix)
  libs/api/domains/vehicles/src/dto/getVehiclesForUserInput.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/usersVehicles.model.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/assets/src/components/VehicleCard.tsx
  libs/service-portal/assets/src/screens/Overview/Overview.graphql
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
Labels: automerge

#13305 fix(j-s): Parent Case File query
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#13286 fix(j-s): Deprecated auth redirect
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/web/messages/Core/login.ts
  apps/judicial-system/web/src/routes/Shared/Login/Login.tsx
  apps/judicial-system/web/src/types/index.ts
Labels: automerge

#13312 feat(web): Add ISK postfix for non icelandic price locales
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
Labels: automerge

#13318 chore(search-indexer): Skip logging if no entries are being mapped
  libs/cms/src/lib/search/importers/adgerdirPage.ts
  libs/cms/src/lib/search/importers/anchorPage.service.ts
  libs/cms/src/lib/search/importers/article.service.ts
  libs/cms/src/lib/search/importers/articleCategory.service.ts
  libs/cms/src/lib/search/importers/enhancedAsset.service.ts
  libs/cms/src/lib/search/importers/event.service.ts
  libs/cms/src/lib/search/importers/frontpage.service.ts
  libs/cms/src/lib/search/importers/groupedMenu.service.ts
  libs/cms/src/lib/search/importers/link.service.ts
  libs/cms/src/lib/search/importers/manual.service.ts
  libs/cms/src/lib/search/importers/manualChapterItem.service.ts
  libs/cms/src/lib/search/importers/menu.service.ts
  libs/cms/src/lib/search/importers/news.service.ts
  libs/cms/src/lib/search/importers/organizationPage.service.ts
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
  libs/cms/src/lib/search/importers/projectPage.service.ts
  libs/cms/src/lib/search/importers/serviceWebPage.service.ts
  libs/cms/src/lib/search/importers/subArticle.service.ts
  libs/cms/src/lib/search/importers/supportQNA.service.ts
Labels: automerge

#13292 fix(signature-collection): admin scope and isDigital
  libs/api/domains/signature-collection/src/lib/models/signature.model.ts
  libs/auth/scopes/src/lib/admin-portal.scope.ts
  libs/clients/signature-collection/src/lib/types/signature.dto.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/compareLists.graphql
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/paperUpload.graphql
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/getListSignees.graphql
  libs/service-portal/signature-collection/src/screens/queries.ts
Labels: automerge

#13317 fix(service-portal): Update position for header nav in desktop
  apps/service-portal/src/components/Header/Header.tsx
  apps/service-portal/src/components/Sidemenu/Sidemenu.tsx
Labels: automerge

#13316 test(j-s): Search Warrant
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/search-warrant-tests.spec.ts
Labels: automerge

#13254 feat(j-s): Improve case file UI
  apps/judicial-system/web/src/components/AccordionItems/CaseFilesAccordionItem/CaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/CaseFile/CaseFile.css.ts
  apps/judicial-system/web/src/components/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/components/CaseFileList/CaseFileList.tsx
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.css.ts
  apps/judicial-system/web/src/components/CourtDocuments/CourtDocuments.tsx
  apps/judicial-system/web/src/components/IconButton/IconButton.css.ts
  apps/judicial-system/web/src/components/IconButton/IconButton.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/utils/stepHelper.ts
Labels: automerge

#13327 chore(inheritance-report): add information section
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/sections/applicationInfo.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#13322 fix(estate): make adding representative optional
  libs/application/templates/estate/src/lib/dataSchema.ts
Labels: automerge

#13310 fix(signature-collection): Signature collection testing & fixes
  libs/application/templates/signature-collection/assets/Illustration.tsx
  libs/application/templates/signature-collection/signature-list-creation/src/fields/ListCreated/index.tsx
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/errors.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Done.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Draft.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/service-portal/signature-collection/src/hooks/graphql/mutations.ts
  libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/module.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/CancelCollection/index.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/signees.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
  libs/service-portal/signature-collection/src/screens/SignatureLists/signeeView.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
  libs/service-portal/signature-collection/src/screens/index.tsx
  libs/service-portal/signature-collection/src/screens/skeletons.tsx
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
Labels: automerge

#13328 fix(j-s): Fix overflowing DateTime component
  apps/judicial-system/web/src/components/DateTime/DateTime.css.ts
Labels: automerge

#13333 fix(signature-collection): extendDeadline success
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/extendDeadline.graphql
  libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx
Labels: automerge

#13325 chore(application-inheritance-report): Expand dataset for consistency
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/fakeData.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/filters.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
Labels: automerge

#13313 test(j-s): Temp fix for dev e2e tests
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#13309 feat(University-Gateway): Minor updates to worker
  apps/services/university-gateway/src/app/modules/course/internalCourse.service.ts
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
  infra/src/uber-charts/islandis.ts
Labels: automerge

#13320 feat(j-s): Sort active cases by court date and save sort to local storage
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
Labels: automerge

#13321 chore(service-portal): Add detail to health cert card
  libs/service-portal/occupational-licenses/src/screens/OccupationalLicensesOverview/OccupationalLicensesOverview.tsx
Labels: automerge

#13332 fix(regulations): Add enhanced fetch to regulation external service
  libs/clients/regulations/src/lib/regulations.service.ts
  libs/clients/regulations/src/lib/regulations.spec.ts
Labels: automerge

#13331 fix(estate): remove fraction got stock facevalue
  libs/application/templates/estate/src/fields/TextFieldsRepeater/index.tsx
  libs/application/templates/estate/src/forms/Sections/estateAssets.ts
Labels: automerge

#13343 fix(old-age-pension): Change text and add markdown
  libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
Labels: automerge

#13338 fix(inheritance-report): remove repeater for other assets
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
Labels: automerge

#13344 fix(admin-portal): Uppfæra signee lista on bulk upload
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
Labels: automerge

#13295 feat(applicaton-ctoa): Previous complaint section
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/pdfGenerators/templates/complaint.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/forms/ComplaintsToAlthingiOmbudsmanApplication.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/attachments.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/courtAction.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/index.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/overview.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/previousOmbudsmanComplaint.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/messages/section.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/utils.ts
Labels: automerge

#13347 fix(service-portal): Currently processing med certificate
  libs/service-portal/health/src/screens/Medicine/MedicineLicense.tsx
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
Labels: automerge

#13337 chore(j-s): Implement tests for a search warrant on the court side
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/system-e2e/src/tests/judicial-system/smoke/search-warrant-tests.spec.ts
Labels: automerge

#13339 feat(j-s): Prosecutor appeal SMS notifications
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealReceivedByCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendAppealToCourtOfAppealsNotifications.spec.ts
Labels: automerge

#13350 fix(admin-portal): Admin unsign functionality
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/removeSignatureFromList.graphql
Labels: automerge

#13324 feat(j-s): Added a appealRulingDecision option
  apps/judicial-system/backend/migrations/20240109205756-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/web/messages/Core/appealRuling.ts
  apps/judicial-system/web/src/components/TagAppealState/TagAppealState.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useStringHelpers/useStringHelpers.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#13345 chore(inheritance-report): sync ir debt screen look with estate application
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/form.ts
  libs/application/templates/inheritance-report/src/forms/sections/business.ts
  libs/application/templates/inheritance-report/src/forms/sections/debts.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13353 fix(admin-portal): texts
  libs/portals/admin/signature-collection/project.json
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/completeReview/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
Labels: automerge

#13354 fix(application-shared-api): National Registry Service Synchronicity
  libs/application/template-api-modules/src/lib/modules/shared/api/national-registry/national-registry.service.ts
Labels: automerge

#13352 fix(signature-collection): update application slug
  libs/application/templates/signature-collection/signature-list-creation/src/lib/messages.ts
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
Labels: automerge

#13359 feat(crc): Move prerequisites to it's own state and update prune times
  libs/application/templates/family-matters/children-residence-change-v2/src/forms/ChildrenResidenceChangeForm.ts
  libs/application/templates/family-matters/children-residence-change-v2/src/forms/PrerequisitesForm.ts
  libs/application/templates/family-matters/children-residence-change-v2/src/lib/ChildrenResidenceChangeTemplate.ts
  libs/application/templates/family-matters/children-residence-change-v2/src/lib/constants.ts
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#13360 fix(web): signature collection query fix
  libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts
Labels: automerge

#13364 fix(service-portal): Use overview url as fallback for detailurl
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
Labels: automerge

#13365 fix(service-portal): Overview fallback url Hotfix
  libs/service-portal/documents/src/components/DocumentRenderer/DocumentRenderer.tsx
Labels: automerge

#13357 test(j-s): Search warrant e2e final steps
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/restriction-case.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/search-warrant-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/shared-steps/complete-appeal.ts
  apps/system-e2e/src/tests/judicial-system/smoke/shared-steps/receive-appeal.ts
  apps/system-e2e/src/tests/judicial-system/smoke/shared-steps/send-appeal.ts
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#13358 feat(j-s): Add prosecutors, judges and registrar's emails to info cards
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/MarkdownWrapper/MarkdownWrapper.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#13336 feat(pension supplement): new application
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration.service.ts
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/social-insurance-administration/core/babel-jest.config.json
  libs/application/templates/social-insurance-administration/core/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/pension-supplement/.babelrc
  libs/application/templates/social-insurance-administration/pension-supplement/.eslintrc.json
  libs/application/templates/social-insurance-administration/pension-supplement/README.md
  libs/application/templates/social-insurance-administration/pension-supplement/jest.config.js
  libs/application/templates/social-insurance-administration/pension-supplement/project.json
  libs/application/templates/social-insurance-administration/pension-supplement/src/assets/pension-supplement-flow-chart.drawio
  libs/application/templates/social-insurance-administration/pension-supplement/src/assets/pension-supplement-flow-chart.png
  libs/application/templates/social-insurance-administration/pension-supplement/src/dataProviders/index.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/ApplicationReason.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/Attachments.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/Comment.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/Payment.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/Period.tsx
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/Review/review-groups/props.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/fields/index.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/InReview.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/PensionSupplementForm.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/index.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.spec.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/PensionSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/pensionSupplementUtils.spec.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/lib/pensionSupplementUtils.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/types.ts
  libs/application/templates/social-insurance-administration/pension-supplement/tsconfig.json
  libs/application/templates/social-insurance-administration/pension-supplement/tsconfig.lib.json
  libs/application/templates/social-insurance-administration/pension-supplement/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/institutionMapper.ts
  libs/clients/social-insurance-administration/src/clientConfig.yaml
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge, deploy-feature

#13370 fix(signature-collection): pagenumber, candidates in collection and listname for compare all
  libs/api/domains/signature-collection/src/lib/models/collection.model.ts
  libs/api/domains/signature-collection/src/lib/models/signature.model.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/clients/signature-collection/src/lib/types/signature.dto.ts
Labels: automerge

#13013 feat(user-notification): Send email in notification worker
  apps/api/src/app/app.module.ts
  apps/services/user-notification/infra/user-notification.ts
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/dto/createHnippNotification.dto.ts
  apps/services/user-notification/src/app/modules/notifications/dto/hnippTemplate.response.ts
  apps/services/user-notification/src/app/modules/notifications/messageProcessor.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationDispatch.service.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.controller.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
  apps/services/user-notification/src/assets/images/logo.jpg
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-profile/src/app/v2/test/user-token.controller.spec.ts
  apps/services/user-profile/src/app/v2/user-profile.controller.ts
  apps/services/user-profile/src/app/v2/user-profile.module.ts
  apps/services/user-profile/src/app/v2/userToken.controller.ts
  apps/services/user-profile/src/app/v2/userToken.service.ts
  apps/services/user-profile/test/fixture-factory.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/auth-nest-tools/src/lib/scopes.guard.ts
  libs/clients/national-registry/v3/src/lib/apiConfig.ts
  libs/clients/user-profile/src/lib/apiConfiguration.ts
  libs/clients/user-profile/src/lib/apis.ts
  libs/clients/user-profile/src/lib/userProfileClient.config.ts
  libs/email-service/src/tools/design/styles.hbs
  libs/email-service/src/tools/design/textwithlink.hbs
  libs/email-service/src/types/index.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#13346 chore(shared): Change max-age to 15 instead of 30 seconds
  libs/shared/constants/src/lib/cacheControl.ts
Labels: automerge

#13351 chore(estate): change overview checkbox to markdown
  libs/application/templates/estate/src/forms/OverviewSections/confirmAction.ts
  libs/application/templates/estate/src/lib/messages.ts
Labels: automerge

#13356 feat(testing): Make testing with podman plug'n play
  .env.podman
  .envrc
  .gitignore
Labels: automerge

#13368 fix(ci): Add application-system-api to list of long-running test job
  scripts/ci/_chunk.js
Labels: automerge

#13361 feat(old-age-pension): Remove spouse
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
Labels: automerge

#13374 fix(old-age-pension-and-household-supplement): remove file upload validation
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/dataSchema.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/answerValidationSections/fileUpload.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/dataSchema.ts
Labels: automerge

#13376 feat(household-suppliment): Add applicant and spouse info
  libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/HouseholdSupplementTemplate.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/lib/householdSupplementUtils.ts
Labels: automerge

#13355 fix(utlendingastofnun): small fixes after testing
  libs/application/template-api-modules/src/lib/modules/templates/directorate-of-immigration/citizenship/citizenship.service.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/ResidenceCountries/ResidenceCountriesRepeaterItem.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/ResidenceCountries/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/SelectedChildrenExtra/SelectedRepeaterItem.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/dataSchema.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/supportingDocuments.ts
  libs/clients/directorate-of-immigration/src/clientConfig.json
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.service.ts
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.types.ts
Labels: automerge

#13366 fix(admin-portal): Signature collection admin create list
  libs/api/domains/signature-collection/src/lib/models/signee.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/compareLists.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/components/createCollection/candidateLookup.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/createCollection/createCollection.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/createCollection/getCurrentCollection.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/createCollection/index.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/components/createCollection/utils.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/getListSignees.graphql
Labels: automerge

#13373 ci: add clientconfig to hash
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#13319 feat(half-old-age-pension): apply for half old-age pension
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/social-insurance-administration/social-insurance-administration-utils.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/fields/EmployersRatioMonthly/index.tsx
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/OldAgePensionTemplate.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/oldAgePensionUtils.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/types.ts
  libs/clients/social-insurance-administration/src/clientConfig.yaml
Labels: automerge, deploy-feature

#13007 feat(health-insurance): Update outdated sjúkratryggingar logo
  libs/application/templates/accident-notification/src/assets/Logo.tsx
  libs/application/templates/health-insurance/src/assets/Logo.tsx
Labels: automerge

#13384 fix(j-s): pathname redirect bug
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
Labels: automerge

#13372 refactor(inheritance-report): update total functionality
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
Labels: automerge, deploy-feature

#13379 fix(web): sc current collection
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/shared/connected/src/lib/SignatureLists/SignatureLists.tsx
  libs/shared/connected/src/lib/SignatureLists/useGetSignatureLists.ts
Labels: automerge, deploy-feature

#13386 fix(tr): Text changes and misc fixes
  libs/application/templates/social-insurance-administration/core/src/lib/constants.ts
  libs/application/templates/social-insurance-administration/core/src/lib/messages.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
Labels: automerge

#13383 feat(web): Allow overriding footer items on service web
  apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  apps/web/screens/queries/ServiceWeb.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/serviceWebPage.model.ts
Labels: automerge

#13385 feat(web): Change chat config for 'ad-eldast' life event
  apps/web/screens/LifeEventPage/LifeEventPage.tsx
  apps/web/screens/LifeEventPage/config.ts
Labels: automerge

#13387 fix(web): life events indexer missing typename
  libs/cms/src/lib/search/importers/lifeEventPage.service.ts
Labels: automerge

#13381 feat(services-user-profile): Create user profile worker infra definition
  apps/services/user-profile/infra/service-portal-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#13389 fix(tr): change period section title
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/AdditionalSupportForTheElderlyForm.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/Prerequisites.ts
Labels: automerge

#13390 fix(utlendingastofnun): File upload accept updated
  libs/application/templates/directorate-of-immigration/citizenship/src/fields/CriminalRecords/index.tsx
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenOtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/ChildrenSupportingDocuments/ChildrenPassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/OtherDocumentsSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/forms/CitizenshipForm/SupportingDocumentsSection/PassportSubSection.ts
  libs/application/templates/directorate-of-immigration/citizenship/src/shared/constants.ts
Labels: automerge

#13388 fix(service-portal): sc tweak for signee empty
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
Labels: automerge

#13391 fix(ChangeMachineSupervisor): Adding feature flag for changeMachineSupervisor application
  libs/application/templates/aosh/change-machine-supervisor/src/lib/ChangeMachineSupervisorTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#13394 fix(ids-api): Making the user profile scope optional to not break service startup
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/clients/user-profile/src/lib/userProfileClient.config.ts
Labels: automerge, high priority

#13392 fix(energy-fund): addressing possible race condition
  libs/application/template-api-modules/src/lib/modules/templates/energy-funds/energy-funds.service.ts
  libs/application/templates/energy-funds/src/fields/SelectVehicle/VehicleCheckboxField.tsx
Labels: automerge

#13398 fix(user-notification): Fixing infra vars for NationalRegistry v3 client.
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#13401 fix(user-notification): Fixing infra vars for NationalRegistry v3 client
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#13402 fix(changemachinesupervisor): Adding feature flag for changeMachineSupervisor application
  libs/application/templates/aosh/change-machine-supervisor/src/lib/ChangeMachineSupervisorTemplate.ts
  libs/feature-flags/src/lib/features.ts
Labels: automerge

#13404 fix(user-notification): Adding NatReg B2C secret env var.
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#13405 fix(user-notification): Adding NatReg B2C secret env var. (#13404)
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge, high priority

#13369 feat(search-indexer): Invalidate graphql api redis cache on content changes
  apps/services/search-indexer/infra/search-indexer-service.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/content-search/src/lib/enums/searchableContentTypes.ts
  libs/cms/src/lib/search/contentful.service.ts
  libs/cms/src/lib/search/importers/event.service.ts
  libs/cms/src/lib/search/importers/lifeEventPage.service.ts
  libs/cms/src/lib/search/importers/manual.service.ts
  libs/cms/src/lib/search/importers/manualChapterItem.service.ts
  libs/cms/src/lib/search/importers/subArticle.service.ts
  libs/cms/src/lib/search/importers/vacancy.service.ts
  libs/content-search-indexer/src/environments/environment.ts
  libs/content-search-indexer/src/lib/cache-invalidation.service.ts
  libs/content-search-indexer/src/lib/indexing.module.ts
  libs/content-search-indexer/src/lib/indexing.service.ts
  libs/shared/types/src/index.ts
  libs/shared/types/src/lib/searchable-content-types.ts
Labels: automerge

#13408 fix(user-notifications): Hotfix user notification infra
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#13400 feat(contentful-apps): Add instance variable to Miðeind translation contentful app
  apps/contentful-apps/components/MideindTranslationSidebar/MideindTranslationSidebar.tsx
  apps/contentful-apps/components/MideindTranslationSidebar/api/index.tsx
  apps/contentful-apps/constants/index.ts
Labels: automerge

#13407 fix(user-notifications): Fix user profile client url env variable name in infra
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge, high priority

#13397 fix(energy-fund): Change to identity api
  libs/application/templates/energy-funds/src/dataProviders/index.ts
  libs/application/templates/energy-funds/src/forms/EnergyFundsForm/InformationSection/UserInformation.ts
  libs/application/templates/energy-funds/src/forms/Prerequisites/index.ts
  libs/application/templates/energy-funds/src/lib/EnergyFundsTemplate.tsx
Labels: automerge

#13403 fix(service-portal): Add health cert error and loading state
  libs/service-portal/health/src/screens/MedicineCertificate/MedicineCertificate.tsx
Labels: automerge

#13399 fix(service-portal): Lists nav for petitions and signature collections
  libs/application/templates/general-petition/src/fields/SignPetitionView/index.tsx
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Done.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/information/src/lib/navigation.ts
  libs/service-portal/information/src/lib/paths.ts
  libs/service-portal/petitions/src/lib/paths.ts
  libs/service-portal/petitions/src/module.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/service-portal/signature-collection/src/lib/paths.ts
  libs/service-portal/signature-collection/src/module.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/signees.tsx
Labels: automerge

#13410 fix(service-portal): adding tags to cards and minor fixes
  libs/application/templates/signature-collection/signature-list-creation/src/lib/errors.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/signees.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
Labels: automerge

#13414 fix(user-notifications): Add IDS client config env var for service infra
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13415 fix(user-notification): Add IDS client config env var for service infra.
  apps/services/user-notification/infra/user-notification.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13413 chore(CI): Cleanup & updates
  .github/actions/cache/action.yml
  .github/actions/change-detection.spec.ts
  .github/actions/dist/main.js
  .github/actions/package.json
  .github/actions/simple-git.ts
  .github/actions/unit-test/action.yml
  .github/actions/yarn.lock
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest-close.yml
  .github/workflows/pullrequest-lint.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  apps/github-actions-cache/README.md
Labels: automerge

#13409 chore(inheritance-report): add subtitles to heir section
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/heirs.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
Labels: automerge

#13411 fix(admin): using numberOfSignatures from list info
  libs/portals/admin/signature-collection/src/screens/List/components/signees.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
Labels: automerge
