Repository island-is/island.is, pull requests merged in 2024-02, with the labels that each got.

#13620 fix(web): Remove sidebarcards on organization subpages in mobile
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/screens/Organization/Home/Home.tsx
Labels: automerge

#13618 feat(parental-leave): Remove employer on review no employer
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/Review.css.ts
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#13642 fix(signature-collection): auth middleware on all
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-creation/signature-list-creation.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
Labels: automerge

#13607 fix(parental-leave): Refactor images components
  libs/application/templates/parental-leave/src/assets/Images/ManWithStrollerIllustration.tsx
  libs/application/templates/parental-leave/src/assets/Images/WomanWithLaptopIllustration.tsx
  libs/application/templates/parental-leave/src/assets/Images/WomanWithPhoneIllustration.tsx
  libs/application/templates/parental-leave/src/fields/ConclusionSectionImage/ConclusionImageScreen.css.ts
  libs/application/templates/parental-leave/src/fields/ConclusionSectionImage/ConclusionImageScreen.tsx
  libs/application/templates/parental-leave/src/fields/ImangeField/index.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/ManWithStrollerIllustration.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/PeriodsSectionImage.tsx
  libs/application/templates/parental-leave/src/fields/PeriodsSectionImage/WomanWithLaptopIllustration.tsx
  libs/application/templates/parental-leave/src/fields/UploadAdditionalFilesInfoScreen/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrant.ts
  libs/application/templates/parental-leave/src/forms/ResidenceGrantNoBirthDate.ts
Labels: automerge

#13643 fix(signature-collection): Sp signature collection updated UI
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Done.ts
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/CancelCollection/index.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/ViewList/index.tsx
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
Labels: automerge

#13625 chore(j-s): Refactor Cases list
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/components/ContextMenu/ContextMenu.css.ts
  apps/judicial-system/web/src/components/Modal/Modal.tsx
  apps/judicial-system/web/src/components/PageLayout/PageLayout.tsx
  apps/judicial-system/web/src/components/SharedPageLayout/SharedPageLayout.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
Labels: automerge

#13634 fix(client-statistics): Add overrideCacheControl to override GDrive Cache-Control header
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/statistics/src/lib/fetchConfig.ts
Labels: automerge

#13570 fix(parental-leave): Refactor union and private pension
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Payments.tsx
  libs/application/templates/parental-leave/src/fields/UsePrivatePensionFund/index.tsx
  libs/application/templates/parental-leave/src/fields/UseUnion/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/paymentsValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.spec.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13644 fix(consultation-portal): KAM-2095: Check if id is a number before querying the API
  apps/consultation-portal/pages/mal/[slug].tsx
Labels: automerge

#13645 fix(consultation-portal): KAM-2095: Check if id is a number before qu…
  apps/consultation-portal/pages/mal/[slug].tsx
Labels: automerge

#13636 chore(j-s): Test PDF
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#13647 feat(web): Add TableOfConents component for reusability
  apps/web/components/TableOfContents/TableOfContents.tsx
  apps/web/components/real.ts
  apps/web/screens/Organization/SubPage.tsx
  apps/web/screens/Project/Project.tsx
  libs/island-ui/core/src/lib/TableOfContents/TableOfContents.tsx
Labels: automerge

#13572 feat(j-s): Implement defendant plea
  apps/judicial-system/api/src/app/modules/defendant/dto/updateDefendant.input.ts
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240125165016-update-case.js
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/web/messages/Indictments/Prosecutor/processing.ts
  apps/judicial-system/web/messages/index.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.strings.ts
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.css.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/processing.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  apps/judicial-system/web/src/utils/stepHelper.ts
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#13653 chore(j-s): Police Case Number Prefix
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseNumbers/PoliceCaseNumbers.tsx
Labels: automerge

#13654 feat(parental-leave): Refactor EditOrAddEmployersAndPeriodsReview
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/Employers.tsx
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/index.tsx
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Employers.tsx
  libs/application/templates/parental-leave/src/fields/EditOrAddEmployersAndPeriodsReview/review-groups/Periods.tsx
Labels: automerge

#13651 fix(university-gateway): university application frontend
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/haskolanam/[id]/index.tsx
  apps/web/pages/haskolanam/index.tsx
  apps/web/pages/haskolanam/leit.tsx
  apps/web/pages/haskolanam/samanburdur.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.css.ts
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
Labels: automerge

#13655 feat(parental-leave): Add alert message to personal allowance
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#13639 feat(service-portal): add link to payments footer
  libs/service-portal/health/src/screens/Payments/wrapper/PaymentsWrapper.tsx
Labels: automerge

#13473 chore(vehicles): Add mileage option as number
  libs/api/domains/vehicles/src/dto/postVehicleMileageInput.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles-mileage.resolver.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/api/domains/vehicles/src/models/getVehicleMileage.model.ts
  libs/api/domains/vehicles/src/utils/helpers.ts
  libs/clients/vehicles-mileage/src/clientConfig.json
  libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.graphql
  libs/service-portal/assets/src/screens/VehicleDetail/VehicleDetail.tsx
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleDetail.graphql
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
  libs/service-portal/assets/src/utils/displayWithUnit.ts
Labels: automerge

#13659 feat: added PodDisruptionBudget support to DSL
  apps/air-discount-scheme/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/dsl.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/pdb.spec.ts
  infra/src/dsl/service-to-environment/pre-process-service.ts
  infra/src/dsl/types/charts.ts
  infra/src/dsl/types/input-types.ts
  infra/src/dsl/types/output-types.ts
Labels: automerge, deploy-feature

#13614 fix(auth-react): Promise needs to be awaited to handle error and trigger the error screen
  libs/auth/react/src/lib/auth/AuthProvider.spec.tsx
  libs/auth/react/src/lib/auth/AuthProvider.tsx
Labels: automerge

#13664 feat(university-gateway): Update worker schedule and add error resiliency
  apps/services/university-gateway/infra/university-gateway.ts
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
  charts/islandis/values.prod.yaml
Labels: automerge

#13662 fix(signature-collection): Add scope to admin
  libs/clients/signature-collection/src/lib/signature-collection.config.ts
Labels: automerge

#13668 chore(Codeowners): Remove Core as Codeowner of **/infra changes
  .github/CODEOWNERS
Labels: automerge

#13667 fix(clients-statistics): Update stale-while-revalidate lifetime to 14 days so we can use cache.
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/statistics/src/lib/fetchConfig.ts
Labels: automerge

#13671 fix(signature-collection): reverting scope
  libs/clients/signature-collection/src/lib/signature-collection.config.ts
Labels: automerge

#13672 fix(clients-statistics): Override cache-control to ignore cache headers from responses and follow client settings
  libs/clients/statistics/src/lib/fetchConfig.ts
Labels: automerge

#13670 infra: set PDB default value
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/.prettierrc
  infra/src/dsl/dsl.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/pdb.spec.ts
  infra/src/dsl/service-to-environment/pre-process-service.ts
Labels: automerge

#13665 feat(university-gateway): Update worker schedule and add error resiliency
  apps/services/university-gateway/infra/university-gateway.ts
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
  charts/islandis/values.prod.yaml
Labels: automerge

#13678 feat(web): Hotfix - Specific housing benefit calculator - display "5" and "6 or more" options for household member radio buttons
  apps/web/components/connected/HousingBenefitCalculator/SpecificHousingBenefitSupportCalculator.tsx
Labels: automerge

#13603 feat(user-notification): Scheduling simplified
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker.service.ts
Labels: automerge

#13673 fix(service-portal): xroad paths
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#13674 feat(web): Specific housing benefit calculator - display 5 and 6 or more options for household member radio buttons
  apps/web/components/connected/HousingBenefitCalculator/SpecificHousingBenefitSupportCalculator.tsx
Labels: automerge

#13660 fix(application-ctao): Xroad path
  .github/CODEOWNERS
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/clients/althingi-ombudsman/src/lib/clients-althingi-ombudsman.config.ts
Labels: automerge

#13676 fix(signature-collection): list review confirmed UI text tweaks
  apps/portals/admin/src/lib/masterNavigation.ts
  libs/application/templates/signature-collection/signature-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/signature-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/messages.ts
  libs/auth-api-lib/seeders/data/scope-signature-collection.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/listReviewedAlert/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
Labels: automerge

#13613 feat(contentful-apps): Deploy contentful-apps on prod
  charts/islandis/values.prod.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#13679 fix(university-gateway): Update to university gateway frontend
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/pages/haskolanam/[id]/index.tsx
  apps/web/pages/haskolanam/index.tsx
  apps/web/pages/haskolanam/leit.tsx
  apps/web/pages/haskolanam/samanburdur.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.css.ts
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
Labels: automerge

#13680 fix(consultation-portal): KAM-2111: Show published date instead of created date on web
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
  apps/consultation-portal/types/interfaces.ts
  libs/api/domains/consultation-portal/src/lib/models/caseItemResult.model.ts
  libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#13684 fix(consultation-portal): Fix/kam2111
  apps/consultation-portal/graphql/queries.graphql.ts
  apps/consultation-portal/screens/Case/components/CaseOverview/CaseOverview.tsx
  apps/consultation-portal/screens/Home/components/Cards/Cards.tsx
  apps/consultation-portal/types/interfaces.ts
  libs/api/domains/consultation-portal/src/lib/models/caseItemResult.model.ts
  libs/api/domains/consultation-portal/src/lib/models/caseResult.model.ts
  libs/clients/consultation-portal/src/clientConfig.json
Labels: automerge

#13682 fix(core): Update @nestjs/sequelize to v10 to match our major NestJS version. Patch nestjs/terminus.
  .yarn/patches/@nestjs-terminus-npm-10.2.0-9e24c129e0.patch
  package.json
  yarn.lock
Labels: automerge, high priority

#13661 fix(p-sign): Application tweaks
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionInformation.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionOverview.ts
  libs/application/templates/p-sign/src/forms/applicationSections/sectionPhoto.ts
  libs/application/templates/p-sign/src/lib/messages.ts
  libs/application/templates/p-sign/src/lib/pSignTemplate.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.tsx
  libs/island-ui/core/src/lib/DatePicker/types.ts
  libs/shared/form-fields/src/lib/DatePickerController/DatePickerController.tsx
Labels: automerge

#13690 fix(university-gateway): changing reroute to haskolanam
  apps/web/next.config.js
  apps/web/screens/UniversitySearch/LandingPage.tsx
Labels: automerge

#13681 feat(service-portal): Add bulk mark as read option to inbox
  libs/api/domains/documents/src/lib/dto/postBulkMailActionInput.ts
  libs/clients/documents/src/lib/models/BulkMailActionDTO.ts
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/MailOpen.tsx
  libs/island-ui/core/src/lib/IconRC/icons/MailOpenOutline.tsx
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/documents/src/components/FavAndStash/index.tsx
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
Labels: automerge

#13683 feat(university-gateway): added client and xroad info for Bifröst
  apps/services/university-gateway/infra/university-gateway.ts
  apps/services/university-gateway/src/app/app.module.ts
  apps/services/university-gateway/src/app/modules/application/application.module.ts
  apps/services/university-gateway/src/app/modules/course/internalCourse.service.ts
  apps/services/university-gateway/src/app/modules/program/internalProgram.service.ts
  apps/services/university-gateway/src/app/worker/worker.module.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/university-application/bifrost-university/.eslintrc.json
  libs/clients/university-application/bifrost-university/README.md
  libs/clients/university-application/bifrost-university/jest.config.ts
  libs/clients/university-application/bifrost-university/project.json
  libs/clients/university-application/bifrost-university/src/clientConfig.yaml
  libs/clients/university-application/bifrost-university/src/index.ts
  libs/clients/university-application/bifrost-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.config.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.module.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.service.ts
  libs/clients/university-application/bifrost-university/tsconfig.json
  libs/clients/university-application/bifrost-university/tsconfig.lib.json
  libs/clients/university-application/bifrost-university/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#13617 feat(web): Watson assistant chat feedback
  apps/api/infra/api.ts
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.css.ts
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/WatsonChatPanel/types.ts
  apps/web/screens/queries/WatsonAssistantChat.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/watson-assistant-chat/src/lib/dto/identityToken.input.ts
  libs/api/domains/watson-assistant-chat/src/lib/dto/submitFeedback.input.ts
  libs/api/domains/watson-assistant-chat/src/lib/models/identityTokenResponse.ts
  libs/api/domains/watson-assistant-chat/src/lib/models/submitFeedbackResponse.ts
  libs/api/domains/watson-assistant-chat/src/lib/models/watsonAssistantChatIdentityTokenResponse.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.config.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.resolver.ts
  libs/api/domains/watson-assistant-chat/src/lib/watson-assistant-chat.service.ts
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/ThumbsDown.tsx
  libs/island-ui/core/src/lib/IconRC/icons/ThumbsDownOutline.tsx
  libs/island-ui/core/src/lib/IconRC/icons/ThumbsUp.tsx
  libs/island-ui/core/src/lib/IconRC/icons/ThumbsUpOutline.tsx
Labels: automerge

#13691 chore(auth-apis): Auth APIs readiness health check
  .yarn/patches/@nestjs-terminus-npm-10.2.0-9e24c129e0.patch
  apps/services/auth/admin-api/infra/auth-admin-api.ts
  apps/services/auth/delegation-api/infra/delegation-api.ts
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/personal-representative-public/infra/personal-representative-public.ts
  apps/services/auth/personal-representative/infra/personal-representative.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  yarn.lock
Labels: automerge

#13696 fix(university-gateway): show footer false
  apps/web/screens/UniversitySearch/LandingPage.tsx
Labels: automerge

#13689 feat(fa): Allowing admins to create and update api keys for api
  apps/financial-aid/api/src/app/app.module.ts
  apps/financial-aid/api/src/app/modules/apiKeys/apiKey.module.ts
  apps/financial-aid/api/src/app/modules/apiKeys/apiKey.resolver.ts
  apps/financial-aid/api/src/app/modules/apiKeys/dto/createApiKey.input.ts
  apps/financial-aid/api/src/app/modules/apiKeys/dto/index.ts
  apps/financial-aid/api/src/app/modules/apiKeys/dto/updateApiKey.input.ts
  apps/financial-aid/api/src/app/modules/apiKeys/index.ts
  apps/financial-aid/api/src/app/modules/apiKeys/models/apiKeys.model.ts
  apps/financial-aid/api/src/app/modules/apiKeys/models/index.ts
  apps/financial-aid/api/src/app/modules/index.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/app.module.ts
  apps/financial-aid/backend/src/app/guards/apiKey.guard.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.module.ts
  apps/financial-aid/backend/src/app/modules/municipality/municipality.service.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/dto/createApiKey.dto.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/dto/index.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.controller.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.module.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.service.ts
  apps/financial-aid/backend/src/environments/environment.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeyModal/CreateApiKeyModal.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeyModal/UpdateApiKeyModal.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeysSettings/ApiKeysInfo.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeysSettings/ApiKeysSettings.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  apps/financial-aid/web-veita/src/utils/useApiKeys.ts
  apps/financial-aid/web-veita/src/utils/useCurrentMunicipalityState.ts
  apps/financial-aid/web-veita/src/utils/useMunicipalities.ts
  libs/financial-aid/shared/src/lib/interfaces.ts
Labels: automerge

#13694 fix(university-gateway): show footer false
  apps/web/screens/UniversitySearch/LandingPage.tsx
Labels: automerge

#12991 feat(notifications): add notifications domain project
  .github/CODEOWNERS
  apps/api/src/app/app.module.ts
  apps/service-portal/src/auth.ts
  apps/services/user-notification/src/app/modules/notifications/dto/notification.dto.ts
  libs/api/domains/notifications/.eslintrc.json
  libs/api/domains/notifications/README.md
  libs/api/domains/notifications/jest.config.ts
  libs/api/domains/notifications/project.json
  libs/api/domains/notifications/src/index.ts
  libs/api/domains/notifications/src/lib/notifications.mock.service.ts
  libs/api/domains/notifications/src/lib/notifications.mock.ts
  libs/api/domains/notifications/src/lib/notifications.model.ts
  libs/api/domains/notifications/src/lib/notifications.module.ts
  libs/api/domains/notifications/src/lib/notifications.resolver.ts
  libs/api/domains/notifications/src/lib/notifications.service.ts
  libs/api/domains/notifications/src/utils/helpers.ts
  libs/api/domains/notifications/tsconfig.json
  libs/api/domains/notifications/tsconfig.lib.json
  libs/api/domains/notifications/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#13650 feat(service-portal): Add filter for mileage registration vehicles
  libs/api/domains/vehicles/src/dto/getVehiclesForUserInput.ts
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.service.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
Labels: automerge, deploy-feature

#13699 feat(web): Chat feedback, send url in payload
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  libs/api/domains/watson-assistant-chat/src/lib/dto/submitFeedback.input.ts
Labels: automerge

#13638 chore(service-portal): Add health overview scope
  apps/service-portal/src/auth.ts
  libs/api/domains/rights-portal/src/lib/overview/overview.resolver.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
Labels: automerge

#13698 fix(fa): Updating endpoint in api by adding municode
  apps/financial-aid/backend/src/app/guards/apiKey.guard.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.service.ts
  apps/financial-aid/open-api/src/app/app.controller.ts
  apps/financial-aid/open-api/src/app/app.service.ts
Labels: automerge

#13700 feat(service-portal): ip updates
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/mapper.ts
  libs/api/domains/intellectual-properties/src/lib/models/priority.model.ts
  libs/api/domains/intellectual-properties/src/lib/tests/mapper.test.ts
  libs/api/domains/intellectual-properties/tsconfig.json
  libs/service-portal/assets/src/components/StackWithBottomDivider/StackWithBottomDivider.tsx
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/IntellectualPropertiesPatentDetail.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/patentVariations/EP.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/patentVariations/IS.tsx
  libs/service-portal/assets/src/screens/IntellectualPropertiesPatentDetail/patentVariations/SPC.tsx
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#13706 feat(web): Add optional xAxisFormat field to Chart content model
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/chart.model.ts
Labels: automerge

#13685 feat(parental-leave): Refactor inReviewSteps and residence grant
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/fields/InReviewSteps/EditsInReviewSteps.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/ReviewSection/ReviewSection.css.ts
  libs/application/templates/parental-leave/src/fields/InReviewSteps/ReviewSection/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/EditsInReview.ts
  libs/application/templates/parental-leave/src/forms/InReview.ts
  libs/application/templates/parental-leave/src/forms/InReviewAdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.spec.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/utils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveTemplateUtils.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13703 fix(signature-collection): Adjusted view for "manage" scope
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/portals/admin/signature-collection/assets/electionsCommittee.svg
  libs/portals/admin/signature-collection/assets/headerImage.svg
  libs/portals/admin/signature-collection/assets/nationalRegistry.svg
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/module.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
Labels: automerge

#13705 feat(fa): Allowing in veita to delete api key
  apps/financial-aid/api/src/app/modules/apiKeys/apiKey.resolver.ts
  apps/financial-aid/api/src/app/modules/apiKeys/dto/deleteApiKey.input.ts
  apps/financial-aid/api/src/app/modules/apiKeys/dto/index.ts
  apps/financial-aid/api/src/app/modules/apiKeys/models/deleteApiKey.response.ts
  apps/financial-aid/api/src/app/modules/apiKeys/models/index.ts
  apps/financial-aid/api/src/services/backend.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/models/deleteFile.response.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/models/user.model.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.controller.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.module.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.service.ts
  apps/financial-aid/web-veita/graphql/sharedGql.ts
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeysSettings/ApiKeysInfo.tsx
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/ApiKeysSettings/ApiKeysSettings.tsx
  apps/financial-aid/web-veita/src/utils/useApiKeys.ts
  apps/financial-aid/web-veita/src/utils/useApiKeysInfo.ts
Labels: automerge

#13709 feat(fa): Adding state to filter in applications and adding attributes
  apps/financial-aid/backend/src/app/modules/openApiApplications/openApiApplication.controller.ts
  apps/financial-aid/backend/src/app/modules/openApiApplications/openApiApplication.module.ts
  apps/financial-aid/backend/src/app/modules/openApiApplications/openApiApplication.service.ts
  apps/financial-aid/open-api/src/app/app.dto.ts
  apps/financial-aid/open-api/src/app/app.service.ts
Labels: automerge

#13716 fix(application-aod): Property share calculations
  libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/forms/overviewSections.ts
Labels: automerge

#13652 fix(application-estate): Stricter and tested validation; error messages
  libs/application/templates/estate/src/fields/RealEstateRepeater/AdditionalRealEstate.tsx
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/templates/estate/src/lib/utils.spec.ts
  libs/application/templates/estate/src/lib/utils.ts
Labels: automerge

#13710 chore(infra): set maxUnavailable PDB's instead of minAvailable
  apps/air-discount-scheme/api/infra/api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/pdb.spec.ts
  infra/src/dsl/types/charts.ts
  infra/src/dsl/types/input-types.ts
Labels: automerge

#13719 fix(application-aod): Fix property shares
  libs/application/templates/announcement-of-death/src/fields/RealEstateRepeater/index.tsx
  libs/application/templates/announcement-of-death/src/forms/overviewSections.ts
Labels: automerge

#13702 fix(parental-leave): Move file upload validation from answer validation to dataschema
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/employerValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/fileUploadValidationSection.ts
  libs/application/templates/parental-leave/src/lib/answerValidators.ts
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13718 fix(fa): Adding models for open api for better documentation
  apps/financial-aid/open-api/.eslintrc.json
  apps/financial-aid/open-api/src/app/app.controller.ts
  apps/financial-aid/open-api/src/app/app.service.ts
  apps/financial-aid/open-api/src/app/models/amount.model.ts
  apps/financial-aid/open-api/src/app/models/application.model.ts
  apps/financial-aid/open-api/src/app/models/deductionFactors.model.ts
  apps/financial-aid/open-api/src/app/models/directTaxPayments.model.ts
  apps/financial-aid/open-api/src/app/models/file.model.ts
  apps/financial-aid/open-api/src/app/models/index.ts
  apps/financial-aid/open-api/src/app/models/staff.model.ts
Labels: automerge

#13720 fix(fa): Adding scroll to nav when on small screen
  apps/financial-aid/web-veita/src/components/Nav/Nav.css.ts
Labels: automerge

#13663 fix(parental-leave): Fix some lint warnings
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx
  libs/application/templates/parental-leave/src/fields/UploadAdditionalFilesInfoScreen/index.tsx
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/answerValidationSections/validateLastestEmployerValidationSection.ts
Labels: automerge

#13708 fix(j-s): Court of appeal banner fixes
  apps/judicial-system/web/src/components/CourtArrangements/CourtArrangements.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Summary/Summary.spec.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Summary/Summary.tsx
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/stepHelper.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
Labels: automerge

#13724 fix(j-s): Remove defendant plea alert box from all case types but indictments
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
Labels: automerge

#13727 fix(fa): Fixing email
  apps/financial-aid/backend/src/app/modules/application/emailTemplates/applicantEmailTemplate.ts
  apps/financial-aid/web-veita/src/components/ModalTypes/EmailFormatInputModal.tsx
  apps/financial-aid/web-veita/src/components/RejectionCommentModal/RejectionCommentModal.tsx
  apps/financial-aid/web-veita/src/components/Timeline/ChatElement.tsx
Labels: automerge

#13707 chore(service-portal): Add health excel. Update Datepicker locale
  libs/service-portal/health/src/screens/Dentists/Dentists.tsx
  libs/service-portal/health/src/screens/Medicine/MedicineCalculator.tsx
  libs/service-portal/health/src/screens/Medicine/MedicinePurchase.tsx
  libs/service-portal/health/src/screens/Medicine/components/DrugRow/DrugRow.tsx
  libs/service-portal/health/src/screens/Medicine/components/QuantityCounter/QuantityCounter.tsx
  libs/service-portal/health/src/screens/Medicine/wrapper/MedicineWrapper.tsx
  libs/service-portal/health/src/screens/Payments/PaymentOverview.tsx
  libs/service-portal/health/src/screens/Payments/PaymentParticipation.tsx
  libs/service-portal/health/src/utils/FileBreakdown/dataHeaders.ts
  libs/service-portal/health/src/utils/FileBreakdown/filesStructure.ts
Labels: automerge

#13715 fix(work-machines): Update api and ui
  libs/api/domains/work-machines/src/lib/workMachines.service.ts
  libs/clients/work-machines/src/clientConfig.json
  libs/clients/work-machines/src/lib/workMachines.service.ts
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/WorkMachinesDetail/WorkMachinesDetail.tsx
  libs/service-portal/assets/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
  libs/service-portal/core/src/lib/messages.ts
Labels: automerge

#13730 fix(web): Auction card see more link visual fix
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
Labels: automerge

#13729 chore(ads): Remove ads private-openapi.yaml from GH
  .gitignore
  apps/air-discount-scheme/backend/src/private-openapi.yaml
Labels: automerge

#13728 fix(intellectual-properties): Fix design image list error
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.resolver.ts
  libs/api/domains/intellectual-properties/src/lib/intellectualProperties.service.ts
  libs/api/domains/intellectual-properties/src/lib/tests/util.test.ts
  libs/api/domains/intellectual-properties/src/lib/utils.ts
  libs/clients/intellectual-properties/src/lib/intellectualPropertiesClient.service.ts
Labels: automerge

#13732 fix(fa): Email formatting for rejection
  apps/financial-aid/web-veita/src/components/ModalTypes/EmailFormatInputModal.tsx
  apps/financial-aid/web-veita/src/components/StateModal/StateModal.tsx
Labels: automerge

#13731 fix(signature-collection): Security fic
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/index.tsx
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
Labels: automerge

#13734 fix(signature-collection): nondigital signature tag in service-portal
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
Labels: automerge

#13736 feat(service-portal): Secondary education x-road
  apps/api/infra/api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/inna/src/clientConfig.json
  libs/clients/inna/src/lib/inna.config.ts
  libs/clients/inna/src/lib/inna.provider.ts
  libs/clients/inna/src/lib/inna.service.ts
  libs/service-portal/education/src/screens/SecondarySchoolGraduationSingle/SecondarySchoolGraduationSingle.tsx
Labels: automerge

#13740 feat(application-system): Logging onsubmit application
  libs/application/template-api-modules/src/lib/modules/templates/passport/passport.service.ts
Labels: automerge

#13741 feat(web): Add header for Hms service web
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/Hms/Hms.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Hms/Hms.tsx
  apps/web/components/ServiceWeb/Background/Variations/Hms/index.ts
  apps/web/components/ServiceWeb/Header/Header.tsx
  apps/web/components/ServiceWeb/SearchSection/SearchSection.css.ts
  apps/web/components/ServiceWeb/config.ts
Labels: automerge

#13744 fix(signature-collection): actor restrictions & collectors visible for admin
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
Labels: automerge

#13669 fix(parental-leave): Remove image field and associated text
  apps/system-e2e/src/tests/islandis/application-system/acceptance/parental-leave.spec.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13743 feat(signature-collection): restrict access for actors for regular users
  libs/api/domains/signature-collection/src/lib/decorators/acessRequirement.decorator.ts
  libs/api/domains/signature-collection/src/lib/decorators/needsOwner.decorator.ts
  libs/api/domains/signature-collection/src/lib/guards/userAccess.guard.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
Labels: automerge

#13749 fix(web): Make sure that subarticle entry hyperlink href starts with a slash
  libs/island-ui/contentful/src/lib/RichTextRC/defaultRenderNode.tsx
Labels: automerge

#13746 feat(web): Chart functional improvements and style changes
  apps/web/components/Charts/v2/constants.ts
  apps/web/components/Charts/v2/hooks/chart.ts
  apps/web/components/Charts/v2/renderers/AccessibilityTableRenderer.tsx
  apps/web/components/Charts/v2/renderers/ChartComponentRenderer.tsx
  apps/web/components/Charts/v2/renderers/ChartNumberBox/ChartNumberBox.tsx
  apps/web/components/Charts/v2/renderers/ChartRenderer.tsx
  apps/web/components/Charts/v2/renderers/LegendRenderer.tsx
  apps/web/components/Charts/v2/renderers/PatternRenderer.tsx
  apps/web/components/Charts/v2/renderers/TooltipRenderer/TooltipRenderer.css.ts
  apps/web/components/Charts/v2/renderers/TooltipRenderer/TooltipRenderer.tsx
  apps/web/components/Charts/v2/types/index.ts
  apps/web/components/Charts/v2/utils/chart.tsx
  apps/web/components/Charts/v2/utils/color.spec.ts
  apps/web/components/Charts/v2/utils/color.ts
  apps/web/components/Charts/v2/utils/format.ts
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/clients/statistics/src/lib/statistics.utils.spec.ts
  libs/clients/statistics/src/lib/statistics.utils.ts
  libs/cms/src/lib/models/chartComponent.model.ts
Labels: automerge

#13745 feat(signed-collection): singedLists and canUnsign
  libs/api/domains/signature-collection/src/lib/models/signature.model.ts
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-signing/signature-list-signing.service.ts
  libs/application/templates/signature-collection/signature-list-signing/src/lib/errors.ts
  libs/clients/signature-collection/src/clientConfig.json
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-manager.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-shared.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.types.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
  libs/clients/signature-collection/src/lib/types/signature.dto.ts
  libs/clients/signature-collection/src/lib/types/success.dto.ts
  libs/clients/signature-collection/src/lib/types/user.dto.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/compareLists/compareLists.graphql
  libs/portals/admin/signature-collection/src/screens/List/getListSignees.graphql
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
  libs/service-portal/signature-collection/src/hooks/index.ts
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/SigneeView/index.tsx
Labels: automerge

#13635 feat(j-s): Click send files to actually send files
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealCaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.strings.ts
  apps/judicial-system/web/src/routes/Shared/AppealToCourtOfAppeals/AppealToCourtOfAppeals.tsx
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.strings.ts
  apps/judicial-system/web/src/routes/Shared/Statement/Statement.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  libs/island-ui/core/src/lib/InputFileUpload/InputFileUpload.tsx
Labels: automerge

#13752 fix(service-portal): Education. Update icon. Add tooltip
  libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.tsx
  libs/service-portal/education-student-assessment/src/screens/EducationStudentAssessment/components/StudentAssessmentTable/StudentAssessmentTable.tsx
Labels: automerge

#13755 feat(signature-collection): Collection and list status, toggle review and process
  libs/api/domains/signature-collection/src/lib/models/status.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
Labels: automerge

#13757 fix(service-portal): Update number mileage inputs
  libs/api/domains/vehicles/src/models/getVehicleMileage.model.ts
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleDetail.graphql
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
Labels: automerge

#13758 fix(service-portal): Hotfix - Update number mileage inputs
  libs/api/domains/vehicles/src/models/getVehicleMileage.model.ts
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleDetail.graphql
  libs/service-portal/assets/src/screens/VehicleMileage/VehicleMileage.tsx
Labels: automerge

#13760 fix(university-gateway): adding university-gateway-url to application-system env variables
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13611 feat(inheritance-report): add relation field for applicant step
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/applicant.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13630 chore(inheritance-report): remove repeater for public charges value
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/CalculationsOfTotal/CalculateTotalDebts/index.tsx
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/sections/debts.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13264 feat: fix mileage label
  apps/native/app/src/contexts/feature-flag-provider.tsx
  apps/native/app/src/graphql/queries/vehicle-mileage.graphql
  apps/native/app/src/index.tsx
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/login/testing-login.tsx
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/stores/preferences-store.ts
  apps/native/app/src/ui/lib/tableview/tableview-cell.tsx
  apps/native/app/src/ui/lib/text-field/text-field.tsx
  apps/native/app/src/utils/get-default-options.ts
  apps/native/app/src/utils/lifecycle/setup-globals.ts
Labels: automerge

#13759 chore(inheritance-report): add property share and more misc changes/fixes
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/announcement-of-death/src/forms/draft/subSectionProperties.ts
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.spec.ts
  libs/application/templates/inheritance-report/src/lib/utils/helpers.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13770 fix(fa): Removing keys for dev and updating status page for application system
  apps/financial-aid/web-veita/src/components/MunicipalityAdminSettings/MunicipalityAdminSettings.tsx
  libs/application/templates/financial-aid/src/fields/MissingFiles/MissingFiles.tsx
  libs/application/templates/financial-aid/src/lib/messages/missingFiles.ts
  libs/application/templates/financial-aid/src/lib/messages/status.ts
Labels: automerge

#13754 fix(signature-collection): Admin portal actions control
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/api/domains/signature-collection/src/lib/models/status.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.module.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionManager.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionManager.service.ts
  libs/clients/signature-collection/src/clientConfig.json
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-manager.service.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/AllLists.loader.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/completeCollectionProcessing/finishCollectionProcess.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/completeCollectionProcessing/index.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/graphql/getAllSignatureLists.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/graphql/getCollectionStatus.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/List.loader.ts
  libs/portals/admin/signature-collection/src/screens/List/components/completeReview/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/completeReview/toggleListReview.graphql
  libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/listInfoAlert/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/listReviewedAlert/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/graphql/getListSignees.graphql
  libs/portals/admin/signature-collection/src/screens/List/graphql/getListStatus.graphql
  libs/portals/admin/signature-collection/src/screens/List/graphql/getSignatureList.graphql
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
Labels: automerge

#13769 fix(university-gateway): adding university-gateway-url to application…
  apps/application-system/api/infra/application-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13765 fix(citizenship): adding parentId to childApplication
  libs/clients/directorate-of-immigration/src/clientConfig.json
  libs/clients/directorate-of-immigration/src/lib/directorateOfImmigrationClient.service.ts
Labels: automerge

#13774 fix(signature-collection): Admin portal actions control (#13754)
  libs/api/domains/signature-collection/src/lib/models/signatureList.model.ts
  libs/api/domains/signature-collection/src/lib/models/status.model.ts
  libs/api/domains/signature-collection/src/lib/signatureCollection.module.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionAdmin.service.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionManager.resolver.ts
  libs/api/domains/signature-collection/src/lib/signatureCollectionManager.service.ts
  libs/clients/signature-collection/src/clientConfig.json
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection-manager.service.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/portals/admin/signature-collection/src/lib/messages.ts
  libs/portals/admin/signature-collection/src/lib/utils.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/AllLists.loader.ts
  libs/portals/admin/signature-collection/src/screens/AllLists/components/completeCollectionProcessing/finishCollectionProcess.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/components/completeCollectionProcessing/index.tsx
  libs/portals/admin/signature-collection/src/screens/AllLists/graphql/getAllSignatureLists.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/graphql/getCollectionStatus.graphql
  libs/portals/admin/signature-collection/src/screens/AllLists/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/List.loader.ts
  libs/portals/admin/signature-collection/src/screens/List/components/completeReview/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/completeReview/toggleListReview.graphql
  libs/portals/admin/signature-collection/src/screens/List/components/extendDeadline/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/listInfoAlert/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/listReviewedAlert/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/components/paperUpload/index.tsx
  libs/portals/admin/signature-collection/src/screens/List/graphql/getListSignees.graphql
  libs/portals/admin/signature-collection/src/screens/List/graphql/getListStatus.graphql
  libs/portals/admin/signature-collection/src/screens/List/graphql/getSignatureList.graphql
  libs/portals/admin/signature-collection/src/screens/List/index.tsx
  libs/service-portal/signature-collection/src/lib/messages.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
Labels: automerge

#13771 chore(inheritance-report): add foreign bank account checkbox
  libs/application/templates/inheritance-report/src/fields/ReportFieldsRepeater/index.tsx
  libs/application/templates/inheritance-report/src/forms/OverviewSections/OverviewAssets.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/messages.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#13775 chore(infra): Tune down PDB strictness
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/pdb.spec.ts
Labels: automerge, high priority

#13776 chore(infra): Tune down PDB strictness (#13775)
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/pdb.spec.ts
Labels: automerge

#13777 chore(web): Add no-cache as fetchPolicy when fetching auctions
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
Labels: automerge

#13779 fix(fa): Removing guard for fetching api keys so employees can get municipality info
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.controller.ts
Labels: automerge, high priority

#13762 fix(j-s): Fixes issues found by e2e tests.
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/domkrofur-og-lagagrundvollur/[id].ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/fyrirtaka/[id].ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/greinargerd/[id].ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/stadfesta/[id].ts
  apps/judicial-system/web/pages/krafa/rannsoknarheimild/varnaradili/[id].ts
  apps/judicial-system/web/src/components/CommentsInput/CommentsInput.tsx
  apps/judicial-system/web/src/components/CourtArrangements/CourtArrangements.tsx
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInput.tsx
  apps/judicial-system/web/src/components/FormProvider/FormProvider.tsx
  apps/judicial-system/web/src/components/RulingInput/RulingInput.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Court/components/AppealSections/AppealSections.tsx
  apps/judicial-system/web/src/routes/Court/components/CourtCaseNumber/CourtCaseNumber.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/SelectCourtOfficials/SelectCourtOfficials.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Ruling/Ruling.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceDemands/PoliceDemands.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/PoliceReport/PoliceReport.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCourtUpload/index.ts
  apps/judicial-system/web/src/utils/hooks/useDefendants/index.ts
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/system-e2e/src/tests/judicial-system/smoke/case-list.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/custody-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/search-warrant-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/smoke/shared-steps/complete-appeal.ts
  apps/system-e2e/src/tests/judicial-system/smoke/shared-steps/send-appeal.ts
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#13781 fix(parental-leave): Removed employer selfEmployed file from dataSchema
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#13778 chore(j-s): Travel ban e2e
  apps/system-e2e/src/tests/judicial-system/smoke/travel-ban-tests.spec.ts
Labels: automerge

#13782 fix(parental-leave): Removed employer selfEmployed file from dataSchema
  libs/application/templates/parental-leave/src/lib/dataSchema.ts
Labels: automerge

#13628 fix(parental-leave): Move enums and functions to constants and utils
  libs/application/templates/parental-leave/src/constants.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#13785 feat(web): Add optional flipAxis field to Chart content model
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/chart.model.ts
Labels: automerge

#13766 chore(core): Add @island-is/origo-auth as Codeowner for auth lib seeders file
  .github/CODEOWNERS
Labels: automerge

#13784 feat(web): Use default footer for social insurance administration (TR)
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#13753 fix(parental-leave): Remove UploadAdditionalFilesInfoScreen
  libs/application/templates/parental-leave/src/fields/UploadAdditionalFilesInfoScreen/index.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/AdditionalDocumentsRequired.ts
Labels: automerge

#13783 fix(parental-leave): Remove useApplicationAnswers and useStatefulAnswers from hooks
  libs/application/templates/parental-leave/src/fields/ConclusionSectionImage/ConclusionImageScreen.tsx
  libs/application/templates/parental-leave/src/fields/EmployerApprovalExtraInformation/index.tsx
  libs/application/templates/parental-leave/src/fields/InReviewSteps/index.tsx
  libs/application/templates/parental-leave/src/fields/Review/Review.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/BaseInformation.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Employment.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/OtherParent.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/Payments.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/PersonalAllowance.tsx
  libs/application/templates/parental-leave/src/fields/Review/review-groups/SpousePersonalAllowance.tsx
  libs/application/templates/parental-leave/src/fields/Rights/SummaryRights.tsx
  libs/application/templates/parental-leave/src/fields/Rights/YourRightsBoxChart.tsx
  libs/application/templates/parental-leave/src/hooks/useApplicationAnswers.ts
  libs/application/templates/parental-leave/src/hooks/useDaysAlreadyUsed.ts
  libs/application/templates/parental-leave/src/hooks/useStatefulAnswers.ts
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#13787 fix(sessions): Fixing infra setup bug in geoip mapped volume.
  apps/services/sessions/docker-compose.yml
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/local-db/extensions.sql
  apps/services/sessions/migrations/20240214153321-clear-ip-location-column.js
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#13751 chore(j-s): Add context menu for all appeal case files
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.css.ts
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.spec.tsx
  apps/judicial-system/web/src/components/AppealCaseFilesOverview/AppealCaseFilesOverview.tsx
  apps/judicial-system/web/src/components/ContextMenu/ContextMenu.strings.ts
  apps/judicial-system/web/src/components/PdfButton/PdfButton.css.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/mocks.ts
Labels: automerge

#13723 chore(j-s): Make caseFilePdf prettier
  apps/judicial-system/backend/src/app/formatters/caseFilesRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/pdf.ts
  apps/judicial-system/backend/src/app/messages/pdfCaseFilesRecord.ts
Labels: automerge

#13792 fix(parental-leave): Fix duration error
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx
Labels: automerge

#13794 fix(parental-leave): Fix duration error (#13792)
  libs/application/templates/parental-leave/src/fields/Duration/Duration.tsx
  libs/application/templates/parental-leave/src/fields/PeriodPercentage/PeriodPercentage.tsx
Labels: automerge

#13789 fix(university-gateway): Accessibility and styling
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/UniversitySearch/useSetZIndexOnHeader.ts
Labels: automerge

#13747 fix(parental-leave): Refactor Conclusion screen
  libs/application/templates/parental-leave/src/fields/ConclusionSectionImage/ConclusionImageScreen.css.ts
  libs/application/templates/parental-leave/src/fields/ConclusionSectionImage/ConclusionImageScreen.tsx
  libs/application/templates/parental-leave/src/fields/index.ts
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-forms/src/lib/formConclusionSection/formConclusionSection.ts
Labels: automerge

#13772 feat(sessions): Session ui/ux changes
  libs/service-portal/sessions/src/components/LogTable/LogTable.css.ts
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/lib/messages.ts
Labels: automerge

#13797 fix(services-sessions): Fix geoip update and UI tweaks
  apps/services/sessions/docker-compose.yml
  apps/services/sessions/infra/sessions.ts
  apps/services/sessions/local-db/extensions.sql
  apps/services/sessions/migrations/20240214153321-clear-ip-location-column.js
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/service-portal/sessions/src/components/LogTable/LogTable.css.ts
  libs/service-portal/sessions/src/components/LogTable/LogTable.tsx
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/lib/messages.ts
Labels: automerge

#13786 fix(SGS Applications): Fixing bug when selecting vehicles is slow if too many cars are owned
  libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/vehicles/vehicles.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-license-plate/order-vehicle-license-plate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/CoOwner/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/shared/types.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/hooks/useLazyVehicleDetails.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/shared/types.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/information.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
  libs/clients/transport-authority/vehicle-owner-change/project.json
  libs/clients/transport-authority/vehicle-owner-change/src/clientConfig.json
Labels: automerge

#13799 fix(university-gateway): Hotfix styling and accessability
  apps/web/components/ActionCategoryCard/ActionCategoryCard.tsx
  apps/web/components/ListViewCard/ListViewCard.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
  apps/web/screens/UniversitySearch/LandingPage.tsx
  apps/web/screens/UniversitySearch/UniversitySearch.tsx
  apps/web/screens/UniversitySearch/UniversitySearchDetails.tsx
  apps/web/screens/UniversitySearch/useSetZIndexOnHeader.ts
Labels: automerge

#13802 fix(sessions): Fix translation strings
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/lib/messages.ts
Labels: automerge

#13800 fix(service-portal): empty state message for incoming deligations
  libs/portals/shared-modules/delegations/src/components/delegations/DelegationsEmptyState.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/incoming/DelegationsIncoming.tsx
  libs/portals/shared-modules/delegations/src/components/delegations/outgoing/DelegationsOutgoing.tsx
  libs/portals/shared-modules/delegations/src/lib/messages.ts
Labels: automerge

#13804 chore(web): Change email for transport authority service web contact form
  libs/api/domains/communications/src/lib/emailTemplates/serviceWebForms.ts
Labels: automerge

#13806 chore(web): Hotfix - Add no-cache as fetchPolicy when fetching auctions (#13777)
  apps/web/screens/Organization/Syslumenn/Auctions.tsx
Labels: automerge

#13608 feat(search-indexer): Fallback to using organization.slug for organizationPage.slug
  libs/cms/src/lib/models/organizationPage.model.ts
Labels: automerge

#13810 fix(service-portal): Update recycle car url, add to CMS
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
Labels: automerge

#13812 fix(service-portal): hotfix - Update recycle car url
  libs/service-portal/assets/src/lib/messages.ts
  libs/service-portal/assets/src/screens/Overview/Overview.tsx
Labels: automerge

#13813 fix(application-ctao): Validation and filename bug fix
  libs/application/template-api-modules/src/lib/modules/templates/complaints-to-althingi-ombudsman/complaints-to-althingi-ombudsman.service.ts
  libs/application/templates/complaints-to-althingi-ombudsman/src/fields/ComplaintOverview/ComplaintOverview.tsx
  libs/application/templates/complaints-to-althingi-ombudsman/src/lib/dataSchema.ts
Labels: automerge

#13815 fix(ip): Fix query
  libs/api/domains/intellectual-properties/src/lib/models/intellectualProperty.model.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
Labels: automerge

#13811 fix(services-sessions): Fix sessions column too large value
  apps/services/sessions/migrations/20240216101538-change-user-agent-column-datatype.js
  apps/services/sessions/src/app/sessions/constants.ts
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
Labels: automerge

#13817 fix(sessions): Hotfix - Sessions translations and large column
  apps/services/sessions/migrations/20240216101538-change-user-agent-column-datatype.js
  apps/services/sessions/src/app/sessions/constants.ts
  apps/services/sessions/src/app/sessions/session.model.ts
  apps/services/sessions/src/app/sessions/sessions.service.spec.ts
  apps/services/sessions/src/app/sessions/sessions.service.ts
  libs/service-portal/sessions/src/components/LogTable/LogTableMobile.tsx
  libs/service-portal/sessions/src/lib/messages.ts
Labels: automerge

#13818 fix(ip): Hotfix - ip query
  libs/api/domains/intellectual-properties/src/lib/models/intellectualProperty.model.ts
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.graphql
  libs/service-portal/assets/src/screens/IntellectualPropertiesOverview/IntellectualPropertiesOverview.tsx
Labels: automerge

#13791 chore(system-e2e): service portal assets smoke test
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/assets.spec.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
Labels: automerge

#13823 chore(core): Add lint warnings for preferred function style
  .eslintrc.json
Labels: automerge

#13825 fix(signature-collection): text tweak
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-creation/emailGenerators/applicationSubmitted.ts
Labels: automerge

#13605 feat(web): Pension calculator
  .github/CODEOWNERS
  apps/web/README.md
  apps/web/components/connected/HousingBenefitCalculator/HousingBenefitCalculator.tsx
  apps/web/components/connected/HousingBenefitCalculator/SpecificHousingBenefitSupportCalculator.tsx
  apps/web/components/connected/vehicles/KilometerFee.tsx
  apps/web/hooks/useLinkResolver/useLinkResolver.ts
  apps/web/i18n/withLocale.tsx
  apps/web/pages/en/o/social-insurance-administration/calculator/index.ts
  apps/web/pages/en/o/social-insurance-administration/calculator/results/index.ts
  apps/web/pages/s/tryggingastofnun/reiknivel/index.ts
  apps/web/pages/s/tryggingastofnun/reiknivel/nidurstodur/index.ts
  apps/web/project.json
  apps/web/screens/CustomPage/CustomPageWrapper.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.css.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorResults.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculatorWrapper.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/utils.ts
  apps/web/screens/queries/CustomPage.ts
  apps/web/screens/queries/PensionCalculator.ts
  apps/web/utils/currency.ts
  libs/api/domains/social-insurance/src/lib/dtos/pensionCalculation.input.ts
  libs/api/domains/social-insurance/src/lib/models/pensionCalculation.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.module.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.resolver.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/api/domains/social-insurance/src/lib/utils.ts
  libs/clients/social-insurance-administration/README.md
  libs/clients/social-insurance-administration/src/clientConfig.json
  libs/clients/social-insurance-administration/src/lib/apis.ts
  libs/clients/social-insurance-administration/src/lib/socialInsuranceAdministrationClient.service.ts
  libs/cms/src/index.ts
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getCustomPage.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/customPage.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/importers/customPage.service.ts
  libs/shared/form-fields/src/lib/SelectController/SelectController.tsx
Labels: automerge

#13735 fix(SGS Applications): Fixing bug when selecting vehicles is slow if too many cars are owned
  libs/api/domains/transport-authority/src/lib/graphql/models/getCurrentVehicles.model.ts
  libs/api/domains/transport-authority/src/lib/transportAuthority.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/vehicles/vehicles.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-co-owner-of-vehicle/change-co-owner-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/change-operator-of-vehicle/change-operator-of-vehicle.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/order-vehicle-license-plate/order-vehicle-license-plate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/transport-authority/transfer-of-vehicle-ownership/transfer-of-vehicle-ownership.service.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/CoOwner/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/graphql/queries.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/messages/information.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/shared/types.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/shared/types.ts
  libs/application/templates/transport-authority/order-vehicle-license-plate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/graphql/queries.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/hooks/useLazyVehicleDetails.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/lib/messages/information.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/shared/types.ts
  libs/application/templates/transport-authority/order-vehicle-registration-certificate/src/utils/getSelectedVehicle.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/fields/VehiclesField/index.tsx
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/graphql/queries.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/messages/information.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/shared/types.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/utils/getSelectedVehicle.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
  libs/clients/transport-authority/vehicle-owner-change/project.json
  libs/clients/transport-authority/vehicle-owner-change/src/clientConfig.json
Labels: automerge

#13828 fix(fa): Adding backend url to api
  apps/financial-aid/open-api/src/app/app.config.ts
Labels: automerge

#13826 fix(university-gateway): Change data type of Program.durationInYears from int to float
  apps/services/university-gateway/migrations/20240215161647-change-program-duration-type.js
  apps/services/university-gateway/src/app/modules/program/model/program.ts
Labels: automerge

#13830 fix(university-gateway): Change data type of Program.durationInYears from int to float
  apps/services/university-gateway/migrations/20240215161647-change-program-duration-type.js
  apps/services/university-gateway/src/app/modules/program/model/program.ts
Labels: automerge

#13829 fix(signature-collection): fixes for testing
  libs/application/template-api-modules/src/lib/modules/templates/signature-collection/signature-list-creation/emailGenerators/applicationSubmitted.ts
  libs/clients/signature-collection/src/lib/signature-collection-admin.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.service.ts
  libs/clients/signature-collection/src/lib/signature-collection.types.ts
  libs/clients/signature-collection/src/lib/types/area.dto.ts
  libs/clients/signature-collection/src/lib/types/bulkUpload.dto.ts
  libs/clients/signature-collection/src/lib/types/collection.dto.ts
  libs/clients/signature-collection/src/lib/types/list.dto.ts
  libs/clients/signature-collection/src/lib/types/user.dto.ts
  libs/service-portal/signature-collection/src/components/SignedList/index.tsx
  libs/service-portal/signature-collection/src/hooks/graphql/queries.ts
  libs/service-portal/signature-collection/src/screens/CandidateView/index.tsx
Labels: automerge
