Repository island-is/island.is, pull requests merged in 2024-08, with the labels that each got.

#15557 fix(parental-leave): Fix application pruning
  libs/application/templates/parental-leave/src/lib/parentalLeaveUtils.ts
Labels: automerge

#15569 fix(services-endorsements-api): Postnumer fix (#15565)
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
Labels: automerge

#15572 fix(services-endorsements-api): Sveitafelag fix
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
Labels: automerge

#15574 fix(services-endorsements-api): Sveitafelag fix (#15572)
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
Labels: automerge

#15577 fix(application-estate): Selection bugfix (#15575)
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/fakeData.ts
Labels: automerge

#15578 fix(application-estate): Fix value for message
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
Labels: automerge

#15580 fix: return void in render local env
  infra/src/cli/cli.ts
Labels: automerge

#15570 feat(driving-license): Added info link to done page
  libs/application/templates/driving-license/src/forms/done.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15583 fix(web): Broken anchor page links in search
  apps/web/screens/Search/Search.tsx
Labels: automerge

#15561 feat(web): Charts - locale specific numeric separators and fractional display
  apps/web/components/Charts/v2/messages.ts
  apps/web/components/Charts/v2/renderers/TooltipRenderer/TooltipRenderer.tsx
  apps/web/components/Charts/v2/types/index.ts
  apps/web/components/Charts/v2/utils/format.ts
Labels: automerge

#15584 fix: 7 char build sha in workflow for ids
  .github/workflows/push.yml
Labels: automerge

#15579 fix(web): Vehicle search - Add new field and display it in frontend
  .github/CODEOWNERS
  apps/web/components/connected/vehicles/PublicVehicleSearch.tsx
  apps/web/screens/queries/PublicVehicleSearch.ts
  libs/api/domains/vehicles/src/models/getPublicVehicleSearch.model.ts
  libs/clients/vehicles/src/clientConfig.json
Labels: automerge

#15591 fix(parental-leave): change lifecycle
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#15593 fix(parental-leave): change lifecycle (#15591)
  libs/application/templates/parental-leave/src/lib/ParentalLeaveTemplate.ts
Labels: automerge

#15585 feat(fetch): Log `name` in fetch failure body
  libs/clients/middlewares/src/lib/withAutoAuth.ts
  libs/clients/middlewares/src/lib/withErrorLog.ts
Labels: automerge

#15592 fix(web): Fix watermark on redocly
  apps/web/components/OpenApiDocumentation/OpenApiDocumentation.tsx
Labels: automerge

#15589 fix(fa): Fixing error messages in financial-aid
  apps/financial-aid/backend/src/app/guards/apiKey.guard.ts
  apps/financial-aid/backend/src/app/modules/municipalityApiUsers/user.service.ts
  apps/financial-aid/open-api/src/app/app.dto.ts
  apps/financial-aid/open-api/src/app/app.service.ts
  apps/financial-aid/open-api/src/app/helpers.ts
Labels: automerge

#15587 feat(regulations): Updated date flow
  libs/portals/admin/regulations-admin/src/components/EditMeta.tsx
  libs/portals/admin/regulations-admin/src/components/EditReviewOverview.tsx
  libs/portals/admin/regulations-admin/src/components/EditSignature.tsx
  libs/portals/admin/regulations-admin/src/components/impacts/ImpactDate.tsx
  libs/portals/admin/regulations-admin/src/lib/messages.ts
  package.json
  yarn.lock
Labels: automerge

#15596 fix(general-petition): Paginated endpoint petitions
  apps/web/screens/PetitionView/PetitionView.tsx
  apps/web/screens/PetitionView/queries.ts
  libs/portals/admin/petition/src/screens/PetitionList/PetitionList.loader.ts
  libs/service-portal/petitions/src/lib/utils.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/service-portal/petitions/src/screens/hooks.ts
  libs/service-portal/petitions/src/screens/queries.ts
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#15586 feat(endorsement-system): Data cleanup worker
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/project.json
  apps/services/endorsements/api/src/app/cleanup/worker.module.ts
  apps/services/endorsements/api/src/app/cleanup/worker.service.ts
  apps/services/endorsements/api/src/cleanup.ts
  apps/services/endorsements/api/src/environments/environment.ts
  apps/services/endorsements/api/src/main.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#15597 feat(portals): Add page titles
  apps/portals/admin/src/app/App.tsx
  apps/service-portal/src/app/App.tsx
  libs/portals/core/src/components/PortalProvider.tsx
  libs/portals/core/src/hooks/useSingleNavigationItem.spec.tsx
  libs/portals/core/src/screens/ModuleRoute.tsx
Labels: automerge

#15598 chore(ci): Quoted and safer workflows
  .github/workflows/config-values.yaml
  .github/workflows/external-checks.yml
  .github/workflows/pullrequest-close.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge, deploy-feature, test everything

#15601 feat(web): Service web - Handle null value for support category gql endpoint
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  libs/cms/src/lib/cms.resolver.ts
Labels: automerge

#15595 chore(search-indexer): Update README for dev-services
  apps/services/search-indexer/dev-services/README.md
Labels: automerge

#15602 fix(web): Service web subpages - Encode uri before setting header when redirecting
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
Labels: automerge

#15606 fix(web): News - Input validation for numeric query params
  apps/web/layouts/main.tsx
  apps/web/screens/News.css.ts
  apps/web/screens/News.tsx
  apps/web/screens/Organization/OrganizationNews/OrganizationNewsList.tsx
  apps/web/screens/Project/ProjectNewsList.tsx
  apps/web/utils/queryParams.ts
Labels: automerge

#15608 fix(ci): Utilize exit code of grep
  .github/workflows/config-values.yaml
Labels: automerge, high priority

#15605 feat(endorsement-system): Data cleanup worker envs
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#15609 fix(service-portal): Only display toast for multi archive
  libs/service-portal/documents/src/hooks/useMailActionV2.ts
Labels: automerge

#15613 chore(ci): (almost) No `always()`
  .github/actions/cache/action.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#15610 fix(service-portal): Only display toast for multi archive - hotfix
  libs/service-portal/documents/src/hooks/useMailActionV2.ts
Labels: automerge

#15600 feat(web): Use default header component for Digital Iceland header
  apps/web/components/DefaultHeader/DefaultHeader.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.css.ts
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#15616 fix(services-endorsements-api): Locality fix and export limit
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/project.json
  apps/services/endorsements/api/src/app/cleanup/worker.module.ts
  apps/services/endorsements/api/src/app/cleanup/worker.service.ts
  apps/services/endorsements/api/src/cleanup.ts
  apps/services/endorsements/api/src/environments/environment.ts
  apps/services/endorsements/api/src/main.ts
  apps/web/screens/PetitionView/PetitionView.tsx
  apps/web/screens/PetitionView/queries.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/portals/admin/petition/src/screens/PetitionList/PetitionList.loader.ts
  libs/service-portal/petitions/src/lib/utils.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/DownloadPdf/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/downloadCSV.ts
  libs/service-portal/petitions/src/screens/PetitionsTable/ExportPetition/index.tsx
  libs/service-portal/petitions/src/screens/PetitionsTable/index.tsx
  libs/service-portal/petitions/src/screens/ViewOwnedList/index.tsx
  libs/service-portal/petitions/src/screens/ViewSignedList/index.tsx
  libs/service-portal/petitions/src/screens/hooks.ts
  libs/service-portal/petitions/src/screens/queries.ts
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#15607 chore: updated readme with more requirements and node versions
  README.md
Labels: automerge

#15604 chore(service-portal): Icon - File tray empty
  libs/island-ui/core/src/lib/IconRC/iconMap.ts
  libs/island-ui/core/src/lib/IconRC/icons/FileTrayEmpty.tsx
  libs/island-ui/core/src/lib/IconRC/icons/FileTrayEmptyOutline.tsx
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBar.tsx
  libs/service-portal/documents/src/components/DocumentActionBar/DocumentActionBarV2.tsx
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV2.tsx
  libs/service-portal/documents/src/components/FavAndStash/index.tsx
  libs/service-portal/documents/src/screens/Overview/OverviewV2.tsx
Labels: automerge

#15612 fix(web): Change form field value to unique value
  apps/web/components/Form/Form.tsx
  apps/web/screens/queries/fragments.ts
Labels: automerge

#15619 fix(contentful-apps): Hotfix - Translation namespace app - trim whitespace when considering if a node is empty
  apps/contentful-apps/components/translation-namespace/utils/deserialize.ts
Labels: automerge

#15618 fix(contentful-apps): Translation namespace app - trim whitespace when considering if a node is empty
  apps/contentful-apps/components/translation-namespace/utils/deserialize.ts
Labels: automerge

#15615 fix(mortgage-certificate): adding #markdown to messages
  libs/application/templates/mortgage-certificate/src/lib/messages/confirmation.ts
  libs/application/templates/mortgage-certificate/src/lib/messages/index.ts
  libs/application/templates/mortgage-certificate/src/lib/messages/overview.ts
Labels: automerge

#15537 chore(j-s): Fix date and set default format
  apps/judicial-system/backend/src/app/formatters/caseFilesRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/confirmedIndictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.spec.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/components/SignedDocument/SignedDocument.tsx
  apps/judicial-system/web/src/components/Table/DurationDate/DurationDate.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCases.spec.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesAwaitingReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesForReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.tsx
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#15514 chore(j-s): SMS and Email Config
  apps/api/src/app/app.module.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/environments/environment.interface.ts
  apps/application-system/api/src/environments/environment.ts
  apps/financial-aid/backend/src/app/app.module.ts
  apps/financial-aid/backend/src/app/modules/application/application.module.ts
  apps/financial-aid/backend/src/app/modules/staff/staff.module.ts
  apps/financial-aid/backend/src/environments/environment.ts
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/court/court.module.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/environments/environment.ts
  apps/judicial-system/backend/src/environments/index.ts
  apps/services/auth/ids-api/src/app/app.module.ts
  apps/services/auth/ids-api/src/app/notifications/notifications.module.ts
  apps/services/auth/ids-api/src/environments/environment.ts
  apps/services/endorsements/api/src/app/app.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/environments/environment.ts
  apps/services/user-notification/src/app/app.module.ts
  apps/services/user-notification/src/app/modules/notifications/notifications.module.ts
  apps/services/user-notification/src/environments/environment.ts
  apps/services/user-profile/src/app/app.module.ts
  apps/services/user-profile/src/app/user-profile/userProfile.module.ts
  apps/services/user-profile/src/app/v2/user-profile.module.ts
  apps/services/user-profile/src/environments/environment.ts
  libs/api/domains/communications/src/lib/communications.module.ts
  libs/api/domains/communications/src/lib/communications.service.spec.ts
  libs/api/domains/communications/src/lib/environments/environment.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change-v2/children-residence-change.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/children-residence-change.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/criminal-record-submission/criminal-record-submission.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-submission/driving-license-submission.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/example-payment-actions/examplePaymentActions.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/financial-statements-inao/financial-statements-inao.module.ts
  libs/application/template-api-modules/src/lib/modules/templates/index.ts
  libs/application/template-api-modules/src/lib/modules/templates/mortgage-certificate-submission/mortgage-certificate-submission.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.module.ts
  libs/application/template-api-modules/src/lib/types/index.ts
  libs/email-service/README.md
  libs/email-service/src/index.ts
  libs/email-service/src/lib/email.config.ts
  libs/email-service/src/lib/email.module.ts
  libs/email-service/src/lib/email.service.ts
  libs/email-service/src/lib/test/createTestingEmailModule.ts
  libs/email-service/src/lib/test/email.service.spec.ts
  libs/judicial-system/auth/src/lib/auth.module.ts
  libs/nova-sms/.eslintrc.json
  libs/nova-sms/README.md
  libs/nova-sms/src/index.ts
  libs/nova-sms/src/lib/sms.config.ts
  libs/nova-sms/src/lib/sms.module.ts
  libs/nova-sms/src/lib/sms.service.spec.ts
  libs/nova-sms/src/lib/sms.service.ts
Labels: automerge

#15529 feat(service-portal): New InfoLine component
  libs/service-portal/core/src/components/GeneralButton/GeneralButton.tsx
  libs/service-portal/core/src/components/InfoLine/InfoLine.css.ts
  libs/service-portal/core/src/components/InfoLine/InfoLine.tsx
  libs/service-portal/core/src/components/InfoLine/InfoLineStack.tsx
  libs/service-portal/core/src/index.ts
  libs/service-portal/education/src/screens/EducationGraduationDetail/EducationGraduationDetail.tsx
  libs/service-portal/information/src/screens/UserInfo/UserInfo.tsx
  libs/service-portal/occupational-licenses/src/components/LicenseDetail.tsx
Labels: automerge

#15322 fix(service-portal): accessibility fixes
  libs/service-portal/core/src/components/InstitutionPanel/InstitutionPanel.tsx
  libs/service-portal/core/src/components/TabNavigation/SubTabItem.tsx
  libs/service-portal/core/src/components/TabNavigation/TabNavigation.tsx
  libs/service-portal/documents/src/screens/Overview/OverviewV2.tsx
  libs/service-portal/documents/src/utils/messages.ts
  libs/service-portal/finance/src/components/FinanceIntro/index.tsx
  libs/service-portal/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#15533 chore(j-s): Tag handling and display merged tag
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/components/Tags/CaseTag.strings.ts
  apps/judicial-system/web/src/components/Tags/CaseTag.tsx
  apps/judicial-system/web/src/components/Tags/utils.ts
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
Labels: automerge

#15623 fix(life-events): Fixing linkRouter locale
  apps/web/screens/LifeEventPage/LifeEventPage.tsx
Labels: automerge

#15590 fix(native-app): Fix mileage validation logic
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
Labels: automerge

#15594 fix(native-app): Fix regression in theme mode
  apps/native/app/src/contexts/theme-provider.tsx
Labels: automerge

#15525 fix(app,auth): Fix passkey authentication on Android
  apps/native/app/src/lib/passkeys/helpers.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.config.ts
  libs/auth-api-lib/src/lib/passkeys-core/passkeys-core.service.ts
Labels: automerge

#15628 fix(search-indexer): Development Dockerfile changes due to mirror.centos.org being down
  apps/services/search-indexer/dev-services/elasticsearch/Dockerfile
Labels: automerge

#15621 feat(application-system): Phone number validation param to user-profile service
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
  libs/application/templates/id-card/src/dataProviders/index.ts
  libs/application/types/src/lib/template-api/shared-api/shared-api-definitions/user-profile-api.ts
Labels: automerge

#15629 fix(signature-collection): texts update
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/constants.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
Labels: automerge

#15630 fix(service-portal-documents): Make input bigger + add label
  libs/service-portal/core/src/components/Filter/Filter.css.ts
  libs/service-portal/core/src/components/Filter/Filter.tsx
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilterV2.tsx
  libs/service-portal/documents/src/utils/messages.ts
Labels: automerge

#15603 feat(signature-collection): Sign parliamentary collection
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/.babelrc
  libs/application/templates/signature-collection/parliamentary-list-signing/.eslintrc.json
  libs/application/templates/signature-collection/parliamentary-list-signing/README.md
  libs/application/templates/signature-collection/parliamentary-list-signing/assets/Logo.tsx
  libs/application/templates/signature-collection/parliamentary-list-signing/jest.config.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/project.json
  libs/application/templates/signature-collection/parliamentary-list-signing/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/index.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/constants.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/dataSchema.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/errors.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/signListTemplate.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/src/lib/utils.ts
  libs/application/templates/signature-collection/parliamentary-list-signing/tsconfig.json
  libs/application/templates/signature-collection/parliamentary-list-signing/tsconfig.lib.json
  libs/application/templates/signature-collection/parliamentary-list-signing/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/InstitutionMapper.ts
  tsconfig.base.json
Labels: automerge

#15631 feat(web): Add namespace to default service web header
  apps/web/components/ServiceWeb/Background/Background.tsx
  apps/web/components/ServiceWeb/Background/Variations/Default/Default.css.ts
  apps/web/components/ServiceWeb/Background/Variations/Default/Default.tsx
Labels: automerge

#15633 fix(web): Add safe fallback operator to namespace conversion for service webs
  apps/web/components/ServiceWeb/Wrapper/Wrapper.tsx
Labels: automerge

#15634 fix(form-system): form-system-backend-client
  apps/services/form-system/project.json
Labels: automerge

#15636 feat(income-plan): text changes
  libs/application/templates/social-insurance-administration/income-plan/src/fields/Review/index.tsx
  libs/application/templates/social-insurance-administration/income-plan/src/lib/IncomePlanTemplate.ts
  libs/application/templates/social-insurance-administration/income-plan/src/lib/messages.ts
Labels: automerge

#15649 fix(service-portal-vehicles): Spacing for cta when tag is visible
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
Labels: automerge

#15538 fix(car-recycling): Change endpoint to the get the applicants vehicles
  libs/api/domains/vehicles/src/lib/api-domains-vehicles.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/car-recycling/car-recycling.service.ts
  libs/application/templates/car-recycling/codegen.yml
  libs/application/templates/car-recycling/project.json
  libs/application/templates/car-recycling/src/dataProviders/index.ts
  libs/application/templates/car-recycling/src/fields/Review/index.tsx
  libs/application/templates/car-recycling/src/fields/Review/review-groups/Vehicles.tsx
  libs/application/templates/car-recycling/src/fields/VehiclesOverview/VehiclesOverview.tsx
  libs/application/templates/car-recycling/src/forms/CarRecyclingForm.ts
  libs/application/templates/car-recycling/src/forms/Prerequisites.ts
  libs/application/templates/car-recycling/src/graphql/queries.ts
  libs/application/templates/car-recycling/src/hooks/index.ts
  libs/application/templates/car-recycling/src/lib/CarRecyclingTemplate.ts
  libs/application/templates/car-recycling/src/lib/carRecyclingUtils.ts
  libs/application/templates/car-recycling/src/lib/dataSchema.ts
  libs/application/templates/car-recycling/src/lib/messages.ts
  libs/application/templates/car-recycling/src/shared/types.ts
Labels: automerge, deploy-feature

#15617 test(j-s): Indictment E2E tests
  apps/system-e2e/src/tests/judicial-system/regression/indictment-tests.spec.ts
Labels: automerge

#15648 fix(form-system): migration/seed errors
  apps/services/form-system/infra/form-system.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
Labels: automerge

#15641 fix(infra): Corrected the version of the docker.io/grokzen/redis-cluster
  apps/air-discount-scheme/backend/docker-compose.yml
  apps/api/docker-compose.yml
  apps/application-system/api/docker-compose.yml
  apps/github-actions-cache/docker-compose.yml
  apps/services/sessions/docker-compose.yml
  apps/services/user-notification/docker-compose.yml
Labels: automerge

#15611 fix(native-app): Fix notifications listeners
  apps/native/app/android/app/src/main/AndroidManifest.xml
  apps/native/app/src/index.tsx
  apps/native/app/src/lib/use-browser.ts
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/finance/finance.tsx
  apps/native/app/src/screens/home/applications-module.tsx
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/login/login.tsx
  apps/native/app/src/screens/login/testing-login.tsx
  apps/native/app/src/screens/onboarding/onboarding-notifications.tsx
  apps/native/app/src/screens/passkey/passkey.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/screens/wallet-passport/wallet-passport.tsx
  apps/native/app/src/utils/coerce-to-number.ts
  apps/native/app/src/utils/lifecycle/setup-notifications.ts
  apps/native/app/src/utils/onboarding.ts
  apps/native/app/src/utils/versions-check.ts
Labels: automerge

#15643 fix(j-s): Indictment Screen Header
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
Labels: automerge

#15639 feat(j-s): LÖKE File Name
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/police/test/getAll.spec.ts
Labels: automerge

#15638 feat(j-s): Layer Assignment
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/utils/validate.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/case.ts
Labels: automerge

#15645 feat(web): Journeyman list - display national id field
  apps/web/components/connected/syslumenn/TableLists/JourneymanList/JourneymanList.tsx
  apps/web/components/connected/syslumenn/TableLists/JourneymanList/queries.ts
  libs/api/domains/syslumenn/src/lib/models/journeymanLicence.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#15635 feat(auth-admin): SuperAdmin hide PersonalRepresentative changes
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/portals/admin/ids-admin/src/screens/Client/components/Delegation.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionDelegations.tsx
Labels: automerge

#15519 chore(ids-apis): Use delegation types and providers to filter.
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index-test-cases.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegation-index.service.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegation-index/delegations-index-types.ts
  apps/services/auth/delegation-api/src/app/delegations/test/delegations-controller/delegations.controller.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.filters.spec.ts
  apps/services/auth/delegation-api/src/app/delegations/test/test-data.ts
  apps/services/auth/delegation-api/test/access-incoming-test-cases.ts
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.spec.ts
  apps/services/auth/ids-api/src/app/delegations/delegations.controller.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-test-cases.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters-types.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-filters.spec.ts
  apps/services/auth/ids-api/src/app/delegations/test/delegations-scopes.spec.ts
  apps/services/auth/ids-api/test/stubs/personalRepresentativeStubs.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.ts
  apps/services/auth/public-api/src/app/modules/delegations/delegations.module.ts
  apps/services/auth/public-api/test/setup.ts
  libs/auth-api-lib/src/lib/clients/clients.service.ts
  libs/auth-api-lib/src/lib/delegations/delegation-provider.service.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-company.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-custom.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-representative.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming-ward.service.ts
  libs/auth-api-lib/src/lib/delegations/delegations-incoming.service.ts
  libs/auth-api-lib/src/lib/resources/models/api-scope-delegation-type.model.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
  libs/services/auth/testing/src/utils/delegations.ts
Labels: automerge

#15662 fix(native-app): more heap for codemagic builds
  codemagic.yaml
Labels: automerge

#15661 fix(fa): Creating muni, children aid needed default value
  apps/financial-aid/backend/src/app/modules/municipality/models/municipality.model.ts
Labels: automerge, high priority

#15654 fix(native-app): small fixes
  apps/native/app/src/screens/air-discount/air-discount.tsx
  apps/native/app/src/screens/wallet-passport/wallet-passport.tsx
  apps/native/app/src/ui/lib/problem/problem-template.tsx
Labels: automerge

#15651 chore(clients): Health Directorate - Factory for apis
  libs/clients/health-directorate/src/lib/apiConfiguration.ts
  libs/clients/health-directorate/src/lib/configFactory.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.config.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.module.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.types.ts
Labels: automerge

#15670 fix(application-system): Allowing transfer of ownership on deregistered machines
  libs/api/domains/work-machines/src/lib/workMachines.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/aosh/transfer-of-machine-ownership/transfer-of-machine-ownership.service.ts
  libs/clients/work-machines/src/lib/workMachines.service.ts
Labels: automerge

#15660 fix(application-driving-license): Remove redundant health cert warning for BE license
  libs/application/templates/driving-license/src/forms/draft/subSectionHealthDeclaration.ts
Labels: automerge

#15671 fix(service-portal): document list gql cache on bulk archive
  libs/service-portal/documents/src/hooks/useDocumentList.ts
  libs/service-portal/documents/src/hooks/useMailActionV2.ts
  libs/service-portal/documents/src/screens/Overview/OverviewV2.tsx
Labels: automerge

#15673 feat(web): Temporary event licences - Location field
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/TemporaryEventLicencesList.tsx
  apps/web/components/connected/syslumenn/CardLists/TemporaryEventLicencesList/queries.ts
  libs/api/domains/syslumenn/src/lib/models/temporaryEventLicence.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.types.ts
  libs/clients/syslumenn/src/lib/syslumennClient.utils.ts
Labels: automerge

#15527 feat(j-s): Waiting for Confirmation Notifications
  apps/judicial-system/backend/project.json
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/index.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/defendant/defendant.service.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/backend/src/app/modules/institution/institution.service.ts
  apps/judicial-system/backend/src/app/modules/notification/baseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/caseNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/institutionNotification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/dto/notification.dto.ts
  apps/judicial-system/backend/src/app/modules/notification/institutionNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/institutionNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.controller.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.module.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/notificationDispatch.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/dispatchIndictmentsWaitingForConfirmationNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/internalNotificationControllerGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCaseNotificationGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefendantsNotUpdatedAtCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendDefenderAssignedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentDeniedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentReturnedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendIndictmentsWaitingForConfirmationNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendReadyForCourtNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRevokedNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRulingNotifications.spec.ts
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/message-handler/src/app/internalDelivery.service.ts
  apps/judicial-system/message-handler/src/app/messageHandler.service.ts
  apps/judicial-system/message-handler/src/app/test/handleMessage.spec.ts
  apps/judicial-system/scheduler/infra/judicial-system-scheduler.ts
  apps/judicial-system/scheduler/src/app/app.module.ts
  apps/judicial-system/scheduler/src/app/app.service.ts
  apps/judicial-system/scheduler/src/app/test/createTestingAppModule.ts
  apps/judicial-system/scheduler/src/app/test/run.spec.ts
  apps/judicial-system/scheduler/src/main.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  libs/judicial-system/message/src/index.ts
  libs/judicial-system/message/src/lib/message.service.ts
  libs/judicial-system/message/src/lib/message.ts
  libs/judicial-system/message/src/lib/test/receiveMessagesFromQueue.spec.ts
  libs/judicial-system/message/src/lib/test/sendMessagesToQueue.spec.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#15675 hotfix(auth-admin): SuperAdmin block PersonalRepresentative changes in IDS
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/portals/admin/ids-admin/src/screens/Client/components/Delegation.tsx
  libs/portals/admin/ids-admin/src/screens/Permission/components/PermissionDelegations.tsx
Labels: automerge

#15677 fix(island-ui): Select menu z-index
  libs/island-ui/core/src/lib/Select/Select.css.ts
Labels: automerge

#15650 chore(j-s): Refactor NameAndEmail component
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/RenderPersonalInfo/RenderPersonalInfo.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/RenderPersonalInfo/RenderPersonalInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#15289 feat(web): Team List - Accordion variant
  apps/web/components/GenericList/GenericList.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/Organization/Slice/TeamListSlice/TeamListSlice.tsx
  apps/web/components/Organization/index.ts
  apps/web/screens/queries/TeamList.ts
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.module.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getTeamMembers.input.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/customPage.model.ts
  libs/cms/src/lib/models/teamList.model.ts
  libs/cms/src/lib/models/teamMember.model.ts
  libs/cms/src/lib/models/teamMemberResponse.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/cmsSync.service.ts
  libs/cms/src/lib/search/importers/teamList.service.ts
  libs/island-ui/contentful/src/index.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.css.ts
  libs/island-ui/contentful/src/lib/TeamList/TeamList.tsx
  libs/island-ui/core/src/lib/Accordion/AccordionItem/AccordionItem.tsx
Labels: automerge

#15652 chore(j-s): Refactor defender in InfoCard
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.css.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.spec.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.strings.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/RenderPersonalInfo/RenderPersonalInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: automerge

#15622 fix(parental-leave): Make redirect to spouse page display correct information
  libs/application/templates/parental-leave/src/fields/Review/review-groups/OtherParent.tsx
Labels: automerge

#15676 feat(general-petition): Update email text
  .github/CODEOWNERS
  libs/application/template-api-modules/src/lib/modules/templates/general-petition/emailGenerators/generalPetitionNotification.ts
Labels: automerge

#15684 chore(form-system): refactor backend
  apps/services/form-system/src/app/modules/applicants/models/applicant.model.ts
  apps/services/form-system/src/app/modules/applicants/models/applicantTypeNameSuggestion.model.ts
  apps/services/form-system/src/app/modules/applicants/models/formApplicant.model.ts
  apps/services/form-system/src/app/modules/applications/models/application.mapper.ts
  apps/services/form-system/src/app/modules/applications/models/application.model.ts
  apps/services/form-system/src/app/modules/applications/models/dto/application.dto.ts
  apps/services/form-system/src/app/modules/certifications/models/certificationType.model.ts
  apps/services/form-system/src/app/modules/certifications/models/dto/formCertificationType.dto.ts
  apps/services/form-system/src/app/modules/fieldSettings/models/dto/fieldSettings.dto.ts
  apps/services/form-system/src/app/modules/fieldSettings/models/dto/updateFieldSettings.dto.ts
  apps/services/form-system/src/app/modules/fieldSettings/models/fieldSettings.model.ts
  apps/services/form-system/src/app/modules/fields/fields.controller.ts
  apps/services/form-system/src/app/modules/fields/fields.service.ts
  apps/services/form-system/src/app/modules/fields/models/dto/applicationField.dto.ts
  apps/services/form-system/src/app/modules/fields/models/field.model.ts
  apps/services/form-system/src/app/modules/fields/models/fieldType.model.ts
  apps/services/form-system/src/app/modules/forms/forms.controller.ts
  apps/services/form-system/src/app/modules/forms/forms.service.ts
  apps/services/form-system/src/app/modules/forms/models/dto/form.dto.ts
  apps/services/form-system/src/app/modules/forms/models/dto/form.response.dto.ts
  apps/services/form-system/src/app/modules/forms/models/dto/formsList.dto.ts
  apps/services/form-system/src/app/modules/forms/models/dto/formsListForm.dto.ts
  apps/services/form-system/src/app/modules/forms/models/form.model.ts
  apps/services/form-system/src/app/modules/listItems/models/listItem.model.ts
  apps/services/form-system/src/app/modules/lists/models/listType.model.ts
  apps/services/form-system/src/app/modules/organizations/models/dto/organization.dto.ts
  apps/services/form-system/src/app/modules/organizations/models/dto/organizations.response.dto.ts
  apps/services/form-system/src/app/modules/organizations/models/organization.model.ts
  apps/services/form-system/src/app/modules/organizations/organizations.controller.ts
  apps/services/form-system/src/app/modules/organizations/organizations.service.ts
  apps/services/form-system/src/app/modules/screens/models/dto/applicationScreen.dto.ts
  apps/services/form-system/src/app/modules/screens/models/dto/screen.dto.ts
  apps/services/form-system/src/app/modules/screens/models/screen.model.ts
  apps/services/form-system/src/app/modules/screens/screens.controller.ts
  apps/services/form-system/src/app/modules/screens/screens.service.ts
  apps/services/form-system/src/app/modules/sections/models/dto/applicationSection.dto.ts
  apps/services/form-system/src/app/modules/sections/models/dto/section.dto.ts
  apps/services/form-system/src/app/modules/sections/models/section.model.ts
  apps/services/form-system/src/app/modules/sections/sections.controller.ts
  apps/services/form-system/src/app/modules/sections/sections.service.ts
Labels: automerge

#15685 feat(mortgage certificate): max properties
  libs/application/templates/mortgage-certificate/src/fields/SelectProperty/index.tsx
  libs/application/templates/mortgage-certificate/src/lib/messages/application.ts
  libs/application/templates/mortgage-certificate/src/lib/messages/error.ts
Labels: automerge

#15679 feat(web): Transport authority web chat config changes
  apps/web/components/ChatPanel/WatsonChatPanel/WatsonChatPanel.tsx
  apps/web/components/ChatPanel/types.ts
  apps/web/components/Organization/Wrapper/config.ts
  apps/web/components/ServiceWeb/config.ts
  apps/web/screens/Article/components/ArticleChatPanel/config.ts
Labels: automerge

#15689 fix(email-service): Update nodemailer package and update SES transport to match aws v3
  libs/email-service/src/lib/email.service.ts
  package.json
  yarn.lock
Labels: automerge

#15687 feat(service-portal): Add clients for directorate of health apis
  apps/api/src/app/app.module.ts
  apps/application-system/api/src/app/app.module.ts
  libs/clients/health-directorate/project.json
  libs/clients/health-directorate/src/index.ts
  libs/clients/health-directorate/src/lib/apiConfiguration.ts
  libs/clients/health-directorate/src/lib/clients/index.ts
  libs/clients/health-directorate/src/lib/clients/occupational-license/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/occupational-license/healthDirectorateClient.config.ts
  libs/clients/health-directorate/src/lib/clients/occupational-license/healthDirectorateClient.provider.ts
  libs/clients/health-directorate/src/lib/clients/occupational-license/healthDirectorateClient.service.ts
  libs/clients/health-directorate/src/lib/clients/occupational-license/index.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/organ-donation/index.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.config.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.provider.ts
  libs/clients/health-directorate/src/lib/clients/organ-donation/organDonation.service.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/clientConfig.json
  libs/clients/health-directorate/src/lib/clients/vaccinations/index.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.config.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.provider.ts
  libs/clients/health-directorate/src/lib/clients/vaccinations/vaccinations.service.ts
  libs/clients/health-directorate/src/lib/configFactory.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.config.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.module.ts
  libs/clients/health-directorate/src/lib/healthDirectorateClient.types.ts
Labels: automerge

#15666 fix(estate): phone number country codes
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/fields/EstateMembersRepeater/index.tsx
Labels: automerge

#15694 feat(endorsement-system): Remove temp cleanup worker
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/project.json
  apps/services/endorsements/api/src/app/cleanup/worker.module.ts
  apps/services/endorsements/api/src/app/cleanup/worker.service.ts
  apps/services/endorsements/api/src/cleanup.ts
  apps/services/endorsements/api/src/main.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#15552 feat(user-notification): DX improvements
  apps/services/user-notification/project.json
  apps/services/user-notification/seeders/seed_notification.js
  apps/services/user-notification/src/app/modules/notifications/notifications.service.ts
  apps/services/user-notification/src/config.ts
Labels: automerge

#15680 feat(j-s): Police case files types
  apps/judicial-system/api/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/migrations/20240816113616-update-case-file.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/pdf.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getCaseFilesRecordPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/limitedAccessCaseController/getCaseFilesRecordPdf.spec.ts
  apps/judicial-system/backend/src/app/modules/police/models/policeCaseFile.model.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/CaseFiles/CaseFiles.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/PoliceCaseFilesRoute.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/PoliceCaseFiles/indictmentPoliceCaseFiles.graphql
  apps/judicial-system/web/src/routes/Prosecutor/components/PoliceCaseFiles/PoliceCaseFiles.tsx
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#15691 feat(api): new domain for health directorate on service portal
  .github/CODEOWNERS
  libs/api/domains/health-directorate/.eslintrc.json
  libs/api/domains/health-directorate/README.md
  libs/api/domains/health-directorate/jest.config.ts
  libs/api/domains/health-directorate/project.json
  libs/api/domains/health-directorate/src/index.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/organ-donation.model.ts
  libs/api/domains/health-directorate/src/lib/models/vaccinations.model.ts
  libs/api/domains/health-directorate/tsconfig.json
  libs/api/domains/health-directorate/tsconfig.lib.json
  libs/api/domains/health-directorate/tsconfig.spec.json
  tsconfig.base.json
Labels: automerge

#15696 feat(web): Add sjúkratryggingar service web category for european health insurance card
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/screens/ServiceWeb/Forms/utils.ts
Labels: automerge

#15681 fix(ids-api): Fix allowed origins in ids-api infra.
  apps/services/auth/ids-api/infra/ids-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15699 fix(application-system): Updating project.json to allow assets for an aosh application
  apps/application-system/api/project.json
Labels: automerge

#15692 fix(j-s): Institution Query
  apps/judicial-system/backend/src/app/modules/institution/institution.service.ts
Labels: automerge

#15688 fix(web): Fix styles for ums cost of living calculator
  apps/web/components/connected/UmbodsmadurSkuldara/UmsCostOfLivingCalculator.css.ts
  apps/web/components/connected/UmbodsmadurSkuldara/UmsCostOfLivingCalculator.tsx
Labels: automerge

#15697 fix(j-s): Subpoena PDF
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/messages/pdfSubpoena.ts
Labels: automerge

#15698 fix(j-s): Stepper Fix
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
Labels: automerge

#15686 fix(j-s): User title and event log ordering
  apps/judicial-system/backend/src/app/formatters/confirmedIndictmentPdf.ts
  apps/judicial-system/backend/src/app/formatters/courtRecordPdf.ts
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/formatters/pdfHelpers.ts
  apps/judicial-system/backend/src/app/formatters/requestPdf.ts
  apps/judicial-system/backend/src/app/formatters/subpoenaPdf.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/web/src/routes/Court/InvestigationCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.spec.ts
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/Components/ModifyDatesModal/ModifyDatesModal.tsx
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#15703 feat(j-s): New Case File Categories
  libs/judicial-system/types/src/lib/file.ts
Labels: automerge

#15705 fix(ids-api): Fix regression in delegation scope filtering.
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
Labels: automerge

#15709 fix(finance): Fix input size
  libs/service-portal/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsTableDetail.tsx
Labels: automerge

#15624 feat(service-portal): Health - Vaccinations
  apps/api/src/app/app.module.ts
  apps/service-portal/src/auth.ts
  libs/api/domains/health-directorate/src/index.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.module.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.service.ts
  libs/api/domains/health-directorate/src/lib/models/organ-donation.model.ts
  libs/api/domains/health-directorate/src/lib/models/vaccinations.model.ts
  libs/api/domains/health-directorate/tsconfig.json
  libs/api/domains/health-directorate/tsconfig.lib.json
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/core/src/components/SortableTable/SortableTable.tsx
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/Vaccinations/Vaccinations.graphql
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsGeneral.tsx
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsOther.tsx
  libs/service-portal/health/src/screens/Vaccinations/dataStructure.ts
  libs/service-portal/health/src/screens/Vaccinations/tables/SortedVaccinationsTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsDetailTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsTable.css.ts
  libs/service-portal/health/src/screens/Vaccinations/tables/VaccinationsTable.tsx
  libs/service-portal/health/src/screens/Vaccinations/wrapper/VaccinationsWrapper.tsx
  libs/service-portal/health/src/utils/constants.ts
  libs/service-portal/health/src/utils/tagSelector.ts
  libs/service-portal/health/src/utils/types.ts
  tsconfig.base.json
Labels: automerge, deploy-feature

#15710 fix: move GestureHandlerRootView to only wrap license scanner
  apps/native/app/src/screens/license-scanner/license-scanner.tsx
  apps/native/app/src/utils/register-component.tsx
Labels: automerge

#15708 fix(native-app): force light mode for splash screens as well
  apps/native/app/android/app/src/main/res/values/styles.xml
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#15227 feat(service-portal): Health - Organ donation
  apps/service-portal/src/auth.ts
  libs/api/domains/health-directorate/src/lib/health-directorate.resolver.ts
  libs/auth/scopes/src/lib/api.scope.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/health/src/lib/messages.ts
  libs/service-portal/health/src/lib/navigation.ts
  libs/service-portal/health/src/lib/paths.ts
  libs/service-portal/health/src/module.tsx
  libs/service-portal/health/src/screens/OrganDonation/OrganDonation.graphql
  libs/service-portal/health/src/screens/OrganDonation/OrganDonation.tsx
  libs/service-portal/health/src/screens/OrganDonationRegistration/Limitations.tsx
  libs/service-portal/health/src/screens/OrganDonationRegistration/OrganDonationRegistration.css.ts
  libs/service-portal/health/src/screens/OrganDonationRegistration/RegistrationForm.tsx
  libs/service-portal/health/src/screens/Vaccinations/Vaccinations.graphql
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsGeneral.tsx
  libs/service-portal/health/src/screens/Vaccinations/VaccinationsOther.tsx
  libs/service-portal/health/src/utils/OrganDonationMock.ts
  libs/service-portal/health/src/utils/types.ts
Labels: automerge

#15711 fix(aosh/register-new-machine): new machine fix
  libs/application/templates/aosh/register-new-machine/src/graphql/queries.ts
Labels: automerge

#15700 fix(auth-admin): Fix scope super admin restrictions on create
  apps/services/auth/admin-api/src/app/v2/scopes/me-scopes.controller.ts
  apps/services/auth/admin-api/src/app/v2/scopes/test/me-scopes.spec.ts
  libs/auth-api-lib/src/lib/clients/admin/admin-clients.service.ts
  libs/auth-api-lib/src/lib/resources/admin/admin-scope.service.ts
  libs/auth-api-lib/src/lib/resources/utils/personalRepresentativeFilter.ts
Labels: automerge

#15293 fix(auth-api-lib): createClient and createScope seed scripts for new delegation types
  libs/auth-api-lib/jest.config.ts
  libs/auth-api-lib/seeders/data/helpers/createClient.ts
  libs/auth-api-lib/seeders/data/helpers/createScope.ts
  libs/auth-api-lib/seeders/data/test-create-client-and-scope.ts
Labels: automerge

#15713 fix(license-api): Missing packages
  apps/services/license-api/esbuild.json
Labels: automerge

#15714 fix(license-api): Hotfix- Missing packages
  apps/services/license-api/esbuild.json
Labels: automerge

#15716 fix: Remove form system
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#15718 fix: Remove form system (#15716)
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
Labels: automerge

#15721 fix(skilavottord): Check if the right owner is registered when deregistering vehicles
  apps/skilavottord/ws/src/app/modules/recyclingRequest/recyclingRequest.service.ts
Labels: automerge

#15715 feat(delegations): Add created by national id field
  libs/auth-api-lib/migrations/20240820094641-delegation-created-by.js
  libs/auth-api-lib/src/lib/delegations/delegations-outgoing.service.ts
  libs/auth-api-lib/src/lib/delegations/models/delegation.model.ts
Labels: automerge

#15727 fix(user-notification): Env cleanup revert
  apps/services/user-notification/src/config.ts
Labels: automerge

#15724 chore(ids-auth-api): added seeder script for Landlæknir scopes
  libs/auth-api-lib/seeders/data/scopes-landlaeknir.ts
Labels: automerge

#15719 feat(j-s): Store user name with uploaded case file
  apps/judicial-system/backend/migrations/20240820112256-update-case-file.js
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
Labels: automerge

#15730 fix(user-notification): Env cleanup revert hotfix
  apps/services/user-notification/src/config.ts
  infra/src/uber-charts/islandis.ts
Labels: automerge

#15515 chore(application-ir): Update DC inheritance tax endpoint
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#15695 chore(j-s): Add law and order scope for judicial system digital mailbox API
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/case.controller.ts
  libs/auth-api-lib/seeders/data/scope-law-and-order.ts
  libs/auth/scopes/src/index.ts
  libs/auth/scopes/src/lib/judicial-system.scope.ts
Labels: automerge

#15725 fix(j-s): Titles in Info Cards
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx
Labels: automerge

#15739 fix(application-system): Use s3Uri to get attachment bucket
  libs/application/template-api-modules/src/lib/modules/shared/services/attachment-s3.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Labels: automerge

#15740 fix(application-system): Use s3Uri to get attachment bucket (hotfix)
  libs/application/template-api-modules/src/lib/modules/shared/services/attachment-s3.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/p-sign-submission/p-sign-submission.service.ts
Labels: automerge

#15744 fix(regulations-admin): Edit signature, today label, redundant title
  libs/portals/admin/regulations-admin/src/components/EditSignature.tsx
  libs/portals/admin/regulations-admin/src/components/TaskList.tsx
  libs/portals/admin/regulations-admin/src/utils/formatAmendingRegulation.ts
Labels: automerge

#15735 fix(application): Replace raw text DraftProgressMeter with message
  libs/application/core/src/lib/messages.ts
  libs/application/ui-components/src/components/ApplicationCard/components/ApplicationCardProgress.tsx
  libs/island-ui/core/src/lib/DraftProgressMeter/DraftProgressMeter.stories.tsx
  libs/island-ui/core/src/lib/DraftProgressMeter/DraftProgressMeter.tsx
Labels: automerge

#15743 fix(efs): advocate validation
  libs/application/templates/inheritance-report/src/fields/HeirsRepeater/AdditionalHeir.tsx
  libs/application/templates/inheritance-report/src/forms/sections/prepaidInheritance/applicant.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#15750 fix: Correct passkey origin for iOS app HOTFIX
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15747 fix: Correct passkey origin for iOS app
  apps/services/auth/ids-api/infra/ids-api.ts
  apps/services/auth/public-api/infra/auth-public-api.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
Labels: automerge

#15749 fix(web): Organization subpage sidebar links lose highlight when query params are present
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge, deploy-feature

#15752 fix(j-s): Indictment view tag
  libs/judicial-system/types/src/lib/indictmentCase.ts
Labels: automerge

#15757 feat(regulations-admin): Add .docx import
  libs/portals/admin/regulations-admin/src/components/EditorInput.tsx
  libs/portals/admin/regulations-admin/src/lib/messages.ts
  libs/portals/admin/regulations-admin/src/utils/fileUploader.ts
  package.json
  yarn.lock
Labels: automerge

#15765 fix(fsie-application): Fix error handling
  libs/application/template-api-modules/src/lib/modules/templates/financial-statement-individual-election/financial-statement-individual-election.service.ts
Labels: automerge

#15745 feat(j-s): Display uploaded indictment case files
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.strings.ts
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/Table/AppealCasesTable/AppealCasesTable.tsx
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.css.ts
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.strings.ts
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/components/Table/index.ts
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/hooks/useSortCases.tsx
  apps/judicial-system/web/src/utils/hooks/index.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSort.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSortAppealCases.ts
  apps/judicial-system/web/src/utils/hooks/useSort/useSortCases.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
Labels: automerge

#15767 fix(ui-core): Radio label width
  libs/island-ui/core/src/lib/RadioButton/RadioButton.css.ts
Labels: automerge

#15766 fix(regulations-admin): Update file url
  libs/portals/admin/regulations-admin/src/utils/fileUploader.ts
Labels: automerge

#15751 fix(application-overview): Make the applicaton overview display translated instutution names
  libs/application/types/src/lib/InstitutionContentfulIds.ts
  libs/application/types/src/lib/InstitutionMapper.ts
  libs/service-portal/applications/src/lib/messages.ts
  libs/service-portal/applications/src/screens/Overview.tsx
  libs/service-portal/applications/src/shared/utils/index.ts
Labels: automerge

#15729 fix(application-ir): Map executors
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
Labels: automerge

#15756 fix(j-s): Info Card for Request Cases
  apps/judicial-system/backend/src/app/modules/case/filters/cases.filter.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/cases.filter.spec.ts
  apps/judicial-system/web/messages/Core/index.ts
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
Labels: automerge

#15768 fix(general-petitions): web pagination revert
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/GeneralPetitionLists.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#15771 fix(citizenship): updating string to markdown
  libs/application/templates/directorate-of-immigration/citizenship/src/lib/messages/confirmation.ts
Labels: automerge

#15672 feat(ojoi): Comments screen
  libs/application/templates/official-journal-of-iceland/src/components/comments/CommentList.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Comments.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useComments.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/comments.ts
Labels: automerge

#15770 fix(j-s): Law and order scope
  libs/auth-api-lib/seeders/data/scope-law-and-order.ts
Labels: automerge

#15722 feat(university-gateway): attachment download links
  apps/services/university-gateway/src/app/modules/application/dto/createApplicationDto.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/university/university.service.ts
  libs/clients/university-application/university-of-iceland/src/clientConfig.yaml
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.service.ts
  libs/clients/university-application/university-of-iceland/src/lib/utils/mapUglaApplication.ts
  libs/university-gateway/src/lib/model/application.ts
Labels: automerge

#15712 chore(j-s): Indictment Court Date Notifications
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/filters/case.filter.ts
  apps/judicial-system/backend/src/app/modules/notification/internalNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendCourtDateNotifications.spec.ts
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#15653 feat(endorsement-system): Server side pdf and csv s3 signed urls
  apps/services/endorsements/api/infra/endorsement-system-api.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.module.ts
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/dto/endorsementListExportUrl.response.dto.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.controller.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.module.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  apps/services/endorsements/api/src/environments/environment.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/api/domains/endorsement-system/src/lib/dto/exportEndorsementList.input.ts
  libs/api/domains/endorsement-system/src/lib/dto/exportUrl.response.ts
  libs/api/domains/endorsement-system/src/lib/endorsementSystem.resolver.ts
  libs/api/domains/endorsement-system/src/lib/endorsementSystem.service.ts
Labels: automerge
