Repository island-is/island.is, pull requests merged in 2024-07, with the labels that each got.

#15378 feat(j-s): Indictment decision tag on summary page
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
Labels: automerge

#15398 fix(service-portal): Update accessibility in docs v2. Add rsk fallback.
  apps/service-portal/src/components/Notifications/NotificationButton.tsx
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/NoPDF/NoPDF.tsx
Labels: automerge

#15401 fix(service-portal): Documents rsk a11y - hotfix
  apps/service-portal/src/components/Notifications/NotificationButton.tsx
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
  libs/clients/documents-v2/src/lib/dto/document.dto.ts
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/documents/src/components/DocumentLine/DocumentLine.tsx
  libs/service-portal/documents/src/components/NoPDF/NoPDF.tsx
  libs/service-portal/documents/src/hooks/useMailActionV2.ts
  libs/service-portal/documents/src/screens/Overview/Overview.tsx
  libs/service-portal/documents/src/utils/messages.ts
  libs/service-portal/documents/src/utils/useSubmitMailAction.ts
Labels: automerge

#15388 feat(ui-fields): table repeater updates
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
Labels: automerge

#15397 fix(native-app): use correct openBrowser function for login screen
  apps/native/app/src/screens/login/login.tsx
Labels: automerge

#15393 feat(j-s): Cancellation Notice
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/deliverCancellationNotice.dto.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentCancellationNoticeToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentCancellationNoticeToCourtGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/court/court.service.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#15396 feat(occupational-licenses): Add license number to health directorate license
  libs/api/domains/occupational-licenses-v2/src/lib/models/license.model.ts
  libs/api/domains/occupational-licenses-v2/src/lib/models/licenseResult.model.ts
  libs/api/domains/occupational-licenses-v2/src/lib/occupationalLicensesV2.service.ts
  libs/api/domains/occupational-licenses/src/index.ts
  libs/service-portal/occupational-licenses/src/lib/messages.ts
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesDetail/OccupationalLicensesDetail.graphql
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesDetail/OccupationalLicensesDetail.tsx
  libs/service-portal/occupational-licenses/src/screens/v2/OccupationalLicensesOverview/OccupationalLicensesOverview.graphql
Labels: automerge

#15404 chore(j-s): Endpoint to retrieve lawyers for RLS
  apps/judicial-system/xrd-api/src/app/app.controller.ts
  apps/judicial-system/xrd-api/src/app/app.model.ts
  apps/judicial-system/xrd-api/src/app/app.module.ts
  apps/judicial-system/xrd-api/src/app/test/createTestingAppModule.ts
Labels: automerge

#15365 fix(ui-fields): TableRepeaterField with NationalIdWithName component
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-components/src/components/NationalIdWithName/NationalIdWithName.tsx
  libs/application/ui-fields/src/lib/TableRepeaterFormField/TableRepeaterFormField.tsx
  libs/application/ui-fields/src/lib/TableRepeaterFormField/utils.ts
Labels: automerge

#15412 fix(service-portal): Add local hasread doc support
  libs/service-portal/documents/src/components/DocumentLine/DocumentLineV2.tsx
  libs/service-portal/documents/src/screens/Overview/DocumentContext.tsx
Labels: automerge

#15407 chore(core): Splitting compiler options of tsconfig.base.json to tsconfig.shared.json
  .nxignore
  nx.json
  scripts/ts-node.js
  tsconfig.base.json
  tsconfig.shared.json
Labels: automerge

#15411 fix(j-s): Public Prosecutor Staff
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
Labels: automerge

#15385 fix(driving-license): Differentiate teachers using first 6 from nationalId
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
Labels: automerge

#15406 fix(j-s): Court Arrangements
  apps/judicial-system/web/src/components/CourtArrangements/CourtArrangements.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/CourtRecord/CourtRecord.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#15414 fix(j-s): Handle no defender assigned in indictment case InfoCard
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
Labels: automerge

#15415 fix(system-e2e): Catch mock errors
  apps/system-e2e/README.md
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
Labels: automerge

#15422 fix(j-s): xrd-API config
  apps/judicial-system/xrd-api/infra/judicial-system-xrd-api.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
Labels: automerge

#15424 fix(application-systems): Adding alertField to personal section
  libs/application/templates/healthcare-work-permit/src/forms/HealthcareWorkPermitForm/personalSection.ts
  libs/application/templates/healthcare-work-permit/src/lib/messages/personal.ts
Labels: automerge

#15419 fix(driving-license): Differentiate teachers using first 6 from natio…
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
Labels: automerge

#15339 feat(application-systems): V2 for V1 user profile api
  apps/application-system/api/infra/application-system-api.ts
  apps/services/user-profile/infra/service-portal-api.ts
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
Labels: automerge

#15382 chore: Remove generated `dist/` files
  apps/api/dist/.nx-results
  apps/application-system/form/dist/.nx-results
  apps/financial-aid/web-osk/dist/.nx-results
  apps/financial-aid/web-veita/dist/.nx-results
  apps/judicial-system/web/dist/.nx-results
Labels: automerge

#15402 chore: Update node.js version to LTS version
  package.json
Labels: automerge, deploy-feature, test everything

#15427 fix: rebuild when node version changes
  nx.json
Labels: automerge, deploy-feature

#15416 fix(j-s): Roles Rules
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmation.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmationRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignature.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignatureRolesRules.spec.ts
Labels: automerge

#15423 fix(j-s): Court Client Error Handling
  libs/judicial-system/court-client/src/lib/courtClient.service.ts
Labels: automerge

#15410 fix(j-s): Indictment Filter Option
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.tsx
Labels: automerge

#15425 chore(j-s): Web Environment Cleanup
  apps/judicial-system/web/src/environments/environment.ts
Labels: automerge

#15421 chore(j-s): Court Autofill
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/create.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/create.spec.ts
  apps/judicial-system/web/src/components/UserProvider/currentUser.graphql
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
Labels: automerge

#15433 fix(passport): updated xroad config
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
Labels: automerge

#15430 feat(application-dld): Entry requirements in DP
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
  libs/application/templates/driving-license-duplicate/src/dataProviders/index.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/driving-license/src/v4/clientConfig.json
  libs/clients/driving-license/src/v5/clientConfig.json
Labels: automerge

#15431 fix(j-s): OpenAPI non-required fields
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/dto/subpoena.dto.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
Labels: automerge

#15445 fix(application-dld): Entry requirements in DP
  libs/api/domains/driving-license/src/lib/drivingLicense.service.ts
  libs/api/domains/driving-license/src/lib/drivingLicense.type.ts
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/driving-license-duplicate/driving-license-duplicate.service.ts
  libs/application/templates/driving-license-duplicate/src/dataProviders/index.ts
  libs/application/templates/driving-license-duplicate/src/forms/applicationSections/sectionDataProviders.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
  libs/clients/driving-license/src/v4/clientConfig.json
  libs/clients/driving-license/src/v5/clientConfig.json
Labels: automerge

#15449 ci: use corepack enable
  .github/actions/unit-test/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge, deploy-feature, high priority, test everything

#15429 fix(j-s): Case file drag fixes
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
Labels: automerge

#15273 fix(service-portal): empty table heading for finance
  libs/service-portal/core/src/components/ExpandableTable/Header.tsx
  libs/service-portal/core/src/utils/utils.ts
  libs/service-portal/finance/src/components/FinanceLoans/FinanceLoansTable.tsx
Labels: automerge

#15268 fix(service-portal): Headings structure fixed
  apps/service-portal/src/screens/Dashboard/Dashboard.tsx
  libs/island-ui/core/src/lib/Filter/FilterMultiChoice/FilterMultiChoice.tsx
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilter.tsx
  libs/service-portal/documents/src/components/DocumentFilter/DocumentsFilterV2.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: automerge

#15435 fix(j-s): Handle empty string
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
Labels: automerge

#15448 fix(application-system-api): Use withNx plugin in application-system-api webpack config
  apps/application-system/api/webpack.config.js
Labels: automerge

#15446 fix(system-e2e): Load x road mock in sequence
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/setup-xroad.mocks.ts
Labels: automerge

#15333 feat(signature-collection): Application for Parliamentary Create List
  libs/application/template-loader/src/lib/templateLoaders.ts
  libs/application/templates/signature-collection/assets/Illustration.tsx
  libs/application/templates/signature-collection/parliamentary-list-creation/.babelrc
  libs/application/templates/signature-collection/parliamentary-list-creation/.eslintrc.json
  libs/application/templates/signature-collection/parliamentary-list-creation/README.md
  libs/application/templates/signature-collection/parliamentary-list-creation/assets/Logo.tsx
  libs/application/templates/signature-collection/parliamentary-list-creation/jest.config.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/project.json
  libs/application/templates/signature-collection/parliamentary-list-creation/src/dataProviders/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Done.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Draft.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/forms/Prerequisites.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/index.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/constants.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/createCollectionTemplate.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/dataSchema.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/errors.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/messages.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/src/lib/utils.ts
  libs/application/templates/signature-collection/parliamentary-list-creation/tsconfig.json
  libs/application/templates/signature-collection/parliamentary-list-creation/tsconfig.lib.json
  libs/application/templates/signature-collection/parliamentary-list-creation/tsconfig.spec.json
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/types/src/lib/InstitutionMapper.ts
  libs/feature-flags/src/lib/features.ts
  tsconfig.base.json
Labels: automerge

#15452 fix(parental-leave): Update conclusion screen
  libs/application/templates/parental-leave/src/forms/EditOrAddEmployersAndPeriods.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/lib/messages.ts
Labels: automerge

#15455 fix(hid): Use correct id to get attachments on submit
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.service.ts
Labels: automerge

#15439 fix(application-system-api): Fix user-profile shared-api module
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.module.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
Labels: automerge

#15453 chore: increase retention days
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: automerge

#15454 fix(hid): Use correct id to fetch attachments on submit
  libs/application/template-api-modules/src/lib/modules/templates/health-insurance-declaration/health-insurance-declaration.service.ts
Labels: automerge

#15443 fix(social-insurance-maintenance): add labels
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/social-insurance-maintenance/src/lib/messages.ts
  libs/service-portal/social-insurance-maintenance/src/lib/navigation.ts
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge

#15458 fix(tr-applications): removed faked form steppers
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/AdditionalSupportForTheElderlyForm.ts
  libs/application/templates/social-insurance-administration/additional-support-for-the-elderly/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/HouseholdSupplementForm.ts
  libs/application/templates/social-insurance-administration/household-supplement/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/PensionSupplementForm.ts
  libs/application/templates/social-insurance-administration/pension-supplement/src/forms/Prerequisites.ts
Labels: automerge

#15459 fix(social-insurance-maintenance): HOTFIX - Add labels
  libs/service-portal/core/src/lib/messages.ts
  libs/service-portal/social-insurance-maintenance/src/lib/messages.ts
  libs/service-portal/social-insurance-maintenance/src/lib/navigation.ts
  libs/service-portal/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge

#15357 feat(j-s): Indictment overview for prison users
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/pages/fangelsi/akaera/yfirlit/[id].ts
  apps/judicial-system/web/pages/fangelsi/krafa/yfirlit/[id].ts
  apps/judicial-system/web/pages/fangelsi/krofur.ts
  apps/judicial-system/web/src/components/FormFooter/FormFooter.tsx
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCard.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment/InfoCardClosedIndictment.spec.ts
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.strings.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/AllCases.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  apps/judicial-system/web/src/utils/hooks/useCaseList/index.tsx
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/types/src/lib/eventLog.ts
Labels: automerge

#15462 fix(j-s): Spacing fix
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#15468 fix(application-driving-license): Remarks revamped and bugfixes
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/remark.model.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/types.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/HealthRemarks.tsx
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#15466 fix(j-s): Grids
  apps/judicial-system/web/src/routes/Court/components/AppealSections/AppealSections.css.ts
  apps/judicial-system/web/src/routes/Court/components/AppealSections/AppealSections.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Overview/Overview.css.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/useSections.spec.tsx
  libs/island-ui/core/src/lib/RadioButton/RadioButton.css.ts
Labels: automerge

#15461 feat(j-s): Service requirement represented on InfoCard
  apps/judicial-system/backend/src/app/formatters/courtRecord.spec.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.spec.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.strings.ts
  apps/judicial-system/web/src/components/InfoCard/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.spec.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
Labels: automerge

#15460 fix(user-notification): Fix email layout for outlook client
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.spec.ts
  apps/services/user-notification/src/app/modules/notifications/notificationsWorker/notificationsWorker.service.ts
  apps/services/user-notification/src/assets/images/en-button-open.png
  apps/services/user-notification/src/assets/images/is-button-open.png
  apps/services/user-notification/src/assets/images/island-2x-logo.png
  libs/email-service/src/tools/adapter.service.ts
  libs/email-service/src/tools/design/foundation.hbs
  libs/email-service/src/tools/design/image.hbs
  libs/email-service/src/tools/design/imagewithlink.hbs
  libs/email-service/src/tools/design/styles.hbs
  libs/email-service/src/types/index.ts
Labels: automerge

#15472 fix(application-driving-license): Remarks revamped and bugfixes
  libs/api/domains/driving-license/src/lib/graphql/models/drivingLicense.model.ts
  libs/api/domains/driving-license/src/lib/graphql/models/remark.model.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/driving-license.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/driving-license/types.ts
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
  libs/application/templates/driving-license/src/fields/HealthRemarks.tsx
  libs/application/templates/driving-license/src/lib/constants.ts
  libs/application/templates/driving-license/src/lib/types.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.service.ts
  libs/clients/driving-license/src/lib/drivingLicenseApi.types.ts
Labels: automerge

#15473 fix: Enable corepack in `infra/`
  .github/workflows/config-values.yaml
Labels: automerge

#15299 fix(service-portal): remove alt text for decorative images
  apps/service-portal/src/components/DocumentsEmpty/DocumentsEmpty.tsx
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
  libs/service-portal/documents/src/components/DocumentLine/AvatarImage.tsx
  libs/service-portal/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/service-portal/finance/src/screens/FinanceLoans/FinanceLoans.tsx
  libs/service-portal/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
  libs/service-portal/information/src/components/PersonalInformation/Forms/ProfileForm/components/DropModal.tsx
  libs/service-portal/licenses/src/components/LicenseIcon/LicenseIcon.tsx
  libs/service-portal/licenses/src/components/SingleLicenseCard/SingleLicenseCard.tsx
Labels: automerge

#15475 fix: cache
  .github/workflows/config-values.yaml
Labels: automerge

#15477 fix: chart
  .github/workflows/config-values.yaml
Labels: automerge, high priority

#15476 fix(finance): Fix paths
  libs/service-portal/core/src/hooks/useDynamicRoutes/paths.ts
  libs/service-portal/finance/src/financeRedirects.tsx
  libs/service-portal/finance/src/lib/navigation.ts
  libs/service-portal/finance/src/lib/paths.ts
  libs/service-portal/finance/src/module.tsx
Labels: automerge

#15413 fix(ui): Auto open accordion if direct route
  libs/island-ui/core/src/lib/Navigation/Navigation.tsx
Labels: automerge

#14881 feat(endorsement-lists): Order endorsement lists endorsement count and display in overview
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.model.ts
  apps/services/endorsements/api/src/app/modules/endorsementList/endorsementList.service.ts
  libs/api/domains/endorsement-system/src/lib/models/endorsementList.model.ts
  libs/nest/pagination/src/lib/paginate.ts
  libs/service-portal/petitions/src/screens/Petitions/index.tsx
  libs/shared/connected/src/lib/generalPetition/GeneralPetitionLists/useGetPetitionLists.ts
Labels: automerge

#15484 chore: force
  infra/src/common.ts
Labels: automerge

#15487 fix(j-s): Ruling signatures
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmationRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignatureRolesRules.spec.ts
Labels: automerge

#15488 ci: use long sha
  .github/workflows/push.yml
Labels: automerge

#15492 ci: retries on flaky tests
  scripts/ci/30_test.sh
  scripts/ci/_chunk.js
Labels: automerge, test everything

#15496 fix: retag
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge, high priority

#15405 feat(native-app): minor UI fixes
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/home/applications-module.tsx
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/screens/vehicles/components/vehicle-item.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/screens/vehicles/vehicles.tsx
  apps/native/app/src/ui/lib/card/vehicle-card.tsx
  apps/native/app/src/utils/get-main-root.ts
Labels: automerge

#15497 fix(service-portal): action card tag if no heading
  libs/service-portal/core/src/components/ActionCard/ActionCard.tsx
Labels: automerge

#15499 fix: bug
  .github/actions/get-cache/action.yml
  .github/workflows/datadog-analysis.yml
  scripts/ci/cache/__config.mjs
Labels: automerge, high priority, test everything

#15434 fix(j-s): Indictment assigned roles in robot message
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentAssignedRolesToCourt.spec.ts
Labels: automerge

#15500 chore(j-s): Allow pascal case and leading underscore in imports
  .eslintrc.json
Labels: automerge

#15494 chore(j-s): Remove compensation claim
  apps/judicial-system/api/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/backend/migrations/20240710090032-update-defendant.js
  apps/judicial-system/backend/src/app/modules/defendant/dto/updateDefendant.dto.ts
  apps/judicial-system/backend/src/app/modules/defendant/internalDefendant.controller.ts
  apps/judicial-system/backend/src/app/modules/defendant/models/defendant.model.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/dto/subpoena.dto.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/internal/internalCase.response.ts
  apps/judicial-system/digital-mailbox-api/src/app/modules/cases/models/subpoena.response.ts
Labels: automerge

#15482 feat(native-app): Update User Card on More screen
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/ui/index.ts
  apps/native/app/src/ui/lib/card/card.stories.tsx
  apps/native/app/src/ui/lib/card/family-member-card.tsx
  apps/native/app/src/ui/lib/card/user-card.tsx
Labels: automerge

#15469 feat(native-app): disable dark mode
  apps/native/app/src/screens/settings/settings.tsx
  apps/native/app/src/utils/get-theme-with-preferences.ts
Labels: automerge

#15426 fix(native-app): Android users should be able to edit their mileage
  apps/native/app/src/lib/show-picker.ts
  apps/native/app/src/screens/vehicles/components/mileage-cell.tsx
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
  apps/native/app/src/types/react-native.d.ts
Labels: automerge

#15501 fix: using 10 sha
  .github/workflows/push.yml
Labels: automerge, high priority

#15502 fix: retag
  .github/workflows/datadog-analysis.yml
  scripts/ci/00_prepare-base-tags.sh
Labels: automerge, high priority

#15491 fix(j-s): Ruling Signature Roles Rule
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmationGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getRulingSignatureConfirmationRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignatureGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/requestRulingSignatureRolesRules.spec.ts
Labels: automerge

#15438 chore(j-s): Shared Auth Module Config
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/data-sources/backend.ts
  apps/judicial-system/api/src/app/modules/event-log/eventLog.resolver.ts
  apps/judicial-system/api/src/environments/environment.ts
  apps/judicial-system/backend/src/app/app.module.ts
  apps/judicial-system/backend/src/app/modules/case/test/createTestingCaseModule.ts
  apps/judicial-system/backend/src/app/modules/defendant/test/createTestingDefendantModule.ts
  apps/judicial-system/backend/src/app/modules/file/test/createTestingFileModule.ts
  apps/judicial-system/backend/src/app/modules/indictment-count/test/createTestingIndictmentCountModule.ts
  apps/judicial-system/backend/src/app/modules/notification/test/createTestingNotificationModule.ts
  apps/judicial-system/backend/src/app/modules/police/test/createTestingPoliceModule.ts
  apps/judicial-system/backend/src/app/modules/user/test/createTestingUserModule.ts
  apps/judicial-system/backend/src/environments/environment.ts
  libs/judicial-system/auth/src/index.ts
  libs/judicial-system/auth/src/lib/auth.config.ts
  libs/judicial-system/auth/src/lib/auth.module.ts
  libs/judicial-system/auth/src/lib/auth.service.ts
  libs/judicial-system/auth/src/lib/guards/token.guard.ts
  libs/judicial-system/auth/src/lib/jwt.strategy.ts
Labels: automerge

#15456 feat(native-app): inbox screen rewrite
  apps/native/app/src/screens/document-detail/document-detail.tsx
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/ui/lib/card/inbox-card.tsx
Labels: automerge

#15504 fix(native-app): large title on all tab screens now fixed
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/ui/index.ts
Labels: automerge

#15506 fix(native-app): Settings icon should always appear in nav bar on more page
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/utils/get-main-root.ts
Labels: automerge

#15467 feat(native-app): add home screen image to cache
  apps/native/app/src/graphql/queries/profile.graphql
  apps/native/app/src/screens/home/hello-module.tsx
Labels: automerge

#15428 chore(testing): Consolidate container starting and add nice name prefixes
  apps/judicial-system/message-handler/docker-compose.yml
  apps/services/documents/src/app/modules/document-provider/e2e/document-provider.spec.ts
  apps/services/endorsements/api/test/globalSetup.ts
  apps/services/endorsements/api/test/globalTeardown.ts
  apps/services/license-api/src/test/globalSetup.ts
  apps/services/license-api/src/test/globalTeardown.ts
  apps/services/user-notification/docker-compose.yml
  apps/services/user-notification/test/globalSetup.ts
  apps/services/user-notification/test/globalTeardown.ts
  libs/message-queue/README.md
  libs/message-queue/src/lib/channel.spec.ts
  libs/message-queue/src/lib/nest/client.service.ts
  libs/message-queue/src/lib/nest/queue.module.ts
  libs/message-queue/src/lib/nest/queue.service.ts
  libs/message-queue/src/lib/nest/testHelpers.ts
  libs/message-queue/test/globalSetup.ts
  libs/message-queue/test/globalTeardown.ts
  libs/testing/containers/src/lib/testing-containers.ts
Labels: automerge

#15512 feat(user-profile): Catching 404 error for getBankInfoFromIslykill
  libs/application/template-api-modules/src/lib/modules/shared/api/user-profile/user-profile.service.ts
Labels: automerge

#15510 chore(native-app): bump version number to 1.3.1
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
Labels: automerge

#15516 fix(native-app): fix lock screen android bug
  apps/native/app/src/screens/home/applications-module.tsx
  apps/native/app/src/utils/lifecycle/setup-event-handlers.ts
Labels: automerge

#15517 fix(native-app): revert: update nav bar right buttons
  apps/native/app/src/screens/applications/applications.tsx
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/inbox/inbox.tsx
  apps/native/app/src/screens/more/more.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/utils/get-main-root.ts
Labels: automerge

#15457 fix(parental-leave): form stepper
  libs/application/templates/parental-leave/src/forms/EmployerApproval.ts
  libs/application/templates/parental-leave/src/forms/EmployerApproveEdits.ts
  libs/application/templates/parental-leave/src/forms/ParentalLeaveForm.ts
  libs/application/templates/parental-leave/src/forms/Prerequisites.ts
Labels: automerge

#15503 fix(j-s): Linting
  apps/judicial-system/backend/migrations/20210608081018-update-case.js
  apps/judicial-system/backend/migrations/20210831141153-update-case.js
  apps/judicial-system/backend/migrations/20210915100238-update-case.js
  apps/judicial-system/message-handler/src/main.ts
  apps/judicial-system/scheduler/src/main.ts
  apps/judicial-system/web/src/routes/Shared/Cases/useFilter.spec.tsx
  libs/email-service/src/tools/generate-html/generate-html.ts
  libs/email-service/src/types/index.ts
  libs/nova-sms/src/lib/sms.service.spec.ts
Labels: automerge

#15509 chore(j-s): API Config
  apps/judicial-system/api/src/app/app.module.ts
  apps/judicial-system/api/src/app/data-sources/index.ts
  apps/judicial-system/api/src/app/modules/auth/auth.config.ts
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/backend/backend.config.ts
  apps/judicial-system/api/src/app/modules/backend/backend.module.ts
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/backend/index.ts
  apps/judicial-system/api/src/app/modules/case-list/caseList.resolver.ts
  apps/judicial-system/api/src/app/modules/case/case.resolver.ts
  apps/judicial-system/api/src/app/modules/case/limitedAccessCase.resolver.ts
  apps/judicial-system/api/src/app/modules/defendant/defendant.resolver.ts
  apps/judicial-system/api/src/app/modules/event-log/eventLog.resolver.ts
  apps/judicial-system/api/src/app/modules/file/file.resolver.ts
  apps/judicial-system/api/src/app/modules/file/limitedAccessFile.resolver.ts
  apps/judicial-system/api/src/app/modules/index.ts
  apps/judicial-system/api/src/app/modules/indictment-count/indictmentCount.resolver.ts
  apps/judicial-system/api/src/app/modules/institution/institution.resolver.ts
  apps/judicial-system/api/src/app/modules/police/police.resolver.ts
  apps/judicial-system/api/src/app/modules/user/user.resolver.ts
  apps/judicial-system/api/src/environments/environment.ts
  apps/judicial-system/api/src/environments/index.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: automerge

#15474 chore(j-s): ActiveCases table refactoring
  apps/judicial-system/web/src/components/AccordionItems/IndictmentsCaseFilesAccordionItem/IndictmentsCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/components/Table/Table.css.ts
  apps/judicial-system/web/src/components/Table/Table.tsx
  apps/judicial-system/web/src/components/Table/TableSkeleton/TableSkeleton.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.strings.ts
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.css.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.spec.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.strings.ts
  apps/judicial-system/web/src/routes/Shared/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
  package.json
  yarn.lock
Labels: automerge

#15508 feat(j-s): Get connected Indictment cases to merge with
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/case/case.resolver.ts
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getConnectedCases.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getConnectedCasesGuards.spec.ts
  apps/judicial-system/backend/src/app/modules/case/test/caseController/getConnectedCasesRolesRules.spec.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/Conclusion.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/SelectConnectedCase.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/SelectConnectedCase.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Conclusion/connectedCases.graphql
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
  apps/judicial-system/web/src/utils/hooks/useCase/index.ts
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
Labels: automerge

#15524 feat(e2e): Add specific firearm license test step
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/licenses.spec.ts
Labels: automerge

#15521 feat(j-s): Display merged case information on court Overview page
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardIndictment.strings.ts
Labels: automerge

#15528 fix(j-s): Active cases tag
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
Labels: automerge

#15526 feat(j-s): Display connected indictment case files
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/components/AccordionItems/ConnectedCaseFilesAccordionItem/ConnectedCaseFilesAccordionItem.strings.ts
  apps/judicial-system/web/src/components/AccordionItems/ConnectedCaseFilesAccordionItem/ConnectedCaseFilesAccordionItem.tsx
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
Labels: automerge

#15536 feat(estate): refactor custom components
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/estate/src/components/assets/Grieving.tsx
  libs/application/templates/estate/src/fields/Cards/index.tsx
  libs/application/templates/estate/src/fields/DoneImage/index.tsx
  libs/application/templates/estate/src/fields/NotFilledOut/index.tsx
  libs/application/templates/estate/src/fields/index.ts
  libs/application/templates/estate/src/forms/Done.ts
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
  libs/application/templates/estate/src/forms/OverviewSections/attachments.ts
  libs/application/templates/estate/src/forms/OverviewSections/representative.ts
  libs/application/templates/estate/src/lib/messages.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/ImageFormField/ImageFormField.tsx
Labels: automerge

#15540 fix(health-directorate): Markdown for errors and file names
  libs/application/templates/healthcare-work-permit/src/fields/CustomFormConclusionSectionField/index.tsx
  libs/application/templates/healthcare-work-permit/src/lib/messages/error.ts
Labels: automerge

#15542 fix(application-system): adding aosh. prefix to translationsNamespace for contentful
  libs/application/types/src/lib/ApplicationTypes.ts
Labels: automerge

#15544 chore: refactor custom components
  libs/application/templates/public-debt-payment-plan/src/fields/DescriptionWithLink/index.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/EmployerInfo/EmployerInfo.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/EmployerInfo/EmployerInfoDescription.css.ts
  libs/application/templates/public-debt-payment-plan/src/fields/EmployerInfo/EmployerInfoDescription.tsx
  libs/application/templates/public-debt-payment-plan/src/fields/index.ts
  libs/application/templates/public-debt-payment-plan/src/forms/PaymentPlanForm.ts
  libs/application/templates/public-debt-payment-plan/src/lib/messages/employer.ts
Labels: automerge

#15545 fix(health-directorate): Adding #markdown to contentful strings and updating file names that are downloaded
  libs/application/templates/healthcare-work-permit/src/fields/CustomFormConclusionSectionField/index.tsx
  libs/application/templates/healthcare-work-permit/src/lib/messages/error.ts
Labels: automerge

#15547 fix(application-system): Aosh, allow input field for machine license plates to reach uo to 7 values from 6
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#15548 fix(application-system): aosh fixes. Allow for 7 value license plates for machines and adding prefix for contentful
  libs/application/types/src/lib/ApplicationTypes.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
Labels: automerge

#15543 chore: refactor bullets custom component
  libs/application/templates/driving-license/src/fields/Done/Declined.tsx
  libs/application/templates/driving-license/src/fields/QualityPhoto/Bullets/Bullets.tsx
  libs/application/templates/driving-license/src/fields/QualityPhoto/index.tsx
  libs/application/templates/driving-license/src/fields/index.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionQualityPhoto.ts
  libs/application/templates/driving-license/src/lib/messages.ts
Labels: automerge

#15522 feat(e2e): update occupational e2e tests
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/mocks/occupationalLicenses.mock.ts
  apps/system-e2e/src/tests/islandis/service-portal/acceptance/occupational-licenses.spec.ts
  libs/api/domains/occupational-licenses/src/lib/occupationalLicenses.service.ts
Labels: automerge

#15532 fix(occupational-licenses): Optional profession
  libs/api/domains/occupational-licenses-v2/src/lib/models/license.model.ts
  libs/api/domains/occupational-licenses-v2/src/lib/occupationalLicensesV2.service.ts
Labels: automerge

#15553 feat(ojoi): update schema and cleanup code
  libs/api/domains/official-journal-of-iceland/src/index.ts
  libs/api/domains/official-journal-of-iceland/src/lib/mapper.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.input.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.model.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.resolver.ts
  libs/api/domains/official-journal-of-iceland/src/lib/officialJournalOfIceland.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/official-journal-of-iceland/official-journal-of-iceland.service.ts
  libs/clients/official-journal-of-iceland/public/src/clientConfig.json
  libs/clients/official-journal-of-iceland/public/src/lib/officialJournalOfIcelandClient.service.ts
Labels: automerge

#15551 chore(university-gateway): Changing program mode of delivery
  apps/services/university-gateway/migrations/20240607123131-remove-undefined-mode-of-delivery.js
  apps/services/university-gateway/migrations/20240607123132-change-application-mode-of-delivery.js
  apps/services/university-gateway/src/app/modules/application/model/application.ts
  apps/services/university-gateway/src/app/modules/application/universityApplication.service.ts
  libs/university-gateway/src/lib/types/modeOfDelivery.ts
Labels: automerge

#15554 feat(search-indexer): Webpack config change lead to us not being able to start the search-indexer locally
  apps/services/search-indexer/webpack.config.js
Labels: automerge

#15558 fix(university-gateway): Removed fetch timeout
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/agriculturalUniversityOfIcelandClient.config.ts
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/apiConfiguration.ts
  libs/clients/university-application/bifrost-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.config.ts
  libs/clients/university-application/holar-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/holar-university/src/lib/holarUniversityClient.config.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/apiConfiguration.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/icelandUniversityOfTheArtsClient.config.ts
  libs/clients/university-application/reykjavik-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/reykjavik-university/src/lib/reykjavikUniversityClient.config.ts
  libs/clients/university-application/university-of-akureyri/src/lib/apiConfiguration.ts
  libs/clients/university-application/university-of-akureyri/src/lib/universityOfAkureyriClient.config.ts
  libs/clients/university-application/university-of-iceland/src/lib/apiConfiguration.ts
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.config.ts
Labels: automerge

#15559 fix(university-gateway): Removed fetch timeout
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/agriculturalUniversityOfIcelandClient.config.ts
  libs/clients/university-application/agricultural-university-of-iceland/src/lib/apiConfiguration.ts
  libs/clients/university-application/bifrost-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/bifrost-university/src/lib/bifrostUniversityClient.config.ts
  libs/clients/university-application/holar-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/holar-university/src/lib/holarUniversityClient.config.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/apiConfiguration.ts
  libs/clients/university-application/iceland-university-of-the-arts/src/lib/icelandUniversityOfTheArtsClient.config.ts
  libs/clients/university-application/reykjavik-university/src/lib/apiConfiguration.ts
  libs/clients/university-application/reykjavik-university/src/lib/reykjavikUniversityClient.config.ts
  libs/clients/university-application/university-of-akureyri/src/lib/apiConfiguration.ts
  libs/clients/university-application/university-of-akureyri/src/lib/universityOfAkureyriClient.config.ts
  libs/clients/university-application/university-of-iceland/src/lib/apiConfiguration.ts
  libs/clients/university-application/university-of-iceland/src/lib/universityOfIcelandClient.config.ts
Labels: automerge

#15541 chore(login-service): refactor custom components
  libs/application/templates/login-service/src/fields/FieldTitle/FieldTitle.tsx
  libs/application/templates/login-service/src/fields/Illustrations/CompanyIllustration.tsx
  libs/application/templates/login-service/src/fields/Overview/Overview.tsx
  libs/application/templates/login-service/src/fields/TermsOfAgreement/TermsOfAgreement.tsx
  libs/application/templates/login-service/src/fields/index.ts
  libs/application/templates/login-service/src/forms/LoginServiceForm.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
Labels: automerge

#15555 feat(web): Allow ChartNumberBox to be embedded as a 'slice'
  apps/web/components/Organization/Slice/SliceMachine.tsx
Labels: automerge

#15539 chore(document-provider): refactor custom components
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/document-provider-onboarding/src/assets/ManOnBenchIllustration.tsx
  libs/application/templates/document-provider-onboarding/src/assets/WomanWithLaptopIllustration.tsx
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/RejectionScreen/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/Review/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/TermsOfAgreement/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/DocumentProvicerApplication/ThankYouScreen/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/Illustrations/ManOnBenchIllustration.tsx
  libs/application/templates/document-provider-onboarding/src/fields/Illustrations/ManOnBenchIllustrationPeriods.tsx
  libs/application/templates/document-provider-onboarding/src/fields/Illustrations/WomanWithLaptopIllustration.tsx
  libs/application/templates/document-provider-onboarding/src/fields/Illustrations/WomanWithLaptopIllustrationPeriods.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/AutomatedTests/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/InfoScreen.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/ProdEndpoint/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/ProdEnvironment/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/TechnicalImplementation/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/TestEndPoint/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/TestPhase/TestEnvironment/index.tsx
  libs/application/templates/document-provider-onboarding/src/fields/index.ts
  libs/application/templates/document-provider-onboarding/src/forms/DocumentProviderApplication.ts
  libs/application/templates/document-provider-onboarding/src/forms/Finished.ts
  libs/application/templates/document-provider-onboarding/src/forms/PendingReview.ts
  libs/application/templates/document-provider-onboarding/src/forms/Rejected.ts
  libs/application/templates/document-provider-onboarding/src/forms/ReviewApplication.ts
  libs/application/templates/document-provider-onboarding/src/forms/TestPhase.ts
  libs/application/templates/document-provider-onboarding/src/lib/DocumentProviderOnboardingTemplate.ts
  libs/application/templates/document-provider-onboarding/src/lib/dataSchema.ts
  libs/application/templates/document-provider-onboarding/src/lib/messages.ts
  libs/application/templates/document-provider-onboarding/src/lib/types.ts
  libs/application/templates/estate/src/forms/Done.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/DescriptionFormField/DescriptionFormField.tsx
  libs/application/ui-fields/src/lib/ImageFormField/ImageFormField.css.ts
  libs/application/ui-fields/src/lib/ImageFormField/ImageFormField.tsx
  libs/application/ui-fields/src/lib/LinkFormField/LinkFormField.tsx
Labels: automerge

#15562 feat(ojoi): Adding pdf methods to client
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.resolver.ts
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.service.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getPdfResponse.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getPdfUrlResponse.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/clients/official-journal-of-iceland/application/src/clientConfig.json
  libs/clients/official-journal-of-iceland/application/src/lib/ojoiApplicationClient.service.ts
Labels: automerge

#15391 feat(web): Add divider check for bullet list
  apps/web/components/BulletList/BulletList.tsx
  apps/web/components/Organization/Slice/BulletList/BulletList.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/bulletListSlice.model.ts
Labels: automerge

#15566 fix(island-ui): Change unstable_autoFocusOnHide prop to lowercase
  libs/island-ui/core/src/lib/DropdownMenu/useMenuHoverProps.tsx
Labels: automerge

#15565 fix(services-endorsements-api): Postnumer fix
  apps/services/endorsements/api/src/app/modules/endorsement/endorsement.service.ts
Labels: automerge
