Repository island-is/island.is, pull requests merged in 2025-06, with the labels that each got.

#19121 feat(driving-instructors-registrations): Updated view for "View student"
  libs/application/templates/driving-instructor-registrations/src/fields/FindStudentModal/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/StudentsOverview/index.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/Skeleton.tsx
  libs/application/templates/driving-instructor-registrations/src/fields/ViewStudent/index.tsx
  libs/application/templates/driving-instructor-registrations/src/lib/messages.ts
Labels: stale

#19256 fix(web): Organization Page - Bottom slices spacing
  apps/web/screens/Organization/Home/Home.tsx
Labels: dirty bypass

#19244 fix(island-ui): Stop waiting for client mount until icon appears
  libs/island-ui/core/src/lib/IconRC/Icon.tsx
Labels: deploy-feature

#19211 chore(ci): `runs-on` caching and envs
  .github/actions/load-deps/action.yml
  .github/actions/setup-yarn/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/dedupe.yml
  .github/workflows/docker.yml
  .github/workflows/feature-close.yml
  .github/workflows/install.yml
  .github/workflows/merge-queue.yml
  .github/workflows/pre-checks.yml
  .github/workflows/pullrequest-close.yml
  .github/workflows/pullrequest-meta.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/ci/generate-files.mjs
Labels: deploy-feature, test everything, dirty bypass

#18934 fix(license-service): new passport endpoint for all documents
  libs/api/domains/license-service/src/lib/mappers/identityDocumentMapper.ts
  libs/api/domains/license-service/src/lib/mappers/passportMapper.ts
  libs/clients/license-client/src/lib/clients/passport-client/passportsClient.service.ts
  libs/clients/passports/src/lib/passportsApi.service.ts
  libs/clients/passports/src/lib/passportsApi.types.ts
Labels: deploy-feature, dirty bypass

#19309 feat(web): Organization parent subpages added to search results
  apps/web/components/SearchInput/SearchInput.tsx
  apps/web/screens/Search/Search.tsx
  apps/web/screens/queries/Search.tsx
  libs/api/domains/content-search/src/lib/models/searchResult.model.ts
  libs/cms/src/index.ts
  libs/cms/src/lib/environments/environment.ts
  libs/cms/src/lib/models/organizationParentSubpage.model.ts
  libs/cms/src/lib/search/cmsSync.module.ts
  libs/cms/src/lib/search/importers/organizationParentSubpage.service.ts
  libs/cms/src/lib/search/importers/organizationSubpage.service.ts
  libs/cms/src/lib/search/mapping.service.ts
  libs/content-search-toolkit/src/queries/search.ts
  libs/shared/types/src/lib/searchable-content-types.ts
Labels: dirty bypass

#19396 chore(samrit): disable thjodskra photos for now (with feature flag)
  libs/application/templates/driving-license-duplicate/src/forms/application.ts
  libs/application/templates/driving-license-duplicate/src/forms/sections/sectionDataProviders.ts
  libs/application/templates/driving-license-duplicate/src/lib/drivingLicenseDuplicateTemplate.ts
  libs/application/templates/driving-license-duplicate/src/lib/getApplicationFeatureFlags.ts
Labels: deploy-feature

#19426 chore(ci): Move newlints to scripts
  .github/workflows/pullrequest.yml
  scripts/ci/compare-lints.sh
  scripts/ci/lint-and-parse.sh
Labels: dirty bypass

#19292 ci: Caching and cleaning
  .github/actions/cache/action.yml
  .github/actions/get-cache/action.yml
  .github/actions/load-deps/action.yml
  .github/actions/setup-yarn/action.yml
  .github/actions/unit-test/action.yml
  .github/workflows/config-values.yaml
  .github/workflows/install.yml
  .github/workflows/merge-queue.yml
  .github/workflows/pre-checks.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  .gitignore
  scripts/ci/cache/.yarn/patches/@actions-cache-npm-3.2.4-c57b047f14.patch
  scripts/ci/cache/__config.mjs
  scripts/ci/cache/_common.mjs
  scripts/ci/cache/_const.mjs
  scripts/ci/cache/_generated_files.mjs
  scripts/ci/cache/_get_hashes_utils.mjs
  scripts/ci/cache/_key_storage.mjs
  scripts/ci/cache/_restore_cache.mjs
  scripts/ci/cache/_save_cache.mjs
  scripts/ci/cache/_utils.mjs
  scripts/ci/cache/cache-action.mjs
  scripts/ci/cache/generate-files.sh
  scripts/ci/cache/package.json
  scripts/ci/cache/yarn.lock
  scripts/ci/generate-files.mjs
Labels: test everything

#19453 fix(ci): Improved compare-lints.sh
  scripts/ci/compare-lints.sh
  scripts/ci/lint-and-parse.sh
Labels: test nothing
