Repository island-is/island.is, pull requests merged in 2025-02, with the labels that each got.

#17756 fix(marriage-conditions): switched codes setup in template
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
Labels: deploy-feature

#17752 fix(application-ir): Percentages Rounding
  libs/application/templates/inheritance-report/src/fields/HeirsRepeater/index.tsx
Labels: deploy-feature

#17781 chore(ci): Refactor Dockerfile (v3)
  scripts/ci/Dockerfile
Labels: deploy-feature, test everything

#17776 feat(web): Add new component for latest news at digital iceland
  apps/web/components/Organization/Slice/LatestEventsSlice/LatestEventsSlice.tsx
  apps/web/components/Organization/Slice/LatestNewsSlice/DigitalIcelandLatestNewsSlice/DigitalIcelandLatestNewsSlice.css.ts
  apps/web/components/Organization/Slice/LatestNewsSlice/DigitalIcelandLatestNewsSlice/DigitalIcelandLatestNewsSlice.tsx
  apps/web/components/Organization/Slice/LatestNewsSlice/DigitalIcelandLatestNewsSlice/index.ts
  apps/web/components/real.ts
  apps/web/screens/Organization/Home/Home.tsx
Labels: deploy-feature

#17697 feat(j-s): Send civil claim to RLS
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.module.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/createTestingSubpoenaModule.ts
Labels: skip-nx-cache

#17863 ci: fix docker layer cache
  .dockerignore
  .github/actions/get-cache/action.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  .gitignore
  .yarn/releases/yarn-3.2.3.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  infra/scripts/build-docker-container.sh
  infra/yarn.lock
  package.json
  scripts/ci/09_load-buildkit-driver.sh
  scripts/ci/10_prepare-docker-deps.sh
  scripts/ci/Dockerfile
  scripts/ci/_docker.sh
  scripts/ci/cache/__config.mjs
  scripts/ci/cache/generate-files.sh
  scripts/ci/cache/yarn.lock
  scripts/ci/generate-docker-chunks.sh
  scripts/ci/generate-files.mjs
  scripts/ci/run-in-parallel.sh
  yarn.lock
Labels: deploy-feature

#17868 feat: Add label for skipping all affected checks
  .github/workflows/pullrequest.yml
  scripts/ci/generate-chunks.sh
  scripts/ci/generate-docker-chunks.sh
Labels: deploy-feature, test nothing

#17898 fix(application-system): Improving logging context for application controller
  apps/application-system/api/src/app/modules/application/application.controller.ts
Labels: deploy-feature

#15436 chore(core): Update ConfigCat version
  apps/native/app/package.json
  apps/native/app/src/contexts/feature-flag-provider.tsx
  libs/feature-flags/src/lib/types.ts
  libs/feature-flags/test/environment.jest.ts
  package.json
  yarn.lock
Labels: test everything

#17974 chore(coderabbit): Add path filters
  .coderabbit.yaml
Labels: test nothing

#17972 ci: Add `static-base` layer for caching
  scripts/ci/Dockerfile
Labels: deploy-feature, test everything

#17779 feat(ci): Use new docker build
  .github/workflows/docker.yml
  scripts/ci/generate-chunks.sh
Labels: deploy-feature, test everything, ci debug

#18026 ci(merge-queue): fix test-everything
  .github/actions/test-everything/action.yml
  .github/workflows/install.yml
  .github/workflows/push.yml
  scripts/ci/generate-docker-chunks.sh
Labels: test everything

#18051 ci: fix features
  .github/actions/feature-checkout/action.yml
  .github/actions/set-shas/action.yml
  .github/workflows/install.yml
  .github/workflows/push.yml
  scripts/ci/generate-chunks.sh
  scripts/ci/generate-docker-chunks.sh
Labels: deploy-feature, chunks-debug

#18073 fix(react-spa): Bff poller pass param with request
  libs/react-spa/bff/src/lib/BffPoller.tsx
Labels: autoupdate

#18046 feat(j-s): add other traffic offense as an option
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCountEnum.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/lib/getIncidentDescription.ts
  apps/judicial-system/web/src/utils/hooks/useCase/createCase.graphql
  libs/judicial-system/types/src/lib/indictmentCount.ts
Labels: skip-nx-cache

#18119 chore: Replace Datadog RUM with Error Tracking
  apps/air-discount-scheme/web/infra/web.ts
  apps/air-discount-scheme/web/next.config.js
  apps/air-discount-scheme/web/pages/_app.tsx
  apps/application-system/form/infra/application-system-form.ts
  apps/application-system/form/src/environments/environment.ts
  apps/application-system/form/src/main.tsx
  apps/consultation-portal/infra/samradsgatt.ts
  apps/consultation-portal/next.config.js
  apps/judicial-system/web/pages/_app.tsx
  apps/native/app/src/utils/lifecycle/setup-globals.ts
  apps/portals/admin/infra/portals-admin.ts
  apps/portals/admin/src/environments/environment.ts
  apps/portals/admin/src/main.tsx
  apps/portals/my-pages/infra/portals-my-pages.ts
  apps/portals/my-pages/src/Main.tsx
  apps/portals/my-pages/src/environments/environment.ts
  apps/skilavottord/web/infra/skilavottord-web.ts
  apps/skilavottord/web/next.config.js
  apps/skilavottord/web/pages/_app.tsx
  apps/web/infra/web.ts
  apps/web/layouts/main.tsx
  apps/web/next.config.js
  charts/islandis-services/air-discount-scheme-web/values.dev.yaml
  charts/islandis-services/air-discount-scheme-web/values.prod.yaml
  charts/islandis-services/air-discount-scheme-web/values.staging.yaml
  charts/islandis-services/application-system-form/values.dev.yaml
  charts/islandis-services/application-system-form/values.prod.yaml
  charts/islandis-services/application-system-form/values.staging.yaml
  charts/islandis-services/consultation-portal/values.dev.yaml
  charts/islandis-services/consultation-portal/values.prod.yaml
  charts/islandis-services/consultation-portal/values.staging.yaml
  charts/islandis-services/portals-admin/values.dev.yaml
  charts/islandis-services/portals-admin/values.prod.yaml
  charts/islandis-services/portals-admin/values.staging.yaml
  charts/islandis-services/service-portal/values.dev.yaml
  charts/islandis-services/service-portal/values.prod.yaml
  charts/islandis-services/service-portal/values.staging.yaml
  charts/islandis-services/skilavottord-web/values.dev.yaml
  charts/islandis-services/skilavottord-web/values.prod.yaml
  charts/islandis-services/skilavottord-web/values.staging.yaml
  charts/islandis-services/web/values.dev.yaml
  charts/islandis-services/web/values.prod.yaml
  charts/islandis-services/web/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  libs/user-monitoring/src/lib/user-monitoring.ts
  package.json
  yarn.lock
Labels: deploy-feature
