Repository island-is/island.is, pull requests merged in 2025-04, with the labels that each got.

#18648 fix(native-app): send locale of app in notifications query
  apps/native/app/src/graphql/queries/notifications.graphql
  apps/native/app/src/screens/notifications/notifications.tsx
  apps/native/app/src/stores/notifications-store.ts
Labels: dirty bypass

#18428 feat(native-app): add support for id cards and use only one screen/route for all licenses
  apps/native/app/src/graphql/fragments/license.fragment.graphql
  apps/native/app/src/lib/deep-linking.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/wallet-pass/wallet-pass.constants.ts
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/screens/wallet-passport/wallet-passport.tsx
  apps/native/app/src/screens/wallet/components/wallet-item.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/ui/assets/card/nafnskirteini-bg.png
  apps/native/app/src/ui/assets/card/nafnskirteini-bg@2x.png
  apps/native/app/src/ui/assets/card/nafnskirteini-bg@3x.png
  apps/native/app/src/ui/lib/card/license-card.tsx
  apps/native/app/src/ui/lib/card/license-list-card.tsx
  apps/native/app/src/utils/lifecycle/setup-components.tsx
  apps/native/app/src/utils/lifecycle/setup-routes.ts
Labels: dirty bypass

#18651 fix(ojoi): Fixes in ui for application and web OJOI.
  apps/web/screens/OfficialJournalOfIceland/OJOIAdvert.tsx
  apps/web/screens/OfficialJournalOfIceland/OJOISearch.tsx
  apps/web/screens/queries/OfficialJournalOfIceland.ts
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.service.ts
  libs/api/domains/official-journal-of-iceland/src/lib/models/advert.model.ts
  libs/application/templates/official-journal-of-iceland/src/screens/InvolvedPartyScreen.tsx
  libs/clients/official-journal-of-iceland/application/src/clientConfig.json
  libs/clients/official-journal-of-iceland/public/src/clientConfig.json
Labels: dirty bypass

#18649 fix(form-system): add support for redis in infra
  apps/services/form-system/infra/form-system.ts
  apps/services/form-system/src/app/modules/applications/applications.controller.ts
  apps/services/form-system/src/app/modules/applications/applications.service.ts
  apps/services/form-system/src/app/modules/forms/forms.service.ts
  charts/islandis-services/services-form-system-api/values.dev.yaml
  charts/islandis/values.dev.yaml
  libs/portals/form-system/graphql/src/lib/client.ts
  libs/portals/form-system/ui-components/src/components/field-components/List/List.tsx
  libs/portals/form-system/ui-components/src/components/form-stepper/formStepper.tsx
Labels: dirty bypass

#18656 feat(j-s): Stop disabling certain fields
  apps/judicial-system/web/src/routes/Court/Indictments/Completed/Completed.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
Labels: dirty bypass

#18645 fix(seminars): field updates
  libs/application/templates/aosh/seminars/src/fields/Participants/index.tsx
  libs/application/templates/aosh/seminars/src/forms/SeminarRegistrationForm/Overview/index.ts
  libs/application/templates/aosh/seminars/src/forms/SeminarRegistrationForm/ParticipantsSection/index.ts
  libs/application/templates/aosh/seminars/src/forms/SeminarRegistrationForm/PaymentArrangement/index.ts
  libs/application/templates/aosh/seminars/src/forms/SeminarRegistrationForm/PersonalInformation/index.ts
  libs/application/templates/aosh/seminars/src/hooks/useLazyQuery.ts
  libs/application/templates/aosh/seminars/src/lib/dataSchema.ts
  libs/application/templates/aosh/seminars/src/lib/messages/overview.ts
  libs/application/templates/aosh/seminars/src/lib/messages/participants.ts
  libs/application/templates/aosh/seminars/src/lib/messages/paymentArrangement.ts
  libs/application/templates/aosh/seminars/src/lib/messages/personal.ts
  libs/application/templates/aosh/seminars/src/utils/getPaymentArrangementForOverview.ts
  libs/application/templates/aosh/seminars/src/utils/submitTableForm.ts
  libs/application/templates/aosh/seminars/src/utils/updateOrAddList.ts
Labels: dirty bypass

#18583 feat(j-s): Button to switch institutions
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/components/UserProvider/UserProvider.tsx
  libs/island-ui/core/src/lib/Header/UserDropdown/UserDropdown.tsx
  libs/island-ui/core/src/lib/Header/UserMenu/UserMenu.tsx
Labels: dirty bypass

#18665 fix(form-system): fix redis error
  apps/services/form-system/infra/form-system.ts
  charts/islandis-services/services-form-system-api/values.dev.yaml
  charts/islandis/values.dev.yaml
  libs/api/domains/form-system/src/lib/forms/forms.service.ts
Labels: dirty bypass

#18671 fix(form-system): remove cmsConfig from api
  apps/services/form-system/infra/form-system.ts
  apps/services/form-system/src/app/app.module.ts
  apps/services/form-system/src/app/modules/forms/forms.module.ts
  charts/islandis-services/services-form-system-api/values.dev.yaml
  charts/islandis/values.dev.yaml
Labels: dirty bypass

#18582 fix(my-pages-social-insurance-maintenance): update payment plan UI
  libs/api/domains/social-insurance/src/lib/models/payments/paymentGroupType.model.ts
  libs/api/domains/social-insurance/src/lib/models/payments/paymentPlan.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/clients/social-insurance-administration/src/clientConfig.json
  libs/portals/my-pages/core/src/components/ScrollableMiddleTable/ScrollableMiddleTable.css.ts
  libs/portals/my-pages/core/src/components/ScrollableMiddleTable/ScrollableMiddleTable.tsx
  libs/portals/my-pages/core/src/index.ts
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.css.ts
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.graphql
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTableRow.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/components/index.ts
  libs/portals/my-pages/social-insurance-maintenance/src/lib/messages.ts
Labels: dirty bypass

#18670 fix(j-s): e2e test
  apps/system-e2e/src/tests/judicial-system/regression/indictment-tests.spec.ts
Labels: dirty bypass

#18674 feat(web): Pension Calculator - Change text to markdown
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/SocialInsuranceAdministration/translationStrings.ts
Labels: dirty bypass

#18668 fix(ojoi): Save HTML as base 64
  libs/application/templates/official-journal-of-iceland/src/components/additions/Additions.tsx
  libs/application/templates/official-journal-of-iceland/src/components/input/OJOIHtmlController.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/AdvertModal.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Preview.tsx
Labels: dirty bypass

#18646 feat(j-s): Upload court files on behalf of case representatives in court
  apps/judicial-system/api/src/app/modules/case/index.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/api/src/app/modules/case/models/caseRepresentative.model.ts
  apps/judicial-system/api/src/app/modules/file/dto/createFile.input.ts
  apps/judicial-system/api/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/migrations/20250318105658-update-case-files.js
  apps/judicial-system/backend/migrations/20250402155933-update-case-file.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/interceptors/case.interceptor.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/backend/src/app/modules/file/dto/createFile.dto.ts
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/guards/caseFileCategory.ts
  apps/judicial-system/backend/src/app/modules/file/guards/test/limitedAccessViewCaseFileGuard.spec.ts
  apps/judicial-system/backend/src/app/modules/file/models/file.model.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
  apps/judicial-system/web/messages/Core/tables.ts
  apps/judicial-system/web/pages/domur/akaera/gogn/[id].ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.strings.ts
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.tsx
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.css.ts
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/AddFiles/AddFiles.strings.ts
  apps/judicial-system/web/src/routes/Shared/AddFiles/AddFiles.tsx
  apps/judicial-system/web/src/routes/Shared/AddFiles/SelectCaseFileRepresentative.css.ts
  apps/judicial-system/web/src/routes/Shared/AddFiles/SelectCaseFileRepresentative.tsx
  apps/judicial-system/web/src/utils/hooks/useS3Upload/useS3Upload.ts
  libs/judicial-system/consts/src/lib/consts.ts
  libs/judicial-system/formatters/src/lib/formatters.ts
  libs/judicial-system/types/src/lib/file.ts
Labels: dirty bypass

#18667 fix(clients-national-registry-v3-app): Update client config and endpoint
  charts/islandis-services/api/values.dev.yaml
  charts/islandis-services/api/values.prod.yaml
  charts/islandis-services/api/values.staging.yaml
  charts/islandis-services/application-system-api/values.dev.yaml
  charts/islandis-services/application-system-api/values.prod.yaml
  charts/islandis-services/application-system-api/values.staging.yaml
  charts/islandis-services/endorsement-system-api/values.dev.yaml
  charts/islandis-services/endorsement-system-api/values.prod.yaml
  charts/islandis-services/endorsement-system-api/values.staging.yaml
  charts/islandis-services/regulations-admin-backend/values.dev.yaml
  charts/islandis-services/regulations-admin-backend/values.prod.yaml
  charts/islandis-services/regulations-admin-backend/values.staging.yaml
  charts/islandis-services/service-portal-api/values.dev.yaml
  charts/islandis-services/service-portal-api/values.prod.yaml
  charts/islandis-services/service-portal-api/values.staging.yaml
  charts/islandis-services/user-notification-worker/values.dev.yaml
  charts/islandis-services/user-notification-worker/values.prod.yaml
  charts/islandis-services/user-notification-worker/values.staging.yaml
  charts/islandis-services/user-notification/values.dev.yaml
  charts/islandis-services/user-notification/values.prod.yaml
  charts/islandis-services/user-notification/values.staging.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/dsl/xroad.ts
  libs/clients/national-registry/v3-applications/src/clientConfig.json
  libs/clients/national-registry/v3-applications/src/lib/nationalRegistryV3Applications.config.ts
  libs/clients/national-registry/v3-applications/src/lib/nationalRegistryV3Applications.service.ts
  libs/clients/national-registry/v3-applications/src/lib/providers.ts
Labels: dirty bypass

#18678 fix(native-app): fix wallet identity document fetching
  apps/native/app/src/screens/home/home.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
Labels: dirty bypass

#18680 chore(native-app): bump app version to 1.5.4
  apps/native/app/android/app/build.gradle
  apps/native/app/ios/IslandApp/Info.plist
Labels: dirty bypass

#18681 fix(native-app): filter out empty states in licenses module on home screen
  apps/native/app/src/screens/home/licenses-module.tsx
Labels: dirty bypass

#18679 feat(native-app): reset all preferences on logout
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/stores/preferences-store.ts
Labels: dirty bypass

#18682 feat(native-app): save pin retries in preferences store
  apps/native/app/src/screens/app-lock/app-lock.tsx
  apps/native/app/src/stores/preferences-store.ts
Labels: dirty bypass

#18662 fix(estate): adding advocate 2 for einkaskipti
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/mappers.ts
  libs/application/templates/estate/src/fields/EstateMembersRepeater/AdditionalEstateMember.tsx
  libs/application/templates/estate/src/forms/OverviewSections/commonFields.ts
  libs/application/templates/estate/src/forms/OverviewSections/representative.ts
  libs/application/templates/estate/src/forms/Sections/deceasedInfoFields.ts
  libs/application/templates/estate/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
Labels: dirty bypass

#18688 fix(identity-documents): Fix up mapping
  libs/api/domains/license-service/src/lib/mappers/identityDocumentMapper.ts
Labels: dirty bypass

#18694 fix(j-s): small improvement for casefile table if submission date is not present
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.tsx
Labels: dirty bypass

#18618 feat(ojoi): dynamic loading of ojoi subpages
  apps/web/pages/stjornartidindi/[slug]/index.ts
  apps/web/pages/stjornartidindi/um/index.ts
  apps/web/screens/CustomPage/CustomSubpageWrapper.tsx
  apps/web/screens/CustomPage/index.ts
  apps/web/screens/OfficialJournalOfIceland/OJOIAbout.tsx
  apps/web/screens/OfficialJournalOfIceland/OJOIHelp.tsx
  apps/web/screens/OfficialJournalOfIceland/OJOISubpage.tsx
  apps/web/screens/OfficialJournalOfIceland/constants.ts
Labels: dirty bypass

#18704 fix(services-cms-importer): publish entry if applicable
  apps/services/cms-importer/src/app/constants.ts
  apps/services/cms-importer/src/app/modules/managementClient/managementClient.service.ts
  apps/services/cms-importer/src/app/repositories/cms.repository.ts
Labels: dirty bypass

#18734 fix(ojoi): changing text of signatureDate
  apps/web/screens/OfficialJournalOfIceland/OJOIAdvert.tsx
  apps/web/screens/OfficialJournalOfIceland/messages.ts
Labels: dirty bypass

#18695 feat(application-system): New payments
  apps/application-system/api/infra/application-system-api.ts
  apps/application-system/api/src/app/app.module.ts
  apps/application-system/api/src/app/modules/application/lifecycle/application-lifecycle.module.ts
  apps/services/payments/infra/payments.ts
  apps/services/payments/src/environments/environment.ts
  charts/islandis-services/application-system-api-worker/values.dev.yaml
  charts/islandis-services/application-system-api-worker/values.prod.yaml
  charts/islandis-services/application-system-api-worker/values.staging.yaml
  charts/islandis-services/application-system-api/values.dev.yaml
  charts/islandis-services/application-system-api/values.prod.yaml
  charts/islandis-services/application-system-api/values.staging.yaml
  charts/islandis-services/services-payments/values.dev.yaml
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  infra/src/uber-charts/islandis.ts
  libs/api/domains/payment/src/lib/api-domains-payment.types.ts
  libs/application/api/payment/src/lib/payment-callback.controller.ts
  libs/application/api/payment/src/lib/payment.config.ts
  libs/application/api/payment/src/lib/payment.module.ts
  libs/application/api/payment/src/lib/payment.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/api/payment/payment.service.ts
  libs/application/template-api-modules/src/lib/modules/shared/shared.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/example-payment-actions/examplePaymentActions.service.ts
  libs/application/ui-components/src/components/PaymentPending/PaymentPending.tsx
  libs/feature-flags/src/lib/features.ts
  scripts/codegen.js
Labels: deploy-feature

#18748 feat(rental-agreement): Validate changed unit values and update api path
  libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableRow.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableUnits.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/index.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/propertySearch.css.ts
  libs/application/templates/rental-agreement/src/lib/constants.ts
  libs/application/templates/rental-agreement/src/lib/dataSchema.ts
  libs/application/templates/rental-agreement/src/lib/messages/housing/registerProperty.ts
  libs/clients/hms/src/lib/hms.config.ts
  libs/clients/hms/src/lib/hms.provider.ts
Labels: dirty bypass

#18545 fix(application-system-api): Using credential provider node for s3 clients
  libs/nest/aws/src/lib/aws.module.ts
Labels: deploy-feature

#18778 fix(j-s): Alternative Service Defender
  apps/judicial-system/web/src/components/ServiceAnnouncement/ServiceAnnouncements.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Defender/Cases/defenderCases.graphql
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: dirty bypass

#18719 chore(j-s): Add img file extensions for additional file upload
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.strings.ts
  apps/judicial-system/web/src/components/UploadFiles/UploadFiles.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Overview/Overview.tsx
Labels: dirty bypass

#18690 feat(j-s): add legal right protector in court for victim
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/VictimInfo/LegalRightsProtectorInputFields.tsx
  apps/judicial-system/web/src/components/VictimInfo/VictimInfo.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/utils/hooks/useVictim/index.ts
Labels: dirty bypass

#18712 feat(j-s): Local User Admin
  apps/judicial-system/backend/migrations/20250407144915-update-user.js
  apps/judicial-system/backend/src/app/modules/user/user.model.ts
  apps/judicial-system/web/src/routes/Admin/ChangeUser/updateUser.graphql
  apps/judicial-system/web/src/routes/Admin/NewUser/NewUser.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.css.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  apps/judicial-system/web/src/routes/Admin/userRoleToString.ts
  apps/judicial-system/web/src/routes/Shared/Landing/Landing.tsx
  libs/judicial-system/types/src/lib/user.ts
Labels: dirty bypass

#18804 fix(rental-agreement): Updates and fixes
  .github/CODEOWNERS
  libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertySearchInput.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableRow.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/components/PropertyTableUnits.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/index.tsx
  libs/application/templates/rental-agreement/src/fields/PropertySearch/propertyData.ts
  libs/application/templates/rental-agreement/src/fields/Summary/ApplicantsRepresentativesSummary.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/ApplicantsSummary.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/OtherFeesSummary.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/PropertyInfoSummary.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/RentalInfoSummary.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/SummaryEdit.tsx
  libs/application/templates/rental-agreement/src/fields/Summary/summaryStyles.css.ts
  libs/application/templates/rental-agreement/src/forms/draft/rentalHousing/rentalHousingUserRole.ts
  libs/application/templates/rental-agreement/src/forms/draft/rentalPeriod/rentalPeriodDetails.ts
  libs/application/templates/rental-agreement/src/forms/draft/rentalPeriod/rentalPeriodOtherFees.ts
  libs/application/templates/rental-agreement/src/forms/draft/summaryDraftSection.ts
  libs/application/templates/rental-agreement/src/forms/inReview/preSignatureInfoSection.ts
  libs/application/templates/rental-agreement/src/forms/inReview/reviewInfoSection.ts
  libs/application/templates/rental-agreement/src/forms/inReview/summaryNoEditSection.ts
  libs/application/templates/rental-agreement/src/forms/prerequisites/externalData.ts
  libs/application/templates/rental-agreement/src/forms/signing/signingSection.ts
  libs/application/templates/rental-agreement/src/forms/summaryForm.ts
  libs/application/templates/rental-agreement/src/lib/RentalAgreementTemplate.ts
  libs/application/templates/rental-agreement/src/lib/constants.ts
  libs/application/templates/rental-agreement/src/lib/dataSchema.ts
  libs/application/templates/rental-agreement/src/lib/getAssigneesNationalIdList.ts
  libs/application/templates/rental-agreement/src/lib/messages/housing/housingCondition.ts
  libs/application/templates/rental-agreement/src/lib/messages/prerequisites.ts
  libs/application/templates/rental-agreement/src/lib/messages/summary.ts
  libs/clients/hms/src/lib/hms.service.ts
Labels: dirty bypass

#18691 feat(j-s): Add punishment type (OTHER)
  apps/judicial-system/web/next-env.d.ts
  apps/judicial-system/web/src/components/Tags/CaseTag.strings.ts
  apps/judicial-system/web/src/components/Tags/utils.ts
  apps/judicial-system/web/src/routes/Prison/IndictmentOverview/IndictmentOverview.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/prisonCases.graphql
  libs/judicial-system/types/src/lib/defendant.ts
Labels: dirty bypass

#18724 feat(j-s): Display victim information on info cards
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/InfoCard/VictimInfo/VictimInfo.tsx
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Result/Result.tsx
  apps/judicial-system/web/src/routes/Defender/CaseOverview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Shared/SignedVerdictOverview/SignedVerdictOverview.tsx
Labels: dirty bypass

#18746 chore(j-s): Add text to BlueBoxWithDate
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.strings.ts
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/IndictmentReviewerSelector.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.tsx
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: dirty bypass

#18728 feat(j-s): Enable registrars to complete cases without ruling
  apps/judicial-system/web/src/routes/Court/InvestigationCase/Confirmation/Confirmation.tsx
Labels: dirty bypass

#18772 feat(j-s): victim legal representative notifications
  apps/judicial-system/backend/src/app/formatters/formatters.spec.ts
  apps/judicial-system/backend/src/app/formatters/formatters.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/services/caseNotification/caseNotification.service.ts
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: dirty bypass

#18786 fix(j-s): Show modal when using side stepper
  apps/judicial-system/web/src/routes/Court/Indictments/Subpoena/Subpoena.tsx
Labels: dirty bypass

#18752 chore(j-s): Reorder indictment case files
  apps/judicial-system/web/src/components/IndictmentCaseFilesList/IndictmentCaseFilesList.tsx
Labels: dirty bypass

#18854 chore(ci): Make feature close be tied to deploy feature
  .github/workflows/feature-close.yml
Labels: test everything

#18853 chore(ci): Move generated file cache out of working directory
  .github/actions/load-deps/action.yml
  .github/workflows/install.yml
  .github/workflows/merge-queue.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: test everything

#18881 feat(j-s): Statistics
  apps/judicial-system/api/src/app/modules/auth/auth.controller.ts
  apps/judicial-system/api/src/app/modules/backend/backend.service.ts
  apps/judicial-system/api/src/app/modules/case-list/caseList.resolver.ts
  apps/judicial-system/api/src/app/modules/case-list/dto/caseStatistics.input.ts
  apps/judicial-system/api/src/app/modules/case-list/index.ts
  apps/judicial-system/api/src/app/modules/case-list/models/caseStatistics.model.ts
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/filters/filterHelpers.ts
  apps/judicial-system/backend/src/app/modules/case/filters/test/defenceUserFilter.spec.ts
  apps/judicial-system/backend/src/app/modules/case/models/caseStatistics.response.ts
  apps/judicial-system/backend/src/app/modules/subpoena/models/subpoenaStatistics.response.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/web/pages/notendur/tolfraedi.ts
  apps/judicial-system/web/src/components/LabelValue/LabelValue.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Admin/Statistics/Statistics.css.ts
  apps/judicial-system/web/src/routes/Admin/Statistics/Statistics.strings.ts
  apps/judicial-system/web/src/routes/Admin/Statistics/Statistics.tsx
  apps/judicial-system/web/src/routes/Admin/Statistics/components/CountAndDays.tsx
  apps/judicial-system/web/src/routes/Admin/Statistics/components/FiltersPanel.tsx
  apps/judicial-system/web/src/routes/Admin/Statistics/components/StatisticsCSVButton.tsx
  apps/judicial-system/web/src/routes/Admin/Statistics/getCaseStatistics.graphql
  apps/judicial-system/web/src/routes/Admin/Statistics/helpers.ts
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  apps/judicial-system/web/src/routes/Admin/Users/Users.tsx
  libs/judicial-system/audit-trail/src/lib/auditTrail.service.ts
  libs/judicial-system/consts/src/lib/consts.ts
Labels: dirty bypass

#18849 feat(j-s): Local Admin
  apps/judicial-system/api/src/app/modules/user/dto/updateUser.input.ts
  apps/judicial-system/backend/src/app/guards/index.ts
  apps/judicial-system/backend/src/app/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/event-log/eventLog.service.ts
  apps/judicial-system/backend/src/app/modules/user/dto/updateUser.dto.ts
  apps/judicial-system/backend/src/app/modules/user/interceptors/createUser.validator.ts
  apps/judicial-system/backend/src/app/modules/user/interceptors/updateUser.validator.ts
  apps/judicial-system/backend/src/app/modules/user/interceptors/user.interceptor.ts
  apps/judicial-system/backend/src/app/modules/user/test/createRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/getAll.spec.ts
  apps/judicial-system/backend/src/app/modules/user/test/updateRolesRules.spec.ts
  apps/judicial-system/backend/src/app/modules/user/user.controller.ts
  apps/judicial-system/backend/src/app/modules/user/user.service.ts
  apps/judicial-system/web/src/routes/Admin/ChangeUser/ChangeUser.tsx
  apps/judicial-system/web/src/routes/Admin/UserForm/UserForm.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/institution.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: dirty bypass

#18901 feat(j-s): Switch User
  apps/judicial-system/web/src/components/Header/Header.tsx
  apps/judicial-system/web/src/routes/Shared/Landing/Landing.tsx
  apps/judicial-system/web/src/routes/Shared/Landing/SelectUser/SelectUser.css.ts
  apps/judicial-system/web/src/routes/Shared/Landing/SelectUser/SelectUser.tsx
Labels: dirty bypass

#18914 fix(ci): Failure when newlint checking a project with no lints
  .github/workflows/pullrequest.yml
Labels: test everything

#18907 feat(j-s): New Institutions
  apps/judicial-system/backend/migrations/20250430112040-update-institution.js
  apps/judicial-system/backend/src/app/modules/case/case.controller.ts
  apps/judicial-system/web/src/routes/Shared/Landing/Landing.tsx
  libs/judicial-system/types/src/lib/institution.ts
  libs/judicial-system/types/src/lib/user.ts
Labels: dirty bypass
