Repository island-is/island.is, pull requests merged in 2025-09, with the labels that each got.

#19884 feat(web): add caption to news image
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
  apps/web/screens/queries/News.tsx
  libs/api/mocks/src/domains/cms/factories.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/news.model.ts
  libs/island-ui/contentful/src/lib/Image/Image.tsx
Labels: deploy-feature

#19673 feat(core): Show related organisation in problems when possible
  libs/clients/middlewares/src/lib/FetchError.ts
  libs/clients/middlewares/src/lib/withResponseErrors.ts
  libs/nest/problem/src/lib/error.filter.ts
  libs/react-spa/shared/src/components/problems/Problem.tsx
  libs/react-spa/shared/src/components/problems/ThirdPartyServiceError.tsx
  libs/shared/problem/src/problems.ts
Labels: stale

#19982 feat(ids-api): sso disabled for all clients migration
  libs/auth-api-lib/migrations/20250704134932-add-mms-oneroster-scopes.js
  libs/auth-api-lib/migrations/20250905163959-disable-sso-for-all-clients.js
Labels: dirty bypass

#20034 fix(clients-documents-v2): Fix opened input logic
  libs/clients/documents-v2/src/lib/documentsClientV2.service.ts
Labels: deploy-feature

#20134 chore: add link to argocd for feature deployment
  .github/workflows/push.yml
  apps/unicorn-app/src/app/page.tsx
  infra/src/feature-env.ts
Labels: deploy-feature

#20136 chore(estate): remove disabled items from final submission
  libs/application/template-api-modules/src/lib/modules/templates/estate/estate.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/filters.ts
  libs/application/template-api-modules/src/lib/modules/templates/estate/utils/processUploadData.ts
  libs/application/templates/estate/src/forms/OverviewSections/assetsAndDebts.ts
Labels: deploy-feature

#20183 fix(vehicles): wrong latest mileage
  libs/api/domains/vehicles/src/lib/models/getVehicleDetail.model.ts
  libs/api/domains/vehicles/src/lib/resolvers/mileage.resolver.ts
  libs/api/domains/vehicles/src/lib/resolvers/shared.resolver.ts
  libs/api/domains/vehicles/src/lib/services/bulkMileage.service.ts
  libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
  libs/api/domains/vehicles/src/lib/utils/basicVehicleInformationMapper.ts
  libs/api/domains/vehicles/src/lib/vehicles.module.ts
  libs/api/mocks/src/domains/vehicles/factories.ts
  libs/clients/vehicles-mileage/src/clientConfig.json
  libs/clients/vehicles-mileage/src/lib/vehiclesMileageClient.service.ts
  libs/clients/vehicles/src/clientConfig.json
  libs/portals/my-pages/assets/src/screens/VehicleDetail/VehicleDetail.graphql
  libs/portals/my-pages/assets/src/screens/VehicleDetail/VehicleDetail.tsx
Labels: deploy-feature
