Repository island-is/island.is, pull requests merged in 2025-03, with the labels that each got.

#17803 feat(my-pages-social-insurance): Multiple ui states
  libs/portals/my-pages/core/src/components/ActionCard/ActionCard.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/lib/messages.ts
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/IncomePlan.graphql
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/IncomePlan.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/IncomePlanCard.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/mapper.ts
  libs/portals/my-pages/social-insurance-maintenance/src/screens/IncomePlan/types.ts
Labels: deploy-feature

#18231 fix(my-pages): Vehicle bulk put
  libs/api/domains/vehicles/src/lib/services/vehicles.service.ts
  libs/clients/vehicles-mileage/src/clientConfig.json
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileage.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageRow.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageSaveButton.tsx
  libs/portals/my-pages/assets/src/screens/VehicleBulkMileage/VehicleBulkMileageTable.tsx
Labels: deploy-feature

#18263 chore: force build all using special flags
  .github/workflows/merge-queue.yml
Labels: test everything

#18105 feat: Enable source map to build
  apps/air-discount-scheme/web/next.config.js
  apps/api/esbuild.json
  apps/auth-admin-web/next.config.js
  apps/consultation-portal/next.config.js
  apps/contentful-apps/next.config.js
  apps/financial-aid/web-osk/next.config.js
  apps/financial-aid/web-veita/next.config.js
  apps/judicial-system/web/next.config.js
  apps/reference-next-app/next.config.js
  apps/skilavottord/web/next.config.js
  apps/tools/contentful-role-permissions/next.config.js
  apps/unicorn-app/next.config.js
  apps/web/next.config.js
  infra/src/dsl/basic.spec.ts
  infra/src/dsl/feature-values.spec.ts
  infra/src/dsl/output-generators/map-to-helm-values.ts
  infra/src/dsl/portal-env.spec.ts
  infra/src/dsl/postgres.spec.ts
Labels: deploy-feature

#18342 fix(web): Organization and service web layout footers
  apps/web/components/Main/Main.tsx
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
  apps/web/components/ServiceWeb/DynamicFooter/DynamicFooter.tsx
  apps/web/layouts/main.tsx
  apps/web/screens/Project/Project.tsx
  apps/web/screens/Project/components/ProjectWrapper/ProjectWrapper.tsx
Labels: deploy-feature

#18477 chore(ci): Respect the `skip-nx-cache` label
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: skip-nx-cache

#18404 feat(license): Add photo to license metadata
  libs/api/domains/license-service/src/lib/dto/GenericUserLicenseMetadata.dto.ts
  libs/api/domains/license-service/src/lib/mappers/drivingLicenseMapper.ts
  libs/api/domains/license-service/src/lib/mappers/firearmLicenseMapper.ts
  libs/api/domains/license-service/src/lib/mappers/huntingLicenseMapper.ts
  libs/api/domains/license-service/src/lib/utils/formatPhoto.spec.ts
  libs/api/domains/license-service/src/lib/utils/formatPhoto.ts
Labels: deploy-feature

#17875 fix(application-ir): Provider failure when no estates found
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/inheritance-report.service.ts
  libs/application/templates/inheritance-report/src/index.ts
Labels: skip-nx-cache

#18462 feat(web): Verdicts - Text search and court level filter
  apps/web/screens/Verdicts/VerdictsList.css.ts
  apps/web/screens/Verdicts/VerdictsList.tsx
  apps/web/screens/Verdicts/translations.strings.ts
  libs/api/domains/verdicts/src/lib/dto/verdicts.input.ts
  libs/api/domains/verdicts/src/lib/verdicts.service.ts
  libs/clients/verdicts/src/lib/verdicts-client.service.ts
Labels: deploy-feature

#18563 fix: update infra configs
  .github/workflows/push.yml
  apps/unicorn-app/src/app/page.tsx
  infra/.yarn/releases/yarn-4.6.0.cjs
  infra/.yarnrc.yml
  infra/package.json
  infra/scripts/Dockerfile
  infra/scripts/build-docker-container.sh
  infra/src/feature-env.ts
  infra/src/secrets.ts
  infra/yarn.lock
Labels: deploy-feature
