Repository island-is/island.is, pull requests merged in 2025-01, with the labels that each got.

#17302 fix(social-insurance-administration): update model
  libs/api/domains/social-insurance/src/lib/models/payments/payment.model.ts
  libs/api/domains/social-insurance/src/lib/socialInsurance.service.ts
  libs/clients/social-insurance-administration/src/clientConfig.json
  libs/portals/my-pages/core/src/components/ScrollableMiddleTable/ScrollableMiddleTable.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTable.graphql
  libs/portals/my-pages/social-insurance-maintenance/src/components/PaymentGroupTable/PaymentGroupTableRow.tsx
  libs/portals/my-pages/social-insurance-maintenance/src/lib/messages.ts
  libs/portals/my-pages/social-insurance-maintenance/src/screens/PaymentPlan/PaymentPlan.tsx
Labels: automerge, deploy-feature

#17354 fix(ids-api): Filter delegated national registry scopes by delegation types.
  apps/services/auth/ids-api/src/app/delegations/test/delegations-scopes.spec.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#17382 fix(inheritance-report): Fix bank account calculation
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17301 feat(j-s): Add functionality to enable revoking appeal
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.strings.ts
  apps/judicial-system/web/src/components/BlueBoxWithIcon/BlueBoxWithDate.tsx
Labels: automerge

#17348 fix(j-s): Add missing court case number to info card
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
Labels: automerge

#17383 fix(inheritance-report): Fix bank account calculation (#17382)
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17366 fix(j-s): add missing civil demand title
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/processing.strings.ts
Labels: automerge

#17368 fix(j-s): hide review date field when review date is falsy
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx
Labels: automerge

#17387 chore(ojoi): Add css class to signature date
  libs/application/templates/official-journal-of-iceland/src/lib/utils.ts
Labels: automerge

#17389 fix(ids-api): Filter delegated national registry scopes by delegation…
  apps/services/auth/ids-api/src/app/delegations/test/delegations-scopes.spec.ts
  apps/services/auth/public-api/src/app/modules/delegations/actorDelegations.controller.spec.ts
  libs/auth-api-lib/src/lib/delegations/delegation-scope.service.ts
  libs/services/auth/testing/src/fixtures/fixture-factory.ts
Labels: automerge

#17360 fix(j-s): Add case info also to reception and assignment component
  apps/judicial-system/web/src/components/CaseInfo/CaseInfo.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Summary/Summary.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
Labels: automerge

#17364 fix(j-s): Fix empty information in merged cases fetched for defender users
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/FormProvider/limitedAccessCase.graphql
  apps/judicial-system/web/src/components/InfoCard/InfoCardActiveIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/InfoCardClosedIndictment.tsx
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.strings.ts
  apps/judicial-system/web/src/components/InfoCard/useInfoCardItems.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Indictment.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#17375 feat(service-portal): expand modal
  libs/portals/my-pages/core/src/components/Modal/Modal.css.ts
  libs/portals/my-pages/core/src/components/Modal/Modal.tsx
  libs/portals/my-pages/health/src/lib/messages.ts
Labels: automerge

#17349 fix(web): Organizations page - truncate tag label
  apps/web/screens/Organizations/Organizations.tsx
Labels: automerge

#17394 fix(inheritance-report): Revert bank account name change
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17390 chore(j-s): Remove unused cf strings
  apps/judicial-system/web/messages/Core/commentsInput.ts
  apps/judicial-system/web/messages/RestrictionCases/Prosecutor/reportForm.ts
Labels: automerge

#17356 chore(web): Stop importing GraphQL types from api/schema
  apps/web/components/Charts/v2/hooks/chart.ts
  apps/web/components/OfficialJournalOfIceland/OJOIAdvertCards.tsx
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
  apps/web/components/TableOfContents/TableOfContents.tsx
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.tsx
  apps/web/components/connected/fiskistofa/ShipSearch/ShipSearch.tsx
  apps/web/components/connected/fiskistofa/calculators/CatchQuotaCalculator/CatchQuotaCalculator.tsx
  apps/web/components/connected/fiskistofa/calculators/CatchQuotaCalculator/machine.ts
  apps/web/components/connected/fiskistofa/calculators/StraddlingStockCalculator/StraddlingStockCalculator.tsx
  apps/web/components/connected/fiskistofa/calculators/StraddlingStockCalculator/machine.ts
  apps/web/components/connected/syslumenn/TableLists/BrokersList/BrokersList.tsx
  apps/web/components/connected/syslumenn/TableLists/JourneymanList/JourneymanList.tsx
  apps/web/components/connected/syslumenn/TableLists/MasterList/MasterList.tsx
  apps/web/components/connected/syslumenn/utils/search.ts
  apps/web/screens/Adgerdir/Article.tsx
  apps/web/screens/Adgerdir/Home.tsx
  apps/web/screens/Adgerdir/components/AdgerdirArticles/AdgerdirArticles.tsx
  apps/web/screens/Adgerdir/components/CardsSlider/CardsSlider.tsx
  apps/web/screens/Adgerdir/components/FeaturedNews/FeaturedNews.tsx
  apps/web/screens/Adgerdir/components/LatestNews/LatestNews.tsx
  apps/web/screens/Home/Home.tsx
  apps/web/screens/LifeEvents/LifeEvents.tsx
  apps/web/screens/Login/Login.tsx
  apps/web/screens/OfficialJournalOfIceland/hooks/useAdverts.ts
  apps/web/screens/Organization/SocialInsuranceAdministration/PensionCalculator.tsx
  apps/web/screens/Organization/StafraentIsland/ApiCatalogue.tsx
Labels: automerge

#17362 feat(web): Service web - Disable contact form for some organizations
  apps/web/components/ServiceWeb/DynamicFooter/DynamicFooter.tsx
  apps/web/components/ServiceWeb/Footer/Footer.tsx
  apps/web/screens/ServiceWeb/Forms/Forms.tsx
  apps/web/screens/ServiceWeb/Home/Home.tsx
  apps/web/screens/ServiceWeb/Search/ServiceSearch.tsx
  apps/web/screens/ServiceWeb/SubPage/SubPage.tsx
  apps/web/screens/ServiceWeb/utils/index.ts
Labels: automerge

#17365 fix(web): Organization parent subpage - Double footer
  apps/web/screens/Organization/ParentSubpage.tsx
Labels: automerge

#17367 fix(web): Organization parent subpage - Link highlighting in sidebar
  apps/web/screens/Organization/ParentSubpage.tsx
  apps/web/screens/Organization/SubPage.tsx
Labels: automerge

#17369 fix(contentful-apps): Handle org subpage and parent subpage preview link routing
  apps/contentful-apps/pages/sidebars/preview-link.tsx
Labels: automerge

#17398 fix(ojoi): Updated type selector and submitted screen
  libs/application/templates/official-journal-of-iceland/src/components/input/OJOISelectController.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Advert.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Submitted.tsx
  libs/application/templates/official-journal-of-iceland/src/lib/messages/submitted.tsx
Labels: automerge

#17391 fix(ui): info card grid
  libs/island-ui/core/src/lib/InfoCardGrid/DetailedInfoCard.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/InfoCard.css.ts
  libs/island-ui/core/src/lib/InfoCardGrid/InfoCard.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/InfoCardGrid.stories.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/InfoCardGrid.tsx
  libs/island-ui/core/src/lib/InfoCardGrid/SimpleInfoCard.tsx
Labels: automerge

#17399 fix(inheritance-report): Account for enabled field on assets
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17393 fix(samgongustofa applications): Fix setting prune date at midnight
  libs/application/templates/aosh/transfer-of-machine-ownership/src/lib/TransferOfMachineOwnershipTemplate.ts
  libs/application/templates/transport-authority/change-co-owner-of-vehicle/src/lib/ChangeCoOwnerOfVehicleTemplate.ts
  libs/application/templates/transport-authority/change-operator-of-vehicle/src/lib/ChangeOperatorOfVehicleTemplate.ts
  libs/application/templates/transport-authority/transfer-of-vehicle-ownership/src/lib/TransferOfVehicleOwnershipTemplate.ts
Labels: automerge

#17363 chore(web): Remove NewLinks component
  apps/web/components/NewLinks/NewLinks.css.ts
  apps/web/components/NewLinks/NewLinks.tsx
  apps/web/components/real.ts
Labels: automerge

#17409 fix(web): Remove email from university studies footer
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudies.css.ts
  apps/web/components/Organization/Wrapper/Themes/UniversityStudiesTheme/UniversityStudiesFooter.tsx
Labels: automerge

#17405 fix(change-operator): Add missing mileage field when removing all operators
  libs/clients/transport-authority/vehicle-operators/src/lib/vehicleOperatorsClient.service.ts
Labels: automerge

#17319 feat(web): Generic List - Order by field in CMS
  apps/web/components/GenericList/GenericList.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/dto/getGenericListItems.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/genericList.model.ts
  libs/cms/src/lib/models/latestGenericListItems.model.ts
  libs/cms/src/lib/search/importers/genericListItem.service.ts
Labels: automerge

#17370 chore(j-s): add gender to custody notice
  apps/judicial-system/backend/src/app/formatters/custodyNoticePdf.ts
  apps/judicial-system/backend/src/app/messages/pdfCustodyNotice.ts
Labels: automerge

#17404 fix(change-operator): Add missing mileage field when removing all operators
  libs/clients/transport-authority/vehicle-operators/src/lib/vehicleOperatorsClient.service.ts
Labels: automerge

#17401 chore(j-s): Remove vehicle registration number validation
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/utils/validate.spec.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#17352 feat(j-s): Unserviced tag for indictment cases
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/components/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/routes/Court/components/CasesInProgressTable/CasesInProgressTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/defenderCases.graphql
  apps/judicial-system/web/src/routes/Shared/Cases/ActiveCases.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/MobileCase.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
Labels: automerge

#17273 fix(application-system): Refactoring half of divider field into a new field
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/aosh/change-machine-supervisor/src/forms/ChangeMachineSupervisorForm/InformationSection/supervisorSubSection.ts
  libs/application/templates/aosh/street-registration/src/forms/StreetRegistrationForm/InformationSection/machineSubSection.ts
  libs/application/templates/document-provider-onboarding/src/forms/DocumentProviderApplication.ts
  libs/application/templates/document-provider-onboarding/src/forms/ReviewApplication.ts
  libs/application/templates/driving-license/src/forms/draft/subSectionTempInfo.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/confirmSection.ts
  libs/application/templates/health-insurance/src/forms/HealthInsuranceForm/formerInsuranceSection.ts
  libs/application/templates/health-insurance/src/forms/MissingInfoForm.ts
  libs/application/templates/passport/src/forms/ParentB.ts
  libs/application/templates/reference-template/src/forms/exampleForm/noInputFieldsSection/dividerSubsection.ts
  libs/application/templates/reference-template/src/forms/exampleForm/noInputFieldsSection/index.ts
  libs/application/templates/reference-template/src/forms/exampleForm/noInputFieldsSection/titleSubsection.ts
  libs/application/templates/reference-template/src/forms/reviewApplicationForm/reviewApplication.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/DividerFormField/DividerFormField.tsx
  libs/application/ui-fields/src/lib/TitleFormField/TitleFormField.stories.mdx
  libs/application/ui-fields/src/lib/TitleFormField/TitleFormField.tsx
  libs/application/ui-fields/src/lib/index.ts
Labels: automerge

#17400 fix(j-s): Enable opening uploaded files on iOS
  apps/judicial-system/web/src/utils/hooks/useFileList/index.ts
  apps/judicial-system/web/src/utils/hooks/useIsMobile/useIsMobile.ts
Labels: automerge

#17414 feat(web): Hotfix - RSS feed for generic lists and events
  apps/web/pages/api/rss/index.ts
  apps/web/screens/queries/Events.ts
  libs/cms/src/lib/models/event.model.ts
Labels: automerge

#17355 feat(j-s): Allow prosecutor office to change the prosecutor decision
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/IndictmentReviewerSelector.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Indictments/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/components/ReviewDecision/ReviewDecision.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/components/utils.ts
  apps/judicial-system/web/src/routes/Shared/IndictmentOverview/IndictmentOverview.tsx
Labels: automerge

#17337 fix(j-s): Undefined recipient email
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/notification/services/caseNotification/caseNotification.service.ts
Labels: automerge

#17417 fix(parental-leave): pdf attachments not uploading (#17114)
  libs/application/template-api-modules/src/lib/modules/templates/parental-leave/parental-leave.service.ts
Labels: automerge

#17411 feat(ojoi): Repost failed applications
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.resolver.ts
  libs/application/templates/official-journal-of-iceland/src/fields/Submitted.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useUpdateApplication.ts
  libs/application/templates/official-journal-of-iceland/src/lib/messages/submitted.tsx
Labels: automerge

#17262 feat(web): new grant card list slice
  apps/tools/contentful-role-permissions/constants/index.ts
  apps/web/components/GrantCardsList/GrantCardsList.tsx
  apps/web/components/GrantCardsList/index.ts
  apps/web/components/GrantCardsList/types.ts
  apps/web/screens/Grants/SearchResults/SearchResultsContent.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/cms.module.ts
  libs/cms/src/lib/cms.resolver.ts
  libs/cms/src/lib/dto/getGrants.input.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/grantCardsList.model.ts
  libs/cms/src/lib/search/importers/grants.service.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#17418 chore(contentful-role-permissions): Footer item is now read only by default
  apps/tools/contentful-role-permissions/constants/index.ts
Labels: automerge

#17291 feat(j-s): Deliver subpoena revocation to police
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/police/police.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/internalSubpoena.controller.ts
  apps/judicial-system/backend/src/app/modules/subpoena/subpoena.service.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/internalSubpoenaController/deliverSubpoenaRevokedToPolice.spec.ts
  apps/judicial-system/backend/src/app/modules/subpoena/test/internalSubpoenaController/deliverSubpoenaRevokedToPoliceGuards.spec.ts
  libs/judicial-system/message/src/lib/message.ts
Labels: automerge

#17303 feat(j-s): Display defendant appealed verdict tag for public prosecutor
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.strings.ts
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/cases.graphql
Labels: automerge

#17426 fix(web): grant info card codeowners
  .github/CODEOWNERS
Labels: automerge

#17425 feat(web): Add missing energy transition message
  apps/web/screens/Grants/Home/mapTagToMessageId.ts
  apps/web/screens/Grants/messages.ts
Labels: automerge

#17423 fix(web): Fix hydration error
  apps/web/components/Organization/Wrapper/OrganizationWrapper.tsx
Labels: automerge

#17406 feat(j-s): send criminal records to public prosecutor static email
  apps/judicial-system/backend/infra/judicial-system-backend.ts
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/notification/notification.config.ts
  apps/judicial-system/backend/src/app/modules/notification/notificationDispatch.service.ts
  apps/judicial-system/backend/src/app/modules/notification/services/indictmentCaseNotification/indictmentCaseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/services/indictmentCaseNotification/indictmentCaseNotification.strings.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/eventNotificationDispatch/eventNotificationDispatch.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/indictmentCaseNotification/sendIndictmentCriminalRecordFilesUploadedNotification.spec.ts
  charts/judicial-system/values.dev.yaml
  charts/judicial-system/values.prod.yaml
  charts/judicial-system/values.staging.yaml
  charts/services/judicial-system-backend/values.dev.yaml
  charts/services/judicial-system-backend/values.prod.yaml
  charts/services/judicial-system-backend/values.staging.yaml
  libs/judicial-system/types/src/lib/notification.ts
Labels: automerge

#17385 chore(j-s): add police case numbers to revoke indictment notification email
  apps/judicial-system/backend/src/app/messages/notifications.ts
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/test/internalCaseController/deliverIndictmentCancellationNoticeToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/notification/services/caseNotification/caseNotification.service.ts
  apps/judicial-system/backend/src/app/modules/notification/test/internalNotificationController/sendRevokedNotifications.spec.ts
Labels: automerge

#17415 fix(client-driving-license): Leap year edge issues
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/residence-history/src/lib/computeCountryResidence.spec.ts
  libs/residence-history/src/lib/computeCountryResidence.ts
Labels: automerge

#17429 fix(web): News - images inside of content are either fetched too small or too large
  apps/web/components/Organization/NewsArticle/NewsArticle.tsx
  apps/web/screens/Organization/OrganizationEvents/OrganizationEventArticle.tsx
  apps/web/utils/richText.tsx
Labels: automerge

#17431 fix(web): Web master service web is the one that shouldn't have a contact form
  apps/web/screens/ServiceWeb/utils/index.ts
Labels: automerge

#17430 fix(my-pages): annual doc query dl
  apps/download-service/src/app/modules/finance-documents/document.controller.ts
  libs/portals/my-pages/core/src/utils/documentFormSubmission.ts
  libs/portals/my-pages/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#17435 fix(my-pages): annual doc query dl - hotfix
  apps/download-service/src/app/modules/finance-documents/document.controller.ts
  libs/portals/my-pages/core/src/utils/documentFormSubmission.ts
  libs/portals/my-pages/finance/src/screens/FinanceStatus/FinanceStatus.tsx
Labels: automerge

#17357 chore(web): Electronic registrations - Remove unused component and relevant endpoints
  .github/CODEOWNERS
  apps/api/infra/api.ts
  apps/api/src/app/app.module.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomLegend/CustomLegend.css.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomLegend/CustomLegend.tsx
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomLegend/index.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomTooltip/CustomTooltip.css.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomTooltip/CustomTooltip.tsx
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/CustomTooltip/index.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.css.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/MonthlyStatistics.tsx
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/index.ts
  apps/web/components/connected/electronicRegistrationStatistics/MonthlyStatistics/utils.ts
  apps/web/components/connected/electronicRegistrationStatistics/index.ts
  apps/web/components/connected/electronicRegistrationStatistics/queries.ts
  apps/web/utils/richText.tsx
  charts/islandis/values.dev.yaml
  charts/islandis/values.prod.yaml
  charts/islandis/values.staging.yaml
  charts/services/api/values.dev.yaml
  charts/services/api/values.prod.yaml
  charts/services/api/values.staging.yaml
  libs/api/domains/electronic-registration-statistics/.babelrc
  libs/api/domains/electronic-registration-statistics/.eslintrc.json
  libs/api/domains/electronic-registration-statistics/README.md
  libs/api/domains/electronic-registration-statistics/jest.config.ts
  libs/api/domains/electronic-registration-statistics/project.json
  libs/api/domains/electronic-registration-statistics/src/index.ts
  libs/api/domains/electronic-registration-statistics/src/lib/dto/getBrokenDownElectronicRegistrationStatistics.input.ts
  libs/api/domains/electronic-registration-statistics/src/lib/electronicRegistrations.module.ts
  libs/api/domains/electronic-registration-statistics/src/lib/electronicRegistrations.resolver.ts
  libs/api/domains/electronic-registration-statistics/src/lib/models/brokenDownRegistrationStatistic.ts
  libs/api/domains/electronic-registration-statistics/tsconfig.json
  libs/api/domains/electronic-registration-statistics/tsconfig.lib.json
  libs/api/domains/electronic-registration-statistics/tsconfig.spec.json
  libs/clients/electronic-registration-statistics/.babelrc
  libs/clients/electronic-registration-statistics/.eslintrc.json
  libs/clients/electronic-registration-statistics/README.md
  libs/clients/electronic-registration-statistics/jest.config.ts
  libs/clients/electronic-registration-statistics/project.json
  libs/clients/electronic-registration-statistics/src/clientConfig.json
  libs/clients/electronic-registration-statistics/src/index.ts
  libs/clients/electronic-registration-statistics/src/lib/apiProvider.ts
  libs/clients/electronic-registration-statistics/src/lib/electronicRegistrations.config.ts
  libs/clients/electronic-registration-statistics/src/lib/electronicRegistrations.module.ts
  libs/clients/electronic-registration-statistics/src/lib/electronicRegistrations.service.ts
  libs/clients/electronic-registration-statistics/tsconfig.json
  libs/clients/electronic-registration-statistics/tsconfig.lib.json
  libs/clients/electronic-registration-statistics/tsconfig.spec.json
  libs/cms/src/lib/generated/contentfulTypes.d.ts
Labels: automerge

#17416 feat(web): Featured link slice
  apps/web/components/FeaturedLinks/FeaturedLinks.tsx
  apps/web/components/Organization/Slice/FeaturedLinksSlice/FeaturedLinksSlice.tsx
  apps/web/components/Organization/Slice/SliceMachine.tsx
  apps/web/components/SearchSection/SearchSection.tsx
  apps/web/components/real.ts
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/featuredLinks.model.ts
  libs/cms/src/lib/unions/slice.union.ts
Labels: automerge

#17439 fix(web): Event card spacing
  apps/web/screens/Organization/OrganizationEvents/OrganizationEventArticle.tsx
Labels: automerge

#17424 fix(application-dl): 65+ Qphoto Req Change
  libs/application/templates/driving-license/src/fields/EligibilitySummary/useEligibility.ts
Labels: automerge

#17445 fix(client-driving-license): Hotfix - Leap year edge issues (#17415)
  libs/api/domains/driving-license/src/lib/drivingLicense.spec.ts
  libs/residence-history/src/lib/computeCountryResidence.spec.ts
  libs/residence-history/src/lib/computeCountryResidence.ts
Labels: automerge

#16696 fix(my-pages): notifications spacing and color
  apps/portals/my-pages/src/components/Notifications/NotificationButton.tsx
  apps/portals/my-pages/src/components/Notifications/NotificationLine.tsx
  apps/portals/my-pages/src/components/Notifications/NotificationMenu.tsx
  apps/portals/my-pages/src/components/Notifications/Notifications.css.ts
  apps/portals/my-pages/src/components/Sidemenu/Sidemenu.css.ts
  apps/portals/my-pages/src/components/Sidemenu/Sidemenu.tsx
Labels: automerge

#17427 fix(web): deadline detail
  apps/web/components/GrantCardsList/GrantCardsList.tsx
  apps/web/screens/Grants/Grant/Grant.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/DetailPanel.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/ExtraPanel.tsx
  apps/web/screens/Grants/Grant/GrantSidebar/GrantSidebar.tsx
  apps/web/screens/Grants/messages.ts
  apps/web/screens/Grants/utils.ts
Labels: automerge

#17441 feat(income-plan): Use different endpoint for income plan year
  libs/application/templates/social-insurance-administration/income-plan/src/forms/IncomePlanForm.ts
Labels: automerge

#17216 chore(ci): add next folder to dockerignore
  .dockerignore
Labels: automerge, deploy-feature, test everything

#17448 fix(web): Hotfix - Generic List order
  libs/cms/src/lib/cms.elasticsearch.service.ts
  libs/cms/src/lib/search/importers/genericListItem.service.ts
  libs/cms/src/lib/search/importers/teamList.service.ts
Labels: automerge

#17454 feat(web): Hotfix - Add custom top login button item to VMST "My Pages" page #17453
  apps/web/screens/Organization/DirectorateOfLabour/MyPages.tsx
Labels: automerge

#17453 feat(web): Add custom top login button item to VMST "My Pages" page
  apps/web/screens/Organization/DirectorateOfLabour/MyPages.tsx
Labels: automerge

#17438 fix(j-s): slow down the execution of js playwright tests
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/system-e2e/src/playwright.config.ts
Labels: automerge

#17455 chore(ids-api): Add secrets for dd rum applicationid and clienttoken.
  apps/services/auth/ids-api/infra/identity-server.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/services/identity-server/values.dev.yaml
  charts/services/identity-server/values.prod.yaml
  charts/services/identity-server/values.staging.yaml
Labels: automerge

#17461 feat(web): Boost.ai - Set language depending on activeLocale
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
Labels: automerge

#17462 chore(ids-api): Add secrets for dd rum applicationid and clienttoken.…
  apps/services/auth/ids-api/infra/identity-server.ts
  charts/identity-server/values.dev.yaml
  charts/identity-server/values.prod.yaml
  charts/identity-server/values.staging.yaml
  charts/services/identity-server/values.dev.yaml
  charts/services/identity-server/values.prod.yaml
  charts/services/identity-server/values.staging.yaml
Labels: automerge

#17463 feat(web): Hotfix - Boost.ai, set language depending on activeLocale #17461
  apps/web/components/ChatPanel/BoostChatPanel/BoostChatPanel.tsx
Labels: automerge

#17396 fix(inheritance-report): Revert bank account parameter name change
  libs/application/template-api-modules/src/lib/modules/templates/inheritance-report/utils/mappers.ts
  libs/application/templates/inheritance-report/src/fields/CalculateShare/index.tsx
  libs/application/templates/inheritance-report/src/fields/Overview/OverviewAssets/rows.ts
  libs/application/templates/inheritance-report/src/forms/sections/assets.ts
  libs/application/templates/inheritance-report/src/lib/dataSchema.ts
  libs/application/templates/inheritance-report/src/types.ts
Labels: automerge

#17452 feat(application-system): Add clear on change
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/reference-template/src/forms/exampleForm/commonActionsSection/clearOnChangeSubsection.ts
  libs/application/templates/reference-template/src/forms/exampleForm/commonActionsSection/index.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/types/src/lib/Form.ts
  libs/application/ui-components/src/components/NationalIdWithName/NationalIdWithName.tsx
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/application/ui-fields/src/lib/BankAccountFormField/BankAccountFormField.tsx
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/DateFormField/DateFormField.tsx
  libs/application/ui-fields/src/lib/DisplayFormField/DisplayFormField.tsx
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/NationalIdWithNameFormField/NationalIdWithNameFormField.tsx
  libs/application/ui-fields/src/lib/PhoneFormField/PhoneFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
  libs/application/ui-fields/src/lib/SelectFormField/SelectFormField.tsx
  libs/application/ui-fields/src/lib/TextFormField/TextFormField.tsx
  libs/application/ui-fields/src/lib/VehicleRadioFormField/VehicleRadioFormField.tsx
  libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx
  libs/shared/form-fields/src/lib/DatePickerController/DatePickerController.tsx
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
  libs/shared/form-fields/src/lib/PhoneInputController/PhoneInputController.tsx
  libs/shared/form-fields/src/lib/RadioController/RadioController.tsx
  libs/shared/form-fields/src/lib/SelectController/SelectController.tsx
  libs/shared/utils/src/index.ts
  libs/shared/utils/src/lib/clearInputsOnChange.spec.ts
  libs/shared/utils/src/lib/clearInputsOnChange.ts
Labels: automerge

#16304 feat(new-primary-school): Reason page - Data implementation
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
  libs/application/templates/new-primary-school/src/fields/FriggOptionsAsyncSelectField/index.tsx
  libs/application/templates/new-primary-school/src/fields/RelativesTableRepeater/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Child.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/ReasonForApplication.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Relatives.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/School.tsx
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/childInfoSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/supportSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/reasonForApplicationSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/siblingsSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/externalDataSubSection.ts
  libs/application/templates/new-primary-school/src/hooks/useFriggOptions.ts
  libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
  libs/application/templates/new-primary-school/src/lib/constants.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
Labels: automerge

#17442 fix(web): remove focusable box
  apps/web/components/CardWithFeaturedItems/CardWithFeaturedItems.tsx
Labels: automerge

#17192 feat(j-s): Allow multiple subtypes in indictments
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/web/src/components/CaseFile/CaseFile.tsx
  apps/judicial-system/web/src/components/CourtArrangements/CourtArrangements.tsx
  apps/judicial-system/web/src/components/RestrictionTags/RestrictionTags.tsx
  apps/judicial-system/web/src/routes/Court/InvestigationCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/RestrictionCase/HearingArrangements/HearingArrangements.tsx
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/AppealCase/AppealCase.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Summary/Summary.spec.tsx
  apps/judicial-system/web/src/routes/CourtOfAppeal/Summary/Summary.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.spec.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/Substances.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/Substances/Substances.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/InvestigationCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/RestrictionCase/Overview/Overview.tsx
  apps/judicial-system/web/src/routes/Prosecutor/components/DefendantInfo/DefendantInfo.tsx
  apps/judicial-system/web/src/utils/formHelper.ts
  apps/judicial-system/web/src/utils/hooks/useAppealAlertBanner/index.tsx
  apps/judicial-system/web/src/utils/hooks/useIndictmentCounts/index.ts
  apps/judicial-system/web/src/utils/hooks/useNationalRegistry/index.ts
  apps/judicial-system/web/src/utils/hooks/useSections/index.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
  apps/judicial-system/web/src/utils/utils.ts
  apps/judicial-system/web/src/utils/validate.ts
Labels: automerge

#17440 feat(my-pages): Health payment doc addition
  apps/download-service/src/app/app.module.ts
  apps/download-service/src/app/modules/health/payment-overview-documents.controller.ts
  libs/api/domains/rights-portal/src/lib/payment/payment.resolver.ts
  libs/api/domains/rights-portal/src/lib/rightsPortal.module.ts
  libs/feature-flags/src/lib/features.ts
  libs/portals/my-pages/health/src/screens/Payments/PaymentOverview.tsx
Labels: automerge

#17473 feat(application-system): Add company search to repeaters
  libs/application/templates/reference-template/src/forms/exampleForm/tablesAndRepeatersSection/fieldsRepeaterSubsection.ts
  libs/application/templates/reference-template/src/forms/exampleForm/tablesAndRepeatersSection/tableRepeaterSubsection.ts
  libs/application/types/src/lib/Fields.ts
Labels: automerge

#17457 test(j-s): Regression E2E for court's handling of indictment cases
  apps/system-e2e/src/tests/judicial-system/regression/indictment-tests.spec.ts
  apps/system-e2e/src/tests/judicial-system/utils/helpers.ts
Labels: automerge

#17464 feat(web): Add image to generic list item
  apps/web/components/GenericList/GenericList.tsx
  apps/web/components/NewsCard/NewsCard.tsx
  apps/web/screens/GenericList/GenericListItem.css.ts
  apps/web/screens/GenericList/GenericListItem.tsx
  apps/web/screens/queries/GenericList.ts
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/genericListItem.model.ts
Labels: automerge

#17475 feat(web): Add show search check to team list
  apps/web/components/Organization/Slice/TeamListSlice/TeamListSlice.tsx
  apps/web/screens/queries/fragments.ts
  apps/web/utils/richText.tsx
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/teamList.model.ts
Labels: automerge

#17478 fix(application-system): Contentful strings removed
  libs/application/templates/aosh/work-accident-notification/src/forms/WorkAccidentNotificationForm/AnnouncementSection/index.ts
  libs/application/templates/aosh/work-accident-notification/src/lib/messages/externalData.ts
Labels: automerge

#16351 fix(marriage): new flow
  libs/api/domains/syslumenn/src/lib/dto/getElectronicID.input.ts
  libs/api/domains/syslumenn/src/lib/syslumenn.resolver.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/emailGenerators/utils.ts
  libs/application/template-api-modules/src/lib/modules/templates/marriage-conditions-submission/marriage-conditions-submission.service.ts
  libs/application/templates/marriage-conditions/src/assets/DigitalServices.tsx
  libs/application/templates/marriage-conditions/src/dataProviders/index.ts
  libs/application/templates/marriage-conditions/src/fields/ApplicationOverview/index.tsx
  libs/application/templates/marriage-conditions/src/fields/NationalIdWithName/index.tsx
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
  libs/application/templates/marriage-conditions/src/fields/PhoneWithElectronicId/index.tsx
  libs/application/templates/marriage-conditions/src/fields/index.ts
  libs/application/templates/marriage-conditions/src/forms/application.ts
  libs/application/templates/marriage-conditions/src/forms/done.ts
  libs/application/templates/marriage-conditions/src/forms/fakeDataSection.ts
  libs/application/templates/marriage-conditions/src/forms/sharedSections/dataCollection.ts
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/MarriageConditionsTemplate.ts
  libs/application/templates/marriage-conditions/src/lib/dataSchema.ts
  libs/application/templates/marriage-conditions/src/lib/getApplicationFeatureFlags.ts
  libs/application/templates/marriage-conditions/src/lib/messages.ts
  libs/application/templates/marriage-conditions/src/lib/utils.ts
  libs/application/templates/marriage-conditions/src/queries/index.ts
  libs/clients/syslumenn/src/clientConfig.json
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#17465 fix(secondary school): Fixes in new application
  libs/application/core/src/lib/messages.ts
  libs/application/template-api-modules/src/lib/modules/templates/secondary-school/secondary-school.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/secondary-school/utils.ts
  libs/application/templates/secondary-school/src/dataProviders/index.ts
  libs/application/templates/secondary-school/src/fields/schoolSelection/SelectionItem.tsx
  libs/application/templates/secondary-school/src/fields/schoolSelection/index.tsx
  libs/application/templates/secondary-school/src/forms/completedForm.ts
  libs/application/templates/secondary-school/src/forms/prerequisitesForm.ts
  libs/application/templates/secondary-school/src/forms/secondarySchoolForm/conclusionSection/index.ts
  libs/application/templates/secondary-school/src/forms/secondarySchoolForm/extraInformationSection/index.ts
  libs/application/templates/secondary-school/src/forms/secondarySchoolForm/overviewSection/index.ts
  libs/application/templates/secondary-school/src/forms/secondarySchoolForm/schoolSection/index.ts
  libs/application/templates/secondary-school/src/forms/secondarySchoolForm/userInformationSection/personalSubSection.ts
  libs/application/templates/secondary-school/src/forms/submittedForm.ts
  libs/application/templates/secondary-school/src/lib/SecondarySchoolTemplate.ts
  libs/application/templates/secondary-school/src/lib/dataSchema.ts
  libs/application/templates/secondary-school/src/lib/messages/application.ts
  libs/application/templates/secondary-school/src/lib/messages/conclusion.ts
  libs/application/templates/secondary-school/src/lib/messages/overview.ts
  libs/application/templates/secondary-school/src/lib/messages/userInformation.ts
  libs/application/templates/secondary-school/src/utils/enums/index.ts
  libs/application/types/src/lib/StateMachine.ts
  libs/application/ui-shell/src/components/ScreenFooter.tsx
  libs/clients/secondary-school/src/clientConfig.json
  libs/clients/secondary-school/src/lib/secondarySchoolClient.service.ts
Labels: automerge, deploy-feature

#17477 feat(new-primary-school): Implement allergies and intolerances page
  libs/application/templates/new-primary-school/jest.config.ts
  libs/application/templates/new-primary-school/src/fields/FriggOptionsAsyncSelectField/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/AllergiesAndIntolerances.tsx
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/allergiesAndIntolerancesSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/index.ts
  libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
Labels: automerge

#17483 fix(my-pages): REVERT "feat(my-pages): Navigation - new mobile menu + tweaks (#17242)"
  apps/portals/my-pages/src/components/Header/Header.css.ts
  apps/portals/my-pages/src/components/Layout/Layout.css.ts
  apps/portals/my-pages/src/components/Layout/NarrowLayout.tsx
  libs/portals/my-pages/core/src/components/Navigation/Navigation.css.ts
  libs/portals/my-pages/core/src/components/Navigation/Navigation.tsx
  libs/portals/my-pages/core/src/index.ts
Labels: automerge, deploy-feature

#17447 fix(ojoi): add use last signatures
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.resolver.ts
  libs/api/domains/official-journal-of-iceland-application/src/lib/ojoiApplication.service.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getInvolvedPartySignatures.input.ts
  libs/api/domains/official-journal-of-iceland-application/src/models/getInvolvedPartySignatures.response.ts
  libs/application/templates/official-journal-of-iceland/src/components/signatures/RegularMember.tsx
  libs/application/templates/official-journal-of-iceland/src/components/tab/LoadingTab.tsx
  libs/application/templates/official-journal-of-iceland/src/fields/Signatures.tsx
  libs/application/templates/official-journal-of-iceland/src/graphql/fragments.ts
  libs/application/templates/official-journal-of-iceland/src/graphql/queries.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useLastSignature.ts
  libs/application/templates/official-journal-of-iceland/src/hooks/useUpdateApplication.ts
  libs/application/templates/official-journal-of-iceland/src/lib/dataSchema.ts
  libs/application/templates/official-journal-of-iceland/src/lib/types.ts
  libs/clients/official-journal-of-iceland/application/src/clientConfig.json
  libs/clients/official-journal-of-iceland/application/src/lib/ojoiApplicationClient.service.ts
Labels: automerge

#17484 fix(application-system): adding defineMEssage to contentful strings
  libs/application/templates/aosh/work-accident-notification/src/lib/messages/information.ts
Labels: automerge

#17277 feat(service-bff): Integrate encryption for session cookies
  apps/services/bff/src/app/modules/auth/auth.controller.spec.ts
  apps/services/bff/src/app/modules/auth/auth.module.ts
  apps/services/bff/src/app/modules/auth/auth.service.ts
  apps/services/bff/src/app/modules/auth/token-refresh.service.spec.ts
  apps/services/bff/src/app/modules/auth/token-refresh.service.ts
  apps/services/bff/src/app/modules/cache/cache.service.spec.ts
  apps/services/bff/src/app/modules/cache/cache.service.ts
  apps/services/bff/src/app/modules/proxy/proxy.controller.spec.ts
  apps/services/bff/src/app/modules/proxy/proxy.module.ts
  apps/services/bff/src/app/modules/proxy/proxy.service.ts
  apps/services/bff/src/app/modules/user/user.controller.spec.ts
  apps/services/bff/src/app/modules/user/user.module.ts
  apps/services/bff/src/app/modules/user/user.service.ts
  apps/services/bff/src/app/services/crypto.service.spec.ts
  apps/services/bff/src/app/services/crypto.service.ts
  apps/services/bff/src/app/services/cryptoKey.service.ts
  apps/services/bff/src/app/services/error.service.ts
  apps/services/bff/src/app/services/sessionCookie.service.spec.ts
  apps/services/bff/src/app/services/sessionCookie.service.ts
  apps/services/bff/test/sharedConstants.ts
Labels: automerge, deploy-feature

#17482 feat(example): alert messages in reference template
  libs/application/templates/reference-template/src/forms/exampleForm/noInputFieldsSection/alertMessageSubsection.ts
  libs/application/templates/reference-template/src/forms/exampleForm/noInputFieldsSection/index.ts
Labels: automerge

#17485 chore(j-s): Unpause revoke indictment
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
Labels: automerge

#17487 fix(marriage-conditions): certificates fix
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
Labels: automerge, high priority

#17490 fix(marriage-conditions): certificates fix (#17487)
  libs/application/templates/marriage-conditions/src/fields/PaymentInfo/index.tsx
Labels: automerge

#17450 feat(new-primary-school): Siblings relation column removal
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.service.ts
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Siblings.tsx
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/siblingsSubSection.ts
  libs/application/templates/new-primary-school/src/lib/constants.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
  libs/application/templates/new-primary-school/src/types.ts
Labels: automerge, deploy-feature

#17468 chore(j-s): add slack lock for daily court hearing arrangements
  apps/judicial-system/backend/src/app/modules/case/internalCase.controller.ts
  apps/judicial-system/backend/src/app/modules/case/internalCase.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.controller.ts
  apps/judicial-system/backend/src/app/modules/event/event.service.ts
  apps/judicial-system/scheduler/src/app/app.service.ts
  apps/judicial-system/scheduler/src/app/test/run.spec.ts
Labels: automerge

#17498 fix(web): Service web contact banner for Digital Iceland #17493
  apps/web/screens/ServiceWeb/utils/index.ts
Labels: automerge

#17493 fix(web): Service web contact banner for Digital Iceland
  apps/web/screens/ServiceWeb/utils/index.ts
Labels: automerge

#17497 fix(web): Hotfix, Service web - FormProvider moved to top of component #17495
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
Labels: automerge

#17499 fix(skilavottord): Route to add pages are forbidden
  apps/skilavottord/web/auth/utils.ts
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
Labels: automerge

#17495 fix(web): Service web - FormProvider moved to top of component
  apps/web/components/ServiceWeb/Forms/StandardForm/StandardForm.tsx
Labels: automerge

#17489 fix(my-pages): User Info Line UI
  libs/portals/my-pages/core/src/components/InfoLine/InfoLine.tsx
  libs/portals/my-pages/health/src/screens/HealthCenter/HealthCenter.tsx
Labels: automerge

#17502 chore(my-pages): Slugify document names
  apps/download-service/src/app/modules/documents/document.controller.ts
Labels: automerge

#17505 fix(my-pages): user-profile form context settings
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Phone.tsx
Labels: automerge

#17501 fix(j-s): Indictment description
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/Defendant.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Defendant/PoliceCaseInfo/PoliceCaseInfo.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.strings.ts
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Indictment/IndictmentCount.tsx
Labels: automerge

#17508 fix(my-pages): hotfix - my pages docs and settings
  apps/download-service/src/app/modules/documents/document.controller.ts
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/BankInfoForm.tsx
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Email.tsx
  libs/portals/my-pages/information/src/components/PersonalInformation/Forms/ProfileForm/components/Inputs/Phone.tsx
Labels: automerge

#17511 fix(shared): InputController relies on FormContext being provided
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#17512 fix(shared): Hotfix - InputController relies on FormContext being provided (#17511)
  libs/shared/form-fields/src/lib/InputController/InputController.tsx
Labels: automerge

#17506 feat(app-sys): markdown labels for checkboxes and radio
  libs/application/ui-fields/src/lib/CheckboxFormField/CheckboxFormField.tsx
  libs/application/ui-fields/src/lib/RadioFormField/RadioFormField.tsx
Labels: automerge

#17520 fix(skilavottord): Rollback debug
  apps/skilavottord/web/auth/utils.ts
  apps/skilavottord/ws/src/app/modules/auth/auth.guard.ts
Labels: automerge

#17521 fix(marriage-conditions): fix for hasElectronicID response check
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#17346 feat(native-app): Barcode fixes
  apps/native/app/src/assets/icons/refresh.png
  apps/native/app/src/assets/icons/refresh@2x.png
  apps/native/app/src/assets/icons/refresh@3x.png
  apps/native/app/src/graphql/fragments/license.fragment.graphql
  apps/native/app/src/graphql/queries/licenses.graphql
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/screens/home/licenses-module.tsx
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/screens/wallet/components/wallet-item.tsx
  apps/native/app/src/screens/wallet/wallet.tsx
  apps/native/app/src/ui/assets/card/p-card.png
  apps/native/app/src/ui/assets/card/p-card@2x.png
  apps/native/app/src/ui/assets/card/p-card@3x.png
  apps/native/app/src/ui/index.ts
  apps/native/app/src/ui/lib/card/license-card.tsx
  apps/native/app/src/ui/lib/card/license-list-card.tsx
Labels: automerge, autoupdate

#17524 fix(marriage): hotfix/marriage electronicid
  libs/clients/syslumenn/src/lib/syslumennClient.service.ts
Labels: automerge

#17515 fix(j-s): update info section components
  apps/judicial-system/web/src/routes/Court/components/ReceptionAndAssignment/ReceptionAndAssignment.tsx
Labels: automerge

#17471 chore(j-s): Rewrites Input Advocate
  apps/judicial-system/web/src/components/DefenderInfo/DefenderInfo.tsx
  apps/judicial-system/web/src/components/Inputs/Input.strings.ts
  apps/judicial-system/web/src/components/Inputs/InputAdvocate.strings.ts
  apps/judicial-system/web/src/components/Inputs/InputAdvocate.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectCivilClaimantAdvocate.tsx
  apps/judicial-system/web/src/routes/Court/Indictments/Advocates/SelectDefender.tsx
  apps/judicial-system/web/src/routes/Prosecutor/Indictments/Processing/Processing.tsx
  apps/judicial-system/web/src/utils/formatters.ts
  apps/judicial-system/web/src/utils/utils.spec.tsx
  libs/judicial-system/types/src/index.ts
  libs/judicial-system/types/src/lib/lawyer.ts
Labels: automerge

#17507 feat(j-s): Add a mergeCaseNumber field to case table
  apps/judicial-system/api/src/app/modules/case/dto/updateCase.input.ts
  apps/judicial-system/api/src/app/modules/case/models/case.model.ts
  apps/judicial-system/backend/migrations/20250115095654-update-case.js
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/dto/updateCase.dto.ts
  apps/judicial-system/backend/src/app/modules/case/guards/rolesRules.ts
  apps/judicial-system/backend/src/app/modules/case/models/case.model.ts
  apps/judicial-system/web/src/components/FormProvider/case.graphql
  apps/judicial-system/web/src/utils/hooks/useCase/updateCase.graphql
Labels: automerge

#16499 fix: minor spelling error
  apps/native/app/src/messages/is.ts
  libs/application/templates/family-matters/children-residence-change-v2/src/lib/messages/childSupportPayments.ts
Labels: automerge, high priority

#17525 feat(application-system): Add dependent loading to async select
  libs/application/core/src/lib/fieldBuilders.ts
  libs/application/templates/reference-template/src/forms/exampleForm/simpleInputsSection/asyncSelectSubsection.ts
  libs/application/types/src/lib/Fields.ts
  libs/application/ui-fields/src/lib/AsyncSelectFormField/AsyncSelectFormField.tsx
  libs/shared/form-fields/src/lib/SelectController/SelectController.tsx
  libs/shared/utils/src/lib/clearInputsOnChange.spec.ts
  libs/shared/utils/src/lib/clearInputsOnChange.ts
Labels: automerge

#17466 feat(new-primary-school): Contacts page
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
  libs/application/templates/new-primary-school/src/fields/ContactsTableRepeater/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Contacts.tsx
  libs/application/templates/new-primary-school/src/fields/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/contactsSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/relativesSubSection.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
  libs/application/templates/new-primary-school/src/types.ts
Labels: automerge

#17535 feat(old-age-pension): add text and remove additional docs page
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
Labels: automerge

#17517 fix(island-ui): Add isClearable option to Select component
  libs/application/templates/aosh/work-accident-notification/src/fields/Components/MultiSelectDropdown.tsx
  libs/island-ui/core/src/lib/Select/Components/index.tsx
  libs/island-ui/core/src/lib/Select/Select.tsx
Labels: automerge

#17486 fix(application-system): Fixing error messages for certain types of machines
  libs/application/template-api-modules/src/lib/modules/templates/aosh/street-registration/street-registration.service.ts
  libs/application/templates/aosh/register-new-machine/src/index.ts
  libs/application/templates/aosh/street-registration/src/dataProviders/index.ts
  libs/application/templates/aosh/street-registration/src/forms/StreetRegistrationForm/InformationSection/pickMachineSubSection.ts
  libs/application/templates/aosh/street-registration/src/forms/StreetRegistrationForm/prerequisitesSection.ts
  libs/application/templates/aosh/street-registration/src/index.ts
  libs/application/templates/aosh/street-registration/src/lib/StreetRegistrationTemplate.ts
  libs/application/templates/aosh/street-registration/src/lib/dataSchema.ts
  libs/application/templates/aosh/street-registration/src/lib/messages/applicationCheck.ts
  libs/application/templates/aosh/street-registration/src/lib/messages/error.ts
  libs/application/templates/aosh/street-registration/src/lib/messages/information.ts
  libs/application/templates/aosh/street-registration/src/utils/getSelectedMachine.ts
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.tsx
  libs/application/ui-fields/src/lib/FindVehicleFormField/FindVehicleFormField.util.ts
  libs/clients/work-machines/src/lib/workMachines.service.ts
Labels: automerge

#17420 chore(j-s): Move DefenderCasesTable to new table component
  apps/judicial-system/web/src/components/ContextMenu/ContextMenuOptions/WithdrawAppealMenuOption.tsx
  apps/judicial-system/web/src/components/PageTitle/PageTitle.tsx
  apps/judicial-system/web/src/components/Table/PastCasesTable/PastCasesTable.tsx
  apps/judicial-system/web/src/components/Tags/TagAppealState/TagAppealState.tsx
  apps/judicial-system/web/src/components/Tags/TagCaseState/TagCaseState.spec.ts
  apps/judicial-system/web/src/components/Tags/TagCaseState/TagCaseState.strings.ts
  apps/judicial-system/web/src/components/Tags/TagCaseState/TagCaseState.tsx
  apps/judicial-system/web/src/components/Tags/TagContainer/TagContainer.tsx
  apps/judicial-system/web/src/components/index.ts
  apps/judicial-system/web/src/routes/Defender/Cases/Cases.tsx
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.css.ts
  apps/judicial-system/web/src/routes/Defender/Cases/components/DefenderCasesTable.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesAwaitingReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesForReview.tsx
  apps/judicial-system/web/src/routes/PublicProsecutor/Tables/CasesReviewed.tsx
  apps/judicial-system/web/src/routes/Shared/Cases/PrisonCases.tsx
Labels: automerge

#17413 feat(j-s): Order case files in descending created order
  apps/judicial-system/backend/src/app/modules/case/case.service.ts
  apps/judicial-system/backend/src/app/modules/case/limitedAccessCase.service.ts
  apps/judicial-system/web/src/components/Table/CaseFileTable/CaseFileTable.tsx
Labels: automerge

#17434 chore(j-s): Use lawyer registry from api
  apps/judicial-system/web/messages/Core/errors.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyer/getLawyer.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyer/index.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyers/getLawyers.ts
  apps/judicial-system/web/pages/api/lawyers/getLawyers/index.ts
  apps/judicial-system/web/src/utils/hooks/useLawyers/useLawyers.ts
Labels: automerge

#17540 feat(old-age-pension): Change text and remove screen
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/OldAgePensionForm.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/forms/Prerequisites.ts
  libs/application/templates/social-insurance-administration/old-age-pension/src/lib/messages.ts
Labels: automerge

#17428 feat(web): Overview links - two column category card view
  apps/web/components/Organization/Slice/OverviewLinks/OverviewLinks.tsx
  apps/web/screens/queries/fragments.ts
  libs/cms/src/lib/generated/contentfulTypes.d.ts
  libs/cms/src/lib/models/overviewLinks.model.ts
Labels: automerge

#17526 chore(j-s): Court Upload Changes
  apps/judicial-system/backend/src/app/modules/file/file.service.ts
  apps/judicial-system/backend/src/app/modules/file/test/fileController/uploadCaseFileToCourt.spec.ts
  apps/judicial-system/backend/src/app/modules/file/test/internalFileController/deliverCaseFileToCourt.spec.ts
Labels: automerge

#17451 feat(new-primary-school): Current school page
  libs/application/templates/new-primary-school/src/fields/Grade/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/CurrentSchool.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/School.tsx
  libs/application/templates/new-primary-school/src/fields/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/childrenNParentsSection/childInfoSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/currentSchoolSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/index.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
Labels: automerge

#17529 fix(marriage-conditions): side2 info screen for birth certificate
  libs/application/templates/marriage-conditions/src/forms/spouseConfirmation.ts
  libs/application/templates/marriage-conditions/src/lib/dataSchema.ts
Labels: automerge

#17543 fix: circular dependencies in app
  apps/native/app/src/screens/wallet-pass/wallet-pass.constants.ts
  apps/native/app/src/screens/wallet-pass/wallet-pass.tsx
  apps/native/app/src/ui/lib/card/license-card.tsx
Labels: autoupdate

#17550 fix(shared): Change type generics for sortAlpha utility function
  apps/web/components/OfficialJournalOfIceland/OJOIUtils.ts
  libs/shared/utils/src/lib/sortAlpha.ts
Labels: autoupdate

#17510 refactor(my-pages): replace filter with UI core filter
  libs/portals/my-pages/assets/src/screens/WorkMachinesOverview/WorkMachinesOverview.tsx
  libs/portals/my-pages/core/src/components/Filter/Filter.css.ts
  libs/portals/my-pages/core/src/components/Filter/Filter.tsx
  libs/portals/my-pages/core/src/index.ts
  libs/portals/my-pages/documents/src/components/DocumentFilter/DocumentsFilterV2.tsx
  libs/portals/my-pages/finance/src/components/DocumentScreen/DocumentScreen.tsx
  libs/portals/my-pages/finance/src/components/FinanceTransactionPeriods/FinanceTransactionPeriodsFilter.tsx
  libs/portals/my-pages/finance/src/components/HousingBenefitsPayments/HousingBenefitsFilter.tsx
  libs/portals/my-pages/finance/src/screens/FinanceLoans/FinanceLoans.tsx
  libs/portals/my-pages/finance/src/screens/FinanceTransactions/FinanceTransactions.tsx
Labels: deprecated:automerge

#17531 chore(CI): Refactor Dockerfile
  scripts/ci/Dockerfile
Labels: deploy-feature, test everything

#17563 fix(app): responsiveness of passkeys app screen
  apps/native/app/src/screens/passkey/passkey.tsx
Labels: autoupdate

#17432 chore(ci): Better local running
  .github/actions/get-cache/action.yml
  .github/workflows/pullrequest.yml
  scripts/ci/00_prepare-base-tags.sh
  scripts/ci/cache/__config.mjs
Labels: deprecated:automerge, deploy-feature, test everything

#17593 fix(application-system): Add support for forwarding query params through DelegationsScreen
  libs/application/ui-shell/src/components/DelegationsScreen.tsx
Labels: deploy-feature

#17166 fix(infra): Support windows `spawn`ing
  infra/src/cli/render-local-mocks.ts
  infra/src/common.ts
Labels: deprecated:automerge

#17538 feat(ci): Run `lint --fix` with dirtybot
  .github/workflows/pullrequest.yml
  infra/scripts/ci/git-check-dirty.sh
Labels: dirty bypass

#17581 ci: increase parallelism
  .github/workflows/dd-metrics.yml
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
  scripts/ci/_chunk.js
  scripts/ci/_common.sh
  scripts/ci/run-affected-in-parallel.sh
  scripts/ci/run-in-parallel-native.sh
  scripts/ci/run-in-parallel.sh
  scripts/codegen.js
Labels: test everything

#17617 revert: "feat(ci): Run `lint --fix` with dirtybot (#17538)"
  .github/workflows/pullrequest.yml
  infra/scripts/ci/git-check-dirty.sh
Labels: dirty bypass

#17536 feat(system-e2e): Add test for admin delegations
  apps/system-e2e/src/tests/islandis/admin-portal/smoke/admin-delegations.spec.ts
  libs/portals/admin/delegation-admin/src/screens/Root.tsx
Labels: autoupdate

#17541 feat(license-service): Barcode session
  apps/services/license-api/src/app/modules/license/test/license.service.spec.ts
  libs/api/domains/license-service/src/lib/licenseService.service.ts
  libs/auth-nest-tools/src/lib/auth.ts
  libs/auth-nest-tools/src/lib/current-actor.decorator.ts
  libs/auth-nest-tools/src/lib/jwt.payload.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.spec.ts
  libs/auth-nest-tools/src/lib/jwt.strategy.ts
  libs/services/license/src/index.ts
  libs/services/license/src/lib/barcode.service.ts
  libs/services/license/src/lib/license.config.ts
  libs/shared/problem/src/Problem.ts
  libs/shared/problem/src/ProblemType.ts
  libs/shared/problem/src/problems.ts
Labels: deploy-feature

#17556 feat(new-primary-school): Add temporary application type and remove "Moving abroad"
  libs/api/domains/auth-admin/src/lib/client/clients.service.spec.ts
  libs/application/template-api-modules/src/lib/modules/templates/new-primary-school/new-primary-school.utils.ts
  libs/application/templates/new-primary-school/src/fields/Review/index.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Child.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Contacts.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/CurrentSchool.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Languages.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Parents.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/ReasonForApplication.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/School.tsx
  libs/application/templates/new-primary-school/src/fields/Review/review-groups/Siblings.tsx
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/allergiesAndIntolerancesSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/differentNeedsSection/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/currentSchoolSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/index.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/newSchoolSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/reasonForApplicationSubSection.ts
  libs/application/templates/new-primary-school/src/forms/NewPrimarySchoolForm/primarySchoolSection/startingSchoolSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/applicationTypeSubSection.ts
  libs/application/templates/new-primary-school/src/forms/Prerequisites/index.ts
  libs/application/templates/new-primary-school/src/lib/NewPrimarySchoolTemplate.ts
  libs/application/templates/new-primary-school/src/lib/constants.ts
  libs/application/templates/new-primary-school/src/lib/dataSchema.ts
  libs/application/templates/new-primary-school/src/lib/messages.ts
  libs/application/templates/new-primary-school/src/lib/newPrimarySchoolUtils.ts
Labels: autoupdate

#17565 fix(app): disable milage registration if user isn't allowed
  apps/native/app/src/screens/vehicles/vehicle-mileage.screen.tsx
Labels: autoupdate

#17568 feat(app): simplify token refresh logic app
  apps/native/app/src/graphql/client.ts
  apps/native/app/src/messages/en.ts
  apps/native/app/src/messages/is.ts
  apps/native/app/src/stores/auth-store.ts
  apps/native/app/src/utils/deduplicatePromise.ts
Labels: autoupdate

#17682 fix: use ec2-runners for tests
  .github/workflows/pullrequest.yml
  .github/workflows/push.yml
Labels: test everything

#17618 chore: `lint --fix`
  apps/auth-admin-web/components/Admin/nav/AdminTabNav.tsx
  apps/auth-admin-web/components/Client/nav/ClientTabNav.tsx
  apps/contentful-apps/components/Layout.tsx
  apps/contentful-apps/components/LocalhostWarning.tsx
  apps/contentful-apps/components/MideindTranslationSidebar/fieldUtils/index.tsx
  apps/contentful-apps/pages/fields/active-translations-field.tsx
  apps/contentful-apps/pages/fields/admin-only-json-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-checkbox-list-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-dropdown-field.tsx
  apps/contentful-apps/pages/fields/admin-only-short-text-field.tsx
  apps/contentful-apps/pages/fields/admin-only-single-reference-field.tsx
  apps/contentful-apps/pages/fields/article-related-articles-field.tsx
  apps/contentful-apps/pages/fields/article-subarticles-field.tsx
  apps/contentful-apps/pages/fields/content-type-notifications-field.tsx
  apps/contentful-apps/pages/fields/embed-link-field.tsx
  apps/contentful-apps/pages/fields/form-default-namespace-field.tsx
  apps/contentful-apps/pages/fields/formatted-location-input-field.tsx
  apps/contentful-apps/pages/fields/publish-date-field.tsx
  apps/contentful-apps/pages/fields/theme-properties-field.tsx
  apps/contentful-apps/pages/fields/time-duration-field.tsx
  apps/contentful-apps/pages/fields/vacancy-contacts-field.tsx
  apps/financial-aid/backend/src/app/modules/staff/test/numberOfUsersForMunicipality.spec.ts
  apps/skilavottord/web/screens/Overview/components/ActionCard/ActionCard.tsx
  apps/skilavottord/ws/src/app/modules/samgongustofa/samgongustofa.service.ts
  apps/tools/contentful-role-permissions/utils/index.ts
  apps/web/screens/PetitionView/PetitionView.tsx
  libs/api/domains/directorate-of-labour/src/lib/parentalLeavePregnancyStatus.model.ts
  libs/api/domains/disability-license/src/lib/disability-license.resolver.ts
  libs/application/templates/financial-aid/src/fields/TaxReturnFilesForm/taxFormContent.tsx
  libs/application/templates/financial-aid/src/lib/hooks/useFileUpload.ts
  libs/infra-express-server/src/lib/infra-express-server.ts
  libs/infra-nest-server/src/lib/httpRequestDurationMiddleware.ts
  libs/island-ui/contentful/src/lib/IframeModal/IframeModal.tsx
  libs/island-ui/core/src/lib/DatePicker/DatePicker.stories.tsx
  libs/island-ui/core/src/lib/ModalBase/ModalBase.tsx
  libs/island-ui/core/src/lib/VisuallyHidden/VisuallyHidden.tsx
  libs/portals/admin/ids-admin/src/hooks/useDynamicShadow.tsx
  libs/portals/admin/ids-admin/src/screens/Client/EditClient.tsx
  libs/portals/shared-modules/delegations/src/hooks/useDynamicShadow.tsx
  libs/shared/types/src/lib/shorthash.d.ts
Labels: test everything

#17446 fix(dd): allowed tracing urls
  libs/user-monitoring/src/lib/user-monitoring.ts
  package.json
  yarn.lock
Labels: deprecated:automerge

#17731 feat(fa): Updating tax info according to 2025
  libs/financial-aid/shared/src/lib/taxCalculator.spec.ts
  libs/financial-aid/shared/src/lib/taxCalculator.ts
Labels: high priority

#17708 chore(license-api): Remove unused assets build config
  apps/services/license-api/project.json
Labels: deploy-feature
